### ISSUE TITLE
The Log needs to show the elapsed time for each upscale process.

### ISSUE THREAD

**Issue by demianill** [upscayl/upscayl#1002]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

I would like to know how many minutes it took to upscale, for example, the file _image0001.jpg_.

### Related Problem(s)

I couldn't find any information in the log about the processing time used for each image. For example, I would like to know how many minutes it took to upscale the file _image0001.jpg_.

This could be particularly useful to help choose the best upscaling method. That way I could test the same image with the various methods and compare their execution times. For batch processing, choosing the best method based on time can be crucial.

### Alternatives

The log could contain a timestamp showing the time at the beginning of the processing, then show the time at the end of the processing, and of course also show, for example, "_elapsed time: 17min56sec_"

**Comment by aaronliu0130** [comment]
interesting idea

**Comment by barf** [comment]
The timestamps are logged already, from the log or console output you can find the difference between 0% and 100% already, if that helps.

**Comment by demianill** [comment]
_> The timestamps are logged already, from the log or console output you can find the difference between 0% and 100% already, if that helps._




Dear Barf, please, show me where is the timestamp.

As you can see below, it is a complete log of one upscale process, from the beginnin to the end.
There is no date or time information.

===================================



🎯 GET_MODELS_LIST:  /Users/andre/Downloads/custom-models-main/models
🎒 BACKEND REPORTED:  📁 Updating Custom Models Folder Path:  /Users/andre/Downloads/custom-models-main/models
🎒 BACKEND REPORTED:  📁 Custom Models Folder Path:  /Users/andre/Downloads/custom-models-main/models
🎒 BACKEND REPORTED:  🔎 Detected Custom Models:  4xHFA2k,4xLSDIR,4xLSDIRCompactC3,4xLSDIRplusC,4xNomos8kSC,4x_NMKD-Siax_200k,4x_NMKD-Superscale-SP_178000_G,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,uniscale_restore,unknown-2.0.1
📜 CUSTOM_MODEL_FILES_LIST:  4xHFA2k,4xLSDIR,4xLSDIRCompactC3,4xLSDIRplusC,4xNomos8kSC,4x_NMKD-Siax_200k,4x_NMKD-Superscale-SP_178000_G,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,uniscale_restore,unknown-2.0.1
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"RealESRGAN_General_WDN_x4_v3","value":"RealESRGAN_General_WDN_x4_v3"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to RealESRGAN_General_WDN_x4_v3
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"RealESRGAN_General_WDN_x4_v3","value":"RealESRGAN_General_WDN_x4_v3"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"RealESRGAN_General_WDN_x4_v3","value":"RealESRGAN_General_WDN_x4_v3"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to RealESRGAN_General_WDN_x4_v3
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  /Users/andre/Desktop/aliens/file0001.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  /Users/andre/Desktop/aliens/file0001.jpg
🖼 Selected Image Path:  /Users/andre/Desktop/aliens/file0001.jpg
📁 Selected Image Directory:  /Users/andre/Desktop/aliens
🖼 imagePath:  /Users/andre/Desktop/aliens/file0001.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"RealESRGAN_General_WDN_x4_v3","gpuId":null,"saveImageAs":"jpg","inputDir":"/Users/andre/Desktop/aliens","fileNameWithExt":"file0001.jpg","outputDir":"/Users/andre/Desktop/aliens","outFile":"/Users/andre/Desktop/aliens/file0001_upscayl_3x_RealESRGAN_General_WDN_x4_v3.jpg","fileName":"file0001","scale":"3","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,/Users/andre/Desktop/aliens/file0001.jpg,-o,/Users/andre/Desktop/aliens/file0001_upscayl_3x_RealESRGAN_General_WDN_x4_v3.jpg,-s,3,-m,/Users/andre/Downloads/custom-models-main/models,-n,RealESRGAN_General_WDN_x4_v3,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"/Applications/Upscayl.app/Contents/Resources/bin/upscayl-bin","args":["/Applications/Upscayl.app/Contents/Resources/bin/upscayl-bin","-i","/Users/andre/Desktop/aliens/file0001.jpg","-o","/Users/andre/Desktop/aliens/file0001_upscayl_3x_RealESRGAN_General_WDN_x4_v3.jpg","-s","3","-m","/Users/andre/Downloads/custom-models-main/models","-n","RealESRGAN_General_WDN_x4_v3","-f","jpg","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  🚀 Starting Upscayl - Copyright © 2024
✨ Detected scale x4
✨ Using the default scale x4

🚧 UPSCAYL_PROGRESS:  🚀 Starting Upscayl - Copyright © 2024
✨ Detected scale x4
✨ Using the default scale x4

🎒 BACKEND REPORTED:  [0 AMD Radeon Pro 5500M]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 AMD Radeon Pro 5500M]  bugsbn1=0  bugbilz=3  bugcopc=0  bugihfa=0
[0 AMD Radeon Pro 5500M]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon Pro 5500M]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
[1 Intel(R) UHD Graphics 630]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) UHD Graphics 630]  bugsbn1=0  bugbilz=19  bugcopc=0  bugihfa=0
[1 Intel(R) UHD Graphics 630]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) UHD Graphics 630]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 AMD Radeon Pro 5500M]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 AMD Radeon Pro 5500M]  bugsbn1=0  bugbilz=3  bugcopc=0  bugihfa=0
[0 AMD Radeon Pro 5500M]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon Pro 5500M]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
[1 Intel(R) UHD Graphics 630]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) UHD Graphics 630]  bugsbn1=0  bugbilz=19  bugcopc=0  bugihfa=0
[1 Intel(R) UHD Graphics 630]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) UHD Graphics 630]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🎒 BACKEND REPORTED:  0.93%

🚧 UPSCAYL_PROGRESS:  0.93%

🎒 BACKEND REPORTED:  1.85%

🚧 UPSCAYL_PROGRESS:  1.85%

🎒 BACKEND REPORTED:  2.78%

🚧 UPSCAYL_PROGRESS:  2.78%

🎒 BACKEND REPORTED:  3.70%

🚧 UPSCAYL_PROGRESS:  3.70%

🎒 BACKEND REPORTED:  4.63%

🚧 UPSCAYL_PROGRESS:  4.63%

🎒 BACKEND REPORTED:  5.56%

🚧 UPSCAYL_PROGRESS:  5.56%

🎒 BACKEND REPORTED:  6.48%

🚧 UPSCAYL_PROGRESS:  6.48%

🎒 BACKEND REPORTED:  7.41%

🚧 UPSCAYL_PROGRESS:  7.41%

🎒 BACKEND REPORTED:  8.33%

🚧 UPSCAYL_PROGRESS:  8.33%

🎒 BACKEND REPORTED:  9.26%

🚧 UPSCAYL_PROGRESS:  9.26%

🎒 BACKEND REPORTED:  10.19%

🚧 UPSCAYL_PROGRESS:  10.19%

🎒 BACKEND REPORTED:  11.11%

🚧 UPSCAYL_PROGRESS:  11.11%

🎒 BACKEND REPORTED:  12.04%

🚧 UPSCAYL_PROGRESS:  12.04%

🎒 BACKEND REPORTED:  12.96%

🚧 UPSCAYL_PROGRESS:  12.96%

🎒 BACKEND REPORTED:  13.89%

🚧 UPSCAYL_PROGRESS:  13.89%

🎒 BACKEND REPORTED:  14.81%

🚧 UPSCAYL_PROGRESS:  14.81%

🎒 BACKEND REPORTED:  15.74%

🚧 UPSCAYL_PROGRESS:  15.74%

🎒 BACKEND REPORTED:  16.67%

🚧 UPSCAYL_PROGRESS:  16.67%

🎒 BACKEND REPORTED:  17.59%

🚧 UPSCAYL_PROGRESS:  17.59%

🎒 BACKEND REPORTED:  18.52%

🚧 UPSCAYL_PROGRESS:  18.52%

🎒 BACKEND REPORTED:  19.44%

🚧 UPSCAYL_PROGRESS:  19.44%

🎒 BACKEND REPORTED:  20.37%

🚧 UPSCAYL_PROGRESS:  20.37%

🎒 BACKEND REPORTED:  21.30%

🚧 UPSCAYL_PROGRESS:  21.30%

🎒 BACKEND REPORTED:  22.22%

🚧 UPSCAYL_PROGRESS:  22.22%

🎒 BACKEND REPORTED:  23.15%

🚧 UPSCAYL_PROGRESS:  23.15%

🎒 BACKEND REPORTED:  24.07%

🚧 UPSCAYL_PROGRESS:  24.07%

🎒 BACKEND REPORTED:  25.00%

🚧 UPSCAYL_PROGRESS:  25.00%

🎒 BACKEND REPORTED:  25.93%

🚧 UPSCAYL_PROGRESS:  25.93%

🎒 BACKEND REPORTED:  26.85%

🚧 UPSCAYL_PROGRESS:  26.85%

🎒 BACKEND REPORTED:  27.78%

🚧 UPSCAYL_PROGRESS:  27.78%

🎒 BACKEND REPORTED:  28.70%

🚧 UPSCAYL_PROGRESS:  28.70%

🎒 BACKEND REPORTED:  29.63%

🚧 UPSCAYL_PROGRESS:  29.63%

🎒 BACKEND REPORTED:  30.56%

🚧 UPSCAYL_PROGRESS:  30.56%

🎒 BACKEND REPORTED:  31.48%

🚧 UPSCAYL_PROGRESS:  31.48%

🎒 BACKEND REPORTED:  32.41%

🚧 UPSCAYL_PROGRESS:  32.41%

🎒 BACKEND REPORTED:  33.33%

🚧 UPSCAYL_PROGRESS:  33.33%

🎒 BACKEND REPORTED:  34.26%

🚧 UPSCAYL_PROGRESS:  34.26%

🎒 BACKEND REPORTED:  35.19%

🚧 UPSCAYL_PROGRESS:  35.19%

🎒 BACKEND REPORTED:  36.11%

🚧 UPSCAYL_PROGRESS:  36.11%

🎒 BACKEND REPORTED:  37.04%

🚧 UPSCAYL_PROGRESS:  37.04%

🎒 BACKEND REPORTED:  37.96%

🚧 UPSCAYL_PROGRESS:  37.96%

🎒 BACKEND REPORTED:  38.89%

🚧 UPSCAYL_PROGRESS:  38.89%

🎒 BACKEND REPORTED:  39.81%

🚧 UPSCAYL_PROGRESS:  39.81%

🎒 BACKEND REPORTED:  40.74%

🚧 UPSCAYL_PROGRESS:  40.74%

🎒 BACKEND REPORTED:  41.67%

🚧 UPSCAYL_PROGRESS:  41.67%

🎒 BACKEND REPORTED:  42.59%

🚧 UPSCAYL_PROGRESS:  42.59%

🎒 BACKEND REPORTED:  43.52%

🚧 UPSCAYL_PROGRESS:  43.52%

🎒 BACKEND REPORTED:  44.44%

🚧 UPSCAYL_PROGRESS:  44.44%

🎒 BACKEND REPORTED:  45.37%

🚧 UPSCAYL_PROGRESS:  45.37%

🎒 BACKEND REPORTED:  46.30%

🚧 UPSCAYL_PROGRESS:  46.30%

🎒 BACKEND REPORTED:  47.22%

🚧 UPSCAYL_PROGRESS:  47.22%

🎒 BACKEND REPORTED:  48.15%

🚧 UPSCAYL_PROGRESS:  48.15%

🎒 BACKEND REPORTED:  49.07%

🚧 UPSCAYL_PROGRESS:  49.07%

🎒 BACKEND REPORTED:  50.00%

🚧 UPSCAYL_PROGRESS:  50.00%

🎒 BACKEND REPORTED:  50.93%

🚧 UPSCAYL_PROGRESS:  50.93%

🎒 BACKEND REPORTED:  51.85%

🚧 UPSCAYL_PROGRESS:  51.85%

🎒 BACKEND REPORTED:  52.78%

🚧 UPSCAYL_PROGRESS:  52.78%

🎒 BACKEND REPORTED:  53.70%

🚧 UPSCAYL_PROGRESS:  53.70%

🎒 BACKEND REPORTED:  54.63%

🚧 UPSCAYL_PROGRESS:  54.63%

🎒 BACKEND REPORTED:  55.56%

🚧 UPSCAYL_PROGRESS:  55.56%

🎒 BACKEND REPORTED:  56.48%

🚧 UPSCAYL_PROGRESS:  56.48%

🎒 BACKEND REPORTED:  57.41%

🚧 UPSCAYL_PROGRESS:  57.41%

🎒 BACKEND REPORTED:  58.33%

🚧 UPSCAYL_PROGRESS:  58.33%

🎒 BACKEND REPORTED:  59.26%

🚧 UPSCAYL_PROGRESS:  59.26%

🎒 BACKEND REPORTED:  60.19%

🚧 UPSCAYL_PROGRESS:  60.19%

🎒 BACKEND REPORTED:  61.11%

🚧 UPSCAYL_PROGRESS:  61.11%

🎒 BACKEND REPORTED:  62.04%

🚧 UPSCAYL_PROGRESS:  62.04%

🎒 BACKEND REPORTED:  62.96%

🚧 UPSCAYL_PROGRESS:  62.96%

🎒 BACKEND REPORTED:  63.89%

🚧 UPSCAYL_PROGRESS:  63.89%

🎒 BACKEND REPORTED:  64.81%

🚧 UPSCAYL_PROGRESS:  64.81%

🎒 BACKEND REPORTED:  65.74%

🚧 UPSCAYL_PROGRESS:  65.74%

🎒 BACKEND REPORTED:  66.67%

🚧 UPSCAYL_PROGRESS:  66.67%

🎒 BACKEND REPORTED:  67.59%

🚧 UPSCAYL_PROGRESS:  67.59%

🎒 BACKEND REPORTED:  68.52%

🚧 UPSCAYL_PROGRESS:  68.52%

🎒 BACKEND REPORTED:  69.44%

🚧 UPSCAYL_PROGRESS:  69.44%

🎒 BACKEND REPORTED:  70.37%

🚧 UPSCAYL_PROGRESS:  70.37%

🎒 BACKEND REPORTED:  71.30%

🚧 UPSCAYL_PROGRESS:  71.30%

🎒 BACKEND REPORTED:  72.22%

🚧 UPSCAYL_PROGRESS:  72.22%

🎒 BACKEND REPORTED:  73.15%

🚧 UPSCAYL_PROGRESS:  73.15%

🎒 BACKEND REPORTED:  74.07%

🚧 UPSCAYL_PROGRESS:  74.07%

🎒 BACKEND REPORTED:  75.00%

🚧 UPSCAYL_PROGRESS:  75.00%

🎒 BACKEND REPORTED:  75.93%

🚧 UPSCAYL_PROGRESS:  75.93%

🎒 BACKEND REPORTED:  76.85%

🚧 UPSCAYL_PROGRESS:  76.85%

🎒 BACKEND REPORTED:  77.78%

🚧 UPSCAYL_PROGRESS:  77.78%

🎒 BACKEND REPORTED:  78.70%

🚧 UPSCAYL_PROGRESS:  78.70%

🎒 BACKEND REPORTED:  79.63%

🚧 UPSCAYL_PROGRESS:  79.63%

🎒 BACKEND REPORTED:  80.56%

🚧 UPSCAYL_PROGRESS:  80.56%

🎒 BACKEND REPORTED:  81.48%

🚧 UPSCAYL_PROGRESS:  81.48%

🎒 BACKEND REPORTED:  82.41%

🚧 UPSCAYL_PROGRESS:  82.41%

🎒 BACKEND REPORTED:  83.33%

🚧 UPSCAYL_PROGRESS:  83.33%

🎒 BACKEND REPORTED:  84.26%

🚧 UPSCAYL_PROGRESS:  84.26%

🎒 BACKEND REPORTED:  85.19%

🚧 UPSCAYL_PROGRESS:  85.19%

🎒 BACKEND REPORTED:  86.11%

🚧 UPSCAYL_PROGRESS:  86.11%

🎒 BACKEND REPORTED:  87.04%

🚧 UPSCAYL_PROGRESS:  87.04%

🎒 BACKEND REPORTED:  87.96%

🚧 UPSCAYL_PROGRESS:  87.96%

🎒 BACKEND REPORTED:  88.89%

🚧 UPSCAYL_PROGRESS:  88.89%

🎒 BACKEND REPORTED:  89.81%

🚧 UPSCAYL_PROGRESS:  89.81%

🎒 BACKEND REPORTED:  90.74%

🚧 UPSCAYL_PROGRESS:  90.74%

🎒 BACKEND REPORTED:  91.67%

🚧 UPSCAYL_PROGRESS:  91.67%

🎒 BACKEND REPORTED:  92.59%

🚧 UPSCAYL_PROGRESS:  92.59%

🎒 BACKEND REPORTED:  93.52%

🚧 UPSCAYL_PROGRESS:  93.52%

🎒 BACKEND REPORTED:  94.44%

🚧 UPSCAYL_PROGRESS:  94.44%

🎒 BACKEND REPORTED:  95.37%

🚧 UPSCAYL_PROGRESS:  95.37%

🎒 BACKEND REPORTED:  96.30%

🚧 UPSCAYL_PROGRESS:  96.30%

🎒 BACKEND REPORTED:  97.22%

🚧 UPSCAYL_PROGRESS:  97.22%

🎒 BACKEND REPORTED:  98.15%

🚧 UPSCAYL_PROGRESS:  98.15%

🎒 BACKEND REPORTED:  99.07%

🚧 UPSCAYL_PROGRESS:  99.07%

🎒 BACKEND REPORTED:  🏞️ Resizing image according to output scale

🚧 UPSCAYL_PROGRESS:  🏞️ Resizing image according to output scale

🎒 BACKEND REPORTED:  🏞️ Scaled image from 2304x1792 to 6912x5376

🚧 UPSCAYL_PROGRESS:  🏞️ Scaled image from 2304x1792 to 6912x5376

🎒 BACKEND REPORTED:  100.00

🙌 Upscayled Successfully!

🚧 UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  /Users/andre/Desktop/aliens/file0001_upscayl_3x_RealESRGAN_General_WDN_x4_v3.jpg
💯 UPSCAYL_DONE:  /Users/andre/Desktop/aliens/file0001_upscayl_3x_RealESRGAN_General_WDN_x4_v3.jpg
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"RealESRGAN_General_WDN_x4_v3","value":"RealESRGAN_General_WDN_x4_v3"}
⚙️ Setting gpuId to empty string

**Comment by barf** [comment]
Try invoking from command line maybe. I am using the Debian/Ubuntu version.
```
$ upscayl 
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
📂 DIRNAME /opt/Upscayl/resources/app.asar/export/electron
Checking for update
10:07:20.054 › 🚀 UPSCAYL EXEC PATH:  /opt/Upscayl/resources/bin/upscayl-bin
10:07:20.056 › 🚀 MODELS PATH:  /opt/Upscayl/resources/models
10:07:20.448 › ⚙️ Getting saveImageAs from localStorage:  png
10:07:20.449 › ⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
10:07:20.449 › ⚙️ Setting gpuId to empty string
10:07:20.450 › 🔀 Setting model to null
10:07:20.454 › 🔀 Setting model to realesrgan-x4plus
Update for version 2.11.5 is not available (latest version: 2.11.5, downgrade is disallowed).
```

**Comment by demianill** [comment]
I never used the Upscayl command line.
I'm a photographer, not a IT guy.
I'm using a Macbook Pro 2019 with Sequoia Mac OS.
I will try and report here.

Thanks !

**Comment by barf** [comment]
I just tested on an old MacBook and the timestamps are showing on the command line, but ideally it would be a feature, +1 for the request!

To run from command line on a Mac OS, open Terminal and try the following commands (or similar, if installed to a different path):
```
cd /Applications/Upscayl.app/Contents/MacOS
./Upscayl
```

**Comment by demianill** [comment]
Uhuuuuuu !
It worked very well !

Every executed line has a timestamp. So, I can calculate the elapsed time. 
In any case, it might actually be a good idea for the application to inform the total execution time at the end of each image processing.   I'm glad you agree (_...it would be a feature, +1 for the request!...)_ !!

Thanks, thanks, thanks !!!!

**Comment by barf** [comment]
Glad that it helps!

I needed to check the time for some large images (orthophotos) that were taking hours, then nothing was output due to memory limits I think, but that's another issue. All the best!

**Comment by NayamAmarshe** [comment]
I've added a calculated time in the sidebar.
