### ISSUE TITLE
The log area dont show the GPU id

### ISSUE THREAD

**Issue by Snez112** [upscayl/upscayl#1006]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

It dont show gpu id like the guide :

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\hình nền genshin\2022-01-09 23.03.00.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  D:\hình nền genshin\2022-01-09 23.03.00.jpg
🖼 Selected Image Path:  D:\hình nền genshin\2022-01-09 23.03.00.jpg
📁 Selected Image Directory:  D:\hình nền genshin
🖼 imagePath:  D:\hình nền genshin\2022-01-09 23.03.00.jpg
🔤 Extension:  jpg
🔀 Model changed:  realesrgan-x4plus
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"D:\\hình nền genshin","fileNameWithExt":"2022-01-09 23.03.00.jpg","outputDir":"D:\\hình nền genshin\\upsacle","outFile":"D:\\hình nền genshin\\upsacle\\2022-01-09 23.03.00_upscayl_2x_realesrgan-x4plus.png","fileName":"2022-01-09 23.03.00","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\hình nền genshin\2022-01-09 23.03.00.jpg,-o,D:\hình nền genshin\upsacle\2022-01-09 23.03.00_upscayl_2x_realesrgan-x4plus.png,-s,2,-m,D:\Upscayl\resources\models,-n,realesrgan-x4plus,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"D:\\Upscayl\\resources\\bin\\upscayl-bin","args":["D:\\Upscayl\\resources\\bin\\upscayl-bin","-i","D:\\hình nền genshin\\2022-01-09 23.03.00.jpg","-o","D:\\hình nền genshin\\upsacle\\2022-01-09 23.03.00_upscayl_2x_realesrgan-x4plus.png","-s","2","-m","D:\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkEnumeratePhysicalDevices failed 5
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed 5
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string

**Comment by aaronliu0130** [comment]
As said above, it doesn't show the GPU ID because it can't connect to your drivers at all. Please file a new issue with the bug-report template, which has troubleshooting steps.

>  Issues with the docs, release notes, website, etc
![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
