### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by erdmann040** [upscayl/upscayl#1007]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

I would like to use the results on a commercial website. If I understand the license conditions on the upscaly website correctly, you need permission for commercial use. Does this also apply to this program?  Is there any kind of digital watermark to recognize that the images were created with this progamm?

I found the following under FAQs on the upscaly-Website: "Out of the box, only General Photo (Real-ESRGAN), General Photo (Fast Real-ESRGAN) and Digital Art, allow commercial use. All other models are for personal use only. If you require commercial with other models, you can sign up for Upscayl Cloud or contact us for commercial Upscayl Desktop licensing." 

Does this programm uses any other models but these two? I just need it for upcaling images.

**Comment by aaronliu0130** [comment]
Duplicate of #442 (thx dosu)
