### ISSUE TITLE
Cannot Save Image on Windows11

### ISSUE THREAD

**Issue by josemacedogoncalves** [upscayl/upscayl#1015]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

I just downloaded the last version of Upscayl.
I do upscale images with preview. and put on Output folder, but the image is not there saved.

When i put 4x scale it did not even upscale image.

my log is this.

⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8.jpg
🖼 Selected Image Path:  C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8.jpg
📁 Selected Image Directory:  C:\Users\josem\Desktop\Novas Fotos Ai
🖼 imagePath:  C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8.jpg
🔤 Extension:  jpg
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  C:\Users\josem\Desktop\Novas Fotos Ai
🗂 Setting Output Path:  C:\Users\josem\Desktop\Novas Fotos Ai
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\josem\Desktop\Novas Fotos Ai
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"jpg","inputDir":"C:\\Users\\josem\\Desktop\\Novas Fotos Ai","fileNameWithExt":"SHAPE-8.jpg","outputDir":"C:\\Users\\josem\\Desktop\\Novas Fotos Ai","outFile":"C:\\Users\\josem\\Desktop\\Novas Fotos Ai\\SHAPE-8_upscayl_2x_realesrgan-x4plus.jpg","fileName":"SHAPE-8","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8.jpg,-o,C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8_upscayl_2x_realesrgan-x4plus.jpg,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\josem\\Desktop\\Novas Fotos Ai\\SHAPE-8.jpg","-o","C:\\Users\\josem\\Desktop\\Novas Fotos Ai\\SHAPE-8_upscayl_2x_realesrgan-x4plus.jpg","-s","2","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","jpg","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  [0 NVIDIA GeForce RTX 3070]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3070]  bugsbn1=0  bugbilz=92  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3070]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3070]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 3070]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3070]  bugsbn1=0  bugbilz=92  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3070]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3070]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8_upscayl_2x_realesrgan-x4plus.jpg
💯 UPSCAYL_DONE:  C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8_upscayl_2x_realesrgan-x4plus.jpg
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string

### To Reproduce

Download the last version on windows 11 - have NVIDIA GeForce RTX 3070

and upscale a 40mgbytes image to 2x or 4x

### Upscayl Version (or commit hash)

2.11.5

### Platform

Linux

### OS Version

Windows 11 Pro 23H2

### GPU Name

NVIDIA GeForce RTX 3070

### Expected Behavior

It should have saved the upscaled image on the folder i put

### Screenshots

![Captura de ecrã 2024-10-23 194700](https://github.com/user-attachments/assets/e8b813e2-c3f1-4a6b-b09d-3fc924fc4623)
![Captura de ecrã 2024-10-23 194700](https://github.com/user-attachments/assets/d5aea6f5-ca26-4849-bbbd-53ca5b3865cc)

### Logs

```sh
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8.jpg
🖼 Selected Image Path:  C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8.jpg
📁 Selected Image Directory:  C:\Users\josem\Desktop\Novas Fotos Ai
🖼 imagePath:  C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8.jpg
🔤 Extension:  jpg
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  C:\Users\josem\Desktop\Novas Fotos Ai
🗂 Setting Output Path:  C:\Users\josem\Desktop\Novas Fotos Ai
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\josem\Desktop\Novas Fotos Ai
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"jpg","inputDir":"C:\\Users\\josem\\Desktop\\Novas Fotos Ai","fileNameWithExt":"SHAPE-8.jpg","outputDir":"C:\\Users\\josem\\Desktop\\Novas Fotos Ai","outFile":"C:\\Users\\josem\\Desktop\\Novas Fotos Ai\\SHAPE-8_upscayl_2x_realesrgan-x4plus.jpg","fileName":"SHAPE-8","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8.jpg,-o,C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8_upscayl_2x_realesrgan-x4plus.jpg,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\josem\\Desktop\\Novas Fotos Ai\\SHAPE-8.jpg","-o","C:\\Users\\josem\\Desktop\\Novas Fotos Ai\\SHAPE-8_upscayl_2x_realesrgan-x4plus.jpg","-s","2","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","jpg","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  [0 NVIDIA GeForce RTX 3070]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3070]  bugsbn1=0  bugbilz=92  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3070]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3070]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 3070]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3070]  bugsbn1=0  bugbilz=92  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3070]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3070]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1


🚧 UPSCAYL_PROGRESS:  68,69%

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8_upscayl_2x_realesrgan-x4plus.jpg
💯 UPSCAYL_DONE:  C:\Users\josem\Desktop\Novas Fotos Ai\SHAPE-8_upscayl_2x_realesrgan-x4plus.jpg
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
```

**Comment by josemacedogoncalves** [comment]
@dosu

permissions are good. I am using Topaz Ai and it works fine. I wanted to try this one with 500+ photos but it seems not to work correctly

I tried Tile Size 0 as well. The Log seems to be ok. i unput the the full Log on first comment.

So i believe there is no solution.

**Comment by T-Six** [comment]
Same issue here. Have tried and will try a bunch of things. For my info, what is the original resolution of the image you're trying to upscale? Mine is pretty high 19267x14467, I wonder if there are limits.

**Comment by T-Six** [comment]
> Same issue here. Have tried and will try a bunch of things. For my info, what is the original resolution of the image you're trying to upscale? Mine is pretty high 19267x14467, I wonder if there are limits.

Okay yes, so I tried it with a 140x140 image and it works perfectly. I then made the image I actually wanted to enhance smaller in Photoshop and enhancing it works now. I hope this helps.

**Comment by aaronliu0130** [comment]
This seems like a duplicate of #493.
