### ISSUE TITLE
Update flatpak runtime to 22.08 (asking once again)

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [upscayl/upscayl#102]
You have a json file in the flatpak folder of the repo that is set to compile with 22.08 and uses Electron2.BaseApp instead of electron builder. So why is the current release still using 20.08?

**Comment by Cyborgscode** [comment]
Flatpak is actually warning about installing Upscayl, something **you do not honestly wan**t:

$ flatpak install ./Upscayl-1.5.5-x86_64.flatpak
Required runtime for org.upscayl.app/x86_64/master (runtime/org.freedesktop.Platform/x86_64/20.08) found in remote flathub
Do you want to install it? [Y/n]: y
Info: org.freedesktop.Platform//20.08 is end-of-life, with reason:
org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: org.freedesktop.Platform.GL.default//20.08 is end-of-life, with reason:
org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

org.upscayl.app permissions:
ipc network pulseaudio wayland x11 dri file access [1] dbus access [2]

**Comment by Cyborgscode** [comment]
BTW: Upscayl was feature today in serveral blogs & newspages in Germany, Austria and Switzerland.

**Comment by NayamAmarshe** [comment]
> BTW: Upscayl was feature today in serveral blogs & newspages in Germany, Austria and Switzerland.

Could you please link it?

**Comment by Cyborgscode** [comment]
https://marius.bloggt-in-braunschweig.de/2022/11/10/upscayl-bestes-beispiel-wieso-man-keine-container-usw-nutzen-sollte/
https://gnulinux.ch/fotos-verbessern-mit-upscayl

Those two (to my knowlage) links  got multiplied by the OSBN and other Newsaggregators.
