### ISSUE TITLE
Add SwinIR to default models

### ISSUE THREAD

**Issue by gbartoli-zcs** [upscayl/upscayl#1020]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

It would be nice to have [SwinIR](https://openmodeldb.info/models/4x-realSR-BSRGAN-DFOWMFC-s64w8-SwinIR-L-x4-GAN) model in the default ones, since it currently seems to be [state-of-the-art](https://www.reddit.com/r/StableDiffusion/comments/xsoczh/upscalers_comparison_part_2_swinir_remacri_valar/) in upscaling tests.

At the moment, they are not event present in the official [custom models collection](https://github.com/upscayl/custom-models).

**Comment by aaronliu0130** [comment]
Doesn't seem to be compatible with the REAL-ESRGAN runtime after converting through chaiNNer
