### ISSUE TITLE
Will there be Chinese in the future

### ISSUE THREAD

**Issue by DGhike** [upscayl/upscayl#1021]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

I hope to have Chinese language very much

### Alternatives

无

**Comment by NayamAmarshe** [comment]
Yes :)

**Comment by aaronliu0130** [comment]
Chinese is going to be in the next release!

**Comment by aaronliu0130** [comment]
Chinese is already in the development version and will be in the next release

**Comment by NayamAmarshe** [comment]
I'll be releasing this week. Sorry for all the delay.
