### ISSUE TITLE
How to use GPU in ubuntu system through deb package installation

### ISSUE THREAD

**Issue by suwei999** [upscayl/upscayl#1028]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

How to use GPU in ubuntu system through deb package installation

### To Reproduce

How to use GPU in ubuntu system through deb package installation

### Upscayl Version (or commit hash)

2.11.5

### Platform

Linux

### OS Version

Ubuntu 22.04.03

### GPU Name

NVIDIA 4060Ti

### Logs

```sh
none
```

**Comment by aaronliu0130** [comment]
I don't see what the problem is here.

**Comment by Fxsch** [comment]
Upscayl uses Vulkan, so it should just work if anything else that uses Vulkan (like games) works on your system. If you want any help, you need to provide some information off what exactly is not working.
