### ISSUE TITLE
Upscale blurs and stretches the image

### ISSUE THREAD

**Issue by andreybexus** [upscayl/upscayl#1029]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

I want you to fix this bug, no new details are added, the text becomes soapy. Hair, skin, distant objects and other things do not improve.

**Comment by andreybexus** [comment]
That is, the quality is not improving. Version upscayl 2.11.5

**Comment by andreybexus** [comment]
Write down if you have encountered such a problem, or have just encountered it.

**Comment by andreybexus** [comment]
> Hey @andreybexus! I'm here to help you with any bugs, questions, or contributions you have. Just waiting for a human maintainer to join.
> 
> The issue you're experiencing, where the image becomes blurry and stretched without improvement in detail, is a known limitation of Upscayl. Upscayl is not designed to de-blur or adjust the focus of images. It can enhance low-resolution and pixelated images, but if the image is out-of-focus or totally blurred, Upscayl is not the right tool for it [[1]](https://github.com/upscayl/upscayl/blob/main/README.md).
> 
> For improving image details, you might want to try the following adjustments:
> 
> 1. **Model Selection**: Choose a model that is better suited for detail enhancement, such as "ultrasharp."
> 2. **Double Upscayl**: Enable the "Double Upscayl" option to run the upscaling process twice, which might improve detail.
> 3. **Custom Tile Size**: Adjust the tile size to optimize processing and potentially enhance detail.
> 4. **Custom Models**: Consider adding custom models that might better preserve details.
> 5. **Image Scale**: Ensure the scale is set appropriately; anything above 4X (except 16X Double Upscayl) only resizes without AI enhancement [[2]](https://github.com/upscayl/upscayl/issues/998).
> 
> These steps might help in improving the results you get from Upscayl.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

Alas, unfortunately there are few custom models

**Comment by andreybexus** [comment]
> Hey @andreybexus! I'm here to help you with any bugs, questions, or contributions you have. Just waiting for a human maintainer to join.
> 
> The issue you're experiencing, where the image becomes blurry and stretched without improvement in detail, is a known limitation of Upscayl. Upscayl is not designed to de-blur or adjust the focus of images. It can enhance low-resolution and pixelated images, but if the image is out-of-focus or totally blurred, Upscayl is not the right tool for it [[1]](https://github.com/upscayl/upscayl/blob/main/README.md).
> 
> For improving image details, you might want to try the following adjustments:
> 
> 1. **Model Selection**: Choose a model that is better suited for detail enhancement, such as "ultrasharp."
> 2. **Double Upscayl**: Enable the "Double Upscayl" option to run the upscaling process twice, which might improve detail.
> 3. **Custom Tile Size**: Adjust the tile size to optimize processing and potentially enhance detail.
> 4. **Custom Models**: Consider adding custom models that might better preserve details.
> 5. **Image Scale**: Ensure the scale is set appropriately; anything above 4X (except 16X Double Upscayl) only resizes without AI enhancement [[2]](https://github.com/upscayl/upscayl/issues/998).
> 
> These steps might help in improving the results you get from Upscayl.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

The RealisticRescaler and Realistic misc models are missing, and crealr reality

**Comment by aaronliu0130** [comment]
"blur"ring is expected because that's how good the models are. (You can convert more models using the guide in the wiki.) Could you elaborate on "stretching"?
