### ISSUE TITLE
Special mode for text?

### ISSUE THREAD

**Issue by vivadavid** [upscayl/upscayl#103]
Hi,

I discovered your programme a few days ago and I've been testing it a bit (especially with low-resolution maps of Middle-earth). It works really well: congratulations!

I've noticed that, in case of doubt, it's worth trying both the photo and anime modes with certain images to determine which one produces better results. During my tests, I realized that Upscayl could be a great tool to improve the legibility of the scanned pages of a book, which made me think if it would make sense to create an additional mode for this, also bearing in mind that the upscaled images would then need to be read by an OCR tool. Without this possible new mode, the results seem to be quite good anyway.

Thanks again for your wonderful programme!

**Comment by maribox** [comment]
Hey, where was this completed? Which model is the text-model?

**Comment by NayamAmarshe** [comment]
Sorry, not sure why I closed it as completed but we have custom models now that you can take a look at. Maybe some of them have better text rendering :)

**Comment by vivadavid** [comment]
> Sorry, not sure why I closed it as completed but we have custom models now that you can take a look at. Maybe some of them have better text rendering :)

Hi! I don't recall a specific mode for text, but the general modes are quite good anyway.

**Comment by maribox** [comment]
So I tried a few models, but I couldn't find ones that really do a great job when there's significant distortion etc.
It sounds to me like this could be a not too hard problem to solve because you could just take pictures of random text, blur/distort them and feed an AI with that, right?
If I wanted to work on this, do you have any tips on getting started?

**Comment by vivadavid** [comment]
> So I tried a few models, but I couldn't find ones that really do a great job when there's significant distortion etc. It sounds to me like this could be a problem that can be solved, because you could just take pictures of random text, blur/distort them and feed an AI with that, right? If I wanted to work on this, do you have any tips on getting started?

It would be fantastic to have a model especially fit for text.

**Comment by NayamAmarshe** [comment]
> So I tried a few models, but I couldn't find ones that really do a great job when there's significant distortion etc. It sounds to me like this could be a problem that can be solved, because you could just take pictures of random text, blur/distort them and feed an AI with that, right? If I wanted to work on this, do you have any tips on getting started?

Try looking into training REAL-ESRGAN models. You'll need to use a large enough dataset that includes images with text and train it.
