### ISSUE TITLE
Add Animated Png Support

### ISSUE THREAD

**Issue by 5cutters** [upscayl/upscayl#1036]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Currently Upscayl (V2.11.5) will show an animated preview of apng files (using .png extension), but the Upscayl processing only produces a static image.

Can all the frames of an apng file be processed and rebuilt into an apng?

Edit - i understand if this doesn't really fit into the scope of Upscayl, but if that's the case then the preview of the source image should not animate (as it creates the impression that apng's are supported)

### Alternatives

Extract frames, upscayl individiually and then rebuild into apng.

**Comment by aaronliu0130** [comment]
we have to do video stuff first (#666), probably try something like https://github.com/orgs/upscayl/discussions/542 instead
