### ISSUE TITLE
 Feature Request: Support for AppImageUpdate

### ISSUE THREAD

**Issue by epic0421** [upscayl/upscayl#105]
Since there is an AppImage version of this application, it would be convenient to be able to update an AppImage without needing to download one from the releases page every time a new version of this application gets released.

More info on the project here: https://github.com/AppImage/AppImageUpdate

**Comment by NayamAmarshe** [comment]
Closing this issue as this has been already a feature since the first release.
Let me know if we missed something or want to discuss about it.

![image](https://user-images.githubusercontent.com/25067102/193807999-c047f5e8-5d60-43be-a94d-9d034aca89d2.png)
