### ISSUE TITLE
uncaught exception: write EPIPE

### ISSUE THREAD

**Issue by j2l** [upscayl/upscayl#106]
Hello,
This is a GREAT (upscayled) tool.
The AppImage worked fine on my Ubuntu 22.04 for weeks until today:
![image](https://user-images.githubusercontent.com/65325/193793157-45cad659-e5cd-4262-acb6-96f74faa6493.png)
I didn't change anything.
Any idea from Ubuntu + Upscayl users?

**Comment by NayamAmarshe** [comment]
That's strange. It's the first time someone has reported this issue. Could you try the flatpak file?

**Comment by j2l** [comment]
Thank you very much @NayamAmarshe 

Finally, after rebooting, it went away.
Very weird indeed. I noticed that Ubuntu 22.04 has issues with other AppImages (yes, after double checking chmod execute +  libfuse2 installed).
