### ISSUE TITLE
Time to test out a few different AI models 

### ISSUE THREAD

**Issue by DJboutit** [upscayl/upscayl#107]
Here is a listed of different AI models https://upscale.wiki/wiki/Model_Database

Best worth trying out 

4x-UltraSharp 

UniScale-Balanced/Strong 

UniScale_Restore

UniScaleV2_Soft/Moderate/Sharp

Lollypop

NickelbackFS

First 4 are the best AI models

**Comment by NayamAmarshe** [comment]
I'll see if they're possible to add and get back to you
