### ISSUE TITLE
Pasting from clipboard is now broken

### ISSUE THREAD

**Issue by fixups** [upscayl/upscayl#108]
Copy/paste an image from the file manager used to work in the previous version (was it 1.2?), but is now broken in v1.5 and 1.5.5.

There is another open issue (#36) about copy/paste from an image app, but it's not the same issue.

I'm using Ubuntu 20.04 MATE, and I'm copying from the file manager (Caja). I'm not copy/pasting an image from another app. I'm using the file manager, so when I paste with Ctrl-V, Upscayl should receive a file path from the clipboard.

I have tried to paste with Shift-Insert and Shift-Ctrl-V, it doesn't work either.

When I paste with Ctrl-V in an editor, the path looks clean. For example, I get: "/home/ct/Air/barcode.png". There are no spaces or special characters in the path (I thought it could be the problem, but it's not).

Copy/paste from the file manager used to work in a previous version, and is VERY USEFUL because dragging an image from the file manager to Upscayl often does not work (you have to wiggle the mouse pointer or to move it in and out the Upscayl window several times for it to finally accept the drag/drop operation). Maybe I should open a separate issue for the drag/drop behavior, BTW.

Thank you for your work and for your attention on this issue.

**Comment by NayamAmarshe** [comment]
Hey, sorry for the late response. I don't know how I missed this.
I'll check if there's anything I can do regarding this. Copy pasting from file manager should work, I tested on Nautilus.

**Comment by fixups** [comment]
> Did you copy the image file itself or the image path?

I'm copying with Ctrl-C (or right-click, then Copy) from the file manager, which does not copy the image content, if that's what you are thinking about. The file manager, Caja here, copies the image path to the clipboard. If I paste that in an editor, I get the absolute path of the image.

For example, in Caja, using Ctrl-C on an image then pasting with Ctrl-V here:
  /home/ct/Images/bug.jpg
Then I open Upscayl, click where it says "Select an image to upscale", then Ctrl-V:
  ...nothing happens.

This used to work in the previous version of Upscayl.

**Comment by fixups** [comment]
> Hey, sorry for the late response. I don't know how I missed this. I'll check if there's anything I can do regarding this. Copy pasting from file manager should work, I tested on Nautilus.

I'm using Caja, because my flavor of Ubuntu is MATE. I thought it would not make a difference.

I have just launched an Ubuntu 22.04 Gnome VM, which has Nautilus, and apparently Nautilus does the same thing as Caja: it copies the image's absolute path to the clipboard.

I was expecting a difference, like maybe Nautilus produces something like "file://...", but nope. It produces a very simple, clean, absolute path, exactly the same thing as Caja produces. For example:
  /home/ct/Images/bug.jpg
To get the above result, I have selected a file in Nautilus, pressed Ctrl-C, launched the system's editor (gedit) and pressed Ctrl-V. The same output happens in Ubuntu MATE using Caja as the file manager and Geany as the editor.

I know on some systems the clipboard can hold several versions of the thing that has been copied, for example a text version (in this case the absolute path) and also an image version (in the case of an image).

I don't know if that's the case here. It's just an idea about what could go wrong.

What's really strange is that it worked perfectly in Upscayl's previous version.

**Comment by fixups** [comment]
Sorry, but I'm testing Upscayl 2.0.1 and this bug is still not fixed.

The exact same problem as in my original post is still present. I have not tested 2.0, so I'm not sure in which version it has been fixed, but it's certainly not in 2.0.1. Pasting an image with:
1. Start Upscayl
2. Switch to the file manager window (Caja), press Ctrl-C while on a JPG file, then
3. Switch to the Upscayl window, then press Ctrl-V

...does nothing.

I'm using the AppImage version under Ubuntu 20.04 MATE.

This used to work on this same system with the AppImage version, I think it was version 1.2 or something. It did not work anymore in 1.5 and has never worked for me since.

Thank you for investigating this issue. I really appreciate the work you are doing.
