### ISSUE TITLE
Homebrew's hash doesn't match

### ISSUE THREAD

**Issue by matthewyang204** [upscayl/upscayl#1085]
### Checklist

- [x] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

When I tried to update to 2.15.0 from 2.11.5 today with homebrew on my Mac (it has an Intel chip), homebrew kept saying that the hash wasn't correct. The hash of the file was reported, and tested by me with HashMaker, to be `0e53c9ee8c1800cb3e2ce0f574e4e1a35a51945e19ff2b93f33928bbd7fd4c5a`. However, the homebrew cask code says that the hash should be `e1659294e9d6a72f840a438c23715ef944eab1733766b82d88534337c563f085`

### To Reproduce

Run
`brew install --cask upscayl`

### Upscayl Version (or commit hash)

2.15.0

### Platform

Mac DMG / Homebrew

### OS Version

macOS 15.2

### GPU Name

AMD Radeon Pro 5500M

### Expected Behavior

It should've just installed correctly. I've never had any issue of this kind in Homebrew, where the SHA256 hash didn't match.

### Logs

```sh
==> Downloading https://github.com/upscayl/upscayl/releases/download/v2.15.0/ups
Already downloaded: /Users/matthewyang/Library/Caches/Homebrew/downloads/6c9013fbc77059abd62b739df7f78a0d9d6ab24a3abe78932dcd86947bab85a4--upscayl-2.15.0-mac.dmg
Error: SHA256 mismatch
Expected: e1659294e9d6a72f840a438c23715ef944eab1733766b82d88534337c563f085
  Actual: 0e53c9ee8c1800cb3e2ce0f574e4e1a35a51945e19ff2b93f33928bbd7fd4c5a
    File: /Users/matthewyang/Library/Caches/Homebrew/downloads/6c9013fbc77059abd62b739df7f78a0d9d6ab24a3abe78932dcd86947bab85a4--upscayl-2.15.0-mac.dmg
To retry an incomplete download, remove the file above.
```

**Comment by matthewyang204** [comment]
@dosu I made my own tap with the different calculated SHA256 and it worked fine.

**Comment by yihuanlin** [comment]
I can confirm I encountered the same issue.

**Comment by LautiLosio** [comment]
Bump this

**Comment by NayamAmarshe** [comment]
@zyoshoka could you please update the sha?

**Comment by bevanjkay** [comment]
@NayamAmarshe Homebrew maintainer here, thank you for confirming the updated checksum here. I would strongly recommend only updating binaries when they coincide with a new version number as much as possible. This is the generally expected standard for git releases.

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe Homebrew maintainer here, thank you for confirming the updated checksum here. I would strongly recommend only updating binaries when they coincide with a new version number as much as possible. This is the generally expected standard for git releases.

Yeah, I apologize for the error. I made a mistake while deploying the release so had to update the builds later. I didn't know it'd be updated this quick, since I updated the release just 30 minutes after putting it up.

Sorry again for all the trouble and thank you for all your help and support!

**Comment by matthewyang204** [comment]
Thanks, it works now. I installed it successfully with homebrew from the official cask tap.
