### ISSUE TITLE
Is there a portable version for USB flash drive?

### ISSUE THREAD

**Issue by pstein** [upscayl/upscayl#1087]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

As already said in the topic I prefer to use Upscayl occasionally from USB flash drive.
Therefore I need a portable version.

Where can I download it?
Thank you

### Related Problem(s)

see above

**Comment by NayamAmarshe** [comment]
You can download the zip version. It's portable :)
