### ISSUE TITLE
Single Process output quality is better than batch process 

### ISSUE THREAD

**Issue by DJboutit** [upscayl/upscayl#109]
I have process a lot of images with this program IMO single process output quality is 35% to 60% better quality.  When I do batch process I select images that I think have best chance to be upscaled to a decent quality with batch process 85% of them look like crap.  This needs to be looked at batch process is a waste since the quality is a lot worse it could be the AI mode craps out with a big run of like 35+ image in one go.

**Comment by NayamAmarshe** [comment]
I'll add an output format feature.
