### ISSUE TITLE
Add denoising strength options

### ISSUE THREAD

**Issue by dpanter** [upscayl/upscayl#11]
Current default denoise strength is rather on the heavy side and can remove significant details.
A range of options would be most welcome!

**Comment by NayamAmarshe** [comment]
Real-ESRGAN currently does not support denoising. For that we'd have to add Real-SRGAN (Tencent). I'll see if we can integrate it, also have to add more models.

**Comment by dpanter** [comment]
Thanks for considering it. Appreciate the simple yet powerful application as an AppImage.
