### ISSUE TITLE
Can't upscale beyond a certain resolution

### ISSUE THREAD

**Issue by NightMare-Vortex** [upscayl/upscayl#111]
IK the point of this is to upscale low res images, but gosh darn it I want to upscale past 16k and torture my GPU

**Comment by aaronliu0130** [comment]
What happened when you tried to upscale?

Could be an ERSGAN issue

**Comment by NightMare-Vortex** [comment]
So it would stop at 20% and show me a broken preview the org is tiny as hell, and the upscale is a broken image icon

**Comment by NightMare-Vortex** [comment]
I tried to recreate this bug for more context, but a different error showed up
![Screenshot 2022-10-10 143945](https://user-images.githubusercontent.com/93774088/194858239-d005e12d-c7dd-4148-be07-d73b9565b271.png)

**Comment by NayamAmarshe** [comment]
Unfortunately a 'CANTFIX', the original NCNN Vulkan code has limits to the resolution it can output :(

**Comment by NightMare-Vortex** [comment]
ah, I finally recreated it IDK if this helps tho since it been closed
![Screenshot 2022-10-10 153803](https://user-images.githubusercontent.com/93774088/194867934-6d80c01e-aa0c-4cb6-bca2-806ea38ed524.png)

**Comment by NayamAmarshe** [comment]
> ah, I finally recreated it IDK if this helps tho since it been closed ![Screenshot 2022-10-10 153803](https://user-images.githubusercontent.com/93774088/194867934-6d80c01e-aa0c-4cb6-bca2-806ea38ed524.png)

Can you send the image?

**Comment by NightMare-Vortex** [comment]
> Can you send the image?
ok ill try to find an image thats SFW

**Comment by NightMare-Vortex** [comment]
![Image](https://user-images.githubusercontent.com/93774088/195383436-d02cb21b-de18-4abf-bbb7-7bae19043be5.png)
ok got it work again
it has to be an anime pic I think because it only works when the first output name has realesrgan-x4plus-anime as a suffix

here is the image
https://mega.nz/file/GjwVhJTT#182hTekxFn734-5uY9rVfllQVHXvzOOPptDzejSUjjI
after you download either choose sharpen or chose digital art but **_don't click on double upscaly_**, and it should work

**Comment by NightMare-Vortex** [comment]
Did this get resolved?

**Comment by NayamAmarshe** [comment]
> Did this get resolved?

https://github.com/upscayl/upscayl/issues/111#issuecomment-1273198167

**Comment by aaronliu0130** [comment]
You might want to close some issues as not planned instead of completed.
