### ISSUE TITLE
Upscaling on iGPU

### ISSUE THREAD

**Issue by m0nk3h** [upscayl/upscayl#112]
OS: Fedora release 36 (Thirty Six) x86_64
CPU: AMD Ryzen 9 5900HS with Radeon Graphics (16) @ 4.680GHz 
GPU: AMD ATI 08:00.0 Cezanne

Downloaded today, latest FlatPak release.  I Upscayl'd a couple of photos before going back to the github page to read that iGPU's don't work.  I suppose this isn't an issue, just a potential correction to the description on the requirements.

**Comment by aaronliu0130** [comment]
You do have a gpu though? I don't see the issue

**Comment by m0nk3h** [comment]
That's an iGPU on a laptop CPU.  

https://github.com/upscayl/upscayl#note-upscayl-does-not-work-without-a-gpu-sorry-youll-need-a-vulkan-compatible-gpu-to-upscale-images-cpu-or-igpu-wont-work

**Comment by NayamAmarshe** [comment]
> OS: Fedora release 36 (Thirty Six) x86_64 CPU: AMD Ryzen 9 5900HS with Radeon Graphics (16) @ 4.680GHz GPU: AMD ATI 08:00.0 Cezanne
> 
> Downloaded today, latest FlatPak release. I Upscayl'd a couple of photos before going back to the github page to read that iGPU's don't work. I suppose this isn't an issue, just a potential correction to the description on the requirements.

Some people have reported some iGPUs to work. I'll fix the readme, thanks!
