### ISSUE TITLE
Double Upscayl tooltip disappears (bug)

### ISSUE THREAD

**Issue by Jonas1999** [upscayl/upscayl#113]
Steps to reproduce:
1. Start Upscayl
2. Select Sharpen Image on Step 2
3. Select General Photo/ Digital Art
OR
1. Start Upscayl
2. Toggle Batch Upscale On then Off

**Comment by NayamAmarshe** [comment]
That's intentional. We don't do double sharpening as it's not worth doing, same with Batch Upscale at the moment. Might add it in the future if I see fit but in my testing, there wasn't any need for it.

**Comment by Jonas1999** [comment]
> That's intentional. We don't do double sharpening as it's not worth doing, same with Batch Upscale at the moment. Might add it in the future if I see fit but in my testing, there wasn't any need for it.
> 
> Let me know if you'd like to discuss anything else :)
I think you misunderstood my problem, I mean this tooltip:
![bild](https://user-images.githubusercontent.com/15720835/194901191-6c583519-b8d7-4886-8256-26678ac2920f.png)
After doing either of the things I mentioned it won't pop up until I restart the application.
![bild](https://user-images.githubusercontent.com/15720835/194901510-eb1bcd92-e20d-4ebd-ab16-08a143f30de1.png)
It's a very small tidbit of a problem but I tought it was worth pointing out. :)

**Comment by NayamAmarshe** [comment]
Yeah, I noticed this issue and I'm honestly not sure why it happens. Maybe a bug in the react-tooltip library. Will see if I can replace that with some other library.
