### ISSUE TITLE
auto updater on windows?

### ISSUE THREAD

**Issue by tails101** [upscayl/upscayl#115]
i know there is a lot of linux user and linux handle the app update 
but it would be nice to include an updater for windows .
and a way to select installation location would be nice as well.
thanks you!

**Comment by aaronliu0130** [comment]
The Windows version already has an auto updater. It doesn't prompt you to start downloading the update and instantly starts downloading though. It does give you an option to apply or not.

Suggested title: Select installation location in installer

**Comment by NayamAmarshe** [comment]
We were unable to get the custom installer working so, for now NSIS is the only option.
