### ISSUE TITLE
Long file names seem to be causing errors

### ISSUE THREAD

**Issue by yekta** [upscayl/upscayl#118]
I think long file names are causing an error. After suspecting it I tried the exact same file with random letters added to name (a very long string) and it failed to upscale.

If I shorten the name, it goes away. I suspected it might be some special characters but it just seems to be related to length. This is the error I'm getting:

![upscayl-error](https://user-images.githubusercontent.com/40706601/196049806-65a70890-85bc-466b-b45a-aa8e480d5159.png)

**Comment by NayamAmarshe** [comment]
The error is probably not from the Upscayl side but the AI model. So marking this as a cantfix for the moment because it's probably a limit from the binaries.

Let me know if you find any exceptions though, I'll reopen the issue.
