### ISSUE TITLE
Feature Request: Zoom in/out in the comparison viewfinder with Fullscreen View

### ISSUE THREAD

**Issue by faisalhr1997** [upscayl/upscayl#119]

**Comment by faisalhr1997** [comment]
> Elaborate?
> 
> Do you mean you wish to be able to make the before after comparison fullscreen?

yes in Fullscreen mode with zoom in out with scroll trigger or floating button.

**Comment by NayamAmarshe** [comment]
I wanted to add this in v1.5.5 but was unable to. Will try again.
