### ISSUE TITLE
JPEGs converted as PNGs in batch mode

### ISSUE THREAD

**Issue by vivadavid** [upscayl/upscayl#121]
Hi,

As far as I can see, the image format (JPEG, PNG, etc.) is kept when you upscale an image. However, I've just noticed that, in batch mode, JPEG images are saved as PNG files.

In addition to this, I wonder if it would be beneficial for users to be able to choose the output format: JPEG, PNG or, as a default option, automatic (which would keep the original format). The JPEG format produces artifacts, though, on the other hand, the upscaled PNG file might too big for some people, so it would be nice to be able to choose and decide.

Thanks!

**Comment by NayamAmarshe** [comment]
Noted.

**Comment by vivadavid** [comment]
> Noted.

Thanks!

**Comment by vivadavid** [comment]
Hi, @NayamAmarshe ,

Thank you for adding an image format section under "Advanced options". Would be it possible to add a fourth option called "same as original"? It would be really useful in batch operations where there might different image formats.

Thanks in advance!

**Comment by NayamAmarshe** [comment]
> Hi, @NayamAmarshe ,
> 
> Thank you for adding an image format section under "Advanced options". Would be it possible to add a fourth option called "same as original"? It would be really useful in batch operations where there might different image formats.
> 
> Thanks in advance!

Ah ok, yes, that's possible.

**Comment by vivadavid** [comment]
> > Hi, @NayamAmarshe ,
> > Thank you for adding an image format section under "Advanced options". Would be it possible to add a fourth option called "same as original"? It would be really useful in batch operations where there might different image formats.
> > Thanks in advance!
> 
> Ah ok, yes, that's possible.

It would be great! Thanks for considering it!
