### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by UPSA007** [upscayl/upscayl#123]
Hi I just discovered your app. It's one of the most intuitive one I have found so far. I upscaled an old black and white comic and results blew my mind. However, I noticed something. I have a laptop with RTX 2060 and Ryzen 4900H. For some reason the app is using the integrated GPU. Can you please add an option to choose between GPUS? Thanks

**Comment by aaronliu0130** [comment]
Side note: The upscaling engine used by this app is REAL-ERSGAN, this app is just a GUI.

**Comment by NayamAmarshe** [comment]
> Hi I just discovered your app. It's one of the most intuitive one I have found so far. I upscaled an old black and white comic and results blew my mind. However, I noticed something. I have a laptop with RTX 2060 and Ryzen 4900H. For some reason the app is using the integrated GPU. Can you please add an option to choose between GPUS? Thanks

I suppose we can add a counter. Sorry for the delay in the release, I've been extremely busy with work and other things.

**Comment by Cyborgscode** [comment]
> Side note: The upscaling engine used by this app is REAL-ERSGAN, this app is just a GUI.

Can you link it pls? Github has two, both with suspect release contents. A CLI command would be extrem cool.

**Comment by NayamAmarshe** [comment]
> > Side note: The upscaling engine used by this app is REAL-ERSGAN, this app is just a GUI.
> 
> Can you link it pls? Github has two, both with suspect release contents. A CLI command would be extrem cool.

https://github.com/xinntao/Real-ESRGAN/blob/master/docs/ncnn_conversion.md
