### ISSUE TITLE
Feature Request: Allow reading source image with "Open With" on Windows

### ISSUE THREAD

**Issue by jlick** [upscayl/upscayl#124]
On Windows there is a shortcut to open a file in a particular program by right clicking on the file, selecting "Open With" and selecting an application. Currently, Upscayl is not an option by default, likely because it isn't registered in the OS for the applicable file types (JPG, PNG, etc.). If you add the application manually (which is hidden in AppData), Upscayl now appears in the "Open With" list, but selecting it opens the Upscayl program without opening the image.

Requests:

1) Add whatever magic is needed so that Windows recognizes it for compatible image types supported by Upscayl so that it shows up in the "Open With" menu without having to manually add it.
2) Fix Upscayl so that using "Open"/"Open With" will load the image in Upscayl without having to "Select Image".

The second request is higher priority as the first has a workaround.

**Comment by aaronliu0130** [comment]
Please also implement this on mac and linux

**Comment by NayamAmarshe** [comment]
No plans to implement this as I personally think there's not a lot of utility that an open with dialog provides for a non image-viewer. It's just as easier to drag and drop the image and hit upscayl.

I think you'd be better off with a script that takes in an image and upscales it with the REAL-ESRGAN binary and you can add that script to open with menu.
