### ISSUE TITLE
Does upsscayl use https://github.com/TencentARC/GFPGAN

### ISSUE THREAD

**Issue by LinuxBeaver** [upscayl/upscayl#126]
This is a sister project of REAL-ESRGAN that restores faces.  I'd like to know if it is used here.

**Comment by NayamAmarshe** [comment]
> This is a sister project of REAL-ESRGAN that restores faces. I'd like to know if it is used here.

Real-ESRGAN already has GFPGAN in its code I think. Please refer to the Real-ESRGAN repository, they've mentioned that in the readme.

**Comment by LinuxBeaver** [comment]
I don't think it does have it. Definitely not all of it based on test I did. 

When I run GFPGAN afterward it does much more to enhance the facial features. The same is true for the CLI only version  of REAL-ESRGAN.  In the future a hypothetical goal would be to have it where the user has a facial enhance checkbox that calls GFPGAN properly.
