### ISSUE TITLE
Maximum Upscale?

### ISSUE THREAD

**Issue by TheCherry** [upscayl/upscayl#127]
What is the maxium upscale that I can archive atm?
I try to Upscale a Image with 1792x2304 with the factor 8, but the process abort around 80%
If I try to upscale this 2 times with the factor 4, it's crash by around 50%

Or do I need more VRAM for my GPU? My Goal is to get around 20,000x10,000 pixels.

**Comment by DJboutit** [comment]
Biggest size number I have found can not be more than 7800 if it is you will get a decoding error.  Any image with a number of 6000+ it will take 4 to 7 min to process the image.  While smaller images with the biggest number of 2400 only take 75 seconds to process.  Example 7800x5500 or 5500x7800
