### ISSUE TITLE
Proposal to convert the project to typescript.

### ISSUE THREAD

**Issue by Spartan09** [upscayl/upscayl#129]
I am new to open source and feel like this would really improve my understanding in working with typescript at a big scale. Also I upscaled a bunch of images with this amazing tool and I really loved it so that gives me additional motivation to this. If you want I could give a shot at converting the project into typescript slowly and steadily.

**Comment by NayamAmarshe** [comment]
Yeah, definitely go ahead :) I wanted to convert this to typescript as well but I've been unwell and very busy lately :(

**Comment by aaronliu0130** [comment]
This has been proposed before in #33

**Comment by NayamAmarshe** [comment]
Done.
