### ISSUE TITLE
show file progress in batch mode

### ISSUE THREAD

**Issue by kmulvey** [upscayl/upscayl#130]
Showing [completed / total] somewhere would give an idea of how much more there is to go.

**Comment by NayamAmarshe** [comment]
The problem with that is sometimes, it does multithreading so calculating how many files are done is not trivial. I wanted to do it but it didn't work unfortunately.

**Comment by Cyborgscode** [comment]
print the filenames you process.. thats enough for now

**Comment by aaronliu0130** [comment]
You could check out ravenfield's mod loading UI, it shows multiple progress bars for each thread. So you could split the files into how many threads are running

**Comment by NayamAmarshe** [comment]
That's still not possible. We depend on the binary's stdoutput. It doesn't give us much to work with, not even file names, just percentages.

**Comment by Cyborgscode** [comment]
and who tells the cmdline tool to process a _file_? ;)

**Comment by aaronliu0130** [comment]
@Cyborgscode noone. The cmdtool itself has batch mode.

Is there a verbose output option?

**Comment by NayamAmarshe** [comment]
> @Cyborgscode noone. The cmdtool itself has batch mode.
> 
> Is there a verbose output option?

Not that I know of.  I'll see if it's possible.

I'm currently trying to port the project to Typescript. Getting a few errors so need to fix those.
