### ISSUE TITLE
Add Code Former (NeurIPS 2022) models

### ISSUE THREAD

**Issue by Tarek-Hasan** [upscayl/upscayl#131]
Please add Code Former's Real-ESRGAN models, as they are better at face restoration than vanilla Real-ESRGAN models.
https://github.com/sczhou/CodeFormer

**Comment by NayamAmarshe** [comment]
I'd want to add Remacri first. Will have to find time to convert it to ncnn if possible. The model you've sent doesn't have ncnn format either.
