### ISSUE TITLE
Support deb and snap

### ISSUE THREAD

**Issue by dtantono** [upscayl/upscayl#134]
Since, flatpak have not released yet and not everyone like appimage. Is it possible to get this app on deb or snap?

**Comment by NayamAmarshe** [comment]
Yes, definitely but the issue with snaps is, they don't allow access to home directory which would break the app.
In the next release, I'll make sure to provide a DEB version.

**Comment by git-Hmmm** [comment]
Please consider supporting rpm version too :pray: #151
