### ISSUE TITLE
Possibility to open directly a file in argument from CLI (flatpack)

### ISSUE THREAD

**Issue by rcspam** [upscayl/upscayl#136]
Hi,
All is in the title.
Is it possible to open file when its path is given in argument.
Example:
`$ flatpak run org.upscayl.app SOMEFILE`

Good job
Thanks

**Comment by NayamAmarshe** [comment]
Sorry, this won't be possible for now as our focus is on making GUI, not maintaining CLI.
You can use the Real-ESRGAN binaries though, that should work better and maybe you can add a custom bash function in your shell rc :)

**Comment by rgrg25** [comment]
On windows:

After getting the UI working successfully, close it.
Open a command prompt and 

1.   cd to the resources\bin folder
2.   `Upscayl-bin.exe -i "C:\Pictures\input.png" -o "C:\Pictures\output.jpg" -s 4 -m "E:\Program Files\Upscayl\resources\models" -n "RealESRGAN_General_x4_v3" -f "jpg"` 

Note that the example above uses the -m argument to specify the location of the previously downloaded [custom models](https://github.com/upscayl/custom-models/blob/main/README.md).  Omit this if you don't want to use any of the custom models.

If you want to see the command being used by the UI based on your own settings made in the UI, just run Upscayl.exe from a command prompt, and you will then be able to see and copy any logged output.

Example:

`**BACKEND REPORTED**:  ≡Upscayl Command:  -i,C:\Pictures\input.png,-o,C:\Pictures\input_upscayl_2x_RealESRGAN_General_x4_v3.jpg,-s,4,-m,E:\Program Files\Upscayl\resources\models,-n,RealESRGAN_General_x4_v3,-f,jpg`

**Comment by aaronliu0130** [comment]
I don't think you need to get the UI working. Our UI is all just a GUI for upscayl-bin which is real-esrgan-ncnn-vulkan.

**Comment by rgrg25** [comment]
Thanks Aaron, the UI is very useful as it provides the logs feature from which you can easily work out what parameters to pass to upscayl-bin.  For example I used the UI logs from a batch upscayl to create the script below to do the same:



        import sys
        import os
        import os.path
        import subprocess

        upscayl_input_folder = "my_path"
        upscayl_location = r"E:\Program Files\Upscayl\resources\bin\upscayl-bin.exe"
        upscayl_models_location = r"E:\Program Files\Upscayl\resources\models"
        upscayl_scaling_factor = "4"
        upscayl_model = "RealESRGAN_General_x4_v3"
        upscayl_output_file_format = "jpg"
        upscayl_output_folder = os.path.join(output_path,"upscaled")
        if not os.path.exists(upscayl_output_folder):
            os.mkdir(upscayl_output_folder)
        commands_list = [upscayl_location, 
                "-i", upscayl_input_folder, 
                "-o", upscayl_output_folder, 
                "-s", upscayl_scaling_factor, 
                "-m", upscayl_models_location, 
                "-n", upscayl_model,   
                "-f", upscayl_output_file_format]
        print(commands_list)
        if subprocess.run(commands_list).returncode == 0:
            print ("Upscayling script ran Successfully")
        else:
            print ("There was an error running the upscayling script")
