### ISSUE TITLE
Sharpen feature not altering image?

### ISSUE THREAD

**Issue by ronikobrosly** [upscayl/upscayl#137]
My father has an old, low-quality picture of his father that he wishes was better quality and I'm trying to de-blur / sharpen it for him. I tried doing this 4-5 years ago with the SOTA super-resolution GANs of the time, with disappointing results. 

I just set up upscayl and tried the sharpen feature with the image, and it's almost as if the image is unchanged. Am I doing something wrong here? 

Thanks!  

<img width="517" alt="results" src="https://user-images.githubusercontent.com/9450972/203199659-3649b0d7-b670-4016-9b43-5149cfcdb0db.png">

**Comment by NayamAmarshe** [comment]
The Sharpen algorithm is kinda finicky tbh. It works sometimes, sometimes doesn't, depends totally on the image.
