### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by LaurentGrenet** [upscayl/upscayl#138]
Hi,

I just discovered this fantastic tool (thanks to its mention in Korben' blog https://korben.info/upscayl-pour-agrandir-une-image-sans-perte-de-qualite.html), and first of all, thank you for providing it. 

Just one remark : I installed it in a Windows 10 environment, and I've been surprised to see it has been installed under %LOCALAPPDATA%, ie. in C:\Users\\[UserName]\AppData\Local\Programs\upscayl\ rather than in "usual place" for programs, ie. either %ProgramFiles% (or %ProgramFiles(x86)% for 32bits apps).

Is there any (good...) reason for that ?

If not, it would be great to fix that for futures releases, and install them in "usual location" (even if it may oblige us to first uninstall the old version before installing the new one supposed to be in the "right" place...

**Comment by aaronliu0130** [comment]
Localapp data is actually the usual location for apps that don’t want admin privileges

**Comment by LaurentGrenet** [comment]
I'm afraid you are wrong. Most of the apps, that are installed in ProgramFiles or in ProgramFiles(x86) do not want nor request admin privileges...
And you may have a look on any Windows powered laptop : I do the bet that, as in my own laptop, ALL the applications are either in ProgramFiles or in ProramFiles(x86) and NONE in Localapp....

Localapp is (probably, I'm not even 100% sure) the default place for PORTABLE applications (that can, by definition, be moved anywhere). That is NOT the case of Upscayle....

**Comment by aaronliu0130** [comment]
Yeah portable is what I meant but this IS the case for upscale though

**Comment by NayamAmarshe** [comment]
> Is there any (good...) reason for that ?

Well the reason is that Windows executable is kinda an afterthought. We only do basic testing of the Windows and Mac versions since we use Linux and develop Upscayl on it as well.

I can add an option to choose custom location in the installer though, if you'd like. Shouldn't be too hard.

**Comment by aaronliu0130** [comment]
Most portable installers can be opened as zip files.
