### ISSUE TITLE
Donation page not working? 

### ISSUE THREAD

**Issue by jarthod** [upscayl/upscayl#140]
Hi, thanks for this nice little tool :heart:, I just tried donating through to https://www.buymeacoffee.com/fossisthefuture but faced this error after entering the card:
> It appears that you are cloning a card payment method to a IN-based connected account. As part of our continued investment in India and to meet local data storage requirements, we no longer allow cloning card payment methods into or out of India, so we had to reject your request. For more information, please visit https://stripe.com/india-data-storage-faq.

I am not in India and I tried with two different cards so I suppose the problem does not come from me here. Apparently I'm not the first one impacted: https://community.monzo.com/t/stripe-payment-problem-with-india-based-merchant-cloned-cards/139872.

I contacted buymeacoffee support to tell them about this, I'm not sure how widespread this is but you may be missing on some donations here. Do you have alternative ways to donate?

**Comment by jarthod** [comment]
Thanks, it worked fine this time :)

**Comment by NayamAmarshe** [comment]
Thank you for donating :D
