### ISSUE TITLE
Allow custom (or more resolution modifiers)

### ISSUE THREAD

**Issue by XDM-Inc** [upscayl/upscayl#144]
It would be nice to have things x1.5 x2 etc...  or even custom resolutions

**Comment by NayamAmarshe** [comment]
I can add that but it won't affect the performance much. The upscale binary only supports 4x scale. 2x, 3x are broken and do not work. So if I post-process the images, I'll have to downscale them from 4x to 1.5x or 2x, which you can do manually as well.

**Comment by XDM-Inc** [comment]
> I can add that but it won't affect the performance much. The upscale binary only supports 4x scale. 2x, 3x are broken and do not work. So if I post-process the images, I'll have to downscale them from 4x to 1.5x or 2x, which you can do manually as well.

I guess it is true I can just run it through Photoshop again figure out the multiplier scale in reverse and get the desired resolution. I used to use a app called topaz back when I used windows and sometimes I just wanted to sharpened or cleaned up without changing the resolution is why I mentioned this.

**Comment by NayamAmarshe** [comment]
> > I can add that but it won't affect the performance much. The upscale binary only supports 4x scale. 2x, 3x are broken and do not work. So if I post-process the images, I'll have to downscale them from 4x to 1.5x or 2x, which you can do manually as well.
> 
> I guess it is true I can just run it through Photoshop again figure out the multiplier scale in reverse and get the desired resolution. I used to use a app called topaz back when I used windows and sometimes I just wanted to sharpened or cleaned up without changing the resolution is why I mentioned this.

Yeah I understand but the thing is, it wouldn't make a difference as far as the speed is considered because 4x would take the same time as 1x, in which case it would be better to use 4x.

**Comment by NayamAmarshe** [comment]
But I'm gonna add an output format option so might add a simple resolution selector as well.

**Comment by XDM-Inc** [comment]
> But I'm gonna add an output format option so might add a simple resolution selector as well.

Nice, thanks. Also speed wasn't a issue for me. It was the size, more highter resolution photos start making a 12-20 mb photo

**Comment by jsegeren** [comment]
+1! Thanks @NayamAmarshe. Some output format options - especially a resolution picker, or even allowing custom resolutions (e.g. for upscaling an image to be used as a device wallpaper) would be awesome. 
Like @XDM-Inc says, speed is OK, but it would help to reduce size before saving to disk.
