### ISSUE TITLE
RFE: Original/Target image size display

### ISSUE THREAD

**Issue by prokoudine** [upscayl/upscayl#145]
Upscayl is lovely! One thing I would appreciate is some way to see the original and the target image size in pixels.

The most logical place would probably be around Step 2. For a reference, this is how Upscaler does it:

![image](https://user-images.githubusercontent.com/57467/204085366-eb9e8ae8-e44e-4687-aef6-28c9706f751e.png)

**Comment by NayamAmarshe** [comment]
Yeah for sure. I'll add an info section in v2.0.
