### ISSUE TITLE
Just uses 3GB of VRAM? (I have 8GB)

### ISSUE THREAD

**Issue by deepnx** [upscayl/upscayl#148]
Well until yesterday i had a GTX 1060 3GB variant, And during batch processing, Upscaly used about 3GB VRAM.
I thought its using maximum GPU RAM. 

I was anyway thinking to update my GPU someday for gaming as well.

So I upgraded to RX 6600 8GB.

Reinstalled Upscaly - 
But it still uses just 3GB Vram.
and task manager shows maximum 5-10% GPU usage

1. Using more VRAM might increase the processing speed?
2. Can it use more than 5% of my GPU to speed up things?

**Comment by NayamAmarshe** [comment]
I think it might be just an ncnn vulkan limitation. I can't do much about it because we're borrowing binaries from @nihui and ncnn programming is rather difficult and a totally different field for us :(

**Comment by deepnx** [comment]
> 

Ahh ok bro ... so i believe we cant go any faster than this? no matter how powerful GPU we add?

**Comment by NayamAmarshe** [comment]
> > 
> 
> Ahh ok bro ... so i believe we cant go any faster than this? no matter how powerful GPU we add?

Yes

**Comment by nihui** [comment]
switch to compute tab in task manager, and then it will report the real utilization.

**Comment by deepnx** [comment]
![Screenshot 2022-12-03 193252](https://user-images.githubusercontent.com/2011820/205444746-3e2a02fe-6e88-4ea0-a2f6-d925f24dca1e.png)

Screenshot attached of using only 3gb/8gb of GPU VRAM

> > > 
> > 
> > 
> > Ahh ok bro ... so i believe we cant go any faster than this? no matter how powerful GPU we add?
> 
> Yes



> switch to compute tab in task manager, and then it will report the real utilization.
