### ISSUE TITLE
3 Quality Feature Review + Request

### ISSUE THREAD

**Issue by deepnx** [upscayl/upscayl#149]
Hi firstly - AMAZING job with this app. It works fantastic!!!

I have done A/B testing on 400+ pictures side by side, Of before and after using this app.

Positives -
Extremely easy to use
Body skin results are flawless, reduce noise amazingly + remove artifacts along the edges too
Works fast and seamlessly
There are too many positives about this app but there are a few minor Req I can give below

Negatives/Requests -

**VERY IMPORTANT-**
1. Hair 
The app tries to smoothen out the hair too much killing the "Highlights/Shine" and also making the black part of the hair look a little clumpy. I understand it needs to smoothen out details to make it look high-resolution. But if the highlights/sharpness can be added while processing it won't make the hair look too clumpy.

2. Brightness
Overall the picture looks a little dull in terms of highlight + brightness and looks just a little dull compared to the original. Again I feel this could be the same reason for point 1. As Highlights give an illusion of a brighter picture.

3. Face Texture
I understand apps like Remini use AI to recreate face texture (But they are very bad at body texture), But if this can do something similar using the GPU power and creating details and sharpness in the face then the texture on the face could look more real.

NOT SO IMPORTANT -
3.  Reduction of file size to roughly 1MB output? Well, I do use an app called Caesium to reduce the file size later keeping the resolution and details as much as possible. It's okay if u ignore this point. 

But please can something be done about points 1 & 2?

Again once more - AMAZING work with this app bro.

Thank you very much.

**Comment by aaronliu0130** [comment]
For not so important, see #116 

For the rest, Upscayl doesn't code the upscayling algorithm itself. It uses REAL-ERSGAN at https://github.com/xinntao/Real-ESRGAN/

**Comment by NayamAmarshe** [comment]
3 is planned but the rest, as Aaron said, isn't in our hands.

Don't worry though, we're adding more models so the results should be different.

**Comment by KaKi87** [comment]
Hi,
Are there any models that could perform as good as Remini ?
Thanks
