### ISSUE TITLE
Adding upscayl to AUR

### ISSUE THREAD

**Issue by artogahr** [upscayl/upscayl#15]
I'd like to add this project to AUR for easy installation in Arch Linux, just wanted to ask your permission first :)

Let me know if you have any questions about it.

**Comment by NayamAmarshe** [comment]
No problem at all :D

**Comment by artogahr** [comment]
You're providing two tools, one for gui, and one for cli, how should we go about that? I'm thinking of making an upscayl-bin repo that provides upscayl GUI by launching the AppImage, but I'm not sure about the CLI binary that's contained in the git repo. How do you think we should proceed? 

Maybe create an upscayl-cli repo and keep the build files for the CLI app there? That way a seperate upscayl-cli package can be downloaded from AUR. 

Or you can add the CLI tool to the releases page, so that one "upscayl-bin" repo contains two binaries - upscayl-gui and upscayl-cli?

**Comment by NayamAmarshe** [comment]
> You're providing two tools, one for gui, and one for cli, how should we go about that? I'm thinking of making an upscayl-bin repo that provides upscayl GUI by launching the AppImage, but I'm not sure about the CLI binary that's contained in the git repo. How do you think we should proceed? 
> 
> Maybe create an upscayl-cli repo and keep the build files for the CLI app there? That way a seperate upscayl-cli package can be downloaded from AUR. 
> 
> Or you can add the CLI tool to the releases page, so that one "upscayl-bin" repo contains two binaries - upscayl-gui and upscayl-cli?

The CLI is from Real-ESRGAN, which is a fork of Real-SRGAN by Tencent. Our work is mostly on the GUI side, so it'd be better to release the GUI only under the name of upscayl.

Yes, the AppImage idea sounds fine. Maybe electron-builder can be used to create PKGBUILD but I'm not sure.

**Comment by artogahr** [comment]
> Our work is mostly on the GUI side, so it'd be better to release the GUI only under the name of upscayl.

Got it.

So, an "upscayl-bin" PKGBUILD that provides "upscayl" binary for now, and maybe another "upscayl-git" PKGBUILD that compiles from source a bit later?

**Comment by NayamAmarshe** [comment]
> 

Sounds great! :D

**Comment by artogahr** [comment]
https://daveparrish.net/posts/2019-11-07-HowTo-PKGBUILD-for-AppImage.html

Based on this blogpost I'm thinking of naming it upscayl-appimage, in case you decide to provide actual compiled binaries in the future, what do you say?

One other thing is I will prepare a .desktop file so people installing it can launch it from their app menus, I've created a separate issue for it: #29

**Comment by artogahr** [comment]
Based on discussion in #29 I'll wait for you guys to implement a .desktop file

**Comment by NayamAmarshe** [comment]
> Based on discussion in #29 I'll wait for you guys to implement a .desktop file

You can actually install the flatpak version and take the desktop file from there :)

**Comment by tacerus** [comment]
Repacking a binary release does not make sense. The software shall be built from source as part of the build process. Since this software requires Real-ESRGAN, that should be packaged first, and then used as a dependency for Upscayl.

**Comment by artogahr** [comment]
> Repacking a binary release does not make sense. The software shall be built from source as part of the build process. Since this software requires Real-ESRGAN, that should be packaged first, and then used as a dependency for Upscayl.

This is regarding to the PKGBUILD, yes? 
I generally agree, but having *-bin of packages make installing much easier, I've dealt with many cases where I couldn't build a package for one reason or other, but -bin version came to the rescue. I want to make the easily installable version available first, then I'll work on ironing the kinks out with a built version. I'm not much expreienced with this stuff admittedly, so feel free to give input. What do you propose?

**Comment by tacerus** [comment]
> This is regarding to the PKGBUILD, yes?

Yes.

> I generally agree, but having *-bin of packages make installing much easier,

Interesting, I didn't know that was a thing with Arch Linux. Maybe the policies there are different - I expected PKGBUILD's needing to be reproducible, the same way as other packaging formats. In this case I unfortunately can't give any better input, sorry for the trouble!

**Comment by artogahr** [comment]
I found time to look into it a bit, I have a starting point for a PKGBUILD, but I still think we should include the .desktop file and the icons in the git repo or the AppImage itself, I don't see an obvious way to get these from the Snap package, while using the PKGBUILD to build it...

**Comment by NayamAmarshe** [comment]
We'll release `.pacman` files in the next update.

**Comment by artogahr** [comment]
Oh, so the strategy changes. I'll wait for the next release then, thank you.

**Comment by NayamAmarshe** [comment]
There's already an Upscayl package on AUR (Arch btw).

https://aur.archlinux.org/packages/upscayl-bin

**Comment by artogahr** [comment]
@prurigro beat me to it huh :smile: I'll leave it to him then. Thanks!

**Comment by prurigro** [comment]
Ahh apologies- I didn't catch this issue and wanted to get a package going so I could install it myself :)
