### ISSUE TITLE
Add an error message if vulkan is not properly detected

### ISSUE THREAD

**Issue by presi300** [upscayl/upscayl#150]
Currently, if vulkan is not detected/doesn't work properly, Upscayl just doesn't work without giving any indication as to why...

**Comment by NayamAmarshe** [comment]
> Currently, if vulkan is not detected/doesn't work properly, Upscayl just doesn't work without giving any indication as to why...

Does it say "DECODING ERROR"? If yes, then the next release will contain more info about the error :)
