### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by dima333750** [upscayl/upscayl#154]
Hi, I had such a problem when loading some PNG images (made Fireshot and not only)
I don't understand how to solve it
I attach pictures [test_png.zip](https://github.com/upscayl/upscayl/files/10184895/test_png.zip)
error
![Screenshot_1](https://user-images.githubusercontent.com/10292009/206436141-5cddcee0-cbb8-4d95-8ce8-8bf24c5a6afa.png)

**Comment by NayamAmarshe** [comment]
This is the first time we've seen this error and thousands of people have tested Upscayl so I'm assuming there's something wrong with your OS installation.
Try on a different machine or OS and let me know.

**Comment by dima333750** [comment]
Solved the problem with pure reinstallation
