### ISSUE TITLE
Decoding error when sharping image

### ISSUE THREAD

**Issue by Flishzaco** [upscayl/upscayl#155]
Everytime I put the option to make a sharpen image, an pop-up saying "DECODING ERROR =>" shows up and there is no way to close it without using the task manager to finish the process.

**Comment by NayamAmarshe** [comment]
What GPU?

**Comment by davidemms** [comment]
I get this also. `lsgpu` gives:
```
card0                    Intel Skylake (Gen9)              drm:/dev/dri/card0
└─renderD128                                               drm:/dev/dri/renderD128
```

**Comment by aaronliu0130** [comment]
You appear to have an integrated Intel GPU which isn't currently supported by the upscayl algorithm.
