### ISSUE TITLE
Weird seem artifacts

### ISSUE THREAD

**Issue by voivodpl** [upscayl/upscayl#157]
Hey, not sure if it's a model problem or the actual software, but I noticed 
![example_hf_upscayl_4x_realesrgan-x4plus_edit](https://user-images.githubusercontent.com/45218752/208221634-0ae0dd41-6e0e-48d6-9fa2-91f0ec830d18.png)
![example_hf](https://user-images.githubusercontent.com/45218752/208221637-ab8e809e-e3fd-4117-b4e7-60d14fd7c52b.png)
I got this seems on both of my PC and laptops.

**Comment by aaronliu0130** [comment]
what's the problem here? I don't see any problems in the circled areas in the first image

**Comment by voivodpl** [comment]
> what's the problem here? I don't see any problems in the circled areas in the first image

Zoom in then.

**Comment by aaronliu0130** [comment]
I did?

**Comment by voivodpl** [comment]
![image](https://user-images.githubusercontent.com/45218752/208272296-f77250d8-3c05-41b6-8406-b9d8f6d6bd42.png)

**Comment by aaronliu0130** [comment]
i still don't see anything weird

**Comment by voivodpl** [comment]
There is a visible seem in the last picture, on the main picture there is a lot of them.

**Comment by aaronliu0130** [comment]
What is a "seem"?

**Comment by voivodpl** [comment]
When there is a visible cut in the picture that is an artifact, and looks poorly stiched. There is a method doing SEEMLESS textures, that means if you put them in an array side by side, there is not visible cut between them and they are smoothly joined.

**Comment by NayamAmarshe** [comment]
I don't think this can be fixed by us. You would have to raise the issue with xintao. v2 is gonna have more models though, so one of them might fix this issue.
