### ISSUE TITLE
Getting "Decoding Error =>" on Windows

### ISSUE THREAD

**Issue by Ank221199** [upscayl/upscayl#158]
I have Dell G7 7588, and getting a decoding error, I try windows graphics to use Nvidia GTX 1060 but didn't work, I have also tried every single options in the upscayl.

So tried to put the image in the empty folder but it didn't work! please help

**Comment by Ank221199** [comment]
![image](https://user-images.githubusercontent.com/40303711/208243982-5ebe5902-a62f-46ab-8f28-9b29d8879616.png)

**Comment by withdavid** [comment]
Same issue aswell

**Comment by aaronliu0130** [comment]
Could you guys try to do the development run which will show logs? Download and install git from https://git-scm.com/download/win and node from https://nodejs.org/en/download/current/ (choose standalone installer 64 for both) then run these in your terminal:
```sh
git clone https://github.com/TGS963/upscayl
cd upscayl
npm install
npm run start
```
After the last command, upscayl should show up. Reproduce the error, send a screenshot of the entire window, and send out the terminal output.

**Comment by bibliotest** [comment]
Same issue with Kubuntu 22.04 using Upscayl-1.5.5.AppImage

**Comment by Fordiboii** [comment]
Same issue on Windows 10, Nvidia GeForce GTX 1050 ti. 

GUI client error message:
![image](https://user-images.githubusercontent.com/26767597/209210042-1098d242-e370-47ce-abc0-903a72551ed8.png)

Console error:
![image](https://user-images.githubusercontent.com/26767597/209210173-c692abc2-0d7b-4b19-9c96-8bb776652d8d.png)
