### ISSUE TITLE
[BUILD] error in /renderer/pages/index.tsx

### ISSUE THREAD

**Issue by ManuLinares** [upscayl/upscayl#159]
```
./pages/index.tsx:522:17
Type error: Type 'string' is not assignable to type 'number'.

  520 |             <>
  521 |               <ImageOptions
> 522 |                 zoomAmount={zoomAmount}
      |                 ^
  523 |                 setZoomAmount={setZoomAmount}
  524 |               />
  525 |               <ReactCompareSlider
```

System: Linux arch
npm version: 8.19.2
upscayl: latest git

**Comment by ManuLinares** [comment]
Thanks, but why bury the fix in a generic "Updated Readme" commit? And no mention at all in the issue closing

https://github.com/upscayl/upscayl/commit/d81c3ed217cccb81c7b9ea1059051a7e70ea0953

**Comment by NayamAmarshe** [comment]
> Thanks, but why bury the fix in a generic "Updated Readme" commit? And no mention at all in the issue closing
> 
> https://github.com/upscayl/upscayl/commit/d81c3ed217cccb81c7b9ea1059051a7e70ea0953

Sorry, I've been very busy so I closed the issues while traveling and didn't post a comment.

I fixed the issue though, so if you pull the latest changes it should be fixed :)
