### ISSUE TITLE
Display path for current image and output folder

### ISSUE THREAD

**Issue by ralacerda** [upscayl/upscayl#16]
There should be some indication to the current image path and the current output folder.
User would have a easier time checking if they are upscaling the right file and if the output folder changed from the default output path.

Here is a suggestion on how to do it.

![Fast mockup](https://i.imgur.com/XKxjj3i.jpg)

I would love to contribute with a Pull Request. The only problem with my current solution is long paths.

**Comment by NayamAmarshe** [comment]
> The only problem with my current solution is long paths.

Yep, this is why I never added the paths in. Also because the image is visible on the right pane anyway, so having a verbose path would not really make much difference.

I'll think about it though, maybe use a truncate class or something.

**Comment by cachandlerdev** [comment]
One possibility could be to show the input file and the export folder names, rather than the whole path. Maybe something like `Input Image: to_upscale.jpeg` and `Output Location: Pictures/`.

**Comment by ralacerda** [comment]
Thanks for considering my idea.

> Yep, this is why I never added the paths in. Also because the image is visible on the right pane anyway, so having a verbose path would not really make much difference.

I agree that having the path for input image might be redundant

> I'll think about it though, maybe use a truncate class or something.

Yeah, truncating was my first thought. The problem is that the most important information is probably at the end, that would end up being truncated. So my next idea was to try to break the line after every "/", but that would take a lot of vertical space.

So maybe using both ideas can work. We add a <wbr /> tag after every "/", this way we have a line break at the best position, we keep the minimal amount of vertical space needed, and we also add the `truncate` class to deal with a folder with a really long name.

Here is what it looks like:

![Screenshot_20220901_154543](https://user-images.githubusercontent.com/19380403/187989769-915e0ae8-f6f0-4993-83a8-2fd17ee017d6.png)
![Screenshot_20220901_154556](https://user-images.githubusercontent.com/19380403/187989776-8a70723a-261b-4f19-80c5-f0b9d9c37e30.png)
![Screenshot_20220901_154607](https://user-images.githubusercontent.com/19380403/187989778-e5cad3f1-ea5b-43b3-806b-021222656663.png)

On the upside, if eventually the button sets the output image with a custom name, the UI is already in place and working.

**Comment by NayamAmarshe** [comment]
I have an even better implementation done :) The next version will use tooltips to show full paths.
