### ISSUE TITLE
Blurry interface 

### ISSUE THREAD

**Issue by majsteeer** [upscayl/upscayl#160]
I dont know how to explain it better but the new 2.0 version constantly gets every of its options blurry and it happens with every theme i select. And I think it would be a nice thing to add 1.5 theme back or make a option to do a custom theme .

Here is a screenshot of how it looks 

![Bez nazwy](https://user-images.githubusercontent.com/118762900/209433626-368192dd-8973-46a6-91ba-23544bab95c3.png)

**Comment by NayamAmarshe** [comment]
Wait, what? I have never seen this issue before. Is some filter being applied to the application? because it sure isn't normal behavior.

**Comment by majsteeer** [comment]
When I took this screenshot I had AeroGlass installed but after I unistalled it I had same effect. It appears to happen when I move upscayls window to other position on screen or resize it and switching to fullscreen makes it clear again. Maybe it is worth to mention that i have an older compilation of windows 10   10.0.14393.1480 to be exact and this issue is not happening on my laptop with windows 11.

**Comment by aaronliu0130** [comment]
I think this is bc your windows display dpi setting is off.

**Comment by majsteeer** [comment]
I have tried to follow this guide https://techcult.com/how-to-fix-scaling-for-blurry-apps-in-windows-10/ but method 1,3 and 4 are not possible to execute on my system because options specified in guide dont exist in my gpedit.msc and setting and compatibility settings (although i found something called turn off dpi scaling for high resolution displays but it didint do anything) only thing I was able to do was to create a DWORD value in HKEY_CURRENT_USER\Control Panel\Desktop but it didint do anything and this path in registry HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop doesnt exist. It maybe important to say that my scale slider is set to 100% in display settings and yes I have a slider there not a menu with options to choose from like they show in guide.

**Comment by aaronliu0130** [comment]
Why wouldn't 4 work?

**Comment by majsteeer** [comment]
because i dont have options specified in 4 they simply dont exist i only have disable display scaling for high dpi stettings and this option is not doing anything for me

**Comment by aaronliu0130** [comment]
Are you sure you right clicked the upscayl shortcut?

**Comment by majsteeer** [comment]
I am absolutely sure
![123](https://user-images.githubusercontent.com/118762900/209565465-7a96bdb5-7778-46e3-a16b-f480605182c9.PNG)

**Comment by NayamAmarshe** [comment]
I'm pretty sure this issue is because of your current machine configuration than anything else.

**Comment by NayamAmarshe** [comment]
Closing this issue as it's not really related to Upscayl.
