### ISSUE TITLE
No output with too large images

### ISSUE THREAD

**Issue by sussyboiiii** [upscayl/upscayl#161]
I was just trying the new version and thought to upscale an 8k image, but after it was done the preview was glitched and i didn't get my picture not that this really is significant or anything just wanted to point this out. And I wanted to thank you for making this programm free.

Im on an M1 Pro with 16GB RAM 
<img width="1332" alt="Bildschirm­foto 2022-12-24 um 12 59 41" src="https://user-images.githubusercontent.com/90244617/209435163-4e4ee853-f09b-4a00-84ac-8b473a8647a0.png">

**Comment by NayamAmarshe** [comment]
Hmm, definitely sus.
Could you please upload the image on imgbb? I could try upscaling it. There are always limits to the upscaling since the binary isn't perfectly bug-free but I can give it a try :)

**Comment by sussyboiiii** [comment]
heres an 8k image not the same one but has the same effect for me, I also used the "general photo (ultrasharp)" upscaling type.
https://ibb.co/dKPctYV

**Comment by thermistance** [comment]
I have exactly the same problem on a Fedora workstation with all my images. (rpm version and appimage version) But on an Ubuntu laptop, no problem, it is working fine. 
 OS: Fedora Linux 36 (Cinnamon) x86_64 
 Kernel: 6.0.15-200.fc36.x86_64 
 Resolution: 1600x900 
 DE: Cinnamon 5.2.7 
 CPU: Intel i7 920 (8) @ 2.668GHz 
 GPU: NVIDIA GeForce 9500 GT 

Congratulations for your application.

**Comment by NayamAmarshe** [comment]
> I have exactly the same problem on a Fedora workstation with all my images (963x682 pixels jpg). (rpm version and appimage version) But on an Ubuntu laptop, no problem, it is working fine. (withh appimage) 
>  OS: Fedora Linux 36 (Cinnamon) x86_64 
>  Kernel: 6.0.15-200.fc36.x86_64 
>  Screen resolution: 1600x900 
>  DE: Cinnamon 5.2.7 
>  CPU: Intel i7 920 (8) @ 2.668GHz 
>  GPU: NVIDIA GeForce 9500 GT 
> 
> Congratulations for your application.
> 

Could it be that Fedora does not have proper vulkan support? We rely on REAL-ESRGAN binary to upscale so it's not really in our hands.

**Comment by NayamAmarshe** [comment]
I checked and it's most definitely an issue with the binary and as such, we can't really fix it. The binary has resolution limits to what it can output :(
