### ISSUE TITLE
Restore old button colors or add option to do that

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#163]
The old buttons looked like a light was shining through. Now it just looks... kinda dull. I'd like it if we could switch to the old ones.

![image](https://user-images.githubusercontent.com/11874211/209450280-84099640-f037-4e3e-acff-8c9a7bb189bd.png)
on a side note, do you have any comments for the flatpak at https://github.com/upscayl/flathub/tree/org.upscayl.app?

**Comment by NayamAmarshe** [comment]
No, this would not be possible since I changed the whole theming system. I'd have to create a totally custom theme for it, so low priority for now 😅

As for flatpak, I had prepared a few files, will push when ready.

**Comment by aaronliu0130** [comment]
aww

**Comment by NayamAmarshe** [comment]
> aww

I'll see if I can add a custom theme.

**Comment by NayamAmarshe** [comment]
I'd allow a PR but no time for it right now :(
