### ISSUE TITLE
GUI not highlighting the selected model option

### ISSUE THREAD

**Issue by RadioactiveRadio** [upscayl/upscayl#165]
App doesn't highlight the option that's being selected. I think it does select the option tho since there's a difference in the detail level but the UI isn't updating until you restart the app.

Package: Appimage
Version: 2.0
OS: Kubuntu 22.04.1 LTS x86_64
Kernel: 5.15.0-56-generic

https://user-images.githubusercontent.com/106451902/209451016-49809e56-58d5-43e5-868f-aa639fa8e395.mp4

**Comment by NayamAmarshe** [comment]
Strange. I'll check it out and push a fix.
