### ISSUE TITLE
Not really Open Source

### ISSUE THREAD

**Issue by opsroller** [upscayl/upscayl#166]
You’re shipping this app with binaries embedded all the way down to the repository, how is anyone going to audit this? How do we know it doesn’t contain any form of malware? Seems like you’re using the GNU Affero license in an incompatible way like a Trojan Horse, and the payload is what’s actually doing all of the work.

**Comment by aaronliu0130** [comment]
![In my fine words, you are utterly stupid.](https://user-images.githubusercontent.com/11874211/209480590-c0dff209-31b6-439d-9513-e10b3ddbc4e4.png)

**Comment by aaronliu0130** [comment]
Plus, if you knew that you should search for duplicates, you'd easily find #27 .
