### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ZuluPilgrim** [upscayl/upscayl#168]
Not an issue but not sure where to ask for assistance. I have a GeForce GTX 1080 Ti. Woul this be a supported GPU and if so, how do I determine the ID?

**Comment by aaronliu0130** [comment]
That should be a supported GPU. Since you have a Nvidia GPU, you can follow their official guide at https://nvidia.custhelp.com/app/answers/detail/a_id/2040/~/identifying-the-graphics-card-model-and-device-id-in-a-pc .

**Comment by ZuluPilgrim** [comment]
Thanks for this

**Comment by aaronliu0130** [comment]
> The method you've described is kinda long and not correct I think 😅
> I'll update the readme later today with the correct method to identify. It involves running Upscayl from terminal and noting the output. Usually, ID 0 is software renderer. 1 is iGPU and 2 is External GPU.

--NayamAmarshe
