### ISSUE TITLE
This project looks awesome , but why you do this ?

### ISSUE THREAD

**Issue by ilovedesert001** [upscayl/upscayl#170]
why marketing it in a this way  ???  very scammy don't you think ?

<img width="864" alt="image" src="https://user-images.githubusercontent.com/15065396/209619190-6b6f6717-2a5a-4fc8-991b-80f45be61bda.png">

**Comment by NayamAmarshe** [comment]
> why marketing it in a this way ??? 

becoz epic fortnite funy chenjlog 😀👍
