### ISSUE TITLE
What about "Default" theme

### ISSUE THREAD

**Issue by LaurentGrenet** [upscayl/upscayl#171]
Hi,

I don't know if this is a bug, or if I do not correctly understand something, but if I choose the Upscayl theme named "Default", it actually applies "DARK".... that is not the theme that was initially used before any change of this option.

**Comment by NayamAmarshe** [comment]
Yeah, dark is default 😅 It's there for the first time 😅

**Comment by LaurentGrenet** [comment]
Very surprising that Dark could be the default, since Darks is **NOT** the theme that comes initially just after Upscayl install...

**Comment by aaronliu0130** [comment]
it is the theme that i get initially

**Comment by NayamAmarshe** [comment]
> Very surprising that Dark could be the default, since Darks is **NOT** the theme that comes initially just after Upscayl install...

https://github.com/upscayl/upscayl/blob/332f9f91bb663fba3e11c5c060d45c46bb0547ef/renderer/components/LeftPaneImageSteps.tsx#L306

**Comment by LaurentGrenet** [comment]
I'm not able to understand the code you send me, nevertheless thank you for it

But what I can say very clearly is that I just did a fresh install of Upscayl on a new Pc that didn't ever had Upscayl installed on it, and at the end
- the theme "looks like" the Light one (and is surely not the dark one)
- and the parameter is said "Default"
See screen copy 1

If then I select any other them, then select back "Default", the theme becomes the "Dark" one, and the parameter is set to "Dark" (and no more "Default")
See screen copy 2

Clearly, this is not really an issue, but I prefered to report it to you since it is clearly NOT what you expect....

Regards
Laurent 
![Screen copy 1](https://user-images.githubusercontent.com/32399301/209847280-54ec7b13-de71-4be0-9062-807d416241af.png)
![Screen copy 2](https://user-images.githubusercontent.com/32399301/209847285-f16df2be-a47b-43d3-8c63-2be5b9698a22.png)

**Comment by NayamAmarshe** [comment]
> I'm not able to understand the code you send me, nevertheless thank you for it
> 
> But what I can say very clearly is that I just did a fresh install of Upscayl on a new Pc that didn't ever had Upscayl installed on it, and at the end
> 
> * the theme "looks like" the Light one (and is surely not the dark one)
> * and the parameter is said "Default"
>   See screen copy 1
> 
> If then I select any other them, then select back "Default", the theme becomes the "Dark" one, and the parameter is set to "Dark" (and no more "Default") See screen copy 2
> 
> Clearly, this is not really an issue, but I prefered to report it to you since it is clearly NOT what you expect....
> 
> Regards Laurent ![Screen copy 1](https://user-images.githubusercontent.com/32399301/209847280-54ec7b13-de71-4be0-9062-807d416241af.png) ![Screen copy 2](https://user-images.githubusercontent.com/32399301/209847285-f16df2be-a47b-43d3-8c63-2be5b9698a22.png)

Thanks for reporting. Sometimes data from previous installation can remain and cause issues like these.
I'll try to fix it though, thanks for reporting.

**Comment by LaurentGrenet** [comment]
Pls read more carefully what I wrote : this **CANNOT** be something coming from previous install : I did my test on a **completely NEW Pc** that had NEVER got any copy of upscayl.

**Comment by NayamAmarshe** [comment]
Well the default theme should be dark in all cases, so not sure why you're receiving the light one tbh. I tested on multiple machines too.

Maybe I missed something? I'll have to reproduce the issue first before fixing it.

**Comment by aaronliu0130** [comment]
Today I opened upscayl on a windows machine with light mode and it also switched to light. Maybe it's reading the system config.
