### ISSUE TITLE
Documentation : What is the "GPU Id" advanced option

### ISSUE THREAD

**Issue by LaurentGrenet** [upscayl/upscayl#172]
Under "Adanced options", there is one I do not understand : "GPU ID"
What is the purpose of this option ?
What difference if it is fulfilled vs empty ?
Where and how to find the value to set ?

**Comment by aaronliu0130** [comment]
See #168

**Comment by NayamAmarshe** [comment]
GPU ID:
gpu device to use (default=auto) can be 0,1,2 for multi-gpu

Sorry clicked the close button accidentally. You can leave it empty, I'll add a note in the readme later.
