### ISSUE TITLE
Cannot save as JPG when using Batch Upscale

### ISSUE THREAD

**Issue by krs-n** [upscayl/upscayl#174]
Cannot save as JPG when using Batch Upscale.
PNG output even if JPG is selected in Advanced Options.

**Comment by NayamAmarshe** [comment]
That's because one of your images is PNG. You can't convert alpha channel in JPG, which is why it outputs JPG.

**Comment by krs-n** [comment]
If I start a batch by specifying a folder that contains only JPGs, I get PNGs.

**Comment by aaronliu0130** [comment]
and you selected jpg output?

**Comment by whoiskevinrich** [comment]
Same issue here. All jpeg files are converted to png on batch operations. I did select jpg in the advanced options.

**Comment by NayamAmarshe** [comment]
Can someone post the terminal output?

**Comment by whoiskevinrich** [comment]
Is there a command-line switch to provide the terminal output? I'm not seeing an obvious option from the GUI

**Comment by NayamAmarshe** [comment]
> Is there a command-line switch to provide the terminal output? I'm not seeing an obvious option from the GUI

If you launch upscayl using terminal, you'll get the GUI and the console output in the terminal.

**Comment by aaronliu0130** [comment]
You may follow these instructions: Download and install git from https://git-scm.com/download/win and node from https://nodejs.org/en/download/current/ (choose standalone installer 64 for both) then run these in your terminal:
```sh
git clone https://github.com/TGS963/upscayl
cd upscayl
npm install
npm run start
```
After the last command, upscayl should show up. Reproduce the error, send a screenshot of the entire window, and send out the terminal output.

**Comment by whoiskevinrich** [comment]
See attached

[upscayl-output.txt](https://github.com/upscayl/upscayl/files/10349662/upscayl-output.txt)

**Comment by NayamAmarshe** [comment]
> See attached
> 
> [Edit] Ignore the first sample, I forgot to switch the output to JPG, but the second sample is correct.
> 
> [~upscayl-output.txt~](https://github.com/upscayl/upscayl/files/10349662/upscayl-output.txt) [upscayl-output2.txt](https://github.com/upscayl/upscayl/files/10349680/upscayl-output2.txt)

As you can see, upscayl sets `-f jpg` correctly.

```
COMMAND: -i D:\Downloads\jpgs -o D:\Downloads\jpgs_upscayled -s 4 -m D:\Source\upscayl\resources\models -n realesrgan-x4plus  -f jpg
```

If it's still outputting PNGs, I suppose it's the realesrgan binary that's buggy, which we honestly can do nothing about :(

**Comment by whoiskevinrich** [comment]
Yes, despite seeing jpg, out still output png

**Comment by NayamAmarshe** [comment]
I guess we'll have to mark this as can't fix then.

**Comment by whoiskevinrich** [comment]
Could you update the UI to no allow output as JPG on batch operations?

**Comment by NayamAmarshe** [comment]
> Could you update the UI to not show the option of output as JPG on batch operations?

Yes I'll do that

**Comment by aaronliu0130** [comment]
#239 reports something interesting:
> "General Photo (Ultramix Balanced)", selected "Advanced Options" then "JPG" - all files were converted, BUT with "General Photo (Real-ESRGAN)" and all files were saved as PNG

**Comment by Charlie-82** [comment]
Pour moi c'est toujours PNG en sortie :(

**Comment by daath** [comment]
It's not just the output filetype that is ignored - it's also upscale algorithm. Batch process always uses "General Photo (Real-ESRGAN)" and outputs PNG regardless of what you choose.

**Comment by ahsanrbaloch** [comment]
Actually it saves as png only until the whole batch is finished. Once it is finished, then all png images automatically get converted to jpg, and saved as jpg as well. You should wait for the whole batch to complete and then check your results.
