### ISSUE TITLE
Auto update doesn't work on Arch based Manjaro (AUR Package)

### ISSUE THREAD

**Issue by RobVor** [upscayl/upscayl#179]
Hey guys. Saw the app on a reddit sub and thought I'd try it out.

Installed from AUR on Manjaro and works fine however when I open the app I receive a notification that a new version, 2.0.1, is being downloaded.

A few seconds later it prompts me to restart to apply the update.

Clicking on 'Restart' does nothing.

Closing the app and then reopening it also doesn't apply the update, instead just goes through the same process again of downloading and asking to restart to apply the update.

**Comment by NayamAmarshe** [comment]
Yeah, the AUR maintainers will need to update it. They're probably using the AppImage which is why you get the update dialog.

I suggest using the AppImage directly.
