### ISSUE TITLE
Portable Installation

### ISSUE THREAD

**Issue by CriticalComposer** [upscayl/upscayl#181]
Is there a way to put Upscayl into a portable mode for the Windows version where the settings are placed in the folder where the .exe is found? Additionally if you could create a zip of this portable version rather than an installer that would be awesome.

**Comment by NayamAmarshe** [comment]
> Is there a way to put Upscayl into a portable mode for the Windows version where the settings are placed in the folder where the .exe is found?

Yes possible. You can clone the project, add "zip" as an export target in package.json probably and get a portable zip.

As for the settings, no I don't think that's possible in the current state.

**Comment by aaronliu0130** [comment]
You can just open the installer as a zip. The data will still be put in %appdata%\Upscayl though.

**Comment by CriticalComposer** [comment]
Are there any plans to create a portable version where settings/data are placed in the same folder as the exe?

**Comment by NayamAmarshe** [comment]
> Are there any plans to create a portable version where settings/data are placed in the same folder as the exe?

Settings/Data placed in same folder as EXE? No.

Portable zip file? Possible.

**Comment by CriticalComposer** [comment]
Thanks for the response. I'll continue to use waifu-2x then and continue my search for a portable upscaler based on ESRGAN.

**Comment by oxou** [comment]
I've built a script to do this.
```batch
@echo off
setlocal

REM Upscayl Portable by <github.com/oxou>
REM Launch Upscayl as Portable
REM
REM Created: 2023-01-03 03:33 PM
REM Updated: 2023-01-03 03:38 PM

set cwd=%~dp0

goto check_data

:check_data
if not exist "%cwd%\data" call make_data
mkdir data
mkdir data\user
mkdir data\user\appdata
mkdir data\user\appdata\local
mkdir data\user\appdata\roaming
goto launch

:make_data
mkdir
goto check_data

:launch

set USERPROFILE=%cwd%\data\user
set PUBLIC=%cwd%\data\user
set PROGRAMDATA=%cwd%\data\user\appdata
set LOCALAPPDATA=%cwd%\data\user\appdata\local
set HOMEPATH=%cwd%\data\user
set ALLUSERSPROFILE=%cwd%\data\user\appdata
set APPDATA=%cwd%\data\user\appdata\roaming

start /B "" "%cwd%Upscayl.exe" %*
exit /B %errorlevel%
```

Save this code in a file named `portable.bat` inside the directory where Upscayl.exe is located.
When you run it it will override environment variables for that process and redirect the contents will be written to the `data\user\appdata\roaming` folder instead of `%appdata%`.

Enjoy!

**Comment by aaronliu0130** [comment]
This is pretty good! I'd like to know why we nest all the folders under "data" though.

**Comment by oxou** [comment]
> This is pretty good! I'd like to know why we nest all the folders under "data" though.

You may get error messages such as these, which are annoying and creating those nested folders is a must. You can specify different name for `data` but the concept is the same.
![image](https://user-images.githubusercontent.com/102489121/210531362-57bada02-e42e-4d6e-95ba-ef72157ca6e1.png)

**Comment by NayamAmarshe** [comment]
@oxou Great work, thanks!
