### ISSUE TITLE
GPU ID option does not working in Windows 10

### ISSUE THREAD

**Issue by honglio** [upscayl/upscayl#182]
I have 2 GPUs on my PC. GPU 1 connects to my monitor, and GPU 0 is idle. It doesn't use GPU 0 to upscale when inputting 0 in the GPU ID option. 

GREAT PROJECT!!! THANK YOU!!!

**Comment by aaronliu0130** [comment]
"0" is not your gpu ID. Please see #168

**Comment by NayamAmarshe** [comment]
> "0" is not your gpu ID. Please see #168. I'm going to open a PR that adds this to the FAQ.

The method you've described is kinda long and not correct I think 😅 

I'll update the readme later today with the correct method to identify. It involves running Upscayl from terminal and noting the output. Usually, ID 0 is software renderer. 1 is iGPU and 2 is External GPU.
