### ISSUE TITLE
Run as a GUI only?

### ISSUE THREAD

**Issue by slives-lab** [upscayl/upscayl#183]
Can this be run from an HPC cluster? Is it a GUI only?

**Comment by oxou** [comment]
The GUI spawns processes which do the operation behind the scenes.
You can investigate this yourself using [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) or [Process Hacker](https://processhacker.sourceforge.io/) by looking at the processes spawned by Upscayl.
In the information you'll see the parameters used for that specific `Upscaling Type` and then you can workaround a script to automate that.

**Comment by aaronliu0130** [comment]
The GUI is only a frontend for the CLI tool REAL-ERSGAN as specified in the README.
>- How does Upscayl work?
>	- Upscayl uses AI models to enhance your images by guessing what the details could be. It uses Real-ESRGAN (and more in the >future) model to achieve this.
>- Is there a CLI available?
>	- The CLI tool is called real-esrgan-ncnn-vulkan and it's available on the Real-ESRGAN repository.
> [Real-ESRGAN: Copyright (c) 2021, Xintao Wang](https://github.com/xinntao/Real-ESRGAN/)
