### ISSUE TITLE
Add AI motion deblurring to upscaling process

### ISSUE THREAD

**Issue by walgarch** [upscayl/upscayl#184]
Hi, I'd love to see a selectable AI motion deblur option added to the upscaling process. Any chance this could happen?

https://github.com/VITA-Group/DeblurGANv2
https://github.com/subeeshvasu/Awesome-Deblurring

**Comment by oxou** [comment]
In my opinion I think this tool should be specifically tailored towards upscaling so as to not mislead the "brand" name. Deblurring is a different thing altogether. Could such thing happen? Sure, but bring in more features similar to that and you'll have a program that's 2 GB in size. It's already a bloated tool just for the fact it ships with Electron...

**Comment by walgarch** [comment]
It seems like a pretty common use case for me. When you upscale, you'll also upscale the motion artifacts making them more apparent (just like the reverse is true when downscaling images)

**Comment by NayamAmarshe** [comment]
Not possible unless you can find an ESRGAN compatible model for deblurring. We cannot add platform specific patches, we need universal solutions that depend on NCNN Vulkan.
