### ISSUE TITLE
Double upscale creates higher resolution than stated

### ISSUE THREAD

**Issue by Der-Penz** [upscayl/upscayl#188]
I upscaled an Image (800x800) with double upscale and the text beneath the upscale buttons tells it upscales to 6400x6400 but the output image is 12800x12800.
Input Image:
![image](https://user-images.githubusercontent.com/99838921/210169608-397cf41d-13be-41cf-b10a-91629f133a03.png)

upscayl:
![image](https://user-images.githubusercontent.com/99838921/210169625-d04f2f7e-bd36-481d-bdf3-fcd3f6ab5668.png)

Output Image:
![output](https://user-images.githubusercontent.com/99838921/210169588-318169c2-36b3-4efd-b993-b62d69562777.png)

**Comment by NayamAmarshe** [comment]
Ah crap haha. I forgot it's 4x multiplied by 4x, not 8x haha.

**Comment by Der-Penz** [comment]
Is there a way to select a specific multiplier like 8x?

**Comment by NayamAmarshe** [comment]
> Is there a way to select a specific multiplier like 8x?

Nope
