### ISSUE TITLE
How to check if Vulkan is installed

### ISSUE THREAD

**Issue by Key-Snapper** [upscayl/upscayl#190]
upscayl 2.0.1 appimage or deb don't work on my Linux Mint 20.3 Cinnamon desktop.
There is no error message but also no result.
Maybe my Radeon R7 240/340 has no Vulkan. 
How can I check?

**Comment by NayamAmarshe** [comment]
The best way is just to search "CARD NAME vulkan"

https://www.reddit.com/r/Amd/comments/4guzbm/does_the_radeon_rx_200_series_support_vulkan/
