### ISSUE TITLE
Feature request: Watchfolder

### ISSUE THREAD

**Issue by davidvb** [upscayl/upscayl#192]
A watchfolder that will automatically trigger upscaling (using pre-configured setting ) as soon as a new file is detected, would be an glorious feature to have! — Sharing that watchfolder on the local network will allow users to use Upscayl indirectly from mobile devices and tablets as well, which would be brilliant!

**Comment by aaronliu0130** [comment]
Upscayl using REAL-ERSGAN to upscayl files, as said in the README. You can see https://stackoverflow.com/questions/4060212/how-to-run-a-shell-script-when-a-file-or-directory-changes for how to run something when watchfolder changes on linux/mac and https://devblogs.microsoft.com/scripting/how-can-i-automatically-run-a-script-any-time-a-file-is-added-to-a-folder/ for windows.

**Comment by davidvb** [comment]
> Upscayl using REAL-ERSGAN to upscayl files, as said in the README. You can see https://stackoverflow.com/questions/4060212/how-to-run-a-shell-script-when-a-file-or-directory-changes for how to run something when watchfolder changes on linux/mac and https://devblogs.microsoft.com/scripting/how-can-i-automatically-run-a-script-any-time-a-file-is-added-to-a-folder/ for windows.

Thank you for this. Ill try that, but it would still be preferable to have this as a feature in the app itself.

**Comment by NayamAmarshe** [comment]
Hi, sorry I don't think we can add this feature. Not only would this take a lot of effort but it's also something you can do with just scripts instead of requiring a specialized GUI.
