### ISSUE TITLE
Pasting from clipboard is still broken

### ISSUE THREAD

**Issue by fixups** [upscayl/upscayl#193]
This issue (#108) is marked as solved, but is not.

I have commented in the issue itself, but as it is closed I guess that nobody will notice, so I repeat my comment here (let me know if it's not the right way):

I'm testing Upscayl 2.0.1 and this bug is still not fixed.

The exact same problem as in my original post (issue #108) is still present. I have not tested 2.0, so I'm not sure in which version it has been fixed, but it's certainly not in 2.0.1. Pasting an image with:

1. Start Upscayl
2. Switch to the file manager window (Caja), press Ctrl-C while on a JPG file, then
3. Switch to the Upscayl window, then press Ctrl-V

...does nothing.

I'm using the AppImage version under Ubuntu 20.04 MATE.

This used to work on this same system with the AppImage version, I think it was version 1.2 or something. It did not work anymore in 1.5 and has never worked for me since. The reason Copy/Paste is important is because dragging a file from the file manager to the Upscayl window works only half of the time, so Ctrl-C Alt-Tab Ctrl-V would be fast and easy.

Thank you for investigating this issue. I really appreciate the work you are doing.

**Comment by NayamAmarshe** [comment]
The issue is already listed in the To-Do List: https://github.com/upscayl/upscayl/issues/5

Pasting images from clipboard only works when it's a real file and not just BASE64 data. The issue is with turning BASE64 into a real image that can be fed to Real-ESRGAN as a path. This is why it doesn't work and never has.

I tried to do it but it's not as easy as it looks. I'd first have to detect whether the image is BASE64 or not, then send it to main process, then the main process would use a library or something to convert the BASE64 into JPG or PNG which in itself is another difficult task to determine, then the main process would send this info back to renderer in which case the renderer would have to prompt the user to enter an output path because the image can only be temporarily saved after which the ncnn vulkan binary would upscale the temporarily saved image and do its work.

It's not an easy task to solve and possibly would require another library which is why I didn't do it.

**Comment by fixups** [comment]
There is a misunderstanding here.

I'm **not** pasting an image as binary data.

I'm pasting an image file from the file manager. If you read issue #108, I have carefully explained that what is pasted is actually a **file path**.

Please read issue #108, that you had marked as solved. It's not solved. In #108 I explain what I am doing, which is extremely simple, and does not involve pasting binary data.

**Comment by NayamAmarshe** [comment]
> There is a misunderstanding here.
> 
> I'm **not** pasting an image as binary data.
> 
> I'm pasting an image file from the file manager. If you read issue #108, I have carefully explained that what is pasted is actually a **file path**.
> 
> Please read issue #108, that you had marked as solved. It's not solved. In #108 I explain what I am doing, which is extremely simple, and does not involve pasting binary data.

Oh sorry, I got different issues mixed up.

You're right, it's not working for me either which is strange because it should be. I'll fix this in the next version, sorry for the misunderstanding.

**Comment by fixups** [comment]
The issue is still present in the latest version (2.5.5).

**Comment by aaronliu0130** [comment]
Ok, thanks for confirming. @NayamAmarshe will be focusing on other projects for a while so this unfortunately probably won't get fixed for about 2 weeks.

**Comment by NayamAmarshe** [comment]
I promise I'll try fixing it this time.
I always forget due to so many issues.

**Comment by NayamAmarshe** [comment]
This is an issue because pasting from file data is not supported in the chromium window.
Unfortunately, I can't do anything about it.

**Comment by fixups** [comment]
Guys, are you sure you have read my description?

Again, I'm not pasting file data, I'm pasting the FILE NAME.

NayamAmarshe has already apologized for not reading/understanding the issue I was reporting. Are we stuck in an infinite loop here?

**Comment by aaronliu0130** [comment]
@NayamAmarshe  is it possible to detect pasting a path into the window?

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe  is it possible to detect pasting a path into the window?

Yes but the whole right pane would have to be an input then, which would interfere with drag and drop capabilities.

**Comment by NayamAmarshe** [comment]
> Guys, are you sure you have read my description?
> 
> Again, I'm not pasting file data, I'm pasting the FILE NAME.
> 
> NayamAmarshe has already apologized for not reading/understanding the issue I was reporting. Are we stuck in an infinite loop here?
> 
> 

I know what you mean, but I think something changed in the recent electron versions.

I tried to paste but it received no file path, otherwise it'd have been an easy fix.

I'll try another distro.
