### ISSUE TITLE
Upscale output on 96DPI?

### ISSUE THREAD

**Issue by microchipmatt** [upscayl/upscayl#196]
I feed in an image JPG or PNG, that is 300 DPI, unfortunately once I upscale and output the image, imgscayl only outputs the image at 96DPI, is there a way for me to output 300 DPI?

**Comment by NayamAmarshe** [comment]
No sorry, I don't think so. The Real-ESRGAN binary modifies the original image and we can't do anything about it at the moment :(

**Comment by netsvetaev** [comment]
DPI is just a number in the file, which needed for a printer. You can change it through Ps or any editor (and leave original resolution as is).

**Comment by sertunc** [comment]
> I feed in an image JPG or PNG, that is 300 DPI, unfortunately once I upscale and output the image, imgscayl only outputs the image at 96DPI, is there a way for me to output 300 DPI?

did you solve the problem? I need to set the dpi value of my png file to 300 for printing, but I don't know how to do it.

**Comment by NayamAmarshe** [comment]
Upscayl v2.8 fixes this issue by copying the EXIF data.
