### ISSUE TITLE
Model License Requirements

### ISSUE THREAD

**Issue by Kim2091** [upscayl/upscayl#198]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

The Remacri, UltraSharp, and UltraMix_Balanced models all require attribution per the license they were released under (CC BY-NC-SA 4.0 https://creativecommons.org/licenses/by-nc-sa/4.0/). 

Original release information and associated licenses: https://upscale.wiki/wiki/Model_Database

(I appreciate my models being included, but this is a violation of the license terms)

### Expected Behavior

Simply adding attribution per the website's terms in your documentation would be sufficient. Thank you

**Comment by aaronliu0130** [comment]
There are two ways we could go about doing this. One is to just add all the attribution to the README. Would that be enough under CC? If not, we could then add it to the footer in the software. It would look a bit ugly with four lines down there though.

**Comment by NayamAmarshe** [comment]
Thanks for reporting. Sorry I totally forgot about the credits, I knew the license terms but I totally forgot, my bad. I've added the credits now, let me know if there's something else I could add :)

**Comment by NayamAmarshe** [comment]
> One last thing, I think all that needs to be added is the links to the models? This is what it states on the website:
> 
> `If supplied, you must provide the name of the creator and attribution parties, a copyright notice, a license notice, a disclaimer notice, and a link to the material. CC licenses prior to Version 4.0 also require you to provide the title of the material if supplied, and may have other slight differences.`
> 
> All that's supplied with these models is the creator name, license, and link to the model.
> 
> Sorry to be a bug about this, I'd rather not being doing this, but it's important. Thank you for the quick responses slightly_smiling_face
> 
> This is a great program you've got going, it'll make basic upscaling a lot easier for people

No problem :)

I've added the link to your upscale.wiki user page and for the models, I've linked them to https://upscale.wiki/wiki/Model_Database

Would that be okay?

**Comment by Kim2091** [comment]
That looks sufficient, thanks!
