### ISSUE TITLE
Issues with the included UltraSharp model

### ISSUE THREAD

**Issue by Kim2091** [upscayl/upscayl#199]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

The UltraSharp model in Upscayl doesn't output comparable results to the model when used separately.  I believe the model files may have gotten swapped with another set by mistake? When the model files are manually replaced in the program's files with the original released set (NCNN FP16), the output is as expected.

### To Reproduce

Run an image through the UltraSharp model in Upscayl, and compare it to the same image processed with another ESRGAN tool (chaiNNer, ESRGAN cli, Real-ESRGAN NCNN). The results are very different.

### Expected Behavior

Described this above

### Version/Commit Hash

2.0.1

### OS Specifics

Windows 11 22H2, 3070 ti

**Comment by NayamAmarshe** [comment]
Thanks. I'll check again. It's possible that I added the wrong files in there, happens when I rush the releases😅

**Comment by NayamAmarshe** [comment]
Tracking: https://github.com/orgs/upscayl/projects/1

**Comment by NayamAmarshe** [comment]
I've updated the model with the correct one :)
