### ISSUE TITLE
[Feature Request] Preview Upscale without Writing to Disk

### ISSUE THREAD

**Issue by cachandlerdev** [upscayl/upscayl#20]
In another upscaling tool I used in the past, Gigapixel AI, the user could open an image in the app and preview a portion of the image at a higher resolution without writing it to disk. This made it possible to try the various upscaling models without cluttering the export directory, and then the user could save the final image once satisfied. 

Admittedly, in Upscayl's current state, the feature doesn't make quite as much sense as in the other application I mentioned, since there's no sliders or additional settings that can be tweaked before exporting. However, if later down the line you guys plan on adding more options to the app, the ability to preview the upscaled image before exporting could be a nice addition.

As for the actual logic behind a feature like this, my guess is that the upscaled image would either be loaded in memory for viewing or saved to a temporary directory where it could be looked at before being moved to the export location.

Thanks for working on the app!

**Comment by NayamAmarshe** [comment]
You're absolutely right. We actually had this functionality in the earlier stages but we had to drop it because we found a way to do it without caching results.

Maybe we'll bring it back if the app requires it :)

**Comment by NayamAmarshe** [comment]
We'll add this feature when we add more upscale options in later versions.
