### ISSUE TITLE
Support for more models

### ISSUE THREAD

**Issue by NaveenUpadhyaya** [upscayl/upscayl#200]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

The currently available models in Upscayl don't provide good upscaling for old photos restoration.

### Description

Is it possible for users to add more models themselves, like other GUI's like Cupscale? If not, would you consider adding other models helpful for old photo restoration, or functionality that can enable users to add models?

### Alternatives

Using other GUIs.

**Comment by NayamAmarshe** [comment]
> Is it possible for users to add more models themselves, like other GUI's like Cupscale?

Yes, that is the plan :)

**Comment by WaGi-Coding** [comment]
idk if that depends on the models, but i'd like to be able to change the upscale rate. I want to upscale twice, but the second time makes it way too big ^^ "Double Upscale" is only available for single images, not batch image upscaling. And i don't even know how that works, as the "?" info on it does not work at all ._.

**Comment by NayamAmarshe** [comment]
> idk if that depends on the models, but i'd like to be able to change the upscale rate: https://github.com/upscayl/upscayl/issues/8

**Comment by WaGi-Coding** [comment]
> > idk if that depends on the models, but i'd like to be able to change the upscale rate
> 
> #8

many thanks. I now upscale once, then shirnk the image 50% and upscale again. Not only for that, some functions for before & after upscaling would be nice to have. Like resizing, cropEdges, cropEdgesAndStretchBack.

Greetings

**Comment by NayamAmarshe** [comment]
Tracking: https://github.com/orgs/upscayl/projects/1/
