### ISSUE TITLE
Please don't block a large batch job on one input bad image

### ISSUE THREAD

**Issue by Shedletsky** [upscayl/upscayl#204]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

I have a folder of 22,000 images I want to upres.

Upscayl occasionally chokes on an image (not sure why, they are all PNGs), pops a model with an error, and blocks the whole job until I come back to my machine and click "OK".

This could be better in two ways:
1. Wait until the entire batch is done and then
2. Pop up a list of images that failed to upscale (maybe with an option to try again)

Right now it doesn't even tell me what images are supposedly corrupt, so its pretty unactionable.

### Description

Don't ever block a batch job on an error modal.

### Alternatives

I could write a bot that detects the modal and clicks "OK" on it whenever it pops up.

**Comment by NayamAmarshe** [comment]
That's not me, that's the Real-ESRGAN throwing the error and stopping midway I believe.
I'll see if I can do something about it.
