### ISSUE TITLE
Add a JPEG artifact removal option

### ISSUE THREAD

**Issue by quontrol** [upscayl/upscayl#205]
### Checklist

- [x] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

When upscaling an image, I find that Upscayl will upscale JPEG Artifacts as well. While annoying, not an immediate problem.

### Description

By adding a JPEG artifact removal option pre-upscale (a checkbox and a dial for artifact removal strength)

Implementing something like [Towards Flexible Blind JPEG Artifacts Removal](https://arxiv.org/abs/2109.14573) [github link](https://github.com/jiaxi-jiang/FBCNN) will help _me_ at least. (open source also!)

[A Live demo here](https://huggingface.co/spaces/danielsapit/JPEG_Artifacts_Removal)

### Alternatives

Yes, a separate program, running something like https://arxiv.org/abs/2109.14573 [(github link)](https://github.com/jiaxi-jiang/FBCNN) will remove JPEG artifacts.

**Comment by NayamAmarshe** [comment]
Hi, sorry I don't think I'll be able to make time for it :( I don't see any vulkan NCNN binaries to run this either, so pretty difficult.

**Comment by quontrol** [comment]
> Hi, sorry I don't think I'll be able to make time for it :( I don't see any vulkan NCNN binaries to run this either, so pretty difficult.

That's alright I made this before I fully understood how the 'sharpen' option worked, seems like I just sharpen my images with JPEG artifacts and they come out alright.
