### ISSUE TITLE
Download stalls

### ISSUE THREAD

**Issue by stefonarch** [upscayl/upscayl#207]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Maybe an GH issue, but download from webpage fails aways, `wget` stops at 41%, using `wget -c`  relaunching 4 times it worked,  stopping again at 66 and 77%

### To Reproduce

Download  it.

### Expected Behavior

It should download in one run

### Version/Commit Hash

appimage

### OS Specifics

arch, amd

**Comment by aaronliu0130** [comment]
Definitely an issue with your network. Also we wanted an actual version and specific OS info though it shouldn't matter.
