### ISSUE TITLE
Propose you app through flathub & appimagehub

### ISSUE THREAD

**Issue by BirdInFire** [upscayl/upscayl#21]
Flat hub submission : https://github.com/flathub/flathub/wiki/App-Submission
For appimage hub i don't know how to do it ; https://www.appimagehub.com/

But since you already propose their format, at lease publish them on the hub to a better discoverability.

Thanks !

**Comment by NayamAmarshe** [comment]
Yes, that is planned. First need to fix the few remaining bugs :)

**Comment by NayamAmarshe** [comment]
Need help with the manifest.

**Comment by PranavBhattarai** [comment]
waiting for upscale to come in flatpak/flathub.

**Comment by NayamAmarshe** [comment]
It's up on AppImageHub

**Comment by PranavBhattarai** [comment]
I think u will reach a wider audience if you provide Flatpak/Flathub (with due RESPECT to AppImage).

**Comment by NayamAmarshe** [comment]
> 

Yeah, have to test the flatpak manifest, it's a headache 😅

**Comment by PranavBhattarai** [comment]
Take your time.

**Comment by PranavBhattarai** [comment]
@NayamAmarshe Is it really available in Flatpak?! Because I see nothing...
![image](https://user-images.githubusercontent.com/32763112/195019974-16d72aa4-b9ee-43ec-9b1a-41dc0689dd9a.png)
