### ISSUE TITLE
Combine multiple images into a super resolution image ?

### ISSUE THREAD

**Issue by shodanx2** [upscayl/upscayl#210]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

In the situation where an image has been taken by two adjacent image sensors

Instead of generating new pixels entirely from scratch, use pixel from multiple images of the same subject to generate the new pixels

### Expected Behavior

Supply one image and then an arbirary number of supplemental pixels

Use pattern matching to align the images as close as possible (alignement might have to be re-done locally every couple pixels, for instance if one sensor is viewing the subject 30 degrees off from the primary sensor)

Then, when generating new pixels, prioritise data from supplement sensors before adding pixels from generative AI model

### Screenshots

https://en.wikipedia.org/wiki/Super-resolution_imaging

In my specific case, I have a dozen cell phone cameras capture a subject from several angles with a lot of overlap between the sensors.

I would like to decompose all video files into a series of png files, one for each frame of each video file.

Then using the frame time code, for each existing frame, generate new inter-frame image from each of the other video angles.

Then combine inter-frame images of overlapping sensors with primary image to generate new upscaled frame.

And finally recombine all frame into a new super spatial and temporal resolution image.

**Comment by NayamAmarshe** [comment]
Sorry, out of the scope of this project :(

**Comment by shodanx2** [comment]
Thanks !
Would it make sense to train a model on all frame of all sensor angles of my scene and then use that model somehow with upscayl ?

**Comment by aaronliu0130** [comment]
It would be possible, but you'd have to train the model first. Upscayl also currently doesn't plan to support training models, but we plan to add support for adding custom models by users (#200). For now you can just replace the files of a model with something compatible with REAL-ERSGAN.
