### ISSUE TITLE
Processed Images still Take Up To Much Space #1 Issue That Needs To Be Fixed.  

### ISSUE THREAD

**Issue by DJboutit** [upscayl/upscayl#211]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

I am upscaling a image set with 133 images average size for the processed image is 330mb whole set is 30gb that is just dumb.  Processed images min size should be 7.5mb max size 18mb nobody want to have processed 50mb+ image a lot of people will stop using the program.  Other image upscalers max image size is like 20mb a lot better than the sizes Upscayl outputs images to.  This is the #1 problem that need to be fix ASAP this is why it takes some images 6 to 8 min to process with 50mb+ size most images take 1 to 2 1/2 min to process.  The 133 image took like 4 1/2 to 5 hrs to process all the image S M H.  IMHO this program is good for image size # up to 4000 until it is fixed

### To Reproduce

Images with the biggest size 4500+

### Expected Behavior

Images should 7.5mb to 18mb not 40mb+ JPGs are compressed 40mb+ image are PNG or Bitmap 

### Version/Commit Hash

2.0.1

### OS Specifics

RX 6600 And Windows 7

### Screenshots

2 Examples 

Original size

![Original Size](https://user-images.githubusercontent.com/38142712/213917135-0fa962c7-2ad0-4840-bfca-959ca1c0c27d.jpg)

Processed size 

![Image Size](https://user-images.githubusercontent.com/38142712/213917159-5abada8d-31b4-4e0e-b6a8-d4c82ffb8c6a.jpg)

Original size 

![Original Size 2](https://user-images.githubusercontent.com/38142712/213917196-a01afaf6-1af8-49aa-bb75-16160facc3c2.jpg)

Processed Size 

![Image Size 2](https://user-images.githubusercontent.com/38142712/213917206-6f4ce6c3-f22f-4554-b74c-5dfccd1d915f.jpg)

**Comment by aaronliu0130** [comment]
Note: Continuation of #116, should be an enhancement not a bug. Either way you haven't provided a solution to "fix" this.

**Comment by DJboutit** [comment]
I do not have a solution to the problem I am not a programmer.  I had to select bug it was the closest I could selection there is nothing for general issues.

**Comment by aaronliu0130** [comment]
No, the closest is Feature Request. You're requesting that images take up less space, and there isn't much wrong with the images as they currently stand.

**Comment by DJboutit** [comment]
I am sorry upscaling images to 50mb+ is just dumb let alone 300mb.  So if you upscale 150 to 200 image and total size for all the images is 10gb to 14gb your saying that is fine no it is not.  100mb+ images take like 90 to 120 seconds to load 3mb to 12mb image take 15 seconds max to load.  Come on nobody keeps 100mb+ images on there computer and raw images from a digital camera max are like 65mb

**Comment by NayamAmarshe** [comment]
I have said it before, multiple times, fixing Real-ESRGAN issues is not what we do. Upscayl is an interface to a binary that does the upscaling.

I can only fix issues that are related to Upscayl, the program, not your upscaled images or your hardware configuration. As for the image sizes, they are sometimes large but that's the best you can get.

As I mentioned before, twice, If you have any issues with the binary, please create them on the Real-ESRGAN repository and not here. Upscayl cannot fix models or the ncnn binary.
