### ISSUE TITLE
Not upscaling images/ Not working

### ISSUE THREAD

**Issue by vivekview** [upscayl/upscayl#213]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Till a week ago Upscayl 2.0.1 works just fine on my system but today when I tried to upscale any image it's doing NOTHING (Not giving any output) on clicking Upscayl (Step- 4) in the app window. Have tried different images, even uninstalled and reinstalled, tried older version 2.0.0 as well but nothing worked. Please fix this issue ASAP. 
**(My system running on Intel i3 8th Gen, 8 GB RAM, Intel UHD Graphics 620, Windows 11 Home).**

### To Reproduce

Don't know about it.

### Expected Behavior

It should upscale images

### Version/Commit Hash

2.0.1

### OS Specifics

Intel UHD Graphics 620

### Screenshots

![Screenshot (355)](https://user-images.githubusercontent.com/123561859/214576806-78f8be75-222c-45c3-9721-8afa6ab9f426.png)
![Screenshot (354)](https://user-images.githubusercontent.com/123561859/214576824-f8ca6ce4-7ffa-448a-ba1e-6faca0ee2893.png)
![Screenshot (353)](https://user-images.githubusercontent.com/123561859/214576843-64642a2e-61c5-4875-8ced-439f2d5e6b72.png)

**Comment by aaronliu0130** [comment]
It should’ve never worked in the first place if your only graphics are Intel UHD Graphics 620, iGPUs especially non Iris from Intel are not supported.

**Comment by NayamAmarshe** [comment]
Intel UHD? Please read the FAQ and the readme, I have mentioned it twice.

**Comment by vivekview** [comment]
> It should’ve never worked in the first place if your only graphics are Intel UHD Graphics 620, iGPUs especially non Iris from Intel are not supported.

I know as per requirement it should Not work on 1st place but it worked and I loved it, I used it since few months. But now it stopped working.

**Comment by NayamAmarshe** [comment]
> 
)

**Comment by aaronliu0130** [comment]
Does sharpen image work?

**Comment by vivekview** [comment]
> Does sharpen image work?

No nothing working now. I tried to install older versions also but its not working now.

**Comment by vivekview** [comment]
> It should’ve never worked in the first place if your only graphics are Intel UHD Graphics 620, iGPUs especially non Iris from Intel are not supported.

> Very sorry, my bad then. I think it's got something to do with a driver update.

After lot of efforts, Finally, It again Started Working on my system. I just have to Re-install two components-
1. Microsoft .NET Core Runtime - 3.1.28
2. Microsoft Windows Desktop Runtime - 7.0.2

And it's working now, although on my GPU it's slower in upscaling images but worth waiting for :)
![Screenshot (367)](https://user-images.githubusercontent.com/123561859/215262829-c5df877f-1caa-4804-a13d-991bb1ed63ca.png)
![Screenshot (369)](https://user-images.githubusercontent.com/123561859/215262847-f5da943b-6b75-474e-ba52-f9f99c299fbe.png)
![Screenshot (370)](https://user-images.githubusercontent.com/123561859/215262851-3a220ce4-e0d8-4d3e-8ea2-893ef5590eae.png)

**Comment by aaronliu0130** [comment]
So it's a runtime problem. I guess we can close this now.

**Comment by NayamAmarshe** [comment]
Awesome! Glad to hear that it's fixed @vivekview :D

**Comment by Hashintha7** [comment]
I did this..but still not working
