### ISSUE TITLE
Upscayle with multiple methods in a batch

### ISSUE THREAD

**Issue by therealjoeblow** [upscayl/upscayl#215]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

Obviously all of the available upscale methods produce different results depending on the source image.  I often find myself having to run it 2, 3 or 4 times with differents method and compare the output files to decide which one worked best for that image.  To do that I have to pick one method, sit and wait until it's done, then pick another method and hit the go button, rinse and repeat.  This is a bit cumbersome.

### Description

To me it would be better if the selection list for the upscale methods had a tick box between each method the user wants to use.  Select your methods, hit the go buttone once, and Upscayle would run each iteration successively without any more user input.

### Alternatives

Manually selecting method 1, hit go, wait, rinse and repeat with other chosen methods.

**Comment by NayamAmarshe** [comment]
Great idea. Will surely add in the next update!

**Comment by aaronliu0130** [comment]
@NayamAmarshe Has this been implemented?

**Comment by NayamAmarshe** [comment]
Nope :(

**Comment by aaronliu0130** [comment]
Should this still be kept closed?

**Comment by NayamAmarshe** [comment]
I think so, yes.
No immediate plans to add this feature. We can reopen in the future if needed.

**Comment by Uhter** [comment]
> To me it would be better if the selection list for the upscale methods had a tick box between each method the user wants to use. Select your methods, hit the go buttone once, and Upscayle would run each iteration successively without any more user input.

Very good idea @therealjoeblow!
