### ISSUE TITLE
Upscayl fails to save output when path contains certain characters

### ISSUE THREAD

**Issue by Marmach** [upscayl/upscayl#217]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Upscayl cannot write an output file if path contains specific characters. In my case, Polish alphabet letter "ę" was used.

Example console output for output file path `C:/zdjęcia`

<details>
	<summary> Click me </summary>
C:\zdj─Öcia\DSCF1141.jpg
≡ƒÜÇ => fileName DSCF1141
≡ƒÜÇ => fileExt .jpg
≡ƒåÖ COMMAND:  -i C:\zdj─Öcia/DSCF1141.jpg -o C:\zdj─Öcia/DSCF1141_upscayl_4x_realesrgan-x4plus.png -s 4 -m C:\Users\Marmach\upscayl\resources\models -n realesrgan-x4plus  -f png
≡ƒÜÇ => upscayl.stderr.on => stderr.toString() [0 NVIDIA GeForce RTX 3080]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3080]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3080]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3080]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 0,00%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 0,57%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 1,14%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 1,70%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 2,27%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 2,84%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 3,41%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 3,98%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 4,55%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 5,11%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 5,68%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 6,25%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 6,82%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 7,39%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 7,95%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 8,52%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 9,09%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 9,66%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 10,23%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 10,80%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 11,36%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 11,93%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 12,50%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 13,07%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 13,64%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 14,20%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 14,77%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 15,34%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 15,91%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 16,48%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 17,05%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 17,61%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 18,18%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 18,75%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 19,32%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 19,89%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 20,45%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 21,02%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 21,59%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 22,16%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 22,73%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 23,30%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 23,86%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 24,43%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 25,00%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 25,57%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 26,14%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 26,70%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 27,27%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 27,84%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 28,41%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 28,98%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 29,55%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 30,11%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 30,68%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 31,25%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 31,82%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 32,39%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 32,95%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 33,52%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 34,09%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 34,66%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 35,23%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 35,80%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 36,36%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 36,93%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 37,50%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 38,07%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 38,64%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 39,20%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 39,77%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 40,34%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 40,91%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 41,48%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 42,05%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 42,61%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 43,18%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 43,75%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 44,32%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 44,89%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 45,45%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 46,02%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 46,59%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 47,16%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 47,73%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 48,30%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 48,86%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 49,43%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 50,00%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 50,57%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 51,14%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 51,70%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 52,27%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 52,84%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 53,41%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 53,98%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 54,55%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 55,11%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 55,68%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 56,25%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 56,82%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 57,39%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 57,95%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 58,52%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 59,09%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 59,66%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 60,23%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 60,80%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 61,36%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 61,93%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 62,50%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 63,07%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 63,64%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 64,20%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 64,77%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 65,34%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 65,91%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 66,48%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 67,05%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 67,61%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 68,18%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 68,75%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 69,32%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 69,89%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 70,45%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 71,02%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 71,59%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 72,16%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 72,73%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 73,30%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 73,86%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 74,43%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 75,00%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 75,57%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 76,14%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 76,70%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 77,27%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 77,84%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 78,41%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 78,98%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 79,55%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 80,11%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 80,68%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 81,25%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 81,82%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 82,39%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 82,95%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 83,52%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 84,09%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 84,66%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 85,23%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 85,80%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 86,36%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 86,93%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 87,50%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 88,07%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 88,64%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 89,20%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 89,77%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 90,34%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 90,91%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 91,48%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 92,05%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 92,61%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 93,18%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 93,75%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 94,32%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 94,89%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 95,45%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 96,02%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 96,59%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 97,16%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 97,73%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 98,30%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 98,86%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 99,43%

Done upscaling
</details>

### To Reproduce

E.g. set output cat to `C:/TĘST` instead of `c:/TEST` and try to upscale any image.

### Version/Commit Hash

2.0.1

### OS Specifics

Windows 10, RTX 3080

### Screenshots

Example graphic output

![obraz](https://user-images.githubusercontent.com/32894259/215606497-0f7cd12d-590f-46b7-97cb-c77069076a4f.png)

**Comment by aaronliu0130** [comment]
Expected behavior is what should've happen, not what currently happens.

**Comment by Marmach** [comment]
I guess I need more sleep. Corrected.

**Comment by NayamAmarshe** [comment]
I'll see if this can be fixed.

**Comment by aaronliu0130** [comment]
Does #292 resolve this?

**Comment by NayamAmarshe** [comment]
> Does #292 resolve this?

Yep

**Comment by NayamAmarshe** [comment]
We need to refine our issue tracking. I didn't properly use issues for project tracking.
