### ISSUE TITLE
Support for face restoration.

### ISSUE THREAD

**Issue by Arka078** [upscayl/upscayl#219]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

The upscayl for face models is not available.

### Description

you can use this for face restoration https://github.com/TencentARC/GFPGAN

### Alternatives

alternatively you can work with other project.

**Comment by NayamAmarshe** [comment]
Discussed before, currently not in the scope of the project.
Will add it if I have time.

**Comment by Arka078** [comment]
ok

**Comment by Snipees** [comment]
I would love to use this wonderful app for face restoration/enhancement. 
GFPGAN algorithm is spectacular to realize this job !
Thanks anyway for your work ❤️

**Comment by aaronliu0130** [comment]
@Snipees In that case, you might want to watch #200 and https://github.com/orgs/upscayl/projects/1?pane=issue&itemId=22018634
