### ISSUE TITLE
Upscayl uses the wrong algorithm

### ISSUE THREAD

**Issue by fixups** [upscayl/upscayl#221]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Upscayl uses the default RealESRGAN every time you start it, even if another algorithm (for example Ultramix balanced) is selected.

### To Reproduce

- Open Upscayl
- Drag an image to the Upscayl window.
- Select the "Ultramix balanced" algorithm in the "Select upscaling type" box.
- Click on UPSCAYL. It generates an upscaled image using the Ultramix balanced algorithm. Good.
- Close Upscayl
- Open Upscayl again
- Drag another image to the Upscayl window (or the same image, it does not matter).
- You can see that "Ultramix balanced" is selected in the "Select upscaling type" box.
- Just press ESC to close the list of available algorithms, because we do want to use Ultramix balanced.
- Click on UPSCAYL. It generates an upscaled image using the RealESRGAN algorithm. Not good.
- Close Upscayl, curse and write a bug report.

### Expected Behavior

Upscayl should have used the "Ultramix balanced" algorithm, the one that was selected, resulting in the user not cursing and not writing a bug report.

### Version/Commit Hash

2.0.1

### OS Specifics

AMD Ryzen 5 5600G with Radeon Graphics
Ubuntu 20.04 MATE

**Comment by NayamAmarshe** [comment]
Ok, noted. I'm kinda busy this month so will start the work as soon as I get some time.

**Comment by NayamAmarshe** [comment]
Tracking: https://github.com/orgs/upscayl/projects/1
