### ISSUE TITLE
[Close me:] praise and thanks

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [upscayl/upscayl#226]
I would just like to say that Upscayl is marvellous - it does wonders for images that I use in presentations. (True, subsequently I must compress the resulting images, because they consume too many resources; but what I end up with looks much better than that with which I started.) A few images, particularly those containing text, do not work out well (whatever Upscayl settings I use) but in the main the results are tremendous. The program is easy to use, too. So, thank you for this program!

**Comment by NayamAmarshe** [comment]
Thank you! I'm honestly really glad that my work helped you. It motivates me to do even better.

Sorry for the delay in the new release btw, I'm actually busy with like 5 different things at the moment so haven't gotten time to work on Upscayl.

Hopefully, I will get back to it soon and fix the remaining issues :)
