### ISSUE TITLE
Make version number easily visible in Upscayl sidebar

### ISSUE THREAD

**Issue by quaintdev** [upscayl/upscayl#228]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Currently, the version number is only visible if no image is loaded. If an image is loaded, there is no way to see the version number unless you unload the image by trying to open a new image but not choosing one from the open dialog. This can be inconvenient for users who want to quickly check the version number without having to close their current work.

It would be helpful if the version number was always visible in the sidebar, regardless of whether an image is loaded or not. This would make it easier for users to check the version number without disrupting their workflow.

### Alternatives

NA

**Comment by NayamAmarshe** [comment]
Tracking: https://github.com/orgs/upscayl/projects/1
