### ISSUE TITLE
Suggestion: Please bring double upscale to batch processing

### ISSUE THREAD

**Issue by alanpang1990301** [upscayl/upscayl#232]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Option for double upscale is not available when batch upscale is toggled on.

### Alternatives

Process image one by one.

**Comment by NayamAmarshe** [comment]
Double upscale is actually nothing special. You could run the batch upscale on the upscaled folder again to do it :)

**Comment by alanpang1990301** [comment]
The problem is then the up cable toggle is turned on, the check box for double upscale disappeared. That why it is not possible to run double upscale on folder.

**Comment by aaronliu0130** [comment]
What they mean is you can normal batch upscayl on the folder and then run normal batch upscayl on the output folder containing the upscayl'd media again to achieve double upscayl.
