### ISSUE TITLE
Logs use "/" in front of file name even on windows

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#233]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Logs from #229:
`COMMAND: -i C:\Users\Jessa\Downloads/pexels-artem-podrez-6941448-removebg-preview.png -o C:\Users\Jessa\Downloads/pexels-artem-podrez-6941448-removebg-preview_upscayl_4x_realesrgan-x4plus.png -s 4 -m C:\Users\Jessa\upscayl\resources\models -n realesrgan-x4plus -f png`
"Downloads/pexels-artem-podrez-6941448-removebg-preview.png"
"Downloads/pexels-artem-podrez-6941448-removebg-preview_upscayl_4x_realesrgan-x4plus.png"

### To Reproduce

1. Pirate Windows
2. Do development run
3. Upscayl any image

### Expected Behavior

"Downloads\pexels-artem-podrez-6941448-removebg-preview.png"
"Downloads\pexels-artem-podrez-6941448-removebg-preview_upscayl_4x_realesrgan-x4plus.png"

### Version/Commit Hash

3a0878c

### OS Specifics

I have reproduced this on 22H2 25300.1000 w/ RX 580

### Screenshots

![](https://user-images.githubusercontent.com/126000205/220409271-92d88c69-e136-4717-a8fe-15d204d2b31d.png)

**Comment by NayamAmarshe** [comment]
Thanks for reporting :D 
Does this cause any issues as such?

**Comment by aaronliu0130** [comment]
No, it just stick out agonizing in the logs.

**Comment by aaronliu0130** [comment]
No, it just stick out agonizingly in the logs.
