### ISSUE TITLE
Error code started without warning. Unknow cause. Persistent

### ISSUE THREAD

**Issue by WaterVes82** [upscayl/upscayl#234]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Image of error :  https://ibb.co/p1ycMvW

Task Manager is the only thing that can close the application after this error. 

[ I do not know how to use command line to launch , im a novice windows user. Not Linux user.

### To Reproduce

Do not know what caused this. I put a image png or jpg. Caused this to happen.  images it upscaled before will not. new images get the same error . right now one image worked without error. very confusing. 

### Expected Behavior

For it to work..

### Version/Commit Hash

Latest version as of 2023/2/21

### OS Specifics

1050 ti, win 10 home

### Screenshots

https://ibb.co/p1ycMvW

**Comment by aaronliu0130** [comment]
If you don’t have logs, you may follow these instructions: Download and install git from https://git-scm.com/download (note that git is bundled with macOS) and node from https://nodejs.org/en/download/current/ (choose standalone installer 64 for both) then run these in your terminal (if you don't know what this is, search and open an app on your computer called "Command Prompt" or "cmd" for short):
```sh
git clone https://github.com/TGS963/upscayl
cd upscayl
npm install
npm run start
```
After the last command, upscayl should show up. Reproduce the error and send out the terminal output. `npm` will tell you about audit errors. These are due to #54 and currently expected.

**Comment by Valorian2023** [comment]
Hi! I am getting exactly the same error. It worked last week and now no upscaling works anymore. However, once I proceed with the step you mentioned and use the git clone, it works. Weird.

**Comment by Valorian2023** [comment]
Okay I was finally able to reproduce the error with the gitclone as well.
Here is the relevant excerpt of what the command console said about it.

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 82,29%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 20,83%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 83,33%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 21,88%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 22,92%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 84,38%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 23,96%
vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
85,42%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
78,12%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 98,96%
vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
79,17%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
80,21%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
81,25%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
82,29%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 83,33%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
84,38%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
85,42%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 86,46%
vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 87,50%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
88,54%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 89,58%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
90,62%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
91,67%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 92,71%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
93,75%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
94,79%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
95,83%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
96,88%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 97,92%

­ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4

­ƒÜÇ => upscayl.stderr.on => stderr.toString() 98,96%
vkQueueSubmit failed -4

[7216:0304/011533.927:ERROR:network_service_instance_impl.cc(499)] Network service crashed, restarting service.
[7216:0304/011533.944:ERROR:gpu_process_host.cc(975)] GPU process exited unexpectedly: exit_code=1

**Comment by aaronliu0130** [comment]
This is Windows, right?

**Comment by NayamAmarshe** [comment]
> Now that I closed the git clone and returned to the regular software installed on my computer, I am getting exactly the same error once again. I really cannot explain this. I cannot use the software at all at this point.

This happens because of some weird Nvidia issue. I absolutely have no idea why this happens because it's the same on Linux.

**Comment by Valorian2023** [comment]
Yes, I am working on windows with a Nvidia Geforce GTX 1050. Tried so many things, but nothing works, the program is sadly permanently unusable by now. Is there any workaround I could attempt? It's so weird.

**Comment by NayamAmarshe** [comment]
> Yes, I am working on windows with a Nvidia Geforce GTX 1050. Tried so many things, but nothing works, the program is sadly permanently unusable by now. Is there any workaround I could attempt? It's so weird.

It's your GPU driver causing it.

**Comment by Kacoda** [comment]
This is still an issue and makes it unusable for me as well. I have a Nvidia Geforce GTX 1070.

**Comment by NayamAmarshe** [comment]
> This is still an issue and makes it unusable for me as well. I have a Nvidia Geforce GTX 1070.

Could you please post the logs from 2.5.1?

**Comment by Kacoda** [comment]
[upscayl-log.txt](https://github.com/upscayl/upscayl/files/11464473/upscayl-log.txt)
Here you go

**Comment by aaronliu0130** [comment]
Is that the entire log?

**Comment by NayamAmarshe** [comment]
Seems like a driver issue to me at first glance.

**Comment by Kacoda** [comment]
I did install the latest drivers and it didn't change anything.

**Comment by aaronliu0130** [comment]
Is there nothing more in the log, just these lines?

**Comment by Kacoda** [comment]
Yes, it's not too much indeed.

**Comment by NayamAmarshe** [comment]
> I did install the latest drivers and it didn't change anything.

But I still think it's driver related. You can see the same issue here: https://github.com/nihui/dain-ncnn-vulkan/issues/19
