### ISSUE TITLE
To add ultramix_smooth.bin

### ISSUE THREAD

**Issue by byblo** [upscayl/upscayl#235]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Please add **ultramix_smooth** to the available upscalers, as it can give sometimes the best results on some pictures. (others upscalers always doing something wrong. I can upload an example if necessary)

### Alternatives

unknown

**Comment by aaronliu0130** [comment]
See also #200

**Comment by NayamAmarshe** [comment]
Follow: https://github.com/orgs/upscayl/projects/1

**Comment by aaronliu0130** [comment]
Pretty sure this is about adding a custom model, not just the model not working
