### ISSUE TITLE
[Feature Request] Use Short Description

### ISSUE THREAD

**Issue by git-Hmmm** [upscayl/upscayl#240]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

Currently, the description used by Upscayl is quite large, which affects its appearance in the app list and start menu. 

[Screencast from 2023-03-09 03-52-58.webm](https://user-images.githubusercontent.com/102938585/223865750-02906397-5878-48ca-a2f8-5b8d22ab8fa3.webm)

### Description

It would be helpful if the description could be shortened or optimized to improve its presentation.
I would suggest just keeping, "AI Image Upscaler".

### Alternatives

- Manually edit .desktop file
- Learn ignoring

**Comment by NayamAmarshe** [comment]
Ok, will fix it

**Comment by aaronliu0130** [comment]
@git-Hmmm I'm pretty sure this is fixed, right?
