### ISSUE TITLE
Cant set as desktop background.

### ISSUE THREAD

**Issue by Ehren1337** [upscayl/upscayl#241]
I get black background after setting it as desktop background. I did try other backgrounds without upscayl'd and it works fine.
 Im on latest Windows 11. im assuming windows doesnt like extreme resolution size? ![image](https://user-images.githubusercontent.com/57159721/224192290-451f9e1e-8949-4fc0-acb0-464d253892c1.png)

**Comment by NayamAmarshe** [comment]
I'm not really sure how this is an Upscayl problem. This place is for issues related to Upscayl, not Windows, sorry.
