### ISSUE TITLE
Batch processing images produces PNGs when set to JPG

### ISSUE THREAD

**Issue by dngrlux** [upscayl/upscayl#245]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Batch upscaling with Advanced Options > Save Image As: JPG will produce a folder full of PNGs.

### To Reproduce

Use Batch Upscale
Select folder of images (in my case JPGs)
Open Advanced Settings and select JPG for output
Click UPSCAYL

### Expected Behavior

Expect folder of upscaled images saved as JPGs.

### Version/Commit Hash

2.01

### OS Specifics

Apple M1 Max macOS Monterey 12.6.3

**Comment by NayamAmarshe** [comment]
Duplicate of #239 

I am wware of the issue already. It has already been filed like 3 times.
I'll see what I can do.

**Comment by dngrlux** [comment]
Thanks. I wouldn’t have opened a new issue after searching if any of those dupes were Open.

**Comment by aaronliu0130** [comment]
also dupe of #174
