### ISSUE TITLE
Found this perfect tool, Maybe could be integrated with Upscaly

### ISSUE THREAD

**Issue by deepnx** [upscayl/upscayl#246]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

This could improve the output quality far more.

### Description

I am not an expert coder or anything as I am a media person who loves tech.
I came across this website that uses some new methods to give really amazing images.
I don't know if its online based only or it can be integrated into an app like Upscaly.

But the results are fantastic for low res images.

I have compared with all the modes of Upscaly, And this website results are just mind boggling good.

Dropping the link of the webpage here - 
https://replicate.com/sczhou/codeformer

If somehow this method is integrated to Upscaly it would be magical.

Please excuse my noob behavior if I am wrong.

Thanks

### Alternatives

Given the link above

**Comment by aaronliu0130** [comment]
How do you want this integrated? All I see here is a completely different program that isn't an ESRGAN model.

**Comment by deepnx** [comment]
> 

Sorry sir as i said im not a IT person ... i just love tech and I was just wondering if this were possible ... because their results were astonishing ...

**Comment by NayamAmarshe** [comment]
@aaronliu0130 I do see a Real-ESRGAN model here: https://github.com/sczhou/CodeFormer/releases/tag/v0.1.0

**Comment by NayamAmarshe** [comment]
The results do look great, maybe we can remove one of the models for this. Our current sharpening model is pretty much useless imo, I've never gotten good results with it.

**Comment by deepnx** [comment]
> 

Thanks for your reply sir... i really loved the way they reconstructed the face of several pixilated pictures I tried (def some sort of AI at work)... I've tested about 40+ images and the results are mind blowing ... if it could be added to upscaly it would be magical !

**Comment by PowerScissor** [comment]
Might be an astonishingly dumb question here, but here it goes.  I'm newly on the search for an upscaler / denoiser...so have yet to try one, which led me here.

The results being so great for you, why not continue to use it?  What are the advantages of having it integrated into this app specifically?

Maybe I'm missing something obvious, excuse the lack of knowledge on the subject.

**Comment by aaronliu0130** [comment]
@PowerScissor it's a locally installed gui. though it's still pretty much a webpage (electron) you can use it offline and it also has other models.

**Comment by aaronliu0130** [comment]
Hmm, duplicated by #146?
