### ISSUE TITLE
Faceing issue with upscayl

### ISSUE THREAD

**Issue by sachhu** [upscayl/upscayl#248]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

I am getting below error when I am trying to upscale any image

![image](https://user-images.githubusercontent.com/31276964/226059373-52c9bee9-3cf8-4d74-92ab-4b7e99ff01ce.png)

Configuration
RYzen 9 
Graphics card Nvidia 1660ti
16GB ram

### To Reproduce

After clicking on UPSCAYL button I am getting this error

### Expected Behavior

Tool should not give this error as my GPU is compatible with VULKAN and I am using the latest driver from Nvidia.

### Version/Commit Hash

V2.0.1

### OS Specifics

Nvidia 1660ti, Windows 11

### Screenshots

![image](https://user-images.githubusercontent.com/31276964/226059944-fea89c58-328f-4469-89dc-7ad8f43ca459.png)

**Comment by NayamAmarshe** [comment]
In v2.5, the real-ESRGAN binary will run in a detached mode. Should hopefully fix this issue then :)

**Comment by sachhu** [comment]
> In v2.5, the real-ESRGAN binary will run in a detached mode. Should hopefully fix this issue then :)
> 
> Meanwhile, try upgrading your drivers, or just run upscayl from the codebase using npm.

I will wait for v2.5

**Comment by MoutonBinoclard** [comment]
Ok I've tried with the 1.5.5 version and It worked perfectly fine
Then I retry with the newer version and IT WORKED ????

I searched back for what I did and I found that Nvidia has uploaded new driver! I also update my amd cpu and now it works

**Comment by NayamAmarshe** [comment]
> Ok I've tried with the 1.5.5 version and It worked perfectly fine Then I retry with the newer version and IT WORKED ????
> 
> I searched back for what I did and I found that Nvidia has uploaded new driver! I also update my amd cpu and now it works

Yeah, happens. Nvidia causes a lot of issues sometimes.

**Comment by aaronliu0130** [comment]
@sachhu 2.5 is here, does this still happen?

**Comment by MoutonBinoclard** [comment]
Yes sadly, but that’s very strange :
I completely reinstall all my driver clean
It works once and now it doesn’t work again

I must say that I totally disable auto update driver so nothing changes between the uses of the app.

still don’t understand

**Comment by MoutonBinoclard** [comment]
I’m a 100% sure it’s the amd driver

**Comment by MoutonBinoclard** [comment]
I think that’s because of the weird combination with a amd chipset and Nvidia graphic card

**Comment by NayamAmarshe** [comment]
> I think that’s because of the weird combination with a amd chipset and Nvidia graphic card

Have you tried putting Upscayl in performance mode in advanced display settings? Windows is weird with picking GPUs so you need to manually specify.

**Comment by MoutonBinoclard** [comment]
Yes I tried both with performance and eco mode (eco for the Amd integrated gpu)
Funny thing, a few update before, I can use the two gpu, both of them worked

**Comment by sachhu** [comment]
For me, it started working fine after the update.

**Comment by aaronliu0130** [comment]
Since OP's issue has been solved I'll mark this completed.
