### ISSUE TITLE
wrong double upscale ?

### ISSUE THREAD

**Issue by Dietz33** [upscayl/upscayl#249]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

when i do normal upscale from 1k to 4 k it works . when i use 1k to 8k (double upscale feature) its says 1k to 8k but the final picture is 16k . 

### To Reproduce

try double upscaly .. evertime the same bug for me

### Expected Behavior

8k not 16k as the program says

### Version/Commit Hash

2.01

### OS Specifics

geforce gtx 1080 windows 10

**Comment by NayamAmarshe** [comment]
https://github.com/upscayl/upscayl/commit/8eacbef0a695b5d0b6066aa84a112e74a0a0be34#diff-845b41cc5a70a99511d40abada49d45059aa90d76f388bd2049506ac9eaad748R244

**Comment by Dietz33** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/128226488/226105131-d5aadd2f-eaec-4174-83cf-4b9417c06f7f.png)

**Comment by NayamAmarshe** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/128226488/226105131-d5aadd2f-eaec-4174-83cf-4b9417c06f7f.png)
> 
> i get 16k

You'll need to wait for v2.5 for the fix :)
