### ISSUE TITLE
[Feature Request] Copy-and-Paste Support (and PNG Output?)

### ISSUE THREAD

**Issue by ghalfacree** [upscayl/upscayl#25]
First, thanks for making this - it makes things so much easier than trying to roll your own upscaler!

I've a feature request, however: in my use-case, I'm almost certainly working on an image in The GIMP - and need to export the low-resolution image to disk, upscale it with Upscayl, and load the resulting high-resolution image back into The GIMP again.

What would be a lot more convenient is if I could just copy the image from The GIMP, paste it into Upscayl, and have the upscaled version popped onto the clipboard ready for pasting back into The GIMP - without anything being (manually) written to disk.

I appreciate that might be a challenge, so there's a related ask: at the moment, Upscayl outputs a lossy JPEG image; a lossless PNG output option would be appreciated as a stopgap.

**Comment by NayamAmarshe** [comment]
Sure, I'll add it to to-do
