### ISSUE TITLE
![Screenshot_1](https://user-images.githubusercontent.com/128226488/226105131-d5aadd2f-eaec-4174-83cf-4b9417c06f7f.png)

### ISSUE THREAD

**Issue by Dietz33** [upscayl/upscayl#250]
![Screenshot_1](https://user-images.githubusercontent.com/128226488/226105131-d5aadd2f-eaec-4174-83cf-4b9417c06f7f.png)

i get 16k

_Originally posted by @Dietz33 in https://github.com/upscayl/upscayl/issues/249#issuecomment-1474831924_

**Comment by NayamAmarshe** [comment]
Please don't create more issues. The issue has already been fixed in the latest main branch.

**Comment by Dietz33** [comment]
ok thank u

**Comment by aaronliu0130** [comment]
probably should be not planned close
