### ISSUE TITLE
MidJourney V5 upscalying

### ISSUE THREAD

**Issue by Glenskii** [upscayl/upscayl#252]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

The new V5 is in Alpha and yes I noted the V2.5 pending upgrade so I am hoping the current artifacting introduced in my current test of V2.0.1 is fixed (goes away) as most results are unusable.
If I missed something I apologize but just throwing this out here now.

### To Reproduce

Taking any midjourney render from the released alpha V5 and do upscayl 

On Left original | right - upscayl
![V5_sample](https://user-images.githubusercontent.com/121144324/226174021-4059058b-3f36-42b6-b70d-024bf5bd984a.jpg)

### Expected Behavior

No artifacting should have occured

### Version/Commit Hash

V2.0.1

### OS Specifics

NVIDIA GTX 1080  | Windows 11 Pro V22H2 (Build 25309.1000)

### Screenshots

![V5_sample](https://user-images.githubusercontent.com/121144324/226174436-61f9c694-9364-4fa3-985c-74c5664f5914.jpg)

**Comment by aaronliu0130** [comment]
Are you asking for us to remove image artifacts? If so I don't see any in the image on the right you provided. Also this shouldn't be related to midjourney and you shouldn't have included that in the issue, this is confusing.

**Comment by Glenskii** [comment]
Let me first apologize for any confusion.
What I am saying is that if you look at the image on left (original) then once upscayl'd (on right) you see the introduction of artifacts or noise of blemishes which is very new to me on results. (png image files)
So I am sharing understaning that there is a V2.5 in play and that MJ V5 is only days new to inform.
As it is now, I cannot use it for MJ V5 upscales as about 70% results are as such.

**Comment by aaronliu0130** [comment]
Could you circle/highlight the artifacts?
Also, this might be a problem with our models which we don't make and can't fix unless we find a better model that doesn't introduce artifacts.

**Comment by Glenskii** [comment]
![2023-03-19_091625](https://user-images.githubusercontent.com/121144324/226177773-76b4700c-f546-46d7-8899-a32b685a346d.png)

Here is a link to the sample file shown that you  may try:
[https://www.dropbox.com/s/icrvaqmy8p54bj9/Glenski_Create_a_photorealistic_image_of_a_close-up_view_of_a_w_8e7c130c-167c-44ac-af0d-4513269e54f1G.jpg?dl=0](url)

**Comment by aaronliu0130** [comment]
Alright, I see them now. I believe this is a model issue.
Also, you probably shouldn't use the digital art model for this. This is art that mimics a realistic photo. Digital art is flat.

**Comment by Glenskii** [comment]
While I appreacite the sentiment with regards to the art model, I would not be wasting time if this was my first or 50th use of Upscayl to upscale such renderings hence why I was specific in the indication of V5.
I have suggested, recommeneded and written about Upscayl as a professional photographer and included part of its worth was the way it had done remarkable job with such works from these AI art platforms. (MD 3/4a & b).
So, I am here to simply notify of the situation in the hopes it may be a heads up.

Thanks for the understanding and the follow up.

**Comment by aaronliu0130** [comment]
I don't mean midjourney, i mean the model to upscayl the image.

**Comment by aaronliu0130** [comment]
@Glenskii<https://github.com/Glenskii> I don't mean midjourney, i mean the model to upscayl the image.

**Comment by NayamAmarshe** [comment]
> While I appreacite the sentiment with regards to the art model, I would not be wasting time if this was my first or 50th use of Upscayl to upscale such renderings hence why I was specific in the indication of V5. I have suggested, recommeneded and written about Upscayl as a professional photographer and included part of its worth was the way it had done remarkable job with such works from these AI art platforms. (MJ 3/4a & b). So, I am here to simply notify of the situation in the hopes it may be a heads up.
> 
> Thanks for the understanding and the follow up.

Thanks for reporting the issue but the AI models we're using were created by researchers and AI professionals. As such, Upscayl depends on their fantastic work to provide the upscaling.
In v2, I converted several pre-trained models from PyTorch to NCNN, so artifacts or any kind of weird results are unfortunately out of the scope of Upscayl project or our control.
