### ISSUE TITLE
Upscayl doesnt work anymore with GTX 1650ti

### ISSUE THREAD

**Issue by MoutonBinoclard** [upscayl/upscayl#253]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

When launching the upscayl, it say my gpu need to be vulkan compatible even if it is
The software worked before

### To Reproduce

Just launch the upscayl

### Expected Behavior

Error Message

### Version/Commit Hash

v2.5

### OS Specifics

Windows 10, GTX1650ti (/!\ i'm on a laptop)

### Screenshots

![image](https://user-images.githubusercontent.com/77278792/226560384-4ba4b639-5462-4a90-bd92-667adf7c0c41.png)

**Comment by NayamAmarshe** [comment]
https://github.com/upscayl/upscayl/issues/248#issuecomment-1474573592

**Comment by NayamAmarshe** [comment]
Marking this as duplicate
