### ISSUE TITLE
Doesn't do...much?

### ISSUE THREAD

**Issue by Niphion** [upscayl/upscayl#255]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Hello,
I downloaded Upscayl in the hope to bring some of my lost details back when upscaling, unfortunately I don't get the expected result, I tried with all the upscalers, on photos and also illustrations. But I basically get the same results as I do with ESRGAN
Am I doing something wrong here?

### To Reproduce

-

### Expected Behavior

Add fine details

### Version/Commit Hash

latest

### OS Specifics

Windows 10 and NVIDIA Geforce GTX 1050Ti

**Comment by aaronliu0130** [comment]
> Upscayl uses Real-ESRGAN-ncnn-vulkan binaries to upscale images.
