### ISSUE TITLE
[Question] Recommended tool for upscales models interpolation.

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [upscayl/upscayl#256]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

I want to interpolate between two upscalers models with a ratio different from 0.5, can you please recommend a tool that would allow me to do it on Linux?
I'm familiar more with Stable Diffusion which allows easy merging of models, I have no idea how to do it with upscalers, but it seems to be something that people do from: [Database](https://upscale.wiki/wiki/Dataset_Database).
Thank You!

### Alternatives

No alternatives.

**Comment by aaronliu0130** [comment]
> The ability to use 2 upscalers is not needed imo. You can easily put the images on each other in [PhotoPea](https://photopea.com/) and adjust the opacity of the top image.
—#265
