### ISSUE TITLE
CPU usage VS upscale progress speed

### ISSUE THREAD

**Issue by Wlassko** [upscayl/upscayl#258]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

CPU usage is low and upscayl "magic AI mysteries" speed is then too low, when I use some background CPU heavy use application - then on foreground Upscayl is faster (in magic upscale - does not matter what upscale type is selected), when CPU is not used by background apps too heavy, then Upscayl use CPU only low (CPU frequency fall down).

PS: CPU affinity and priority process does not have effect. In this case is only depend on CPU usage, higher CPU usage = faster upscale progress. I think screenshot is not nescessary. (Sorry for my English, I am simple older man with limited education.)

### To Reproduce

Reproduce this "bug" is easy - try some upscale and test speed times with CPU in idle (only Upscayl in use) and with CPU in boost mode (test some CPU heavy apps) and you will see differences,

### Expected Behavior

Better CPU usage, nothing more :)

### Version/Commit Hash

Upscayl v2.0.1

### OS Specifics

GPU nVidia GTX 970, CPU i5-2500K, Windows 10 x64 22H2

**Comment by aaronliu0130** [comment]
I didn't find any differences in my test. And it shouldn't have differences, Upscayl uses the GPU.

**Comment by fixups** [comment]
I think I have noticed that as well. It does not matter that "Upscayl uses the GPU". It obviously has to use the CPU to feed the GPU, and it's easy to understand that when the scheduler believes the program is idle, it will give it a lower priority, which in turn means that the GPU will wait for data as well (because the CPU does not provide it with work to do). Depending on the system and especially the amount of VRAM, the CPU may have to send a lot of data to the GPU, which it may not do fast enough because the OS erroneously believes this process is waiting for user input or something like that.

**Comment by coolst3r** [comment]
> ### Checklist
> 
>     * [x]  I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
> 
>     * [x]  I have checked that this issue isn't addressed in any other issue or pull request.
> 
> 
> ### Describe the Bug
> 
> CPU usage is low and upscayl "magic AI mysteries" speed is then too low, when I use some background CPU heavy use application - then on foreground Upscayl is faster (in magic upscale - does not matter what upscale type is selected), when CPU is not used by background apps too heavy, then Upscayl use CPU only low (CPU frequency fall down).
> 
> PS: CPU affinity and priority process does not have effect. In this case is only depend on CPU usage, higher CPU usage = faster upscale progress. I think screenshot is not nescessary. (Sorry for my English, I am simple older man with limited education.)
> ### To Reproduce
> 
> Reproduce this "bug" is easy - try some upscale and test speed times with CPU in idle (only Upscayl in use) and with CPU in boost mode (test some CPU heavy apps) and you will see differences,
> ### Expected Behavior
> 
> Better CPU usage, nothing more :)
> ### Version/Commit Hash
> 
> Upscayl v2.0.1
> ### OS Specifics
> 
> GPU nVidia GTX 970, CPU i5-2500K, Windows 10 x64 22H2
> ### Screenshots
> 
> _No response_

might also be windows 10 windows in general is very resource heavy had i7 could not use windows anymore was forced to to use linux

**Comment by aaronliu0130** [comment]
Hate on Windows and Microsoft all you want, but how would Windows affect this?

**Comment by coolst3r** [comment]
> Hate on Windows and Microsoft all you want, but how would Windows affect this?

i am not hating on it just cant use my desktop on it its also just a fact that its more resource intensive i don't care if you use it good on you

**Comment by coolst3r** [comment]
https://www.youtube.com/shorts/upXQQaDTuFM

**Comment by coolst3r** [comment]
> Being more resource intensive does not affect this issue.

read everything and what cpu he has . the cpu he has is a older gen  CPU i5-2500K, Windows 10 x64 22H2

**Comment by coolst3r** [comment]
> Being more resource intensive does not affect this issue.

i had windows on i i7 5 gen and i could barely use it and all he is asking is for it to be more affectation on cpu usage and i understand why and  resources does  affect  you if don't have the newest hardware

**Comment by aaronliu0130** [comment]
The problem is not that Windows is using too much resources, it’s that Upscayl is faster when CPU load is high.

**Comment by shenef** [comment]
My first guess would be that it is a windows 10 scheduler problem or that upscayl is not correctly requesting CPU resources which then causes the CPU to not turbo up (unless it's already turboed up because of another process).

Node.js seems to have a method to control process priority: https://nodejs.org/api/os.html#ossetprioritypid-priority

Maybe the windows scheduler setting in "Advanced System Settings > Advanced > Performance > Settings > Advanced > Processor Scheduling" (wow, that's buried) could also have an impact.

**Comment by vmdao** [comment]
Hi @aaronliu0130,
Could you please suggest ways to limit the resource consumption of the program?

**Comment by NayamAmarshe** [comment]
> I dunno, maybe @NayamAmarshe would after she returns from her 2 week break; but for CPU [this](https://superuser.com/questions/214566/are-there-solutions-that-can-limit-the-cpu-usage-of-a-process) might help you.

I'm a guy 😭

**Comment by NayamAmarshe** [comment]
We've updated the ncnn binaries. If this issue is fixed, great but if not, unfortunately we cannot do anything about it at the moment. 

We need a bigger team (with C++ developers) to maintain the ncnn repository.
