### ISSUE TITLE
upscayl video?

### ISSUE THREAD

**Issue by coolst3r** [upscayl/upscayl#264]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

can you upscale every frame of a video to upscayle it

### Alternatives

nope

**Comment by coolst3r** [comment]
40000 frames yeah

**Comment by NayamAmarshe** [comment]
> 40000 frames yeah

Yeah it's an issue. I tried to integrate video upscaling but, it's kinda not trivial.

**Comment by swrobel** [comment]
Probably worth replacing the [website](https://www.upscayl.org) image which implies that video upscaling is possible with this app
![screenshot](https://www.upscayl.org/screenshot.png)

**Comment by aaronliu0130** [comment]
How does this image imply that video upscayling is possible?

**Comment by swrobel** [comment]
It looks like the website image was just updated today! The old one had an image/video toggle:
![upscayl](https://github.com/upscayl/upscayl/assets/157270/e591d377-ab91-41f3-82c8-fd7c121efb94)

**Comment by aaronliu0130** [comment]
Yea, apparently https://github.com/upscayl/upscayl.github.io/commit/01ecb69c2ce20b4f68dfc992ac2fa65dc46d639c
