### ISSUE TITLE
here a script to seprate a video frames into images  in order

### ISSUE THREAD

**Issue by coolst3r** [upscayl/upscayl#266]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

To separate each frame from a video and name them in order, you can use a video processing library or tool like OpenCV, FFMPEG or PyAV. These tools can extract frames from a video and save them as images. You can then rename the images using a loop in a programming language like Python or bash scripting.

Here is an example Python code using OpenCV library to extract frames from a video and save them as images:

python

import cv2
import os

# Open the video file
video_path = "path/to/video.mp4"
vidcap = cv2.VideoCapture(video_path)

# Create a folder to store the frames
if not os.path.exists("frames"):
    os.makedirs("frames")

# Loop through the frames and save them as images
success, image = vidcap.read()
count = 0
while success:
    # Save the image with a sequential number
    cv2.imwrite("frames/frame{}.jpg".format(count), image)
    
    success, image = vidcap.read()
    count += 1

This code will extract frames from the video at the path video_path and save them in a folder called frames. The frames will be named as frame0.jpg, frame1.jpg, frame2.jpg, etc.

You can modify the code to suit your needs, such as changing the file format, frame rate, or output folder. Just make sure to handle errors and edge cases appropriately.

### Alternatives

maybe

**Comment by coolst3r** [comment]
https://pastebin.com/jTAgc7CC

**Comment by aaronliu0130** [comment]
Firstly thank you for your contributions but this should be in discussions. Secondly, you could just use ffmpeg instead of running python in an Electron (JS/TS, HTML, CSS) environment.

**Comment by NayamAmarshe** [comment]
Thanks for the script. I'll be using ffmpeg for this :)
