### ISSUE TITLE
put frames back toghter into a video

### ISSUE THREAD

**Issue by coolst3r** [upscayl/upscayl#267]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

To put the frames back together in order, you can use a video processing library or tool like OpenCV, FFMPEG or PyAV. These tools can read the frames from the folder and combine them to form a video. You can then save the video using the same library or tool.

Here is an example Python code using OpenCV library to read the frames from the folder and combine them to form a video:

makefile

import cv2
import os

# Read the frames from the folder
frames_folder = "path/to/frames"
frame_names = os.listdir(frames_folder)
frame_names.sort()  # Make sure frames are in order

# Get the first frame to get the video size
first_frame = cv2.imread(os.path.join(frames_folder, frame_names[0]))
height, width, channels = first_frame.shape

# Create the video writer
fourcc = cv2.VideoWriter_fourcc(*"mp4v")  # Choose codec
video_path = "output/video.mp4"  # Choose output path
video_writer = cv2.VideoWriter(video_path, fourcc, 30, (width, height))

# Loop through the frames and add them to the video
for frame_name in frame_names:
    frame_path = os.path.join(frames_folder, frame_name)
    frame = cv2.imread(frame_path)
    video_writer.write(frame)

# Release the video writer and close the video file
video_writer.release()

This code will read the frames from the folder at the path frames_folder, combine them to form a video, and save the video at the path video_path. The frames are assumed to be in order with filenames like frame0.jpg, frame1.jpg, frame2.jpg, etc.

You can modify the code to suit your needs, such as changing the codec, frame rate, or output path. Just make sure to handle errors and edge cases appropriately.

### Alternatives

maybe

**Comment by coolst3r** [comment]
https://pastebin.com/fPJ1Ctmm

**Comment by aaronliu0130** [comment]
Firstly thank you for your contributions but this should be in discussions. Secondly, you could just use ffmpeg instead of running python in an Electron (JS/TS, HTML, CSS) environment.

**Comment by coolst3r** [comment]
took me 4 minutes to do this this is for upscaling videos lmao you sayed it is hard to do

**Comment by NayamAmarshe** [comment]
I could write a bash script under a minute to do the same but that's not what's it about. We're dealing with different stacks here, Upscayl is a GUI program, not really a script runner.

**Comment by franva** [comment]
thanks for this request, I too have this need. Hopefully, we can see that Upscayl recognizes this function and adds it into the power tool.
