### ISSUE TITLE
Add Unbluring Feature

### ISSUE THREAD

**Issue by EdisonCC** [upscayl/upscayl#275]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

May I ask if it is possible to add images without magnification and process them based on their original resolution

### Description

May I ask if it is possible to add images without magnification and process them based on their original resolution

### Alternatives

May I ask if it is possible to add images without magnification and process them based on their original resolution

**Comment by aaronliu0130** [comment]
What does that mean?

**Comment by Cqoicebordel** [comment]
You have a blurry image with a satisfactory resolution, and you want to remove the bluriness while keeping the resolution.

It would be useful to me too.

**Comment by MrPenguin07** [comment]
This would actually be a great feature.

For photos that are already of good resolution and sized in Mb, upscaling can cause them to bloat up to 300MB!

**Comment by Masterlovsky** [comment]
Yes, that's a good idea. Also need it!
Sometimes, we just want to make the picture sharper and  more exquisite without changing the resolution.

**Comment by Cqoicebordel** [comment]
FFS.

**Comment by aaronliu0130** [comment]
@NayamAmarshe are there models for this?

**Comment by NayamAmarshe** [comment]
No, there are no models like this.
However, I'm planning to add a compress and downscale option.
