### ISSUE TITLE
Changing the source image's data without changing the filename causes Upscayl not to upscale the new image.

### ISSUE THREAD

**Issue by Lunarien** [upscayl/upscayl#276]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

I found this out by making slight adjustments to the source image before trying to upscale the nearly-same image again.
So what happens is that I change some pixels on the image, keeping the name, import that image into Upscayl, and I click the Upscayl button.
The result appears instantly, since it probably is cached somewhere. It seems to me that it is checking/comparing only the name of the image and not the data of the image, and so the program isn't interpreting a change.
The resulting upscaled image also is the previous image, upscaled. When I drag the slider between the non-upscaled and the upscaled image, the upscaled image is the old upscaled image, while the non-upscaled one is the new image that I want to be upscaled.

Restarting Upscayl doesn't help, the problem still persists even after a restart.

### To Reproduce

1) Get an image and import it. You can name it "test.png", for example. I will refer to it as that.
2) Upscale the image. You should probably keep the output image where it was saved to.
3) Open test.png in a graphics program like Krita, Photoshop or Paint.net. I personally used Krita for this to happen, but I don't think it is a necessity to use it. Download it as a last resort in case you don't have it.
4) Change any pixels in the test.png image. Preferably many pixels, or just scribble on the image.
5) Save the image with the same exact name, test.png.
6) Import the image into Upscayl again and click on the Upscayl button.
Finally) You should see that the preview loaded instantly, and that the two images are not the same, even after the upscaling process. They just shouldn't correspond to each other.

### Expected Behavior

Upscayl should figure out whether the image data has changed from the previous upscaling of the current image.
If the data is different, then upscale again. If it is the same, then Upscayl can display the last upscaled version of the image.
And I know this might be for a different issue, but there could also be a button to force-upscale an image, or rather redo the upscaling.

### Version/Commit Hash

2.0.1

### OS Specifics

GTX 1650 in a laptop, Windows 11 Home 22H2

### Screenshots

If you look on the weird light spot on the dog's leg, you will see that the upscaled version (top image) has it, while the non-upscaled version does not have it (bottom image).
Also, the well-lit foot has a dark spot in the top image, but that wasn't supposed to be there. It is an artefact I removed later, as you can see in the lower resolution image (bottom).
![image](https://user-images.githubusercontent.com/73956350/232338219-7a3c8f91-ac86-4df2-9c00-3b94b7319a57.png)
![image](https://user-images.githubusercontent.com/73956350/232338220-cc036b9e-af7b-4965-8d4d-8807000cc18a.png)

**Comment by aaronliu0130** [comment]
Do these minuscule pixels make much of a difference to the image? To me this looks like a feature we should keep

**Comment by Lunarien** [comment]
A bigger problem might arise when you fully replace an image while keeping the name.
1) The replacement image **will not** upscale, because another image with the same name was upscaled.
2) The preview will be all wrong, because the old upscaled image is cached somewhere (I assume), and that will show up as the upscale version of the new, different image, which is just wrong.

**Comment by aaronliu0130** [comment]
@NayamAmarshe Are we going to add an overwrite option?

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe Are we going to add an overwrite option?

I'm actually not sure about it. I'll need opinions 😅

**Comment by aaronliu0130** [comment]
I think there should be some sort of override for this caching as some websites download images under the same name.

**Comment by NayamAmarshe** [comment]
> I think there should be some sort of override for this caching as some websites download images under the same name.

How about appending (1), (2) to the name of the image?

**Comment by aaronliu0130** [comment]
I meant like when you scrape an image, like saving directly from Bing's results, the image name is the same and saving doesn't append that by default. Though yes, this is an edge case, but there probably should be a way to override

**Comment by aaronliu0130** [comment]
Overwriting was added in 2.7.5.
