### ISSUE TITLE
Offer pretreatment for images

### ISSUE THREAD

**Issue by Cqoicebordel** [upscayl/upscayl#278]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

This one might be niche, and a very narrow use case, but I'm just proposing things here.

I'm using upscayl to upscale texture of a video game (Kirby on Wii, through Dolphin). Some textures give great results, other less so.

For example, the texture below gives ok-ish results, the best being with Anime, but even there, it's not great (the straight line at the top right has issues, for example). If you zoom in, it's obvious.
<details>
Original, tex1_100x100_1d4307958a53e82d_14.png : <br />
<img src="https://user-images.githubusercontent.com/2286246/232515342-7374589a-69b9-408e-b620-80db0b9b5cc3.png" />

Upscale, tex1_100x100_1d4307958a53e82d_14_upscayl_4x_realesrgan-x4plus-anime.png : </br>
<img src="https://user-images.githubusercontent.com/2286246/232516899-69749a8d-3000-4d1b-afb5-4c88a160faaf.png" />
</details>

### Description

So I have made an experiment : take the texture in gimp, upscale it from 100x100 to 400x400, blur it a bit (gaussian blur of 4, horizontally and vertically), downscale it back to 100x100, and then use upscayl.

Here the result is a lot better. There are still issues, of course, like the mirroring on the edges of the image but everything is sharper, and what we would expect from an upscaled texture. Anime still gives the best result, but the others can be better too (or useless, depending).
<details>
Blurred original texture tex1_100x100_1d4307958a53e82d_14-perso2.png : <br />
<img src="https://user-images.githubusercontent.com/2286246/232519672-77d2e034-06ec-40c7-ab03-a498d98ea1e9.png" />

Upscale, tex1_100x100_1d4307958a53e82d_14-perso2_upscayl_4x_realesrgan-x4plus-anime.png : <br />
<img src="https://user-images.githubusercontent.com/2286246/232519737-6115ca8d-5842-4d4f-aa39-83193fade81f.png">
</details>

So what I'm proposing is to add a few features to, for example, mathematically upscale, blur, mathematically downscale, before feeding it to the GAN. If #275 is implemented, it could even skip the downscale step.
Other small adjustements like that could be added too, to be beneficial in the rendering part, but I don't know which.

### Alternatives

Alternatively, proposing to run a command line for pre-processing of the image, and post-processing of the image could be helpful in that way too.

That alternative can even be preferable because it'll fit more use cases, but it would be less user friendly.

**Comment by Cqoicebordel** [comment]
Disable "watch" on the top right corner of Github ?

**Comment by NayamAmarshe** [comment]
> How do I stop getting notifications for these updates? I have unsubscribed from this list at least every day for one week and I still keep getting them. Does anybody have any clue?

![image](https://user-images.githubusercontent.com/25067102/232571797-a26a9c63-e851-4960-b838-8b8979ec0448.png)

**Comment by Cqoicebordel** [comment]
Seriously, there are still some repo using the stale bot ?

**Comment by aaronliu0130** [comment]
Nayam added it last month. I opened #328 and may have brought about its deprecation by pinging the maintainer.

**Comment by Cqoicebordel** [comment]
My issue wasn't with the bot in itself, but with the usage of "stale" at all.

https://fvsch.com/stale-bots

**Comment by aaronliu0130** [comment]
Upscayl has been under pretty active development last month. So the issues that go stale are mainly ones where the author didn't respond to confirm if the issue still exists. For actual long term things that we should keep open I have removed the label on them. I don't close duplicates of stale issues. Now that GitHub has added the "not planned" reason, we can see the grey tick and see that the issue hasn't been solved yet plus the label. We also have an FAQ for certain non-issues that will get closed.

**Comment by NayamAmarshe** [comment]
> My issue wasn't with the bot in itself, but with the usage of "stale" at all.
> 
> https://fvsch.com/stale-bots

Some issues have stopped receiving any comments from the authors, even after being asked. So I thought stale bot would be better to keep track of such issues and it has helped, tbh.

Some other issues, like this one, are issues that are low priority at the moment and I might revisit them once I take care of other higher priority issues. So I apologize if you didn't want it to be marked as stale. Thanks for letting us know.

**Comment by NayamAmarshe** [comment]
Maybe on Upscayl Cloud we could add something like this, but for the desktop, no plans (for now at the very least).
