### ISSUE TITLE
Add progress bar on taskbar

### ISSUE THREAD

**Issue by AyliasTheCoder** [upscayl/upscayl#279]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Add a progress bar on the icon. There is builtin support for electron to have a progress bar that shows on the icon on the taskbar on windows, mac, and linux, using the win.setProgressBar method, so it would be cool to have this implemented so we can see the progress without having to switch back to the window.

### Alternatives

Not really

**Comment by NayamAmarshe** [comment]
Cool idea
