### ISSUE TITLE
[Bug] App hangs on Windows and Mac

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#28]
The app hangs forever(at least for over an hour) when trying to upscayl an image on my Windows PC and MacBook Air. It forever does the "Hold on..." step. My PC has a RX580 GPU so I don't think that's the reason of my problems.
<details>
    <summary> Command Line Output </summary>
    <pre>
PS C:\Users\aaron\Git\upscayl> npm run start

> upscayl@1.1.1 start
> electron .

warn  - You have enabled experimental feature (images) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
event - compiled client and server successfully in 10.7s (158 modules)
wait  - compiling...
event - compiled successfully in 137 ms (126 modules)
wait  - compiling...
event - compiled client and server successfully in 116 ms (158 modules)
ICON:  C:\Users\aaron\Git\upscayl\main\icon.png
wait  - compiling / (client and server)...
event - compiled client and server successfully in 202 ms (189 modules)
C:\Users\aaron\OneDrive\Pictures\left.jpg
C:\Users\aaron\OneDrive\Pictures
PRODUCTION? : true
EXEC:  C:\Users\aaron\Git\upscayl\resources\win\bin\upscayl
error - uncaughtException: Error: spawn C:\Users\aaron\Git\upscayl\resources\win\bin\upscayl ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Users\\aaron\\Git\\upscayl\\resources\\win\\bin\\upscayl',
  path: 'C:\\Users\\aaron\\Git\\upscayl\\resources\\win\\bin\\upscayl',
  spawnargs: [
    '-i',
    'C:\\Users\\aaron\\OneDrive\\Pictures/C:\\Users\\aaron\\OneDrive\\Pictures\\left.jpg',
    '-o',
    'C:\\Users\\aaron\\OneDrive\\Pictures/left_upscayled_4x.jpg',
    '-s',
    4,
    '-m',
    'C:\\Users\\aaron\\Git\\upscayl\\resources\\win\\bin\\models',
    '-n',
    'realesrgan-x4plus'
  ]
}
[9716:0825/110040.999:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is
    </pre>
</details>

**Comment by NayamAmarshe** [comment]
MacOS and Windows binaries aren't available in the project code yet. I'll try to add and release the new version this week.

**Comment by aaronliu0130** [comment]
I used `npm start`

**Comment by NayamAmarshe** [comment]
Yes, the Real-ESRGAN binaries for MacOS and Windows aren't available in the code yet.

**Comment by NayamAmarshe** [comment]
We'll be releasing for Mac and Windows soon so closing this issue.
