### ISSUE TITLE
DECODING ERROR when trying to use batch upscale of folder of PNG images

### ISSUE THREAD

**Issue by tomexx** [upscayl/upscayl#284]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

I'm getting DECODING ERROR (see screenshot) when trying to use batch upscale of folder of PNG images.

### To Reproduce

- toggle Batch Upscale ON
- select folder of PNG images
- start upscaling

### Expected Behavior

Working without error

### Version/Commit Hash

2.0.1

### OS Specifics

Windows

### Screenshots

![image](https://user-images.githubusercontent.com/2822756/233808019-c18bfc58-e8c3-4e51-8527-fd26fa2d6cc5.png)

**Comment by aaronliu0130** [comment]
If you don’t have logs, you may follow these instructions: Download and install git from https://git-scm.com/download (note that git is bundled with macOS) and node from https://nodejs.org/en/download/current/ (choose standalone installer 64 for both) then run these in your terminal (if you don't know what this is, search and open an app on your computer called "Command Prompt" or "cmd" for short):
```sh
git clone https://github.com/TGS963/upscayl
cd upscayl
npm install
npm run start
```
After the last command, upscayl should show up. Reproduce the error and send out the terminal output. `npm` will tell you about audit errors. These are due to #54 and currently expected.

**Comment by tomexx** [comment]
> If you don’t have logs, you may follow these instructions: Download and install git from https://git-scm.com/download (note that git is bundled with macOS) and node from https://nodejs.org/en/download/current/ (choose standalone installer 64 for both) then run these in your terminal (if you don't know what this is, search and open an app on your computer called "Command Prompt" or "cmd" for short):
> 
> ```shell
> git clone https://github.com/TGS963/upscayl
> cd upscayl
> npm install
> npm run start
> ```
> 
> After the last command, upscayl should show up. Reproduce the error and send out the terminal output. `npm` will tell you about audit errors. These are due to #54 and currently expected.

I tested it using your steps and the error is not present there. (v 2.0.5). However JPG upscale does not work for batch upscale. So I couldn't test it properly.

**Comment by tomexx** [comment]
I tried a different batch of images and it actually does fails at an error. The error log from console looks like this.

```
00:17:12.402 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 65.71%                 
                                                                                     
00:17:12.403 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 77.14%                 
                                                                                     
00:17:12.413 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 68.57%                 
                                                                                     
00:17:12.418 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 80.00%                 
                                                                                     
00:17:12.424 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 71.43%                 
                                                                                     
00:17:12.429 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 82.86%                 
                                                                                     
00:17:12.436 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 74.29%                 
                                                                                     
00:17:12.441 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 85.71%                 
                                                                                     
00:17:12.447 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 77.14%                 
                                                                                     
00:17:12.450 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 88.57%                 
                                                                                     
00:17:12.459 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 80.00%                 
                                                                                     
00:17:12.459 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 91.43%                 
                                                                                     
00:17:12.467 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
94.29%                                                                               
82.86%                                                                               
                                                                                     
00:17:12.476 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 85.71%                 
                                                                                     
00:17:12.476 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 97.14%                 
                                                                                     
00:17:12.484 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 88.57%                 
                                                                                     
00:17:12.488 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 0.00%                  
                                                                                     
00:17:12.496 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 91.43%                 
                                                                                     
00:17:12.499 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 2.86%                  
                                                                                     
00:17:12.506 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 94.29%                 
                                                                                     
00:17:12.509 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 5.71%                  
                                                                                     
00:17:12.514 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 97.14%                 
                                                                                     
00:17:12.517 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 8.57%                  
                                                                                     
00:17:12.525 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
0.00%                                                                                
11.43%                                                                               
                                                                                     
00:17:12.532 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
2.86%                                                                                
                                                                                     
00:17:12.535 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
14.29%                                                                               
                                                                                     
00:17:12.541 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
                                                                                     
00:17:12.542 > ≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 5.71%                  
```

**Comment by aaronliu0130** [comment]
@sunnydavis Your issue is different, you ran out of memory. See #57.

**Comment by coolst3r** [comment]
> ### Checklist
> 
>     * [x]  I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
> 
>     * [x]  I have checked that this issue isn't addressed in any other issue or pull request.
> 
> 
> ### Describe the Bug
> 
> I'm getting DECODING ERROR (see screenshot) when trying to use batch upscale of folder of PNG images.
> ### To Reproduce
> 
>     * toggle Batch Upscale ON
> 
>     * select folder of PNG images
> 
>     * start upscaling
> 
> 
> ### Expected Behavior
> 
> Working without error
> ### Version/Commit Hash
> 
> 2.0.1
> ### OS Specifics
> 
> Windows
> ### Screenshots
> 
> ![image](https://user-images.githubusercontent.com/2822756/233808019-c18bfc58-e8c3-4e51-8527-fd26fa2d6cc5.png)

try format factory in windows for changing format type or just rename it to the correct format i do it alot does not change much

**Comment by coolst3r** [comment]
a solution to this is code that just renames all images it uses to .png

**Comment by aaronliu0130** [comment]
@coolst3r That is not how formats work nor is it the reason for it to fail.

**Comment by coolst3r** [comment]
says you dont have write perms run as admin

**Comment by coolst3r** [comment]
it says it in the screenshot make sure you have write perms

**Comment by coolst3r** [comment]
read some more he cant upscale a bunch of jpeg files saw vulkan failed to allocate memory and it also has something to do with vulkan queuing  

vkAllocateMemory failed -2 vulkan failed to allocate memory

vkQueueSubmit failed -4 failed to submit to vulkan q 
https://registry.khronos.org/VulkanSC/specs/1.0-extensions/man/html/vkQueueSubmit.html

it does seem like some kind of permission issue or may be a different bug

**Comment by aaronliu0130** [comment]
That dialog is a generic error that doesn’t mean write access must be the issue, and vkQueueSubmitFailed has been an unrelated issue that usually doesn’t affect things https://github.com/nihui/dain-ncnn-vulkan/issues/19 for a long time. Nowhere in the logs show the memory allocation error.

**Comment by yohgizzy** [comment]
please im having the same problem,

03:07:09.919 > Γ¥î INVALID GPU OR FAILED
03:07:09.922 > image upscayl:  vkEnumerateInstanceExtensionProperties failed -1
vkEnumerateInstanceExtensionProperties failed -1
invalid gpu device

03:07:09.924 > Γ¥î INVALID GPU OR FAILED
03:07:09.921 ΓÇ║ ≡ƒÉ₧ BACKEND REPORTED:  image upscayl:  vkEnumerateInstanceExtensionProperties failed -1

03:07:13.301 ΓÇ║ ≡ƒöä Resetting image paths
03:07:13.303 ΓÇ║ ≡ƒÜº UPSCAYL_PROGRESS:  vkEnumerateInstanceExtensionProperties failed -1

03:07:13.311 ΓÇ║ ≡ƒöä Resetting image paths
03:07:13.312 ΓÇ║ ≡ƒÉ₧ BACKEND REPORTED:  Γ¥î INVALID GPU OR FAILED
03:07:13.314 ΓÇ║ ≡ƒÉ₧ BACKEND REPORTED:  image upscayl:  vkEnumerateInstanceExtensionProperties failed -1
vkEnumerateInstanceExtensionProperties failed -1
invalid gpu device

03:10:49.710 ΓÇ║ ≡ƒöä Resetting image paths
03:10:49.711 ΓÇ║ ≡ƒÜº UPSCAYL_PROGRESS:  vkEnumerateInstanceExtensionProperties failed -1
vkEnumerateInstanceExtensionProperties failed -1
invalid gpu device

03:10:49.730 ΓÇ║ ≡ƒÉ₧ BACKEND REPORTED:  Γ¥î INVALID GPU OR FAILED

**Comment by yohgizzy** [comment]
i'm using gtx 1060 6gb

**Comment by aaronliu0130** [comment]
@yohgizzy That is not the same problem, please file a new issue.

**Comment by aaronliu0130** [comment]
@tomexx Can you reproduce this in 2.5?

**Comment by agithbusr** [comment]
Hi, 

I experienced the same issue on OS X, v2.5.5 with a CIFS/SMB mounted folder containing >40,000 pngs.  

I cloned the repo just now and ran as directed and received the following error during the run:

`
10:40:23.234 › 🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

10:40:23.262 › ❌ INVALID GPU OR FAILED
10:40:44.860 › 🔄 Resetting image paths
10:40:44.861 › 🚧 FOLDER_UPSCAYL_PROGRESS:  decode image /Volumes/home/ffmpeg/png/0000000154.png failed

10:40:44.865 › 🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
10:40:44.865 › 🚧 FOLDER_UPSCAYL_PROGRESS:  50.00%
66.67%
`

I'm on the main branch with last commit c0809737fd132878b8efa8e458571d0faf3d17d3.

On a side note, I had many, many failures, and it seems like a bad idea to pop an alert someone must click to clear for a batch operation.  In the end I simply had to kill the processes since there were an unknown number of clicks ahead.  Maybe adding an "abort batch?" option to let the user know that an error occurred, while continuing the run and logging the failures, would be a friendlier approach?

**Comment by NayamAmarshe** [comment]
> Hi, 
> 
> I experienced the same issue on OS X, v2.5.5 with a CIFS/SMB mounted folder containing >40,000 pngs.  
> 
> I cloned the repo just now and ran as directed and received the following error during the run:
> 
> `
> 10:40:23.234 › 🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%
> 
> 10:40:23.262 › ❌ INVALID GPU OR FAILED
> 10:40:44.860 › 🔄 Resetting image paths
> 10:40:44.861 › 🚧 FOLDER_UPSCAYL_PROGRESS:  decode image /Volumes/home/ffmpeg/png/0000000154.png failed
> 
> 10:40:44.865 › 🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
> 10:40:44.865 › 🚧 FOLDER_UPSCAYL_PROGRESS:  50.00%
> 66.67%
> `
> 
> I'm on the main branch with last commit c0809737fd132878b8efa8e458571d0faf3d17d3.
> 
> On a side note, I had many, many failures, and it seems like a bad idea to pop an alert someone must click to clear for a batch operation.  In the end I simply had to kill the processes since there were an unknown number of clicks ahead.  Maybe adding an "abort batch?" option to let the user know that an error occurred, while continuing the run and logging the failures, would be a friendlier approach?
> 
> 

Yes, that's a good idea. I should probably be avoiding multiple dialogs.

40k images won't upscale though, I think you'll have to divide it into multiple folders.

**Comment by eesaben** [comment]
Hi all 
I am experiencing the same issue at the moment. I have read through the comments but I am not sure if there is a solution. Has this issue been fixed, if so where is the solution?
Much appreciated
