### ISSUE TITLE
Upscayl begins processing image, but then both of my monitors shut off and I have to reboot my machine

### ISSUE THREAD

**Issue by dorkerdev** [upscayl/upscayl#286]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

See title. I'll also add that, upon reboot, running Upscayl again showed an error message advising that it couldn't parse this JSON file:

F:\Program Files\Upscayl\resources\app.asar.unpacked\node_modules\upscayl-ffmpeg\package.json

When I opened it, it was just a bunch of random binary-looking data. I had to actually reinstall the program. Again, using it caused my monitors to turn off and I had to reboot. The JSON file wasn't corrupted this time, so I wasn't able to get a screenshot of it.

I am using Windows 7 which I know is out of support, but, looking at the tech stack, seems like it should work.

### To Reproduce

Just drag an image to the workspace, use the default General Photo option, and click UPSCAYL. I didn't do anything with Advanced Options.

### Expected Behavior

It should have worked, but it didn't.

### Version/Commit Hash

upscayl-2.0.1-win

### OS Specifics

Windows 7 x64 / GeForce GTX 680

**Comment by aaronliu0130** [comment]
Upscayl is a Linux-first application. If this bug can't be reproduced on a modern OS, we probably won't troubleshoot it.
