### ISSUE TITLE
Add .desktop file for DE integration

### ISSUE THREAD

**Issue by artogahr** [upscayl/upscayl#29]
I'm thinking of preparing a .desktop file so people installing it can launch it from their app menus, instead of launching it by finding the appimage file and clicking on it, etc.

**Comment by NayamAmarshe** [comment]
You can use DeskCut for this too ;)

**Comment by artogahr** [comment]
So I get you aren't considering offering binary builds, just AppImages and Flatpaks? And also for Flathub you're going to need to include a desktop file anyway, no?

So my proposal is this:
When a .desktop file is included, I write a script inside the PKGBUILD for the AUR that extracts the .desktop file from the AppImage, and modifies it to run the symlinked binary to the AppImage file. How does that sound?

End result:
Arch user installs "upscayl-appimage" package from the AUR, and Upscayl is available to them in their app launcher.

**Comment by NayamAmarshe** [comment]
> So I get you aren't considering offering binary builds, just AppImages and Flatpaks? And also for Flathub you're going to need to include a desktop file anyway, no?
> 
> So my proposal is this: When a .desktop file is included, I write a script inside the PKGBUILD for the AUR that extracts the .desktop file from the AppImage, and modifies it to run the symlinked binary to the AppImage file. How does that sound?
> 
> End result: Arch user installs "upscayl-appimage" package from the AUR, and Upscayl is available to them in their app launcher.

Yeah you can do it for the Arch build, no problem :)

**Comment by artogahr** [comment]
Okay, I don't know much about Flatpaks so I'll wait for you guys to implement a .desktop file then. Thanks

**Comment by NayamAmarshe** [comment]
Closing this issue, we can discuss this here as well:
https://github.com/upscayl/upscayl/issues/15
