### ISSUE TITLE
2.5 PRE-RELEASE for Windows

### ISSUE THREAD

**Issue by ThomasCZ** [upscayl/upscayl#295]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Assets in 2.5 PRE-RELEASE does not contain executable file for Windows.

### To Reproduce

Missing file in https://github.com/upscayl/upscayl/releases/tag/v2.5.0

### Expected Behavior

Assets contains executable file for Windows

### Version/Commit Hash

2.5 PRE-RELEASE

### OS Specifics

Windows

### Screenshots

![chrome_0NBogrXYsZ](https://user-images.githubusercontent.com/7516715/235443033-250a417b-7298-4410-ac95-4456c04c3078.png)

**Comment by NayamAmarshe** [comment]
Hi Thomas,
as the release says: [PRE-RELEASE FOR LINUX USERS]

We're not releasing the beta for Windows or MacOS. Those operating systems will receive the stable version.

**Comment by ThomasCZ** [comment]
Alright I got it.
