### ISSUE TITLE
React goes into infinite loop when selecting or dropping a single image in version 2.5.0

### ISSUE THREAD

**Issue by yevgeniyakimenko** [upscayl/upscayl#296]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Browser console log:

`Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ab (framework-af64bd368ed34feb.js:9:60959)
    at ud (framework-af64bd368ed34feb.js:9:72801)
    at i (framework-af64bd368ed34feb.js:9:120370)
    at oO (framework-af64bd368ed34feb.js:9:99112)
    at framework-af64bd368ed34feb.js:9:98979
    at oF (framework-af64bd368ed34feb.js:9:98986)
    at ox (framework-af64bd368ed34feb.js:9:95738)
    at oC (framework-af64bd368ed34feb.js:9:96127)
    at r4 (framework-af64bd368ed34feb.js:9:44776)
    at framework-af64bd368ed34feb.js:9:93630
Y @ main-f0ea92079748733d.js:1
fn @ main-f0ea92079748733d.js:1
componentDidCatch @ main-f0ea92079748733d.js:1
a.componentDidCatch.t.callback @ framework-af64bd368ed34feb.js:9
lH @ framework-af64bd368ed34feb.js:9
uY @ framework-af64bd368ed34feb.js:9
e @ framework-af64bd368ed34feb.js:9
(anonymous) @ framework-af64bd368ed34feb.js:9
oI @ framework-af64bd368ed34feb.js:9
oC @ framework-af64bd368ed34feb.js:9
r4 @ framework-af64bd368ed34feb.js:9
(anonymous) @ framework-af64bd368ed34feb.js:9

main-f0ea92079748733d.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
Y @ main-f0ea92079748733d.js:1
fn @ main-f0ea92079748733d.js:1
componentDidCatch @ main-f0ea92079748733d.js:1
a.componentDidCatch.t.callback @ framework-af64bd368ed34feb.js:9
lH @ framework-af64bd368ed34feb.js:9
uY @ framework-af64bd368ed34feb.js:9
e @ framework-af64bd368ed34feb.js:9
(anonymous) @ framework-af64bd368ed34feb.js:9
oI @ framework-af64bd368ed34feb.js:9
oC @ framework-af64bd368ed34feb.js:9
r4 @ framework-af64bd368ed34feb.js:9
(anonymous) @ framework-af64bd368ed34feb.js:9`

The issue seems to reside in the `formatPath` function in `renderer/pages/index.tsx`. The front end works fine when commenting out line 486, `logit("📢 Formatting path: ", path);`.

### To Reproduce

Try to open a single image by clicking the "Select Image" button or drag and drop a single file into the window.

### Expected Behavior

The image file is picked up correctly and displayed in the window, like it does correctly with AppImage version 2.0.1.

### Version/Commit Hash

2.5.0

### OS Specifics

Manjaro Linux, Nvidia GTX1050 mobile

### Screenshots

![upscayl-error](https://user-images.githubusercontent.com/108773054/235570926-35d5bf58-9f78-4fd5-a731-d3a2c74b11a7.jpg)

**Comment by NayamAmarshe** [comment]
How did I miss this 😭

**Comment by NayamAmarshe** [comment]
I have no idea why this is happening.

**Comment by yevgeniyakimenko** [comment]
Yes, it's probably something to do with how the `<img>` elements call the function directly. I'm trying to work on a pull request :)

**Comment by NayamAmarshe** [comment]
Weird, I tried the fix, it doesn't work.
