### ISSUE TITLE
BuildID folder in the RPM can cause conflicts

### ISSUE THREAD

**Issue by andrio1988** [upscayl/upscayl#299]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

When trying to install an RPM package on Fedora 38, the following error occurs:
Transaction validation error:
  The /usr/lib/.build-id/33/d1f99f5a2b6366dedfe3ac2f58936d7ba4df19 file from the installed upscayl-2.5.0-1.x86_64 package conflicts with a file from the chainner-0.18.6-1.x86_64 package

### To Reproduce

I have chaiNNer version 0.18.6 installed.
There is some conflict when I try to install the rpm.

### Expected Behavior

Not installed

### Version/Commit Hash

2.5.0

### OS Specifics

Fedora KDE 38, Radeon RX 550

**Comment by aaronliu0130** [comment]
> 5.0.0

Pretty sure you meant 2.5.0?

**Comment by aaronliu0130** [comment]
https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/issues/55 @NayamAmarshe Apparently, these are a bridge with a potential debuginfo file, which we don't ship, and can be safely removed.

**Comment by NayamAmarshe** [comment]
Couldn't find much info about this in Electron Builder's issues. I'll take a proper look at this later.
