### ISSUE TITLE
Can you make Upscayl Portable?

### ISSUE THREAD

**Issue by pstein** [upscayl/upscayl#300]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

I would like to install Upscayl as a portable program (e.g. on an USB flash drive).

Can you make it portable?

Thank you

### Description

See above

### Alternatives

not known

**Comment by NayamAmarshe** [comment]
Please always search for pre-existing issues before creating a new one.

https://github.com/upscayl/upscayl/issues/181
