### ISSUE TITLE
Not using the selected GPU

### ISSUE THREAD

**Issue by FiodarShurankou** [upscayl/upscayl#302]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

I followed the instructions in FAQs and identified that my iGPU has ID 0 and dGPU has ID 1. After setting the GPU ID to 1 it still uses the iGPU, even after restarting and rebooting.

### To Reproduce

1. Set GPU ID to 1
2. Still uses GPU 0

### Expected Behavior

1. Set GPU ID to 1
2. Still uses GPU 1

### Version/Commit Hash

2.5.1

### OS Specifics

Windows 10 Pro 21H2 Build 19044.2846, iGPU i7-1185G7 Iris(R) Xe, dGPU NVIDIA GTX 1650 Ti with Max-Q Design driver version 531.83

### Screenshots

Settings:
![image](https://github.com/upscayl/upscayl/assets/108727928/7f01bbe3-dc7a-4a96-8c5b-96e62079a215)

GPU usage:
![image](https://github.com/upscayl/upscayl/assets/108727928/389dd473-f357-47a1-b478-4b3b8d68b8cc)

**Comment by NayamAmarshe** [comment]
> If you don’t have logs, you may follow these instructions: Download and install git from https://git-scm.com/download (note that git is bundled with macOS) and node from https://nodejs.org/en/download/current/ (choose standalone installer 64 for both) then run these in your terminal (if you don't know what this is, search and open an app on your computer called "Command Prompt" or "cmd" for short):
> 
> ```shell
> git clone https://github.com/TGS963/upscayl
> cd upscayl
> npm install
> npm run start
> ```
> 
> After the last command, upscayl should show up. Reproduce the error and send out the terminal output. `npm` will tell you about audit errors. These are due to #54 and currently expected.

We don't need to do all this anymore. We now have a logs window.
![image](https://github.com/upscayl/upscayl/assets/25067102/fa8d4134-22fd-4a8a-8ee4-95a35f56ab97)

**Comment by NayamAmarshe** [comment]
I think your GPU ID is wrong. Please read the FAQ (You can check the settings tab for logs)

**Comment by FiodarShurankou** [comment]
> I think your GPU ID is wrong. Please read the Wiki.
> 
> https://github.com/upscayl/upscayl/wiki/Guide

I followed the same instructions but from the terminal, but logs are saying the same thing basically.

As you can see from the [logs](https://pastebin.com/Y7C0XwBA) my dGPU has GPU ID 1. Also here [logs](https://pastebin.com/xBr0htqQ) with GPU ID 1 selected, but it still uses the iGPU

**Comment by NayamAmarshe** [comment]
> > I think your GPU ID is wrong. Please read the Wiki.
> > https://github.com/upscayl/upscayl/wiki/Guide
> 
> I followed the same instructions but from the terminal, but logs are saying the same thing basically.
> 
> As you can see from the [logs](https://pastebin.com/Y7C0XwBA) my dGPU has GPU ID 1. Also here [logs](https://pastebin.com/xBr0htqQ) with GPU ID 1 selected, but it still uses the iGPU

I don't see any gpu id in the command. There should be `-g ${gpuId}` in the upscayl command. I'll see what's wrong.

**Comment by FiodarShurankou** [comment]
In the first one there is not, but in the logs with GPU ID selected there is a -g 1 almost at the end of the command :
```
C:\Users\FiodarShuran_jvurx92\Downloads\zl3kq2awws3a1.png,-o,C:\Users\FiodarShuran_jvurx92\Downloads\zl3kq2awws3a1_upscayl_4x_ultrasharp.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultrasharp,-g 1,-f,png
```

**Comment by NayamAmarshe** [comment]
Very strange. Could be a command parsing issue or Real-ESRGAN issue. If it's the latter, it's a cant-fix, if former, then sure.

**Comment by FiodarShurankou** [comment]
If i can provide any additional info in order to help you better understand the root cause of the issue let me know.

**Comment by FiodarShurankou** [comment]
For me the issue persists on every model

**Comment by NayamAmarshe** [comment]
There's one thing you can do. In Additional Display Settings, you could force Upscayl to use Nvidia.

**Comment by NayamAmarshe** [comment]
I'm not sure how to debug this tbh. I'd have to ask @TGS963 to test because I don't have Windows and Upscayl won't work inside a VM.

**Comment by TGS963** [comment]
Okay, I have been able to reproduce this issue. This is not a real esrgan issue as calling the binary from command line works as intended. But the selection in the app doesn't work, even though it appears in the log as the proper command.

**Comment by NayamAmarshe** [comment]
> the issue was in parsing the arguments correctly. it should be fixed in the latest commit

Awesome! Thank you!

**Comment by FiodarShurankou** [comment]
Still having the issue but the usage on iGPU is now somehow capped at 30%

**Comment by TGS963** [comment]
> Still having the issue but the usage on iGPU is now somehow capped at 30%

Well you'll not see the changes unless the new builds are released or you build the source code yourself. I've tested it on my own laptop and both my GPUs reached 99% during testing

**Comment by FiodarShurankou** [comment]
Ok, after a little investigation seems a Windows issue now... (Thank you Bill !)

Setting the GPU ID to 0 works as expected, iGPU is used at 100%.

Setting the GPU ID to 1 for the first 2 seconds usage on dGPU goes to 10% then to 0 and iGPU usage goes to 30%.

What seems to happen is it's using the dGPU to upscale and the iGPU is used to render something the Upscayl tab (infact when the window is covered or i switch to Settings tab iGPU usage goes to 0), Windows just doesn't display correctly the usage of dGPU.

P.S. I cloned the repo to run the test with the 9432be1 commit

**Comment by TGS963** [comment]
could you try and check the dGPU usage by calling the binary from the command line? the binary is located in the resources/win/bin folder and the command is like:

``.\upscayl-realesrgan.exe -i "input image path" -o "output image path" -s 4 -m YOURPATH\resources\models -n "name of the model" -g 1 -f png``

**Comment by TGS963** [comment]
> It's using the dGPU for sure now, the temperature goes up and it upscales much faster. I can see from task manager that there is some memory in use during the upscale but no usage.

Does only the command line work? Or is the actual app working now as well?

**Comment by FiodarShurankou** [comment]
Both work fine (aside from usage not displaying), it's solved. Thank you!

**Comment by FiodarShurankou** [comment]
Found it!

When upscaling the usage is displayed in Compute_1 graph!!!
![image](https://github.com/upscayl/upscayl/assets/108727928/adcea915-2779-4491-87d2-cff5c64220b9)

By default the displayed graphs are 3D, Copy, Video Encode and Video Decode
