### ISSUE TITLE
Disable Auto-Updates

### ISSUE THREAD

**Issue by x21isUnreal** [upscayl/upscayl#305]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

The program causes a fault. I cannot disable updates.

### To Reproduce

Try running under windows 7

### Expected Behavior

The program should either work or allow updates to be disabled.

### Version/Commit Hash

2.5.1

### OS Specifics

GTX 1070 and Windows 7

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/99152229/92af1d1e-c1cf-4a03-91e1-8f57f7e2e3a0)

**Comment by x21isUnreal** [comment]
After a lot more fighting with it I managed to disable updates by renaming the file "C:\Program Files\Upscayl\resources\app-update.yml" to something else.

**Comment by NayamAmarshe** [comment]
Windows 7 is EOL, not supported by the project at the moment. Marlin this as a wont-fix for now.

**Comment by x21isUnreal** [comment]
> Windows 7 is EOL, not supported by the project at the moment. Marking this as a wont-fix for now.

Your reply doesn't help as older working revisions get broken by the auto update,

**Comment by NayamAmarshe** [comment]
It does not matter if it works or not. I cannot support Windows 7 in any sense. You are free to use v1, the version without auto-updates.

Your issue is about Windows 7, which is a dead OS, not auto-update. If you'd like to request a feature for disabling auto updates, please feel free to do so, but as of now I personally cannot support anything related to Windows 7 or Windows 8 hence the `wontfix` label.

**Comment by x21isUnreal** [comment]
> It does not matter if it works or not. I cannot support Windows 7 in any sense. You are free to use v1, the version without auto-updates.
> 
> > How are your forced updates any better that what Microsoft does?
> 
> They're better for everybody else. Nobody should be using Windows 7 in 2023 and that's not my opinion but a good general security advice.
> 
> Your issue is about Windows 7, which is a dead OS, not auto-update. If you'd like to request a feature for disabling auto updates, please feel free to do so, but as of now I personally cannot support anything related to Windows 7 or Windows 8 hence the `wontfix` label.

I guess I will be forced to make a patch for version 2.0.1

**Comment by NayamAmarshe** [comment]
> > It does not matter if it works or not. I cannot support Windows 7 in any sense. You are free to use v1, the version without auto-updates.
> > > How are your forced updates any better that what Microsoft does?
> > 
> > 
> > They're better for everybody else. Nobody should be using Windows 7 in 2023 and that's not my opinion but a good general security advice.
> > Your issue is about Windows 7, which is a dead OS, not auto-update. If you'd like to request a feature for disabling auto updates, please feel free to do so, but as of now I personally cannot support anything related to Windows 7 or Windows 8 hence the `wontfix` label.
> 
> I guess I will be forced to make a patch for version 2.0.1

You can compile a version by following the development guidelines in the README. In the main/index.ts file, at the very bottom, you can remove the update functions and compile a version for yourself with the command `npm run dist:msi`

**Comment by x21isUnreal** [comment]
Or I can delete the file that facilitates the auto update.

**Comment by x21isUnreal** [comment]
as I said reproving "C:\Program Files\Upscayl\resources\app-update.yml" stops the update a simple back file patch can be made. for 2.0.1

**Comment by x21isUnreal** [comment]
> as I said removing "C:\Program Files\Upscayl\resources\app-update.yml" stops the update a simple batch file patch can be made. for 2.0.1,
> 
> I'm happy to hear you are considering a way to disable auto-update. But it's causing trouble already.

**Comment by x21isUnreal** [comment]
> I'll add a ticket for disabling auto-updates.



    as I said removing "C:\Program Files\Upscayl\resources\app-update.yml" stops the update a simple batch file patch can be made. for 2.0.1,

    I'm happy to hear you are considering a way to disable auto-update. But it's causing trouble already.
