### ISSUE TITLE
Use libm.so.6 inside Appimage....

### ISSUE THREAD

**Issue by AgostinoA** [upscayl/upscayl#311]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

 /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_appevMIwM/resources/bin/upscayl-realesrgan)

### To Reproduce

 All inside!!! 

### Expected Behavior

All inside!!! 

### Version/Commit Hash

Last

### OS Specifics

Custom OS

**Comment by NayamAmarshe** [comment]
Fix:
```
wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.29.tar.gz
tar -zxvf glibc-2.29.tar.gz
mkdir glibc-2.29/build
cd glibc-2.29/build
../configure --prefix=/opt/glibc
make 
make install
```

**Comment by aaronliu0130** [comment]
I think they're recommending you to include these libs inside the appimage.

**Comment by NayamAmarshe** [comment]
> I think they're recommending you to include these libs inside the appimage.

That won't be possible. It's a system library, not something I should be packaging.

**Comment by coolst3r** [comment]
> > I think they're recommending you to include these libs inside the appimage.
> 
> That won't be possible. It's a system library, not something I should be packaging.

its possible  a auto install on at start of installation or to al least run some checks at launch would help

**Comment by coolst3r** [comment]
> > I think they're recommending you to include these libs inside the appimage.
> 
> That won't be possible. It's a system library, not something I should be packaging.

and app image is in a container away from system https://www.youtube.com/watch?v=9HuExVD56Bo

**Comment by aaronliu0130** [comment]
It's a system library, not something we should be handling.

**Comment by coolst3r** [comment]
lol you can its linux plus if you make a application or software at some point you have to work with system

**Comment by coolst3r** [comment]
and appimages are not part of the system its a sandbox so its ok to install it inside of the appimage so you wont be interfering with users main system

**Comment by AgostinoA** [comment]
I fixed I created an improved version of the appimage. I am now independent of the operating system

**Comment by AgostinoA** [comment]
> > I think they're recommending you to include these libs inside the appimage.
> 
> That won't be possible. It's a system library, not something I should be packaging.

It's possibile

**Comment by AgostinoA** [comment]
> It's not an Upscayl problem. I think your OS doesn't have the required libraries.
> Fix:
> ```
> wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.29.tar.gz
> tar -zxvf glibc-2.29.tar.gz
> mkdir glibc-2.29/build
> cd glibc-2.29/build
> ../configure --prefix=/opt/glibc
> make 
> make install
> ```

This is one way, but it is not a good solution.

**Comment by AgostinoA** [comment]
> > > It's not an Upscayl problem. I think your OS doesn't have the required libraries.
> > > Fix:
> > > ```
> > > wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.29.tar.gz
> > > tar -zxvf glibc-2.29.tar.gz
> > > mkdir glibc-2.29/build
> > > cd glibc-2.29/build
> > > ../configure --prefix=/opt/glibc
> > > make 
> > > make install
> > > ```
> > 
> > This is one way, but it is not a good solution.
> 
> its better to add it to your app images the required lib

Exactly

**Comment by coolst3r** [comment]
> > It's not an Upscayl problem. I think your OS doesn't have the required libraries.
> > Fix:
> > ```
> > wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.29.tar.gz
> > tar -zxvf glibc-2.29.tar.gz
> > mkdir glibc-2.29/build
> > cd glibc-2.29/build
> > ../configure --prefix=/opt/glibc
> > make 
> > make install
> > ```
> 
> This is one way, but it is not a good solution.

its better to add it to your app images the required lib

> > > > It's not an Upscayl problem. I think your OS doesn't have the required libraries.
> > > > Fix:
> > > > ```
> > > > wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.29.tar.gz
> > > > tar -zxvf glibc-2.29.tar.gz
> > > > mkdir glibc-2.29/build
> > > > cd glibc-2.29/build
> > > > ../configure --prefix=/opt/glibc
> > > > make 
> > > > make install
> > > > ```
> > > 
> > > 
> > > This is one way, but it is not a good solution.
> > 
> > 
> > its better to add it to your app images the required lib
> 
> Exactly,I don't understand this desire to depend on the operating system....

it might not be their fault a lot of people don't know that appimage flatpak and snaps are different but still its better if its done this way security wise and also stability

**Comment by aaronliu0130** [comment]
We use electron builder to build things, including the AppImage. Unless someone makes a script that adds the library back into the AppImage after the AppImage is compiled this isn't planned, I think.

**Comment by coolst3r** [comment]
> We use electron builder to build things, including the AppImage. Unless someone makes a script that adds the library back into the AppImage after the AppImage is compiled this isn't planned, I think.

its not hard to do and might not even need  a script

**Comment by aaronliu0130** [comment]
PRs are welcome.

**Comment by NayamAmarshe** [comment]
> > > > It's not an Upscayl problem. I think your OS doesn't have the required libraries.
> > > > Fix:
> > > > ```
> > > > wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.29.tar.gz
> > > > tar -zxvf glibc-2.29.tar.gz
> > > > mkdir glibc-2.29/build
> > > > cd glibc-2.29/build
> > > > ../configure --prefix=/opt/glibc
> > > > make 
> > > > make install
> > > > ```
> > > 
> > > This is one way, but it is not a good solution.
> > 
> > its better to add it to your app images the required lib
> 
> Exactly,I don't understand this desire to depend on the operating system....

Dynamic libraries are loaded by the kernel, the paths are not hardcoded in a program. A program just says "I need libc.so.6". The system then searches in library paths as defined in /etc/ld.so.conf, including /usr/lib and /lib by default. This file includes additional configuration files in /etc/ld.so.conf.d.

https://askubuntu.com/a/40425

**Comment by AgostinoA** [comment]
OK, all the reasoning and the ride, I know exactly how this works and even more.
If you use ld linux hoped to run, all the stability and trip issues you ran into are worked around, as long as you know how ld linux works, it should take you less than 5 minutes to fix.
Also, if you take a look at electron's execution against other built-in executables, there are 2 different versions of the library you used: electron's version uses the older one while upscayl-realesrgan uses the newer ones, nonsense. Logic says you should compile everything for an equal version for the entire program, at least that's how it works at home, the basis of compatibility.
Honestly, many AppImages are very badly done and thank goodness more than 100 appimages are saved!. Then do as you like, I rebuilt it with this concept and it works well, I wanted to make a suggestion, don't create controversy anyway, have a good life.

**Comment by NayamAmarshe** [comment]
> OK, all the reasoning and the ride, I know exactly how this works and even more. If you use ld linux hoped to run, all the stability and trip issues you ran into are worked around, as long as you know how ld linux works, it should take you less than 5 minutes to fix. Also, if you take a look at electron's execution against other built-in executables, there are 2 different versions of the library you used: electron's version uses the older one while upscayl-realesrgan uses the newer ones, nonsense. Logic says you should compile everything for an equal version for the entire program, at least that's how it works at home, the basis of compatibility. Honestly, many AppImages are very badly done and thank goodness more than 100 appimages are saved!. Then do as you like, I rebuilt it with this concept and it works well, I wanted to make a suggestion, don't create controversy anyway, have a good life.

No it's not about controversy. I value your opinion and suggestions.
I'll see if I can fix the library discrepancy.

**Comment by rohezal** [comment]
Having the same problem with Ubuntu 18.04, other people reported the same problem with Debian and Mint. Please add the required glbc to the appimage.

**Comment by NayamAmarshe** [comment]
> Having the same problem with Ubuntu 18.04, other people reported the same problem with Debian and Mint. Please add the required glbc to the appimage.

Ubuntu 18.04 support was dropped with v2.5.1. You'll need to update the library manually for Ubuntu 18.04.

**Comment by rohezal** [comment]
This is an important information, which version still works with 18.04?

**Comment by aaronliu0130** [comment]
Anything before 18.04 hit its EOL (and GitHub actions stopped supporting it), so 2.0.1 and before.

**Comment by rohezal** [comment]
Thank you a lot :). And yes, I just tried 2.5.0 before you answered me :sweat_smile:

**Comment by rohezal** [comment]
2.0.1 is not working anymore on Ubuntu 18.04. Also: is there a way to disable auto updates?

```
./upscayl-2.0.1-linux.AppImage
/home/user/Nextcloud/dd/arorua.png
🚀 => fileName arorua
🚀 => fileExt .png
🆙 COMMAND:  -i /home/user/Nextcloud/dd/arorua.png -o /home/user/Nextcloud/dd/arorua_upscayl_4x_realesrgan-x4plus.png -s 4 -m /tmp/.mount_upscaytm3QyB/resources/models -n realesrgan-x4plus  -f png
🚀 => upscayl.stderr.on => stderr.toString() /tmp/.mount_upscaytm3QyB/resources/bin/upscayl-realesrgan: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_upscaytm3QyB/resources/bin/upscayl-realesrgan)

Done upscaling
download range: bytes=240294390-240467943
New version 2.5.1 has been downloaded to /home/user/.cache/upscayl-updater/pending/upscayl-2.5.1-linux.AppImage

```

**Comment by NayamAmarshe** [comment]
> 2.0.1 is not working anymore on Ubuntu 18.04. Also: is there a way to disable auto updates?
> 
> ```
> ./upscayl-2.0.1-linux.AppImage
> /home/user/Nextcloud/dd/arorua.png
> 🚀 => fileName arorua
> 🚀 => fileExt .png
> 🆙 COMMAND:  -i /home/user/Nextcloud/dd/arorua.png -o /home/user/Nextcloud/dd/arorua_upscayl_4x_realesrgan-x4plus.png -s 4 -m /tmp/.mount_upscaytm3QyB/resources/models -n realesrgan-x4plus  -f png
> 🚀 => upscayl.stderr.on => stderr.toString() /tmp/.mount_upscaytm3QyB/resources/bin/upscayl-realesrgan: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_upscaytm3QyB/resources/bin/upscayl-realesrgan)
> 
> Done upscaling
> download range: bytes=240294390-240467943
> New version 2.5.1 has been downloaded to /home/user/.cache/upscayl-updater/pending/upscayl-2.5.1-linux.AppImage
> 
> ```

You can use the latest upscayl. Did you try the commands I sent above?

**Comment by rohezal** [comment]
glibc fails to build because of some strange pointer conversion error:

https://gcc.gnu.org/pipermail/gcc-patches/2020-September/554415.html

**Comment by NayamAmarshe** [comment]
> glibc fails to build because of some strange pointer conversion error:
> 
> https://gcc.gnu.org/pipermail/gcc-patches/2020-September/554415.html

Oh sad. One question though, why still use Ubuntu 18.04? Why not upgrade to the latest one? I believe there's a lot to gain since 18.04 reached EOL last month.

**Comment by rohezal** [comment]
I am a paranoid guy, who don't trusts companies like Valve and lets run steam in an LXC container (with all the problems this creates). The LXC containers needs the same driver settings / version as the host does. I am afraid, that if I update the host, the container might stop working.

**Comment by NayamAmarshe** [comment]
> I am a paranoid guy, who don't trusts companies like Valve and lets run steam in an LXC container (with all the problems this creates). The LXC containers needs the same driver settings / version as the host does. I am afraid, that if I update the host, the container might stop working. 

Then why not just use flatpaks? They're sandboxed.
