### ISSUE TITLE
Dropdown list for GPU (ID) selection

### ISSUE THREAD

**Issue by FiodarShurankou** [upscayl/upscayl#316]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

GPU selection involves rendering an image and checking in the logs to check the ID, not so trivial for an average user.

### Description

Make the GPU selection a dropdown similar to model selection where you can see the GPU names

### Alternatives

Add a button "List GPU IDs" wich shows the user the GPU list with IDs and names

**Comment by NayamAmarshe** [comment]
Great idea but GPU ID is more complicated than just a dropdown. It also supports multi-GPU and hence not really something I want to spend time making a GUI for.
It's an advanced option for advanced users, as such, I currently do not see a need for a GPU ID dropdown.

**Comment by aaronliu0130** [comment]
Is there a complication that makes the dropdown more difficult than logging the GPU IDs?

It may not be advanced for users with an iGPU and dGPU (which is most users with a dGPU) who get the former selected.

**Comment by NayamAmarshe** [comment]
No plans for this (for now), sorry.
