### ISSUE TITLE
Hello, i have a Nvidia GTX760 and drivera are upto date. do i need a new Nvidia cArd? or what is vulkan?

### ISSUE THREAD

**Issue by ChicodelMar** [upscayl/upscayl#317]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

🐞 BACKEND REPORTED:  image upscayl:  [0 NVIDIA GeForce GTX 760]  queueC=0[16]  queueG=0[16]  queueT=1[1]
[0 NVIDIA GeForce GTX 760]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 760]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 760]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce GTX 760]  queueC=0[16]  queueG=0[16]  queueT=1[1]
[0 NVIDIA GeForce GTX 760]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 760]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 760]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

### To Reproduce

onyl with GTX760

### Expected Behavior

error

### Version/Commit Hash

2.5

### OS Specifics

GTX760

**Comment by NayamAmarshe** [comment]
Your GPU is too old. I don't think it's compatible with Upscayl. You need a GPU released around 2018-2019

**Comment by ChicodelMar** [comment]
thank you very muhc...and thanks for the great tool, im a member ;-) have a great weekend

**Comment by ChicodelMar** [comment]
should i buy a nvidia or AMD? can you gibe some good suggestions? thanks

**Comment by NayamAmarshe** [comment]
> should i buy a nvidia or AMD? can you gibe some good suggestions? thanks

It depends on your budget but if you're buying any new card, all of them will be compatible :)

**Comment by ChicodelMar** [comment]
thank you , i bougth a RTX 3050, thanks again, i only need it for your upscayl ;-)

**Comment by NayamAmarshe** [comment]
Congratulations! Great to hear that! Hope Upscayl helps you with your new card :D
