### ISSUE TITLE
Images saved in previous batch input folder

### ISSUE THREAD

**Issue by fractalien** [upscayl/upscayl#319]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

After batch-upscaling a folder, subsequently upscaled individual files are put in the batch's source folder although the setting says "Defaults to the image's path", and hovering over the button "Set upload folder" shows a tooltip with the expected folder. This persists after deleting the folder – it gets recreated.

### To Reproduce

1. Batch-upscale a folder
2. Upscale an individual file

### Expected Behavior

The upscaled version of the individual file should be placed next to the original.

### Version/Commit Hash

2.5.1

### OS Specifics

NVIDIA GeForce GTX 980 Ti, Windows 10

**Comment by NayamAmarshe** [comment]
Did you set the option in the settings to remember output folder?

**Comment by fractalien** [comment]
No, never touched that. Checked now, and it's off.

**Comment by aaronliu0130** [comment]
Try setting it on?

**Comment by fractalien** [comment]
FYI, selecting images from a different source folder changed the target folder to that. But anyway, I didn't really doubt that there was a way to change the target, but just wanted to report the bug that it's not correct after batch processing.

**Comment by Athenakt** [comment]
I set the option to remember the output folder. 
Despite that, after running a batch and starting the next one, my input folder is set to my previous output folder, and my output folder is set to my previous input folder.

**Comment by Athenakt** [comment]
Sorry for the delay.

I still have to specify the settings every time I do an Upscayl batch. "Select folder" for the Input points to my last Output folder, and "Select Output Folder"- whoops and huzzah, it also went to the Output folder!

That setting only saves Output folders from the sound of it. Any chance of being able to also save the Input folder setting? It only makes sense...

Thanks!

Logs:
?? Getting saveImageAs from localStorage jpg
?? Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
?? Setting gpuId to empty string
?? Setting model to 
?? GET_MODELS_LIST:  C:\Users\aroth\Downloads\custom-models-main\custom-models-main\models
?? Resetting image paths
?? Setting model to realesrgan-x4plus-anime
?? BACKEND REPORTED:  ?? Custom Models Folder Path:  C:\Users\aroth\Downloads\custom-models-main\custom-models-main\models
?? BACKEND REPORTED:  ?? Detected Custom Models:  realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,ultrasharp-2.0.1
?? CUSTOM_MODEL_FILES_LIST:  realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,ultrasharp-2.0.1
?? Getting saveImageAs from localStorage jpg
?? Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
?? Setting gpuId to empty string
?? Getting rememberOutputFolder from localStorage true

**Comment by aaronliu0130** [comment]
You may want to file a new feature request for that.
