### ISSUE TITLE
upscayl encounters a JavaScript error in the main process

### ISSUE THREAD

**Issue by johnblommers** [upscayl/upscayl#32]
Version 1.1.1 AppImage running on PopOS 22.04 (Ubuntu derivative)
To reproduce:
1. Launch AppImage
2. Accept system integration dialog
3. Choose an image
4. Click Upscayl
5. JavaScript error:

The following is a screen grab of  the message:

![upscayl Error](https://user-images.githubusercontent.com/8484427/186789117-be1764b2-6902-4452-8547-a4acb8857794.png)

At this point the application hangs doing its spinner thing.

**Comment by NayamAmarshe** [comment]
I'll investigate.

**Comment by johnblommers** [comment]
**Update 1**. The error can be avoided. When launching the AppImage for the first time the system prompts for permission to integrate it into the system. 

Just click no. Then Upscayl will work allright.

**Update 2**. When I build Upscayl on Apple Silicon a very similar thing happens when launching the application. It's installed into `/Applications`, dragged there from the DMG file. Yes I gave Upscayl full disk permission. The error message upon clicking Step 4 is:

> **A JavaScript error occurred in the main process.**  
> Uncaught exception:  
> Error: spawn /Applications/Upscayl.app/Contents/Resources/bin/upscayl EACCES  
> at ChildProcess._handle.onexit (node:internal/child_process:283:19)  
> at onErrorNT (node:internal/child_process:478:16)  
> at process.processTicksAndRejections (node:internal/process/task_queues:83:21)  

<button>OK</button>

The error occurs in exactly the same place on Apple Silicon as it does on Intel Linux.

**Comment by NayamAmarshe** [comment]
Very interesting, so AppImage launcher is unsupported. I'll test it on my machine again.

**Comment by NayamAmarshe** [comment]
It's working fine for me.

**Comment by TanujW** [comment]
Can confirm this error persists on Apple Silicon:

```
Uncaught Exception:
Error: spawn /Applications/Upscayl.app/Contents/Resources/bin/upscayl EACCES
at ChildProcess._handle.onexit (node:internal/child_process:283:19)
at onErrorNT (node:internal/child_process:478:16)
at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Giving the app Full Disk Access has no effect

**Comment by NayamAmarshe** [comment]
> Can confirm this error persists on Apple Silicon:
> 
> ```
> Uncaught Exception:
> Error: spawn /Applications/Upscayl.app/Contents/Resources/bin/upscayl EACCES
> at ChildProcess._handle.onexit (node:internal/child_process:283:19)
> at onErrorNT (node:internal/child_process:478:16)
> at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
> ```
> 
> Giving the app Full Disk Access has no effect

Does it work in development environment?

**Comment by TGS963** [comment]
As the comment above mentioned, do try in a developmental environment if you can.

Alternatively, could you show the folder structure after extracting or mounting the AppImage?
`Upscayl-1.2.0.AppImage --appimage-mount`

**Comment by TanujW** [comment]
Does not work in the development environment either, even with sudo. Full traceback below:

```
objc[5305]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x223aedb50) and /Users/Tanuj/Desktop/upscayl/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x105a59d08). One of the two will be used. Which one is undefined.
warn  - You have enabled experimental feature (images) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
event - compiled client and server successfully in 455 ms (158 modules)
wait  - compiling...
event - compiled successfully in 37 ms (126 modules)
wait  - compiling...
event - compiled client and server successfully in 25 ms (158 modules)
ICON:  /Users/Tanuj/Desktop/upscayl/main/icon.png
wait  - compiling / (client and server)...
event - compiled client and server successfully in 35 ms (189 modules)
/Users/Tanuj/Desktop/upscayl/test.jpeg
🚀 => ipcMain.on => outputDir /Users/Tanuj/Desktop/upscayl
PRODUCTION? : true
EXEC:  /Users/Tanuj/Desktop/upscayl/resources/mac/bin/upscayl
error - uncaughtException: Error: spawn /Users/Tanuj/Desktop/upscayl/resources/mac/bin/upscayl EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/Tanuj/Desktop/upscayl/resources/mac/bin/upscayl',
  path: '/Users/Tanuj/Desktop/upscayl/resources/mac/bin/upscayl',
  spawnargs: [
    '-i',
    '/Users/Tanuj/Desktop/upscayl/test.jpeg',
    '-o',
    '/Users/Tanuj/Desktop/upscayl/test_upscayled_4x.jpeg',
    '-s',
    4,
    '-m',
    '/Users/Tanuj/Desktop/upscayl/resources/models',
    '-n',
    'realesrgan-x4plus'
  ]
}

```

**Comment by NayamAmarshe** [comment]
> Does not work in the development environment either, even with sudo. Full traceback below:
> 
> ```
> objc[5305]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x223aedb50) and /Users/Tanuj/Desktop/upscayl/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x105a59d08). One of the two will be used. Which one is undefined.
> warn  - You have enabled experimental feature (images) in next.config.js.
> warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
> 
> info  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
> event - compiled client and server successfully in 455 ms (158 modules)
> wait  - compiling...
> event - compiled successfully in 37 ms (126 modules)
> wait  - compiling...
> event - compiled client and server successfully in 25 ms (158 modules)
> ICON:  /Users/Tanuj/Desktop/upscayl/main/icon.png
> wait  - compiling / (client and server)...
> event - compiled client and server successfully in 35 ms (189 modules)
> /Users/Tanuj/Desktop/upscayl/test.jpeg
> 🚀 => ipcMain.on => outputDir /Users/Tanuj/Desktop/upscayl
> PRODUCTION? : true
> EXEC:  /Users/Tanuj/Desktop/upscayl/resources/mac/bin/upscayl
> error - uncaughtException: Error: spawn /Users/Tanuj/Desktop/upscayl/resources/mac/bin/upscayl EACCES
>     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
>     at onErrorNT (node:internal/child_process:478:16)
>     at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   errno: -13,
>   code: 'EACCES',
>   syscall: 'spawn /Users/Tanuj/Desktop/upscayl/resources/mac/bin/upscayl',
>   path: '/Users/Tanuj/Desktop/upscayl/resources/mac/bin/upscayl',
>   spawnargs: [
>     '-i',
>     '/Users/Tanuj/Desktop/upscayl/test.jpeg',
>     '-o',
>     '/Users/Tanuj/Desktop/upscayl/test_upscayled_4x.jpeg',
>     '-s',
>     4,
>     '-m',
>     '/Users/Tanuj/Desktop/upscayl/resources/models',
>     '-n',
>     'realesrgan-x4plus'
>   ]
> }
> ```

Seems like a permission issue. Can you try 1.2.0?

**Comment by TanujW** [comment]
This was using 1.2.0

I tried changing permissions for the  folder, as well as for /usr/local/lib/node_modules, but neither helped. Any idea on what's causing the permission issue or any fixes I can try?

**Comment by NayamAmarshe** [comment]
@TanujW I'm honestly not sure. I don't have MacOS anymore so I used Sosumi to create these builds but because of the absence of hardware acceleration, I was unable to test the MacOS builds. We'll really need some help here.

**Comment by TanujW** [comment]
I'm not a Node developer, but if you think you have the patience to guide me, I can definitely give it a go. Could potentially help with signing as well (ref #34 ) since I have an Apple Dev account.

**Comment by NayamAmarshe** [comment]
@TanujW I'd suggest looking at index.js inside main folder.

The executable path is listed as `EXEC:  /Users/Tanuj/Desktop/upscayl/resources/mac/bin/upscayl`, that means it's trying to find the binary inside upscayl. Is it on the desktop? If yes, can you try moving the app to Applications?

**Comment by TanujW** [comment]
@NayamAmarshe Will check out index.js and see if I can trace the erroneous function/file by adding a few console logs. 

The location of the folder/binary shouldn't matter since the folder and it's contents all have the correct permissions. Moreover, since MacOS 11 (I think), Applications folder has stricter permissions than my desktop. But I'll give it a shot regardless.

**Comment by TanujW** [comment]
> The executable path is listed as `EXEC: /Users/Tanuj/Desktop/upscayl/resources/mac/bin/upscayl`, that means it's trying to find the binary inside upscayl. Is it on the desktop? If yes, can you try moving the app to Applications?

No go on the Applications folder after deleting node-modules & lock files, cleaning cache and reinstalling

**Comment by TanujW** [comment]
@NayamAmarshe Fixed. The problem was weird. It seems like the binary file (and no other file/folder) for some reason has the wrong permissions (readable instead of executable).

Original:
-rw-r--r--@
Corrected:
-rwxr-xr-x@

Any idea how to fix this during packaging?

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe Fixed. The problem was weird. It seems like the binary file (and no other file/folder) for some reason has the wrong permissions (readable instead of executable).
> 
> Original:
> -rw-r--r--@
> Corrected:
> -rwxr-xr-x@
> 
> Any idea how to fix this during packaging?

Aha! Nice!
I guess `chmod +x` and then `npm run dist:dmg` should fix the issue.

**Comment by TanujW** [comment]
Output DMG works flawlessly. Thanks @NayamAmarshe !

**Comment by NayamAmarshe** [comment]
> Output DMG works flawlessly. Thanks @NayamAmarshe !

Thanks for testing. I guess we'll reissue Mac builds with this change.

**Comment by TanujW** [comment]
Fix for DMG file downloaded from github:

After downloading the DMG and moving Upscayl into the applications folder, run the following commands:

`cd /Applications/Upscayl.app/Contents/Resources/bin/`

`chmod +x upscayl`

**Comment by johnblommers** [comment]
Let me confirm that also fixes the issue on my Apple Silicon machine. It fixes it for the version I compiled myself from source following the directions provided.
Sweet

As an aside, I had to  chuckle at myself. I had no idea that Node.js was available for Apple Silicon until today. That's a nice discovery so thanks!

**Comment by CavalcanteLeo** [comment]
<img width="260" alt="Screen Shot 2022-09-02 at 01 06 34" src="https://user-images.githubusercontent.com/1735944/188056974-6024cd97-63cc-4f2d-accb-eeb7ff6f6eb9.png">

same here

**Comment by NayamAmarshe** [comment]
> <img alt="Screen Shot 2022-09-02 at 01 06 34" width="260" src="https://user-images.githubusercontent.com/1735944/188056974-6024cd97-63cc-4f2d-accb-eeb7ff6f6eb9.png">
> 
> same here

Don't forget to read the instructions

**Comment by thezeroalpha** [comment]
For those using Homebrew on macOS, I created a [cask](https://github.com/thezeroalpha/homebrew-formulae/blob/master/Casks/upscayl.rb) that takes care of this. It should just work by running `brew install thezeroalpha/formulae/upscayl`.
