### ISSUE TITLE
The result is a downscale rather than an upscale

### ISSUE THREAD

**Issue by joomgallerytestit** [upscayl/upscayl#320]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Hi,

I have following problem:

Upscayl 2.5.1 always only generates a mini image under Windows 10 Prof. 64 bit on a Vulkan-compatible (see screenshot) GPU Radeon RX Vega M GH, but no result image is saved.

As you can see from the screenshots below, the Radeon GPU is listed with ID 1 on Windows, but according to the log from Upscayl with GPUID 0. However, the result is always the same whether I enter 0 or 1 for GPUID in Upscayl.

Thanks in advance and kind regards
Jtestit

![scrshot3](https://github.com/upscayl/upscayl/assets/40622822/7f86eda9-87bc-4e0c-95e5-4fbf7689bb3d)

![scrshot1](https://github.com/upscayl/upscayl/assets/40622822/c860dab3-21d6-4b0e-b902-af896f592457)

![scrshot-vulkan3](https://github.com/upscayl/upscayl/assets/40622822/0387ae40-2e73-4dab-a936-f20d08e9016a)

<details>
<summary>Logs</summary>
<pre>
🐞 BACKEND REPORTED:  📄 Selected File Path:  D:\tempo\upscayl\scrshot2.jpg
🖼 Selected Image Path:  D:\tempo\upscayl\scrshot2.jpg
📁 Selected Image Directory:  D:\tempo\upscayl
🖼 imagePath:  D:\tempo\upscayl\scrshot2.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\tempo\upscayl\scrshot2.jpg,-o,D:\tempo\upscayl\scrshot2_upscayl_4x_realesrgan-x4plus.jpg,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,-f,jpg
🐞 BACKEND REPORTED:  image upscayl:  [0 Radeon RX Vega M GH Graphics]  queueC=1[3]  queueG=0[1]  queueT=2[2]
[0 Radeon RX Vega M GH Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon RX Vega M GH Graphics]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 Radeon RX Vega M GH Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 Radeon RX Vega M GH Graphics]  queueC=1[3]  queueG=0[1]  queueT=2[2]
[0 Radeon RX Vega M GH Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon RX Vega M GH Graphics]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 Radeon RX Vega M GH Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  [1 Intel(R) HD Graphics 630]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) HD Graphics 630]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 Intel(R) HD Graphics 630]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) HD Graphics 630]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [1 Intel(R) HD Graphics 630]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) HD Graphics 630]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 Intel(R) HD Graphics 630]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) HD Graphics 630]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  D:\tempo\upscayl\scrshot2_upscayl_4x_realesrgan-x4plus.jpg
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberO

</pre>
</details>

### To Reproduce

Try to scale an image in the above system configuration!

### Expected Behavior

An upscaled image should have been output!

### Version/Commit Hash

2.5.1 for Windows

### OS Specifics

Radeon RX Vega M GH

**Comment by NayamAmarshe** [comment]
The logs show that there's no progress reported by the backend, only a success message. Not sure what's wrong here. I suspect it's the driver that's causing it.

Have you tried on some other hardware?

**Comment by joomgallerytestit** [comment]
Hello,

no, I don't have any other hardware because my device is relatively powerful (NUC8i7HVB).
The driver ist the latest one provided by the Intel® Driver- und Support-Assistent.

Kind regards
Jtestit

**Comment by joomgallerytestit** [comment]
The Intel Driver- and Support-Assistant states that the installed AMD driver Advanced Micro Devices, Inc./ version 30.0.21017.1000 from 17.05.2022 is the current one for my machine and the Radeon RX Vega MX GH.

Kind regards
jtestit

**Comment by joomgallerytestit** [comment]
Thanks a lot for your help!

The AMD-URLs you posted are not recommended by INTEL for iNucs but drivers certified by INTEL like this one from July of 2022:
https://www.intel.com/content/www/us/en/download/19269/radeon-rx-vega-m-graphics-driver-for-windows-10-64-bit-for-nuc8i7hnk-nuc8i7hvk.html

My Radeon driver was from an earlier month of 2022.

Kind regards
jtestit

**Comment by aaronliu0130** [comment]
Intel's opinions don't really matter on AMD equipment, especially when the thing I linked is recommended by AMD. Also where does it recommend against the AMD URL I posted?

**Comment by joomgallerytestit** [comment]
Not with the URL leading to the AMD automatic detection software but from INTEL like mentioned already in my former post:
https://github.com/upscayl/upscayl/issues/320#issuecomment-1546929249

Kind regards
jtestit

**Comment by NayamAmarshe** [comment]
This should be fixed in v2.8
