### ISSUE TITLE
Where did the Ultrasharp go?

### ISSUE THREAD

**Issue by royal-rigolo** [upscayl/upscayl#324]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

First, thank you for the amazing work, your app is lifesaving! Such a great job.

I just noticed a disturbing loss of quality in the renders of the **"General Photo (Ultrasharp)"** type of upscaler between the 2.0.1 and 2.5.1 version, on mac.
(maybe even happened between 2.5.0 and 2.5.1).

I can see you tried to upgrade it, but the last version now makes parts of the picture **very flat and blurry** when it treated the entire image way more homogeneously before. And it's exactly what I needed to preserve a regular sharper noise in the entire picture. 
I find it such a shame losing that feature in the last version.

### Alternatives

Do you think it would be possible to add it back in the next one?

**Comment by aaronliu0130** [comment]
I don’t think the 2.0.1 version was any better, it made them very pixelated. The model in the 2.0.1 in fact was not Ultrasharp, see #199.

**Comment by royal-rigolo** [comment]
Thank you for your answer aaronliu0130.
It might be true the Ultrasharp model offered kind of mediumsharp results before the 2.5.1 version. 
But this model had the good taste to maintain a consistent quality all over the pictures.
Not finding this satisfying option anymore seems more like a downgrade to me, unfortunately.

**Comment by aaronliu0130** [comment]
I don't think being consistent is enough, as a downscaling model would also be consistent. I have included it in my custom-models repository (see the commit above) and you can follow https://github.com/upscayl/upscayl/wiki/Guide to add it if you still want to use it.

**Comment by NayamAmarshe** [comment]
I'll have to take a look at the model and see which model it really was.

I'll add it to the custom models repository if I find the original one.

**Comment by royal-rigolo** [comment]
You are awesome! 
Thank you infinitely for putting it back in the custom models. 
It really is the one working best for what I need. Even so it's the softer of them all.

**Comment by aaronliu0130** [comment]
@NayamAmarshe I strongly suspect it's Remacri. Take a look at these results:
![snapshot7_upscayl_4x_ultrasharp-2 0 1](https://github.com/upscayl/upscayl/assets/11874211/51085091-9905-4ed4-9f6b-003bd8b0fe20)
![snapshot7_upscayl_4x_remacri](https://github.com/upscayl/upscayl/assets/11874211/43092804-fa68-4cfe-bb84-5b6ba942df85)
I don't see much difference except the second one is a lot more unsaturated/lighter.
@royal-rigolo could you try Remacri?

**Comment by royal-rigolo** [comment]
![TEST1-OLDULTRA](https://github.com/upscayl/upscayl/assets/123543764/35e04752-34e1-4c12-92f6-460f115f27eb)
![TEST1-ULTRA](https://github.com/upscayl/upscayl/assets/123543764/80de5cf9-e7f5-49df-bb45-4a49a8d87a2c)
![TEST1-REMACRI](https://github.com/upscayl/upscayl/assets/123543764/549f6f78-d5f0-4e82-a596-93419d6b6145)
![TEST1-ORIGINAL](https://github.com/upscayl/upscayl/assets/123543764/17c90437-b058-4d2f-83c3-0362d5074e41)
Hello @aaronliu0130. 
It appears my results are not quite like yours. 
Here is a little comparison on a detail, between Remacri, the latest Ultrasharp and the old one.

**Comment by aaronliu0130** [comment]
Thanks, very informative.
