### ISSUE TITLE
INVALID GPU OR FAILED

### ISSUE THREAD

**Issue by yohgizzy** [upscayl/upscayl#326]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

<details>
<summary>Logs</summary>
<pre>
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🎯 GET_MODELS_LIST:  C:\custom-models-main\models
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus-anime
🐞 BACKEND REPORTED:  📁 Custom Models Folder Path:  C:\custom-models-main\models
🐞 BACKEND REPORTED:  🔎 Detected Custom Models:  realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3
📜 CUSTOM_MODEL_FILES_LIST:  realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\yohgi\Downloads\Default_Classical_art_upper_body_portrait_painting_of_Skeleton_3_9302fd68-08a9-4973-bbf0-657a56973552_1.jpg
🖼 Selected Image Path:  C:\Users\yohgi\Downloads\Default_Classical_art_upper_body_portrait_painting_of_Skeleton_3_9302fd68-08a9-4973-bbf0-657a56973552_1.jpg
📁 Selected Image Directory:  C:\Users\yohgi\Downloads
🖼 imagePath:  C:\Users\yohgi\Downloads\Default_Classical_art_upper_body_portrait_painting_of_Skeleton_3_9302fd68-08a9-4973-bbf0-657a56973552_1.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\yohgi\Downloads\Default_Classical_art_upper_body_portrait_painting_of_Skeleton_3_9302fd68-08a9-4973-bbf0-657a56973552_1.jpg,-o,C:\Users\yohgi\Downloads\Default_Classical_art_upper_body_portrait_painting_of_Skeleton_3_9302fd68-08a9-4973-bbf0-657a56973552_1_upscayl_2x_realesrgan-x4plus-anime.jpg,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,,-f,jpg
🐞 BACKEND REPORTED:  image upscayl:  vkEnumerateInstanceExtensionProperties failed -1

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumerateInstanceExtensionProperties failed -1

🔄 Resetting image paths
🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
🐞 BACKEND REPORTED:  image upscayl:  vkEnumerateInstanceExtensionProperties failed -1

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumerateInstanceExtensionProperties failed -1

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
🐞 BACKEND REPORTED:  image upscayl:  vkEnumerateInstanceExtensionProperties failed -1
invalid gpu device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumerateInstanceExtensionProperties failed -1
invalid gpu device

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\yohgi\Downloads\00020-4021838673.png
🖼 Selected Image Path:  C:\Users\yohgi\Downloads\00020-4021838673.png
📁 Selected Image Directory:  C:\Users\yohgi\Downloads
🖼 imagePath:  C:\Users\yohgi\Downloads\00020-4021838673.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\yohgi\Downloads\00020-4021838673.png,-o,C:\Users\yohgi\Downloads\00020-4021838673_upscayl_2x_realesrgan-x4plus-anime.jpg,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,,-f,jpg
🐞 BACKEND REPORTED:  image upscayl:  vkEnumerateInstanceExtensionProperties failed -1

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumerateInstanceExtensionProperties failed -1

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
🔄 Resetting image paths
🐞 BACKEND REPORTED:  image upscayl:  vkEnumerateInstanceExtensionProperties failed -1

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumerateInstanceExtensionProperties failed -1

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
🐞 BACKEND REPORTED:  image upscayl:  vkEnumerateInstanceExtensionProperties failed -1
invalid gpu device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumerateInstanceExtensionProperties failed -1
invalid gpu device

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
</pre>
</details>

### To Reproduce

I'm using upscayl for the first time. 
I selected the image I wanted to upscale, set my output folder and click on Upscayl.
Then got that error message.

### Expected Behavior

nothing happened

### Version/Commit Hash

2.5.1

### OS Specifics

GTX 1060 6gb

### Screenshots

![Screenshot 2023-05-17 154541](https://github.com/upscayl/upscayl/assets/36752282/47cc92f2-4446-4aca-a1a1-47d23e614ffa)
![Screenshot 2023-05-17 154631](https://github.com/upscayl/upscayl/assets/36752282/2ae920d2-98bb-4691-a78b-4155abe87996)

**Comment by yohgizzy** [comment]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug


<details>
<summary>Logs</summary>
<pre>


</pre>
</details>


### To Reproduce

I'm using upscayl for the first time. 
I selected the image I wanted to upscale, set my output folder and click on Upscayl.
Then got that error message.


### Expected Behavior

nothing happened

### Version/Commit Hash

2.5.1

### OS Specifics

GTX 1060 6gb

### Screenshots

![Screenshot 2023-05-17 154541](https://github.com/upscayl/upscayl/assets/36752282/47cc92f2-4446-4aca-a1a1-47d23e614ffa)
![Screenshot 2023-05-17 154631](https://github.com/upscayl/upscayl/assets/36752282/2ae920d2-98bb-4691-a78b-4155abe87996)

**Comment by yohgizzy** [comment]
<details>
<summary>Logs</summary>
<pre>


</pre>
</details>


### To Reproduce

I'm using upscayl for the first time. 
I selected the image I wanted to upscale, set my output folder and click on Upscayl.
Then got that error message.


### Expected Behavior

nothing happened

### Version/Commit Hash

2.5.1

### OS Specifics

GTX 1060 6gb

### Screenshots

![Screenshot 2023-05-17 154541](https://github.com/upscayl/upscayl/assets/36752282/47cc92f2-4446-4aca-a1a1-47d23e614ffa)
![Screenshot 2023-05-17 154631](https://github.com/upscayl/upscayl/assets/36752282/2ae920d2-98bb-4691-a78b-4155abe87996)

**Comment by aaronliu0130** [comment]
Key line:
`🐞 BACKEND REPORTED:  image upscayl:  vkEnumerateInstanceExtensionProperties failed -1`
Apparently Vulkan wasn't able to detect any GPUs for some reason.

**Comment by aaronliu0130** [comment]
https://stackoverflow.com/questions/40037166/vulkan-sdk-setup-vkenumerateinstanceextensionproperties-failed-to-find-the-vk-k Do you have nVidia optimus enabled? If so try disabling it.

**Comment by yzf750** [comment]
I received the same error after upgrading to version 2.5.1 from 2.0.0. I resolved this issue by going to the settings page and entering a GPU ID. In my case I entered "0" (without quotes). Hope this helps.

**Comment by yohgizzy** [comment]
> https://stackoverflow.com/questions/40037166/vulkan-sdk-setup-vkenumerateinstanceextensionproperties-failed-to-find-the-vk-k Do you have nVidia optimus enabled? If so try disabling it.

I can't find where to turn it off?

**Comment by aaronliu0130** [comment]
@yohgizzy I found a guide here: https://jarrods.tech/how-to-turn-off-optimus-on-your-gaming-laptop/

**Comment by yohgizzy** [comment]
please I'm using a desktop

**Comment by aaronliu0130** [comment]
Ok. Optimus is a laptop-only feature, so it isn't that.

**Comment by aaronliu0130** [comment]
Your nVidia drivers are also the latest, correct?

**Comment by yohgizzy** [comment]
yeah, i even updated it yesterday

**Comment by NayamAmarshe** [comment]
Did you try setting Upscayl on performance mode in Advanced Display Settings?

**Comment by yohgizzy** [comment]
Yeah, i have tried that

**Comment by yohgizzy** [comment]
> I received the same error after upgrading to version 2.5.1 from 2.0.0. I resolved this issue by going to the settings page and entering a GPU ID. In my case I entered "0" (without quotes). Hope this helps.

it didn't change anything, thnx tho

**Comment by lindpark** [comment]
I get the same problem and this is my solution, in the setting page, set the 'save image as' to jpg

**Comment by DJboutit** [comment]
I have notice this error message like 10x more with the newest version that with than any of the older versions.

**Comment by NayamAmarshe** [comment]
> I have notice this error message like 10x more with the newest version than any of the older versions.  
> I am using a AMD video card and the drivers are the newest version.  
> I normally see this error when I do a run of 50+ images

Oh, interesting find.

**Comment by HannuEKN** [comment]
I had a similar issue with the Appimage on Ubuntu 20.04 with nVidia driver 530, Vulkan apparently working (vkcube actually displays a cube, and vkinfo telling a lot of stuff)

vullkaninfo | grep -iE 'layer|GPU' output ends in.
GPU id : 0 (Intel(R) UHD Graphics 630 (CFL GT2)):
		maxImageArrayLayers = 1
GPU id : 1 (llvmpipe (LLVM 12.0.0, 256 bits)):
		maxImageArrayLayers = 1
GPU id : 2 (NVIDIA GeForce GTX 1660 Ti):
		maxImageArrayLayers = 1

Vulkan version 1.2.73, layer version 1

Hrm "error 5" shown when running Appimage? (Appimage deleted)

**Comment by HannuEKN** [comment]
Oh. version 2.5.5 ^

**Comment by vlad00777** [comment]
> I received the same error after upgrading to version 2.5.1 from 2.0.0. I resolved this issue by going to the settings page and entering a GPU ID. In my case I entered "0" (without quotes). Hope this helps.

Same for me error after update to 2.5.5.
But 0 does not solve a problem for me (probably because I have a Laptop without external GPU) only with CPU AMD Ryzen 5 4600H with Radeon Graphics

**Comment by aaronliu0130** [comment]
@HannuEKN Try setting your GPU ID to 2.

**Comment by HannuEKN** [comment]
@aaronliu0130 Did not change anything, swapping out the AppImage to *.deb-installation maed it work, immediately.

**Comment by Parth589** [comment]
i had a similar problem. but i am not using nvidia graphic card. it says that i am using integrated graphics of intel chip. what should i do now?

**Comment by NayamAmarshe** [comment]
Your GPU isn't supported.

**Comment by aaronliu0130** [comment]
See the FAQ...

**Comment by kakhak** [comment]
This software does not work with iGPU, it refuses to work with my AMD 5700G APU. Ahh, what a shame!

**Comment by smartt3** [comment]
> J'ai reçu la même erreur après la mise à niveau vers la version 2.5.1 à partir de 2.0.0. J'ai résolu ce problème en accédant à la page des paramètres et en entrant un ID GPU. Dans mon cas, j'ai entré "0" (sans les guillemets). J'espère que cela t'aide.

où placer le 0 je ne sais même pas comment paramétrer le GPU

**Comment by kakhak** [comment]
No, that did not help in my case.

**Comment by aaronliu0130** [comment]
@smartt3 https://github.com/upscayl/upscayl/wiki/Guide

**Comment by vgrabovets** [comment]
I wasn't able to run .AppImage on Ubuntu - vkEnumeratePhysicalDevices failed 5
When running server with npm run dev - everything works

**Comment by yohgizzy** [comment]
thanks guys, I have tried almost everything but it didn't work for me.

**Comment by NayamAmarshe** [comment]
> I wasn't able to run .AppImage on Ubuntu - vkEnumeratePhysicalDevices failed 5 When running server with npm run dev - everything works

I really need to get to the bottom of this.
Not sure where to begin but I'll see what I can find.

**Comment by vgrabovets** [comment]
> > I wasn't able to run .AppImage on Ubuntu - vkEnumeratePhysicalDevices failed 5 When running server with npm run dev - everything works
> 
> I really need to get to the bottom of this. Not sure where to begin but I'll see what I can find.

Let me give you a bit of context: 
I downloaded latest .AppImage from the assets - vkEnumeratePhysicalDevices failed 5. 
I switched to the latest Nvidia drivers - app works as expected.
I restarted my PC - vkEnumeratePhysicalDevices failed 5 again.
I built binary myself - vkEnumeratePhysicalDevices failed 5
With the server running everything works.

**Comment by NayamAmarshe** [comment]
> > > I wasn't able to run .AppImage on Ubuntu - vkEnumeratePhysicalDevices failed 5 When running server with npm run dev - everything works
> > 
> > 
> > I really need to get to the bottom of this. Not sure where to begin but I'll see what I can find.
> 
> Let me give you a bit of context: I downloaded latest .AppImage from the assets - vkEnumeratePhysicalDevices failed 5. I switched to the latest Nvidia drivers - app works as expected. I restarted my PC - vkEnumeratePhysicalDevices failed 5 again. I built binary myself - vkEnumeratePhysicalDevices failed 5 With the server running everything works.

That's strange.
So for some reason, the spawned child process works in dev but not prod.

Did you try using the real-esrgan binary as is?

**Comment by vgrabovets** [comment]
I didn't change anything at all, so yes.

**Comment by NayamAmarshe** [comment]
> vkEnumeratePhysicalDevices failed 5

https://nvidia.custhelp.com/app/answers/detail/a_id/5182/~/unable-to-launch-vulkan-apps/game-on-notebooks-with-amd-radeon-igpus

Could you try this as well?

**Comment by NayamAmarshe** [comment]
Oh wait, sorry. You're not on Windows.

**Comment by NayamAmarshe** [comment]
One solution I can think of, is to update the Real-ESRGAN libraries. For example, Vulkan SDK.
The issue is, I can't reproduce this error. If I could, I'd have better chances at debugging.

**Comment by vshwjth** [comment]
solution given by @NayamAmarshe works on Windows machines

**Comment by vshwjth** [comment]
> > vkEnumeratePhysicalDevices failed 5
> 
> https://nvidia.custhelp.com/app/answers/detail/a_id/5182/~/unable-to-launch-vulkan-apps/game-on-notebooks-with-amd-radeon-igpus
> 
> Could you try this as well?

solution given by @NayamAmarshe  works on Windows machines
