### ISSUE TITLE
Preserve EXIF metadata

### ISSUE THREAD

**Issue by ghost** [upscayl/upscayl#327]
### Checklist

- [x] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

It would be nice if Upscayl preserved the metadata from the original images. Currently it is a lot of work to transfer them by hand.

### Alternatives

Do it manually with other tools.

**Comment by NayamAmarshe** [comment]
Ok, let's see if it's possible to include this feature in the next release.

**Comment by NayamAmarshe** [comment]
v2.8 comes with this feature :)

**Comment by woahhjack** [comment]
> v2.8 comes with this feature :)

Beauty, thanks!
