### ISSUE TITLE
Use actions/stale instead of probot/stale

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#328]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

Currently, we use https://github.com/marketplace/stale, which appears to be unmaintained (check issues and PRs). It lacks the major feature of closing issues as not planned.

### Expected Behavior

We should use https://github.com/actions/stale, which is maintained and has a lot more features including closing issues as not planned.

**Comment by NayamAmarshe** [comment]
Thanks. I'll set it up tomorrow or this weekend :)

**Comment by aaronliu0130** [comment]
A maintainer of the probot/stale repo just deprecated and archived it: https://github.com/probot/stale/pull/382

**Comment by NayamAmarshe** [comment]
Done!
