### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by FiodarShurankou** [upscayl/upscayl#329]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

I have cloned the repository and want to install the new build without waiting for the new release, but there are no instructions for it. For example my friend would like to have the GPU selection fix, but dont want to run npm command to start Upscayl every time

### Expected Behavior

Add build instructions section to allow users to have the latest updates without waiting for next release

**Comment by aaronliu0130** [comment]
It’s in the README.
