### ISSUE TITLE
Any thoughts on migrating to typescript?

### ISSUE THREAD

**Issue by JeelRajodiya** [upscayl/upscayl#33]

**Comment by NayamAmarshe** [comment]
We wanted to do that but electron and react weren't playing very nicely. So we chose the template from DeskCut. I really wanted this to be a typescript project but as of now, since the scope is small and the we're following good enough practices, typescript isn't needed.

**Comment by NayamAmarshe** [comment]
btw, if you'd like to help setup typescript in the project, we'd be more than happy to accept a PR :)

**Comment by JeelRajodiya** [comment]
> btw, if you'd like to help setup typescript in the project, we'd be more than happy to accept a PR :)

sounds Great! I'll start looking into it.

**Comment by davidCpp16** [comment]
What do you mean by "migrating to typescript"?

**Comment by JeelRajodiya** [comment]
> What do you mean by "migrating to typescript"?

sorry, after running the application (both binary file executable and  the development application) it turns out that my machine can not run upscayl properly. This problem has something to do with GPU compatibility. 
without running the application I can not test whether or not my implementation is correct. 

it's not possible for me anymore ;(

**Comment by NayamAmarshe** [comment]
The project is now in Typescript
