### ISSUE TITLE
Donate button doesn't work on mobile

### ISSUE THREAD

**Issue by thgh** [upscayl/upscayl#330]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

Chrome for Android

### Expected Behavior

.

**Comment by NayamAmarshe** [comment]
Hi, this is already an issue on @upscayl/upscayl.github.io

This repository is for Upscayl the application, not the website upscayl.org but thanks for reporting.
