### ISSUE TITLE
Allow upscales larger than 32k

### ISSUE THREAD

**Issue by DuckersMcQuack** [upscayl/upscayl#332]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

Images being 8k upscales max to 32k even if "expected res is 130k".

### Description

Images that is say 8k, to be able to properly upscale to expected 130k
![image](https://github.com/upscayl/upscayl/assets/9039370/8a78cf66-f684-477d-8471-f3a897049ff2)
![image](https://github.com/upscayl/upscayl/assets/9039370/685fcea4-f1e8-4ee8-93a3-c59bccb4a911)

### Alternatives

I've tried a few, even topaz wich is paid only goes up to 32k as well.

**Comment by NayamAmarshe** [comment]
Thanks for reporting and noticing the limit! Until we fork real-ESRGAN and start maintaining a version for Upscayl, we're unfortunately limited in our ability to fix this 😅

I'll add a calculation limit though, to show that it cannot cross 32k.

**Comment by NayamAmarshe** [comment]
> gotchu! :D
> 
> By the way, would tiling be a way it could "go past the limit" with? That way the "tile's" limit could be 32k even :P 

It actually already tiles them internally.

**Comment by NayamAmarshe** [comment]
> Ah ok. So is 32k a limit by the upscaler from OG image? Or can it upscale say max 4x of an image repeatedly until desired res is reached?

It can only do a certain limit, after which ncnn framework gives up.

**Comment by NayamAmarshe** [comment]
The latest PR fixes this

**Comment by DuckersMcQuack** [comment]
Just updated it, tried to upscale with double upscale, but apparently limit is 10k now.  Both 4x and 16x is both 10244x3936. Doesn't seem to want to make it higher of a very wide image.

**Comment by NayamAmarshe** [comment]
> Just updated it, tried to upscale with double upscale with the anime/art model, but apparently limit is 10k now. Both 4x and 16x is both 10244x3936. Doesn't seem to want to make it higher of a very wide image.

You can disable post processing in settings

**Comment by DuckersMcQuack** [comment]
> > Just updated it, tried to upscale with double upscale with the anime/art model, but apparently limit is 10k now. Both 4x and 16x is both 10244x3936. Doesn't seem to want to make it higher of a very wide image.
> 
> You can disable post processing in settings

What does the post process do though? apart from lowering resolution, practically eliminating why we upscale at all :P

**Comment by NayamAmarshe** [comment]
> > > Just updated it, tried to upscale with double upscale with the anime/art model, but apparently limit is 10k now. Both 4x and 16x is both 10244x3936. Doesn't seem to want to make it higher of a very wide image.
> > 
> > 
> > You can disable post processing in settings
> 
> What does the post process do though? apart from lowering resolution, practically eliminating why we upscale at all :P

It allows you to scale and compress images.

**Comment by DuckersMcQuack** [comment]
Got another resolution limitation:

https://privatebin.net/?1545ecc3e0c0c9ce#8rUrK4jkLDwhuhYNVRQ7KK3NuanHJk39Po18vBL8jruH

And yes, i love making these ridiculously high res images :P

**Comment by aaronliu0130** [comment]
Could you post that again? It expired.
Also, we're tracking this in #493 now.
