### ISSUE TITLE
Package for Apple Silicon chips

### ISSUE THREAD

**Issue by denis-kasak** [upscayl/upscayl#333]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

The mac-version of Upscayl is compiled for Intel chips. Please compile a version for Apple Silicon (ARM) chips so that the ressource usage is more efficient.

### Alternatives

Usage of existing intel chip binaries => ressource inefficient

**Comment by NayamAmarshe** [comment]
That won't be possible for now. Our binaries are x86_64 only.

**Comment by jacksongoode** [comment]
So all new Mac's will not be supported then?

**Comment by aaronliu0130** [comment]
I'll add a note. Also note that this isn't a design choice and is because of GitHub Actions not having any ARM runner (except self-hosted which we don't have the resources for).

**Comment by NayamAmarshe** [comment]
We'll post universal builds starting from 2.8
