### ISSUE TITLE
Add new models pls 

### ISSUE THREAD

**Issue by rk5w4hh2** [upscayl/upscayl#334]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

no Problem

### Description

could add the models 4x_scalenx_90k and 4x_fatal_Anime_500000_G and 4x_Lady0101_314000_G and 4x_RealSR_DF2K_JPEG and 4x_Link_500000_G and 4x_PixelPerfectV4_137000_G and 4x_NMKD-UltraYandere_300k and 4x_reks_effeks_photoanime_v2_150k and 4x_FatalPixels_340000_G and 4x_NMKD-YandereNeoXL_200k in the next update if possible pls

### Alternatives

no Alternatives

**Comment by NayamAmarshe** [comment]
Are they Real-ESRGAN models?

**Comment by aaronliu0130** [comment]
Do you have the files in a .bin + .param ? If so you can just load custom models by following the guide in the wiki.
