### ISSUE TITLE
the picture is pulled up and does not upscale

### ISSUE THREAD

**Issue by bimbek** [upscayl/upscayl#335]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Fast Real-ESRGAN)","value":"RealESRGAN_General_x4_v3"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🎯 GET_MODELS_LIST:  
🔄 Resetting image paths
🔀 Setting model to RealESRGAN_General_x4_v3
🔀 Model changed:  realesrgan-x4plus
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\я\Downloads\DreamShaper_v5_Enter_a_dreamsurreal_landscape_where_reality_an_3.jpg
🖼 Selected Image Path:  C:\Users\я\Downloads\DreamShaper_v5_Enter_a_dreamsurreal_landscape_where_reality_an_3.jpg
📁 Selected Image Directory:  C:\Users\я\Downloads
🖼 imagePath:  C:\Users\я\Downloads\DreamShaper_v5_Enter_a_dreamsurreal_landscape_where_reality_an_3.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\я\Downloads\DreamShaper_v5_Enter_a_dreamsurreal_landscape_where_reality_an_3.jpg,-o,C:\Users\я\Downloads\DreamShaper_v5_Enter_a_dreamsurreal_landscape_where_reality_an_3_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  C:\Users\я\Downloads\DreamShaper_v5_Enter_a_dreamsurreal_landscape_where_reality_an_3_upscayl_4x_realesrgan-x4plus.png
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\я\Downloads\Без названия.jpg
🖼 Selected Image Path:  C:\Users\я\Downloads\Без названия.jpg
📁 Selected Image Directory:  C:\Users\я\Downloads
🖼 imagePath:  C:\Users\я\Downloads\Без названия.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\я\Downloads\Без названия.jpg,-o,C:\Users\я\Downloads\Без названия_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  C:\Users\я\Downloads\Без названия_upscayl_4x_realesrgan-x4plus.png
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false

### To Reproduce

In general, I didn't do anything special, I just uploaded the file (I tried several), I also tried all types of upscaling, and each time the photo without loading immediately stretched up and became narrow

![Без названия](https://github.com/upscayl/upscayl/assets/60547195/9e178e88-3b1a-4a1b-9a4f-ad50a8d8a9b9)
![image](https://github.com/upscayl/upscayl/assets/60547195/d246882d-88ba-4f80-8745-6be273c1f783)

### Expected Behavior

actually, there should have been a loading and an upscale of the image behind it

### Version/Commit Hash

last one 2.5.1

### OS Specifics

Intel(R) UHD Graphics   	ntel(R) Pentium(R) Silver N6000 @ 1.10GHz  	Windows 10 Pro 22H2

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/60547195/8c713855-dd2e-4229-8262-00009651f246)
![image](https://github.com/upscayl/upscayl/assets/60547195/3d4b3aad-35ae-42aa-8426-35bcec8d6c42)
![image](https://github.com/upscayl/upscayl/assets/60547195/c5d56a6e-f5c3-4c98-87d1-8e6b5b83af54)

**Comment by aaronliu0130** [comment]
> * Do I need a GPU for this to work?
> * * Yes, unfortunately. NCNN Vulkan requires a Vulkan compatible GPU. Upscayl won't work with most iGPUs or CPUs.

> I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Comment by bimbek** [comment]
everything is fine, it turns out I reinstalled vidnovs and there were no necessary drivers, right now everything is working, please remove the rikroll

**Comment by aaronliu0130** [comment]
Great! However, we still do not support intel iGPUs as most of them don't support the graphics library we use. If fit works that's great, but if it doesn't we won't troubleshoot it.
