### ISSUE TITLE
dmg.blockmap - no mac release

### ISSUE THREAD

**Issue by gummipunkt** [upscayl/upscayl#338]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Hi,

in the last release thers's no valid dmg file, just a dmg.blockmap. Could you upload it? Thank you.

### To Reproduce

see release section

### Expected Behavior

there should be a dmg file

### Version/Commit Hash

2.5.1

### OS Specifics

macos ventura

**Comment by aaronliu0130** [comment]
![image](https://github.com/upscayl/upscayl/assets/11874211/d81c9cad-98cb-4bdc-8353-ba5196bc315d)
