### ISSUE TITLE
No upscaled image, empty preview

### ISSUE THREAD

**Issue by stefanovuga** [upscayl/upscayl#339]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

//

### To Reproduce

Unknown interface failures 

### Expected Behavior

Working "show/hide" area

### Version/Commit Hash

Version 2.5.1 (2.5.1)

### OS Specifics

MacOS 13.3.1 (a) (22E772610a), on MacBook Pro 2,2 GHz 6-Core Intel Core i7, Radeon Pro 555X 4 GB Intel UHD Graphics 630 1536 MB, 16 GB 2400 MHz DDR4, 

### Screenshots

[](url)
![Screenshot 2023-06-01 at 12 59 55](https://github.com/upscayl/upscayl/assets/80175678/3ca1b9c2-5f83-4fe0-a91c-6c153720a054)

**Comment by aaronliu0130** [comment]
Could you copy the logs from the settings?

**Comment by NayamAmarshe** [comment]
Please post the logs.

**Comment by Jackie1205NL** [comment]
I also have the same problem. Here is my log.

⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"普通照片 (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to ultramix_balanced
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1.png
🖼 Selected Image Path:  D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1.png
📁 Selected Image Directory:  D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1
🖼 imagePath:  D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1.png,-o,D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1_upscayl_4x_ultramix_balanced.jpg,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultramix_balanced,,,-f,jpg
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1_upscayl_4x_ultramix_balanced.jpg
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"普通照片 (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"普通照片 (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Getting gpuId from localStorage 1
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1.png,-o,D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1_upscayl_4x_ultramix_balanced.jpg,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultramix_balanced,-g,1,-f,jpg
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1_upscayl_4x_ultramix_balanced.jpg
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"普通照片 (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Getting gpuId from localStorage 1
⚙️ Getting rememberOutputFolder from localStorage false
🐞 BACKEND REPORTED:  🚫 Select Custom Models Folder Operation Cancelled
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"普通照片 (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Getting gpuId from localStorage 2
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1.png,-o,D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1_upscayl_4x_ultramix_balanced.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultramix_balanced,-g,2,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1_upscayl_4x_ultramix_balanced.png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1.png,-o,D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1_upscayl_4x_ultramix_balanced.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultramix_balanced,-g,2,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  D:\BaiduNetdiskWorkspace\Personal\Coding\商业调研\成片\Etsy上传用图片\Cuba1\Cuba1_upscayl_4x_ultramix_balanced.png
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"普通照片 (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Getting gpuId from localStorage 2
⚙️ Getting rememberOutputFolder from localStorage false

**Comment by aaronliu0130** [comment]
Does the same happen when you load an image from folders without Chinese characters?

**Comment by Jackie1205NL** [comment]
> Does the same happen when you load an image from folders without Chinese characters? Do you have a discrete GPU?

Yep, even if I load the picture from my desktop, the same issue will happen.

**Comment by aaronliu0130** [comment]
What GPU (and CPU if it has integrated graphics) do you have then?

**Comment by LifeHackerGTD** [comment]
I have integrated graphics ，but i meet the same problem

**Comment by aaronliu0130** [comment]
@LifeHackerGTD It says in the README that integrated graphics are not supported.

**Comment by aaronliu0130** [comment]
<details><summary>@laborant303's logs</summary><pre>

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 1
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\matte\Downloads\desktop-1600x900.jpg
🖼 Selected Image Path:  C:\Users\matte\Downloads\desktop-1600x900.jpg
📁 Selected Image Directory:  C:\Users\matte\Downloads
🖼 imagePath:  C:\Users\matte\Downloads\desktop-1600x900.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\matte\Downloads\desktop-1600x900.jpg,-o,C:\Users\matte\Downloads\desktop-1600x900_upscayl_4x_realesrgan-x4plus-anime.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-g,1,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  C:\Users\matte\Downloads\desktop-1600x900_upscayl_4x_realesrgan-x4plus-anime.png
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 1
⚙️ Getting rememberOutputFolder from localStorage false
</pre></details>

**Comment by David93GitHub** [comment]
I accidently solved the problem yestoday. In oder to play some games, I used the Directx repair  to complete some dynamic library files, after that, I found that upscayl also works. My GPU is integrated UHD770 in I712700.

**Comment by aaronliu0130** [comment]
@stefanovuga Is this problem solved for you?

**Comment by NayamAmarshe** [comment]
I'll mark this as fixed for now, because we haven't seen this bug (after applying the fix) in recent releases.

**Comment by Kiskadee-dev** [comment]
Having this issue on the latest version using flatpak, downgraded to 2.5 and it works fine
