### ISSUE TITLE
The macOS app isn't signed

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#34]
See https://developer.apple.com/developer-id/ and https://www.electronjs.org/docs/latest/tutorial/code-signing

**Comment by NayamAmarshe** [comment]
We'll add it in the initial release. I don't have MacOS anymore, neither does @TGS963 so it's kinda hard to maintain and test the MacOS builds.

**Comment by NayamAmarshe** [comment]
Is it signed now?

**Comment by aaronliu0130** [comment]
> Is it signed now?

Nope, it still isn't.
 - Signature verification failed:
/private/tmp/d20220922-20437-d1vvk1/Upscayl.app: code object is not signed at all
In architecture: x86_64

**Comment by NayamAmarshe** [comment]
> > Is it signed now?
> 
> Nope, it still isn't.
> 
> * Signature verification failed:
>   /private/tmp/d20220922-20437-d1vvk1/Upscayl.app: code object is not signed at all
>   In architecture: x86_64

Ah. The Electron Builder docs suggested that building on MacOS would automatically take the signature, I guess not.

**Comment by aaronliu0130** [comment]
See electron’s tutorial:
https://www.electronjs.org/docs/latest/tutorial/code-signing

**Comment by EthanM25** [comment]
Still isn't signed unfortunately.

**Comment by aaronliu0130** [comment]
@EthanM25 Yes I know about the workaround, but signing is still important for some package managers. Plus it's better for an object to be signed.

**Comment by EthanM25** [comment]
> @EthanM25 Yes I know about the workaround, but signing is still important for some package managers. Plus it's better for an object to be signed.

Wasn't discounting the importance of signing, I most certainly think it should be signed, was just offering an alternative for those who might be unaware of how to open an unsigned application.

**Comment by aaronliu0130** [comment]
Yes but that isn't exactly the point. Inability to open isn't really to problem as the solution to gatekeeper is trivial.

**Comment by NayamAmarshe** [comment]
No plans for this as of yet. PRs are welcome but I personally do not have the time to look into this 😅
