### ISSUE TITLE
Add upscale info in batch upscaled files (rename)

### ISSUE THREAD

**Issue by PhobosK** [upscayl/upscayl#340]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

Maybe connected to another enhancement reported here: #327

### Description

Right now when upscaling images and the output folder is the same as source, the image gets renamed with some Upscayl info like method used etc.
But if it is a batch job outputting results in another folder (or even a single job, but with another output folder) the image/s stay with the same name and one loses the info that the image was upscaled.

It would be great if the app has an option in settings where the user could select to activate an action which will add some EXIF metadata to the final image, containing some info for the method used, original size, app used etc :)

### Alternatives

Use EXIF data manipulation tools to add some metadata for the image/s that's been upscaled.

**Comment by NayamAmarshe** [comment]
Ok good idea. I'll rename this issue to 'Add upscale info in batch upscaled files'
