### ISSUE TITLE
2.5.5 renames a protected file flagged by Norton AV and doesn't allow installation

### ISSUE THREAD

**Issue by Athenakt** [upscayl/upscayl#342]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

After Norton AV stops the install due to 2.5.5 renaming a protected file, Upscayl returns an error "Failed to uninstall old application files. Please try running the installer again.: 2"

Norton AV action observed: "Suspicious process attempted renaming a file protected by Data Protector", but it doesn't name the file being protected.

### To Reproduce

On a computer with the latest version of Norton Antivirus (default settings) with Windows 10 Home 64 bit, update Upscayl to 2.5.5

Follow the prompts to allow installation of a file that isn't trusted yet

Wait for Upscayl to finish downloading files (It would be nice to have a prompt for that here; I didn't know what was going on until I looked at the Network activity of my Task Manager)

Norton AV shows the suspicious action and halts installation.

### Expected Behavior

Upscayl should be updated to 2.5.5

### Version/Commit Hash

2.5.1

### OS Specifics

AMD Radeon RX 5700 XT, Windows 10 Home 64 bit

**Comment by aaronliu0130** [comment]
Which file is the protected file?

**Comment by Athenakt** [comment]
The only file mentioned other than the Upscayl 2.5.5 exe file is Target: C:\Program Files\Upscayl\icon_128x128.png
I don't see how that could be the file that's the problem however.

I used Exclude Process by Norton to finish the install. 
But now when I start Upscayl, Norton comes up as 'Threats Detected' because there isn't a valid digital signature for the program. I allowed running the instance.

I did a couple of small batch Upscayls, but I'm still running into the issue where the Input and Output folder settings still are not retained after a batch is run. I still have to specify the settings.

Thanks!

**Comment by NayamAmarshe** [comment]
It's probably due to the Upscayl binaries not being signed. We'll soon be releasing Upscayl on Windows store but before that, no binaries will be signed as dealing with windows is a huge hassle for me.

If it's not about signature and if it's not fixed after signing, then I'm afraid I'll have to mark this as a wont-fix as this issue is being caused by a third party software, which the project is not responsible for and cannot account for.

**Comment by NayamAmarshe** [comment]
> I can deal with clicking 'Allow' in Norton AV. :)
> 
> However, the issue in [#319] still persists. The Input folder and Output folders aren't saving correctly as I mentioned above. Just letting you know since I tested it too.
> 

I fixed and tested #319.
Could you please post a comment there with the exact description of the problem and logs if possible?
