### ISSUE TITLE
Wow i love square ! this software is incredible to make...Squares ..

### ISSUE THREAD

**Issue by Ke031** [upscayl/upscayl#343]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

<details>
<summary>Logs</summary>
<pre>

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🎯 GET_MODELS_LIST:  
🔄 Resetting image paths
🔀 Setting model to ultrasharp
🔄 Resetting image paths
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\Volta\Downloads\00022-1828480031-closeup portrait of,, walking on the beach, shaved skin, no fur,.png
🖼 Selected Image Path:  C:\Users\Volta\Downloads\00022-1828480031-closeup portrait of,, walking on the beach, shaved skin, no fur,.png
📁 Selected Image Directory:  C:\Users\Volta\Downloads
🖼 imagePath:  C:\Users\Volta\Downloads\00022-1828480031-closeup portrait of,, walking on the beach, shaved skin, no fur,.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Volta\Downloads\00022-1828480031-closeup portrait of, , walking on the beach, shaved skin, no fur,_upscayl_2x_realesrgan-x4plus.png,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,,-f,png
🐞 BACKEND REPORTED:  image upscayl:  [0 NVIDIA GeForce RTX 2080 SUPER]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 2080 SUPER]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 2080 SUPER]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 2080 SUPER]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 2080 SUPER]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 2080 SUPER]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 2080 SUPER]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 2080 SUPER]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  [1 Intel(R) UHD Graphics 630]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) UHD Graphics 630]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 Intel(R) UHD Graphics 630]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) UHD Graphics 630]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [1 Intel(R) UHD Graphics 630]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) UHD Graphics 630]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 Intel(R) UHD Graphics 630]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) UHD Graphics 630]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  0,00%

🚧 UPSCAYL_PROGRESS:  0,00%

🐞 BACKEND REPORTED:  image upscayl:  2,08%

🚧 UPSCAYL_PROGRESS:  2,08%

🐞 BACKEND REPORTED:  image upscayl:  4,17%

🚧 UPSCAYL_PROGRESS:  4,17%

🐞 BACKEND REPORTED:  image upscayl:  6,25%

🚧 UPSCAYL_PROGRESS:  6,25%

🐞 BACKEND REPORTED:  image upscayl:  8,33%

🚧 UPSCAYL_PROGRESS:  8,33%

🐞 BACKEND REPORTED:  image upscayl:  10,42%

🚧 UPSCAYL_PROGRESS:  10,42%

🐞 BACKEND REPORTED:  image upscayl:  12,50%

🚧 UPSCAYL_PROGRESS:  12,50%

🐞 BACKEND REPORTED:  image upscayl:  14,58%

🚧 UPSCAYL_PROGRESS:  14,58%

🐞 BACKEND REPORTED:  image upscayl:  16,67%

🚧 UPSCAYL_PROGRESS:  16,67%

🐞 BACKEND REPORTED:  image upscayl:  18,75%

🚧 UPSCAYL_PROGRESS:  18,75%

🐞 BACKEND REPORTED:  image upscayl:  20,83%

🚧 UPSCAYL_PROGRESS:  20,83%

🐞 BACKEND REPORTED:  image upscayl:  22,92%

🚧 UPSCAYL_PROGRESS:  22,92%

🐞 BACKEND REPORTED:  image upscayl:  25,00%

🚧 UPSCAYL_PROGRESS:  25,00%

🐞 BACKEND REPORTED:  image upscayl:  27,08%

🚧 UPSCAYL_PROGRESS:  27,08%

🐞 BACKEND REPORTED:  image upscayl:  29,17%

🚧 UPSCAYL_PROGRESS:  29,17%

🐞 BACKEND REPORTED:  image upscayl:  31,25%

🚧 UPSCAYL_PROGRESS:  31,25%

🐞 BACKEND REPORTED:  image upscayl:  33,33%

🚧 UPSCAYL_PROGRESS:  33,33%

🐞 BACKEND REPORTED:  image upscayl:  35,42%

🚧 UPSCAYL_PROGRESS:  35,42%

🐞 BACKEND REPORTED:  image upscayl:  37,50%

🚧 UPSCAYL_PROGRESS:  37,50%

🐞 BACKEND REPORTED:  image upscayl:  39,58%

🚧 UPSCAYL_PROGRESS:  39,58%

🐞 BACKEND REPORTED:  image upscayl:  41,67%

🚧 UPSCAYL_PROGRESS:  41,67%

🐞 BACKEND REPORTED:  image upscayl:  43,75%

🚧 UPSCAYL_PROGRESS:  43,75%

🐞 BACKEND REPORTED:  image upscayl:  45,83%

🚧 UPSCAYL_PROGRESS:  45,83%

🐞 BACKEND REPORTED:  image upscayl:  47,92%

🚧 UPSCAYL_PROGRESS:  47,92%

🐞 BACKEND REPORTED:  image upscayl:  50,00%

🚧 UPSCAYL_PROGRESS:  50,00%

🐞 BACKEND REPORTED:  image upscayl:  52,08%

🚧 UPSCAYL_PROGRESS:  52,08%

🐞 BACKEND REPORTED:  image upscayl:  54,17%

🚧 UPSCAYL_PROGRESS:  54,17%

🐞 BACKEND REPORTED:  image upscayl:  56,25%

🚧 UPSCAYL_PROGRESS:  56,25%

🐞 BACKEND REPORTED:  image upscayl:  58,33%

🚧 UPSCAYL_PROGRESS:  58,33%

🐞 BACKEND REPORTED:  image upscayl:  60,42%

🚧 UPSCAYL_PROGRESS:  60,42%

🐞 BACKEND REPORTED:  image upscayl:  62,50%

🚧 UPSCAYL_PROGRESS:  62,50%

🐞 BACKEND REPORTED:  image upscayl:  64,58%

🚧 UPSCAYL_PROGRESS:  64,58%

🐞 BACKEND REPORTED:  image upscayl:  66,67%

🚧 UPSCAYL_PROGRESS:  66,67%

🐞 BACKEND REPORTED:  image upscayl:  68,75%

🚧 UPSCAYL_PROGRESS:  68,75%

🐞 BACKEND REPORTED:  image upscayl:  70,83%

🚧 UPSCAYL_PROGRESS:  70,83%

🐞 BACKEND REPORTED:  image upscayl:  72,92%

🚧 UPSCAYL_PROGRESS:  72,92%

🐞 BACKEND REPORTED:  image upscayl:  75,00%

🚧 UPSCAYL_PROGRESS:  75,00%

🐞 BACKEND REPORTED:  image upscayl:  77,08%

🚧 UPSCAYL_PROGRESS:  77,08%

🐞 BACKEND REPORTED:  image upscayl:  79,17%

🚧 UPSCAYL_PROGRESS:  79,17%

🐞 BACKEND REPORTED:  image upscayl:  81,25%

🚧 UPSCAYL_PROGRESS:  81,25%

🐞 BACKEND REPORTED:  image upscayl:  83,33%

🚧 UPSCAYL_PROGRESS:  83,33%

🐞 BACKEND REPORTED:  image upscayl:  85,42%

🚧 UPSCAYL_PROGRESS:  85,42%

🐞 BACKEND REPORTED:  image upscayl:  87,50%

🚧 UPSCAYL_PROGRESS:  87,50%

🐞 BACKEND REPORTED:  image upscayl:  89,58%

🚧 UPSCAYL_PROGRESS:  89,58%

🐞 BACKEND REPORTED:  image upscayl:  91,67%

🚧 UPSCAYL_PROGRESS:  91,67%

🐞 BACKEND REPORTED:  image upscayl:  93,75%

🚧 UPSCAYL_PROGRESS:  93,75%

🐞 BACKEND REPORTED:  image upscayl:  95,83%

🚧 UPSCAYL_PROGRESS:  95,83%

🐞 BACKEND REPORTED:  image upscayl:  97,92%

🚧 UPSCAYL_PROGRESS:  97,92%

🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  C:\Users\Volta\Downloads\00022-1828480031-closeup portrait of,walking on the beach, shaved skin, no fur,_upscayl_2x_realesrgan-x4plus.png
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
</pre>
</details>

### To Reproduce

Just execute the software ....

oh and there is another problem too, impossible to change the upscale to "2x" even if you set to this number.
It will stay at 4x. 

### Expected Behavior

Squares squares squares......

### Version/Commit Hash

2.5.1 & 2.5.5

### OS Specifics

Win10 RTX 2080Super

### Screenshots

![super](https://github.com/upscayl/upscayl/assets/119963095/368296f3-e075-4b15-bcd4-78dbc023834a)

**Comment by Ke031** [comment]
ok i didn't see the wiki, and now i know why and it seems logic ! sorry guyz, my bad ^^

**Comment by aaronliu0130** [comment]
(Just marking this as a Duplicate of #303)
