### ISSUE TITLE
Image doesn't render in preview if stored on a network drive (SMB)

### ISSUE THREAD

**Issue by jondycz** [upscayl/upscayl#344]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

When importing a file from an SMB server, the image doesn't show in the preview.

### To Reproduce

1) Import an image from a network drive
2) profit

### Expected Behavior

The image should show in the preview window just fine

### Version/Commit Hash

2.5.5

### OS Specifics

Windows 11, GTX1060 6GB

**Comment by aaronliu0130** [comment]
What does it show? Could you add a screenshot, or maybe the logs though I doubt that would help?

**Comment by jondycz** [comment]
> What does it show? Could you add a screenshot, or maybe the logs though I doubt that would help?

It looks the same as a broken image link in a browser. Shows broken image in top left corner and the rest is just black screen.

**Comment by NayamAmarshe** [comment]
That's because we can't support SMB. We're using file protocol to access files on computer, not smb protocol.

**Comment by jondycz** [comment]
It upscales the image and saves the image onto a network drive just fine. Only fails to display it. Kinda janky to let it partially work.

**Comment by NayamAmarshe** [comment]
> It upscales the image and saves the image onto a network drive just fine. Only fails to display it. Kinda janky to let it partially work.

Like I said, I don't think it can read the image from smb directly.

https://bugs.chromium.org/p/chromium/issues/detail?id=40415

**Comment by jondycz** [comment]
> > It upscales the image and saves the image onto a network drive just fine. Only fails to display it. Kinda janky to let it partially work.
> 
> Like I said, it can't read the image from smb directly.
> 
> https://bugs.chromium.org/p/chromium/issues/detail?id=40415

How about loading the image as a base64 encoded string? The app itself can load the image into memory and upscale it. Only the browser can not display it. So feeding it into chrome as base64 string would eliminate the need of storing it as a temporary file. Not sure about the memory footprint.
