### ISSUE TITLE
Add a check update button in settings page.

### ISSUE THREAD

**Issue by liudonghua123** [upscayl/upscayl#345]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

Hi, I want my upscayl app to get updates when new versions is available. Maybe a check-update button is a good idea. 
I searched the issues and found the update feature is already implemented. I saw `updaterCacheDirName: upscayl-updater` in `resources/app-update.yml`. And from https://github.com/electron-userland/electron-builder/issues/5646#issuecomment-785017352, I found the update feature is implemented via `electron-updater`. I also go to the `%localappdata%\upscayl-updater` and only found an old updates.

![image](https://github.com/upscayl/upscayl/assets/2276718/79a6061e-0c9e-4ae0-8bb7-b2573984ddba)

### Description

Add a check update button in settings page.

![image](https://github.com/upscayl/upscayl/assets/2276718/a650e8dc-6a18-4e30-a4e1-bffafc262e7e)

### Alternatives

Add such button somewhere else.

**Comment by NayamAmarshe** [comment]
Did it not inform you of a new update? That's not possible, I checked.

**Comment by NayamAmarshe** [comment]
I'll give it another look

**Comment by liudonghua123** [comment]
> Did it not inform you of a new update? That's not possible, I checked.

No, I didn't get any updates, so I searched the issues to verify is there any auto-update feature in this app.

**Comment by NayamAmarshe** [comment]
> > Did it not inform you of a new update? That's not possible, I checked.
> 
> No, I didn't get any updates, so I searched the issues to verify is there any auto-update feature in this app.

Could there be something wrong with your internet? Most people haven't reported any issues.

**Comment by liudonghua123** [comment]
> > > Did it not inform you of a new update? That's not possible, I checked.
> > 
> > No, I didn't get any updates, so I searched the issues to verify is there any auto-update feature in this app.
> 
> Could there be something wrong with your internet? Most people haven't reported any issues.

yeah, maybe the network issue caused  this problem.
