### ISSUE TITLE
Clarification of Upscayl impact on image DPI

### ISSUE THREAD

**Issue by Sivivatu** [upscayl/upscayl#347]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

When I run the upscaler I expect the DPI to increase. However, the image size increases in resolution but not dpi. 

This might be my misunderstanding but clarifying that in documentation would be useful.

### Expected Behavior

clarification of the upscaling impact on DPI

**Comment by aaronliu0130** [comment]
Upscayl's models should preserve the existing DPI, if that is indeed a measurement for images and not just displays. If you want better results you might wanna try downscaling before upscayling.

**Comment by Sivivatu** [comment]
> Upscayl's models should preserve the existing DPI, if that is indeed a measurement for images and not just displays. If you want better results you might wanna try downscaling before upscayling.

Thanks for clarifying. I'll have to re-evaluate my process
