### ISSUE TITLE
support for NT5.1

### ISSUE THREAD

**Issue by andika207** [upscayl/upscayl#350]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

is there a version that's known for a fact to to work on WinXP ?
I don't mind if it's portable so long as it runs fine

### Alternatives

don't know

**Comment by aaronliu0130** [comment]
Sorry, but no, as Electron and Chrome, both technologies this project depends on, have also dropped support. You may have some luck with https://github.com/xinntao/Real-ESRGAN .
