### ISSUE TITLE
GPU changing caused failure.

### ISSUE THREAD

**Issue by ryanniedev** [upscayl/upscayl#351]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

When I upgrade my 3080 to a 3090, and updated the newest version 2.5.5 the upsacayl stop generating any images with a prompt of "Error. Please make sure you have a Vulkan compatible GPU (Most modern GPUs support Vulkan). .
Upscayl does not work with CPU or iGPU sadly."
 Anything that I can do to solve this?

### To Reproduce

When I upgrade my 3080 to a 3090, and updated the newest version 2.5.5 

### Expected Behavior

Error. Please make sure you have a Vulkan compatible GPU (Most modern GPUs support Vulkan). .
Upscayl does not work with CPU or iGPU sadly."

### Version/Commit Hash

2.5.5

### OS Specifics

3090 Win11

### Screenshots

![errorUp](https://github.com/upscayl/upscayl/assets/134979172/0fe14a04-a37a-4ae4-9757-72225b5ea3da)

**Comment by NayamAmarshe** [comment]
Maybe try reinstalling your drivers.
Also, read the wiki.

**Comment by vladninja** [comment]
I have the similar error after the update to 2.5.5 from 2.1.X
![image](https://github.com/upscayl/upscayl/assets/76119088/f161477e-32c9-4f75-b290-7759b0cf4ed4)
Tried other images, but the same error was shown.

Version 2.1.X works fine

**Comment by aaronliu0130** [comment]
@vladninja Again, from the FAQ:
> *Do I need a GPU for this to work?
>   *Yes, unfortunately. NCNN Vulkan requires a Vulkan compatible GPU. Upscayl won't work with most iGPUs or CPUs. But hey, no harm in trying ;)

**Comment by ryanniedev** [comment]
> Maybe try reinstalling your drivers. Also, read the wiki.

Thanks NayamAmarshe, after reading the WIKI, I found out that the GPU ID should be 0,1,2 that works with Upscayl, not the actual 3080 or something. (I remember this was 3080 before I upgrade to 3090, so I filled in 3090 just like what GPU ID shows with 3080) Now I changed it to 0, it works perfectly.

Thanks again for your guide!
