### ISSUE TITLE
Batch files no longer save as JPG- can we get that back?

### ISSUE THREAD

**Issue by Athenakt** [upscayl/upscayl#353]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

We used to be able to save images as JPG when running batch Upscayls, but now it says only PNGs are supported for batches. If there's an important reason for it, that's okay. But otherwise, could we get that functionality back?

Thanks!

### To Reproduce

Select batch upscayling and upscale JPG files. They come out PNG

### Expected Behavior

Clicking the JPG setting should result in JPG images when batch upscayling.

### Version/Commit Hash

2.5.5

### OS Specifics

AMD Radeon RX 5700 XT, Windows 10 Home 64 bit

**Comment by aaronliu0130** [comment]
It is because it doesn't work, our underlying engine (real-esrgan) can only save batch jobs as png. This is also said in #174 and the FAQ.

**Comment by NayamAmarshe** [comment]
I'll have to dive into the C++ code and fix the bug myself. It's not an easy task because I don't know NCNN programming or the way things happen in the C++ land. I'll still give it a shot though.
