### ISSUE TITLE
upscaled pictures cannot be saved, shown as black

### ISSUE THREAD

**Issue by guanyuj** [upscayl/upscayl#354]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

<details>
<summary>Logs</summary>
<pre>

🐞 BACKEND REPORTED:  image upscayl:  [0 NVIDIA GeForce RTX 3080 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3080 Ti]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3080 Ti]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3080 Ti]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 3080 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3080 Ti]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3080 Ti]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3080 Ti]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%
</pre>
</details>

### To Reproduce

how

### Expected Behavior

![image](https://github.com/upscayl/upscayl/assets/136320132/13643677-2816-466a-a4c8-c93f88638e85)
![image](https://github.com/upscayl/upscayl/assets/136320132/42264ad4-86b6-4604-8b60-a3b056bdcbaf)

### Version/Commit Hash

2.5.5

### OS Specifics

RTX 3080 ix

### Screenshots

upscaled pictures cannot be saved, if upscale folder, a new folder will be generated, but no new picture.
![image](https://github.com/upscayl/upscayl/assets/136320132/ed00d416-2150-49df-8194-6ed0f53604a0)

**Comment by NayamAmarshe** [comment]
The log that you posted, is that the whole log?

**Comment by guanyuj** [comment]
> The log that you posted, is that the whole log?

not whole, just partly,

**Comment by guanyuj** [comment]
I think i found the problem. if the name of folder is with characters, then will appear that. I changed the folder name to only  alphabet and number, then it works. I don't know what is the problem. before hasn't happened.

**Comment by NayamAmarshe** [comment]
> I think i found the problem. if the name of folder is with characters, then will appear that. I changed the folder name to only alphabet and number, then it works. I don't know what is the problem. before hasn't happened.

What's the folder name?

**Comment by IVI7md** [comment]
yeah I'm having the same issue is there any fix for that?
![2023-06-13 04_30_09-](https://github.com/upscayl/upscayl/assets/136402347/fa208242-ee6e-42a7-8594-bb1beec17f39)

**Comment by aaronliu0130** [comment]
There were many reports of blank output unrelated to Chinese characters, I'll try to find one.

**Comment by udu3324** [comment]
same issue occuring (gtx 1650)

**Comment by NayamAmarshe** [comment]
I am currently in the process of forking Real-ESRGAN to see if I can fix these weird bugs

**Comment by IVI7md** [comment]
> 

will it be fixed anytime soon?

**Comment by ckwebdev** [comment]
Considering that it is similar to my issue, tiny picture during preview, blank output,  I would make sure to check that you have the installs as stated and then verify your GPU is Vulkan capable. 

Go here and check your device for proper support:
https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/checking_for_support.adoc

https://github.com/skeeto/vulkan-test

**Comment by ckwebdev** [comment]
I have a 3070 and no issue. I'll check what packs I have installed and driver version of GPU when I get home.

**Comment by ckwebdev** [comment]
Drivers and distributables installed on my working pc:

![1](https://github.com/upscayl/upscayl/assets/22624134/8e5a0ab1-bba9-4a2f-885a-334297ec7926)
![2](https://github.com/upscayl/upscayl/assets/22624134/da73e3b8-aceb-444b-88f3-ac1329971681)

**Comment by dtxn** [comment]
Hi. I'm having the same issues if I'm trying to upscale larger than 4k images. From 4k and smaller images upscaled 4 times works ok. If I want to upscale x2 or x3 then I get tiled view from any size image.

**Comment by NayamAmarshe** [comment]
> Hi. I'm having the same issues if I'm trying to upscale larger than 4k images. From 4k and smaller images upscaled 4 times works ok. If I want to upscale x2 or x3 then I get tiled view from any size image.

Please read the wiki.

**Comment by batteryhun78** [comment]
I'm experiencing the same issue with my RTX 3060. Reinstalled program, drivers, tried everything above mentioned, no success.

**Comment by GuillaumeIvan** [comment]
The image renders but is very corrupt with multiple large and small black squares where the image did not render. Reinstalled and tried all the different settings but no luck. Each image I generate / upscale is corrupt with black squares as if I am in a Demo version. Please help

**Comment by aaronliu0130** [comment]
@GuillaumeIvan Does your output look like the screenshot above or #303?

**Comment by NayamAmarshe** [comment]
Please check if v2.7.5 fixes the issue :)

**Comment by NayamAmarshe** [comment]
This is a weird bug tbh. I am able to reproduce is sometimes but then, after a few upscales, it disappears.

I'm thinking it's more of an underlying electron/Next.js bug than ours.

**Comment by NayamAmarshe** [comment]
Case in point.
<img width="1313" alt="image" src="https://github.com/upscayl/upscayl/assets/25067102/e05e0da2-a4c5-42fb-821b-022cf6995449">

**Comment by NayamAmarshe** [comment]
Thinking of switching to this: https://www.npmjs.com/package/he

**Comment by NayamAmarshe** [comment]
It seems that images that are too large cause this issue. It's an electron bug, like I suspected.

https://github.com/nylas/nylas-mail/issues/415

**Comment by aaronliu0130** [comment]
However that bug is already closed. Either they regressed or it's a different issue. Also that isue says "crash", not just doesn't showup.

**Comment by NayamAmarshe** [comment]
> However that bug is already closed. Either they regressed or it's a different issue. Also that issue says "crash", not just doesn't showup.

Oops, sorry. We need to move to the different issue then.

**Comment by aaronliu0130** [comment]
I can't find a current issue either. This sounds quite different as it doesn't render instead of crashing. Maybe we could use a different view/just open the result image natively when we detect that it didn't render?

**Comment by aaronliu0130** [comment]
Closing as original issue of not even saving is probably solved.
