### ISSUE TITLE
Latest update broke Upscayl on Windows 7

### ISSUE THREAD

**Issue by vorgbardo** [upscayl/upscayl#356]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Upscayl auto-updated today to 2.5.5. After the update, Upscayl will no longer start on my Windows 7 machine. Uninstalling and re-installing will not fix the issue. The error shown is:

Entry Point Not Found
The procedure entry point GetPackageFamilyName could not be located in the dynamic link library KERNEL32.dll.

Earlier version I had installed was 2.0.1, and it worked perfectly fine on my setup (and still does, after I reinstalled it and prevented it from auto-updating). I tried installing 2.5.1 manually to see if that version would work on my system, but it also has this same crash problem.

<details>
<summary>Logs</summary>
<pre>

</pre>
</details>

### To Reproduce

Install Upscayl on Windows 7 and try to start it.

### Expected Behavior

Upscayl should have started and worked normally.

### Version/Commit Hash

2.5.5

### OS Specifics

GPU: NVIDIA GeForce RTX 2060. OS: Windows 7 Ultimate 64-bit.

### Screenshots

![kuva](https://github.com/upscayl/upscayl/assets/113989345/b0d17f3b-611a-48b6-a50c-6befc87593fe)

**Comment by NayamAmarshe** [comment]
Hi, please see issue #305

**Comment by aaronliu0130** [comment]
Personally for an OS that has past EOL it should be not supported unless specified by default. Also, we do have an OS list at https://github.com/upscayl/upscayl/wiki/Compatibility-List though I'm not sure how one should link that in the README.

**Comment by NayamAmarshe** [comment]
> Cheers. Consider adding a list of supported OS versions to release notes to avoid similar confusion in the future, there is no mention anywhere that Win 7/8 support was dropped after 2.0.1.

Thanks for the feedback. I'll mention this in the installation section.
