### ISSUE TITLE
AMD Radeon R9 M380 not working

### ISSUE THREAD

**Issue by DaedalusYoung** [upscayl/upscayl#357]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Unsupported GPU, not listed on compatibility page.
<details>

<summary>Logs</summary>
<pre>

⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 0
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/jpeg","filePath":"/Users/DaedalusYoung/Pictures/aidb/pencat.jpg","extension":"jpg"}
🖼 Setting image path:  /Users/DaedalusYoung/Pictures/aidb/pencat.jpg
🗂 Setting output path:  /Users/DaedalusYoung/Pictures/aidb
🖼 imagePath:  /Users/DaedalusYoung/Pictures/aidb/pencat.jpg
🔤 Extension:  jpg
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 0
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 2
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,/Users/DaedalusYoung/Pictures/aidb/pencat.jpg,-o,/Users/DaedalusYoung/Pictures/aidb/pencat_upscayl_4x_realesrgan-x4plus-anime.jpg,-s,4,-m,/Applications/Upscayl.app/Contents/Resources/models,-n,realesrgan-x4plus-anime,-g,2,-f,jpg
🐞 BACKEND REPORTED:  image upscayl:  [0 AMD Radeon R9 M380]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 AMD Radeon R9 M380]  bugsbn1=0  bugbilz=110  bugcopc=0  bugihfa=0
[0 AMD Radeon R9 M380]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon R9 M380]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
invalid gpu device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  [0 AMD Radeon R9 M380]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 AMD Radeon R9 M380]  bugsbn1=0  bugbilz=110  bugcopc=0  bugihfa=0
[0 AMD Radeon R9 M380]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon R9 M380]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
invalid gpu device

🔄 Resetting image paths
🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 2
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 0
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting Upscaled Image Path
🚫 No valid image selected
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/jpeg","filePath":"/Users/DaedalusYoung/Pictures/aidb/pencat.jpg","extension":"jpg"}
🖼 Setting image path:  /Users/DaedalusYoung/Pictures/aidb/pencat.jpg
🗂 Setting output path:  /Users/DaedalusYoung/Pictures/aidb
🖼 imagePath:  /Users/DaedalusYoung/Pictures/aidb/pencat.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,/Users/DaedalusYoung/Pictures/aidb/pencat.jpg,-o,/Users/DaedalusYoung/Pictures/aidb/pencat_upscayl_4x_realesrgan-x4plus-anime.jpg,-s,4,-m,/Applications/Upscayl.app/Contents/Resources/models,-n,realesrgan-x4plus-anime,-g,0,-f,jpg
🐞 BACKEND REPORTED:  image upscayl:  [0 AMD Radeon R9 M380]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 AMD Radeon R9 M380]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon R9 M380]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon R9 M380]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 AMD Radeon R9 M380]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 AMD Radeon R9 M380]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon R9 M380]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon R9 M380]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🐞 BACKEND REPORTED:  image upscayl:  16.67%

🚧 UPSCAYL_PROGRESS:  16.67%

🐞 BACKEND REPORTED:  image upscayl:  33.33%

🚧 UPSCAYL_PROGRESS:  33.33%

🐞 BACKEND REPORTED:  image upscayl:  50.00%

🚧 UPSCAYL_PROGRESS:  50.00%

🐞 BACKEND REPORTED:  image upscayl:  66.67%

🚧 UPSCAYL_PROGRESS:  66.67%

🐞 BACKEND REPORTED:  image upscayl:  83.33%
dyld: lazy symbol binding failed: Symbol not found: __ZNSt3__14__fs10filesystem10__absoluteERKNS1_4pathEPNS_10error_codeE
  Referenced from: /Applications/Upscayl.app/Contents/Resources/bin/upscayl-realesrgan (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libc++.1.dylib

dyld: Symbol not found: __ZNSt3__14__fs10filesystem10__absoluteERKNS1_4pathEPNS_10error_codeE
  Referenced from: /Applications/Upscayl.app/Contents/Resources/bin/upscayl-realesrgan (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libc++.1.dylib

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  83.33%
dyld: lazy symbol binding failed: Symbol not found: __ZNSt3__14__fs10filesystem10__absoluteERKNS1_4pathEPNS_10error_codeE
  Referenced from: /Applications/Upscayl.app/Contents/Resources/bin/upscayl-realesrgan (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libc++.1.dylib

dyld: Symbol not found: __ZNSt3__14__fs10filesystem10__absoluteERKNS1_4pathEPNS_10error_codeE
  Referenced from: /Applications/Upscayl.app/Contents/Resources/bin/upscayl-realesrgan (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libc++.1.dylib

🔄 Resetting image paths
🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 0
⚙️ Getting rememberOutputFolder from localStorage false
</pre>
</details>

### To Reproduce

Sorry, I'm new to this whole bug report thing, so apologies if I did everything wrong.

AMD Radeon R9 M380 supports Vulkan, but Upscayl says it's invalid. It is not listed on the compatibility page https://github.com/upscayl/upscayl/wiki/Compatibility-List .

I'm also running it on MacOS 10.14. Even though it says it needs MacOS 11, but the application runs fine. If it couldn't run, MacOS wouldn't even start it. Upscayl doesn't complain about the OS, it only complains about the GPU.

It appears to start the upscaling process, get to 83.33% and then refuse to complete. See log:

> 🐞 BACKEND REPORTED:  image upscayl:  83.33%
> dyld: lazy symbol binding failed: Symbol not found: __ZNSt3__14__fs10filesystem10__absoluteERKNS1_4pathEPNS_10error_codeE
>   Referenced from: /Applications/Upscayl.app/Contents/Resources/bin/upscayl-realesrgan (which was built for Mac OS X 11.0)
>   Expected in: /usr/lib/libc++.1.dylib
> 
> dyld: Symbol not found: __ZNSt3__14__fs10filesystem10__absoluteERKNS1_4pathEPNS_10error_codeE
>   Referenced from: /Applications/Upscayl.app/Contents/Resources/bin/upscayl-realesrgan (which was built for Mac OS X 11.0)
>   Expected in: /usr/lib/libc++.1.dylib

Tried with images from various sources, so I doubt it's the format.

### Expected Behavior

As it was happily doing its thing, it was expected it would finish the job.

### Version/Commit Hash

2.0.1 and 2.5.1 and 2.5.5

### OS Specifics

AMD Radeon R9 M380; MacOS 10.14

**Comment by aaronliu0130** [comment]
As you can see in the "backend reported", our actual upscaling binary wouldn't be able to continue as that part can only run on macOS 11+. TL;DR, our backend doesn't work below macOS 11.

**Comment by DaedalusYoung** [comment]
Ok, but is the graphics card supported or not? The application complains that the graphics card is not compatible, however, the card should be supported, and it is not listed on the compatibility page. If the card is fine, and Upscayl would work fine if I would be able to upgrade my system, then the bug is that the error message incorrectly identifies the card as the cause for the failed process, not the OS.

Ideally, the whole application will fail to open, and the OS should be aware it will not be able to run it, as it does with other MacOS 11 application.

**Comment by NayamAmarshe** [comment]
> Ok, but is the graphics card supported or not? The application complains that the graphics card is not compatible, however, the card should be supported, and it is not listed on the compatibility page. If the card is fine, and Upscayl would work fine if I would be able to upgrade my system, then the bug is that the error message incorrectly identifies the card as the cause for the failed process, not the OS.
> 
> Ideally, the whole application will fail to open, and the OS should be aware it will not be able to run it, as it does with other MacOS 11 application.

Graphics might be supported, can't say for sure. You'll need to test it on macOS 11.

**Comment by aaronliu0130** [comment]
Your graphics card should be supported. I'm not sure if there's a way to set a minimum version other than an if statement based on the useragent.
