### ISSUE TITLE
Add Upscayl to the Scoop platform

### ISSUE THREAD

**Issue by TechPro424** [upscayl/upscayl#358]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

No problems, this request is just for user convenience.

### Description

Please add Upscayl to the [Scoop](https://scoop.sh/) platform.
It's a command line based package manager that makes the installation of apps much more convenient as I don't have to click "Next" a million times :)

### Alternatives

I don't know about any alternatives to Scoop.

**Comment by NayamAmarshe** [comment]
We'll soon be uploading Upscayl to Microsoft Store.

For the CLI tools, users are free to volunteer and create packages :)

The core team only focuses on Linux solutions mostly.

**Comment by TechPro424** [comment]
@NayamAmarshe https://github.com/TechPro424/scoop-bucket
Made a scoop bucket for this, can you add it to the home page?

**Comment by aaronliu0130** [comment]
is there a reason this can't be in the extras bucket?

**Comment by aaronliu0130** [comment]
@TechPro424 It's already in scoop extras. https://github.com/ScoopInstaller/Extras/pull/9771
