### ISSUE TITLE
Download count hasn't passed 1M yet

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#359]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

The README states that Upscayl has 1.6M downloads. However, I've added up the actual binaries' (not counting the YMLs and BLOCKMAPs) download counts:
```python
2.4k+810+1.2k+4.8k+3.6k+11.3k+695+2.7k+1.7k+3.7k+2.8k+11.3k+5.4k+4.5k+26k+48+25+6+9+9+32+181+2.4k+254+74+49+779+4.6k+24k+4.9k+1.1k+948+44k+144.7k+1.6k+215+57+54+97.4k+21.9k+176+139+680+10.4k+55.3k+6.9k+53+89+289+4.4k
Plus 6,045 on Flathub
AUR doesn't have public download counts
```
Which adds up to 516,716.

### Expected Behavior

There either should be something I'm overlooking or... we should remove the 1M claim? I'm not sure

**Comment by NayamAmarshe** [comment]
The downloads are from total endpoints being hit on the GitHub API for all the releases combined.

https://shields.io/category/downloads

If there's a calculation issue, I'd suggest creating an issue on shields.io side :)

**Comment by aaronliu0130** [comment]
Like I said, that's probably from the download count of the latest.YMLs . I think every time the app launches it downloads the right yml for the system to check updates, so our update checking is inflating the download count.

**Comment by NayamAmarshe** [comment]
> Like I said, that's probably from the download count of the latest.YMLs . I think every time the app launches it downloads the right yml for the system to check updates, so our update checking is inflating the download count.

No, I don't think it's the YAML. Their documentation doesn't mention that.

**Comment by aaronliu0130** [comment]
Their documentation says "GitHub all releases". I think that means every single artifact's download count added together. As the yml is an artificat it should be counting towards releases, as there's no reason to assume they will automatically discount all artifacts with the "yml" extension. Also they use the GitHub API which just says "download_count" without further information.

**Comment by NayamAmarshe** [comment]
> Their documentation says "GitHub all releases". I think that means every single artifact's download count added together. As the yml is an artificat it should be counting towards releases, as there's no reason to assume they will automatically discount all artifacts with the "yml" extension. Also they use the GitHub API which just says "download_count" without further information.
> 
> Edit: According to [random strangers at stackoverflow](https://github.com/ScoopInstaller/Extras/blob/master/bucket/upscayl.json), it is
> 
> > downloads number of your assets (files attached to the release), field download_count mentioned below, but, [as commented](https://stackoverflow.com/questions/4338358/github-can-i-see-the-number-of-downloads-for-a-repo/57993109#comment95277810_4338358), only for the most recent 30 releases
> 
> So yes, including YMLs.

That's actually still not entirely incorrect as the app has auto-update functionality. Nobody comes on github again to download the DMG. So YML downloads are the only way to judge the total downloads.

**Comment by NayamAmarshe** [comment]
and yes, I do understand it's not super-accurate as there's not really a way to aggregate downloads correctly. So it serves as a good approximation :)

**Comment by aaronliu0130** [comment]
No, it's very inflated. Just look at how much more latest-mac.yml is downloaded than upscayl-2.5.5.dmg, or even upscayl-2.5.1.dmg . And I just did a way to (albeit not automatically) estimate the amount of total downloads, and it shows that counting YMLs inflates the download count by >3x.

**Comment by NayamAmarshe** [comment]
> No, it's very inflated. Just look at how much more latest-mac.yml is downloaded than upscayl-2.5.5.dmg, or even upscayl-2.5.1.dmg . And I just did a way to (albeit not automatically) estimate the amount of total downloads, and it shows that counting YMLs inflates the download count by >3x, over an entire million more.

Like I said, the YMLs will obviously be used more because they're used by auto-updater. Yes, it might be inflated, however, it's probably the best way to judge and show a downloads counter at the moment.

When we release the apps on official stores, there won't be a way to grab the total downloads either.

**Comment by NayamAmarshe** [comment]
My opinion is, we leave it here as is, until we release on stores or find a better counter or something.

**Comment by aaronliu0130** [comment]
The downloads counter is not just the YMLs but everything in the last 30 days combined. This means that downloads are at least duplicated.

**Comment by NayamAmarshe** [comment]
Yeah, I understand.  I'll find a better measure or maybe remove it altogether later.

**Comment by TimChinye** [comment]
To be fair they never said "accurate"...
![screenshot of shields.io homepage with the slogan: "Concise, consistent, and legible badges"](https://github.com/upscayl/upscayl/assets/150863066/7dbdf28d-9351-4fa8-ab6d-f6b0aaa443c0)

**Comment by TimChinye** [comment]
To be fair they never said "accurate"...
![Screenshot of shields.io homepage with the slogan: "Concise, consistent, and legible badges"](https://github.com/upscayl/upscayl/assets/150863066/7dbdf28d-9351-4fa8-ab6d-f6b0aaa443c0)
