### ISSUE TITLE
[Bug] Clipboard paste in 1.2.0 is non-functional

### ISSUE THREAD

**Issue by ghalfacree** [upscayl/upscayl#36]
I see in the release notes that Upscayl 1.2.0 should come with clipboard support... but it doesn't seem to.

I've opened the AppImage version on Ubuntu 20.04 64-bit, and it works perfectly for upscaling images from disk - but it doesn't respond to Ctrl-V or Ctrl-Shift-V.

# Reproduction
1. Open an image in The GIMP
2. Copy it to the clipboard
3. Paste it into The GIMP to confirm image data is, in fact, on the clipboard
4. Open Upscayl 1.2.0
5. Paste the image into Upscayl

# Expected results
The copied image appears in Upscayl, allowing you to upscale it without having to have written it to disk first.

# Actual results
Nothing. Nada. Zip. Zero.

# Additional information
No errors are generated at the console; Upscayl simply appears to be entirely ignoring Ctlr-V.

**Comment by NayamAmarshe** [comment]
Hi, I think it's because the images you copy from other applications aren't detected as images. Try this, copy an image from Nautilus with Ctrl+C and then click the right empty area of upscayl and press Ctrl+V, you'll see your image working just fine.

**Comment by NayamAmarshe** [comment]
I just tested again, it's because of the file path. Upscayl requires a file-path for upscaling images, which images copied from applications don't provide. That's why it's not working.

**Comment by TGS963** [comment]
> Upscayl requires a file-path for upscaling images.
Yeah, because the binary takes input path and upscales to output path. I don't know if it is possible but we could try writing the copied image data into a temporary file to upscale it maybe?

**Comment by NayamAmarshe** [comment]
That'll have to wait then,  batch mode is a higher priority for me at the moment.

**Comment by NayamAmarshe** [comment]
This is still not fixed in v1.5. Perhaps in v2 I'll get back to this.
