### ISSUE TITLE
Load .pth PyTorch Models

### ISSUE THREAD

**Issue by dtxn** [upscayl/upscayl#360]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

Hi. I have a suggestion: make it possible to load custom sharpening/upscaling model as *.pth extension.

### Description

Hi. I have a suggestion: make it possible to load custom sharpening/upscaling model as *.pth extension.

### Alternatives

Hi. I have a suggestion: make it possible to load custom sharpening/upscaling model as *.pth extension.

**Comment by NayamAmarshe** [comment]
No that's not possible. We rely on NCNN, instead of PyTorch for models.

You can use Chainner to convert PTH to bin+param models.

**Comment by dtxn** [comment]
> No that's not possible. We rely on NCNN, instead of PyTorch for models.
> 
> You can use Chainner to convert PTH to bin+param models.

Thank you for the answer. However I'm newbie in those things, so probably I will not manage what and how to do :) 
But what I understood: so if I convert from pth to bin, what I should do further with that bin ?

**Comment by aaronliu0130** [comment]
Tencent's guide for converting to bin I found, may not be reliable: https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx
I just put the information on loading custom models in the [wiki's guide](https://github.com/upscayl/upscayl/wiki/Guide#custom-models).

**Comment by dtxn** [comment]
> Tencent's guide for converting to bin I found, may not be reliable: https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx I just put the information on loading custom models in the [wiki's guide](https://github.com/upscayl/upscayl/wiki/Guide#custom-models).

Thank you for the links. I checked them, but that conversion process waaay over my head :)

**Comment by NayamAmarshe** [comment]
> Author

I'll update the wiki with the conversion process. It's actually quite simple.

**Comment by dtxn** [comment]
> > Author
> 
> [Here's the guide for converting new models](https://github.com/upscayl/upscayl/wiki/%F0%9F%96%A5%EF%B8%8F-Model-Conversion---Create-more-AI-models!)
> 
> Happy upscayling! :)

Thank you for the detailed instructions :) By that time when I checked here, I found some small app Cupscale. With that app I just didn't need to do anything- just drag and drop and got what I needed :)
