### ISSUE TITLE
It seems that it can't recognize my GPU.

### ISSUE THREAD

**Issue by LINGMOE-X** [upscayl/upscayl#364]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

<details>
<summary>Logs</summary>
<pre>

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 0
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 0
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 2
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\23903\Pictures\Screenshots\Screenshot 2023-06-21 164106.png
🖼 Selected Image Path:  C:\Users\23903\Pictures\Screenshots\Screenshot 2023-06-21 164106.png
📁 Selected Image Directory:  C:\Users\23903\Pictures\Screenshots
🖼 imagePath:  C:\Users\23903\Pictures\Screenshots\Screenshot 2023-06-21 164106.png
🔤 Extension:  png
🔀 Model changed:  realesrgan-x4plus-anime
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\23903\Pictures\Screenshots\Screenshot 2023-06-21 164106.png,-o,C:\Users\23903\Pictures\Screenshots\Screenshot 2023-06-21 164106_upscayl_4x_realesrgan-x4plus-anime.png,-s,4,-m,D:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-g,2,-f,png
🐞 BACKEND REPORTED:  image upscayl:  [0 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[0 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
invalid gpu device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  [0 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[0 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
invalid gpu device

🔄 Resetting image paths
🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 2
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\23903\Pictures\Screenshots\Screenshot 2023-06-21 164106.png
🖼 Selected Image Path:  C:\Users\23903\Pictures\Screenshots\Screenshot 2023-06-21 164106.png
📁 Selected Image Directory:  C:\Users\23903\Pictures\Screenshots
🖼 imagePath:  C:\Users\23903\Pictures\Screenshots\Screenshot 2023-06-21 164106.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\23903\Pictures\Screenshots\Screenshot 2023-06-21 164106.png,-o,C:\Users\23903\Pictures\Screenshots\Screenshot 2023-06-21 164106_upscayl_4x_realesrgan-x4plus-anime.png,-s,4,-m,D:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,,,-f,png
🐞 BACKEND REPORTED:  image upscayl:  [0 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[0 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[0 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  vkAllocateMemory failed -2

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkAllocateMemory failed -2

🔄 Resetting image paths
🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false

</pre>
</details>

### To Reproduce

Feel free to select a picture, clicking the upscayl.

### Expected Behavior

it turned wrong. Can't continue to.

### Version/Commit Hash

2.5.5

### OS Specifics

AMD 6800H with Radeon Graphics. Windows 22h2 22621.1848

### Screenshots

<img width="726" alt="Screenshot 2023-06-21 183951" src="https://github.com/upscayl/upscayl/assets/58373835/91a71c8a-88ff-4f45-9345-dfe39b8c835d">

**Comment by LINGMOE-X** [comment]
<img width="421" alt="Screenshot 2023-06-21 185228" src="https://github.com/upscayl/upscayl/assets/58373835/be70ff82-1ca2-4a68-add7-698cabdbe350">
That showed AMD 6800H graphics supporting Vulkan feature.

**Comment by aaronliu0130** [comment]
> * Do I need a GPU for this to work?
>   * Yes, unfortunately. NCNN Vulkan requires a Vulkan compatible GPU. <strong>Upscayl won't work with most iGPUs or CPUs.</strong> But hey, no harm in trying ;)

Just being Vulkan compatible doesn't necessarily mean it should work.
