### ISSUE TITLE
Can you add a status bar in the icon on taskbar

### ISSUE THREAD

**Issue by dimon453** [upscayl/upscayl#365]
### Checklist

- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [x] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).

### Description

Hello, can you add a persentage or progress in taskbar icon on windows. It will really help. 

### Alternatives

where are no altarnatives, its just an UI improvement

**Comment by NayamAmarshe** [comment]
I think we already implemented that. The progress should show up on Windows.

**Comment by dimon453** [comment]
> I think we already implemented that. The progress should show up on Windows.

There are no it. I use windows 11
![Screen Shot 2023-06-25 at 14 21 00](https://github.com/upscayl/upscayl/assets/64100952/055fa418-41fa-4be8-8337-6bdc6adb8702)

**Comment by aaronliu0130** [comment]
![image](https://github.com/upscayl/upscayl/assets/11874211/cae08c09-c6e6-4c23-9f55-6838db7b9463)
I get one. Also that looks like Windows 10, but that also should have a progress bar.
