### ISSUE TITLE
App icon improvements

### ISSUE THREAD

**Issue by NicKoehler** [upscayl/upscayl#37]
I made this icon for the app, I think is an improvement of the current one.

There is always space for improvements, let me know what you think!

![Upscayl](https://user-images.githubusercontent.com/53040044/187046551-449734e2-08ae-463f-9afb-35720a56f948.jpg)

**Comment by NayamAmarshe** [comment]
This is really nice! Thanks a lot! We'll use this in the next version :D

**Comment by TGS963** [comment]
Wow thanks a lot! This looks neat 🔥

**Comment by NicKoehler** [comment]
I'm glad you like it, here's the svg file

![Upscayl](https://user-images.githubusercontent.com/53040044/187059901-892f811b-4c83-414c-a2ca-5753d04485ae.svg)
