### ISSUE TITLE
Encoding Error on Flatpak

### ISSUE THREAD

**Issue by gteachey** [upscayl/upscayl#371]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Well, I see this was raised like yesterday and closed...but it looks like I'm doing it right?
I have a NVIDIA GEFORCE RTX 3060 which I selected as '1' in the app, yet it's saying invalid GPU or FAILED in the logs. 
Where am I going wrong with this?

<summary>Logs</summary>
<pre>
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 1
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  /run/user/1000/doc/207107b3/data_src
🖼 Selected Folder Path:  /run/user/1000/doc/207107b3/data_src
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  /run/user/1000/doc/327dc980/full
🗂 Setting Output Path:  /run/user/1000/doc/327dc980/full
🧠 Remembering Output Folder:  /run/user/1000/doc/327dc980/full
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 1
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 1
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,/run/user/1000/doc/207107b3/data_src,-o,/run/user/1000/doc/327dc980/full,-s,4,-m,/app/upscayl/resources/models,-n,realesrgan-x4plus,-g,1,-f,png
🚧 FOLDER_UPSCAYL_PROGRESS:  both 00212.png and 00212.jpg output 00212.png ! 00212.png will output 00212.png.png

🚧 FOLDER_UPSCAYL_PROGRESS:  [0 Intel(R) Graphics (RPL-S)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) Graphics (RPL-S)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) Graphics (RPL-S)]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) Graphics (RPL-S)]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  [1 NVIDIA GeForce RTX 3060]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[1 NVIDIA GeForce RTX 3060]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 NVIDIA GeForce RTX 3060]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 NVIDIA GeForce RTX 3060]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  [2 llvmpipe (LLVM 15.0.7, 256 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[2 llvmpipe (LLVM 15.0.7, 256 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[2 llvmpipe (LLVM 15.0.7, 256 bits)]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[2 llvmpipe (LLVM 15.0.7, 256 bits)]  subgroup=8  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  8.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  8.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  16.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  16.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  25.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  25.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  41.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  41.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  50.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  50.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  58.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  58.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%
66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  75.00%
75.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  83.33%
83.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  91.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  91.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%
0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  8.33%

🔄 Resetting image paths
🚧 FOLDER_UPSCAYL_PROGRESS:  encode image /run/user/1000/doc/327dc980/full/00001.png failed

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
🔄 Resetting image paths
🚧 FOLDER_UPSCAYL_PROGRESS:  encode image /run/user/1000/doc/327dc980/full/00002.png failed

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
🚧 FOLDER_UPSCAYL_PROGRESS:  8.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  16.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  16.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  25.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  25.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  41.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  41.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  50.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  50.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  58.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  58.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%
66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  75.00%
75.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  83.33%
83.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  91.67%
91.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%
0.00%

🔄 Resetting image paths
🚧 FOLDER_UPSCAYL_PROGRESS:  encode image /run/user/1000/doc/327dc980/full/00003.png failed

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
🔄 Resetting image paths
🚧 FOLDER_UPSCAYL_PROGRESS:  encode image /run/user/1000/doc/327dc980/full/00004.png failed

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
🚧 FOLDER_UPSCAYL_PROGRESS:  8.33%
8.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  16.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  16.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  25.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  25.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  41.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  41.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  50.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  50.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  58.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  58.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  75.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  75.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  83.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  83.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  91.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  91.67%

🛑 Stopping Upscayl
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🛑 Stopping Upscaling Process 131
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 1
⚙️ Getting rememberOutputFolder from localStorage false
</pre>
</details>

### To Reproduce

Use an NVIDIA GeForce RTX 3060.
Try to upscale png images

### Expected Behavior

PNG image gets upscaled

### Version/Commit Hash

2.5.5

### OS Specifics

NVIDIA GeForce RTX 3060 Ubuntu 22.04

**Comment by aaronliu0130** [comment]
If you're using Windows, could you enable [performance mode](https://youtube.com/watch?v=sxvs6qYHJmc) for Upscayl?

**Comment by gteachey** [comment]
ah sorry this is on Ubuntu. Only have Linux to use for now

**Comment by NayamAmarshe** [comment]
Seems like some vulkan libraries are missing, that are causing this error.

Encode error is usually when the Real-ESRGAN fails to use some specific GPU functions.

It's not your GPU that's throwing the error here, it's most likely the OS. Some people have reported in the past that Ubuntu gives them issues but other distros work fine.

We've been unable to find out a solid reason for this.

**Comment by gteachey** [comment]
My issue lies with flatpak from what I can see. I just noticed you have binaries to download and run.
I ran the AppImage version and have no problems upscaling.
Thanks for those other options to use this! 

(I REALLY hate flatpak, always a problem with it when I use it....)
