### ISSUE TITLE
Error: vulkan compatible gpu nvidia

### ISSUE THREAD

**Issue by bit0bit** [upscayl/upscayl#379]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Paste the logs

<details><summary>Logs</summary><pre>

</pre>
</details>

### Describe the Bug

ERROR pop up saying, **'need Vulkan Compatible GPU...'.** But I have Nvidia GeForce 1660ti, and Nvidia web site says its compatible. I have updated the latest driver today only. What should I write in the tab says **"GPU ID"?** Is there any connection with that?

### To Reproduce

Select image then select output folder and run.

### Version/Commit Hash

2.5.5

### OS Specifics

Nvidia GeForce GTX 1660ti, Win 11

### Screenshots

![Screenshot 2023-07-02 212245](https://github.com/upscayl/upscayl/assets/138388115/df160dbc-cfc7-477d-8db3-cde7363354f1)

**Comment by aaronliu0130** [comment]
Have you tried [setting your GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id)?

**Comment by bit0bit** [comment]
I have read the process and tried again, it only says "INVALID GPU OR FAILED". I tried changing the ID as '0', '1', '2', etc  (just to try luck) .

🔄 Resetting image paths
🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 0
⚙️ Getting rememberOutputFolder from localStorage false

**Comment by aaronliu0130** [comment]
Did you set Upscayl to performance mode?

**Comment by bit0bit** [comment]
is there any? I haven't seen!

UPSCAYL SECTION:
![Screenshot 2023-07-03 021338](https://github.com/upscayl/upscayl/assets/138388115/0da2adea-9674-45e8-bd44-5157c56688a2)

SETTING SECTION:

![Uploading Sc
![Screenshot 2023-07-03 021455](https://github.com/upscayl/upscayl/assets/138388115/2046a1fe-b572-434d-bfc0-7691262a33f7)
reenshot 2023-07-03 021421.jpg…]()

**Comment by bit0bit** [comment]
SETTING SECTION: 1

![Screenshot 2023-07-03 021421](https://github.com/upscayl/upscayl/assets/138388115/ec63e09a-7dcf-499e-be3e-24f23b468b38)

**Comment by bit0bit** [comment]
SETTING SECTION: Part 2
![Screenshot 2023-07-03 021455](https://github.com/upscayl/upscayl/assets/138388115/ff589f36-c65a-41fd-bde8-0f38bbbbf974)

**Comment by aaronliu0130** [comment]
Read the guide.
![image](https://github.com/upscayl/upscayl/assets/11874211/6e18c997-6415-4783-b74f-2b1016d6c4b3)

**Comment by bit0bit** [comment]
Tried! No Luck!
![Screenshot 2023-07-03 021455](https://github.com/upscayl/upscayl/assets/138388115/5b0e97e2-aeff-4e6c-944e-edd7ed247ca7)

**Comment by bit0bit** [comment]
![Screenshot 2023-07-03 025201](https://github.com/upscayl/upscayl/assets/138388115/3fa0032f-24ed-467b-b44c-de2bd14bc6e9)

**Comment by aaronliu0130** [comment]
You input GPU IDs one at a time.

**Comment by bit0bit** [comment]
Yes ofcourse. That was a last desperate try.

**Comment by aaronliu0130** [comment]
So it just says "invalid GPU or failed"?

**Comment by NayamAmarshe** [comment]
Have you tried reinstalling graphics drivers using [NVCleanstall](https://www.techpowerup.com/download/techpowerup-nvcleanstall/)?

**Comment by bit0bit** [comment]
> So it just says "invalid GPU or failed"?



> So it just says "invalid GPU or failed"?
 Yep!! 
https://user-images.githubusercontent.com/138388115/250369990-df160dbc-cfc7-477d-8db3-cde7363354f1.jpg

**Comment by bit0bit** [comment]
> Have you tried reinstalling graphics drivers using [NVCleanstall](https://www.techpowerup.com/download/techpowerup-nvcleanstall/)?

No I didn't!

**Comment by bit0bit** [comment]
Tried, but issue remained. Can I download an older version?

**Comment by aaronliu0130** [comment]
It probably won't change anything as our core upscaling engine doesn't change between versions.

**Comment by bit0bit** [comment]
So, that means I'm out of luck to use this great peace of software for now :(

**Comment by NayamAmarshe** [comment]
I wish we could find a solution for this problem. Many people seem to have it.

**Comment by bit0bit** [comment]
Hey I think I found something!!

**Comment by bit0bit** [comment]
[This worked for me. ](https://youtu.be/fCSStZCM6a8) 
AMD issue!

**Comment by aaronliu0130** [comment]
just link to the guide?
https://nvidia.custhelp.com/app/answers/detail/a_id/5182/~/unable-to-launch-vulkan-apps%2Fgame-on-notebooks-with-amd-radeon-igpus

**Comment by AnshulSehrawat** [comment]
> [This worked for me. ](https://youtu.be/fCSStZCM6a8) AMD issue!

Thank you so much.
