### ISSUE TITLE
In-app warning for Windows about performance mode

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#380]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Add a GUI (maybe radio buttons) for setting the GPU ID that also tells about performance mode on Windows.

### Related Problem(s)

Having to dig into logs can be cumbersome and many often don't know about performance mode. This results in many not-bugs being filed.

### Alternatives

Make these instructions more prominent, somehow.

**Comment by NayamAmarshe** [comment]
Ok, I'll add a warning for Windows users.

**Comment by aaronliu0130** [comment]
Ok, uhh it turns out the first half of this is a duplicate of #316 
![⅓ compulsory rickrolls are issued for ⅓ duplicates of other issues and the FAQ](https://github.com/upscayl/upscayl/assets/11874211/1b6870c9-bc20-419b-8f08-e4f77db239e5)

**Comment by NayamAmarshe** [comment]
I forgot about this. I did start implementing it but it wasn't completed.
