### ISSUE TITLE
blockmap.exe file for Windows release

### ISSUE THREAD

**Issue by hughholster** [upscayl/upscayl#381]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

Hello, I am very new to these things, and I'm a bit confused about how to integrate the blockmap.exe file along with the upscayl.exe that is the main application. My app doesn't work (it doesn't upscayl and there are no files in the destination folder) but that issue has been adressed several times already. I thought maybe the blockmap.exe file has to come into play somehow and I'm not doing it right.

Hope you can help me,

All the best

**Comment by NayamAmarshe** [comment]
The blockmap is not required. You can download the EXE directly from https://upscayl.org
