### ISSUE TITLE
upscayl compatibility  #GPU

### ISSUE THREAD

**Issue by Axe7bravo** [upscayl/upscayl#382]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Intel (R) HD Graphics 620 is compatible with upscayl. Upscaled an image 4x. Below are the logs:

⚙️ Setting saveImageAs to png
🔀 Setting model to realesrgan-x4plus
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\LENOVO\Desktop\Hugging face\own\Bravo3.png
🖼 Selected Image Path:  C:\Users\LENOVO\Desktop\Hugging face\own\Bravo3.png
📁 Selected Image Directory:  C:\Users\LENOVO\Desktop\Hugging face\own
🖼 imagePath:  C:\Users\LENOVO\Desktop\Hugging face\own\Bravo3.png
🔤 Extension:  png
🔀 Model changed:  realesrgan-x4plus
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\LENOVO\Desktop\Hugging face\own\Bravo3.png,-o,C:\Users\LENOVO\Desktop\Hugging face\own\Bravo3_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,D:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,,-f,png
🐞 BACKEND REPORTED:  image upscayl:  [0 Intel(R) HD Graphics 620]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) HD Graphics 620]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) HD Graphics 620]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) HD Graphics 620]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 Intel(R) HD Graphics 620]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) HD Graphics 620]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) HD Graphics 620]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) HD Graphics 620]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🐞 BACKEND REPORTED:  image upscayl:  6.25%

🚧 UPSCAYL_PROGRESS:  6.25%

🐞 BACKEND REPORTED:  image upscayl:  12.50%

🚧 UPSCAYL_PROGRESS:  12.50%

🐞 BACKEND REPORTED:  image upscayl:  18.75%

🚧 UPSCAYL_PROGRESS:  18.75%

🐞 BACKEND REPORTED:  image upscayl:  25.00%

🚧 UPSCAYL_PROGRESS:  25.00%

🐞 BACKEND REPORTED:  image upscayl:  31.25%

🚧 UPSCAYL_PROGRESS:  31.25%

🐞 BACKEND REPORTED:  image upscayl:  37.50%

🚧 UPSCAYL_PROGRESS:  37.50%

🐞 BACKEND REPORTED:  image upscayl:  43.75%

🚧 UPSCAYL_PROGRESS:  43.75%

🐞 BACKEND REPORTED:  image upscayl:  50.00%

🚧 UPSCAYL_PROGRESS:  50.00%

🐞 BACKEND REPORTED:  image upscayl:  56.25%

🚧 UPSCAYL_PROGRESS:  56.25%

🐞 BACKEND REPORTED:  image upscayl:  62.50%

🚧 UPSCAYL_PROGRESS:  62.50%

🐞 BACKEND REPORTED:  image upscayl:  68.75%

🚧 UPSCAYL_PROGRESS:  68.75%

🐞 BACKEND REPORTED:  image upscayl:  75.00%

🚧 UPSCAYL_PROGRESS:  75.00%

🐞 BACKEND REPORTED:  image upscayl:  81.25%

🚧 UPSCAYL_PROGRESS:  81.25%

🐞 BACKEND REPORTED:  image upscayl:  87.50%

🚧 UPSCAYL_PROGRESS:  87.50%

🐞 BACKEND REPORTED:  image upscayl:  93.75%

🚧 UPSCAYL_PROGRESS:  93.75%

🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  C:\Users\LENOVO\Desktop\Hugging face\own\Bravo3_upscayl_4x_realesrgan-x4plus.png
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Setting rememberOutputFolder to false

**Comment by aaronliu0130** [comment]
Added

**Comment by NayamAmarshe** [comment]
Thanks for reporting!

**Comment by sdfgeoff** [comment]
Can confirm, works on `Intel(R) Core(TM) i7-8565U` which has a `00:02.0 VGA compatible controller: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620]`
