### ISSUE TITLE
DECODING ERROR

### ISSUE THREAD

**Issue by Cinou16213** [upscayl/upscayl#383]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

<details><summary>Logs</summary><pre>

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Fast Real-ESRGAN)","value":"RealESRGAN_General_x4_v3"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🎯 GET_MODELS_LIST:  
🔄 Resetting image paths
🔀 Setting model to RealESRGAN_General_x4_v3
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Fast Real-ESRGAN)","value":"RealESRGAN_General_x4_v3"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false

</pre>
</details>

### Describe the Bug

When using Upscayl I get an error message. 
![Capture Upscayl](https://github.com/upscayl/upscayl/assets/118073090/ca2445a0-acd9-4baf-84c3-6023bfe9b4ce)
![Capture Upscayl 2](https://github.com/upscayl/upscayl/assets/118073090/f1ffb992-1403-4b55-9bce-7448406c6b73)

### To Reproduce

I don't know!

### Version/Commit Hash

2.5.5

### OS Specifics

Intel(R) Core(TM) i7-3770K CPU - Windows 10

### Screenshots

![Capture Upscayl](https://github.com/upscayl/upscayl/assets/118073090/cb9a19ae-78c7-4b1d-82c7-7f248a9ce316)
![Capture Upscayl 2](https://github.com/upscayl/upscayl/assets/118073090/81909e04-1577-436d-b8cb-f7eed4133c84)

**Comment by aaronliu0130** [comment]
> Yes, unfortunately. NCNN Vulkan requires a Vulkan compatible GPU. Upscayl won't work with most iGPUs or CPUs. 

> I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
