### ISSUE TITLE
iMac Functionality

### ISSUE THREAD

**Issue by DrDaringPhD** [upscayl/upscayl#394]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Woks on iMac. 3.2 GHz 6-Core Intel Core i7 Radeon Pro 560X 4 GB. Although seems to be stuck at 4x upscale.

**Comment by aaronliu0130** [comment]
That's because you have a Radeon GPU.

**Comment by DrDaringPhD** [comment]
I figured that had something to do with it. I was mostly just following the advice given on the main page to let people know what it works on. It is quite functional on this hardware, as long as you stick to 4x. And crazy fast! Excellent upscaler.

**Comment by aaronliu0130** [comment]
Thanks, but like I said, the scale option is expected to be locked there by default. More information about it can be found in the wiki's guide.
