### ISSUE TITLE
x1 resolution option

### ISSUE THREAD

**Issue by Miraihi** [upscayl/upscayl#398]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Hello Upscayl team, thank you for your snappy and good-looking upscaler software. However where I find it lacking is in the absence of the option to not upscale at all (100%/x1). Some models specialize on artifact removal or even mild inpainting, and they require the image to stay at the same resolution (1x Jaywreck3-Lite by NMKD for example). I think that won't be that hard to implement since even cupscale had this function.

**Comment by aaronliu0130** [comment]
Could you suggest a model for this?

**Comment by Miraihi** [comment]
You can find a variety of such models [here](https://nmkd.de/?esrgan).

**Comment by aaronliu0130** [comment]
Could be done by implementing #412
