### ISSUE TITLE
Uspacyl Is Not Able To Process Jumbo Size Image You Have To Process Them One At A Time 

### ISSUE THREAD

**Issue by DJboutit** [upscayl/upscayl#399]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

<details><summary>Logs</summary><pre>

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to ultrasharp
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\DJboutit\Desktop\KW
🖼 Selected Folder Path:  C:\Users\DJboutit\Desktop\KW
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\DJboutit\Desktop\KW
🗂 Setting Output Path:  C:\Users\DJboutit\Desktop\KW
🧠 Remembering Output Folder:  C:\Users\DJboutit\Desktop\KW
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\DJboutit\Desktop\KW,-o,C:\Users\DJboutit\Desktop\KW,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultrasharp,,,-f,png
🚧 FOLDER_UPSCAYL_PROGRESS:  [0 AMD Radeon RX 6600 XT]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 AMD Radeon RX 6600 XT]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon RX 6600 XT]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon RX 6600 XT]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  [1 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[1 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.17%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.34%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.52%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.17%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.69%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.34%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.86%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.52%

🚧 FOLDER_UPSCAYL_PROGRESS:  1.03%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.69%

🐞 BACKEND REPORTED:  💯 Done upscaling
💯 FOLDER_UPSCAYL_DONE:  C:\Users\DJboutit\Desktop\KW
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage true
</pre></details>

### Describe the Bug

When you try to batch process 5 10 20 or 50 images it does not matter how many where the largest number it a min of 6k for the size,  the program will start run for 5 to 10 seconds then stop and say all done without process one image.  

### To Reproduce

Get 10 to 15 images with the largest size being 5500 to 7000 example 6300x3800 or 3000x6500 and batch process all the images at one time it will not complete.   Processing all of these jumbo one by one takes 3 to 4 times longer than batch processing them all at one go.  

### Version/Commit Hash

2.5.5

### OS Specifics

AMD RX 6600 XT Windows 10 Pro

### Expected Behavior

All of these images should complete batch processing with not stopping , if you have 15 to 100 jumbo size the program should take 30min to 4hrs to process all the image during batch process.

**Comment by aaronliu0130** [comment]
Possibly related to #332

**Comment by DJboutit** [comment]
> Possibly related to #332

Yes but the images I am trying to batch upscale any not that close to 32k size
