### ISSUE TITLE
black painting in the end

### ISSUE THREAD

**Issue by davidhhh123** [upscayl/upscayl#40]
black painting in the end

**Comment by TGS963** [comment]
Could you please elaborate on the issue?

**Comment by davidhhh123** [comment]
![Без имени](https://user-images.githubusercontent.com/73849221/187069906-ca35a789-a765-4898-813d-59913a1c5bce.png)
)

**Comment by davidhhh123** [comment]
here

**Comment by TGS963** [comment]
could you try and run the upscayl.exe in the installation directory from command prompt and show its output here?

**Comment by davidhhh123** [comment]
in powershell

**Comment by TGS963** [comment]
yes powershell would be okay too

**Comment by davidhhh123** [comment]
I use windows what you need to write just run?

**Comment by davidhhh123** [comment]
![Без имени](https://user-images.githubusercontent.com/73849221/187070347-c6c30bf9-2b08-449a-bb1d-68130b215db8.png)

**Comment by TGS963** [comment]
yes, I am talking about windows. Go to the installation directory using terminal or powershell by doing:
`cd "C:\Users\your username\AppData\Local\Programs\upscayl\"`
then just do:
`.\Upscayl.exe`

**Comment by TGS963** [comment]
> ![Без имени](https://user-images.githubusercontent.com/73849221/187070347-c6c30bf9-2b08-449a-bb1d-68130b215db8.png)

Don't run the setup again

**Comment by davidhhh123** [comment]
![Без имени](https://user-images.githubusercontent.com/73849221/187070753-b89bff69-1fba-446f-9753-f6c4381d4cec.png)
works but

**Comment by TGS963** [comment]
but?

**Comment by davidhhh123** [comment]
but it says that gl is disabled

**Comment by TGS963** [comment]
could you show the whole powershell output

**Comment by davidhhh123** [comment]
![Без имени](https://user-images.githubusercontent.com/73849221/187071652-d3778827-47bc-455f-b975-2fc56ae019c1.png)

**Comment by TGS963** [comment]
even after this the end result is black?

**Comment by davidhhh123** [comment]
![Без имени](https://user-images.githubusercontent.com/73849221/187071702-8966d1f8-02ee-4ef7-82a9-8c59bd5e6ea3.png)

**Comment by davidhhh123** [comment]
at the end it

**Comment by davidhhh123** [comment]
the same black picture

**Comment by TGS963** [comment]
yes that is not a bug, it occurs on my end too. but the image upscales perfectly fine in my case

**Comment by davidhhh123** [comment]
what can i do?

**Comment by TGS963** [comment]
the output image should be stored at the same location is that input image, unless you specified any other output path. try opening that file manually and see if that image is black as well

**Comment by davidhhh123** [comment]
![to_upscale_upscayled_4x](https://user-images.githubusercontent.com/73849221/187071841-b5d1c02b-031c-4a01-acca-e4a96176a0ae.jpeg)

**Comment by TGS963** [comment]
wow, I can't image what might be causing this. does this happen with any image you select?

**Comment by davidhhh123** [comment]
yes

**Comment by TGS963** [comment]
@NayamAmarshe could you take a look at this?

**Comment by NayamAmarshe** [comment]
I already mentioned, iGPU is not supported. Upscayl needs a discrete GPU to work properly.

https://github.com/upscayl/upscayl#faq-
