### ISSUE TITLE
 the possibility to add several folders with files at once

### ISSUE THREAD

**Issue by haidautuiosif** [upscayl/upscayl#402]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Hello, I was thinking of an update that consists in selecting several folders at once, this in case I want to let the laptop work for a longer time, and in case the images are in several folders. ON THE FOLDER SELECTION BUTTON, I HAVE THE OPTION TO SELECT MORE FOLDERS. THANK YOU

### Related Problem(s)

YES, I WAS GONE ON VACATION, AND I WOULD LIKE TO BE ABLE TO GIVE MY LAPTOP TO PROCESS MORE FOLDERS WITH IMAGES DURING THIS TIME

### Alternatives

IS THERE ANY ALTERNATIVE TO THIS SUGGESTION AT THIS MOMENT??

**Comment by aaronliu0130** [comment]
Thank you for your suggestion. Please refrain from shouting. While we implement this, you can try opening multiple windows of Upscayl.

**Comment by NayamAmarshe** [comment]
I don't think electron API allows selecting multiple directories.
