### ISSUE TITLE
Download button in readme file links to the image asset instead of the actual download

### ISSUE THREAD

**Issue by anghelos** [upscayl/upscayl#403]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

See title. The download button in the GitHub readme just opens an image of the download button.

**Comment by aaronliu0130** [comment]
Nice catch, I have no idea why this is happening, we have it surrounded by a link element. Since the image is outdated I've commented it out for now.
