### ISSUE TITLE
Mobile Compatibility 

### ISSUE THREAD

**Issue by scorpiol13** [upscayl/upscayl#404]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Please make this usable on iphone. Either as a mobile app or a mobile website.

### Related Problem(s)

I and millions of other busy people do their work on mobile phones

**Comment by aaronliu0130** [comment]
This will be a lot of work (a major API we use doesn't support mobile yet, so we'll either have to rewrite the app or fiddle with Cordova). That's not to say we won't work on this, it's just that we have [other priorities](https://github.com/upscayl/upscayl/milestone/2) at the moment

**Comment by mxvin** [comment]
That's why it's important not to target electron, instead use something like RN

**Comment by NayamAmarshe** [comment]
> That's why it's important not to target electron, instead use something like RN

No, Vulkan doesn't work on mobile. It's not the question of frontend but the backend.

**Comment by AndroidDeveloperLB** [comment]
Any news about this? I'm interested in a solution for Android.
Google offered only an example of using TensorFlowLite , but I can't find a way to create something myself, which uses a better model:

https://www.tensorflow.org/lite/examples/super_resolution/overview

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/examples/super_resolution/overview.ipynb

Can I use the current repository somehow to run on Android app?
