### ISSUE TITLE
Default model definitions

### ISSUE THREAD

**Issue by StrangerHelper** [upscayl/upscayl#405]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

I would like to know definitions of each model to better understand which model to use for what. For example, when should I use digital art model rather than esrgan, what's best for black&white image, or what's best for printability? And so on.

I do think that all of the models are similar in a way, but I am mainly looking what is best for each scenario. I am personally using Upscayl for coloring pages (so black and white), but I am unsure what model is best for this. I've tried ultrasharp the most because it looks crispier, but what would be the difference if I use digital art instead? They all look identical.

**Comment by aaronliu0130** [comment]
Only digital art (technically anime) is just for art (including sketchbooks); everything else is trained with all kinds of different images (some might have a real-life photo bias)

**Comment by StrangerHelper** [comment]
So, coloring pages that are black-and-white and fine as Digital Art?

I know that real-esrgan is superior, but what about comparing fast-esrgan with Digital Art model?

**Comment by aaronliu0130** [comment]
@StrangerHelper Should be. Fast-ESRGAN vs Digital Art is basically the same with REAL-ESRGAN to Digital Art.
