### ISSUE TITLE
NVIDIA GT1030 (SDDR4) is confirmed to work properly with Upscayl

### ISSUE THREAD

**Issue by thedoggybrad** [upscayl/upscayl#406]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

https://github.com/upscayl/upscayl/wiki/Compatibility-List (Compatibility List - Wiki)
Confirming that the NVIDIA GT1030 seems to work fine without any issues.

Original Photo (Non-upscaled): https://c4.wallpaperflare.com/wallpaper/994/286/441/windows-95-logo-blue-microsoft-hd-wallpaper-preview.jpg

### Screenshots

Upscaled using Upscayl:
![windows-95-logo-blue-microsoft-hd-wallpaper-preview_upscayl_4x_ultrasharp](https://github.com/upscayl/upscayl/assets/94173621/d10971e0-16b5-4e76-a40e-45376b7f0990)

Screenshots:
![2](https://github.com/upscayl/upscayl/assets/94173621/7aa78166-56dd-4a9e-8714-039a2d516289)
![1](https://github.com/upscayl/upscayl/assets/94173621/ff76d4ec-156d-4e80-acc8-4c0b15382745)

**Comment by thedoggybrad** [comment]
GPU Specs:
![Screenshot 2023-08-02 091405](https://github.com/upscayl/upscayl/assets/94173621/05349e3c-c6fc-40aa-9812-7a6e6d72450a)

**Comment by aaronliu0130** [comment]
I'm pretty sure unless otherwise specified all discrete GPUs should work with Upscayl. Thanks for confirming though.
