### ISSUE TITLE
尊敬的开发者能不能增加个简体中文界面

### ISSUE THREAD

**Issue by lesspem** [upscayl/upscayl#407]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

希望增加简体中文功能 zh-cn

### Related Problem(s)

希望增加简体中文功能 zh-cn

### Alternatives

希望增加简体中文功能 zh-cn

**Comment by aaronliu0130** [comment]
您好，这个 issue 与#91重复。
> I have checked that this issue isn't addressed in any other issue or pull request.

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

我们需要先给整个玩意儿转换成支持翻译的才能加简中

**Comment by QQ804218** [comment]
![image](https://github.com/upscayl/upscayl/assets/67571282/fddd5eee-24d4-479e-904a-b98f8950cd69)

**Comment by QQ804218** [comment]
![image](https://github.com/upscayl/upscayl/assets/67571282/8881bc66-4ee1-4d63-82e8-3574a2ca5034)
已找到三方汉化版
