### ISSUE TITLE
GTX 1650 not detected correctly by Upscayl

### ISSUE THREAD

**Issue by MattPinPCC** [upscayl/upscayl#408]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

<details><summary>Logs</summary><pre>

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 2
🔀 Setting model to 
🎯 GET_MODELS_LIST:  
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/png","filePath":"C:\\Users\\Matt Pin\\Pictures\\AI Generated\\Midjourney\\Niji 5\\Adoptables\\ch1y_William_anthro_cat_mechanic_reference_sheet_with_back_and__73afdb71-667d-411a-ab0c-0615f680271b.png","extension":"png"}
🖼 Setting image path:  C:\Users\Matt Pin\Pictures\AI Generated\Midjourney\Niji 5\Adoptables\ch1y_William_anthro_cat_mechanic_reference_sheet_with_back_and__73afdb71-667d-411a-ab0c-0615f680271b.png
🗂 Setting output path:  C:\Users\Matt Pin\Pictures\AI Generated\Midjourney\Niji 5\Adoptables
🖼 imagePath:  C:\Users\Matt Pin\Pictures\AI Generated\Midjourney\Niji 5\Adoptables\ch1y_William_anthro_cat_mechanic_reference_sheet_with_back_and__73afdb71-667d-411a-ab0c-0615f680271b.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Matt Pin\Pictures\AI Generated\Midjourney\Niji 5\Adoptables\ch1y_William_anthro_cat_mechanic_reference_sheet_with_back_and__73afdb71-667d-411a-ab0c-0615f680271b.png,-o,C:\Users\Matt Pin\Pictures\AI Generated\Midjourney\Niji 5\Adoptables\ch1y_William_anthro_cat_mechanic_reference_sheet_with_back_and__73afdb71-667d-411a-ab0c-0615f680271b_upscayl_4x_realesrgan-x4plus-anime.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-g,2,-f,png
🐞 BACKEND REPORTED:  image upscayl:  vkEnumeratePhysicalDevices failed 5
invalid gpu device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed 5
invalid gpu device

🔄 Resetting image paths
🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 2
⚙️ Getting rememberOutputFolder from localStorage false
</pre></details>

### Describe the Bug

I cannot get my gtx 1650 to be detected on Upscayl, I reinstalled the drivers to my graphics card and can confirm that vulkan is working. The program was working until after I factory reset my laptop.

### To Reproduce

> Reinstall Nvidia Driver (Version 536.67 - WHQL)

>Open Upscayl
![Capture](https://github.com/upscayl/upscayl/assets/141511802/8202d8af-b5c5-432d-a7b0-7976d970e0b6)

>Drag image into Upscayl

>Set Upscale Type to Digital Art

> Press UPSCAYL Button

### Version/Commit Hash

2.5.5

### OS Specifics

Windows 10 Home x64 (Version 10.0.19045 Build 19045) and Nvidia GTX 1650

### Expected Behavior

The program should have detected my GPU and set the GPU ID automatically and upscaled. 

### Screenshots

![ProofJustIncase](https://github.com/upscayl/upscayl/assets/141511802/89923a1c-cf55-454f-9065-cba524ade066)

**Comment by NayamAmarshe** [comment]
Did you read the Wiki? Try the troubleshooting guide.

**Comment by MattPinPCC** [comment]
> Did you read the Wiki? Try the troubleshooting guide.

I did do everything in the general fixes and can confirm it still isn't working.

**Comment by NayamAmarshe** [comment]
The log says that the program is unable to find any GPUs at all.
It's a weird bug ngl. Sometimes reinstalling drivers via NVCleanInstall can fix the issue.

**Comment by MattPinPCC** [comment]
>I did do a clean install on my Nvdia driver before I used the program, so I'm guessing the issue has to do with my driver's or something, because Blender detects my GPU just fine.

**Comment by MattPinPCC** [comment]
I tried doing a clean install with the Nvidia Gaming and Studio Driver and it still isn't working, I get the same error with both.

**Comment by NayamAmarshe** [comment]
There's something fishy with Node.js child process spawning. Sometimes, it has graphics issues.

I really have no permanent solution because the issue is not easy to reproduce in the first place :(

**Comment by MattPinPCC** [comment]
> There's something fishy with Node.js child process spawning. Sometimes, it has graphics issues.
> 
> I really have no permanent solution because the issue is not easy to reproduce in the first place :(

Ok, thank you, it might not be a problem with the program then, it might just be windows 10 being funny... 🤔
