### ISSUE TITLE
No output displayed nor saved

### ISSUE THREAD

**Issue by laborant303** [upscayl/upscayl#409]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

<details><summary>Logs</summary><pre>

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 1
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\matte\Downloads\desktop-1600x900.jpg
🖼 Selected Image Path:  C:\Users\matte\Downloads\desktop-1600x900.jpg
📁 Selected Image Directory:  C:\Users\matte\Downloads
🖼 imagePath:  C:\Users\matte\Downloads\desktop-1600x900.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\matte\Downloads\desktop-1600x900.jpg,-o,C:\Users\matte\Downloads\desktop-1600x900_upscayl_4x_realesrgan-x4plus-anime.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-g,1,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  C:\Users\matte\Downloads\desktop-1600x900_upscayl_4x_realesrgan-x4plus-anime.png
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 1
⚙️ Getting rememberOutputFolder from localStorage false
</pre></details>

### Describe the Bug

The image does not get saved and the output in the program does not appear, also the original picture appears too small on the side by side view. Is the resulting image null?

### To Reproduce

![desktop-1600x900](https://github.com/upscayl/upscayl/assets/84988977/0192ae50-f85c-424f-ae63-1b85b46be3ca)

Upscale this image using ESRGAN or Digital Art setting. My result is the screenshot I attached in the "Screenshot" section.

### Version/Commit Hash

 upscayl-2.5.5-win.exe 

### OS Specifics

Nvidia (Asus) RTX 3060 Windows 10

### Expected Behavior

I expected an upscaled image to appear and also a copy of that image saved on my SSD.

### Screenshots

![result](https://github.com/upscayl/upscayl/assets/84988977/00e3b430-d9ee-41a0-887f-0f7424033595)

**Comment by aaronliu0130** [comment]
There isn't any output in your downloads folder either?

**Comment by madman4589** [comment]
No output whatsoever in any folder, not even in "Downloads"

**Comment by David93GitHub** [comment]
I have the same problem. I reinstalled win10, and then reinstall upscayl, and the problem appears.

**Comment by aaronliu0130** [comment]
@David93GitHub make sure you've tried [setting your GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id) and have a discrete GPU

**Comment by NayamAmarshe** [comment]
This is most likely an electron bug or something. I was having the same issue but I made some changes and it's not happening anymore.
I hope the fix works for you in v2.6

**Comment by David93GitHub** [comment]
> @David93GitHub make sure you've tried [setting your GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id) and have a discrete GPU

The only gpu I have is the UHD770 integrated in the i712700. I have set the gpu id to 0 1 2 3 repectively, and it doesn't work. The software was always working well before I reinstall win10. I don't know the why it doesn't work in the newly installed system

**Comment by laborant303** [comment]
I did set the GPU ID as well.
I will check the new version to see if anything changed. Let me know when it gets released.
Thank you

**Comment by laborant303** [comment]
I accidentally closed this issue, I reopened it...

**Comment by LifeHackerGTD** [comment]
> @David93GitHub make sure you've tried [setting your GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id) and have a discrete GPU确保您已尝试设置 GPU ID 并拥有独立 GPU

我也遇到的同样的问题

**Comment by LifeHackerGTD** [comment]
<img width="718" alt="image" src="https://github.com/upscayl/upscayl/assets/131576033/f6a75b53-5d63-47bb-9097-286dfd700e4f">

**Comment by aaronliu0130** [comment]
Tracking in #339 for now.

**Comment by David93GitHub** [comment]
> I accidentally closed this issue, I reopened it...
I solved the problem yestoday. In oder to play some games, I used the Directx repair  to complete some dynamic library files, after that, I found that upscayl also works. You can have a try
