### ISSUE TITLE
Passthrough is not supported, GL is disabled, ANGLE is

### ISSUE THREAD

**Issue by davidhhh123** [upscayl/upscayl#41]
Passthrough is not supported, GL is disabled, ANGLE is

**Comment by NayamAmarshe** [comment]
Please post proper description.

**Comment by davidhhh123** [comment]
![to_upscale_upscayled_4x](https://user-images.githubusercontent.com/73849221/187072967-5897c463-a964-4a00-8648-102e39da61ef.jpeg)
![Без имени](https://user-images.githubusercontent.com/73849221/187072969-0b001d7e-a975-43e9-b553-6488295d332e.png)

**Comment by davidhhh123** [comment]
I run the application and as a result black output

**Comment by NayamAmarshe** [comment]
> I run the application and as a result black output

I already said. iGPUs are not supported. You need a discrete graphics card.
