### ISSUE TITLE
Can you make version for M1 devices which is arm64

### ISSUE THREAD

**Issue by Mikasa-san** [upscayl/upscayl#410]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Can you make version for M1 devices which is arm64

### Related Problem(s)

There is no problem here

**Comment by aaronliu0130** [comment]
Also duplicate of #333
> I have checked that this issue isn't addressed in any other issue or pull request.

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
