### ISSUE TITLE
Add input box to manually specify image scale

### ISSUE THREAD

**Issue by sujyQ** [upscayl/upscayl#412]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Hi, Thanks for awesome work.

I'd like to do x8 SR with x8 SR model, but it seems only x2, x3, x4 are supported.
What can i do? or is there any plans to support x8?

### Related Problem(s)

I loaded x8 model with x4 image scale option but output broken :(

![image](https://github.com/upscayl/upscayl/assets/82137849/2828293a-7e1d-46d4-a622-c0e88c540133)
![0311_upscayl_4x_ESRGAN_32](https://github.com/upscayl/upscayl/assets/82137849/1b464b3e-da64-4543-9003-93d29f40db40)

**Comment by NayamAmarshe** [comment]
I don't think Real-ESRGAN program supports 8 as the scale argument.

**Comment by sujyQ** [comment]
Oh i can train the network with x4 pretrained one, and actually there were
x8 esrgan model at your model database.

2023년 8월 11일 (금) 오후 5:04, NayamAmarshe ***@***.***>님이 작성:

**Comment by aaronliu0130** [comment]
The model database isn't ours. It does show a couple ESRGAN 8x models though. Maybe we could add an input text box alongside the slider?

**Comment by sujyQ** [comment]
Yeah that would be nice. I'd appreciate it if you did!!

2023년 8월 13일 (일) 오전 12:11, Aaron Liu ***@***.***>님이 작성:

**Comment by NayamAmarshe** [comment]
> The model database isn't ours. It does show a couple ESRGAN 8x models though. Maybe we could add an input text box alongside the slider?

It's not about the input box. The Real-ESRGAN binary doesn't support arbitrary scale factors.

**Comment by aaronliu0130** [comment]
Huh, it appears I've misunderstood the scale factor documentation

**Comment by sujyQ** [comment]
Can't it automatically calculate the scale factor? Honestly, for x2 SR, the procedure including choosing x2 model, clicking Setting tab, and select x2 scale factor is little bit complicated for the newbies. Getting less user input would make less mistakes to use awesome Upscayl.

**Comment by aaronliu0130** [comment]
The thing is we don't have a consistent way of determining that yet.

**Comment by NayamAmarshe** [comment]
This issue has been fixed in 2.7.5

**Comment by sujyQ** [comment]
Thanks. I'll wait for 2.7.5 :)
