### ISSUE TITLE
Can't figure out how to set my GPU ID

### ISSUE THREAD

**Issue by LifeHackerGTD** [upscayl/upscayl#413]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🎯 GET_MODELS_LIST:  
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/png","filePath":"D:\\桌面\\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54.png","extension":"png"}
🖼 Setting image path:  D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54.png
🗂 Setting output path:  D:\桌面
🖼 imagePath:  D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54.png
🔤 Extension:  png
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 0,1,2
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54.png,-o,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,D:\应用程序\Upscayl\resources\models,-n,realesrgan-x4plus,-g,0,1,2,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54.png,-o,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,D:\应用程序\Upscayl\resources\models,-n,realesrgan-x4plus,-g,0,1,2,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54.png,-o,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,D:\应用程序\Upscayl\resources\models,-n,realesrgan-x4plus,-g,0,1,2,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54.png,-o,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,D:\应用程序\Upscayl\resources\models,-n,realesrgan-x4plus,-g,0,1,2,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54.png,-o,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,D:\应用程序\Upscayl\resources\models,-n,realesrgan-x4plus,-g,0,1,2,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54.png,-o,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,D:\应用程序\Upscayl\resources\models,-n,realesrgan-x4plus,-g,0,1,2,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54.png,-o,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,D:\应用程序\Upscayl\resources\models,-n,realesrgan-x4plus,-g,0,1,2,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_4x_realesrgan-x4plus.png
🔄 Resetting Upscaled Image Path
🏁 DOUBLE_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54.png,-o,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_16x_realesrgan-x4plus.png,-s,4,-m,D:\应用程序\Upscayl\resources\models,-n,realesrgan-x4plus,-g,0,1,2,-f,png
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_16x_realesrgan-x4plus.png,-o,D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_16x_realesrgan-x4plus.png,-s,4,-m,D:\应用程序\Upscayl\resources\models,-n,realesrgan-x4plus,-g,0,1,2,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
💯 DOUBLE_UPSCAYL_DONE:  D:\桌面\amorphousblue_Interaction_between_autistic_children_and_a_littl_14626fba-750d-408b-8461-540801222c54_upscayl_16x_realesrgan-x4plus.png
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 0,1,2
⚙️ Getting rememberOutputFolder from localStorage false
🐞 BACKEND REPORTED:  🚫 Select Custom Models Folder Operation Cancelled

### Describe the Bug

My original problem is that the picture cannot be displayed, but I need to add the GPU ID in the FAQ. I haven't been able to find the ID in the logs, so looking for help.I have tried it before and it worked, but after reinstalling the system, this problem occurred.

### To Reproduce

<img width="938" alt="image" src="https://github.com/upscayl/upscayl/assets/131576033/f4d6909f-e6d5-4981-93f1-00cb21f042e4">

### Version/Commit Hash

win 2.55

### OS Specifics

12th Gen Intel(R) Core(TM) i5-12500H   2.50 GHz

### Screenshots

<img width="938" alt="image" src="https://github.com/upscayl/upscayl/assets/131576033/ab385674-4a49-40f6-8653-ba7ce679d78f">

**Comment by aaronliu0130** [comment]
> Yes, unfortunately. NCNN Vulkan requires a Vulkan compatible GPU. Upscayl won't work with most iGPUs or CPUs. 

> I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).

![compulsory rickrolls are issued for duplicates of issues and the FAQ and normies who use intel](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
