### ISSUE TITLE
Windows progress bar in taskbar doesn't reset when Upscayling stopped

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#416]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

<details><summary>Logs</summary><pre>

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Fast Real-ESRGAN)","value":"RealESRGAN_General_x4_v3"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🎯 GET_MODELS_LIST:  C:\Users\aaron\Git\custom-models\models
🔄 Resetting image paths
🔀 Setting model to RealESRGAN_General_x4_v3
🐞 BACKEND REPORTED:  📁 Custom Models Folder Path:  C:\Users\aaron\Git\custom-models\models
🐞 BACKEND REPORTED:  🔎 Detected Custom Models:  realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,ultrasharp-2.0.1
📜 CUSTOM_MODEL_FILES_LIST:  realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,ultrasharp-2.0.1
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\aaron\Downloads\IMG_2310.jpg
🖼 Selected Image Path:  C:\Users\aaron\Downloads\IMG_2310.jpg
📁 Selected Image Directory:  C:\Users\aaron\Downloads
🖼 imagePath:  C:\Users\aaron\Downloads\IMG_2310.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\aaron\Downloads\IMG_2310.jpg,-o,C:\Users\aaron\Downloads\IMG_2310_upscayl_4x_RealESRGAN_General_x4_v3.png,-s,4,-m,C:\Users\aaron\Git\custom-models\models,-n,RealESRGAN_General_x4_v3,,,-f,png
🐞 BACKEND REPORTED:  image upscayl:  [0 Radeon RX 580 Series]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 Radeon RX 580 Series]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon RX 580 Series]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 Radeon RX 580 Series]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 Radeon RX 580 Series]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 Radeon RX 580 Series]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon RX 580 Series]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 Radeon RX 580 Series]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🐞 BACKEND REPORTED:  image upscayl:  0.30%

🚧 UPSCAYL_PROGRESS:  0.30%

🐞 BACKEND REPORTED:  image upscayl:  0.60%

🚧 UPSCAYL_PROGRESS:  0.60%

🐞 BACKEND REPORTED:  image upscayl:  0.89%

🚧 UPSCAYL_PROGRESS:  0.89%

🐞 BACKEND REPORTED:  image upscayl:  1.19%

🚧 UPSCAYL_PROGRESS:  1.19%

🐞 BACKEND REPORTED:  image upscayl:  1.49%

🚧 UPSCAYL_PROGRESS:  1.49%

🐞 BACKEND REPORTED:  image upscayl:  1.79%

🚧 UPSCAYL_PROGRESS:  1.79%

🐞 BACKEND REPORTED:  image upscayl:  2.08%

🚧 UPSCAYL_PROGRESS:  2.08%

🐞 BACKEND REPORTED:  image upscayl:  2.38%

🚧 UPSCAYL_PROGRESS:  2.38%

🐞 BACKEND REPORTED:  image upscayl:  2.68%

🚧 UPSCAYL_PROGRESS:  2.68%

🐞 BACKEND REPORTED:  image upscayl:  2.98%

🚧 UPSCAYL_PROGRESS:  2.98%

🐞 BACKEND REPORTED:  image upscayl:  3.27%

🚧 UPSCAYL_PROGRESS:  3.27%

🐞 BACKEND REPORTED:  image upscayl:  3.57%

🚧 UPSCAYL_PROGRESS:  3.57%

🐞 BACKEND REPORTED:  image upscayl:  3.87%

🚧 UPSCAYL_PROGRESS:  3.87%

🐞 BACKEND REPORTED:  image upscayl:  4.17%

🚧 UPSCAYL_PROGRESS:  4.17%

🐞 BACKEND REPORTED:  image upscayl:  4.46%

🚧 UPSCAYL_PROGRESS:  4.46%

🐞 BACKEND REPORTED:  image upscayl:  4.76%

🚧 UPSCAYL_PROGRESS:  4.76%

🐞 BACKEND REPORTED:  image upscayl:  5.06%

🚧 UPSCAYL_PROGRESS:  5.06%

🐞 BACKEND REPORTED:  image upscayl:  5.36%

🚧 UPSCAYL_PROGRESS:  5.36%

🐞 BACKEND REPORTED:  image upscayl:  5.65%

🚧 UPSCAYL_PROGRESS:  5.65%

🐞 BACKEND REPORTED:  image upscayl:  5.95%

🚧 UPSCAYL_PROGRESS:  5.95%

🐞 BACKEND REPORTED:  image upscayl:  6.25%

🚧 UPSCAYL_PROGRESS:  6.25%

🐞 BACKEND REPORTED:  image upscayl:  6.55%

🚧 UPSCAYL_PROGRESS:  6.55%

🐞 BACKEND REPORTED:  image upscayl:  6.85%

🚧 UPSCAYL_PROGRESS:  6.85%

🐞 BACKEND REPORTED:  image upscayl:  7.14%

🚧 UPSCAYL_PROGRESS:  7.14%

🐞 BACKEND REPORTED:  image upscayl:  7.44%

🚧 UPSCAYL_PROGRESS:  7.44%

🐞 BACKEND REPORTED:  image upscayl:  7.74%

🚧 UPSCAYL_PROGRESS:  7.74%

🐞 BACKEND REPORTED:  image upscayl:  8.04%

🚧 UPSCAYL_PROGRESS:  8.04%

🐞 BACKEND REPORTED:  image upscayl:  8.33%

🚧 UPSCAYL_PROGRESS:  8.33%

🐞 BACKEND REPORTED:  image upscayl:  8.63%

🚧 UPSCAYL_PROGRESS:  8.63%

🐞 BACKEND REPORTED:  image upscayl:  8.93%

🚧 UPSCAYL_PROGRESS:  8.93%

🐞 BACKEND REPORTED:  image upscayl:  9.23%

🚧 UPSCAYL_PROGRESS:  9.23%

🐞 BACKEND REPORTED:  image upscayl:  9.52%

🚧 UPSCAYL_PROGRESS:  9.52%

🐞 BACKEND REPORTED:  image upscayl:  9.82%

🚧 UPSCAYL_PROGRESS:  9.82%

🐞 BACKEND REPORTED:  image upscayl:  10.12%

🚧 UPSCAYL_PROGRESS:  10.12%

🐞 BACKEND REPORTED:  image upscayl:  10.42%

🚧 UPSCAYL_PROGRESS:  10.42%

🐞 BACKEND REPORTED:  image upscayl:  10.71%

🚧 UPSCAYL_PROGRESS:  10.71%

🐞 BACKEND REPORTED:  image upscayl:  11.01%

🚧 UPSCAYL_PROGRESS:  11.01%

🐞 BACKEND REPORTED:  image upscayl:  11.31%

🚧 UPSCAYL_PROGRESS:  11.31%

🐞 BACKEND REPORTED:  image upscayl:  11.61%

🚧 UPSCAYL_PROGRESS:  11.61%

🐞 BACKEND REPORTED:  image upscayl:  11.90%

🚧 UPSCAYL_PROGRESS:  11.90%

🐞 BACKEND REPORTED:  image upscayl:  12.20%

🚧 UPSCAYL_PROGRESS:  12.20%

🐞 BACKEND REPORTED:  image upscayl:  12.50%

🚧 UPSCAYL_PROGRESS:  12.50%

🐞 BACKEND REPORTED:  image upscayl:  12.80%

🚧 UPSCAYL_PROGRESS:  12.80%

🐞 BACKEND REPORTED:  image upscayl:  13.10%

🚧 UPSCAYL_PROGRESS:  13.10%

🐞 BACKEND REPORTED:  image upscayl:  13.39%

🚧 UPSCAYL_PROGRESS:  13.39%

🐞 BACKEND REPORTED:  image upscayl:  13.69%

🚧 UPSCAYL_PROGRESS:  13.69%

🐞 BACKEND REPORTED:  image upscayl:  13.99%

🚧 UPSCAYL_PROGRESS:  13.99%

🐞 BACKEND REPORTED:  image upscayl:  14.29%

🚧 UPSCAYL_PROGRESS:  14.29%

🐞 BACKEND REPORTED:  image upscayl:  14.58%

🚧 UPSCAYL_PROGRESS:  14.58%

🐞 BACKEND REPORTED:  image upscayl:  14.88%

🚧 UPSCAYL_PROGRESS:  14.88%

🐞 BACKEND REPORTED:  image upscayl:  15.18%

🚧 UPSCAYL_PROGRESS:  15.18%

🐞 BACKEND REPORTED:  image upscayl:  15.48%

🚧 UPSCAYL_PROGRESS:  15.48%

🐞 BACKEND REPORTED:  image upscayl:  15.77%

🚧 UPSCAYL_PROGRESS:  15.77%

🐞 BACKEND REPORTED:  image upscayl:  16.07%

🚧 UPSCAYL_PROGRESS:  16.07%

🐞 BACKEND REPORTED:  image upscayl:  16.37%

🚧 UPSCAYL_PROGRESS:  16.37%

🐞 BACKEND REPORTED:  image upscayl:  16.67%

🚧 UPSCAYL_PROGRESS:  16.67%

🐞 BACKEND REPORTED:  image upscayl:  16.96%

🚧 UPSCAYL_PROGRESS:  16.96%

🐞 BACKEND REPORTED:  image upscayl:  17.26%

🚧 UPSCAYL_PROGRESS:  17.26%

🐞 BACKEND REPORTED:  image upscayl:  17.56%

🚧 UPSCAYL_PROGRESS:  17.56%

🐞 BACKEND REPORTED:  image upscayl:  17.86%

🚧 UPSCAYL_PROGRESS:  17.86%

🐞 BACKEND REPORTED:  image upscayl:  18.15%

🚧 UPSCAYL_PROGRESS:  18.15%

🐞 BACKEND REPORTED:  image upscayl:  18.45%

🚧 UPSCAYL_PROGRESS:  18.45%

🐞 BACKEND REPORTED:  image upscayl:  18.75%

🚧 UPSCAYL_PROGRESS:  18.75%

🐞 BACKEND REPORTED:  image upscayl:  19.05%

🚧 UPSCAYL_PROGRESS:  19.05%

🐞 BACKEND REPORTED:  image upscayl:  19.35%

🚧 UPSCAYL_PROGRESS:  19.35%

🐞 BACKEND REPORTED:  image upscayl:  19.64%

🚧 UPSCAYL_PROGRESS:  19.64%

🐞 BACKEND REPORTED:  image upscayl:  19.94%

🚧 UPSCAYL_PROGRESS:  19.94%

🐞 BACKEND REPORTED:  image upscayl:  20.24%

🚧 UPSCAYL_PROGRESS:  20.24%

🐞 BACKEND REPORTED:  image upscayl:  20.54%

🚧 UPSCAYL_PROGRESS:  20.54%

🐞 BACKEND REPORTED:  image upscayl:  20.83%

🚧 UPSCAYL_PROGRESS:  20.83%

🐞 BACKEND REPORTED:  image upscayl:  21.13%

🚧 UPSCAYL_PROGRESS:  21.13%

🐞 BACKEND REPORTED:  image upscayl:  21.43%

🚧 UPSCAYL_PROGRESS:  21.43%

🐞 BACKEND REPORTED:  image upscayl:  21.73%

🚧 UPSCAYL_PROGRESS:  21.73%

🐞 BACKEND REPORTED:  image upscayl:  22.02%

🚧 UPSCAYL_PROGRESS:  22.02%

🐞 BACKEND REPORTED:  image upscayl:  22.32%

🚧 UPSCAYL_PROGRESS:  22.32%

🐞 BACKEND REPORTED:  image upscayl:  22.62%

🚧 UPSCAYL_PROGRESS:  22.62%

🐞 BACKEND REPORTED:  image upscayl:  22.92%

🚧 UPSCAYL_PROGRESS:  22.92%

🐞 BACKEND REPORTED:  image upscayl:  23.21%

🚧 UPSCAYL_PROGRESS:  23.21%

🐞 BACKEND REPORTED:  image upscayl:  23.51%

🚧 UPSCAYL_PROGRESS:  23.51%

🐞 BACKEND REPORTED:  image upscayl:  23.81%

🚧 UPSCAYL_PROGRESS:  23.81%

🐞 BACKEND REPORTED:  image upscayl:  24.11%

🚧 UPSCAYL_PROGRESS:  24.11%

🐞 BACKEND REPORTED:  image upscayl:  24.40%

🚧 UPSCAYL_PROGRESS:  24.40%

🐞 BACKEND REPORTED:  image upscayl:  24.70%

🚧 UPSCAYL_PROGRESS:  24.70%

🐞 BACKEND REPORTED:  image upscayl:  25.00%

🚧 UPSCAYL_PROGRESS:  25.00%

🐞 BACKEND REPORTED:  image upscayl:  25.30%

🚧 UPSCAYL_PROGRESS:  25.30%

🐞 BACKEND REPORTED:  image upscayl:  25.60%

🚧 UPSCAYL_PROGRESS:  25.60%

🐞 BACKEND REPORTED:  image upscayl:  25.89%

🚧 UPSCAYL_PROGRESS:  25.89%

🐞 BACKEND REPORTED:  image upscayl:  26.19%

🚧 UPSCAYL_PROGRESS:  26.19%

🐞 BACKEND REPORTED:  image upscayl:  26.49%

🚧 UPSCAYL_PROGRESS:  26.49%

🐞 BACKEND REPORTED:  image upscayl:  26.79%

🚧 UPSCAYL_PROGRESS:  26.79%

🛑 Stopping Upscayl
🔄 Resetting image paths
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🛑 Stopping Upscaling Process 26656
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Fast Real-ESRGAN)","value":"RealESRGAN_General_x4_v3"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
</pre></details>

### Describe the Bug

The progress bar displayed in the taskbar doesn't reset after stopping the Upscayl process. I'm pretty sure it stops instead of pausing as the image is also reset after you press STOP and the progress starts as 0 again when you re-select it.

### To Reproduce

1. Upscayl an image
2. wait no stop that
3. See progress bar still at where it stopped

### Version/Commit Hash

2.5.5

### OS Specifics

Windows 11 22H2 25926.1000 with AMD Radeon RX 580

### Expected Behavior

The progress bar resets to a normal bar after pressing stop.

### Screenshots
![normal](https://github.com/upscayl/upscayl/assets/11874211/537af099-4baa-4888-9d46-5c0c8f626a8e)
![with progress bar](https://github.com/upscayl/upscayl/assets/11874211/bcc2d163-69e8-49cc-a4ae-17f3f6e15562)

**Comment by NayamAmarshe** [comment]
Thanks for reporting. I'll fix it.
