### ISSUE TITLE
开始之后软件并没有运行就结束了任务

### ISSUE THREAD

**Issue by shanyingji** [upscayl/upscayl#417]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🎯 GET_MODELS_LIST:  
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  D:\01AI图库\20230811奥本海默\图虫
🖼 Selected Folder Path:  D:\01AI图库\20230811奥本海默\图虫
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\01AI图库\20230811奥本海默\图虫,-o,D:\01AI图库\20230811奥本海默\图虫_upscayled,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,,-f,jpg
🐞 BACKEND REPORTED:  💯 Done upscaling
💯 FOLDER_UPSCAYL_DONE:  D:\01AI图库\20230811奥本海默\图虫_upscayled
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\01AI图库\20230811奥本海默\图虫,-o,D:\01AI图库\20230811奥本海默\图虫_upscayled,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,,-f,jpg
🐞 BACKEND REPORTED:  💯 Done upscaling
💯 FOLDER_UPSCAYL_DONE:  D:\01AI图库\20230811奥本海默\图虫_upscayled
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🚫 Select Folder Operation Cancelled
🚫 Folder selection cancelled
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  D:\01AI图库\20230811奥本海默\视觉中国
🖼 Selected Folder Path:  D:\01AI图库\20230811奥本海默\视觉中国
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\01AI图库\20230811奥本海默\视觉中国,-o,D:\01AI图库\20230811奥本海默\视觉中国_upscayled,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,,-f,jpg
🐞 BACKEND REPORTED:  💯 Done upscaling
💯 FOLDER_UPSCAYL_DONE:  D:\01AI图库\20230811奥本海默\视觉中国_upscayled
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  D:\01AI图库\20230811奥本海默\视觉中国
🖼 Selected Folder Path:  D:\01AI图库\20230811奥本海默\视觉中国
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\01AI图库\20230811奥本海默\视觉中国,-o,D:\01AI图库\20230811奥本海默\视觉中国_upscayled,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,,-f,jpg
🐞 BACKEND REPORTED:  💯 Done upscaling
💯 FOLDER_UPSCAYL_DONE:  D:\01AI图库\20230811奥本海默\视觉中国_upscayled
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false

### Describe the Bug

重装过系统之后，upscy就无法正常运行，选择需要增强的图片文件夹运行程序，只是创建了新的增强文件夹，但是软件并无任何的增强动作

### To Reproduce

打开程序
点击选择需要增强的文件夹
点击开始

### Version/Commit Hash

2.5.5

### OS Specifics

win11家庭版 4050显卡

**Comment by shanyingji** [comment]
之前使用一直都是没有问题的，重装过系统之后就不能够正常使用了，系统是官方版本，感觉像是显卡无法被识别调动

**Comment by shanyingji** [comment]
已解决。去官网下载最新驱动之后正常

**Comment by NayamAmarshe** [comment]
Translation: 
Solved. After going to the official website to download the latest driver, it is normal
