### ISSUE TITLE
Web UI for upscayl

### ISSUE THREAD

**Issue by Sloth-on-meth** [upscayl/upscayl#419]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Add a webUI for upscayl so i can host it on my server with dedicated GPU

**Comment by aaronliu0130** [comment]
See #178 . We use electron specific functions to leverage the GPU so this isn't possible without a rewrite at the moment.
