### ISSUE TITLE
Face Enhance

### ISSUE THREAD

**Issue by manjus3** [upscayl/upscayl#420]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Hi, thanks for this excellent GUI app. Will you be adding the face enhance feature anytime in the near future?

Thanks,
Manju

**Comment by NayamAmarshe** [comment]
Yes, soon :)

**Comment by manjus3** [comment]
> 

OK, thanks. Looking forward to the feature!

**Comment by aaronliu0130** [comment]
(I'll assume this reopens #246)

**Comment by NayamAmarshe** [comment]
> (I'll assume this reopens #246)

We won't be introducing face enhance in Upscayl desktop (because that's not possible right now) but Upscayl Cloud will have that functionality for sure.

**Comment by aaronliu0130** [comment]
Doesn't https://github.com/sczhou/CodeFormer/releases have PyTorch Real-ESRGAN models?

**Comment by NayamAmarshe** [comment]
> Doesn't https://github.com/sczhou/CodeFormer/releases have PyTorch Real-ESRGAN models?

I can give it a try

**Comment by aaronliu0130** [comment]
Last time I checked, these were PyTorch CodeFormer models, not ESRGAN models, so.....
