### ISSUE TITLE
problem when opening two applications in parallel

### ISSUE THREAD

**Issue by haidautuiosif** [upscayl/upscayl#421]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

<details><summary>Logs</summary><pre>

</pre></details>

### Describe the Bug

I uploaded two folders with images to enlarge, but I uploaded one then the other. the first time it converted them both, then after they were finished I went to two other folders, but from the first folder it converted almost all of them, and turned some of them into black images, and in the second file, it converted some good, and the rest turned into black images

### To Reproduce

for reproduction, try to convert two image folders of approximately 1500-2500 images, and then reload two more as soon as it is finished (the next and the next, i.e. a total of 4 image files) . 
then it shows me the very common error: ENCODING ERROR 

### Version/Commit Hash

2.5.5

### OS Specifics

windows 11 , video card rtx 3050 ti

### Expected Behavior

to turn all my images into good images, not black

### Screenshots

![bandicam 2023-08-20 21-00-16-879](https://github.com/upscayl/upscayl/assets/140640441/f9debf90-c4ec-47ee-adaf-b58f0c67d8d7)
![bandicam 2023-08-20 21-00-28-163](https://github.com/upscayl/upscayl/assets/140640441/2b504e55-ebe6-43a1-913f-5ce7c629d195)

**Comment by haidautuiosif** [comment]
I applied the recommendation given to me here :  https://github.com/upscayl/upscayl/issues/402

**Comment by aaronliu0130** [comment]
I'm sorry but I don't really get your problem description. What is "reload two more"? Is the "first folder" the first folder or the third folder? Which folders did you run in parallel and which ones did one run in the same instance?

**Comment by haidautuiosif** [comment]
it is about 4 folders with images that are upscaled. They were upscaled in two windows of the program, first the first two, and then in turn to the other two folders (for example, after finishing folder 1, I started 3, and after finishing folder 2, I started 4)

**Comment by haidautuiosif** [comment]
the program will run for a while until it gives the error, more precisely on folder 3 and 4.

**Comment by haidautuiosif** [comment]
the idea is for the PC to be requested more in the application

**Comment by aaronliu0130** [comment]
Alright. Can you send the last lines of the logs for when it gives the error?

**Comment by NayamAmarshe** [comment]
It's possible that Vulkan can't be used by both the processes at the same time.
