### ISSUE TITLE
Why can't I use the computer after changing it

### ISSUE THREAD

**Issue by f231541** [upscayl/upscayl#422]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

换了个电脑就不能用了   家人们 谁能教教我  公司的电脑怎么这样啊

### Screenshots

![的 的](https://github.com/upscayl/upscayl/assets/142781793/be750ab2-10ab-4224-8ca7-2a5265bd35df)

**Comment by f231541** [comment]
After changing the computer, I couldn't use it successfully

**Comment by f231541** [comment]
why？？？？？

**Comment by NayamAmarshe** [comment]
Post the logs please.

**Comment by f231541** [comment]
> 请发布日志。

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 0,1,2
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  E:\用户\user\Desktop\处理过的照片\英雄联盟\wbg.png
🖼 Selected Image Path:  E:\用户\user\Desktop\处理过的照片\英雄联盟\wbg.png
📁 Selected Image Directory:  E:\用户\user\Desktop\处理过的照片\英雄联盟
🖼 imagePath:  E:\用户\user\Desktop\处理过的照片\英雄联盟\wbg.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,E:\用户\user\Desktop\处理过的照片\英雄联盟\wbg.png,-o,E:\用户\user\Desktop\处理过的照片\英雄联盟\wbg_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,D:\图片处理软件\图片\resources\models,-n,realesrgan-x4plus,-g,0,1,2,-f,png
🐞 BACKEND REPORTED:  image upscayl:  vkCreateInstance failed -9

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🔄 Resetting image paths
🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
🐞 BACKEND REPORTED:  image upscayl:  vkCreateInstance failed -9
invalid gpu device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9
invalid gpu device

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 0,1,2
⚙️ Getting rememberOutputFolder from localStorage true

**Comment by aaronliu0130** [comment]
请用合适的template发表issue
你用的是啥显卡

**Comment by f231541** [comment]
> 请用合适的模板发表问题 你用的是啥显卡

graphics  4600

**Comment by aaronliu0130** [comment]
AMD?
你试图 upscayl 一个路径里没有中文的文件了吗？
你试图把 GPU ID 设成0，1和2了吗？
你在试图设 GPU ID 的时候打开[高性能模式](https://www.youtube.com/watch?v=sxvs6qYHJmc)了吗？

**Comment by yummeshugr** [comment]
hey i've had this before, you may want to update your drivers on your GPU , thats how i fixed it
