### ISSUE TITLE
Result Error

### ISSUE THREAD

**Issue by NoelNoel12** [upscayl/upscayl#424]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

All besides the result are normal. I don't know why, but the result become tile(s)

### Screenshots

![Screenshot 2023-08-24 110716](https://github.com/upscayl/upscayl/assets/138089805/d1b98c68-1dbc-495a-b7cd-1515ca8f85ab)

**Comment by NayamAmarshe** [comment]
Please read the wiki and search for existing issues before creating a new one.

Thanks.

**Comment by aaronliu0130** [comment]
Duplicate of #303 
> I have checked that this issue isn't addressed in any other issue or pull request.

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
