### ISSUE TITLE
The icon of the appimage version is wrong

### ISSUE THREAD

**Issue by hghgthifg** [upscayl/upscayl#425]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

<details><summary>Logs</summary><pre>

</pre></details>

### Describe the Bug

The icon is wrong.

### To Reproduce

Just use AppimageLauncher to add the icon to the Application Launcher

### Version/Commit Hash

2.5.5

### OS Specifics

Deepin 20.9

### Expected Behavior

Show the icon of upscayl

### Screenshots

![图片](https://github.com/upscayl/upscayl/assets/61531662/bcf2076c-eced-489a-a4f3-181eb19af0fa)

**Comment by NayamAmarshe** [comment]
That's pretty strange. It's fine for me. Maybe something is wrong with your icon cache?

**Comment by hghgthifg** [comment]
> That's pretty strange. It's fine for me. Maybe something is wrong with your icon cache?

Today the icon has gone missing, but other applications are normal.

![图片](https://github.com/upscayl/upscayl/assets/61531662/a8203edb-ad2a-4f8a-962a-9fab9e1fb43d)

![图片](https://github.com/upscayl/upscayl/assets/61531662/cb5b4df1-ea3d-416d-a389-07f01b004c1d)

**Comment by aaronliu0130** [comment]
Do you think it could be related to one of your system upgrades?

**Comment by hghgthifg** [comment]
> Do you think it could be related to one of your system upgrades?

I have not updated my system these days. Yesterday I added another appimage application, and it's icon was successfully displayed.
