### ISSUE TITLE
Self trained models

### ISSUE THREAD

**Issue by Phhofm** [upscayl/upscayl#427]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Thank you for your work with upscayl :)

This is not per se a request, I simply wanted to provide some of my self trained models that can be used with upscayl (since I saw some requesting more models in the github issues, i thought maybe this could be interesting for those wanting to try more models. If not, im sorry, and this github issue can simply be deleted). I tested these 4 models with upscaly on Ubuntu (AppImage file) (i had simply followed the [upscaly model conversion guide](https://github.com/upscayl/upscayl/wiki/%F0%9F%96%A5%EF%B8%8F-Model-Conversion-%E2%80%90-Create-more-AI-models!) for this, it worked great):

[Download Link Recommended Models Zip File](https://drive.google.com/file/d/1-UxKi76jvziWj6bpFRZRcaeGt2OvZRGJ/view?usp=sharing)

To use my models, simply extract the 'models' folder, and then select it in upscayl settings in the ADD CUSTOM MODELS section. Then you should see all of them selectable in upscayl.

Models (with imgsli examples to see the results):
4xNomos8kSC (general) [Example1](https://imgsli.com/MjAwNzEx),  [Example2](https://imgsli.com/MjAwNzE0), [Example3](https://imgsli.com/MjAwNzE1), [Example4](https://imgsli.com/MjAwNzE2), [Example5](https://imgsli.com/MjAwNzE3)
4xLSDIRCompact3 (photos, its main point is that its fast (SRVGGNet model)) [Example](https://imgsli.com/MjAwNzIy)
4xLSDIRplus (photos, handles more degradations than 4xNomos8kSC like a little bit of noise) [Example](https://imgsli.com/MjAwNzE5)
4xLSDIR (photos, bicubic upscaler, needs good quality input) [Example1](https://imgsli.com/MjAwNzIw), [Example2](https://imgsli.com/MjAwNzIx)

There are of course lots of more esrgan models that could be converted to be used with upscayl, and also one could create interpolations of existing models, [like these](https://phhofm.github.io/upscale/interpolation.html), which can be converted to be used with upscayl. I had not shared all my self trained models on the ersgan arch (that I had prepared so they could be used with upscayl), since most of them would simply be variants or old versions of the above and will do worse in general. But if there is interest I could of course simply share all of them.

**Comment by NayamAmarshe** [comment]
Thanks a lot for this!

You can submit a PR (if you'd like) to add these models to our custom models repository too :D
