### ISSUE TITLE
Why so slow in rtx 3050 mobile 4gb

### ISSUE THREAD

**Issue by Ramam001** [upscayl/upscayl#429]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

so ive ryzen 5600h with radeon graphics and gpu with rtx 3050 4gb 
they both seems to work with same speed or nearly same
and arent even using much of the power
(yes i did checked your windows systerm ecetc, tried it on both gpu and igpu)

on Igpu it seems to consume about 60% power still being slow

and on gpu RTX 3050 it dosnt seems to be going above 20% at all cost

**Ultr sharp is really great model Keeep it**

### Related Problem(s)

try including custom models out of stable diffusion, civitai etc website, 
pls add codformers or something like that(restore faces in sd)

### Alternatives

pls make rtx support

**Comment by Ramam001** [comment]
Never mid , i accidentally used wrong gpu id

anyways keeep my suggestion of stable diffusion upscalers in mind pls. they are growing at very good pace and ulra shar is my all time favouraite upscaler

**Comment by aaronliu0130** [comment]
CodeFormer is tracked in #420 .
Currently we only use Real-ESRGAN to upscayl.
