### ISSUE TITLE
m1 has terrible results

### ISSUE THREAD

**Issue by KevinColemanInc** [upscayl/upscayl#43]
I am running this on my m1 max and none of the images look good. Even the sample landscape turns out bad. Is the issue my graphics card?

<img width="677" alt="image" src="https://user-images.githubusercontent.com/2381771/187104657-452359b6-a7df-4f46-b85e-14ebf723339a.png">

**Comment by johnblommers** [comment]
So I have an M1 Mac Mini and Upscayl 1.1.2 works pretty well. I cannot reproduce it. You have a more recent more powerful Mac. Your screenshot suggests no image processing occurred.

Attached is my M1 Mac Mini output having upscaled `to_upscale.jpeg` using the "General Photo" setting.

---

Input:
![to_upscale](https://user-images.githubusercontent.com/8484427/187108850-5a3478be-a93e-4572-bfe1-06b1337177be.jpeg)

---

Output:
![to_upscale_upscayled_4x](https://user-images.githubusercontent.com/8484427/187108884-e2e145f3-e67a-4e25-9362-6a681bdac773.jpeg)

---

Now I'm not sure what training set of images the A.I. in Upscayl has consumed but I'll wager there were a lot of nature images in that set.

**Comment by KevinColemanInc** [comment]
Interesting... For the original image, I took a screenshot (which created a png). If I run the jpg you just posted, then it works as expected.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/2381771/187109473-66096689-8736-4625-b4b3-7fd5acc0b84e.png">

**Comment by KevinColemanInc** [comment]
png
<img width="646" alt="image" src="https://user-images.githubusercontent.com/2381771/187109668-da8bfec9-e631-4fa7-aa23-66f748244f35.png">

converted png to jpg
<img width="653" alt="image" src="https://user-images.githubusercontent.com/2381771/187109727-bdcd5892-f160-41cd-9b48-49c76d0dcf90.png">


But the original file you shared looks great.

**Comment by johnblommers** [comment]
BTW  I found that `to_upscale.jpeg` image file tucked inside one of the directories in the Upscayl GitHub repository. It's the unadulterated original file not a web rendered/scaled screenshot converted to a different file format.
