### ISSUE TITLE
Commercial Issue

### ISSUE THREAD

**Issue by Malshan722** [upscayl/upscayl#442]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

Can i publish images on stock website without any commercial errors upscale through your software ?

**Comment by NayamAmarshe** [comment]
Yes, you can use Upscayl for commercial stuff if you own the copyright to the images.
