### ISSUE TITLE
 The problem is not upscaling the images

### ISSUE THREAD

**Issue by haidautuiosif** [upscayl/upscayl#443]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

<details><summary>Logs</summary><pre>

</pre></details>
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🎯 GET_MODELS_LIST:  
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\iosif\Desktop\buckledcranium
🖼 Selected Folder Path:  C:\Users\iosif\Desktop\buckledcranium
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\iosif\Desktop\buckledcranium,-o,C:\Users\iosif\Desktop\buckledcranium_upscayled_realesrgan-x4plus_x4,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,,-f,png
🚧 FOLDER_UPSCAYL_PROGRESS:  [0 Intel(R) UHD Graphics]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) UHD Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) UHD Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) UHD Graphics]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  [1 NVIDIA GeForce RTX 3050 Ti Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[1 NVIDIA GeForce RTX 3050 Ti Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 NVIDIA GeForce RTX 3050 Ti Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 NVIDIA GeForce RTX 3050 Ti Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  2,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  2,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  5,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  5,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  12,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  12,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  15,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  15,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,00%
20,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  22,50%
22,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  27,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  27,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  30,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  30,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  37,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  37,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  40,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  40,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  45,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  45,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  47,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  47,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  52,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  52,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  55,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  55,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  62,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  62,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  65,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  65,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  70,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  70,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  72,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  72,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  77,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  77,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  80,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  80,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  87,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  87,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  90,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  90,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  95,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  95,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  97,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  97,50%

🔄 Resetting image paths
🚧 FOLDER_UPSCAYL_PROGRESS:  encode image C:\Users\iosif\Desktop\buckledcranium_upscayled_realesrgan-x4plus_x4/0 A view of futuristic European city in Deus Ex, Cyberpunk, Sci-Fi, Science Fiction, Raised walkway, elevated park, Geometric Shapes, Modernist, Minimalism, Brutalist, Park, Neon Lighting, Mixed Archite.png failed

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR INVALID FILES IN FOLDER - FAILED
🔄 Resetting image paths
🚧 FOLDER_UPSCAYL_PROGRESS:  encode image C:\Users\iosif\Desktop\buckledcranium_upscayled_realesrgan-x4plus_x4/1 A view of futuristic European city in Deus Ex, Cyberpunk, Sci-Fi, Science Fiction, Raised walkway, elevated park, Geometric Shapes, Modernist, Minimalism, Brutalist, Park, Neon Lighting, Mixed Archite.png failed

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR INVALID FILES IN FOLDER - FAILED
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false

### Describe the Bug

it doesn't upscale my images in version 2.7.5 (I mention that it worked for one batch, but for the following I got the error ENCODING ERROR =>. On version 2.5.5 it works perfectly

### To Reproduce

HERE IS THE JOURNAL FOR VERSION 2.5.5

⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🎯 GET_MODELS_LIST:  
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  ✅ Update Downloaded
🐞 BACKEND REPORTED:  🚫 Update Installation Cancelled
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\iosif\Desktop\buckledcranium
🖼 Selected Folder Path:  C:\Users\iosif\Desktop\buckledcranium
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\iosif\Desktop\buckledcranium,-o,C:\Users\iosif\Desktop\buckledcranium_upscayled,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,,-f,jpg
🚧 FOLDER_UPSCAYL_PROGRESS:  [0 Intel(R) UHD Graphics]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) UHD Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) UHD Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) UHD Graphics]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  [1 NVIDIA GeForce RTX 3050 Ti Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[1 NVIDIA GeForce RTX 3050 Ti Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 NVIDIA GeForce RTX 3050 Ti Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 NVIDIA GeForce RTX 3050 Ti Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  2,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  2,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  5,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  5,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,50%

⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
🚧 FOLDER_UPSCAYL_PROGRESS:  10,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  12,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  12,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  15,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  15,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,00%
20,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  22,50%
22,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%
25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  27,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  27,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  30,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  30,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  37,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  37,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  40,00%
40,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  45,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  45,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  47,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  47,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  52,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  52,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  55,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  55,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  62,50%
62,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  65,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  65,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  70,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  70,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  72,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  72,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  77,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  77,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  80,00%
80,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  87,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  87,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  90,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  90,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  95,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  95,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  97,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  97,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  2,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  2,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  5,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  5,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  12,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  12,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  15,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  15,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  22,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  22,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  27,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  27,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  30,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  30,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  37,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  37,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  40,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  40,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  45,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  45,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  47,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  47,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  52,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  52,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  55,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  55,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  62,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  62,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  65,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  65,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  70,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  70,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  72,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  72,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  77,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  77,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  80,00%
80,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,50%
82,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  87,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  87,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  90,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  90,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  95,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  95,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  97,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  97,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  2,78%

🚧 FOLDER_UPSCAYL_PROGRESS:  2,78%

🚧 FOLDER_UPSCAYL_PROGRESS:  5,56%

🚧 FOLDER_UPSCAYL_PROGRESS:  5,56%

🚧 FOLDER_UPSCAYL_PROGRESS:  8,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  8,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  11,11%

🚧 FOLDER_UPSCAYL_PROGRESS:  11,11%

🚧 FOLDER_UPSCAYL_PROGRESS:  13,89%

🚧 FOLDER_UPSCAYL_PROGRESS:  13,89%

🚧 FOLDER_UPSCAYL_PROGRESS:  16,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  16,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  19,44%

🚧 FOLDER_UPSCAYL_PROGRESS:  19,44%

🚧 FOLDER_UPSCAYL_PROGRESS:  22,22%

🚧 FOLDER_UPSCAYL_PROGRESS:  22,22%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  27,78%

🚧 FOLDER_UPSCAYL_PROGRESS:  27,78%

🚧 FOLDER_UPSCAYL_PROGRESS:  30,56%

🚧 FOLDER_UPSCAYL_PROGRESS:  30,56%

🚧 FOLDER_UPSCAYL_PROGRESS:  33,33%
33,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  36,11%

🚧 FOLDER_UPSCAYL_PROGRESS:  36,11%

🚧 FOLDER_UPSCAYL_PROGRESS:  38,89%

🚧 FOLDER_UPSCAYL_PROGRESS:  38,89%

🚧 FOLDER_UPSCAYL_PROGRESS:  41,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  41,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  44,44%

🚧 FOLDER_UPSCAYL_PROGRESS:  44,44%

🚧 FOLDER_UPSCAYL_PROGRESS:  47,22%

🚧 FOLDER_UPSCAYL_PROGRESS:  47,22%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%
50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  52,78%

🚧 FOLDER_UPSCAYL_PROGRESS:  52,78%

🚧 FOLDER_UPSCAYL_PROGRESS:  55,56%

🚧 FOLDER_UPSCAYL_PROGRESS:  55,56%

🚧 FOLDER_UPSCAYL_PROGRESS:  58,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  58,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  61,11%

🚧 FOLDER_UPSCAYL_PROGRESS:  61,11%

🚧 FOLDER_UPSCAYL_PROGRESS:  63,89%

🚧 FOLDER_UPSCAYL_PROGRESS:  63,89%

🚧 FOLDER_UPSCAYL_PROGRESS:  66,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  66,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  69,44%

🚧 FOLDER_UPSCAYL_PROGRESS:  69,44%

🚧 FOLDER_UPSCAYL_PROGRESS:  72,22%

🚧 FOLDER_UPSCAYL_PROGRESS:  72,22%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  77,78%

### Version/Commit Hash

2.7.5

### OS Specifics

windows 11 , video card rtx 3050 ti

### Expected Behavior

TO UPSCALE MY IMAGES

**Comment by aaronliu0130** [comment]
Please refrain from shouting and opening duplicate issues.
