### ISSUE TITLE
Make how to close the Upscayl cloud popup clearer

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#444]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Add an "X" to the popup's top right corner
Also, maybe make the background fade in when closing the popup

### Related Problem(s)

![image](https://github.com/upscayl/upscayl/assets/11874211/f11e912c-70d6-4507-9b48-bef88018464c)
While some might realize that clicking anywhere else gets rid of the cloud popup, others might not yet don't want to sign up. (In my case, I already signed up and don't want to do it twice)
Also, the flashing green bar never disappears... It's annoying

### Alternatives

watch users in their desperate confusion

**Comment by NayamAmarshe** [comment]
Thank you. I do admit that it was a bit rushed. We wanted to get things out because we tend to procrastinate sometimes 😅 

I'll add a fix in v2.8, thanks!

**Comment by NayamAmarshe** [comment]
v2.8 adds a "DON'T SHOW THIS AGAIN" button.
