### ISSUE TITLE
Minor theme enhancements

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#445]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Multiple stuff:
1. Make the step two dropdown look like a dropdown
![image](https://github.com/upscayl/upscayl/assets/11874211/3e0f2483-3544-488b-ac10-4181b8434a72)
![image](https://github.com/upscayl/upscayl/assets/11874211/c086cb5e-0a22-4e17-b014-aa706af349bc)
2. Many themes have poor contrast on the empty screen
![Light](https://github.com/upscayl/upscayl/assets/11874211/ee54ffa9-bb9e-4a8f-a22a-156705f5a767)
![Corporate](https://github.com/upscayl/upscayl/assets/11874211/fed31cc2-0248-46cf-a1c2-fa26449fbb68)
![Synthwave](https://github.com/upscayl/upscayl/assets/11874211/8ae545c9-623f-4515-903e-90389f21f0e1)
![Halloween](https://github.com/upscayl/upscayl/assets/11874211/371071b9-170c-413f-bbef-81ca8b66effa)
(maybe keep the halloween theme's part of this bug as a feature? it spooky)
![Garden](https://github.com/upscayl/upscayl/assets/11874211/23473793-fd20-4279-8fa6-54f091ff1eac)
![Forest](https://github.com/upscayl/upscayl/assets/11874211/e80669c0-7773-435f-8bce-c15a9f36590d)
![Aqua](https://github.com/upscayl/upscayl/assets/11874211/786a4a6c-1ade-4eeb-a03e-a5c09edeeda5)
![how is this "lofi"](https://github.com/upscayl/upscayl/assets/11874211/d03b089a-952f-4b4a-89ff-90a21165dd29)
![Fantasy](https://github.com/upscayl/upscayl/assets/11874211/2c341ee9-551c-4d4a-9a56-0f2f2d1c6435)
![Luxury](https://github.com/upscayl/upscayl/assets/11874211/de4aff65-f6a5-4fee-9671-545add4b3886)
![Dracula](https://github.com/upscayl/upscayl/assets/11874211/a8a3c385-c963-43fe-9133-c385379f8e68)
![Autumn](https://github.com/upscayl/upscayl/assets/11874211/bb564246-b73e-4e2b-86e5-d822fe92fc03)
![Acid](https://github.com/upscayl/upscayl/assets/11874211/d426e27d-0085-4f3b-b9e7-a2bb187d5ff7)
![Lemonade (why is this green)](https://github.com/upscayl/upscayl/assets/11874211/ef944a64-dcd0-4292-bab6-833f50751f80)
![Night](https://github.com/upscayl/upscayl/assets/11874211/f563b248-ea73-4ca6-af2c-b83dbb28d034)
![Winter](https://github.com/upscayl/upscayl/assets/11874211/c839f099-2ed8-4d09-af4b-b14533ceb493)
3. Same images above: Save for Upscayl virtually all themes are unclear on the Save Image As part which extension is selected. When PNG is selected it seems like JPG is selected because JPG has the accent color.
4. add light version of Upscayl theme? If 5 isn't implemented the pastel theme seems like it'll fit the purpose
5. Get the system's accent color for the Upscayl theme's (and if we implement 4 that too's) accent color instead of always using purple
6. Center or maximize some elements?
7. Change "Select Upscayling Type" to "Select Upscayling Model"
![just a mockup](https://github.com/upscayl/upscayl/assets/11874211/169a794f-b686-4dce-ad30-7b94e4235804)
8. Increase Coffee's overall contrast
![Coffee](https://github.com/upscayl/upscayl/assets/11874211/e9d61b60-1f93-4a17-892c-1c541922498d)

### Related Problem(s)

See above

### Alternatives

everything is fine, this doesn't need to be implemented

**Comment by NayamAmarshe** [comment]
Thank you. I'll implement these suggestions.

**Comment by aaronliu0130** [comment]
I'll just go ahead with dependabot then.

**Comment by aaronliu0130** [comment]
From what I can see only points 2 and 7 were implemented?

**Comment by NayamAmarshe** [comment]
Oh yeah, sorry.

- 6 looks weird imo. Text and content must always be aligned and here, left alignment looks great.
- 8, that's DaisyUI's default coffee theme. So I suppose it'd be better to let them know about it.
- 5, this is very difficult. There's no standard way to do this, on all operating systems.
- 4 is for later :)

I've fixed the rest :)

**Comment by aaronliu0130** [comment]
Well, I think the model selection dropdown should be made as big as the theme selection dropdown at least

**Comment by NayamAmarshe** [comment]
> Well, I think the model selection dropdown should be made as big as the theme selection dropdown at least

I didn't do it to keep design consistency in that column.

**Comment by aaronliu0130** [comment]
Well, IMO actual consistency would be to make every UI element look like the corresponding element in the theme; having a dropdown look like a button is inconsistency. Not to mention you already have an accented button, a toggle and a checkbox in that column.

**Comment by NayamAmarshe** [comment]
> Well, IMO actual consistency would be to make every UI element look like the corresponding element in the theme; having a dropdown look like a button is inconsistency. Not to mention you already have an accented button, a toggle and a checkbox in that column.

The issue is that it's not necessarily a select menu like others. It's a custom component that also acts like an input field.

**Comment by aaronliu0130** [comment]
But the UI of it acts like a dropdown. Correct me if I'm wrong, but isn't all it takes is change the class name to `select-primary select`?

**Comment by aaronliu0130** [comment]
I accidently committed 62dd93b while trying to start a pull request...
I think the problem with 3 is the hacky way the selector is made to fit the upscayl theme. In that theme the primary color is a lighter shade of grey, though in other themes it's less background-y. So the button was accented, and both buttons were made primary (which I don't get).
![image](https://github.com/upscayl/upscayl/assets/11874211/f194dcde-2bf1-43a5-9dd1-cff56cc741fe)
This also makes it kinda inconsistent with the other UI elements, so I <del>propose making</del> <ins>accidently made</ins> only not-selected buttons primary.
![image](https://github.com/upscayl/upscayl/assets/11874211/082591a3-7601-4a77-9ea0-888293ea0f5b)
![image](https://github.com/upscayl/upscayl/assets/11874211/02592860-e9a1-4ee4-b85e-1640c474b8d6)

**Comment by NayamAmarshe** [comment]
> I accidently committed [62dd93b](https://github.com/upscayl/upscayl/commit/62dd93b92118de12e72c4d274c2249fe987d6633) while trying to start a pull request... I think the problem with 3 is the hacky way the selector is made to fit the upscayl theme. In that theme the primary color is a lighter shade of grey, though in other themes it's less background-y. So the button was accented, and both buttons were made primary (which I don't get). ![image](https://user-images.githubusercontent.com/11874211/266863481-f194dcde-2bf1-43a5-9dd1-cff56cc741fe.png) This also makes it kinda inconsistent with the other UI elements, so I ~propose making~ accidently made only not-selected buttons primary. ![image](https://user-images.githubusercontent.com/11874211/266863461-082591a3-7601-4a77-9ea0-888293ea0f5b.png) ![image](https://user-images.githubusercontent.com/11874211/266863548-02592860-e9a1-4ee4-b85e-1640c474b8d6.png)

Wait, but I fixed it already. I added a ring to the selected buttons.

**Comment by aaronliu0130** [comment]
My main problem was the colors

**Comment by NayamAmarshe** [comment]
> My main problem was the colors

Ok, fixed it.
