### ISSUE TITLE
Compatibility List - Integrated GPU Suggestion

### ISSUE THREAD

**Issue by Yaki-0** [upscayl/upscayl#448]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

I have a "AMD Radeon Vega 8 Mobile" as an iGPU and Upscayl works perfectly fine

**Comment by aaronliu0130** [comment]
Thanks for your contribution! Please use the "documentation" label next time as this isn't about the app itself.
