### ISSUE TITLE
Digital Art Upscale Type

### ISSUE THREAD

**Issue by TrafalgarSP** [upscayl/upscayl#449]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
None
```

### Describe the Bug

After the recent update on Upscayl what happen to Digital Art upscayl type? Is it my version only or the entire update for everyone?

### To Reproduce

Bring back the Digital Art type model.

### Version/Commit Hash

Upscayl v2.7.5

### OS Specifics

NVIDIA MX330

### Screenshots

[](ur
![Screenshot (1208)](https://github.com/upscayl/upscayl/assets/47938272/cd83c1f3-5f0d-418f-bfa0-1a59836287e0)
![Screenshot (1209)](https://github.com/upscayl/upscayl/assets/47938272/f29bd356-07f3-41da-9def-78b432f5262a)

**Comment by aaronliu0130** [comment]
It's still here for me. This seems like an issue of the dropdown clipping out (see how the bottom doesn't have rounded corners?), try scrolling down the page instead of just the dropdown.
![image](https://github.com/upscayl/upscayl/assets/11874211/9951fc40-fdb3-4e3d-a09c-fa9786bf4cad)

**Comment by TrafalgarSP** [comment]
> It's still here for me. This seems like an issue of the dropdown clipping out (see how the bottom doesn't have rounded corners?), try scrolling down the page instead of just the dropdown. ![image](https://user-images.githubusercontent.com/11874211/265513449-9951fc40-fdb3-4e3d-a09c-fa9786bf4cad.png)

i'm afraid mine is not there i try scrolling but the below is only ultrasharp.

**Comment by NayamAmarshe** [comment]
Try setting your display to 100% instead of 125% in the settings. I suspect it's your display zoomed in, not having enough space.

**Comment by aaronliu0130** [comment]
Don’t scroll the drop-down, scroll the page outside of the drop-down.On Sep 4, 2023, at 10:27 PM, TrafalgarSP ***@***.***> wrote:﻿

It's still here for me. This seems like an issue of the dropdown clipping out (see how the bottom doesn't have rounded corners?), try scrolling down the page instead of just the dropdown. 

i'm afraid mine is not there i try scrolling but the below is only ultrasharp.
