### ISSUE TITLE
Is a GPU required?

### ISSUE THREAD

**Issue by lnicola** [upscayl/upscayl#45]
I tried both 1.1.1 and 1.2.0 on my PC with a Radeon 6800XT with the Mesa drivers, which AFAIK doesn't support Vulkan compute, and they work fine. Is there a way to check if the GPU is actually used?

**Comment by NayamAmarshe** [comment]
https://github.com/upscayl/upscayl#note-upscayl-does-not-work-without-a-gpu-sorry-youll-need-a-vulkan-compatible-gpu-to-upscale-images-cpu-or-igpu-wont-work

**Comment by lnicola** [comment]
Sure, what I'm saying is that I don't think I have a compatible GPU and it's still working on my system.

**Comment by lnicola** [comment]
Okay, not even `RADV_DEBUG=nocompute`, but I checked the power management info and my GPU spikes to 230 W, so I suppose it actually supports Vulkan compute. TIL!

Sorry for the noise!
