### ISSUE TITLE
Batch Upscayl toggle "persists" across sessions

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#453]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
N/A
```

### Describe the Bug

Upscayl defaults to Batch mode and toggle off if you closed the last session with Batch on. In this mode toggling the toggle also makes it normal mode.

### To Reproduce

1. toggle batch
2. turn upscayl off and on again (close it lol)
3. observe that the menus say select folder
4. successfully batch upscayl through dialog
5. toggle
6. normal mode!

### Version/Commit Hash

2.7.5

### OS Specifics

N/A, win11 23H2 25941

### Expected Behavior

no persist pls

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/11874211/b40c42f6-2fcf-4fb3-a577-1ffb3ec6d46f)

**Comment by NayamAmarshe** [comment]
Ah good catch, thank you!
