### ISSUE TITLE
Refactor Codebase and make it more modular

### ISSUE THREAD

**Issue by tpfbnz** [upscayl/upscayl#454]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

I am not a java writer, but I had a look at code. I could easily be way off base, so apologies in advance if that is the case.
selectFile.js and selectFolder.js in main/util listener appear to be called to handle both input and output files.
By separating functions and creating to, say, selectInFolder.js , selectFolderFile.js, selectInFile.js , selectOutFile.js, work flow overlap may be reduced . It is at expense of more code but overhead in user managed program segment likely miniscule. Benefit to user - tidier workflow.

### Related Problem(s)

A relatively minor issue is that my entry in input folder field is replaced during the process by the output details, and similarly for other entries so when working with several images and addresses I am having to re-enter all information. It was mainly noticeable when processing did not complete and I was repeating process.
I suspect that the action of re-entering the same module to process different objectives may contribute to unwanted fails of process.

### Alternatives

I have checked that this is not addressed in other issues, but I think it may help in possibly several different issues i.e.#453,452,450,440 , although my check of  most of them was cursory.

cheers
bob

**Comment by NayamAmarshe** [comment]
I tried that already but it didn't work. 
Electron works in weird ways.

**Comment by NayamAmarshe** [comment]
I started working on this again: https://github.com/upscayl/upscayl/pull/464

I'll give the refactor another go.
