### ISSUE TITLE
Instructions text is barely legible on some themes.

### ISSUE THREAD

**Issue by cd-CreepArghhh** [upscayl/upscayl#457]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [ ] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

This issue is similar to #186, #206 and #224, but it is different text, and more related to different themes, so I am making a new issue.

On some themes, the text that says "Select or drag and drop a PNG, JPG, JPEG or WEBP image." is barely legible. Some themes have more legible text than others, but it is an issue in all the themes listed below:
- Light
- Corporate
- Synthwave
- Halloween
- Garden
- Forest (With this theme, the text is not legible at all)
- Aqua
- Lofi
- Fantasy
- Luxury
- Dracula
- Autumn
- Acid
- Lemonade
- Night
- Coffee
- Winter

### Screenshots

Forest is the worst. Not only is the text illegible, the bounding box's border is also barely perceptible
![image](https://github.com/upscayl/upscayl/assets/65649991/d43cdf3b-21e4-4a57-b071-d7d432b2cec5)

Some others (all the themes listed are basically the same as these examples):
![image](https://github.com/upscayl/upscayl/assets/65649991/a83684e8-9a30-4a66-9800-09676614f159)
![image](https://github.com/upscayl/upscayl/assets/65649991/cc2e1878-f53b-4820-a3ea-a3ea81eae332)
![image](https://github.com/upscayl/upscayl/assets/65649991/8c552148-5bc0-4e27-9dd8-aaa269942272)

**Comment by NayamAmarshe** [comment]
Thanks for reporting. I just fixed it in v2.8

**Comment by aaronliu0130** [comment]
This is a duplicate of #445 , which admittingly doesn't have a clear title.
