### ISSUE TITLE
Add GFPGAN

### ISSUE THREAD

**Issue by sandarutharuneth** [upscayl/upscayl#458]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Please consider adding GFPGAN to the app. It's really helpful when you're trying to restore faces and upscale images in bulk cuz gfpgan does both perfectly.

Thanks in advance

**Comment by NayamAmarshe** [comment]
Upscayl Cloud will have the option to enhance faces in photos :)

Currently, this functionality cannot be added easily to Upscayl Desktop.

**Comment by sandarutharuneth** [comment]
Thanks for the quick response <3
Looking forward to use the upcoming Upscayl Cloud
