### ISSUE TITLE
Batch upscayl error

### ISSUE THREAD

**Issue by DimMan88** [upscayl/upscayl#459]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to ultramix_balanced
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
```

### Describe the Bug

When try to to a batch Upscayl it shows me this error :

![2023-09-09 174950](https://github.com/upscayl/upscayl/assets/71668463/62e7fa7e-12ea-4083-804b-aa04043a29cf)

### To Reproduce

try to batch upscayl

### Version/Commit Hash

2.7.5

### OS Specifics

Windows 10 22H2 Build 19045.3393

### Screenshots

![2023-09-09 174950](https://github.com/upscayl/upscayl/assets/71668463/4fad9cf8-ede2-4984-81c1-5fd2b3bf8de5)

**Comment by aaronliu0130** [comment]
what's your GPU

**Comment by DimMan88** [comment]
The folder contained only the images that needed to upscale.
The error appears only on Batch upscale.

-i7 12700K
-ASUS Radeon RX 6650 XT 8GB GDDR6 Dual OC PCIe 4.0

**Comment by aaronliu0130** [comment]
You just copy them like how you got these logs *after* you reproduce the bug.

**Comment by DimMan88** [comment]
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to ultramix_balanced
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\Δημήτρης\Desktop
🖼 Selected Folder Path:  C:\Users\Δημήτρης\Desktop
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Δημήτρης\Desktop,-o,C:\Users\Δημήτρης\Desktop_upscayled_ultramix_balanced_x4,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultramix_balanced,,,-f,png
🚧 FOLDER_UPSCAYL_PROGRESS:  [0 AMD Radeon RX 6650 XT]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 AMD Radeon RX 6650 XT]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon RX 6650 XT]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon RX 6650 XT]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🔄 Resetting image paths
🚧 FOLDER_UPSCAYL_PROGRESS:  decode image C:\Users\��������\Desktop/desktop.ini failed

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR INVALID FILES IN FOLDER - FAILED
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false

**Comment by DimMan88** [comment]
Yeah. That was the problem.....

Tried now to upscale from c:\1 folder to another disk folder e:\2  and worked fine.

**Comment by aaronliu0130** [comment]
Ok, so the problem is yet again non-latin characters. 2.8 should fix this issue, please stand by while we compile a Windows build.

**Comment by DimMan88** [comment]
Just updated to 2.8.1 version. Still the same problem.

**Comment by aaronliu0130** [comment]
Alright, could you post the logs?

**Comment by DimMan88** [comment]
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to ultramix_balanced
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\Δημήτρης\Desktop
🖼 Selected Folder Path:  C:\Users\Δημήτρης\Desktop
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\Δημήτρης\Desktop\1
🗂 Setting Output Path:  C:\Users\Δημήτρης\Desktop\1
🧠 Remembering Output Folder:  C:\Users\Δημήτρης\Desktop\1
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Δημήτρης\Desktop,-o,C:\Users\Δημήτρης\Desktop\1_ultramix_balanced_x4,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultramix_balanced,,,-f,png
🚧 FOLDER_UPSCAYL_PROGRESS:  [0 AMD Radeon RX 6650 XT]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 AMD Radeon RX 6650 XT]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon RX 6650 XT]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon RX 6650 XT]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🔄 Resetting image paths
🚧 FOLDER_UPSCAYL_PROGRESS:  decode image C:\Users\��������\Desktop/desktop.ini failed

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR INVALID FILES IN FOLDER - FAILED
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Setting quality to 100%

**Comment by NayamAmarshe** [comment]
Don't batch upscale the desktop folder.

**Comment by DimMan88** [comment]
> Don't batch upscale the desktop folder.

Why?

**Comment by NayamAmarshe** [comment]
> > Don't batch upscale the desktop folder.
> 
> Why?

Because Desktop folder has extra files that are not images.

The folder you're upscaling has to only have image files, nothing else, not even hidden files.

**Comment by DimMan88** [comment]
> > > Don't batch upscale the desktop folder.
> > 
> > 
> > Why?
> 
> Because Desktop folder has extra files that are not images.
> 
> The folder you're upscaling has to only have image files, nothing else, not even hidden files.

Yes. You are correct. I made some tests and this was the problem. 

Now it is working fine. Thank you!
