### ISSUE TITLE
Error message when 'upscayle' is pressed and app seems to hang afterwards

### ISSUE THREAD

**Issue by Rabscuttler** [upscayl/upscayl#46]
Thanks for your work on this. 
I can add an image, but when I press Step 4, I get the following error message in a modal dialogue box. The app then shows the 'Hold On...' spinner but never seems to progress further.

```
Uncaught Exception: Error: spawn /Applications/Upscayl.app/Contents/Resources/bin/upscayl EACCES at ChildProcess._handle.onexit (node:internal/child_process:283:19) at onErrorNT (node:internal/child_process:478:16) at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Tried with a few images.
Upscayl Version 1.2.0 (1.2.0)
MacBook Pro (14-inch, 2021), MacOS 12.3 (21E230)

**Comment by NayamAmarshe** [comment]
Hi, please read this: https://github.com/upscayl/upscayl/issues/44

**Comment by Rabscuttler** [comment]
Many thanks! Apologies, double fail for not reading the instructions or spotting the closed issue.
