### ISSUE TITLE
Something went wrong installing the sharp module

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#462]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
A JavaScript error occurred in the main process
Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/tmp/.mount_upscayzhENCa/resources/app.asar/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/tmp/.mount_upscayzhENCa/resources/app.asar/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
```

### Describe the Bug

Whenever I try to run the latest Upscayl prerelease I fail to launch it and the terminal gives me this error.

### To Reproduce

just open it

### Version/Commit Hash

2.8.0 (both .zip and appimage)

### OS Specifics

Linux aliugate 6.4.12-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:37:46 +0000 x86_64 GNU/Linux (this is the output of `uname -a`

**Comment by fwn0** [comment]
Same here, ..... 
fix = paru libvips or sudo pacman -S libvips (for archlinux based distros)
sudo cp  libvips* libcgif* libgsf*   ..... to /your/path/upscayl-2.8.0-linux     directory 
sudo pacman -Rcns libvips libgsf libcgif

**Comment by aaronliu0130** [comment]
Yeah, the obvious workaround which also works is to just install libvips.

**Comment by fwn0** [comment]
Yes, but if you need the portable package (appimage, zip or dwarfs), you need copy these libs in upscayl-2.8.0-linux root directory.  ;)

**Comment by NayamAmarshe** [comment]
Awesome, thanks for testing!
I think this is only an issue on Linux. Need to find a universal solution before release.

**Comment by NayamAmarshe** [comment]
Fix is mentioned here, I totally skipped over it: 
https://sharp.pixelplumbing.com/install#prebuilt-binaries

**Comment by aaronliu0130** [comment]
It also needs libatk, libcups, libdrm (surprising), libgtk3, libasound to start and need to load libopenjp2 (openjpeg2) for sharp, though most DEs already ship these.

**Comment by TGS963** [comment]
can we package these libraries inside the upscayl zip somehow?

**Comment by TGS963** [comment]
even if libvips is found, the app fails to launch. any idea why? I see no errors

**Comment by aaronliu0130** [comment]
Try launching from terminal

**Comment by aaronliu0130** [comment]
Also, why do we have libasound.so? We don't play any sound

**Comment by NayamAmarshe** [comment]
> Also, why do we have libasound.so? We don't play any sound

🤷🏻

**Comment by NayamAmarshe** [comment]
I tested flatpak on Zorin, it seems to work well. I'm not sure why you're getting errors.

**Comment by NayamAmarshe** [comment]
@TGS963 tested the zip and AppImage too, they work fine.

**Comment by TGS963** [comment]
Yep

**Comment by aaronliu0130** [comment]
I'm pretty sure 2.8.1 fixed this
