### ISSUE TITLE
GPU ID does not work correctly. 

### ISSUE THREAD

**Issue by gabrielcapilla** [upscayl/upscayl#465]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🎯 GET_MODELS_LIST:  
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus-anime
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting quality from localStorage 0
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 0,1
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 0,1
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting quality from localStorage 0
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 0,1
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  /home/human/Snow-Leopard.jpg
🖼 Selected Image Path:  /home/human/Snow-Leopard.jpg
📁 Selected Image Directory:  /home/human
🖼 imagePath:  /home/human/Snow-Leopard.jpg
🔤 Extension:  jpg
🔀 Model changed:  realesrgan-x4plus
🔀 Setting model to realesrgan-x4plus
🔀 Model changed:  realesrgan-x4plus
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,/home/human/Snow-Leopard.jpg,-o,/home/human/Snow-Leopard_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,/usr/lib/upscayl/resources/models,-n,realesrgan-x4plus,-g,0,1,-f,png
🐞 BACKEND REPORTED:  image upscayl:  [0 AMD Radeon RX 5700 XT]  queueC=1[4]  queueG=0[1]  queueT=2[2]
[0 AMD Radeon RX 5700 XT]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon RX 5700 XT]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon RX 5700 XT]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
[1 AMD Radeon RX 5700 XT]  queueC=1[4]  queueG=0[1]  queueT=2[2]
[1 AMD Radeon RX 5700 XT]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 AMD Radeon RX 5700 XT]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 AMD Radeon RX 5700 XT]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 AMD Radeon RX 5700 XT]  queueC=1[4]  queueG=0[1]  queueT=2[2]
[0 AMD Radeon RX 5700 XT]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon RX 5700 XT]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon RX 5700 XT]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
[1 AMD Radeon RX 5700 XT]  queueC=1[4]  queueG=0[1]  queueT=2[2]
[1 AMD Radeon RX 5700 XT]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 AMD Radeon RX 5700 XT]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 AMD Radeon RX 5700 XT]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  [2 AMD Radeon RX 5700]  queueC=1[4]  queueG=0[1]  queueT=2[2]
[2 AMD Radeon RX 5700]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[2 AMD Radeon RX 5700]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[2 AMD Radeon RX 5700]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
[3 AMD Radeon RX 5700]  queueC=1[4]  queueG=0[1]  queueT=2[2]
[3 AMD Radeon RX 5700]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[3 AMD Radeon RX 5700]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[3 AMD Radeon RX 5700]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [2 AMD Radeon RX 5700]  queueC=1[4]  queueG=0[1]  queueT=2[2]
[2 AMD Radeon RX 5700]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[2 AMD Radeon RX 5700]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[2 AMD Radeon RX 5700]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
[3 AMD Radeon RX 5700]  queueC=1[4]  queueG=0[1]  queueT=2[2]
[3 AMD Radeon RX 5700]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[3 AMD Radeon RX 5700]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[3 AMD Radeon RX 5700]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 0,1
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting quality from localStorage 0
🐞 BACKEND REPORTED:  image upscayl:  0.00%

...

🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
upscaledImagePath:  /home/human/Snow-Leopard_upscayl_4x_realesrgan-x4plus.png
💯 UPSCAYL_DONE:  /home/human/Snow-Leopard_upscayl_4x_realesrgan-x4plus.png
```

### Describe the Bug

According to the [Wiki](https://github.com/upscayl/upscayl/wiki/Guide) I can use **multi-GPU** by typing `0`, `1`, or `2` to call the correct GPU ID. You can even use the `0,1` parameter to use more than one GPU. 

**Context**:
**GPU 0** is `0c:00.0` _(AMD Radeon RX 5700 XT)_
**GPU 1** is `0f:00.0` _(AMD Radeon RX 5700)_

According to this, GPU ID _does not work_. So I tried other, less elegant methods; I launched _Upscayl_ via terminal using the parameter `DRI_PRIME=1 upscayl-run` to force Upscayl to run on GPU 1. This causes GPU 1 to be used, but at a usage rate of _less than 15%_. That means that mainly GPU 0 is used at 100%. 

According to the Upscayl log, **GPU 0** is `GPU 0` (_0 AMD Radeon RX 5700 XT_) and **GPU 1** is `GPU 2` (_2 AMD Radeon RX 5700_). By setting GPU ID to 2, the GPU shows a fictitious load of 99%, but at power consumption it stays in IDLE. The result is that the image is not processed.

On short, setting GPU ID to `2` does not work, setting GPU ID to `0,2` does not work. Setting `DRI_PRIME=1` **works partially** but the main workload (100%) falls on GPU 0.

The multi-GPU capability is not available at the moment, can you check the multi-GPU feature? 

## About multi-GPU usage.

* In DaVinci Resolve Studio multi-GPU usage works fine.

* Using the `DRI_PRIME=1` parameter on **OBS Studio** works, making the encoding workload load on GPU 1 and not GPU 0 while maintaining good performance in games as well as recording.

### To Reproduce

According to the Upscayl log, **GPU 0** is `GPU 0` (_0 AMD Radeon RX 5700 XT_) and **GPU 1** is `GPU 2` (_2 AMD Radeon RX 5700_). By setting GPU ID to 2, the GPU shows a fictitious load of 99%, but at power consumption it stays in IDLE. The result is that the image is not processed.

On short, setting GPU ID to `2` does not work, setting GPU ID to `0,2` does not work. Setting `DRI_PRIME=1` **works partially** but the main workload (100%) falls on GPU 0.

### Version/Commit Hash

aur/upscayl-bin  2.8.0-2

### OS Specifics

OS: CachyOS KERNEL: 6.5.2-1-cachyos CPU: AMD Ryzen 9 3900X 12-Core GPU: AMD Radeon RX 5700 XT (navi10, LLVM 16.0.6, DRM 3.54, 6.5.2-1-cachyos) GPU DRIVER: 4.6 Mesa 23.1.7-arch1.1 RAM: 16 GB

**Comment by NayamAmarshe** [comment]
Thanks for the bug report, Gabriel. Unfortunately, there's not much that I can do about this for now because we depend on this repo: https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan

The best we can do is make sure nothing like this happens on Upscayl Cloud, but that's an online service, not a local one 😅 

We're also thinking of fixing some bugs in the repo above by forking it, so we might fix this issue in the future :)

**Comment by gabrielcapilla** [comment]
Ok, thanks @NayamAmarshe !
