### ISSUE TITLE
[Bug]: A javascript error eccurred in the main process

### ISSUE THREAD

**Issue by akivaron** [upscayl/upscayl#47]
Very interesting product. I had this problem when running on Mac m1 pro.
Do you have any suggestions for this?

<img width="1098" alt="Screen Shot 2022-08-30 at 02 49 39" src="https://user-images.githubusercontent.com/9086506/187286526-00a42184-e319-4bd6-9783-efd8db3b71a9.png">

**Comment by NayamAmarshe** [comment]
https://github.com/upscayl/upscayl/issues/44
