### ISSUE TITLE
Grainy/Noisy/Pixelated output in 2.8.1

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#474]
Reproduced with Digital Art (animevideo) model on x4 PNG 0% compression, you can compare pictures at https://www.diffchecker.com/image-compare/ 's "Downloadable" tab which labels differences with pink dots

![test1](https://github.com/upscayl/upscayl/assets/145080602/ec1c3c51-ed26-4f63-a56a-426d9438de57)
![test2](https://github.com/upscayl/upscayl/assets/145080602/4cc5942e-579a-4baf-ba5f-11b701dc6178)
![eman](https://github.com/upscayl/upscayl/assets/11874211/6058fc5f-9d48-41f1-a03b-5a81e1487f2f)
[eman-downloadable (differences labeled with pink dots)](https://github.com/upscayl/upscayl/assets/11874211/c830b7b8-6b2c-45fe-9ed7-1cc3b3f6610d)

## 2.7.5
![2 7 5](https://github.com/upscayl/upscayl/assets/145080602/340a45eb-ac12-4aeb-a3bc-d155bac529fc)
[eman-2 7 5](https://github.com/upscayl/upscayl/assets/11874211/c4f0e208-817c-470a-8202-f1c3c4e7c4a4)

## 2.8.1
![2 8 1](https://github.com/upscayl/upscayl/assets/145080602/fd835a9f-3004-4061-9c35-918bcc7dc616)
[eman-2 8 1](https://github.com/upscayl/upscayl/assets/11874211/94fa7de8-3995-40e4-9729-5b3af55225cf)

_Originally posted by @VinzMota in https://github.com/upscayl/upscayl/discussions/467#discussioncomment-7008766_

**Comment by NayamAmarshe** [comment]
Should we add a 'Disable Post-Processing' toggle?

**Comment by NayamAmarshe** [comment]
Does this look better?
![image](https://github.com/upscayl/upscayl/assets/25067102/93ac0916-1f85-4f1f-ad2c-f73d157debdf)

**Comment by NayamAmarshe** [comment]
Could you please test with the latest commit?

**Comment by aaronliu0130** [comment]
[downloadable](https://github.com/upscayl/upscayl/assets/11874211/14baeea4-b60c-415b-915d-c25b742c94e1)
looks fixed to me! @VinzMota how about you? Download npm (or pnpm if you want) and the latest source code from <https://github.com/upscayl/upscayl/archive/refs/heads/main.zip> and do `npm install && npm run dev` in the extracted folder (substitute npm with pnpm if you want to use that)

**Comment by SpiritPowerTX** [comment]
Hello ! I have the same issue the same problem and it is boring.
I have found a weird solution : that when I launch a very big batch images folder upscaling the GPU turn hot (all is ok for now) BUT AFTER the GPU job finished the CPU start to turn hot for destroy the good finished pictures for replace the good ones by the ugly pixelated ones. So the solution is : when the job is finished (for the GPU) I imediatly kill the program process "Upscayl" while it is using the CPU and i have my nice pictures without the ugly pixels !

**Comment by SpiritPowerTX** [comment]
> Should we add a 'Disable Post-Processing' toggle?

It looks like the issue is a strange "post-processing" using CPU for make pictures lighter but the same dimensions.

**Comment by aaronliu0130** [comment]
@SpiritPowerTX At least for me, this has been fixed yesterday, we're just waiting for VinzMota to confirm. Can you run the steps I mentioned to confirm if it works for you?

**Comment by SpiritPowerTX** [comment]
> @SpiritPowerTX At least for me, this has been fixed yesterday, we're just waiting for VinzMota to confirm. Can you run the steps I mentioned to confirm if it works for you?

can you post a new version ? (like 2.8.2) with corrected bugs ? Or the 2.8.1 already corrected ?

**Comment by SpiritPowerTX** [comment]
> @SpiritPowerTX At least for me, this has been fixed yesterday, we're just waiting for VinzMota to confirm. Can you run the steps I mentioned to confirm if it works for you?

@aaronliu0130 Hello, sorry I don't know how to use and test your lastest and corrected version ?
the ".zip" file don't have any software, only codes..

**Comment by aaronliu0130** [comment]
Yes, it’s the source code. Use the npm commands I mentioned to run it.

**Comment by aaronliu0130** [comment]
Also, you're encounter some hydration errors on startup, ignore these.

**Comment by VinzMota** [comment]
> [downloadable](https://github.com/upscayl/upscayl/assets/11874211/14baeea4-b60c-415b-915d-c25b742c94e1) looks fixed to me! @VinzMota how about you? Download npm (or pnpm if you want) and the latest source code from https://github.com/upscayl/upscayl/archive/refs/heads/main.zip and do `npm install && npm run dev` in the extracted folder (substitute npm with pnpm if you want to use that)

Yes, it works ! Thanks !

**Comment by SpiritPowerTX** [comment]
> Yes, it’s the source code. Use the npm commands I mentioned to run it.

the npm command doesn't work in my cmd.exe (windows 11) : i have this ERROR message : 
'npm' is not recognized as an internal command
or external, an executable program or batch file.
