### ISSUE TITLE
Adding support for selecting & upscaling multiple images

### ISSUE THREAD

**Issue by davidCpp16** [upscayl/upscayl#48]

**Comment by NayamAmarshe** [comment]
Yes that is already planned.

**Comment by davidCpp16** [comment]
Can I help you somewhere in the development?

**Comment by NayamAmarshe** [comment]
> Can I help you somewhere in the development?

Oh definitely :)
We could use some help here: https://github.com/upscayl/upscayl/issues/33

**Comment by davidCpp16** [comment]
You mean by porting the project to typescript?

**Comment by NayamAmarshe** [comment]
> You mean by porting the project to typescript?

Yes, just setting up typescript

**Comment by davidCpp16** [comment]
Alright!

**Comment by NayamAmarshe** [comment]
Shifting discussion here:
https://github.com/upscayl/upscayl/issues/50
