### ISSUE TITLE
Error processing (scaling and convirting)

### ISSUE THREAD

**Issue by mayaalla** [upscayl/upscayl#487]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
Error processing (scaling and convirting)
```

### Describe the Bug

I can't upscale any image

### To Reproduce

I can't upscale any image

### Version/Commit Hash

2.8.6

### OS Specifics

Intel (R) HD graphic 520

### Expected Behavior

![image](https://github.com/upscayl/upscayl/assets/102388977/6c70e4ba-1fbd-4bc5-a1e1-4bfae3251352)

### Screenshots

![Capture](https://github.com/upscayl/upscayl/assets/102388977/d69209bc-30d9-4a11-93dc-cb9dea475a25)

**Comment by aaronliu0130** [comment]
> Intel (R) HD graphic 520
> Yes, unfortunately. NCNN Vulkan requires a Vulkan compatible GPU. Upscayl won't work with most iGPUs or CPUs. 

> I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).

![compulsory rickrolls are issued for duplicates of issues and the FAQ and normies who use intelgrated GPUs](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
---
[Have you tried the workaround?](https://github.com/upscayl/upscayl/wiki/Misc)

**Comment by mayaalla** [comment]
> > Intel (R) HD graphic 520
> > Yes, unfortunately. NCNN Vulkan requires a Vulkan compatible GPU. Upscayl won't work with most iGPUs or CPUs.
> 
> > I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
> 
> ## ![compulsory rickrolls are issued for duplicates of issues and the FAQ and normies who use intelgrated GPUs](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
> [Have you tried the workaround?](https://github.com/upscayl/upscayl/wiki/Misc)

I dowloaded the app a few days ago and it worked but today I reset the computer and downloaded again but this time it did not work

**Comment by aaronliu0130** [comment]
The dialog window is not the logs.
