### ISSUE TITLE
Output folder selector and progress indicator don't work correctly for batch upscale  / v. 2.8.6

### ISSUE THREAD

**Issue by Ypdes** [upscayl/upscayl#488]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage:  1
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus-anime
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Updating Folder Path:  D:\_Temp\_Upscale_test
🖼 Selected Folder Path:  D:\_Temp\_Upscale_test
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  D:\_Temp\_Upscale_test
🔀 Model changed:  realesrgan-x4plus-anime
🔀 Setting model to realesrgan-x4plus-anime
🐞 BACKEND REPORTED:  📁 Updating Folder Path:  D:\_Temp\_Upscale_test
🗂 Setting Output Path:  D:\_Temp\_Upscale_test
🧠 Remembering Output Folder:  D:\_Temp\_Upscale_test
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  D:\_Temp\_Upscale_test
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\_Temp\_Upscale_test,-o,D:\_Temp\_Upscale_test_realesrgan-x4plus-anime_x4,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-g,1,-f,png
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🚧 FOLDER_UPSCAYL_PROGRESS:  [0 Intel(R) UHD Graphics]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) UHD Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) UHD Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) UHD Graphics]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  2,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  4,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  2,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  6,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  4,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  8,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  6,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  8,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  12,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  12,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  16,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  16,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  18,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  18,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  22,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  22,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  27,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  27,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  29,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  29,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  31,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  31,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  33,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  33,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  37,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  37,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  41,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  41,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  43,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  43,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  45,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  45,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  47,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  47,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  52,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  52,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  54,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  54,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  56,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  56,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  58,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  58,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  62,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  62,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  66,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  66,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  68,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  68,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  70,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  70,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  72,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  72,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  77,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  77,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  79,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  79,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  81,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  81,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  83,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  83,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  87,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  87,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  91,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  91,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  93,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  93,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  95,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  95,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  97,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  97,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  2,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  2,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  4,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  4,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  6,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  6,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  8,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  8,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  12,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  12,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  16,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  16,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  18,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  18,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  22,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  22,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  27,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  27,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  29,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  29,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  31,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  31,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  33,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  33,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  37,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  37,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  41,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  41,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  43,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  43,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  45,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  45,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  47,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  47,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  52,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  52,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  54,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  54,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  56,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  56,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  58,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  58,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  62,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  62,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  66,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  66,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  68,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  68,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  70,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  70,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  72,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  72,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  77,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  77,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  79,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  79,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  81,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  81,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  83,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  83,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  87,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  87,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  91,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  91,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  93,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  93,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  95,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  95,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  97,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  97,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  2,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  4,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  6,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  8,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  12,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  16,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  18,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  22,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  27,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  29,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  31,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  33,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  37,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  41,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  43,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  45,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  47,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  52,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  54,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  56,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  58,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  62,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  66,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  68,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  70,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  72,92%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  77,08%

🚧 FOLDER_UPSCAYL_PROGRESS:  79,17%

🚧 FOLDER_UPSCAYL_PROGRESS:  81,25%

🚧 FOLDER_UPSCAYL_PROGRESS:  83,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,42%

🚧 FOLDER_UPSCAYL_PROGRESS:  87,50%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,58%

🚧 FOLDER_UPSCAYL_PROGRESS:  91,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  93,75%

🚧 FOLDER_UPSCAYL_PROGRESS:  95,83%

🚧 FOLDER_UPSCAYL_PROGRESS:  97,92%

🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
💯 FOLDER_UPSCAYL_DONE:  D:\_Temp\_Upscale_test_realesrgan-x4plus-anime_x4
🐞 BACKEND REPORTED:  📐 Processing Image:  [object Object]
🐞 BACKEND REPORTED:  📐 Processing Image:  [object Object]
🐞 BACKEND REPORTED:  📐 Processing Image:  [object Object]
🐞 BACKEND REPORTED:  📐 Processing Image:  [object Object]
🐞 BACKEND REPORTED:  📐 Processing Image:  [object Object]
🐞 BACKEND REPORTED:  
🐞 BACKEND REPORTED:  
🐞 BACKEND REPORTED:  
🐞 BACKEND REPORTED:  
🐞 BACKEND REPORTED:  ✅ Done converting to:  D:\_Temp\_Upscale_test_realesrgan-x4plus-anime_x4\003.png
🐞 BACKEND REPORTED:  ✅ Done converting to:  D:\_Temp\_Upscale_test_realesrgan-x4plus-anime_x4\001.png
🐞 BACKEND REPORTED:  ✅ Done converting to:  D:\_Temp\_Upscale_test_realesrgan-x4plus-anime_x4\004.png
🐞 BACKEND REPORTED:  ✅ Done converting to:  D:\_Temp\_Upscale_test_realesrgan-x4plus-anime_x4\002.png
🐞 BACKEND REPORTED:  
🐞 BACKEND REPORTED:  ✅ Done converting to:  D:\_Temp\_Upscale_test_realesrgan-x4plus-anime_x4\005.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage:  1
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0
```

### Describe the Bug

I'm trying to use batch mode. It works. The progress indicator is spinning but showing zero percent, everything looks like the app is working. After time the app says everything is done. But there are no files in output folder. I see the files in the folder "Source + realesrgan-x4plus-anime_x4" next to the source folder even I chose to save to the same folder.

![Image 002](https://github.com/upscayl/upscayl/assets/134853152/d9aa6c87-f1f5-4925-81ce-768f03fe6eb5)

### To Reproduce

1) Select Batch mode
2) Select source folder
3) Select a model
4) Select output folder
5) Press Upscayl button

### Version/Commit Hash

2.8.6

### OS Specifics

Windows 10

### Expected Behavior

The app should save processed images into the same folder, as I selected. I want to see the progress in per sent like in the previous versions

### Screenshots

![Image 002](https://github.com/upscayl/upscayl/assets/134853152/f2b734e4-aadb-48a9-8916-9ca7eaa132ce)
![Image 001](https://github.com/upscayl/upscayl/assets/134853152/9a2eb79a-c76d-4bdd-8f14-0b6c814a8e31)

**Comment by SpiritPowerTX** [comment]
i have the same bug !

**Comment by NayamAmarshe** [comment]
Could you please zip the image files and send them to me so that I can test it? 

I tried to reproduce the issue and the upscayl counter shows no progress ONLY if Upscayl doesn't have enough permissions to create a new folder.

**Comment by Ypdes** [comment]
> Could you please zip the image files and send them to me so that I can test it?
> 
> I tried to reproduce the issue and the upscayl counter shows no progress ONLY if Upscayl doesn't have enough permissions to create a new folder.

Sure, here're. Please note, version 2.5.1 works perfect in that mode. I had to roll back to it

[_000.zip](https://github.com/upscayl/upscayl/files/12706369/_000.zip)

**Comment by Ypdes** [comment]
Here's the log of 2.5.1:

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 1
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  D:\_Temp\_000
🖼 Selected Folder Path:  D:\_Temp\_000
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  D:\_Temp\_000
🗂 Setting Output Path:  D:\_Temp\_000
🧠 Remembering Output Folder:  D:\_Temp\_000
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\_Temp\_000,-o,D:\_Temp\_000,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-g 1,-f,png
🚧 FOLDER_UPSCAYL_PROGRESS:  [0 Intel(R) UHD Graphics]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) UHD Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) UHD Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) UHD Graphics]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  [1 NVIDIA GeForce RTX 3060 Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  bugsbn1=0  bugbilz=24  bugcopc=0  bugihfa=0
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  6,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  13,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  26,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  33,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  40,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  66,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  73,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  80,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  86,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  93,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  6,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  13,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  26,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  33,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  40,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  66,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  73,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  80,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  86,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  93,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  6,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  13,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  26,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  33,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  40,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  66,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  73,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  80,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  86,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  93,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  6,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  13,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  26,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  33,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  40,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  66,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  73,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  80,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  86,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  93,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  6,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  13,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  20,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  26,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  33,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  40,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  66,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  73,33%

🚧 FOLDER_UPSCAYL_PROGRESS:  80,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  86,67%

🚧 FOLDER_UPSCAYL_PROGRESS:  93,33%

🐞 BACKEND REPORTED:  💯 Done upscaling
💯 FOLDER_UPSCAYL_DONE:  D:\_Temp\_000
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage 1
⚙️ Getting rememberOutputFolder from localStorage false

**Comment by CrashCat** [comment]
Definitely see similar behavior on my end. Ignores my output folder and makes a new one with the name of the input folder as part. It seems around the same time this bug was introduced there was also some other error in file handling that started that causes early termination (with a success message?) on big batches (200+) but I've got to take some more time to reproduce properly.
