### ISSUE TITLE
Add where you can disable the preview

### ISSUE THREAD

**Issue by yummeshugr** [upscayl/upscayl#489]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Add where you can disable the preview. Sometimes i just want to have to render the image and not have my GPU trying to render the 16k image. It would just help me alot because sometimes i can't see any difference because of the quality.

### Related Problem(s)

sometimes lagging and crashing whenever i try and preview it 

### Alternatives

you could make it where the image preview just goes to the resolution of the monitor

**Comment by aaronliu0130** [comment]
Hmm, maybe but we should probably put something there in place of the preview. Any ideas?

**Comment by NayamAmarshe** [comment]
I don't think the GPU is used much when previewing images.

**Comment by SpiritPowerTX** [comment]
just add a "show preview button" in the prewiew area after the finished process (without any error)

**Comment by aaronliu0130** [comment]
Having the user toggle every time is bad. If we were to implement this we’d just add a toggle in options

**Comment by yummeshugr** [comment]
> I don't think the GPU is used much when previewing images.

i know it just lags whenever i try and look at the preview

**Comment by SpiritPowerTX** [comment]
> Having the user toggle every time is bad. If we were to implement this we’d just add a toggle in options

yes it's good too 😉

**Comment by NayamAmarshe** [comment]
> > I don't think the GPU is used much when previewing images.
> 
> i know it just lags whenever i try and look at the preview, and i have a decent graphics card

You can also reset the image after the upscaling is done.
