### ISSUE TITLE
[Bug] I cannot use an Image although it is .png

### ISSUE THREAD

**Issue by davidCpp16** [upscayl/upscayl#49]
![image](https://user-images.githubusercontent.com/77726560/187521378-6baefe8b-bffa-49ab-b1b3-f877d2ac253d.png)

I do not know why, but I suppose the rendering was successful and at the end I became this.

Or is it the bug which you were talking about, because I used an iGPU with Vulkan installed on Manjaro?

**Comment by aaronliu0130** [comment]
The read me states that you can't use an igpu
