### ISSUE TITLE
Seeming regression: AMD Radeon RX460 does not work

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [upscayl/upscayl#490]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Sharpen Image","value":"models-DF2K"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to models-DF2K
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/png","filePath":"D:\\Pictures library\\Clipart\\again.png","extension":"png"}
🖼 Setting image path:  D:\Pictures library\Clipart\again.png
🗂 Setting output path:  D:\Pictures library\Clipart
🖼 imagePath:  D:\Pictures library\Clipart\again.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  [object Object]
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\Pictures library\Clipart\again.png,-o,D:\Pictures library\Clipart\again_upscayl_4x_models-DF2K.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,models-DF2K,,,-f,png
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  [object Object]
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  image upscayl:  [0 Radeon(TM) RX 460 Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 Radeon(TM) RX 460 Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon(TM) RX 460 Graphics]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 Radeon(TM) RX 460 Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 Radeon(TM) RX 460 Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 Radeon(TM) RX 460 Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon(TM) RX 460 Graphics]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 Radeon(TM) RX 460 Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  _wfopen C:\Program Files\Upscayl\resources\bin\C:\Program Files\Upscayl\resources\models/models-DF2K.param failed

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  _wfopen C:\Program Files\Upscayl\resources\bin\C:\Program Files\Upscayl\resources\models/models-DF2K.param failed

🔄 Resetting image paths
🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Sharpen Image","value":"models-DF2K"}
⚙️ Setting gpuId to empty string
⚙️ Setting rememberOutputFolder to false
⚙️ Setting compression to 100%
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Sharpen Image","value":"models-DF2K"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to models-DF2K
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/png","filePath":"D:\\Pictures library\\Clipart\\Group Work.png","extension":"png"}
🖼 Setting image path:  D:\Pictures library\Clipart\Group Work.png
🗂 Setting output path:  D:\Pictures library\Clipart
🖼 imagePath:  D:\Pictures library\Clipart\Group Work.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  true
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  [object Object]
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\Pictures library\Clipart\Group Work.png,-o,D:\Pictures library\Clipart\Group Work_upscayl_4x_models-DF2K.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,models-DF2K,,,-f,png
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  [object Object],[object Object]
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  image upscayl:  [0 Radeon(TM) RX 460 Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[2]
🚧 UPSCAYL_PROGRESS:  [0 Radeon(TM) RX 460 Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[2]
🐞 BACKEND REPORTED:  image upscayl:  
[0 Radeon(TM) RX 460 Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon(TM) RX 460 Graphics]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 Radeon(TM) RX 460 Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  
[0 Radeon(TM) RX 460 Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon(TM) RX 460 Graphics]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 Radeon(TM) RX 460 Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  _wfopen C:\Program Files\Upscayl\resources\bin\C:\Program Files\Upscayl\resources\models/models-DF2K.param failed

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  _wfopen C:\Program Files\Upscayl\resources\bin\C:\Program Files\Upscayl\resources\models/models-DF2K.param failed

🔄 Resetting image paths
🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Sharpen Image","value":"models-DF2K"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0
```

### Describe the Bug

EDIT: Despite my username, in the present instance I am using _Windows_.

Seemingly, on my system no PNG of JPG can be upscayled - whereas on version 1.5.0 of Upscayl, the upscaling worked.

I did try entering '0' for the 'GPU Id' but so doing did not help (and I was unable to enter any other number into the relevant field).

PS: [This webpage of yours](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id) instructs one to 'upscayl an image'. It would be more accurate and more helpful to speak of _trying_ to upscayl an image. That same page could be clearer, too, about how to use the log to identify an integer for one's GPU. (The log contains a lot of text and many numbers.)

### To Reproduce

Here is one of the files that failed.
![90 percent](https://github.com/upscayl/upscayl/assets/47056543/57c4f491-d9dd-42a8-9c14-61138d87bc69)

### Version/Commit Hash

2.8.6

### OS Specifics

Windows 10 Pro - 22H2 (2009: 19045)

### Expected Behavior

Upscaling should work.

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/47056543/89596f6f-0c16-4f02-90a9-62459d38fd76)

![image](https://github.com/upscayl/upscayl/assets/47056543/cc3d29d4-f4a8-4bf9-b31f-6015efecf46d)

**Comment by NayamAmarshe** [comment]
> `🐞 BACKEND REPORTED:  image upscayl:  _wfopen C:\Program Files\Upscayl\resources\bin\C:\Program Files\Upscayl\resources\models/models-DF2K.param failed`
> Despite the error message it looks like it's not related to your GPU. It's somehow trying to read an invalid path.
> 
> `⚙️ Getting model from localStorage:  {"label":"Sharpen Image","value":"models-DF2K"}`
> Aha, that's the issue. We removed sharpen image in 2.5.1 and it's trying to find a nonexistent model. @NayamAmarshe Should we add a way to detect this? Can we somehow get more accurate error messages?

Wait, how is that possible? I removed sharpen model a long time ago.

**Comment by aaronliu0130** [comment]
I think they had the option set before updating beyond 2.5.1

**Comment by NayamAmarshe** [comment]
So all they need to do is change the model option :)

**Comment by aaronliu0130** [comment]
Yeah. What I'm wondering is perhaps the error dialog might be made clearer?

**Comment by NayamAmarshe** [comment]
> Yeah. What I'm wondering is perhaps the error dialog could be made clearer?

The issue is we can't handle every single edge case with just one alert dialog 😅

**Comment by aaronliu0130** [comment]
Well is it possible to put the line with "failed" inside the alert dialog? Treating any case of failed as an issue with the image or drivers is a bit weird...

**Comment by LinuxOnTheDesktop** [comment]
I do find that changing the 'model' option solves the problem. Yet, others might encounter the same problem. Hence at the least an improved error message seems desirable.

**Comment by NayamAmarshe** [comment]
> I do find that changing the 'model' option solves the problem. Yet, others might encounter the same problem. Hence at the least an improved error message seems desirable.

I've added a check for this in the latest update.

**Comment by aaronliu0130** [comment]
I was asking if the original error message could be outputted, like detect the line that has "failed" in it and print it in its entirety

**Comment by NayamAmarshe** [comment]
> I was asking if the original error message could be outputted, like detect the line that has "failed" in it and print it in its entirety

No, that won't be needed since it'd automatically reset the model if it's not in the default list.

**Comment by aaronliu0130** [comment]
This is not just about this specific problem. Since almost nobody used sharpen image this is a very small probability, and outputting the actual error message instead of a generic one would be greatly beneficial to debugging, instead of just adding more edgecase detection

**Comment by aaronliu0130** [comment]
I still wonder if we could output full error messages
