### ISSUE TITLE
List the app in DNF Package manager

### ISSUE THREAD

**Issue by IkelAtomig** [upscayl/upscayl#495]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Need to list the app in DNF package manager to update easily. 

Saying so because I didn't find the app in Fedora's DNF while using these commands in terminal : 

```
dnf search upscayl
dnf list | grep "Upscayl"
```

**Comment by NayamAmarshe** [comment]
It'd be difficult for us to maintain a DNF package since none of us use Fedora. I'd be happy to have someone volunteer though.

Same case with APT, we'd love to have Upscayl on Debian or Ubuntu but for now, it's too much maintenance work.

**Comment by aaronliu0130** [comment]
I use arch which has tools for creating fedora and Debian packages. I’d be happy to do this

**Comment by IkelAtomig** [comment]
Waiting for it !

**Comment by aaronliu0130** [comment]
RPMlint which we’re needed to fix fixable errors results in a flurry of errors, including ridiculous ones such as the icon size being the 0x0 folder. It also complains about finding header files among other things.

**Comment by IkelAtomig** [comment]
Fixing electron builder seems a better idea. Since it also applies for debian.

**Comment by aaronliu0130** [comment]
I don’t see any issues for the deb package yet and so far I have no idea how to fix builder lol

**Comment by IkelAtomig** [comment]
If this takes some time. Why not just make the AppImage updatable which would be better for the time being ?

**Comment by NayamAmarshe** [comment]
> If this takes some time. Why not just make the AppImage updatable which would be better for the time being ?

It already is updatable though

**Comment by aaronliu0130** [comment]
@NayamAmarshe Do we use AGPL 3.0 only or AGP 3.0 or later?

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe Do we use AGPL 3.0 only or AGP 3.0 or later?

Sorry, forgot to reply 😅 We use AGPL3+

**Comment by aaronliu0130** [comment]
I cannot get building from source to work, so I'll try making a package that just repackages our bad .rpm instead. Hopefully Fedora allows these

**Comment by NayamAmarshe** [comment]
Closing this issue because we're currently not equipped to fix this. Contributions are most welcome!

**Comment by IkelAtomig** [comment]
@NayamAmarshe - Would you like some help from me a fedora user to work on this ?

**Comment by aaronliu0130** [comment]
Would be great!

**Comment by IkelAtomig** [comment]
I am not of a developler here in packaging formats. So, What and How do I do it ?

**Comment by aaronliu0130** [comment]
https://docs.fedoraproject.org/en-US/package-maintainers/New_Package_Process_for_New_Contributors/

**Comment by IkelAtomig** [comment]
Okay, I like the idea. I might also package other apps that are available either as `deb` or AppImage only.

No promises though. I will try on free time. It's a lot of documentation to understand and to proceed with it.

**Comment by aaronliu0130** [comment]
No worries! Good luck.
