### ISSUE TITLE
Some parts of an image (blocks) are inappropriate

### ISSUE THREAD

**Issue by synth7x7** [upscayl/upscayl#506]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
-
```

### Describe the Bug

Some parts of an image (blocks) are inappropriate only in the
realesrgan algo..
screenshot is a small cut from an 4x_realesrgan-x4plus - Upscayled image

### To Reproduce

-

### Version/Commit Hash

2.8.6

### OS Specifics

GTX1070, Windows10 - newest

### Expected Behavior

-

### Screenshots

![Orig A_upscayl_4x_realesrgan-x4plus_Errors](https://github.com/upscayl/upscayl/assets/147054879/8ef5c64f-9bad-473f-81ba-1629c2332936)

**Comment by aaronliu0130** [comment]
Pretty sure this is the fault of the REAL-ESRGAN model, Upscayl is merely a GUI for it. I've also noticed similar blurred details. You can try other models as you said.
