### ISSUE TITLE
Updater Message did't get parsed (shows html code)

### ISSUE THREAD

**Issue by YveIce** [upscayl/upscayl#510]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
--
```

### Describe the Bug

Update Messages shows non parsed html code.

### To Reproduce

start an older version and check update msg. 

### Version/Commit Hash

don't know, as overwritten by update to 2.8.8

### OS Specifics

Windows 10

### Expected Behavior

show a plain text message or styled message

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/42624289/462bcf61-e2de-4d73-9bb0-9bc1197c4135)

**Comment by aaronliu0130** [comment]
What version did you update from? #175 should’ve been fixed already. Could you try installing 2.8.5 and see if this still comes up?

**Comment by NayamAmarshe** [comment]
Yeah, we removed the HTML a long time ago. Your version must be quite old. Sorry for the trouble.
