### ISSUE TITLE
Detect if the output file exists before trying to process it

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#513]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Make the program detect if the output of upscaling exists before trying to run the processing on it.

### Related Problem(s)

The current behavior makes unsupported hardware look something like this:
```sh
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  [object Object]
🐞 BACKEND REPORTED:  📢 Upscayl Command:  <redacted for posperity>
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  [object Object]
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
🐞 BACKEND REPORTED:  📐 Processing Image:  [object Object]
🐞 BACKEND REPORTED:  ❌ Error processing (scaling and converting) the image. Please report this error on GitHub. Error: Input file is missing: <redacted for posperity>
```
If my guess is correct, this is because the Upscayling didn't actually work and produced no output.

**Comment by NayamAmarshe** [comment]
We do have a check:
```
  if (!mainWindow || !originalImage) {
    throw new Error("Could not grab the original image!");
  }
```

but it seems it's not the correct way to check.

I've added an alternative.
