### ISSUE TITLE
Introducing HATL model ,Image Super-Resolution 4x upscaling   NO.1 model, right now 

### ISSUE THREAD

**Issue by Erwin11** [upscayl/upscayl#514]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Introducing HATL model ,it fine tuning with SWIR, paper is here:https://arxiv.org/abs/2205.04437

Real_HAT_GAN_SRx4_sharper.pth  
model:
https://drive.google.com/drive/folders/1HpmReFfoUqUbnAOQ7rvOeNU3uf_m69w0?usp=sharing

offical site:
https://github.com/XPixelGroup/HAT

BENCHMARK
Image Super-Resolution BENCHMARK BY paperswithcode.com
[Image Super-Resolution on Set5 - 4x upscaling NO.1 ](https://paperswithcode.com/sota/image-super-resolution-on-set5-4x-upscaling?p=activating-more-pixels-in-image-super)

[Image Super-Resolution on Set14 - 4x upscaling  NO.1 ](https://paperswithcode.com/sota/image-super-resolution-on-set14-4x-upscaling?p=activating-more-pixels-in-image-super)

[Image Super-Resolution on Urban100 - 4x upscaling  NO.1 ](https://paperswithcode.com/sota/image-super-resolution-on-urban100-4x?p=activating-more-pixels-in-image-super)

[Image Super-Resolution on Manga109 - 4x upscaling NO.1 ](https://paperswithcode.com/sota/image-super-resolution-on-manga109-4x?p=activating-more-pixels-in-image-super)

in my test, on Anime Upscale , very familiar with R-ESRGAN, but color control would be better ,less false color.
on Real photo , more details on background ,better than R-ESRGAN, R-ESRGAN will draw simple line on the  road.

### Anime: (click for see more details)
![R-ESRGAN的眼睛最好，但是手部有蓝斑](https://github.com/upscayl/upscayl/assets/6300501/badf1f08-b238-474b-afd1-910e56492d57)

![背景网格HAT会出些，R-ESRGAN直接涂抹](https://github.com/upscayl/upscayl/assets/6300501/4939b2b6-f27e-41f3-9b02-8683471d57a5)

### Real photo: (click for see more details)
![HAT最好 HAT sharper添加了耳环 他们的马路都很好，ultra sharp和R-ESRGAN都在乱画马路](https://github.com/upscayl/upscayl/assets/6300501/bf433527-8646-4e25-856a-d0c872c25001)

![遇到主体和背景相似的或者分离的， 背景R-ESRGAN会乱造 马路开始乱造了  HAT 2个都有细节](https://github.com/upscayl/upscayl/assets/6300501/51a2726a-abc9-4dc1-bdfa-3950b03def17)

### Related Problem(s)

add more powerful model

**Comment by aaronliu0130** [comment]
Sorry, but we’re not increasing our file size by 160+ MB just for a model ATM. You can convert it with [these instructions](https://github.com/upscayl/upscayl/wiki/🖥%EF%B8%8F-Model-Conversion-%E2%80%90-Create-more-AI-models!).

**Comment by Erwin11** [comment]
Thanks for reply.
I'm followed these instructions, get this error.
![HAT 现在转不了upscayl 模型](https://github.com/upscayl/upscayl/assets/6300501/acbbcbfb-3f0f-481d-a334-9c6f6f77a196)

I'm sure HAT models base on SWIR,and changes on Transformer with some things in simple words.  it should be  work.
How could I debug & fix that ?
Is NCNN  means https://github.com/Tencent/ncnn ?


_More info_
Here is my node workflow  as the instructions mentioned:
![image](https://github.com/upscayl/upscayl/assets/6300501/3ecded9f-c60e-45c3-a00b-1b407833afe0)

Hers is my config:
![Clipboard - 2023-10-11 10 43 06](https://github.com/upscayl/upscayl/assets/6300501/2046afc7-380c-46fb-9fd0-b2c2ac3f890b)

**Comment by NayamAmarshe** [comment]
It won't work with Upscayl, it seems. It's a totally different algorithm and architecture.

**Comment by Erwin11** [comment]
@NayamAmarshe ok, thanks any way : )
