### ISSUE TITLE
[FEATURE REQUEST] Support Base64 image pasting

### ISSUE THREAD

**Issue by yetbad** [upscayl/upscayl#518]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Thank you for your work.

Use-case: Quick image processing improvement for academic/office work when you need to fix blurry photos of textbooks, presentations, etc.

Most of the time, you simply take screenshots using the snipping tool, which copies them to the clipboard. Then, you paste them into various documents such as Obsidian, Notion, OneNote, etc. However, most of the time, the images are blurry, and it would be efficient to process them through upscaling and then copy/paste the upscaled version.

**Comment by aaronliu0130** [comment]
Weird, this should've been added already even on Windows. In the meantime you can try drag-n-dropping the images.

**Comment by NayamAmarshe** [comment]
We haven't implemented BASE64 image pasting. Pasting images from file manager might work but not BASE64 because they aren't files, just strings of text.

**Comment by SkyLostTR** [comment]
Is there any progress on this? I would love to use the program with a clipboard.
