### ISSUE TITLE
[suggestion] add Upscayle to chocolatey.org

### ISSUE THREAD

**Issue by user4302** [upscayl/upscayl#52]
consider adding it to chocolatey.org
no amazing reason, id just like it there :3
but its linux first so i understand if this is super low priority :D

**Comment by aaronliu0130** [comment]
You may read the docs at https://docs.chocolatey.org/en-us/create/create-packages and create it yourself.

**Comment by NayamAmarshe** [comment]
As you said, our priority and focus is making Upscayl available on Flathub and AppImage Hub first. GitHub as a distribution platform is fine but we want to focus on the Linux desktop distribution platforms primarily :)

**Comment by user4302** [comment]
> You may read the docs at https://docs.chocolatey.org/en-us/create/create-packages and create it yourself.

sounds good, if i do get it all set up ill update this thread.

**Comment by Smart123s** [comment]
I have submitted a package to chocolatey: https://community.chocolatey.org/packages/upscayl
It's currently awaiting review from moderators, which (from my experience) can take up to a month. If you'd like to see something changed regarding the package, feel free to contact me via chocolatey, add a comment to this issue, or open a PR in the source of the package at https://github.com/Smart123s/chocolatey-packages/tree/master/upscayl.

**Comment by aaronliu0130** [comment]
Thanks! I have a minor nitpick though: The icon doesn't appear to be transparent. Could you reupload a transparent one? It can be found at https://github.com/upscayl/upscayl/issues/37#issuecomment-1229383241.
