### ISSUE TITLE
The linux binary file name has a typo resulting in error

### ISSUE THREAD

**Issue by Quesstor** [upscayl/upscayl#521]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
Error: spawn /home/.../upscayl/resources/linux/bin/upscayl-bin ENOENT
```

### Describe the Bug

renaming `resources/linux/bin/upcayl-bin` to `resources/linux/bin/upscayl-bin` fixes the issue, note the missing s in the binary file name.

### To Reproduce

run it on linux

### Version/Commit Hash

542cad6

### OS Specifics

Ubuntu 22.04

**Comment by NayamAmarshe** [comment]
Fixed :D
