### ISSUE TITLE
Upscayl on Windows has no publisher

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#524]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
N/A
```

### Describe the Bug

In the control panel (or settings), Upscayl has no publisher set. This interferes with Winget's ability to detect the package as Upscayl

### To Reproduce

1. Install
2. Open Control Panel → Uninstall a program

### Version/Commit Hash

2.8.6

### OS Specifics

N/A, win11 23H2 25967

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/11874211/266c1d56-5adb-4dca-8074-4f6de571c6b7)

**Comment by NayamAmarshe** [comment]
I'll fix this when we publish on Windows store.

**Comment by jacyscott** [comment]
Why hasn't this been addressed yet?

**Comment by aaronliu0130** [comment]
It has, wdym it hasn't?

![image](https://github.com/upscayl/upscayl/assets/11874211/ab6603ea-f1d5-43d6-868e-324fc11e3275)

**Comment by jacyscott** [comment]
Then why am I seeing this?
![image](https://github.com/upscayl/upscayl/assets/110212112/c46d55af-c081-4cf4-b72d-c3e94de6b4d3)

**Comment by aaronliu0130** [comment]
That's the installer.

**Comment by NayamAmarshe** [comment]
That's because of unsigned build. Probably will stay that way for a while. We'll sign the Windows builds in the future too but it kinda is unnecessary to pay Microsoft just to remove their unsafe warning. Anybody could still publish signed malware.

**Comment by jacyscott** [comment]
> That's because of unsigned build. Probably will stay that way for a while. We'll sign the Windows builds in the future too but it kinda is unnecessary to pay Microsoft just to remove their unsafe warning. Anybody could still publish signed malware.

Perhaps, though it goes without saying that a Windows pop-up stating that the software could put a user's PC at risk doesn't exactly inspire trust.

**Comment by aaronliu0130** [comment]
Pretty much every installer does that. Doing that is not because we don't have a publisher, it's because Windows Defender thinks there's some malware pattern inside it.

**Comment by jacyscott** [comment]
> Pretty much every installer does that.

Most installers don't trigger a warning.

**Comment by aaronliu0130** [comment]
https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro

> Most installers don't trigger a warning.

Then you simply have only been downloading from very popular apps

**Comment by aaronliu0130** [comment]
![image](https://github.com/upscayl/upscayl/assets/11874211/d37ef7d7-3a43-4f3e-8dc1-b1228be88bc4)
There also is this, but as you can see it's a very different warning

**Comment by jacyscott** [comment]
> https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro
> 
> > Most installers don't trigger a warning.
> 
> Then you simply have only been downloading from very popular apps

Most legitimate software doesn't trigger said warning. Does that mean software can't be legitimate if it does? No, but 'most' legitimate software doesn't.

**Comment by aaronliu0130** [comment]
Ugh, how much of this experience do you have? What's the least popular and newest app you've ever installed?

**Comment by jacyscott** [comment]
Are you really suggesting that over half (_most_) legitimate Windows apps that the **majority** of users install aren't digitally signed?

**Comment by aaronliu0130** [comment]
Well, I actually don't have much logic beyond "in my experience a lot of apps do that". In my experience, the majority of users don't install open source apps either.

**Comment by NayamAmarshe** [comment]
I read somewhere that an EV certificate can cost a thousand dollars.

For now, we can just update the instructions for Windows users. The current installation instructions are definitely not correct and Upscayl is most definitely not a 'threat'. It just shows that warning because it was downloaded from the internet.

**Comment by aaronliu0130** [comment]
Usually, clicking "Run anyway" would be enough. The properties dialog thing should only be needed in rare cases.

**Comment by jacyscott** [comment]
> Well, I actually don't have much logic beyond "in my experience a lot of apps do that". In my experience, the majority of users don't install open source apps either.

For the average user, it's viewed as a red flag, but given the cost, I understand why it doesn't have a certificate.

**Comment by jacyscott** [comment]
> Well, I actually don't have much logic beyond "in my experience a lot of apps do that". In my experience, the majority of users don't install open source apps either.

For the average user, it's viewed as a red flag. However, given the cost, I understand why it doesn't have a certificate.
