### ISSUE TITLE
Upscayl EXEC PATH is wrong

### ISSUE THREAD

**Issue by CHJ85** [upscayl/upscayl#53]
The flatpak gives a java error when I click the Upscayl button.

**Comment by NayamAmarshe** [comment]
Some extra details would be nice :)

**Comment by CHJ85** [comment]
@NayamAmarshe This is exclusive to the flatpak version. AppImage works just fine.

**Comment by aaronliu0130** [comment]
First of all this is a javascript error.
What operating system(aka distro) is this?

**Comment by CHJ85** [comment]
Ubuntu. Shouldn't matter though, as flatpak is isolated from the rest of the system.

**Comment by NayamAmarshe** [comment]
> Ubuntu. Shouldn't matter though, as flatpak is isolated from the rest of the system.

Working just fine on ZorinOS (based on Ubuntu 20.04). There's possibly something wrong with your system configuration or the path you're using. ENOENT error was in development v1.0, we fixed it already before release.

![image](https://user-images.githubusercontent.com/25067102/188273433-abeeec87-b100-40c9-9d43-5ef28f17e968.png)

**Comment by winsomehax** [comment]
I'm seeing the same thing with both the flatpak and the appimage versions.  Distro:

>lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

NVIDIA 1060 6GB VRAM
AMD Ryzen 5 1600 Six-Core Processor (family: 0x17, model: 0x1, stepping: 0x1) - 16GB RAM

**Comment by NayamAmarshe** [comment]
I'll need a full trace.
Run upscayl from the commandline and post the results.

**Comment by winsomehax** [comment]
> I'll need a full trace. Run upscayl from the commandline and post the results.

**APPIMAGE:**

$ ./Upscayl-1.2.0.AppImage 

ICON:  /tmp/.mount_UpscayQ4mxiW/resources/app.asar/main/icon.png
Checking for update
Update for version 1.2.0 is not available (latest version: 1.2.0, downgrade is disallowed).
/home/gdd/split-i5-2.jpg
/home/gdd/Desktop
🚀 => ipcMain.on => outputDir /home/gdd/Desktop
PRODUCTION? : false
EXEC:  /Resources/bin/upscayl


**FLATPAK**

$ flatpak run org.upscayl.app

[3 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/lib/org.upscayl.app/upscayl --type=zygote --enable-crashpad
Gtk-Message: 17:20:54.274: Failed to load module "xapp-gtk3-module"
Gtk-Message: 17:20:54.274: Failed to load module "appmenu-gtk-module"
[3:0903/172054.327607:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0903/172054.327660:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
ICON:  /app/lib/org.upscayl.app/resources/app.asar/main/icon.png
APPIMAGE env is not defined, current application is not an AppImage
/home/gdd/split-i5-2.jpg
/home/gdd/Desktop
🚀 => ipcMain.on => outputDir /home/gdd/Desktop
PRODUCTION? : false
EXEC:  /Resources/bin/upscayl

**Comment by CHJ85** [comment]
@winsomehax I'm on same version and distro as you.
However like I said, my appimage works fine. Very strange.
But then I guess it's related to the latest version of Ubuntu, because it's working just fine according to @NayamAmarshe on zorin 20.04.

**Comment by NayamAmarshe** [comment]
> > I'll need a full trace. Run upscayl from the commandline and post the results.
> 
> Two copy/pastes. One for the APPIMAGE version. One for the flatpak. Both give the same end result when Upscayl button is clicked - the ENOENT dialog
> 
> 
> **APPIMAGE:**
> 
> $ ./Upscayl-1.2.0.AppImage 
> 
> ICON:  /tmp/.mount_UpscayQ4mxiW/resources/app.asar/main/icon.png
> Checking for update
> Update for version 1.2.0 is not available (latest version: 1.2.0, downgrade is disallowed).
> /home/gdd/split-i5-2.jpg
> /home/gdd/Desktop
> 🚀 => ipcMain.on => outputDir /home/gdd/Desktop
> PRODUCTION? : false
> EXEC:  /Resources/bin/upscayl
> 
> 
> **FLATPAK**
> 
> $ flatpak run org.upscayl.app
> 
> [3 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/lib/org.upscayl.app/upscayl --type=zygote --enable-crashpad
> Gtk-Message: 17:20:54.274: Failed to load module "xapp-gtk3-module"
> Gtk-Message: 17:20:54.274: Failed to load module "appmenu-gtk-module"
> [3:0903/172054.327607:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> [3:0903/172054.327660:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
> ICON:  /app/lib/org.upscayl.app/resources/app.asar/main/icon.png
> APPIMAGE env is not defined, current application is not an AppImage
> /home/gdd/split-i5-2.jpg
> /home/gdd/Desktop
> 🚀 => ipcMain.on => outputDir /home/gdd/Desktop
> PRODUCTION? : false
> EXEC:  /Resources/bin/upscayl
> 
> 
> 

Thanks for the log. Seems like the binary path is totally wrong for some reason. I'm not sure why because we've tested it already and it's working fine for most people too.

I'll see if there's something that can be done about this. It's trying to find upscayl binary in /Resources/bin when it should be looking in a /tmp/.mount_UpscayQ4mxiW/resources/Resources/bin

**Comment by winsomehax** [comment]
> I'll see if there's something that can be done about this. It's trying to find upscayl binary in /Resources/bin when it should be looking in a /tmp/.mount_UpscayQ4mxiW/resources/Resources/bin

Thanks.

for info:

The flatpak was installed by downloading it from github and then using flatpak install Upscayl-1.2.0-x86_64.flatpak

The AppImage was downloaded from github. Then chmod u+x Upscayl-1.2.0.AppImage and then just executed it.

**Comment by winsomehax** [comment]
Additional:

I followed the development instructions. https://github.com/upscayl/upscayl#development-

I had to apt-get install npm first - which installed a lot of NODEJS stuff.

After going to the cloned folder - cd upscayl

$ npm install
$ npm run start 

And the application works. It does not demonstrate the same ENOENT error and will allow images to be upscaled.

**No idea if this following stuff is useful for diagnosing the packaging issue... but I will include it for completeness:**

I figured it was probably worth trying to build/package it to see what happens.

$ npm run dist
 
will eventually fail with an error:
`
info  - using build directory: /home/gdd/Projects/upscayl/renderer/.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "/home/gdd/Projects/upscayl/next.config.js". Generating map from "./pages"
info  - Launching 11 workers
info  - Copying "public" directory
info  - Exporting (3/3)
Export successful. Files written to /home/gdd/Projects/upscayl/renderer/out
Error: Cannot find module 'fs/promises'
Require stack:
- /home/gdd/Projects/upscayl/node_modules/builder-util/out/fs.js
- /home/gdd/Projects/upscayl/node_modules/builder-util/out/util.js
- /home/gdd/Projects/upscayl/node_modules/electron-builder/out/cli/cli.js
- /home/gdd/Projects/upscayl/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/gdd/Projects/upscayl/node_modules/builder-util/src/fs.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/gdd/Projects/upscayl/node_modules/builder-util/src/util.ts:25:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
`

**Comment by CHJ85** [comment]
@winsomehax Right. So the app works fine, which I've already stated. I'm using the appimage.
But we're talking about the pre-built package.
Obviously if you build it yourself it'll work just fine.

**Comment by winsomehax** [comment]
Interesting... I removed nodejs from this version ubuntu after I realised that the apt-get version is way back at v12. Instead I installed "node" from the snap store which is Node v16. That appeared to be the cause of the error about "fs/promises" when trying to build. So that's something for anyone trying to build on Ubuntu to note perhaps.

I do have one interesting thing to note with regard to this error.

If I take the release version of 1.2.0 AppImage and move it into the folder: "/home/gdd/Projects/upscayl/dist/"

So

$ cd /home/gdd/Projects/upscayl/dist/
$ ./Upscayl-1.2.0.AppImage

Then it will NOT display the ENOENT error when clicking the Upscayl button. 

If I move it back to my home folder and try to run the AppImage from there... it WILL display the ENOENT failure. Same release AppImage... but it fails depending on where it is in the folder structure.

Hopefully that's one extra bit of data that will help.

**Comment by NayamAmarshe** [comment]
> Interesting... I removed nodejs from this version ubuntu after I realised that the apt-get version is way back at v12. Instead I installed "node" from the snap store which is Node v16. That appeared to be the cause of the error about "fs/promises" when trying to build. So that's something for anyone trying to build on Ubuntu to note perhaps.
> 
> I do have one interesting thing to note with regard to the ENOENT error.
> 
> If I take the release version of 1.2.0 AppImage and move it into the folder: "/home/gdd/Projects/upscayl/dist/"
> 
> So
> 
> $ cd /home/gdd/Projects/upscayl/dist/ $ ./Upscayl-1.2.0.AppImage
> 
> Then it will NOT display the ENOENT error when clicking the Upscayl button.
> 
> If I move it back to my home folder and try to run the AppImage from there... it WILL display the ENOENT failure. Same release AppImage... but it fails depending on where it is in the folder structure.
> 
> Hopefully that's one extra bit of data that will help.

I'll try fixing the path issue, probably caused because of the changes we had to make for the multi-platform release. Will try to fix it in the next release. I'll spin up an Ubuntu VM and see if it causes the same fuss.

**Comment by v3ss0n** [comment]
Both flatpak and appimage versions have problems for me . I tried building from scratch and all is fine.

**Comment by NayamAmarshe** [comment]
> Both flatpak and appimage versions have problems for me . I tried building from scratch and all is fine.
> 
> BTW I use arch.

Does your compiled AppImage still work when you put it in another directory?

**Comment by v3ss0n** [comment]
I run directly from code , haven't build APPimage

**Comment by NayamAmarshe** [comment]
Does v1.5 change anything?

If this issue is machine-specific and I can't reproduce it, I can't really help, sorry :(

**Comment by winsomehax** [comment]
I've downloaded the 1.5 release.

Difference in behaviour: when clicking "Upscayl" I no longer see an exception, but the binary executable doesn't run. The application just sits with a spinning wheel saying "Hold on" and this never completes. I've waited for 2 hours for it to complete.

Effectively no difference. It still cannot find the executable but does not display an error now.

Terminal Output:
`
🚀 Icon Path:  /tmp/.mount_Upscayu23TGz/resources/app.asar/main/icon.png

🚀 Development Mode? : false

🚀 RS Executable Path:  /home/bin/upscayl-

🚀 Models:  /home/models

Checking for update

Update for version 1.5.0 is not available (latest version: 1.5.0, downgrade is disallowed).

/home/gdd/FSp8XC1XEAYTwyt.jpeg

FSp8XC1XEAYTwyt.jpeg
`

If I look at the folder:  

/tmp/.mount_Upscayu23TGz/resources/bin

while the application is running I can see all of the AppImage stuff - the binary applications for "upscayl-realesrgan" etc. When i close the application that unpacked resources is cleaned up obviously

Perhaps the executable path needs to be based off the same temporary source as the icon path "/tmp/.mount_Upscayu23TGz/" not the current method.

**Comment by NayamAmarshe** [comment]
> I've downloaded the 1.5 release.
> 
> Difference in behaviour: when clicking "Upscayl" I no longer see an exception, but the binary executable doesn't run. The application just sits with a spinning wheel saying "Hold on" and this never completes. I've waited for 2 hours for it to complete.
> 
> Effectively no difference. It still cannot find the executable but does not display an error now.
> 
> Terminal Output: ` 🚀 Icon Path: /tmp/.mount_Upscayu23TGz/resources/app.asar/main/icon.png
> 
> 🚀 Development Mode? : false
> 
> 🚀 RS Executable Path: /home/bin/upscayl-
> 
> 🚀 Models: /home/models
> 
> Checking for update
> 
> Update for version 1.5.0 is not available (latest version: 1.5.0, downgrade is disallowed).
> 
> /home/gdd/FSp8XC1XEAYTwyt.jpeg
> 
> FSp8XC1XEAYTwyt.jpeg `
> 
> If I look at the folder:
> 
> /tmp/.mount_Upscayu23TGz/resources/bin
> 
> while the application is running I can see all of the AppImage stuff - the binary applications for "upscayl-realesrgan" etc. When i close the application that unpacked resources is cleaned up obviously
> 
> Perhaps the executable path needs to be based off the same temporary source as the icon path "/tmp/.mount_Upscayu23TGz/" not the current method.

Yep, it shouldn't be this way. Wish I could reproduce this. I think the app is reporting the wrong path. Will see if I can find a fix.

**Comment by winsomehax** [comment]
> 

Here's a bit of interesting info. I had a thought... perhaps it's the home folder that's causing the issue.

$ cd /home/gdd

$ mkdir x

$ mv Upscale-1.5.AppImage x

$ cd x

$ ./Upscale-1.5.AppImage

You do not get the incorrect folder for binaries any longer.  The application works correctly and finds the binaries and upscales just fine. Very odd. 

Possibility

The package used for finding the binaries in electron isn't handling "~" (tilde) very well. The people who think it's working may well not be using it from their home folder.

Maybe you could try moving the AppImage to your home folder and running from there to see what happens on your end.

**Comment by NayamAmarshe** [comment]
> > 
> 
> Here's a bit of interesting info. I had a thought... perhaps it's the home folder that's causing the issue.
> 
> $ cd /home/gdd
> 
> $ mkdir x
> 
> $ mv Upscale-1.5.AppImage x
> 
> $ cd x
> 
> $ ./Upscale-1.5.AppImage
> 
> You do not get the incorrect folder for binaries any longer. The application works correctly and finds the binaries and upscales just fine. Very odd.
> 
> Possibility
> 
> Maybe the package used for finding the binaries (app-root-dir) for electron isn't handling "~" (tilde) very well - just a guess - or something else about the home folder is wrong. the repo for app-root-dir doesn't appear to have been updated since 2015.
> 
> Also the people who think it's working may well not be using it from their home folder.
> 
> Maybe you could try moving the AppImage to your home folder and running from there to see what happens on your end.

Very interesting. I suppose we need to remove that old libary and find an alternative. I'll fix the build as soon as I get time, been a lot busy with other things so sorry about that.

**Comment by NayamAmarshe** [comment]
Could you guys please test this build: https://link.storjshare.io/jw34l25j4e27dpthmpi5tpy426kq/drive%2FUpscayl-1.5.5.AppImage

**Comment by winsomehax** [comment]
Downloaded 1.5.5 from your link

It seems to be working ok when that AppImage is launched from the home folder. 

Below is a copy of the console output when upscaling using that version from the home folder. The RS Executable Path is correct.

For completeness I also tried it from other folders and those worked too.

Just out of curiosity... what did the problem turn out to be.

Thanks.

******

```
$ ./Upscayl-1.5.5.AppImage 

/tmp/.mount_UpscayR3ZzfK/resources/app.asar

🚀 Icon Path:  /tmp/.mount_UpscayR3ZzfK/resources/app.asar/main/icon.png

🚀 Development Mode? : false

🚀 RS Executable Path:  /tmp/.mount_UpscayR3ZzfK/resources/bin/upscayl-

🚀 Models:  /tmp/.mount_UpscayR3ZzfK/resources/models

Checking for update

Update for version 1.5.5 is not available (latest version: 1.5.0, downgrade is disallowed).

/home/gdd/E47Jyi9VUAUB8oK.jpeg

E47Jyi9VUAUB8oK.jpeg

🚀 => upscayl.stderr.on => stderr.toString() [0 NVIDIA GeForce GTX 1060 6GB]  queueC=2[8]  queueG=0[16]  
queueT=1[2]

🚀 => upscayl.stderr.on => stderr.toString() 

[0 NVIDIA GeForce GTX 1060 6GB]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0

[0 NVIDIA GeForce GTX 1060 6GB]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1

[0 NVIDIA GeForce GTX 1060 6GB]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚀 => upscayl.stderr.on => stderr.toString() [1 llvmpipe (LLVM 13.0.1, 256 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]

[1 llvmpipe (LLVM 13.0.1, 256 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0

[1 llvmpipe (LLVM 13.0.1, 256 bits)]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1

[1 llvmpipe (LLVM 13.0.1, 256 bits)]  subgroup=8  basic=1  vote=1  ballot=1  shuffle=0

🚀 => upscayl.stderr.on => stderr.toString() 0.00%

🚀 => upscayl.stderr.on => stderr.toString() 3.33%

🚀 => upscayl.stderr.on => stderr.toString() 6.67%

🚀 => upscayl.stderr.on => stderr.toString() 10.00%

🚀 => upscayl.stderr.on => stderr.toString() 13.33%

🚀 => upscayl.stderr.on => stderr.toString() 16.67%

🚀 => upscayl.stderr.on => stderr.toString() 20.00%

🚀 => upscayl.stderr.on => stderr.toString() 23.33%

🚀 => upscayl.stderr.on => stderr.toString() 26.67%

🚀 => upscayl.stderr.on => stderr.toString() 30.00%

🚀 => upscayl.stderr.on => stderr.toString() 33.33%

🚀 => upscayl.stderr.on => stderr.toString() 36.67%

🚀 => upscayl.stderr.on => stderr.toString() 40.00%

🚀 => upscayl.stderr.on => stderr.toString() 43.33%

🚀 => upscayl.stderr.on => stderr.toString() 46.67%

🚀 => upscayl.stderr.on => stderr.toString() 50.00%

🚀 => upscayl.stderr.on => stderr.toString() 53.33%

🚀 => upscayl.stderr.on => stderr.toString() 56.67%

🚀 => upscayl.stderr.on => stderr.toString() 60.00%

🚀 => upscayl.stderr.on => stderr.toString() 63.33%

🚀 => upscayl.stderr.on => stderr.toString() 66.67%

🚀 => upscayl.stderr.on => stderr.toString() 70.00%

🚀 => upscayl.stderr.on => stderr.toString() 73.33%

🚀 => upscayl.stderr.on => stderr.toString() 76.67%

🚀 => upscayl.stderr.on => stderr.toString() 80.00%

🚀 => upscayl.stderr.on => stderr.toString() 83.33%

🚀 => upscayl.stderr.on => stderr.toString() 86.67%

🚀 => upscayl.stderr.on => stderr.toString() 90.00%

🚀 => upscayl.stderr.on => stderr.toString() 93.33%

🚀 => upscayl.stderr.on => stderr.toString() 96.67%

Done upscaling
```

**Comment by CHJ85** [comment]
@NayamAmarshe That build works fine. Tested both single and batch upscaling.
Great work.
Btw. A bit off-topic here, but during the batch process, some of images gave me a "DECODING ERROR =>". Would be nice to know the filename of these images so that I can troubleshoot the issue. Could this be included in the error message somehow?

**Comment by NayamAmarshe** [comment]
https://github.com/upscayl/upscayl/releases/tag/v1.5.5

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe That build works fine. Tested both single and batch upscaling. Great work. Btw. A bit off-topic here, but during the batch process, some of images gave me a "DECODING ERROR =>". Would be nice to know the filename of these images so that I can troubleshoot the issue. Could this be included in the error message somehow?

It usually throws that error when you have files other than images.

**Comment by CHJ85** [comment]
@NayamAmarshe That explains it then.
Thank you all for your help and contribution.
👍
