### ISSUE TITLE
Update org.freedesktop.Platform dependency for flatpak

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [upscayl/upscayl#54]
It's currently really out of date at 20.08, and requires users to install an extra dep for this flatpak since most apps use 21.08, and some of them are already using the newly released 22.08

**Comment by NayamAmarshe** [comment]
Ok, will update

**Comment by NayamAmarshe** [comment]
Turns out it's electron-builder that uses 20.08, can't update unless they do I guess.

**Comment by Etaash-mathamsetty** [comment]
I would check https://github.com/flathub/com.heroicgameslauncher.hgl, they managed to update the runtime to 22.08.
