### ISSUE TITLE
Double click in empty area to open file

### ISSUE THREAD

**Issue by JanJastrow** [upscayl/upscayl#540]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

I would love if Upscayl could borrow the behavior from Photoshop/Affinity Photo:
If you double click in the large empty area, while no image is currently open, it opens up the `Select Image` dialogue.

**Comment by NayamAmarshe** [comment]
Ok, I'll add that
