### ISSUE TITLE
GPU isn't detected.

### ISSUE THREAD

**Issue by cam12687** [upscayl/upscayl#547]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
🎯 GET_MODELS_LIST:  
🔄 Resetting image paths
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Getting gpuId from localStorage:  0
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  true
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\Downloads\Ada Twist, Scientist (2021) - S01E04_6.png
🐞 BACKEND REPORTED:  📄 Selected File Path:  D:\Downloads\Ada Twist, Scientist (2021) - S01E04_6.png
🖼 Selected Image Path:  D:\Downloads\Ada Twist, Scientist (2021) - S01E04_6.png
📁 Selected Image Directory:  D:\Downloads
🖼 imagePath:  D:\Downloads\Ada Twist, Scientist (2021) - S01E04_6.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  [object Object]
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\Downloads\Ada Twist, Scientist (2021) - S01E04_6.png,-o,D:\Downloads\Ada Twist, Scientist (2021) - S01E04_6_upscayl_4x_ultramix_balanced.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultramix_balanced,-g,0,-f,png
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  [object Object]
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  image upscayl:  vkCreateInstance failed -9

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🔄 Resetting image paths
🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Getting gpuId from localStorage:  0
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0
```

### Describe the Bug

When trying to upscale I get the image is corrupt or the GPU isn't compatible. I did just update my graphics driver before this issue happened. I did notice that it doesn't detect my GPU, so it doesn't get a GPU code.

### To Reproduce

Have the latest Nvidia graphics driver update.  Load an image, and click on upscayl. It should come up with a popup that says either the image is corrupt or incompatible with upscayl. Or the graphics driver is acting funny or incompatible.

### Version/Commit Hash

2.9.1

### OS Specifics

Nvidia GTX 1660, Windows 11, 22H2

### Expected Behavior

The image should have upscaled.

### Screenshots

![Screenshot (9)](https://github.com/upscayl/upscayl/assets/37483191/79697b3c-b47d-41de-8376-b52a693c444c)

**Comment by NayamAmarshe** [comment]
Does 2.8.6 work?

**Comment by aaronliu0130** [comment]
Have you tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting) and setting GPU ID to 1? I'm assuming you've already restarted after the driver update.

**Comment by cam12687** [comment]
Yes, I tried all the common troubleshooting steps. Just tried setting the GPU ID to 1 and still get the same error message. Yes, I restarted after the driver update. Version 2.8.6 also does it, so i believe it's related to the new graphics driver update.
________________________________

**Comment by aaronliu0130** [comment]
https://github.com/nihui/realsr-ncnn-vulkan/issues/18 exists, but you clearly have Windows so I don't know.

**Comment by cam12687** [comment]
Just wanted to update you. I tried reinstalling my graphics driver, and tried to run the image again, and now it works. Installation of the driver must of had an error somewhere.
