### ISSUE TITLE
My UI doesn't have scroll bars 

### ISSUE THREAD

**Issue by Flyingmatthew** [upscayl/upscayl#549]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [X] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Paste the logs

```sh
🔄 Resetting image paths
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Remacri)","value":"remacri"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
🔀 Setting model to remacri
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Remacri)","value":"remacri"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Remacri)","value":"remacri"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to remacri
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Updating Folder Path:  E:\New
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  E:\New
🖼 Selected Folder Path:  E:\New
🔀 Model changed:  realesrgan-x4plus
🔀 Setting model to realesrgan-x4plus
🔀 Model changed:  ultrasharp
🔀 Setting model to ultrasharp
🔀 Model changed:  ultrasharp
🔀 Setting model to ultrasharp
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultrasharp
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0
```

### Describe the Bug

I can't scroll down past 6 models or in the settings page past "setting model to???", and the final step is half covered when in single image mode. It's been like this since I unstailled the program a few weeks ago, I just updated to v.2.9.1 with the same results.
![Screenshot (217)](https://github.com/upscayl/upscayl/assets/88611828/0c478053-f820-44f6-a1d1-a624483a9e9d)
![Screenshot (218)](https://github.com/upscayl/upscayl/assets/88611828/8c449bd2-91b7-4833-9e84-7ab44dd45a84)
![Screenshot (219)](https://github.com/upscayl/upscayl/assets/88611828/9f69c77e-a268-4bdc-a57a-b2b7a7b5035d)

### To Reproduce

No Idea

### Version/Commit Hash

2.9.1

### OS Specifics

Intel(R) UHD Graphics, Microsoft windows 10 version 22H2, build 19045.3570

### Screenshots

![Screenshot (217)](https://github.com/upscayl/upscayl/assets/88611828/85123d39-8725-43f3-9de7-9940e70f1b2d)
![Screenshot (218)](https://github.com/upscayl/upscayl/assets/88611828/643f6bdf-b321-402b-8a4a-20482aac4aa9)
![Screenshot (219)](https://github.com/upscayl/upscayl/assets/88611828/7f697ab4-b64c-4a2b-a3bb-9080415336e3)

**Comment by NayamAmarshe** [comment]
That's a really weird theme. Maybe your OS theme is causing this?

**Comment by Flyingmatthew** [comment]
Changed to Default windows theme and it fixed it. Thanks 😊
