### ISSUE TITLE
Possibility for a Docker Image?

### ISSUE THREAD

**Issue by tomtom215** [upscayl/upscayl#55]
Hello,

Your project is impressive! I see you mention Linux first philosophy and have provided binaries, but I was wondering if you'd make a docker image available?

Thanks!

**Comment by NayamAmarshe** [comment]
I could make a docker file but I'm not sure what purpose would it serve.

**Comment by xinmans** [comment]
any update？

**Comment by nodecentral** [comment]
> I could make a docker file but I'm not sure what purpose would it serve.

My home set up is basically an iPad and a NAS which I run a lot of containers to support video / photo work - having upscayl available via a Docker container make it available to me (as I don’t have windows, mac or Linux).  

If you’re still considering doing it, I’d love to use it..

**Comment by aaronliu0130** [comment]
@nodecentral Upscayl is based on REAL-ERSGAN which already has lots of docker images https://hub.docker.com/search?q=real-esrgan https://hub.docker.com/search?q=esrgan

**Comment by xinmans** [comment]
I try to build myself, but failure



> upscayl@2.5.1 dev
> tsc && electron .
node:events:489
      throw er; // Unhandled 'error' event
      ^
Error: spawn /app/node_modules/electron/dist/electron ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at 3000._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {

  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /app/node_modules/electron/dist/electron',
  path: '/app/node_modules/electron/dist/electron',
  spawnargs: [ '.' ]
}
Node.js v20.1.0

      
Dockerfile 
# Dockerfile

# Use node alpine as it's a small node image
FROM node:alpine

# Create the directory on the node image 
# where our Next.js app will live
RUN mkdir -p /app

# Set /app as the working directory
WORKDIR /app

# Copy package.json and package-lock.json
# to the /app working directory
COPY package*.json ./

# Install dependencies in /app
RUN npm install

# Copy the rest of our Next.js folder into /app
COPY . .

# Ensure port 3000 is accessible to our system
EXPOSE 3000

# Run yarn dev, as we would via the command line 
CMD ["npm", "run", "dev"]

 docker-compose.yml 
version: "3.8"

networks:
  default:

services:
  app:
    container_name: upscayl
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - default

**Comment by nodecentral** [comment]
Hi @xinmans - I’ve not tried it yet, but I followed @aaronliu0130 advice and looked up some on Docker Hub and have this one to try at some point.. https://github.com/wpafbo79/ai-docker/tree/master/real-esrgan
