### ISSUE TITLE
GPU compatibility list addition

### ISSUE THREAD

**Issue by thorsten-schneider** [upscayl/upscayl#550]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

Hello guys,

I saw just that the GPU compatibility list is very small. I use Upscayl on an NVIDIA Quadro P2000 and it works flawlessly. Can we maybe add this to the list?

In case of any questions, feel free to ask.

Best regards,
Thorsten

**Comment by aaronliu0130** [comment]
The Quadro is a dedicated GPU and thus automatically assumed to be compatible
