### ISSUE TITLE
Improve quality of alpha chanel upscaling.

### ISSUE THREAD

**Issue by imagicalFantasy** [upscayl/upscayl#556]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Currently, when we upscale picture, the RGB chanels are upscaled with advanced algorytm. Alpha is preserved but seem upscaled with classic algorytm. No smart upscale for it.

You can turn the alpha chanel as a separate grayscale image and apply same upscaling process than the main image and after the process you could reaply the grayscaled opacity mask as an alpha chanel for the image.

This process don't sound too complicated and could really improve opacity of transparent images.

### Related Problem(s)

Currently alpha chanel is upscaled with classic conventional process.

### Alternatives

Export separated alpha chanel as other file and replace alpha chanel in photoshop using the original image and and exported alpha mask.

**Comment by aaronliu0130** [comment]
Hmm, why would Alpha channels need special smart upscayl?

**Comment by NayamAmarshe** [comment]
> You can turn the alpha chanel as a separate grayscale image and apply same upscaling process than the main image and after the process you could reaply the grayscaled opacity mask as an alpha chanel for the image.

> This process don't sound too complicated and could really improve opacity of transparent images.

This does sound complicated tbh.

This also depends on ncnn, we do not have any C++ ML devs to maintain the repo, we're only able to provide library updates for now. We're trying though, make Upscayl into a bigger project but who knows what happens in the future 🤷🏻

**Comment by imagicalFantasy** [comment]
> > You can turn the alpha chanel as a separate grayscale image and apply same upscaling process than the main image and after the process you could reaply the grayscaled opacity mask as an alpha chanel for the image.
> 
> > This process don't sound too complicated and could really improve opacity of transparent images.
> 
> This does sound complicated tbh.
> 
> This also depends on ncnn, we do not have any C++ ML devs to maintain the repo, we're only able to provide library updates for now. We're trying though, make Upscayl into a bigger project but who knows what will happen in the future 🤷🏻

It's sure that changing how software work require some programming skills and can have some complexity. But if person have the skills the steps are pretty simples :
- If procecess image have PNG alpha chanel :
- Extract alpha chanel as a second grayscale picture
- Upscale process alpha picture
- Upscale process original picture without alpha chanel
- Reaply the alpha picture as alpha chanel of the png

**Comment by NayamAmarshe** [comment]
Closing because we've changed the NCNN backend's image processing.

**Comment by imagicalFantasy** [comment]
It's still unfixed.
