### ISSUE TITLE
Allow selection of lower image scaling (2x, for example) while not post-processing image

### ISSUE THREAD

**Issue by tuxgirl** [upscayl/upscayl#557]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

I've been having trouble upscaling a larger base image, and one of the recommendations I see in the various bugs is to run it without post-processing the image. Unfortunately, that prevents me from using a lower amount of image scaling. 

### Related Problem(s)

Trouble upscaling larger images (someone else filed a bug for this)

**Comment by aaronliu0130** [comment]
See #303. Only specialized models can Upscayl an image directly with certain scales. You can get some by following the instructions [in the wiki](https://github.com/upscayl/upscayl/wiki/%F0%9F%96%A5%EF%B8%8F-Model-Conversion%E2%80%89%E2%80%93%E2%80%89Get-more-models!).
