### ISSUE TITLE
Feature request: add instructions on how to run script using colab.research.google.com

### ISSUE THREAD

**Issue by inglesuniversal** [upscayl/upscayl#56]
I don't have access to a local computer with a GPU so I was thinking if you can provide instructions on how to run your awesome code using colaboratory website.

Thanks

**Comment by NayamAmarshe** [comment]
Please follow Real-ESRGAN's repository for this. Upscayl is using Real-ESRGAN underneath :)

https://github.com/xinntao/Real-ESRGAN/
