### ISSUE TITLE
Crazy juddering menus on Windows 10

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [upscayl/upscayl#563]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [X] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Paste the logs

```sh
🔄 Resetting image paths
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  true
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\<redacted>\Desktop\e.png
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\<redacted>\Desktop\e.png
🖼 Selected Image Path:  C:\Users\<redacted>\Desktop\e.png
📁 Selected Image Directory:  C:\Users\<redacted>\Desktop
🖼 imagePath:  C:\Users\<redacted>\Desktop\e.png
🔤 Extension:  png
🔀 Model changed:  realesrgan-x4plus
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  true
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  [object Object]
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\<redacted>\Desktop\e.png,-o,C:\Users\<redacted>\Desktop\e_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,,-f,png
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  [object Object]
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  image upscayl:  [0 Radeon(TM) RX 460 Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 Radeon(TM) RX 460 Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon(TM) RX 460 Graphics]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 Radeon(TM) RX 460 Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 Radeon(TM) RX 460 Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 Radeon(TM) RX 460 Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon(TM) RX 460 Graphics]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 Radeon(TM) RX 460 Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🐞 BACKEND REPORTED:  image upscayl:  8.33%

🚧 UPSCAYL_PROGRESS:  8.33%

🐞 BACKEND REPORTED:  image upscayl:  16.67%

🚧 UPSCAYL_PROGRESS:  16.67%

🐞 BACKEND REPORTED:  image upscayl:  25.00%

🚧 UPSCAYL_PROGRESS:  25.00%

🐞 BACKEND REPORTED:  image upscayl:  33.33%

🚧 UPSCAYL_PROGRESS:  33.33%

🐞 BACKEND REPORTED:  image upscayl:  41.67%

🚧 UPSCAYL_PROGRESS:  41.67%

🐞 BACKEND REPORTED:  image upscayl:  50.00%

🚧 UPSCAYL_PROGRESS:  50.00%

🐞 BACKEND REPORTED:  image upscayl:  58.33%

🚧 UPSCAYL_PROGRESS:  58.33%

🐞 BACKEND REPORTED:  image upscayl:  66.67%

🚧 UPSCAYL_PROGRESS:  66.67%

🐞 BACKEND REPORTED:  image upscayl:  75.00%

🚧 UPSCAYL_PROGRESS:  75.00%

🐞 BACKEND REPORTED:  image upscayl:  83.33%

🚧 UPSCAYL_PROGRESS:  83.33%

🐞 BACKEND REPORTED:  image upscayl:  91.67%

🚧 UPSCAYL_PROGRESS:  91.67%

🐞 BACKEND REPORTED:  image upscayl:  Upscayl Successful

🚧 UPSCAYL_PROGRESS:  Upscayl Successful

🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
🐞 BACKEND REPORTED:  Skipping png compression for 4x scale
upscaledImagePath:  C:\Users\<redacted>\Desktop\e_upscayl_4x_realesrgan-x4plus.png
💯 UPSCAYL_DONE:  C:\Users\<redacted>\Desktop\e_upscayl_4x_realesrgan-x4plus.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0
```

### Describe the Bug

A terrible juddering menu, as of version 2.9.1. (I had 2.8.6 before.) See the video below. (I managed to upload the video into your 'screenshots' section. So: change that section name?)

### To Reproduce

Uncertain. Try: 1) open upscayl; 2) move the pointer as I did in the aforementioned video.

### Version/Commit Hash

2.9.1

### OS Specifics

Windows 10 Pro - 22H2 (2009: 19045). ATI Radeon RX 460

### Expected Behavior

No mad judder. But is the judder expected behaviour? Relevant too: I found that, by dint I think of your auto-updater, I had two versions of upscayl installed:

![image](https://github.com/upscayl/upscayl/assets/47056543/c5169df5-0ffd-45af-bd62-b8862b0555d7)

I found that after I had managed (with some difficulty) to have only one installation, the juddering seemed less bad than is shown in the video.

### Screenshots

https://github.com/upscayl/upscayl/assets/47056543/69dd4b00-3ba5-4452-9301-029d1a089885

**Comment by aaronliu0130** [comment]
Can you include a cursor in your screen recording, maybe by recording with the game bar or Nvidia Shadowplay? Or is your cursor not visible inside the application either?

**Comment by LinuxOnTheDesktop** [comment]
The point is visible within the application. Yet: I am afraid that I recorded using the program 'VLC', which seems to have no pointer-capturing option; and I have not managed - not yet anyway - to use another recording program. Perhaps I'll try 'Radeon Relive'. In the meantime, _here is an image that shows - the red circle - where the pointer is when the really bad juddering occurs_. (I am finding that the problem is just as bad as it was originally. Moreover, I think that, excepting the really bad juddering - which occurs when I leave the pointer at the location marked by the red circle - the behaviour is by design.)

![image](https://github.com/upscayl/upscayl/assets/47056543/1fe6a44d-9ec1-4938-aada-a424ba0965ec)

**Comment by NayamAmarshe** [comment]
Yes, that is unexpected but also expected because it expands on hover. When you place it in a position where it constantly turns hover on and off, it looks like that.

**Comment by LinuxOnTheDesktop** [comment]
Thank you for the information. Evidently enough, it were best were the application not to do that. I have not encountered another application that did it - which itself suggests that there might be a way to avoid doing it.

**Comment by aaronliu0130** [comment]
I, for one, remember a couple of electron apps also doing that. The only thing I think we can do rn is to eliminate the margin, which doesn't look good

**Comment by NayamAmarshe** [comment]
Fixed in latest commit

**Comment by LinuxOnTheDesktop** [comment]
Wonderful! I have trouble though determining which commit is at issue,
