### ISSUE TITLE
Issue in using it on Ubuntu System

### ISSUE THREAD

**Issue by mawadstore** [upscayl/upscayl#564]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Paste the logs

```sh
This was the error in logs

14:20:34.162 › 🐞 BACKEND REPORTED:  ❌ Error reading original image metadata Error: Input file is missing: /media/sotsys-313/0f54d7fa-d25c-4b07-81c8-f5f3b49b5555/home/sotsys313/Downloads/Downloads/snowyhouse_upscayl_16x_realesrgan-x4plus-anime.png
```

### Describe the Bug

Getting this error while trying to applying upscayling on an image.

### To Reproduce

![image](https://github.com/upscayl/upscayl/assets/141239883/5532fd5e-9261-41e6-a10e-1fef5eeb082c)

### Version/Commit Hash

2.9.1

### OS Specifics

I'm using on a ubuntu 20.04 system on a CPU machine

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/141239883/5532fd5e-9261-41e6-a10e-1fef5eeb082c)

**Comment by NayamAmarshe** [comment]
This will be fixed in 2.9.3

**Comment by aaronliu0130** [comment]
(Note that this is different from the glibc issue)

Can you also put in the lines surrounding that error message?

**Comment by NayamAmarshe** [comment]
> (Note that this is different from the glibc issue)
> 
> Can you also put in the lines surrounding that error message?

Ah ok. We'll need full logs then
