### ISSUE TITLE
Keep colour profile of original image

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#565]
### Discussed in https://github.com/orgs/upscayl/discussions/560

<div type='discussions-op-text'>

<sup>Originally posted by **@p-taylor** November  6, 2023</sup>
Does upscayl honour embedded Colour Profiles or does it strip them out / ignore them during the process?
</div>
<div type='discussions-op-text'>

<sup>Originally posted by **@aaronliu0130** November  6, 2023</sup>
I... don't know, it's handled by REAL-ESRGAN. Perhaps you could do a test?
</div>
<div type='discussions-op-text'>

<sup>Originally posted by **@p-taylor** November  9, 2023</sup>
Unfortunately it converts to a generic sRGB profile.
This caused a colour shift in the images i tested which is not ideal if you care about colour consistency.</div>

**Comment by NayamAmarshe** [comment]
If NCNN is doing this, then it's quite difficult. We'll take a look at this later.

**Comment by p-taylor** [comment]
Unfortunately 2.9.9 still ignores colour profiles.
Caused a colour shift in the images I tested even when using the "DON'T POST-PROCESS IMAGE" setting.
This is a real problem if you care about colour consistency and photography.

**Comment by NayamAmarshe** [comment]
Extremely difficult to integrate without proper tools and libraries :( Sharp didn't work either.
