### ISSUE TITLE
Remote images don't show

### ISSUE THREAD

**Issue by Mardoek53** [upscayl/upscayl#567]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Paste the logs

```sh
🔄 Resetting image paths
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  1
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  1
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/jpeg","filePath":"\\\\192.168.178.164\\Users\\mardo\\WorkSpace\\Graphic Design 02\\AI\\Upscale test 01\\298463_210806932312163_30028920_001a.jpg","extension":"jpg"}
🖼 Setting image path:  \\192.168.178.164\Users\mardo\WorkSpace\Graphic Design 02\AI\Upscale test 01\298463_210806932312163_30028920_001a.jpg
🗂 Setting output path:  \\192.168.178.164\Users\mardo\WorkSpace\Graphic Design 02\AI\Upscale test 01
🖼 imagePath:  \\192.168.178.164\Users\mardo\WorkSpace\Graphic Design 02\AI\Upscale test 01\298463_210806932312163_30028920_001a.jpg
🔤 Extension:  jpg
⚙️ Setting saveImageAs to png
🔀 Setting model to realesrgan-x4plus
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Setting rememberOutputFolder to false
⚙️ Setting compression to 100%
```

### Describe the Bug

When I drag an image into upscaly, it doesn't show.

![2023-11-11](https://github.com/upscayl/upscayl/assets/41394112/aba1bf22-149e-4694-94b0-8c41ee161f8c)

Windows 11 Home

23H2 22631.2506

![GPU 2](https://github.com/upscayl/upscayl/assets/41394112/ed664824-c29a-41d4-8528-086406bff69d)

![GPU 1](https://github.com/upscayl/upscayl/assets/41394112/1336c1e0-4ca7-4472-8d23-918fa9c0f8b4)

### To Reproduce

?

### Version/Commit Hash

2.9.1

### OS Specifics

Windows 11

### Expected Behavior

Show image

**Comment by NayamAmarshe** [comment]
You're loading from an external server. It's not possible for Upscayl to fetch images like that.

**Comment by aaronliu0130** [comment]
Still, thanks for filling out the template!

**Comment by Mardoek53** [comment]
Thank you for your fast reply.

I've a new PC running on Win 11 and I wanted to access the "Workspace" folder easier from the file explorer, so I added this folder to the file explorer as a network location. 

I just tried to drag the image into Upscayl from the "original" "Workspace" folder and now the image IS displayed. 

That solves my problem, so thanks!

**Comment by aaronliu0130** [comment]
I guess we won't be adding remote functionality
