### ISSUE TITLE
Drag & Drop/Select Multiple Files

### ISSUE THREAD

**Issue by I-Wings-I** [upscayl/upscayl#568]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

I would love to be able to Drag & Drop in multiple files or select multiple files, as the batch Upscayl seems to be a bit hit-and-miss most of the time when getting it to upscale a lot of files, would be nice to control it more with which files goes in and have options like the Double Upscayl on for every file.

**Comment by NayamAmarshe** [comment]
Probably gonna add this later.

**Comment by NayamAmarshe** [comment]
This is quite a complicated to handle for the backend, since it doesn't support multiple paths.

Maybe we'll revisit this later.

**Comment by katarzyna-art** [comment]
![Image](https://github.com/user-attachments/assets/e53b9b68-6c2b-459c-9b92-129227a06a35)
