### ISSUE TITLE
vkAllocateMemory failed -2

### ISSUE THREAD

**Issue by gregfr** [upscayl/upscayl#57]
Greetings

I'm trying to use UPscayl but whatever the image I try, I get this error:

```
vkAllocateMemory failed -2
```

What did I miss?

Thanks in advance

Upscayl version 1.2.0 appimage
Vulkan Instance Version: 1.1.114

**Comment by NayamAmarshe** [comment]
It just means you ran out of memory. Vulkan is trying to allocate memory but is failing because it's exceeding your hardware limits. Can't do anything about this, sorry :(

**Comment by NayamAmarshe** [comment]
> What memory? the GPU's or the main?

GPU

**Comment by sarisarinyama** [comment]
It worked fine in 2.0.1, but this version says there is not enough memory.

**Comment by aaronliu0130** [comment]
Are you sure you have the same amount of memory?

**Comment by sarisarinyama** [comment]
I'm sorry. It was due to the fact that I tried to use it right after updating and selected a model that did not exist in the latest version. I re-selected the model and it worked.
