### ISSUE TITLE
upscaling already high res image breaks program

### ISSUE THREAD

**Issue by BrandonBoshuis** [upscayl/upscayl#572]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [X] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Paste the logs

```sh
last part of log just says:

🐞 BACKEND REPORTED:  image upscayl:  57,05%

🚧 UPSCAYL_PROGRESS:  57,05%

🐞 BACKEND REPORTED:  image upscayl:  57,10%

🚧 UPSCAYL_PROGRESS:  57,10%

🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
🐞 BACKEND REPORTED:  Skipping png compression for 4x scale
upscaledImagePath:  E:\16k%20img_upscayl_4x_realesrgan-x4plus.png
💯 UPSCAYL_DONE:  E:\16k%20img_upscayl_4x_realesrgan-x4plus.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0
```

### Describe the Bug

Im trying to upscale a 12326x6933 to 49304x27732 for just some extra detail but the program just stops at ~50% and goes to the part where it show original/upscayled. in the original/upscayled the original image shows but the upscayled one does not.

### To Reproduce

upscale high resolution image

### Version/Commit Hash

2.9.1

### OS Specifics

GTX 1060, Windows 10

### Expected Behavior

It should have upscaled correctly

### Screenshots

I got no screenshots, and either way, there is not much to see.

**Comment by aaronliu0130** [comment]
Is there any output at  E:\16k img_upscayl_4x_realesrgan-x4plus.png?

**Comment by f3k-tech** [comment]
I experienced the same issue when trying to upscale a 13k image. Version 2.9.5

**Comment by aaronliu0130** [comment]
Logs, please

**Comment by NayamAmarshe** [comment]
Could it be the % sign in the file name?

**Comment by aaronliu0130** [comment]
Not sure what happened with the bot on Jan 21
