### ISSUE TITLE
My software can't process the pictures

### ISSUE THREAD

**Issue by taiguguai** [upscayl/upscayl#577]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [X] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Paste the logs

```sh
🔄 Resetting image paths
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\20231125194923.png
🖼 Selected Image Path:  D:\20231125194923.png
📁 Selected Image Directory:  D:
🖼 imagePath:  D:\20231125194923.png
🔤 Extension:  png
🐞 BACKEND REPORTED:  📄 Selected File Path:  D:\20231125194923.png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  [object Object]
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\20231125194923.png,-o,D:\20231125194923_upscayl_4x_realesrgan-x4plus-anime.png,-s,4,-m,D:\software\Upscayl\resources\models,-n,realesrgan-x4plus-anime,,,-f,png
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  [object Object]
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
🐞 BACKEND REPORTED:  Skipping png compression for 4x scale
upscaledImagePath:  D:\20231125194923_upscayl_4x_realesrgan-x4plus-anime.png
💯 UPSCAYL_DONE:  D:\20231125194923_upscayl_4x_realesrgan-x4plus-anime.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0
```

### Describe the Bug

Unable to process the picture, the picture becomes small

### To Reproduce

I don't know how you can reproduce the failure, but in the process, my computer has reinstalled the system, and it works fine before the installation, but not after that

### Version/Commit Hash

291

### OS Specifics

GPU：intel(R) lris(R) Xe Graphics system：Windows 11 23H2

### Screenshots

![bug](https://github.com/upscayl/upscayl/assets/152018253/92d3aa8e-68c5-46a5-87b2-f4a066b2b912)

**Comment by aaronliu0130** [comment]
Forget the preview, are you sure that there is no output in the folder you put the images in?

**Comment by taiguguai** [comment]
i am sure.

Aaron Liu ***@***.***> 于 2023年11月26日周日 01:45写道：

**Comment by aaronliu0130** [comment]
Are you sure you've tried the GPU ID thing?

**Comment by aaronliu0130** [comment]
Not sure what's causing the problem, @NayamAmarshe any thoughts?

**Comment by aaronliu0130** [comment]
They haven't filled in any of the details. Are you sure you have updated all the drivers and tried the common troubleshooting steps? The simplest explanation would be that the graphics aren't supported.

**Comment by NayamAmarshe** [comment]
It's as if the upscaling never happens. I don't see any output from upscayl-bin

**Comment by NayamAmarshe** [comment]
Maybe 2.9.4 will fix it

**Comment by taiguguai** [comment]
The glitch disappeared inexplicably, and now everything is fine with the software...
