### ISSUE TITLE
When setting a single image to be enlarged by a factor of 2, the result is indeed a 2x enlargement. However, when processing images in batches, regardless of the settings, the enlargement appears to be 4x. How should I configure the settings to achieve a 2x enlargement for batch processing?

### ISSUE THREAD

**Issue by leehsincn** [upscayl/upscayl#578]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Paste the logs

```sh
When setting a single image to be enlarged by a factor of 2, the result is indeed a 2x enlargement. However, when processing images in batches, regardless of the settings, the enlargement appears to be 4x. How should I configure the settings to achieve a 2x enlargement for batch processing?
```

### Describe the Bug

When setting a single image to be enlarged by a factor of 2, the result is indeed a 2x enlargement. However, when processing images in batches, regardless of the settings, the enlargement appears to be 4x. How should I configure the settings to achieve a 2x enlargement for batch processing?

### To Reproduce

When setting a single image to be enlarged by a factor of 2, the result is indeed a 2x enlargement. However, when processing images in batches, regardless of the settings, the enlargement appears to be 4x. How should I configure the settings to achieve a 2x enlargement for batch processing?

### Version/Commit Hash

2.8.6

### OS Specifics

win10

**Comment by NayamAmarshe** [comment]
Fix coming in v2.9.4

**Comment by aaronliu0130** [comment]
Are we sure that this isn't a duplicate of #574?

**Comment by NayamAmarshe** [comment]
> Are we sure that this isn't a duplicate of #574?

It was a bug I noticed today. PNG wouldn't output anything other than 4x in batch mode.
So what I've done now is, a new temp folder will be used with the original files copied in there.
