### ISSUE TITLE
Can I directly replace the original image?

### ISSUE THREAD

**Issue by leehsincn** [upscayl/upscayl#579]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Can I directly replace the original image?

**Comment by NayamAmarshe** [comment]
No, this wasn't added as a feature because it's better to be safe than sorry 😅
