### ISSUE TITLE
Nvidia GPUs returns DECODING ERROR (except for Fast Real-ESRGAN)

### ISSUE THREAD

**Issue by ElTioRata** [upscayl/upscayl#581]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [X] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Paste the logs

```sh
🔄 Resetting image paths
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  E:\Carpeta piola\Fondos de pantalla\6798062-hdr-wallpaper.jpg
🐞 BACKEND REPORTED:  📄 Selected File Path:  E:\Carpeta piola\Fondos de pantalla\6798062-hdr-wallpaper.jpg
🖼 Selected Image Path:  E:\Carpeta piola\Fondos de pantalla\6798062-hdr-wallpaper.jpg
📁 Selected Image Directory:  E:\Carpeta piola\Fondos de pantalla
🖼 imagePath:  E:\Carpeta piola\Fondos de pantalla\6798062-hdr-wallpaper.jpg
🔤 Extension:  jpg
🐞 BACKEND REPORTED:  📁 Updating Folder Path:  C:\Users\Marcelo\Desktop
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\Marcelo\Desktop
🗂 Setting Output Path:  C:\Users\Marcelo\Desktop
🧠 Remembering Output Folder:  C:\Users\Marcelo\Desktop
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  [object Object]
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,E:\Carpeta piola\Fondos de pantalla\6798062-hdr-wallpaper.jpg,-o,C:\Users\Marcelo\Desktop\6798062-hdr-wallpaper_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,,-f,png
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  [object Object]
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  image upscayl:  [0 NVIDIA GeForce GTX 1060 3GB]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce GTX 1060 3GB]  bugsbn1=0  bugbilz=160  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 1060 3GB]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 1060 3GB]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce GTX 1060 3GB]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce GTX 1060 3GB]  bugsbn1=0  bugbilz=160  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 1060 3GB]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 1060 3GB]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  0,00%

🚧 UPSCAYL_PROGRESS:  0,00%

🐞 BACKEND REPORTED:  image upscayl:  vkWaitForFences failed -4

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkWaitForFences failed -4

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
🔄 Resetting image paths
🐞 BACKEND REPORTED:  image upscayl:  1,14%

🚧 UPSCAYL_PROGRESS:  1,14%

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0
```

### Describe the Bug

Title. All of them used to work previously (can't recall which version).

### To Reproduce

Try to upscale anything with a model that isn't Fast Real-ESRGAN.

### Version/Commit Hash

v2.9.1

### OS Specifics

GTX 1060 · Windows 10 21H2

**Comment by NayamAmarshe** [comment]
Quite strange.
Seems like a vulkan issue: vkWaitForFences failed -4

**Comment by moh21amed** [comment]
I have the same problem, my internal UHD 620 graphics card works on all model but my mx150 don't work unless i choose fast real esrgan, i am using the latest nvidea driver and tried all recommended troublshooting and here is my full log
`🔄 Resetting image paths
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  0
🔀 Setting model to 
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\MEA\Downloads\a.png
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\MEA\Downloads\a.png
🖼 Selected Image Path:  C:\Users\MEA\Downloads\a.png
📁 Selected Image Directory:  C:\Users\MEA\Downloads
🖼 imagePath:  C:\Users\MEA\Downloads\a.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  [object Object]
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\MEA\Downloads\a.png,-o,C:\Users\MEA\Downloads\a_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-g,0,-f,png
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  [object Object]
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  image upscayl:  [0 NVIDIA GeForce MX150]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce MX150]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce MX150]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 NVIDIA GeForce MX150]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 Intel(R) UHD Graphics 620]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) UHD Graphics 620]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 Intel(R) UHD Graphics 620]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/0
[1 Intel(R) UHD Graphics 620]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce MX150]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce MX150]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce MX150]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 NVIDIA GeForce MX150]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 Intel(R) UHD Graphics 620]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) UHD Graphics 620]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 Intel(R) UHD Graphics 620]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/0
[1 Intel(R) UHD Graphics 620]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  vkWaitForFences failed -4

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkWaitForFences failed -4

🔄 Resetting image paths
🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
🐞 BACKEND REPORTED:  image upscayl:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🛑 Stopping Upscayl
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  true
🐞 BACKEND REPORTED:  🛑 Stopping Upscaling Process 15056
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  0
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0`

**Comment by aaronliu0130** [comment]
Perhaps a Nvidia issue…

**Comment by NayamAmarshe** [comment]
I think the older cards like 1060, MX150 and 1050 have issues with Vulkan due to the outdated drivers.

**Comment by Ati1707** [comment]
> I think the older cards like 1060, MX150 and 1050 have issues with Vulkan due to the outdated drivers.

The 1060 is still getting updates. I am using it but the 6GB version and Upscayl v2.9.4 works fine on the latest driver.
Maybe the user who created the issue didn't update his card. The latest driver is 546.17.

**Comment by aaronliu0130** [comment]
Well, they claim they have attempted troubleshooting steps which includes updating drivers

**Comment by ElTioRata** [comment]
Issue should be solved now, it works again, it could've been some driver related issue that was solved on the latest version as of typing this comment.

**Comment by ElTioRata** [comment]
Tried upscaling today and the issue is back for some reason.

**Comment by ElTioRata** [comment]
Okay, tried upscaling today, it worked again, looks like it's an issue that occurs at random because once I restarted the program and upscaled the same image, the issue was back.

**Comment by aaronliu0130** [comment]
uhhhhh

Maybe related to #258 ?

**Comment by ElTioRata** [comment]
Could be the same issue that you just linked. Although I didn't find any comment of the author trying other upscaling models.

**Comment by aaronliu0130** [comment]
(you can comment to say it's still happening)

**Comment by yl4070** [comment]
I had the same issue earlier. Then, I found out that's because the GPU number doesn't match the number from VulkanCapsViewer. Normally, the dedicate GPU will be number 1, but it's 2 in this case.

**Comment by aaronliu0130** [comment]
I don't think that's the same issue. Does Fast Real-ESRGAN also work for you with GPU ID 1?

**Comment by yl4070** [comment]
Yes, it does, only Fest Real-ESRGAN works for GPU 1, and everything works for GPU 0.  Here's my GPUs.
![image](https://github.com/upscayl/upscayl/assets/87774314/944922e9-60a3-4051-a6fb-d4d2a28b32fb)

**Comment by aaronliu0130** [comment]
@ElTioRata do you have a similar configuration?

**Comment by ElTioRata** [comment]
I don't have an iGPU but it may be the case? @yl4070 Also check if the Digital Art model works for you.

**Comment by aaronliu0130** [comment]
Actually, the logs say that you’re using your Nvidia GPU, so I doubt it’s the same issue

**Comment by yl4070** [comment]
I just realized my issue related to the size of the image. Small images would still work for all models, even if I chose the wrong GPU.  That explains why the Fast Real model is the only one that works. It seems that even though the error msg says DECODING ERROR, it's actually out of memory.

**Comment by NayamAmarshe** [comment]
Closing because OP has a potential solution. Unfortunately, I cannot help much here because we're always updating vulkan and ncnn and that's pretty much the only thing we can do :(

**Comment by sergiufalcusan** [comment]
> I had the same issue earlier. Then, I found out that's because the GPU number doesn't match the number from VulkanCapsViewer. Normally, the dedicate GPU will be number 1, but it's 2 in this case.

how did you check that ? I still have this issue, didn't find a solution yet.

**Comment by yl4070** [comment]
> > I had the same issue earlier. Then, I found out that's because the GPU number doesn't match the number from VulkanCapsViewer. Normally, the dedicate GPU will be number 1, but it's 2 in this case.
> 
> how did you check that ? I still have this issue, didn't find a solution yet.

[VulkanCapsViewer ](https://github.com/SaschaWillems/VulkanCapsViewer?tab=readme-ov-file)has a list of numbered GPU devices, usually starting at integrated GPUs. You should use the number corresponding to your Nvidia GPU in your setting of GPU ID in Upscayl.
