### ISSUE TITLE
Don't create new discussions for new releases

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#583]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

Often enough, instead of reporting through GitHub issues, users report issues they encounter through discussions under a release instead. Since they don't provide computer information, this often requires us to do extra steps. Maybe we should uncheck "Create a discussion for this release" in future releases?

**Comment by NayamAmarshe** [comment]
Ok, I'll do that. Thank you for the suggestion!
