### ISSUE TITLE
I have used upscale for months, and finally decided to upgrade.  Now its broke and won't do batch images (decoding error).  That's why i hate updates.  If its not broke don't fix it.  But I thought it would even be better.  Additionally, under the github releases they removed past versions.  Help!

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#584]
<div type='discussions-op-text'>

<sup>Originally posted by @JonMike12341234 in https://github.com/upscayl/upscayl/discussions/544#discussioncomment-7708100</sup>
I have used upscale for months, and finally decided to upgrade.  Now its broke and won't do batch images (decoding error).  That's why i hate updates.  If its not broke don't fix it.  But I thought it would even be better.  Additionally, under the github releases they removed past versions.  Help!
</div>

**Comment by aaronliu0130** [comment]
@JonMike12341234 Past versions have NOT been removed, I'm not sure what you mean. Also, the changelogs reflect a lot of bug fixes we've done and non-fixes never impede on existing functionality.

Are you sure the folder you're trying to Upscayl is full of images and *only* images? What is the path of your folder, and are you sure it's the same folder that worked before?

**Comment by NayamAmarshe** [comment]
Good idea, I'll try not to create discussions.

**Comment by FoxxMulder** [comment]
I had the same problem when updating, I solved it by going to settings and pressing RESET UPSCAYL, I hope it helps.

**Comment by moritz-t-w** [comment]
> under the github releases they removed past versions.

@aaronliu0130 If you click on the latest release, only that is shown but it looks very similar to the releases page. I've been confused by this too before. Just go to https://github.com/upscayl/upscayl/releases and you can find all versions.

PS:
>  That's why i hate updates. If its not broke don't fix it.

Shit take

**Comment by aaronliu0130** [comment]
@jasonj88 Firstly that’s a different issue, this issue mentions “decoding error”. Please check if you have the latest version and file a new issue

Closing as opener did not respond
