### ISSUE TITLE
It would be good were the 'release notes' button not to prevent in-app upgrade

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [upscayl/upscayl#589]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

When the app detects an available upgrade it offers the options of (1) upgrading and (2) viewing the release notes. 2 is a nice touch yet seemingly selecting it removes the ability to go for 1. That is: after seeing the release notes - which is something one does in order to decide whether to upgrade - one can no longer . . upgrade. I suggest that in one way or another the upgrade option remain visible. [EDITED in order to fix a typo.]

### Related Problem(s)

If one decides to upgrade, then one must restart the app, or download manually.

**Comment by aaronliu0130** [comment]
Should be shipped but since we don't have another update yet we don't know if it works

**Comment by LinuxOnTheDesktop** [comment]
Thanks, though I don't see the change within [the changelog](https://github.com/upscayl/upscayl/compare/v2.9.4...v2.9.5).

**Comment by NayamAmarshe** [comment]
Yeah, I didn't have any time to test it so it's not in the new update, sorry.

**Comment by aaronliu0130** [comment]
Funnily enough, the windows 2.9.5 updater doesn't seem to be working :p
