### ISSUE TITLE
Images missing from Wiki

### ISSUE THREAD

**Issue by scottonanski** [upscayl/upscayl#595]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

Images are missing from the Wiki. This makes it difficult for people who aren't as savvy to get thing done.

https://github.com/upscayl/upscayl/wiki/%F0%9F%96%A5%EF%B8%8F-Model-Conversion%E2%80%89%E2%80%93%E2%80%89Get-more-models!

### Screenshots

Nope.

**Comment by NayamAmarshe** [comment]
That's quite strange. Why would GitHub delete the images?

**Comment by NayamAmarshe** [comment]
I opened the wiki again and it seems like a non-issue. The images are working.

**Comment by scottonanski** [comment]
It was weird. Maybe something intermittent?  Anyway, seems to be okay now.

**Comment by aaronliu0130** [comment]
It could be your workplace. I know that certain Schools and China block images and assets on GitHub
