### ISSUE TITLE
Batch processing ---   nearly solved...  

### ISSUE THREAD

**Issue by jasonj88** [upscayl/upscayl#596]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [X] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Paste the logs

```sh
bcvbcvbcvbcb
```

### Describe the Bug

batch process fails when set to jpg format.    ** but does work ** if left at default png. 

### To Reproduce

was getting the same issue with batch processing.   however did notice the files were copied into temp dir ok and the processing appeared to go fine. output directory created.... BUT upon finishing, there were no files in the output directory.

I was trying to figure out the issue and noticed ( by accident ) that IF i left the file format as PNG , everything worked fine.     I wanted jpg but when i switched then i got the same issue again.   So looks like there is issue with writing the output ONLY when set to JPG.   If left as default PNG then all is fine.      Hopefully a quick fix.       

### Version (or commit hash)

2.9.4

### Select your Operating System

Windows

### OS Version

11

### GPU Name

nvidia rtx 3080

### Expected Behavior

should have outputted jpg files after batch process. It works fine for batch if set to output as default png file format

**Comment by aaronliu0130** [comment]
Ah. Could you try 2.9.5?

Please put valid logs next time.

**Comment by jasonj88** [comment]
my bad re logs.        Showing 2.9.4 as win dl ver on the website ?

**Comment by aaronliu0130** [comment]
@NayamAmarshe Is there a way we could make the website always show the latest download? Or maybe embed the GitHub release page?

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe Is there a way we could make the website always show the latest download? Or maybe embed the GitHub release page?

Possibly. I'll try to find a way.

**Comment by aaronliu0130** [comment]
Anyways, download from GitHub releases
