### ISSUE TITLE
Set up google colab option?

### ISSUE THREAD

**Issue by harry-adventurersbg** [upscayl/upscayl#598]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

While we wait for the cloud option to be added can google colab be added as an alternative until then for people without good hardware to try out stuff? It should be similar to the video2x option that they have and google colab is free. The only limit is the time that they have available and the hardware used but it should be still much better than using low end stuff and having to wait for ages for batch processing to complete.

**Comment by aaronliu0130** [comment]
Just use REAL-ESRGAN, read the credits
https://huggingface.co/ai-forever/Real-ESRGAN
