### ISSUE TITLE
Images shouldn’t render with tiles

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#601]
### Discussed in https://github.com/orgs/upscayl/discussions/600

<div type='discussions-op-text'>

<sup>Originally posted by **@happysurf** December 16, 2023</sup>
After looking an upscaled image with your program, I noticed with a zoom of about 600%, that the rendering had been perform with the _Tile parameter_, not set to 0.
I had noticed this problem in some online services images result in the past.

This causes the completion of the image through a series of rendering tiles which however present some very ugly interruptions which you can also notice on the print if you look carefully.

This setting decreases the load of the GPU but the result does not justify this choice in my opinion.
To understand all this, simply go to the model developer's website (Xintao) and try to upscale an image, by setting the Anime model (in my case) and leaving the _Tile parameter_ to 0.

The result will be uniform because the rendering is done only once.
The Tile setting affected also the other Xintao models, still I don't test the other Upscayl models, like ultrasharp or ultramix balanced.

I also attach the explanatory images, the first is with Upscayl (digital art), the second is created on Xintao (anime V6) web site.

Xintao page: https://replicate.com/xinntao/realesrgan?prediction=jxxbf3rb4hqk76wv5uo2ebwlia

![Upscayl](https://github.com/upscayl/upscayl/assets/13637587/f20e3dd8-9bf9-448b-961e-b53160dd9b2b)

![Xintao](https://github.com/upscayl/upscayl/assets/13637587/459fef7f-ceb0-4014-913e-53b7f9f9d78d)

</div>

**Comment by mangandini** [comment]
I'm having the same problem, but for me, the upscaling Image results in (BIG) Tiled/Mosaic artifacts when using some all General Photo models except Real ESRGAN.

Using Upscay 2.95
Macbook Pro - M1 Pro - 16GB Ram


<img width="964" alt="image" src="https://github.com/upscayl/upscayl/assets/660871/cb05cb24-d2ca-4edb-845b-ce8aad2a2b1d">

⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultrasharp
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultrasharp
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  /Users/oscarmanuelmotamangandi/Downloads/paches-guatemalan.jpg
🖼 Selected Image Path:  /Users/oscarmanuelmotamangandi/Downloads/paches-guatemalan.jpg
📁 Selected Image Directory:  /Users/oscarmanuelmotamangandi/Downloads
🖼 imagePath:  /Users/oscarmanuelmotamangandi/Downloads/paches-guatemalan.jpg
🔤 Extension:  jpg
🐞 BACKEND REPORTED:  📄 Selected File Path:  /Users/oscarmanuelmotamangandi/Downloads/paches-guatemalan.jpg
🔀 Model changed:  ultrasharp
🔀 Setting model to ultrasharp
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  ✅ Already upscayled at:  /Users/oscarmanuelmotamangandi/Downloads/paches-guatemalan_upscayl_3x_ultrasharp.jpg
upscaledImagePath:  /Users/oscarmanuelmotamangandi/Downloads/paches-guatemalan_upscayl_3x_ultrasharp.jpg
💯 UPSCAYL_DONE:  /Users/oscarmanuelmotamangandi/Downloads/paches-guatemalan_upscayl_3x_ultrasharp.jpg
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false

**Comment by aaronliu0130** [comment]
@mangandini That is a very different issue (related to #605). Please set your scale to 3.

**Comment by aaronliu0130** [comment]
<div type='discussions-op-text'>

<sup>Originally posted by **@NayamAmarshe** December 17, 2023</sup>
This is a common problem in super resolution and there's nothing we (Upscayl) can do about it for now.
The tiling is a required setting to make sure we don't go out of bounds with the GPU memory, which is extremely easy to do with a custom tile size.

When the tile size is 0 (default), it automatically sets the tile size according to the available GPU memory.
</div>
