### ISSUE TITLE
Continue Upscayling after image crashed

### ISSUE THREAD

**Issue by PatrickZehentbauer** [upscayl/upscayl#604]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

When Batch Upscayling sometimes there are errors on encoding the images in the folder etc.
I think it would be better if the program would automatically continue with the next image and try to upscayl it and instead of throwing an error it should return a list of the pictures which could not be upscayled and maybe why.

(Also i sometimes have the problem that when i batch upscayl, the image does not work, but when i single upscayl it works for the exact same image)

**Comment by NayamAmarshe** [comment]
It must be because of hidden folders or files in your batch upscale folder.

I'd suggest creating a new folder first, then copying the files there and trying it again.

**Comment by PatrickZehentbauer** [comment]
Normally i create a folder and put the images in there, then i use upscayl. after upscayling, i delete all images from the original folder so it should be empty again. if there are hidden folders or files in there, they are created by upscayl.

What about the automatic continue feature?

**Comment by NayamAmarshe** [comment]
> Normally i create a folder and put the images in there, then i use upscayl. after upscayling, i delete all images from the original folder so it should be empty again. if there are hidden folders or files in there, they are created by upscayl.
> 
> What about the automatic continue feature? 

That's certainly on our to-do list :)

**Comment by NayamAmarshe** [comment]
Fixed in v2.11
