### ISSUE TITLE
Increase precision on image scale configuration

### ISSUE THREAD

**Issue by albertowar** [upscayl/upscayl#609]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

The current setting only allows integer values (1x, 2x, 3x, 4x) 
![image](https://github.com/upscayl/upscayl/assets/15969015/a0079991-9ce5-473b-bca2-2237773d2962)

Unfortunately, that doesn't give a lot of flexibility.

The request is to extend this configuration to enable more precise values. For example, it could have a few options in between (0.25, 0.5, 0.75) or, alternatively, an input field to provide the exact value.

### Related Problem(s)

I was trying to upload an scaled image to www.optimalprint.ie to print an A1 photo and realized the file was too large (limit is 30 MB)

The original picture (before scaling) was 6 MB and the scaled picture (2x) ended up at 47 MB.

Having the ability to provide a more precise scaling setting, would allow me to increase the resolution and still meet the file size requirements.

### Alternatives

The alternative would be to play with the compression option to fine tune the final size. However, there is a risk of losing quality on the final image.

**Comment by aaronliu0130** [comment]
In the meantime, you can try resizing the image with your favorite image manip program (MSPaint, Algodoo, etc)

**Comment by NayamAmarshe** [comment]
You can use https://photopea.com to resize and compress images even further. Upscayl not being an image editing program can only provide limited options.
