### ISSUE TITLE
Picking both digital art and general photo options at once

### ISSUE THREAD

**Issue by MrQuerter** [upscayl/upscayl#61]
Hi. Great program and good job for making it so easy to use. Would it be possible to pick both the digital art and general photo options so the upscayl can generate 2 new files? Sometimes you can't tell which would be a better result so you decide to do both of them and then compare it yourself. I currently rename the first one with either "general" or "digital" text at the end of filename and relaunch upscayl to create a second one, but maybe it would be possible to save few seconds and make it an option in the upscayl? Unfortunately I don't know how it would work when it comes to built in comparison tool.

**Comment by NayamAmarshe** [comment]
v1.5 saves the images with proper names so you won't have this problem :)
