### ISSUE TITLE
Ignore desktop.ini when batch processing folder.

### ISSUE THREAD

**Issue by duckduckdog** [upscayl/upscayl#615]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Windows can be a PITA & insist on adding some hidden files to certain folders, currently Upscayl errors out on non-image files _before_ processing what is viable & not after.

Note: Thank you all for your work & time in releasing really easy to use software for free.

**Comment by NayamAmarshe** [comment]
I'll be adding an option to create a temp folder before batch upscayl.

**Comment by DavidEGx** [comment]
IMO, it should ignore anything that is not an image. In any case, carry on with the next file if one fails.

Thanks for the work.

**Comment by NayamAmarshe** [comment]
upscayl-ncnn needs to be updated for this.
