### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by mattpilott** [upscayl/upscayl#62]
<img width="372" alt="Screenshot 2022-09-11 at 9 36 06 pm" src="https://user-images.githubusercontent.com/2401925/189547899-4f359d8d-fbbe-4945-bd9d-b6815de5a707.png">

My settings are image from desktop saving to desktop, tried downloads too but same error.

I'm on an M1 Max

**Comment by NayamAmarshe** [comment]
Hi, you didn't read instructions.

https://github.com/upscayl/upscayl/issues/44
