### ISSUE TITLE
your domain upscayl.org inactivate

### ISSUE THREAD

**Issue by crucifyer** [upscayl/upscayl#629]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Is it expired? I'd better make sure it's not bought by someone else and used for phishing.
thank you.

**Comment by NayamAmarshe** [comment]
Hi, seems like the DNS changes didn't work or will take time to update. Sorry for the trouble.

**Comment by aaronliu0130** [comment]
looks good to me
