### ISSUE TITLE
Error processing image on Win 11 - Image duplicated and rotated

### ISSUE THREAD

**Issue by Erik-Debye** [upscayl/upscayl#63]
![image](https://user-images.githubusercontent.com/18238905/189564745-454fa4eb-336c-4af3-846c-daef9bfea36f.png)

This occurred after processing a different image first. But after restarting the app, it happened again using the same image. 

Image in question: 

![IMG_20211118_151649](https://user-images.githubusercontent.com/18238905/189565260-f4f8b00f-ba87-4a48-9a19-75435d59d4bf.jpg)

**Comment by NayamAmarshe** [comment]
It's only rotated because original image was rotated but you used the photo editor to change the metadata. Real-ESRGAN doesn't handle Metadata very well at the moment.

**Comment by Erik-Debye** [comment]
That was definitely it. Using the photo app to rotate it back to the rotated state it thinks it should be (note the photo was taken regularly? not sure when/how it was rotated)  and it worked fine.
