### ISSUE TITLE
Upscayl is not using 100% of my GPU

### ISSUE THREAD

**Issue by Sayrix** [upscayl/upscayl#631]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Upscayl is only using 8% of my GPU and 10% of my CPU, it should be better if it uses all my GPU and CPU to process the image faster.

**Comment by NayamAmarshe** [comment]
Duplicate of #149
