### ISSUE TITLE
Upscaling process stops at around 69% for 10,000x6,958px JPEG

### ISSUE THREAD

**Issue by Fiech** [upscayl/upscayl#64]
I am currently trying to the original file size of [this file](https://secure.flickr.com/photos/llnl/9403051123/sizes/o/) with upscayl (I tried to compile the CLI version, to only use 2x upscaling, but had no luck as of yet...).

Anyway, the process works with smaller file sizes of the same image, but with this particular file size, it just stops short of 69% (see log)

![image](https://user-images.githubusercontent.com/7039866/190530503-e28acdf9-7156-4f6d-90ff-18f83592b09f.png)

I tried it with both Ubuntu 20.04 with an GTX980 (4GB VRAM) and 32GB of RAM as well as under Ubuntu 22.04 with an RTX A5000 (24GB VRAM) and 1TB of RAM, with the same problem. It just says "Done upscaling" and nothing gets written to disk (also no upscaled image is shown in the GUI)

I have attached the output log.
[upscaly_output.log](https://github.com/upscayl/upscayl/files/9579675/upscaly_output.log)

**Comment by NayamAmarshe** [comment]
It's possibly the size of the image that's causing it. Real-ESRGAN has a few bugs, this is one of those. You can try creating an issue on Real-ESRGAN repository but I doubt it's going to get solved because the activity there is cold.

**Comment by AlexHCC** [comment]
I have the same issue and I have a completely different GPU setup. When I try to upscale a large image x4 it stops at 69% each time, no matter the upscaler used.

**Comment by aaronliu0130** [comment]
Step 2 only changes the model, all of them rely on REAL-ESRGAN which unfortunately has quite a few bugs. The repository is at https://github.com/xinntao/Real-ESRGAN which hasn't had activity since last Sept.
