### ISSUE TITLE
DECODING ERROR: vkCreateInstance failed -9

### ISSUE THREAD

**Issue by GabrielLN88** [upscayl/upscayl#641]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [X] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

Upscayl gives the error in the title when upscaling any image. Cannot set GPU ID as it does not show in the logs.

### To Reproduce

Upscaling an image

### Version (or commit hash)

2.9.5

### Select your Operating System

Windows

### OS Version

11

### GPU Name

RTX 4080

### Paste the logs

```sh
⚙️ Setting saveImageAs to png
🔀 Setting model to realesrgan-x4plus
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Setting rememberOutputFolder to false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  F:\EG Logo for upscayl.jpg
🐞 BACKEND REPORTED:  📄 Selected File Path:  F:\EG Logo for upscayl.jpg
🖼 Selected Image Path:  F:\EG Logo for upscayl.jpg
📁 Selected Image Directory:  F:
🖼 imagePath:  F:\EG Logo for upscayl.jpg
🔤 Extension:  jpg
🐞 BACKEND REPORTED:  📁 Updating Folder Path:  F:\
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  F:\
🗂 Setting Output Path:  F:\
🧠 Remembering Output Folder:  F:\
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"F:","outputDir":"F:\\","fullfileName":"EG Logo for upscayl.jpg","fileName":"EG Logo for upscayl","initialScale":"4","desiredScale":"4","outFile":"F:\\\\EG Logo for upscayl_upscayl_4x_realesrgan-x4plus.png","compression":0}
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,F:\EG Logo for upscayl.jpg,-o,F:\\EG Logo for upscayl_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,F:\Programs\Upscayl\resources\models,-n,realesrgan-x4plus,,,-f,png
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"F:\\Programs\\Upscayl\\resources\\bin\\upscayl-bin","args":["F:\\Programs\\Upscayl\\resources\\bin\\upscayl-bin","-i","F:\\EG Logo for upscayl.jpg","-o","F:\\\\EG Logo for upscayl_upscayl_4x_realesrgan-x4plus.png","-s","4","-m","F:\\Programs\\Upscayl\\resources\\models","-n","realesrgan-x4plus","","","-f","png"]}
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  image upscayl:  vkCreateInstance failed -9

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  F:\EG Logo for upscayl.jpg
🐞 BACKEND REPORTED:  📄 Selected File Path:  F:\EG Logo for upscayl.jpg
🖼 Selected Image Path:  F:\EG Logo for upscayl.jpg
📁 Selected Image Directory:  F:
🖼 imagePath:  F:\EG Logo for upscayl.jpg
🔤 Extension:  jpg
🐞 BACKEND REPORTED:  📁 Updating Folder Path:  F:\
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  F:\
🗂 Setting Output Path:  F:\
🧠 Remembering Output Folder:  F:\
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"F:","outputDir":"F:\\","fullfileName":"EG Logo for upscayl.jpg","fileName":"EG Logo for upscayl","initialScale":"4","desiredScale":"4","outFile":"F:\\\\EG Logo for upscayl_upscayl_4x_realesrgan-x4plus.png","compression":0}
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,F:\EG Logo for upscayl.jpg,-o,F:\\EG Logo for upscayl_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,F:\Programs\Upscayl\resources\models,-n,realesrgan-x4plus,,,-f,png
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"F:\\Programs\\Upscayl\\resources\\bin\\upscayl-bin","args":["F:\\Programs\\Upscayl\\resources\\bin\\upscayl-bin","-i","F:\\EG Logo for upscayl.jpg","-o","F:\\\\EG Logo for upscayl_upscayl_4x_realesrgan-x4plus.png","-s","4","-m","F:\\Programs\\Upscayl\\resources\\models","-n","realesrgan-x4plus","","","-f","png"]}
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  image upscayl:  vkCreateInstance failed -9

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  F:\EG Logo for upscayl.jpg
🐞 BACKEND REPORTED:  📄 Selected File Path:  F:\EG Logo for upscayl.jpg
🖼 Selected Image Path:  F:\EG Logo for upscayl.jpg
📁 Selected Image Directory:  F:
🖼 imagePath:  F:\EG Logo for upscayl.jpg
🔤 Extension:  jpg
🔀 Model changed:  remacri
🔀 Setting model to remacri
🐞 BACKEND REPORTED:  📁 Updating Folder Path:  F:\
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  F:\
🗂 Setting Output Path:  F:\
🧠 Remembering Output Folder:  F:\
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"remacri","gpuId":null,"saveImageAs":"png","inputDir":"F:","outputDir":"F:\\","fullfileName":"EG Logo for upscayl.jpg","fileName":"EG Logo for upscayl","initialScale":"4","desiredScale":"4","outFile":"F:\\\\EG Logo for upscayl_upscayl_4x_remacri.png","compression":0}
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,F:\EG Logo for upscayl.jpg,-o,F:\\EG Logo for upscayl_upscayl_4x_remacri.png,-s,4,-m,F:\Programs\Upscayl\resources\models,-n,remacri,,,-f,png
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"F:\\Programs\\Upscayl\\resources\\bin\\upscayl-bin","args":["F:\\Programs\\Upscayl\\resources\\bin\\upscayl-bin","-i","F:\\EG Logo for upscayl.jpg","-o","F:\\\\EG Logo for upscayl_upscayl_4x_realesrgan-x4plus.png","-s","4","-m","F:\\Programs\\Upscayl\\resources\\models","-n","realesrgan-x4plus","","","-f","png"]}
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  image upscayl:  vkCreateInstance failed -9

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🐞 BACKEND REPORTED:  ❌ INVALID GPU OR FAILED
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Remacri)","value":"remacri"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
```

**Comment by Nolo632** [comment]
Me sucede igual:
⚙️ Setting saveImageAs to png
🔀 Setting model to realesrgan-x4plus
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\1era.jpg
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\1era.jpg
🖼 Selected Image Path:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\1era.jpg
📁 Selected Image Directory:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana
🖼 imagePath:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\1era.jpg
🔤 Extension:  jpg
🔀 Model changed:  realesrgan-x4plus-anime
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting Upscaled Image Path
🏁 DOUBLE_UPSCAYL
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Nolo\Desktop\Fundación Salud\Liliana\1era.jpg,-o,C:\Users\Nolo\Desktop\Fundación Salud\Liliana\1era_upscayl_16x_realesrgan-x4plus-anime.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,,,-f,png
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🔄 Resetting image paths
🚧 DOUBLE_UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\1er-removebg-preview.png
🖼 Selected Image Path:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\1er-removebg-preview.png
📁 Selected Image Directory:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana
🖼 imagePath:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\1er-removebg-preview.png
🔤 Extension:  png
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\1er-removebg-preview.png
🔄 Resetting Upscaled Image Path
🏁 DOUBLE_UPSCAYL
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Nolo\Desktop\Fundación Salud\Liliana\1er-removebg-preview.png,-o,C:\Users\Nolo\Desktop\Fundación Salud\Liliana\1er-removebg-preview_upscayl_16x_realesrgan-x4plus-anime.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,,,-f,png
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🔄 Resetting image paths
🚧 DOUBLE_UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\Dos_atendiendo-removebg-preview.png
🖼 Selected Image Path:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\Dos_atendiendo-removebg-preview.png
📁 Selected Image Directory:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana
🖼 imagePath:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\Dos_atendiendo-removebg-preview.png
🔤 Extension:  png
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\Dos_atendiendo-removebg-preview.png
🔄 Resetting Upscaled Image Path
🏁 DOUBLE_UPSCAYL
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Nolo\Desktop\Fundación Salud\Liliana\Dos_atendiendo-removebg-preview.png,-o,C:\Users\Nolo\Desktop\Fundación Salud\Liliana\Dos_atendiendo-removebg-preview_upscayl_16x_realesrgan-x4plus-anime.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,,,-f,png
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🔄 Resetting image paths
🚧 DOUBLE_UPSCAYL_PROGRESS:  vkCreateInstance failed -9

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
⚙️ Setting rememberOutputFolder to false
⚙️ Setting saveImageAs to png
🔀 Setting model to realesrgan-x4plus
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\ksper3.png
🖼 Selected Image Path:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\ksper3.png
📁 Selected Image Directory:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana
🖼 imagePath:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\ksper3.png
🔤 Extension:  png
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\Nolo\Desktop\Fundación Salud\Liliana\ksper3.png
🔄 Resetting Upscaled Image Path
🏁 DOUBLE_UPSCAYL
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  true
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Nolo\Desktop\Fundación Salud\Liliana\ksper3.png,-o,C:\Users\Nolo\Desktop\Fundación Salud\Liliana\ksper3_upscayl_16x_realesrgan-x4plus.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,,,-f,png
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🔄 Resetting image paths
🚧 DOUBLE_UPSCAYL_PROGRESS:  vkCreateInstance failed -9

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Setting rememberOutputFolder to false

**Comment by aaronliu0130** [comment]
@Nolo632 Could you also go through the checklist above?

I'm not sure what's causing the issue.

**Comment by SeitiYamatsumi** [comment]
I encountered a very similar issue, and it turned out that Vulkan wasn't supported on my GTX 1060 drivers. I resolved this by updating my GPU drivers, which enabled Vulkan support.

To check if Vulkan is supported on your current GPU drivers, follow these steps:

Press (Win+R) and type "dxdiag", then press Enter.
In the Display tab, look for the "Feature Levels" section.
If you don't see anything listed under "Feature Levels," it's likely that you need to update your graphics card drivers.

![dxdiag](https://github.com/upscayl/upscayl/assets/39918309/543362ab-f94a-4117-8f3c-53dfbe58aa21)

**Comment by GabrielLN88** [comment]
Drivers arent the issue, they're fully updated.

![image](https://github.com/upscayl/upscayl/assets/155691700/045a279d-85a5-4ca8-8ab4-e892b0f71d67)

**Comment by GabrielLN88** [comment]
I checked to see if Vulkan drivers were installed by using  Vulkan Caps Viewer. The app didn't even open because it said no Vulkan drivers were installed. I did a reinstall of the drivers and now Upscayl works perfectly.

**Comment by Matloubetoday** [comment]
![Uploading problem.JPG…]()
![Uploading CCd.JPG…]()
Can you help me?

**Comment by NayamAmarshe** [comment]
> ![Uploading problem.JPG…]()
> ![Uploading CCd.JPG…]()
> Can you help me?

Did you try all the troubleshooting steps?
