### ISSUE TITLE
Error processing (scaling and converting) the image. |  Error: Input file is missing: C:\Users\XXX\OneDrive\...Test_PXL_20231226_171_upscayl_1x_realesrgan-x4plus.png

### ISSUE THREAD

**Issue by urmel2024** [upscayl/upscayl#643]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [X] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

During a test upscaling with a small JPG slide, i received after a 92.6% processing an error:
Error processing (scaling and converting) the image. Please report this error on GitHub. 
Error: Input file is missing: C:\Users .....

[2024-01-12 00:27:02.553] [info]  🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
[2024-01-12 00:27:02.569] [info]  📐 Processing Image:  {"originalWidth":6144,"originalHeight":8160,"scale":"1","saveImageAs":"jpg","compressionPercentage":0,"compressionLevel":0}
**[2024-01-12 00:27:02.572] [info]  ❌ Error processing (scaling and converting) the image. Please report this error on GitHub. Error: Input file is missing: C:\Users\XyzXy\OneDrive\Bilder\Kalender 2024\Anflug ZH 26-12-23\Test_PXL_20231226_171_upscayl_1x_realesrgan-x4plus.png
[2024-01-12 00:27:02.573] [info]  🐞 BACKEND REPORTED:  📐 Processing Image:  {"originalWidth":6144,"originalHeight":8160,"scale":"1","saveImageAs":"jpg","compressionPercentage":0,"compressionLevel":0}
**[Fehler File-not-found.txt](https://github.com/upscayl/upscayl/files/13923916/Fehler.File-not-found.txt)**
[2024-01-12 06:40:49.192] [info]  🔄 Resetting image paths**
[2024-01-12 06:40:54.558] [info]  ⚙️ Getting saveImageAs from localStorage:  jpg
[Fehler File-not-found.txt](https://github.com/upscayl/upscayl/files/13923917/Fehler.File-not-found.txt)

### To Reproduce

input path for the JPG File:
C:\\Users\\XyzXy\\OneDrive\\Bilder\\Kalender 2024\\Anflug ZH 26-12-23\\Test_PXL_20231226_171.jpg 
output path for the new upscaled JPG File:
C:\Users\XyzXy\OneDrive\Bilder\Kalender 2024\Anflug ZH 26-12-23

start the program for processing for upscaling after 92.6 % 
after 92.6% processing the error occured ...but during the processing nothing changed nothing happend to the filesystem nothing. 
I tried twice always after 92.6% the error happend ... I have no idea why this gone happend.

### Version (or commit hash)

2.9.5

### Select your Operating System

Windows

### OS Version

Microsoft Windows 11 [Version 10.0.22631.3007] with latest Patch Jan24 applied

### GPU Name

Intel(R) UHD Graphics 620 / Lenovo TP L390

### Expected Behavior

...just correct the sharpness of this test picture.JPG 

### Screenshots

n/a

### Paste the logs

```sh
see complete log file Fehler (above on section "Describe the Bug") File-not-found.txt
```

**Comment by urmel2024** [comment]
Thanks a lot for your assistance

**Comment by urmel2024** [comment]
The input file has a size of 5.45 MB (5’720’971 Bytes). Sorry I have omitted the size of the JPG input file

**Comment by aaronliu0130** [comment]
> Yes, unfortunately. NCNN Vulkan requires a Vulkan-compatible GPU. Upscayl won't work with most iGPUs or CPUs.

A workaround exists for Windows and Linux in #390.

> I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).

![compulsory rickrolls are issued for duplicates of issues and the FAQ and normies who use intelgrated GPUs](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Comment by urmel2024** [comment]
good afternoon Aaron Liu
I tried all the renaming of the .DLL which comes into the game acording "workaround exists for Windows and Linux in https://github.com/upscayl/upscayl/issues/390." hint.
.
I tried shorter naming (no blank in the path and shorted them to a minimum) on the directory and l placing an dummy file "Test_PXL_20231226_171_upscayl_1x_realesrgan-x4plus.png" into the directory path. The upscaling failed still after 92.6%.
Then I changed the dummy output file to .png, the process still failed.
I removed the dummy file ... 
Then I finally, I started the upscale process as Administrator to test once more, but it failed as well.

![grafik](https://github.com/upscayl/upscayl/assets/156413028/9194e2d8-e3ac-4867-adf2-2b0a165551e6)

I still have the problem to understand why there is an an error telling me that Input file is missing: 
**Error: Input file is missing:** C:\tmp\AnflugZH26-12-23\Test_PXL_20231226_171_upscayl_1x_RealESRGAN_General_x4_v3.png
🔄 Resetting image paths


I have attached the different PATH testing Short and long Directory path. And a listing of the installed .DLL Files from Upscayl install directory.
[listDLL save.txt](https://github.com/upscayl/upscayl/files/13931206/listDLL.save.txt)
Different test with long, short path and run with Admin right.
[Test 14-1-24 short PATH Test_PXL_20231226_171.txt](https://github.com/upscayl/upscayl/files/13931215/Test.14-1-24.short.PATH.Test_PXL_20231226_171.txt)

It failed always at 92.6% ...this is very stange, why this is happend ...?

Can please some one explain what is here realy going on and why is the Application telling me theInput file is missing?
That would be great...
Thanks a lot for your assistance
Urmel

**Comment by aaronliu0130** [comment]
Input file is missing means that the upscayling step failed. We have two steps, the upscayling and converting the image to the formats people what. If the upscayling step failed to produce results, the processing step wouldn't have an input file.

**Comment by urmel2024** [comment]
good afternoon  Aaron Liu
thanks a lot for your response. This is clear for me. 
1:
But can you please, tell me which module will try to (re)write this new file.
On my opinion the upscale process was done but we can't write them into the output file. Is this correct? 

2:
I tried the upscale test (upscayl-2.9.7-win) once more a other "new PC TP T570" (to be honest the Graphic CPU is the same i620 as on the original Windows system) latest Windows level, with the same JPG and it failed also exactly on the same percentage with the same message.

3:
On your tip/hint Windows and Linux in https://github.com/upscayl/upscayl/issues/390."
after renaming these .dll and removing them (Renaming the vk_swiftshader.dll library to vulkan-1.dll) ...it worked?
This is a bit strange for me ...? Then I have the same problem at the same percentage, on two different Windows Systems. The shame is that I have no real grafic system :-( 

If you have, may be an explain, for this that would be great 
Thank you so much for your assistance
with best regards
Urmel

**Comment by NayamAmarshe** [comment]
> good afternoon Aaron Liu thanks a lot for your response. This is clear for me. 1: But can you please, tell me which module will try to (re)write this new file. On my opinion the upscale process was done but we can't write them into the output file. Is this correct?
> 
> 2: I tried the upscale test (upscayl-2.9.7-win) once more a other "new PC TP T570" (to be honest the Graphic CPU is the same i620 as on the original Windows system) latest Windows level, with the same JPG and it failed also exactly on the same percentage with the same message.
> 
> 3: On your tip/hint Windows and Linux in #390." after renaming these .dll and removing them (Renaming the vk_swiftshader.dll library to vulkan-1.dll) ...it worked? This is a bit strange for me ...? Then I have the same problem at the same percentage, on two different Windows Systems. The shame is that I have no real grafic system :-(
> 
> If you have, may be an explain, for this that would be great Thank you so much for your assistance with best regards Urmel

It worked because your graphics aren't supported by Upscayl, so the hack worked.

**Comment by urmel2024** [comment]
good afternoon Nayam Amarshe
Thanks a lot for your fast feedback.
...it's hard to read have this feedback. It will be that way.
Will there be in the future be a possibility to support any iGraphics?

The other alternativ will be to use the Cloud Version I guess? 
When it will this version (even Beta) be out?

Thanks a lot for your respone and have a great day
Urmel

**Comment by NayamAmarshe** [comment]
> good afternoon Nayam Amarshe
> Thanks a lot for your fast feedback.
> ...it's hard to read have this feedback. It will be that way.
> Will there be in the future be a possibility to support any iGraphics?
> 
> The other alternativ will be to use the Cloud Version I guess? 
> When it will this version (even Beta) be out?
> 
> Thanks a lot for your respone and have a great day
> Urmel

Hi Urmel,
Unfortunately, due to the way Upscayl Desktop works, it requires a graphics card. We cannot do anything about it, sadly.

The alternative is Upscayl Cloud, yes. It will work on all platforms and even mobile because it's a cloud-based web application.

It'll be out in the coming months. We're just 2 developers in the team, so handling the development of both the Upscayl Cloud and the Upscayl Desktop is a bit difficult sometimes 😅

But we're working on it everyday :)

**Comment by urmel2024** [comment]
Hi Nayam Amarshe and team
thank you very much for what you have achieved so far. 
I also keep my fingers crossed that your product will be a success.
I am also looking with great interest at your cloud product, which will certainly help me, in my project to digitize my old slides. 
Of course I would like to do everything on my own PC (Laptop) and not in the cloud (for security and privacy reasons).
anyway thank you very much and good luck
Thank you 
Urmel
