### ISSUE TITLE
Always got Black Image!

### ISSUE THREAD

**Issue by zh100ch** [upscayl/upscayl#649]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

I tried several times with different models and set the app in performance mode but I could only get black images, even It has been told intel HD graphics 620 works with Unscayl but for me it is not, how can I solve this issue?

### To Reproduce

just followed the instruction: 
Upload image
Select model
Set output folder
P.S I set GPU ID as 0 (but I don't know if it is right)

### Version (or commit hash)

2.9.5

### Select your Operating System

Linux

### OS Version

windows 10

### GPU Name

Inter HD Graphics 620

### Expected Behavior

generate an upscaled clearer image

### Paste the logs

```sh
1
```

**Comment by zh100ch** [comment]
I can not upload the log file  because it exceeded the maximum comment length I can edit, I stored it in a .txt file for checking, sorry, I am very new here
[log file.txt](https://github.com/upscayl/upscayl/files/13944721/log.file.txt)

**Comment by NayamAmarshe** [comment]
You don't have a compatible GPU

**Comment by zh100ch** [comment]
> You don't have a compatible GPU
Hi, NayamAmarshe
thanks for your quick reply, but I saw the compatibility list, the intel HD Graphics 620 works (credit: [@Axe7bravo](https://github.com/upscayl/upscayl/issues/382)) when using Upscayl. 
And one more question, if the GPU is not compatible with Unscayl, does it mean that I can not use Upscayl anymore?

**Comment by NayamAmarshe** [comment]
> > You don't have a compatible GPU
> > Hi, NayamAmarshe
> > thanks for your quick reply, but I saw the compatibility list, the intel HD Graphics 620 works (credit: [@Axe7bravo](https://github.com/upscayl/upscayl/issues/382)) when using Upscayl.
> > And one more question, if the GPU is not compatible with Unscayl, does it mean that I can not use Upscayl anymore?

You can try reinstalling the intel graphics drivers. Other than that, I can't really guarantee. Sometimes, the drivers support vulkan and sometimes they don't. When they don't, you get issues like a blank upscaled image.

You might be able to use Upscayl when we launch the cloud version, which will not require any special hardware :)
