### ISSUE TITLE
Doesn't work in Windows 10 Pro

### ISSUE THREAD

**Issue by odinian** [upscayl/upscayl#65]
Hello, I downloaded the 1.2.0 Windows installer. I can run the program and get the GUI. I select an image and click Upscayl and I just get a tiny version of the image on the left and black on the right. Any ideas? 

Note, I tied several times using the same image. Once it worked, but 9 times it didn't. I also tried different images and I get the same failed results. 

System Info:
```
OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DEFINE7
System Manufacturer	Gigabyte Technology Co., Ltd.
System Model	X570 AORUS ELITE
System Type	x64-based PC
System SKU	Default string
Processor	AMD Ryzen 7 5800X 8-Core Processor, 3801 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date	American Megatrends International, LLC. F37c, 5/12/2022
SMBIOS Version	3.3
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Gigabyte Technology Co., Ltd.
BaseBoard Product	X570 AORUS ELITE
BaseBoard Version	Default string
Platform Role	Desktop
Secure Boot State	Off
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume6
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.1806"
User Name	DEFINE7\allan
Time Zone	Mountain Daylight Time
Installed Physical Memory (RAM)	64.0 GB
Total Physical Memory	63.9 GB
Available Physical Memory	40.5 GB
Total Virtual Memory	73.4 GB
Available Virtual Memory	41.5 GB
Page File Space	9.50 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes
```
<img width="815" alt="image" src="https://user-images.githubusercontent.com/5237422/190866344-60274f1c-ae8c-4106-b3bc-38a9d0a45c17.png">

**Comment by NayamAmarshe** [comment]
No GPU?

**Comment by odinian** [comment]
Sorry, I assumed the GPU was in the report. AMD RX-590

**Comment by odinian** [comment]
Is there a log file that might be helpful?

**Comment by NayamAmarshe** [comment]
> Is there a log file that might be helpful?

No idea about Windows tbh. On Linux and Mac we can launch upscayl via command line to see the logs.

**Comment by odinian** [comment]
Umm, not much info. Is there a command line switch for more verbose logging?
```
C:\Users\allan\Desktop\(5 Star) DSC01839.jpg
≡ƒÜÇ => ipcMain.on => outputDir C:\Users\allan\Desktop
PRODUCTION? : false
EXEC:  C:\Users\allan\AppData\Local\Programs\upscayl\Resources\bin\upscayl
[0 Radeon RX 590 Series]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 Radeon RX 590 Series]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon RX 590 Series]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 Radeon RX 590 Series]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

Done upscaling
```

**Comment by odinian** [comment]
more info. If is possible the issue is the path to to models has a \ as the last delimiter?

```
C:\Users\allan>C:\Users\allan\AppData\Local\Programs\upscayl\Resources\bin\upscayl -i "C:\Users\allan\Desktop\DSC01839.jpg" -o "C:\Users\allan\Desktop\up.jpg" 
[0 Radeon RX 590 Series]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 Radeon RX 590 Series]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon RX 590 Series]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 Radeon RX 590 Series]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
_wfopen C:\Users\allan\AppData\Local\Programs\upscayl\Resources\bin\models/realesr-animevideov3-x4.param failed

C:\Users\allan>C:\Users\allan\AppData\Local\Programs\upscayl\Resources\bin\upscayl -i "C:\Users\allan\Desktop\DSC01839.jpg" -o "C:\Users\allan\Desktop\up.jpg" -n realesrgan-x4plus
[0 Radeon RX 590 Series]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 Radeon RX 590 Series]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Radeon RX 590 Series]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 Radeon RX 590 Series]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
_wfopen C:\Users\allan\AppData\Local\Programs\upscayl\Resources\bin\models/realesrgan-x4plus.param failed
```

**Comment by NayamAmarshe** [comment]
> more info. If is possible the issue is the path to to models has a \ as the last delimiter?
> 
> ```
> C:\Users\allan>C:\Users\allan\AppData\Local\Programs\upscayl\Resources\bin\upscayl -i "C:\Users\allan\Desktop\DSC01839.jpg" -o "C:\Users\allan\Desktop\up.jpg" 
> [0 Radeon RX 590 Series]  queueC=1[2]  queueG=0[1]  queueT=2[2]
> [0 Radeon RX 590 Series]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
> [0 Radeon RX 590 Series]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
> [0 Radeon RX 590 Series]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
> _wfopen C:\Users\allan\AppData\Local\Programs\upscayl\Resources\bin\models/realesr-animevideov3-x4.param failed
> 
> C:\Users\allan>C:\Users\allan\AppData\Local\Programs\upscayl\Resources\bin\upscayl -i "C:\Users\allan\Desktop\DSC01839.jpg" -o "C:\Users\allan\Desktop\up.jpg" -n realesrgan-x4plus
> [0 Radeon RX 590 Series]  queueC=1[2]  queueG=0[1]  queueT=2[2]
> [0 Radeon RX 590 Series]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
> [0 Radeon RX 590 Series]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
> [0 Radeon RX 590 Series]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
> _wfopen C:\Users\allan\AppData\Local\Programs\upscayl\Resources\bin\models/realesrgan-x4plus.param failed
> ```

Could be a path issue? That's weird. It's working for other Windows users and I have no idea why something like that would happen only on your machine.

**Comment by odinian** [comment]
No big deal. Lot's of other similar software to try. Thanks for looking.

**Comment by AmrMonzir** [comment]
I fixed this by copying the "models" directory and pasting it inside the "bin" folder.
By default, it was outside for me. That's the issue.
