### ISSUE TITLE
.deb package fails to install with multiple partitions

### ISSUE THREAD

**Issue by bovender** [upscayl/upscayl#652]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

The .deb package fails to install on my KDE system (Linux). My disk is partitioned, and the package apparently attempts to hard-link files between partitions, which does not work:

### To Reproduce

On a Linux box with multiple partitions (e.g., `/`, `/home`, `/opt` etc.), do the following:
1. Download .deb package.
2. `sudo dpkg -i upscayl-2.9.7-linux.deb`

### Version (or commit hash)

2.9.7

### Select your Operating System

Linux

### OS Version

KDE neon 5.27

### GPU Name

Intel UHD Graphics 620

### Expected Behavior

The package should install properly.

### Paste the logs

```sh
Unpacking upscayl (2.9.7) ...
dpkg: error processing archive upscayl-2.9.7-linux.deb (--install):
 error creating hard link './opt/Upscayl/resources/512x512.png': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
```
```

**Comment by bovender** [comment]
Thanks for your comment. It's not that uncommon to have a Linux system spread out over different partitions/filesystems. A  symlink would work. But after some research, I agree that this issue cannot be solved within Upscayl.

For reference, it appears to be an issue with electron-builder: electron-userland/electron-builder/issues/5721 -- see the comment thread for other packages that are affected by this. However, at the time of writing, there is no solution yet. (Other than not installing the deb package, but rather use the AppImage.)

**Comment by infinity0** [comment]
Alternative workaround is to install the package with `--path-exclude`:

~~~~
$ sudo dpkg -i \
  --path-exclude=/usr/share/icons/hicolor/512x512/apps/upscayl.png \
  --path-exclude=/usr/share/icons/hicolor/128x128/apps/upscayl.png \
  upscayl-2.9.9-linux.deb
~~~~
