### ISSUE TITLE
Upscayl shows black screen on Windows in a folder with the path `C:\static`

### ISSUE THREAD

**Issue by maxwowpow** [upscayl/upscayl#654]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

Windows: really weird! 🤯

- ❌ It fails/aka empty screen if the path starts with `C:\static` (or any other drive like `E:\static`), e.g. `C:\static\upscayl-2.9.8`  and works otherwise. Seems **not** connected to: symlinks, file permissions, runas admin, upsc.version.
- ✅ It works on "other" locations (including e.g. C:\1\static).
2.9.8.

### To Reproduce

- download zip
- put it into `C:\static`
- launch

### Version (or commit hash)

all/2.9.7

### Select your Operating System

Windows

### OS Version

win 11 22h2

### GPU Name

nvidia

### Paste the logs

```
VM173:1 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at <anonymous>:1:1
```

```js
localStorage.getItem("lastImagePath");
```

```
Request URL:
file:///C:/static/upscayl-2.9.8/resources/app.asar/renderer/out/index.html
Referrer Policy:
strict-origin-when-cross-origin
```

Leads:
https://github.com/electron-userland/electron-builder/issues/7157
https://github.com/electron/electron/issues/35808

```js
protocol.registerSchemesAsPrivileged([
  { scheme: 'app', privileges: { standard: true, supportFetchAPI: true, secure: true } }
])
```

**Comment by aaronliu0130** [comment]
Does running as admin help? If so, Upscayl simply does not have permissions to access that folder.

**Comment by NayamAmarshe** [comment]
It's pretty strange. Really seems like a permission issue.

**Comment by maxwowpow** [comment]
runas admin = same black screen.

**Comment by aaronliu0130** [comment]
And that *only* happens if the folder is named static and at the root? Not when it's a subfolder of something else?

**Comment by NayamAmarshe** [comment]
> runas admin = same black screen.
> 
> 
> 
> but to be fair, guys, I do not want to burden you with this issue, especially with this speficity and "easy way to avoid this". 
> 
> So if it's confirmed by someone else, just add a note/faq for this and maybe "someone" will look into it out of curiosity :)

I think it would be good to find out what exactly is wrong. Mac users facing this problem could also benefit

**Comment by emanuel73** [comment]
I got a similar problem but the "way out" does not work.
The resulting image is in any model: (1) black, (2) smaller than the original image, (3) C:\1\static does not help at all
This might be coupled with another issue: Setting the application to remember the output folder does not work. It always refers back to cc:\desktop and I am enquired to type in the right path to the output folder in which the file is black.

**Comment by NayamAmarshe** [comment]
> I got a similar problem but the "way out" does not work.
> The resulting image is in any model: (1) black, (2) smaller than the original image, (3) C:\1\static does not help at all
> This might be coupled with another issue: Setting the application to remember the output folder does not work. It always refers back to cc:\desktop and I am enquired to type in the right path to the output folder in which the file is black.

Not the same issue. This is for the app not working at all.

Your issue sounds more of a GPU problem. You need better drivers or a compatible GPU.

**Comment by emanuel73** [comment]
Il do not have a GPU at all.
If the fault is "better drivers" to which drivers do you refer?
All other applications work OK.


Best Regards ,
     Emanuel

**Comment by aaronliu0130** [comment]
> Il do not have a GPU at all.

Please read the FAQ again.
