### ISSUE TITLE
Mac Batch using default settings don't work under 2.9.8

### ISSUE THREAD

**Issue by roja6969** [upscayl/upscayl#657]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

When I select Batch on Mac Sonoma M3 Pro I select local folder with any amount of images it auto completes instantly no files created with no errors saying Done. 2.9.5 works fine. I have deleted and went back to 2.9.5 all works fine again.  

### To Reproduce

download 2.9.8 default settings on Apple silicon Mac from App store. 

### Version (or commit hash)

2.9.8

### Select your Operating System

MacOS

### OS Version

Sonoma latest update 14.2.1

### GPU Name

SOC Apple

### Expected Behavior

batch process similar to 2.9.7 

### Screenshots

no since it auto completes and says "Done"

### Paste the logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🚨 Folder Bookmarks:  Ym9vawgDAAAAAAQQMAAAAONZqzX2Gc/9hPsXhoYRwEwjQOJnTvV8VRhaxUAZFPpcBAIAAAQAAAADAwAAAAgAKAUAAAABAQAAVXNlcnMAAAAFAAAAAQEAAHJvZ2VyAAAACAAAAAEBAABQaWN0dXJlcwQAAAABAQAAMjAyMw0AAAABAQAAQUkgY29udmVyc2lvbgAAAAUAAAABAQAAYmF0MTYAAAAYAAAAAQYAABAAAAAgAAAAMAAAAEAAAABMAAAAZAAAAAgAAAAEAwAAED4AAAAAAAAIAAAABAMAAOwEBAAAAAAACAAAAAQDAADz2wcAAAAAAAgAAAAEAwAAjN4HAAAAAAAIAAAABAMAAExdEgAAAAAACAAAAAQDAABnBTIAAAAAABgAAAABBgAAlAAAAKQAAAC0AAAAxAAAANQAAADkAAAACAAAAAAEAABBxZiPTzU/RRgAAAABAgAAAgAAAAAAAAAPAAAAAAAAAAAAAAAAAAAACAAAAAQDAAAEAAAAAAAAAAQAAAADAwAA9QEAAAgAAAABCQAAZmlsZTovLy8MAAAAAQEAAE1hY2ludG9zaCBIRAgAAAAEAwAAAFChG3MAAAAIAAAAAAQAAEHFlk7IgAAAJAAAAAEBAAA0QUQxNEYxNC0yQjA3LTRCQzgtOTlGMC1GMjlCMDdBNDYxNjQYAAAAAQIAAIEAAAABAAAA7xMAAAEAAAAAAAAAAAAAAAEAAAABAQAALwAAAAAAAAABBQAAzAAAAP7///8BAAAAAAAAABAAAAAEEAAAdAAAAAAAAAAFEAAA9AAAAAAAAAAQEAAAJAEAAAAAAABAEAAAFAEAAAAAAAACIAAA8AEAAAAAAAAFIAAAYAEAAAAAAAAQIAAAcAEAAAAAAAARIAAApAEAAAAAAAASIAAAhAEAAAAAAAATIAAAlAEAAAAAAAAgIAAA0AEAAAAAAAAwIAAA/AEAAAAAAAABwAAARAEAAAAAAAARwAAAIAAAAAAAAAASwAAAVAEAAAAAAAAQ0AAABAAAAAAAAAA=
🐞 BACKEND REPORTED:  📁 Updating Folder Path:  /Users/roger/Pictures/2023/AI conversion/bat16
🖼 Selected Folder Path:  /Users/roger/Pictures/2023/AI conversion/bat16
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  /Users/roger/Pictures/2023/AI conversion/bat16
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  🗑️ Deleting .DS_Store file
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,/Users/roger/Pictures/2023/AI conversion/bat16,-o,/Users/roger/Pictures/2023/AI conversion/bat16/upscayl_realesrgan-x4plus_x4,-s,4,-m,/Applications/Upscayl.app/Contents/Resources/models,-n,realesrgan-x4plus,-f,png
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🚧 FOLDER_UPSCAYL_PROGRESS:  filename: IMG_2365.JPG
filename: IMG_2380.JPG

🚧 FOLDER_UPSCAYL_PROGRESS:  [0 Apple M3 Pro]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Apple M3 Pro]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0

🚧 FOLDER_UPSCAYL_PROGRESS:  [0 Apple M3 Pro]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Apple M3 Pro]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
🐞 BACKEND REPORTED:  Skipping png compression for 4x scale and 0% compression
🐞 BACKEND REPORTED:  Skipping png compression for 4x scale and 0% compression
🐞 BACKEND REPORTED:  Skipping png compression for 4x scale and 0% compression
💯 FOLDER_UPSCAYL_DONE:  /Users/roger/Pictures/2023/AI conversion/bat16/upscayl_realesrgan-x4plus_x4
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
```

**Comment by aaronliu0130** [comment]
Does setting compression to 1% help? This seems like it could be related to #653

**Comment by NayamAmarshe** [comment]
Very strange, This seems like a permission issue. Try selecting an output folder before upscayling.

**Comment by NayamAmarshe** [comment]
> Does setting compression to 1% help? This seems like it could be related to #653

It could also be related to M3 pro. We haven't tested it yet.

**Comment by NayamAmarshe** [comment]
I tried to reproduce the error but I couldn't. It's working absolutely fine on M1.

I even tried to have the same path as you but it's working fine. This is 2.9.8 Mac App Store version.
<img width="594" alt="image" src="https://github.com/upscayl/upscayl/assets/25067102/8b02bf55-d81d-4366-b9ea-0fa7187b272a">

**Comment by roja6969** [comment]
Hello team very sorry for the late response, Life. I don't frequent here so. I have tried a few things mentioned above. 
I have tried Selecting the output folder (made no difference)
I have tried with the 1% compression (same)
Tried different Model (defaults no extra)
I recently added custom models found in your git and same results.
I tried a clean up and reinstall and same results. If I uninstall then reinstall the 2.9.5 (I made a typo previously) everything works 

I first time installed in December and used all default settings and in January when the new version was out upgraded from appstore (with no custom settings).  M3 Mac bookPro Latest Sonoma.

I run the same version on My PC and that works flawlessly. Doing single files works with no issues. If it is a me problem and not a everyone else in the world where should I look for the correct permissions ?  ~/Library ? is there a plist or some ext.

Thank you again for your time.

**Comment by roja6969** [comment]
Also tried the saving to JPG instead of PNG same, compression off, Output folder set. 3x files in folder all JPG's nothing is output.

**Comment by roja6969** [comment]
I now seem to get this Randomly 
<img width="1335" alt="Untitled" src="https://github.com/upscayl/upscayl/assets/2814617/6594fb26-383f-44af-8bbf-0c674190e9fc">

**Comment by aaronliu0130** [comment]
Could you try 2.9.9? If it doesn't work, try sending us the logs again

**Comment by roja6969** [comment]
Hello good day I downloaded 2.9.9 and all works just fine with no changes being made. Thank you this can be closed it's now as resolved.
