### ISSUE TITLE
Ctrl + ➕ doesn't zoom in

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#658]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

title
electron now super zoomed out
i ugpraded and reinstalled
it still is zooméd out
help

### To Reproduce

0. Ctrl + ➖ 
0. Ctrl + ➖ 
0. CtrL + ➖ 
0. CtRL + ➖ 
0. CtRl + ➖ 
0. ctRL + ➖ 
0. CTrl + ➖ 
0. CTRL + ➖ 

### Version (or commit hash)

2.9.8, also present on 2.9.5 at least

### Select your Operating System

Windows

### OS Version

Windows 11 23H2

### GPU Name

n/a

### Screenshots

<details>
<summary>

![image](https://github.com/upscayl/upscayl/assets/11874211/46b47535-755b-43a0-aef9-a30441a50510)

</summary>

![image](https://github.com/upscayl/upscayl/assets/11874211/fb5f6a98-bf0d-4ca5-ac84-8e2df1f86e89)

</details>

### Paste the logs

```sh
🎯 GET_MODELS_LIST:  C:\Users\aaron\Git\custom-models\models
🐞 BACKEND REPORTED:  📁 Updating Custom Models Folder Path:  C:\Users\aaron\Git\custom-models\models
🐞 BACKEND REPORTED:  📁 Custom Models Folder Path:  C:\Users\aaron\Git\custom-models\models
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🐞 BACKEND REPORTED:  🔎 Detected Custom Models:  4x_NMKD-Siax_200k,4x_NMKD-Superscale-SP_178000_G,realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,ultrasharp-2.0.1,uniscale_restore
📜 CUSTOM_MODEL_FILES_LIST:  4x_NMKD-Siax_200k,4x_NMKD-Superscale-SP_178000_G,realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,ultrasharp-2.0.1,uniscale_restore
🔀 Setting model to ultrasharp
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  NaN
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
```

**Comment by NayamAmarshe** [comment]
Does Ctrl+0 help?

**Comment by NayamAmarshe** [comment]
> It does! Why doesn't Ctrl + ➕  work though?

Who knows, electron.js is a mystery to me😂
