### ISSUE TITLE
Output folder not remembered

### ISSUE THREAD

**Issue by emanuel73** [upscayl/upscayl#662]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

In Windows 10 setting the option to remember the output folder does not hold and I have, time and again, in step 3 to reassign the output folder. The application choice is to write to a desktop file.
Might be connect with the other issue that mentioned that the output file is always black and reduced in size from the original image.

### To Reproduce

1. Set the option
2. Check that it was accepted
3. Change to the right folder
4. Check that it was accepted
5. Execute

### Version (or commit hash)

2.9.8

### Did you download Upscayl from the Mac App Store?

- [ ] Yes, I downloaded Upscayl from the Mac App Store!

### Select your Operating System

Windows

### OS Version

Windows 10

### GPU Name

NO GPU

### Paste the logs

```sh
No logs available
```

**Comment by NayamAmarshe** [comment]
Hi, could you please attach logs as well?
