### ISSUE TITLE
Different Scales produce the same size images

### ISSUE THREAD

**Issue by loraleiffxi** [upscayl/upscayl#663]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [X] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

Using Batch mode to process from Png to Jpg,  starting from 1344 x896, the same image size is produced no matter what multiplier I select in settings.  x2 produces 5376 x 3584, and x3 produces 5376 x 3584.  x4 does the same thing.

### To Reproduce

Batch upscayl, pick a folder with png images, select any image scale, with jpg as the output

### Version (or commit hash)

Windows 2.9.8

### Did you download Upscayl from the Mac App Store?

- [ ] Yes, I downloaded Upscayl from the Mac App Store!

### Select your Operating System

Windows

### OS Version

Windows 11

### GPU Name

Nvidia Geforce RTX 4080

### Expected Behavior

Each scale should have produced a different sized image. 

### Paste the logs

```sh
🚧 UPSCAYL_PROGRESS:  Upscayl Successful

🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
🐞 BACKEND REPORTED:  📐 Processing Image:  {"originalWidth":896,"originalHeight":1344,"scale":"2","saveImageAs":"jpg","compressionPercentage":0,"compressionLevel":0}
🐞 BACKEND REPORTED:  🖼️ Checking if original image exists:  D:\Images\RawImagesFromMJ\midjourney_session_2024-1-19_[0-41]\_leeloo__Adapt_Claude_Monets_impressionist_style_to_an_underwat_5ea3f2d0-1f4a-4325-965c-db23d5dd67ca.png
🐞 BACKEND REPORTED:  ✅ Done converting to:  D:\Images\RawImagesFromMJ\midjourney_session_2024-1-19_[0-41]\_leeloo__Adapt_Claude_Monets_impressionist_style_to_an_underwat_5ea3f2d0-1f4a-4325-965c-db23d5dd67ca_upscayl_2x_ultramix_balanced.jpg
upscaledImagePath:  D:\Images\RawImagesFromMJ\midjourney_session_2024-1-19_[0-41]\_leeloo__Adapt_Claude_Monets_impressionist_style_to_an_underwat_5ea3f2d0-1f4a-4325-965c-db23d5dd67ca_upscayl_2x_ultramix_balanced.jpg
💯 UPSCAYL_DONE:  D:\Images\RawImagesFromMJ\midjourney_session_2024-1-19_[0-41]\_leeloo__Adapt_Claude_Monets_impressionist_style_to_an_underwat_5ea3f2d0-1f4a-4325-965c-db23d5dd67ca_upscayl_2x_ultramix_balanced.jpg
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
```

**Comment by NayamAmarshe** [comment]
![image](https://github.com/upscayl/upscayl/assets/25067102/96bfc9fa-fa00-4350-b8a5-101cfc9b0934)

**Comment by loraleiffxi** [comment]
After performing a 2x , 3x, and 4x upscale, all images in the new upscaled folders were 5376 x 3584.

**Comment by NayamAmarshe** [comment]
I'm unable to reproduce this issue. Maybe try restarting/reinstalling the app. Batch upscale is working fine here, with the scale selection as well.

Also, let the the batch upscale process be completely done before you check the images inside the folders. They should be the scale that you set earlier.

**Comment by loraleiffxi** [comment]
You are right.  I just wasn't patient enough to look after it completed.  So sorry to bother you, but thank you for replying and showing me the way.

**Comment by NayamAmarshe** [comment]
No worries, happy to help!

**Comment by NayamAmarshe** [comment]
@aaronliu0130 This should be closed as completed as this issue has already been fixed and the issue creator has gotten the solution as well.

**Comment by aaronliu0130** [comment]
This isn’t a real bug, just a misunderstanding

**Comment by NayamAmarshe** [comment]
> This isn’t a real bug, just a misunderstanding

Yes, and we cleared the misunderstanding. We shouldn't be marking this as 'Not Planned' because I don't think that fits.

**Comment by aaronliu0130** [comment]
IMO There wasn’t any work needed so there wasn’t anything completed, plus this issue is actually a duplicate

**Comment by NayamAmarshe** [comment]
> IMO There wasn’t any work needed so there wasn’t anything completed, plus this issue is actually a duplicate

Hmm, ok, for duplicate issues we should mark them as such but for the rest, where queries or questions are answered and accepted (while not being a discussion), we should mark them as completed because that's what completed is for and just for code-fixes.

**Comment by aaronliu0130** [comment]
Hmm... Sure, though it's a little bit different than actually adding it or changing the code, so I've just created the "works as intended label" which should hopefully clear things up
