### ISSUE TITLE
File limitation when batch upscaling

### ISSUE THREAD

**Issue by mindthemix** [upscayl/upscayl#667]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

I tried to upscale 2K files but the upscaling stopped at file 178.

Is there a file limit?

Thanks.

### To Reproduce

Uploading more than 178 files and run batch upscaling

### Version (or commit hash)

2.9.8

### Did you download Upscayl from the Mac App Store?

- [ ] Yes, I downloaded Upscayl from the Mac App Store!

### Select your Operating System

MacOS

### OS Version

14.2.1

### GPU Name

MacBook Pro M3

### Paste the logs

```sh
🎯 GET_MODELS_LIST:  /Users/refueladmin/Library/CloudStorage/OneDrive-refuelagency.com/Resources/custom-models-main/models
🧠 Recalling Output Folder:  /Users/refueladmin/Creative Cloud Files/Scaling/Batch #2 for review
🐞 BACKEND REPORTED:  📁 Updating Custom Models Folder Path:  /Users/refueladmin/Library/CloudStorage/OneDrive-refuelagency.com/Resources/custom-models-main/models
🐞 BACKEND REPORTED:  📁 Custom Models Folder Path:  /Users/refueladmin/Library/CloudStorage/OneDrive-refuelagency.com/Resources/custom-models-main/models
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
🐞 BACKEND REPORTED:  📁 Updating Output Folder Path:  /Users/refueladmin/Creative Cloud Files/Scaling/Batch #2 for review
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  true
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  true
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  true
```

**Comment by aaronliu0130** [comment]
Could you give us the logs for when you try to Upscayl?

**Comment by mindthemix** [comment]
Hi there,

Thanks for the prompt reply.

Attached is the log.

Thx/F

On Jan 25, 2024, at 11:31 AM, Aaron Liu ***@***.***> wrote:


Could you give us the logs for when you try to Upscayl?

**Comment by aaronliu0130** [comment]
Email attachments do not send to GitHub. Try attaching it on GitHub’s web interface.

**Comment by mindthemix** [comment]
I will. Thanks for letting me know Sent from my iPhoneOn Jan 25, 2024, at 1:10 PM, Aaron Liu ***@***.***> wrote:﻿
Email attachments do not send to GitHub. Try attaching it on GitHub’s web interface.

**Comment by mindthemix** [comment]
Please find attached the logs.

[log.rtf.zip](https://github.com/upscayl/upscayl/files/14056842/log.rtf.zip)

**Comment by aaronliu0130** [comment]
The logs say 2900+ files were successfully upscaled and nothing ever stopped. Are you sure it only output 178?

**Comment by mindthemix** [comment]
Please check the video. The batch is 2,420 files, and only 128 were scaled.

https://github.com/upscayl/upscayl/assets/155106230/e22d1a1a-0385-48f1-983c-9ec6ca21dbdc

Log
[batch scaling.zip](https://github.com/upscayl/upscayl/files/14058218/batch.scaling.zip)

**Comment by aaronliu0130** [comment]
Okay, this is very weird. @NayamAmarshe Any ideas?

**Comment by mindthemix** [comment]
All files are jpg and have no special characters.

**Comment by mindthemix** [comment]
After a quick experiment, it worked.

Locally upscaling files always limits you to 128 or 178 files. My setup is a Macbook Pro M3 Max, 16‑core CPU, 40‑core GPU and 128GB RAM. As soon as I moved all 5K files to an external HD connected to my iMac, it scaled all the files from the M3 settings folders.

Perhaps the M3 specs are overkill when running files locally?

**Comment by NayamAmarshe** [comment]
> After a quick experiment, it worked.
> 
> Locally upscaling files always limits you to 128 or 178 files. My setup is a Macbook Pro M3 Max, 16‑core CPU, 40‑core GPU and 128GB RAM. As soon as I moved all 5K files to an external HD connected to my iMac, it scaled all the files from the M3 settings folders.
> 
> Perhaps the M3 specs are overkill when running files locally?

It's possible. I'll update Vulkan in the next release to see if that fixes it.

**Comment by njardim** [comment]
I had similar problems while upscaling around 972 files to a specific width, i.e., 2160px. The batch ran for over 6 hours, and when it finally finished, it left all files upscaled to 4x the size of the original files and not with the width I had specified. 

With a number under 180 files, the batch runs fine, but larger batches won't complete correctly. I've tested this several times.

Also, I've noticed that the batch upscales all files to 4x the size of the original file while running, and that it's only at the end of the batch process that all the files are resized to the specific size set by the user. So, my question is, can't the batch complete the upscale process for each individual file and only then move on to the next one?

**Comment by GitPKU** [comment]
I'm trying to batch-upscale bigger pixel size images (Insta360 cam 18MP) and I hit a limit of just 8 input files. Add one more file to input folder and whole upscale process reports job done in just a few seconds while nothing is scaled. And I have hundereds to go !
