### ISSUE TITLE
[GPU ERROR] Error upon Upscayl start

### ISSUE THREAD

**Issue by o10222** [upscayl/upscayl#668]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

o10222-> upscayl
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
📂 DIRNAME /snap/upscayl/31/opt/Upscayl/resources/app.asar/export/electron
Checking for update
15:18:52.217 › 🚀 UPSCAYL EXEC PATH:  /snap/upscayl/31/opt/Upscayl/resources/bin/upscayl-bin
15:18:52.223 › 🚀 MODELS PATH:  /snap/upscayl/31/opt/Upscayl/resources/models
[27166:0124/151852.245330:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[27249:0124/151852.358132:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[27182:0124/151852.410091:ERROR:command_buffer_proxy_impl.cc(127)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
15:18:52.644 › 💾 Updating Save Output Folder:  false
These error are returned upon start:

Vulkan SDK vkconfig reports find the Nvidia RTX 2060 card.

### To Reproduce

run command upscayl 
it returns this error in screen shot.

Vlkan cube and SDK check appear to be correct

### Version (or commit hash)

2.9.8

### Did you download Upscayl from the Mac App Store?

- [ ] Yes, I downloaded Upscayl from the Mac App Store!

### Select your Operating System

Linux

### OS Version

Fedora 38

### GPU Name

NVIDIA GeForce RTX 2060

### Screenshots

![Screenshot_upscayl](https://github.com/upscayl/upscayl/assets/7388018/84d0a883-2d01-4073-bb9c-b97c0f834533)

### Paste the logs

```sh
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  0
🔀 Setting model to 
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  0
⚙️ Getting rememberOutputFolder from localStorage:  false
```

**Comment by o10222** [comment]
o10222-> sudo dnf list nvidia*
Last metadata expiration check: 0:27:41 ago on Wed 24 Jan 2024 03:11:18 PM MST.
Installed Packages
nvidia-gpu-firmware.noarch                                             20231211-1.fc38                                    @updates                  
nvidia-modprobe.x86_64                                                 3:545.29.06-1.fc38                                 @rpmfusion-nonfree-updates
nvidia-persistenced.x86_64                                             3:545.29.06-1.fc38                                 @rpmfusion-nonfree-updates
nvidia-settings.x86_64                                                 3:545.29.06-1.fc38                                 @rpmfusion-nonfree-updates
nvidia-xconfig.x86_64                                                  3:545.29.06-1.fc38                                 @rpmfusion-nonfree-updates

**Comment by o10222** [comment]
![nvtop](https://github.com/upscayl/upscayl/assets/7388018/7e97a820-9d7a-48e7-8f95-46ab50878c51)

NVtop seems to find GPU also.

**Comment by aaronliu0130** [comment]
Could you give us the logs for when you Upscayl an image?

**Comment by NayamAmarshe** [comment]
Does the AppImage work?

**Comment by layyah5025** [comment]
I am facing this problem in my system, please tell me any way to solve this problem, thanks

**Comment by aaronliu0130** [comment]
Please file a new issue.

**Comment by NayamAmarshe** [comment]
@o10222 Does the AppImage work? I'm assuming you're running flatpak.

**Comment by aaronliu0130** [comment]
They seem to be using a snap. Since they haven't replied or updated, I'm closing this as stale.
