### ISSUE TITLE
vkCreateInstance failed -9 invalid gpu device 

### ISSUE THREAD

**Issue by Matloubetoday** [upscayl/upscayl#674]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the next checkbox. I will try the last two checkboxes in the checklist.
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [X] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

I have this problem in my computer, I am suing Windwos 10, 64 bit
![problem](https://github.com/upscayl/upscayl/assets/157534399/c5e86280-5b77-4bb8-8757-f44f5480ed77)
![CCd](https://github.com/upscayl/upscayl/assets/157534399/d035c638-e8d1-42bc-9b47-c30993b3dace)

### To Reproduce

I did my best to solve this problem but till now, I do not now what to do.
Help me please
![problem](https://github.com/upscayl/upscayl/assets/157534399/27e9c839-467b-4f38-ada2-54fcf9347973)

### Version (or commit hash)

Version 2.9.8

### Platform

Windows

### OS Version

11

### GPU Name

Internal Graphic family

### Expected Behavior

I did my best to solve this problem but till now, I do not now what to do.
Help me please

### Screenshots

![problem](https://github.com/upscayl/upscayl/assets/157534399/9db6788a-e349-41f7-b05c-ca24fbb6dcb3)
![CCd](https://github.com/upscayl/upscayl/assets/157534399/51b4cf7f-f9db-44b5-ad22-f334ee77bb8f)

### Paste the logs

```sh
🎯 GET_MODELS_LIST:  C:\custom-models-main\custom-models-main\models
🐞 BACKEND REPORTED:  📁 Updating Custom Models Folder Path:  C:\custom-models-main\custom-models-main\models
🐞 BACKEND REPORTED:  📁 Custom Models Folder Path:  C:\custom-models-main\custom-models-main\models
🐞 BACKEND REPORTED:  🔎 Detected Custom Models:  4xHFA2k,4xLSDIR,4xLSDIRCompactC3,4xLSDIRplusC,4xNomos8kSC,4x_NMKD-Siax_200k,4x_NMKD-Superscale-SP_178000_G,realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,uniscale_restore,unknown-2.0.1
📜 CUSTOM_MODEL_FILES_LIST:  4xHFA2k,4xLSDIR,4xLSDIRCompactC3,4xLSDIRplusC,4xNomos8kSC,4x_NMKD-Siax_200k,4x_NMKD-Superscale-SP_178000_G,realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,uniscale_restore,unknown-2.0.1
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  0,1,2
🔀 Setting model to 
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
🐞 BACKEND REPORTED:  🔕 Updating Turn Off Notifications:  true
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  0,1,2
⚙️ Getting rememberOutputFolder from localStorage:  false
```

**Comment by aaronliu0130** [comment]
> Yes, unfortunately. NCNN Vulkan requires a Vulkan-compatible GPU. Upscayl won't work with most iGPUs or CPUs.

A workaround exists for Windows and Linux in #390.

> I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).

![compulsory rickrolls are issued for duplicates of issues and the FAQ and normies who use intelgrated GPUs](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
