### ISSUE TITLE
Generated image does not respect orentation

### ISSUE THREAD

**Issue by WhosyVox** [upscayl/upscayl#68]
Orientation data in a target image is ignored (e.g. orientation=upper-right in a jpeg), resulting in a malformed preview. 

![image](https://user-images.githubusercontent.com/24579654/191099332-5f7b2092-3786-48a0-a095-a64da03a3c64.png)

`JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=12, height=2448, manufacturer=SAMSUNG, model=GT-N7100, orientation=upper-right, xresolution=208, yresolution=216, resolutionunit=2, software=N7100XXDME6, datetime=2013:08:03 16:28:36, width=3264], baseline, precision 8, 3264x2448, components 3`

Tested on newest release (1.5) AppImage on Linux Mint 20.3.

**Comment by NayamAmarshe** [comment]
Yeah, you'd have to reset the rotation. Real-ESRGAN resets the metadata so there's no good solution at the moment other than putting in the original image.

**Comment by WhosyVox** [comment]
There are workable solutions. You have access to the source image so you can either rotate the source image or, better still, use the opposite rotation on the final output.
I expect this issue is most likely to crop up on jpeg images as cameras commonly compensate for rotations in this manner, so conditional checks for jpeg file source. The final rotate on output could be done as simply as a css transformation in theory.

Even the former solution (rotate source image to match) is better than the current behaviour though.

**Comment by NayamAmarshe** [comment]
> There are workable solutions. You have access to the source image so you can either rotate the source image or, better still, use the opposite rotation on the final output. I expect this issue is most likely to crop up on jpeg images as cameras commonly compensate for rotations in this manner, so conditional checks for jpeg file source. The final rotate on output could be done as simply as a css transformation in theory.
> 
> Even the former solution (rotate source image to match) is better than the current behaviour though.

We'd have to use an image manipulation library for this, which we're going to in v2 for upscaling videos. Will consider fixing this then.
