### ISSUE TITLE
Upscayl icon not following icon theme spec in .deb & .rpm binary pkgs

### ISSUE THREAD

**Issue by MrPenguin07** [upscayl/upscayl#680]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the next checkbox. I will try the last two checkboxes in the checklist.
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [ ] https://github.com/SaschaWillems/VulkanCapsViewer reports Vulkan capabilities.

### Describe the Bug

Currently the .deb and .rpm binary packaging jobs are placing the upscayl icon in the dir structure at
`/usr/share/icons/hicolor/0x0/apps/upscayl.png`
The icon lookup mechanism does not search the non-standard `0x0` directory for icons hence it is unavailable.

Considering the icon in these binary packages is **512x512**, after manually moving upscayl.png to 
`/usr/share/icons/hicolor/512x512/apps/upscayl.png`
The icon then shows up in menus/when .desktop is invoked.

### To Reproduce

Unpack the .deb or .rpm and check dir structure 

### Version (or commit hash)

n/a

### Platform

Linux

### OS Version

Gentoo

### GPU Name

n/a

### Expected Behavior

Icon is placed in appropriate folder(s) so that the lookup mechanism finds it.
https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s03.html

### Paste the logs

```sh
n/a
```

**Comment by aaronliu0130** [comment]
An issue with electron builder, which might be able to be configured. We don’t know.

**Comment by MrPenguin07** [comment]
> An issue with electron builder: [electron-userland/electron-builder#5294](https://github.com/electron-userland/electron-builder/issues/5294)
> 
> Also, why’d you check the second checkbox? :p

The second tickbox had so many big fancy words, I couldn't resist ticking it apparently :o

I'm unfamiliar with most things electron, I assumed it was a simple fix when you know where to look.
I could have 'fixed' this by hacking it in the Gentoo ebuild, though if we've fixed it at the source well that's always the best solution.

You want this left open until we can confirm 2.9.9?

Regards

**Comment by aaronliu0130** [comment]
Agreed, it's much better if buildspecs don't need to fix something themselves

> You want this left open until we can confirm 2.9.9?

Yep

**Comment by MrPenguin07** [comment]
> Agreed, it's much better if buildspecs don't need to fix something themselves
> 
> > You want this left open until we can confirm 2.9.9?
> 
> Yep

Sure thing, i'll confirm 2.9.9 and close this if fixed :) 
Cheers

**Comment by NayamAmarshe** [comment]
I'm not sure what to do with this, since I already followed the electron-builder docs.

**Comment by aaronliu0130** [comment]
@MrPenguin07 I just remembered—you can already test it out by following the development instructions in the README! (don’t try to publish it)

**Comment by MrPenguin07** [comment]
> @MrPenguin07 I just remembered—you can already test it out by following the development instructions in the README! (don’t try to publish it)

Got around to working on a live git ebuild for upscayl, during which I built HEAD with npm and had a look inside the binary packages;

```
└──  usr
   └──  share
      ├──  applications
      │  └──  upscayl.desktop
      ├──  doc
      │  └──  upscayl
      │     └──  changelog.gz
      └──  icons
         └──  hicolor
            ├──  128x128
            │  └──  apps
            │     └──  upscayl.png
            └──  512x512
               └──  apps
                  └──  upscayl.png
                  ```
                  
So looks to me like you've had a win here with commit d4a6153
Closing as complete.
