### ISSUE TITLE
Upscayl cant work with Ryzen 5600G iGPU

### ISSUE THREAD

**Issue by vibit84** [upscayl/upscayl#685]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for my issue in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

Upscayl latest release doesnt work with Ryzen 5600G iGPU.

When I try to upscale any image it shows an error indicating something related to allocation memory problems and I can not upscale any image.

### To Reproduce

Just try to run Upscayl to upscale any image on an Ryzen 5600g iGPU on Windows 10 22h2 pro updated and with latest amd adrenlin drivers.

### Upscayl Version (or commit hash)

2.9.8

### Platform

Windows

### OS Version

Windows 10 22h2 Pro x64 updated with amd drivers updated

### GPU Name

Ryzen 5600G iGPU with 8gb of vram

### Expected Behavior

Upscayl to upscale any images

### Screenshots

No screenshot right now.

### Logs

```sh
Cant have it right now but I guess its noot needed as the logs only show generic informations.
```

**Comment by MrPenguin07** [comment]
Hi, without an exact error message or the log file this bug report isn't terribly helpful in diagnosing the issue. What you see as generic information in the log, is a wealth of information to those who wrote the debug code.

I suggest you upload these so that you receive an accurate response as to where your problem lies.

**Comment by aaronliu0130** [comment]
> Yes, unfortunately. NCNN Vulkan requires a Vulkan-compatible GPU. Upscayl won't work with most iGPUs or CPUs.

A workaround exists for Windows and Linux in #390.

> Make sure to read [the FAQ](https://github.com/upscayl/upscayl#-faq) first to avoid getting rickrolled.
> —[Troubleshooting](https://github.com/upscayl/upscayl/wiki/Troubleshooting)

![compulsory rickrolls are issued for duplicates of issues and the FAQ and normies who use intelgrated GPUs](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Comment by NayamAmarshe** [comment]
5600iG should work but check the logs for any vulkan errors
