### ISSUE TITLE
SUPIR model

### ISSUE THREAD

**Issue by 2b** [upscayl/upscayl#689]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Is there any chance we could see a new SUPIR model ([paper](https://arxiv.org/abs/2401.13627)) in Upscayl? It looks quite promising. 

[Python code](https://github.com/Fanghua-Yu/SUPIR) has permissive MIT license.

**Comment by aaronliu0130** [comment]
Sorry, but we currently use Real-ESRGAN and we’re not bundling all the Python stuff. Maybe something for that Upscayl cloud.
