### ISSUE TITLE
Cosmetic: 'Original' text bubble in bottom-left disappears

### ISSUE THREAD

**Issue by WhosyVox** [upscayl/upscayl#69]
.. if you move the preview divider all the way to the left. This is not true for the bottom-right 'Upscayled' text bubble when moving the divider far to the right.

![image](https://user-images.githubusercontent.com/24579654/191099892-4aa8b792-c633-4e55-a61a-ed92675eeeb8.png)

**Comment by NayamAmarshe** [comment]
This is normal behavior. It happens for the right side as well: 
![image](https://user-images.githubusercontent.com/25067102/191176743-0287e8b3-5a18-4d6f-920d-83d65a300abb.png)

**Comment by WhosyVox** [comment]
This does not appear to be true on my side. Linux Mint 20.3, AppImage variant.

![image](https://user-images.githubusercontent.com/24579654/191179167-2a3ef242-8b80-4155-8a4e-15a2247feb9a.png)

**Comment by NayamAmarshe** [comment]
> This does not appear to be true on my side. Linux Mint 20.3, AppImage variant.
> 
> ![image](https://user-images.githubusercontent.com/24579654/191179167-2a3ef242-8b80-4155-8a4e-15a2247feb9a.png)
> 
> Regardless even if this behaviour was consistent, I would still consider it to be erroneous. The labels aren't canonically part of the image, so why does the slider have any effect upon them?

This is consistent across all operating systems we've tested. Even MacOS:

![image](https://user-images.githubusercontent.com/25067102/191201916-82946833-271d-4c4f-9933-e5d60c9321a2.png)

I'll test another distro in a VM to see if it's the same there or not.

**Comment by NayamAmarshe** [comment]
Okay, I think I get why it's happening. Must be the PNG. The original image is supposed to overlay on top of the upscaled one, so since PNGs do not have a background, the title doesn't disappear. Interesting problem but a bit challenging since putting a solid background on PNGs could make things difficult.

**Comment by WhosyVox** [comment]
I spent a while trying to figure this out myself testing landscape/portrait, etc. You're probably correct though. Nice catch.

If the background colour is identical to the background colour of the app itself, would that cause much of an issue at all? I guess it'd be something to test.

**Comment by NayamAmarshe** [comment]
Yeah, I can fix it. Just not sure whether I should push a 1.5.1 just for this. 

I think I'll get it fixed in v2 so closing the issue for now and adding it to my to-do. Thanks for reporting!

**Comment by NayamAmarshe** [comment]
Fixed in https://github.com/upscayl/upscayl/releases/tag/v1.5.5
