### ISSUE TITLE
Migrate Wiki to docs.upscayl.org

### ISSUE THREAD

**Issue by NayamAmarshe** [upscayl/upscayl#692]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

We should start moving the documentation to docs.upscayl.org. It's easy to modify, the docs folder in this repo is the all the data.

**Comment by aaronliu0130** [comment]
wait, nayam's unbanned!!!

**Comment by NayamAmarshe** [comment]
We'll keep adding more pages.
