### ISSUE TITLE
Windows (and perhaps other platforms): have an option to disable notifications

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [upscayl/upscayl#697]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

It would be nice were there an option to disable the notifications that, on Windows (or my copy of Windows 10, at least) one gets when a job is finished. (For, barring special Windows configuration, those notifications need dismissing and put a badge on the taskbar.)

### Related Problem(s)

'Coerced' is a bit strong (' Are there any problems that coerced you into filing this feature request?'), but being irritated by notifications was my motivation for filing this request.

### Alternatives

Workaround: tell Windows, globally, i.e. for all apps, to disable (or hide away) notifications.

**Comment by aaronliu0130** [comment]
https://www.lifewire.com/turn-off-notifications-in-windows-10-5189206#toc-how-to-turn-off-notifications-from-specific-apps

**Comment by LinuxOnTheDesktop** [comment]
@aaronliu0130: ah; thanks; I was unaware of that setting. However, upscayl seems to lack an entry within those settings:

![image](https://github.com/upscayl/upscayl/assets/47056543/d8662d57-ab02-41d4-b1af-5ab157c824dd)

**Comment by NayamAmarshe** [comment]
It's in the settings.

**Comment by LinuxOnTheDesktop** [comment]
@NayamAmarshe : what is which settings tab?

**Comment by NayamAmarshe** [comment]
Upscayl settings tab

**Comment by LinuxOnTheDesktop** [comment]
@NayamAmarshe : I am sorry, but I see no relevant setting. Here is what I do see.

![image](https://github.com/upscayl/upscayl/assets/47056543/349d287d-1ce1-4fa6-a63f-da12a7b1791e)

![image](https://github.com/upscayl/upscayl/assets/47056543/9d743298-c6e2-4268-ba2b-67c9e0b34243)

**Comment by NayamAmarshe** [comment]
Is this v2.9.8?

**Comment by LinuxOnTheDesktop** [comment]
Ah: from the changeLog for version 2.9.8:

![image](https://github.com/upscayl/upscayl/assets/47056543/e2537cf6-7b06-4285-a976-f49188c8f8c1)

I was on 2.9.7. I've upgraded and now there is an option to disable notifications. Marvellous!
