### ISSUE TITLE
Windows setup not launching

### ISSUE THREAD

**Issue by stashymane** [upscayl/upscayl#70]
When launched, the setup shows no signs of life. No process, nothing.
The installer is also 165 KB, not sure if this is a downloader or the installer does not package any files :)

**Comment by SebaM90** [comment]
Here I have the same problem. The Windows installer doesn't work, the file weighs only a few KB.
Apparently, they confused the "blockmap" when uploading.

**Comment by MarleVVLL** [comment]
Same issue.

**Comment by bigred1978** [comment]
I have the same issue. .exe file double clicked and nothing happens.

**Comment by NayamAmarshe** [comment]
Windows Defender must be deleting the setup. You have to allow the file in Defender, it's not a virus, it's just Microsoft's antivirus going crazy.

I'll upload another installer, see if that works.

**Comment by NayamAmarshe** [comment]
I'll upload the EXE again.

**Comment by NayamAmarshe** [comment]
https://github.com/upscayl/upscayl/issues/75

**Comment by NayamAmarshe** [comment]
I've updated the EXE, can you please test again?

**Comment by stashymane** [comment]
Works now, thank you :)
