### ISSUE TITLE
Scaler dont work in batch mode.  No matter which upscale we shoose, it  gives the output as 4X

### ISSUE THREAD

**Issue by thanuradw** [upscayl/upscayl#701]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for my issue in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

Scaler not working.. It works as 4x only.  It works in single image upscale. But not working as batch upscale

### To Reproduce

Select the scale you want and check batch upscale and then give a input and output folder. Run it

### Upscayl Version (or commit hash)

2.9.8

### Platform

Linux

### OS Version

Windows 11

### GPU Name

Nvidia Geforce RTX 3060

### Expected Behavior

When we click 2X, it should give us the output image in 2xof original resolution. 

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/57842869/05b95f04-72e4-4eb9-b963-a256636077e3)

### Logs

```sh
🎯 GET_MODELS_LIST:  
🧠 Recalling Output Folder:  E:\##AI Generated\##Upscaled
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🐞 BACKEND REPORTED:  📁 Updating Output Folder Path:  E:\##AI Generated\##Upscaled
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  true
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  true
```

**Comment by aaronliu0130** [comment]
If you have am uppercase file extension, it's #687

**Comment by NayamAmarshe** [comment]
Are you sure you're not stopping the process mid-way? You have to let the Upscayl process finish to get the intended scale and format.

**Comment by thanuradw** [comment]
Its' working.. It scales after every image in the queue is upscaled.

**Comment by thanuradw** [comment]
Thanks everyone
