### ISSUE TITLE
Upscaling options disappear when maximizing/minimizing the window

### ISSUE THREAD

**Issue by woodvale** [upscayl/upscayl#71]
https://user-images.githubusercontent.com/81210414/191131348-3714faf4-3a85-4ac1-8883-bd2ec39b3a34.mp4

Drop down box with upscaling options disappear (or sometimes show empty options for a split second) when maximizing/minimizing the window. Switching focus to another window seems to fix the issue until triggered again.

Tested 1.5 flatpak version.

**Comment by NayamAmarshe** [comment]
You're right, I'll see if this can be fixed.

**Comment by NayamAmarshe** [comment]
https://github.com/upscayl/upscayl/releases/tag/v1.5.5
