### ISSUE TITLE
Request feature : Command line support

### ISSUE THREAD

**Issue by gcoderbh** [upscayl/upscayl#712]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

I would like to use it for automation.
ex.
./upscayl.ext --input-dir="<input>"  --output-dir="output/"  --gpu-id=0  --model="general_ultrasharp"

**Comment by NayamAmarshe** [comment]
> I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).

You most definitely didn't read the FAQ 😄

**Comment by aaronliu0130** [comment]
Also duplicate of #10

**Comment by infinity0** [comment]
Upscayl in fact does have an internal CLI, which you can see, together with its CLI args, in the stdout logs it outputs when processing an image. On GNU/Linux this is located at `/opt/Upscayl/resources/bin/upscayl-bin`. It even takes `--help` so you can see what all the options are.
