### ISSUE TITLE
Add something like Magnific or Krea

### ISSUE THREAD

**Issue by PierrunoYT** [upscayl/upscayl#715]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Add something like Magnific or Krea so it add details which does not exist.

**Comment by NayamAmarshe** [comment]
Upscayl is an AI upscaler, not an AI re-painter. Magnific and those other tools do not upscale, they regenerate the image.

**Comment by PierrunoYT** [comment]
> Upscayl is an AI upscaler, not an AI re-painter. Magnific and those other tools do not upscale, they regenerate the image.

Is there any similar opensource like them?
