### ISSUE TITLE
Option to restore old photos

### ISSUE THREAD

**Issue by PierrunoYT** [upscayl/upscayl#716]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Option to restore old photos. Adding colors, Upscaling, Fix Broken Images etc.

**Comment by aaronliu0130** [comment]
Convert a model with https://github.com/upscayl/upscayl/wiki/Model-Conversion-Guide

**Comment by PierrunoYT** [comment]
> Convert a model with https://github.com/upscayl/upscayl/wiki/Model-Conversion-Guide

Can it be easier?

**Comment by aaronliu0130** [comment]
No, sorry. We already bundle 138MB of models.

**Comment by PierrunoYT** [comment]
There should be an easier solution 😐

**Comment by aaronliu0130** [comment]
Well, we don't see any at this time
