### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by vivadavid** [upscayl/upscayl#72]
Hi,

Windows security has detected a Trojan when running Upscayl.Setup.1.5.0.exe

![Seguridad de Windows - 000926](https://user-images.githubusercontent.com/9334287/191132385-4d3f7e08-f26b-41fd-b10e-6be4c640715f.png)

Also, I've noticed that the Windows installer is much smaller than in previous version.

**Comment by aaronliu0130** [comment]
Wactac.B!ml is well known as (usually) a false positive. I can assure you there is no malware in here. You can check the source if you want.
Devs please submit it to windows defender if you want it to work better on windows. I understand if devs don't.

**Comment by aaronliu0130** [comment]
> Also, I've noticed that the Windows installer is much smaller than in previous version.

See #70 .

**Comment by vivadavid** [comment]
> Wactac.B!ml is well known as (usually) a false positive. I can assure you there is no malware in here. You can check the source if you want. Devs please submit it to windows defender if you want it to work better on windows. I understand if devs don't.

Thanks for the explanation, @aaronliu0130

**Comment by NayamAmarshe** [comment]
I've updated the EXE, can you please test again?

**Comment by vivadavid** [comment]
Hi! No trojan this time: thank you, @NayamAmarshe !
