### ISSUE TITLE
Lens view toggle resets every reload without actually changing the settings

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#725]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for my issue in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

The lens view toggle has a display error, in that upon reload it becomes inactivated no matter the actual settings.

By the way, why did we make lens view the default? The comparison slider is in the logo and shows the changes more effectively and uses the correct background colors

### To Reproduce

1. Toggle comparison mode to slider view
2. Restart/reload
3. Notice that the toggle is now at lens view
4. Upscayl and image and notice that you get the slider view

### Upscayl Version (or commit hash)

2.9.9

### Platform

Windows

### OS Version

Windows 11 23H2

### GPU Name

N/A

### Expected Behavior

I should've seen the toggle in slider view

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/11874211/9f0b147e-aded-4c06-965a-4dbd9e393d67)

### Logs

```sh
🎯 GET_MODELS_LIST:  C:\Users\aaron\Git\custom-models\models
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"realesrgan-x4fast"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🐞 BACKEND REPORTED:  📁 Updating Custom Models Folder Path:  C:\Users\aaron\Git\custom-models\models
🔀 Setting model to realesrgan-x4fast
🐞 BACKEND REPORTED:  📁 Custom Models Folder Path:  C:\Users\aaron\Git\custom-models\models
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  NaN
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  🔎 Detected Custom Models:  4xLSDIRplusC,4x_NMKD-Siax_200k,4x_NMKD-Superscale-SP_178000_G,realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,ultrasharp-2.0.1,uniscale_restore
📜 CUSTOM_MODEL_FILES_LIST:  4xLSDIRplusC,4x_NMKD-Siax_200k,4x_NMKD-Superscale-SP_178000_G,realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,ultrasharp-2.0.1,uniscale_restore
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\aaron\Downloads\low_upscayl_2x_realesrgan-x4fast.png
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\aaron\Downloads\low_upscayl_2x_realesrgan-x4fast.png
🖼 Selected Image Path:  C:\Users\aaron\Downloads\low_upscayl_2x_realesrgan-x4fast.png
📁 Selected Image Directory:  C:\Users\aaron\Downloads
🖼 imagePath:  C:\Users\aaron\Downloads\low_upscayl_2x_realesrgan-x4fast.png
🔤 Extension:  png
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\aaron\Downloads\low.jpg
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\aaron\Downloads\low.jpg
🖼 Selected Image Path:  C:\Users\aaron\Downloads\low.jpg
📁 Selected Image Directory:  C:\Users\aaron\Downloads
🖼 imagePath:  C:\Users\aaron\Downloads\low.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  Is Default Model? :  true
🐞 BACKEND REPORTED:  ✅ Already upscayled at:  C:\Users\aaron\Downloads\low_upscayl_2x_realesrgan-x4fast.png
upscaledImagePath:  C:\Users\aaron\Downloads\low_upscayl_2x_realesrgan-x4fast.png
💯 UPSCAYL_DONE:  C:\Users\aaron\Downloads\low_upscayl_2x_realesrgan-x4fast.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"realesrgan-x4fast"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
```

**Comment by NayamAmarshe** [comment]
Oops, I think I forgot to make it persistent

**Comment by allbut0ne** [comment]
I can't see anything but a circle. The lens view has no effect.

**Comment by aaronliu0130** [comment]
@allbut0ne You can drag the circle or click on the image. That is the intended behavior of lens view, although I agree that it is inferior to the slider in most cases.

**Comment by allbut0ne** [comment]
@aaronliu0130 Yes, I thought that's how it would have to work. But I'm afraid it's not working on my computer. I only have a circle without any functionality. (macOS 14.1.2)

**Comment by aaronliu0130** [comment]
That's weird, could you file another issue with a screen recording?

**Comment by aaronliu0130** [comment]
The button on the right includes a slider for zooming.

-- 
Cheers,
Aᴀʀᴏɴ

**Comment by allbut0ne** [comment]
You're right! I thought this slider wouldn't work either. But it only takes effect when the cursor leaves the area and returns to the image. And 100% is not what Photoshop understands by 100%.
But anyway – my fault.

**Comment by NayamAmarshe** [comment]
Closing because slider is now the default.

**Comment by aaronliu0130** [comment]
Issue with the setting resetting seems to be fixed.
