### ISSUE TITLE
UPSCAYL DOES NOTHING

### ISSUE THREAD

**Issue by BFC17** [upscayl/upscayl#736]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

I select the image, click upscale, then nothing happens, no image output.
I Noticed the line: "dzn is not a conformant Vulkan implementation, testing use only" But my GPU should be compatible with Vulkan. I also noticed that my GPU isn't "recognised" like in everyone else logs
I then Tried to put "0" in GPUid but the problem still occurs.

### To Reproduce

Just run an Upscale

### Upscayl Version (or commit hash)

2.9.9

### Platform

Windows

### OS Version

Windows 11 Home

### GPU Name

AMD Radeon RX6600M

### Expected Behavior

The upscale 4x of an image.

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/162055409/07554034-8958-4d72-a2f8-38ed015ac2c1)

### Logs

```sh
🧠 Recalling Output Folder:  C:\Users\aless\Desktop
🐞 BACKEND REPORTED:  📁 Updating Output Folder Path:  C:\Users\aless\Desktop
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  true
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\aless\Desktop\image.png
🖼 Selected Image Path:  C:\Users\aless\Desktop\image.png
📁 Selected Image Directory:  C:\Users\aless\Desktop
🖼 imagePath:  C:\Users\aless\Desktop\image.png
🔤 Extension:  png
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\aless\Desktop\image.png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  Is Default Model? :  true
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"C:\\Users\\aless\\Desktop","outputDir":"C:\\Users\\aless\\Desktop","fullfileName":"image.png","fileName":"image","initialScale":"4","desiredScale":"4","outFile":"C:\\Users\\aless\\Desktop\\image_upscayl_4x_realesrgan-x4plus.png","compression":0}
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\aless\Desktop\image.png,-o,C:\Users\aless\Desktop\image_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-f,png
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\aless\\Desktop\\image.png","-o","C:\\Users\\aless\\Desktop\\image_upscayl_4x_realesrgan-x4plus.png","-s","4","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png"]}
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  image upscayl:  WARNING: dzn is not a conformant Vulkan implementation, testing use only.

🚧 UPSCAYL_PROGRESS:  WARNING: dzn is not a conformant Vulkan implementation, testing use only.

🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
🐞 BACKEND REPORTED:  Skipping compression for 4x scale and 0% compression
upscaledImagePath:  C:\Users\aless\Desktop\image_upscayl_4x_realesrgan-x4plus.png
💯 UPSCAYL_DONE:  C:\Users\aless\Desktop\image_upscayl_4x_realesrgan-x4plus.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  true
```

**Comment by PierrunoYT** [comment]
🧠 Recalling Output Folder:  C:\Users\pierr\Downloads\Upscayl
🐞 BACKEND REPORTED:  📁 Updating Output Folder Path:  C:\Users\pierr\Downloads\Upscayl
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  true
🔀 Setting model to ultramix_balanced
🔄 Resetting image paths
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\pierr\Downloads\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0.png
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\pierr\Downloads\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0.png
🖼 Selected Image Path:  C:\Users\pierr\Downloads\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0.png
📁 Selected Image Directory:  C:\Users\pierr\Downloads
🖼 imagePath:  C:\Users\pierr\Downloads\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  Is Default Model? :  true
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"ultramix_balanced","gpuId":null,"saveImageAs":"jpg","inputDir":"C:\\Users\\pierr\\Downloads","outputDir":"C:\\Users\\pierr\\Downloads","fullfileName":"14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0.png","fileName":"14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0","initialScale":"4","desiredScale":"4","outFile":"C:\\Users\\pierr\\Downloads\\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0_upscayl_4x_ultramix_balanced.jpg","compression":0}
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\pierr\Downloads\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0.png,-o,C:\Users\pierr\Downloads\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0_upscayl_4x_ultramix_balanced.jpg,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultramix_balanced,-f,jpg
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\pierr\\Downloads\\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0.png","-o","C:\\Users\\pierr\\Downloads\\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0_upscayl_4x_ultramix_balanced.jpg","-s","4","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","ultramix_balanced","-f","jpg"]}
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  image upscayl:  [0 NVIDIA GeForce RTX 4090]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4090]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4090]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4090]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 4090]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4090]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4090]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4090]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  image C:\Users\pierr\Downloads\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0.png has alpha channel ! C:\Users\pierr\Downloads\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0.png will output C:\Users\pierr\Downloads\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0_upscayl_4x_ultramix_balanced.jpg.png

🚧 UPSCAYL_PROGRESS:  image C:\Users\pierr\Downloads\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0.png has alpha channel ! C:\Users\pierr\Downloads\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0.png will output C:\Users\pierr\Downloads\14490_((masterpiece)), ((best quality)), ((detailed)), V_xl-1024-v1-0_upscayl_4x_ultramix_balanced.jpg.png

🐞 BACKEND REPORTED:  📢 INCLUDES ALPHA CHANNEL, CHANGING OUTFILE NAME!
🐞 BACKEND REPORTED:  image upscayl:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🐞 BACKEND REPORTED:  image upscayl:  3.57%

🚧 UPSCAYL_PROGRESS:  3.57%

🐞 BACKEND REPORTED:  image upscayl:  7.14%

🚧 UPSCAYL_PROGRESS:  7.14%

🐞 BACKEND REPORTED:  image upscayl:  10.71%

🚧 UPSCAYL_PROGRESS:  10.71%

🐞 BACKEND REPORTED:  image upscayl:  14.29%

🚧 UPSCAYL_PROGRESS:  14.29%

🐞 BACKEND REPORTED:  image upscayl:  17.86%

🚧 UPSCAYL_PROGRESS:  17.86%

🐞 BACKEND REPORTED:  image upscayl:  21.43%

🚧 UPSCAYL_PROGRESS:  21.43%

🐞 BACKEND REPORTED:  image upscayl:  25.00%

🚧 UPSCAYL_PROGRESS:  25.00%

🐞 BACKEND REPORTED:  image upscayl:  28.57%

🚧 UPSCAYL_PROGRESS:  28.57%

🐞 BACKEND REPORTED:  image upscayl:  32.14%

🚧 UPSCAYL_PROGRESS:  32.14%

🐞 BACKEND REPORTED:  image upscayl:  35.71%

🚧 UPSCAYL_PROGRESS:  35.71%

🐞 BACKEND REPORTED:  image upscayl:  39.29%

🚧 UPSCAYL_PROGRESS:  39.29%

🐞 BACKEND REPORTED:  image upscayl:  42.86%

🚧 UPSCAYL_PROGRESS:  42.86%

🐞 BACKEND REPORTED:  image upscayl:  46.43%

🚧 UPSCAYL_PROGRESS:  46.43%

🐞 BACKEND REPORTED:  image upscayl:  50.00%

🚧 UPSCAYL_PROGRESS:  50.00%

🐞 BACKEND REPORTED:  image upscayl:  53.57%

🚧 UPSCAYL_PROGRESS:  53.57%

🐞 BACKEND REPORTED:  image upscayl:  57.14%

🚧 UPSCAYL_PROGRESS:  57.14%

🐞 BACKEND REPORTED:  image upscayl:  60.71%

🚧 UPSCAYL_PROGRESS:  60.71%

🐞 BACKEND REPORTED:  image upscayl:  64.29%

🚧 UPSCAYL_PROGRESS:  64.29%

🐞 BACKEND REPORTED:  image upscayl:  67.86%

🚧 UPSCAYL_PROGRESS:  67.86%

🐞 BACKEND REPORTED:  image upscayl:  71.43%

🚧 UPSCAYL_PROGRESS:  71.43%

🐞 BACKEND REPORTED:  image upscayl:  75.00%

🚧 UPSCAYL_PROGRESS:  75.00%

🐞 BACKEND REPORTED:  image upscayl:  78.57%

🚧 UPSCAYL_PROGRESS:  78.57%

🐞 BACKEND REPORTED:  image upscayl:  82.14%

🚧 UPSCAYL_PROGRESS:  82.14%

🐞 BACKEND REPORTED:  image upscayl:  85.71%

🚧 UPSCAYL_PROGRESS:  85.71%

🐞 BACKEND REPORTED:  image upscayl:  89.29%

🚧 UPSCAYL_PROGRESS:  89.29%

🐞 BACKEND REPORTED:  image upscayl:  92.86%

🚧 UPSCAYL_PROGRESS:  92.86%

🐞 BACKEND REPORTED:  image upscayl:  96.43%

🚧 UPSCAYL_PROGRESS:  96.43%

🐞 BACKEND REPORTED:  image upscayl:  Upscayl Successful

🚧 UPSCAYL_PROGRESS:  Upscayl Successful

🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
🐞 BACKEND REPORTED:  Skipping compression for 4x scale and 0% compression
upscaledImagePath:  C:\Users\pierr\Downloads\14490_((masterpiece))%2C%20((best%20quality))%2C%20((detailed))%2C%20V_xl-1024-v1-0_upscayl_4x_ultramix_balanced.jpg
💯 UPSCAYL_DONE:  C:\Users\pierr\Downloads\14490_((masterpiece))%2C%20((best%20quality))%2C%20((detailed))%2C%20V_xl-1024-v1-0_upscayl_4x_ultramix_balanced.jpg
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  true

**Comment by BFC17** [comment]
So any solutions? @aaronliu0130

**Comment by aaronliu0130** [comment]
Dunno. That's the first time we've seen this issue. The best I could find was https://stackoverflow.com/questions/77913326/vkcreateinstance-crashes-even-after-updating-drivers

**Comment by BFC17** [comment]
> Dunno. That's the first time we've seen this issue. The best I could find was https://stackoverflow.com/questions/77913326/vkcreateinstance-crashes-even-after-updating-drivers

Unistalling OpenCL compatibility from microsoft store fixed it!
Thank you.
