### ISSUE TITLE
Upscaly is not working during Batch Upscale. Its Stacked-on o upscaled

### ISSUE THREAD

**Issue by Reazour-Rahman** [upscayl/upscayl#737]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

Upscaly is not working during Batch Upscale. Single Upscale is working fine but When I try to upscale batch images it is stacked on 0 upscaled and even I can't stop upscale as well (Stop button is also not working). I thought it was my GPU issue. For that I cleaned up my GPU using DDU Uninstaller and Installed latest version of GPU. Note that my GPU is intel Arc a750 series which is a Vulkan Supported GPU and It had been working very faster with Upscaly software previous time. After this process nothing happened and I uninstalled Upscaly as well and installed latest one. But still same issue occurring.

### To Reproduce

You can contact the bug identifier to see what the problem is. Take action about it.

### Upscayl Version (or commit hash)

2.9.9 and Previous version as well

### Platform

Windows

### OS Version

Windows 11 Pro 23H2

### GPU Name

Intel Arc A750 8GB

### Expected Behavior

Smooth upscaling during Batch upscale

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/86196606/9700349d-6410-4f7e-9c0e-214195cfaeaf)

### Logs

```sh
🎯 GET_MODELS_LIST:  
🧠 Recalling Output Folder:  C:\Downloads\Upscaled\First
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🐞 BACKEND REPORTED:  📁 Updating Output Folder Path:  C:\Downloads\Upscaled\First
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  true
🐞 BACKEND REPORTED:  📐 Updating Compression:  NaN
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  true
```

**Comment by Reazour-Rahman** [comment]
I solved it. My Raw file location was in Local C. When I moved those files in working Locals E. It is now working. If you have same issue You guys can fix it by moving From C drive.

**Comment by aaronliu0130** [comment]
That sounds like a bug. What's a "stacked" upscayl?
