### ISSUE TITLE
Sharpen Image

### ISSUE THREAD

**Issue by Koba-Hiro** [upscayl/upscayl#74]
Very, very good software.
Thank you very much.
What are the differences between the "Digital Art" and "Sharpen Image" processes?

**Comment by NayamAmarshe** [comment]
DIgital Art uses Real-ESRGAN model and Sharpen uses DF2K model.

**Comment by Koba-Hiro** [comment]
Thanks.

**Comment by Rybec** [comment]
@NayamAmarshe So wait, does this mean that "Digital Art" is identical to "General Photo (Real-ESRGAN)"?

(I'm using both Upscayle for manual stuff and the Real-ESRGAN CLI executable for automation, and I'm trying to work out how to do the "Digital Art" setting on the Real-ESRGAN CLI.)

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe So wait, does this mean that "Digital Art" is identical to "General Photo (Real-ESRGAN)"?
> 
> (I'm using both Upscayle for manual stuff and the Real-ESRGAN CLI executable for automation, and I'm trying to work out how to do the "Digital Art" setting on the Real-ESRGAN CLI.)

Digital art is just a different model. It's still Real-ESRGAN.

**Comment by Rybec** [comment]
Ah, I see.  Which model is it?

**Comment by NayamAmarshe** [comment]
> Ah, I see. Which model is it?

https://github.com/upscayl/upscayl/blob/main/renderer/components/LeftPaneImageSteps.tsx#L125

**Comment by Rybec** [comment]
Thank you!  That answers my question.
