### ISSUE TITLE
Perform a clean upscale, without sharpening the image

### ISSUE THREAD

**Issue by ashilon** [upscayl/upscayl#742]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

I've tested all the built in models on my images, 
and all of them sharpen the images, even when the option "DON'T POST-PROCESS IMAGE" is turned off.
Is it possible to add an option to do a clean upscale? without sharpening the image?
Sharpening adds a kind of artificial look to images which isn't necessarily what we want.
Is it possible to get a 1 to 1 copy of the original image after upscaling?
Perhaps there is a model that already behaves like that?
Thank you very much for your kind efforts and contributions.

**Comment by aaronliu0130** [comment]
Just use mspaint resizing.

**Comment by ashilon** [comment]
I see.
OK sorry I was misunderstood,
so if post-processing is just the part of changing he dimensions of the image,
then that's what I think would be great addition to the software,
basically letting us do the opposite of how it works today,
choose only the post processing (resize) of the image, without upscaling it.

**Comment by Woisek** [comment]
> choose only the post processing (resize) of the image, without upscaling it.

Then just resize it in any program that is capable of resizing an image and turn all 'enhancements' off. 🤷‍♂️
But you are aware, that 'resizing' means up or down scaling, right?
Also:

> Is it possible to get a 1 to 1 copy of the original image after upscaling?

No. Except: Make a copy of it. Anything else means it will be altered in some way and therefore is no 1:1 copy anymore.
