### ISSUE TITLE
Request: option in settings to control parallel image upscayling when doing a batch upscayl

### ISSUE THREAD

**Issue by gaiking-uk** [upscayl/upscayl#744]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

I recently raised bug #743 and believe this may have been caused because upscayl was trying to work on multiple images in parallel.

If this can be confirmed in testing, then it would be useful if there was an option to either:
- Disable parallel image upscayling (boolean), or
- Limit the max. number of images to be upscayled in parallel (int)

### Related Problem(s)

#743 Batch upscayl of large images fails (upscayling each image individual works)

**Comment by NayamAmarshe** [comment]
The NCNN project has an option like that but it's broken. Will revisit in the future and add the option in settings :)
