### ISSUE TITLE
[FEATURE][v3] Preserve EXIF and ICCProfile Data

### ISSUE THREAD

**Issue by NayamAmarshe** [upscayl/upscayl#746]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Get sharp.js to somehow preserve all the metadata, including the ICCProfile.

**Comment by MrPenguin07** [comment]
If "Preserve EXIF data" could be added as a toggle that would be useful I think.

Oftentimes I don't want it preserved in images that i've upscayled :)
