### ISSUE TITLE
Error processing (scaling and converting) the image. Please report this error on GitHub. Error: Input file is missing:

### ISSUE THREAD

**Issue by bastcazaux** [upscayl/upscayl#747]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [X] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

during process Error processing (scaling and converting) the image. Please report this error on GitHub. Error: Input file is missing:
at the end : Abandon (core dumped)

### To Reproduce

start any convert image 

### Upscayl Version (or commit hash)

v2.10

### Platform

Linux

### OS Version

kubuntu 20.04

### GPU Name

no

### Logs

```sh
14:22:39.305 › 💯 Done upscaling
14:22:39.306 › ♻ Scaling and converting now...
14:22:39.308 › 🐞 BACKEND REPORTED:  💯 Done upscaling
14:22:39.309 › 📐 Processing Image:  {"originalWidth":3884,"originalHeight":2857,"customWidth":null,"scale":"2","saveImageAs":"jpg","compressionPercentage":50,"compressionLevel":5}
14:22:39.310 › 🖼️ Checking if original image exists:  image.jpg
14:22:39.311 › ❌ Error processing (scaling and converting) the image. Please report this error on GitHub. Error: Input file is missing: image_upscayl_2x_realesrgan-x4fast.jpg
14:22:39.311 › 🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
14:22:39.312 › 🐞 BACKEND REPORTED:  📐 Processing Image:  {"originalWidth":3884,"originalHeight":2857,"customWidth":null,"scale":"2","saveImageAs":"jpg","compressionPercentage":50,"compressionLevel":5}
14:22:39.313 › 🐞 BACKEND REPORTED:  🖼️ Checking if original image exists:  image.jpg
14:22:39.313 › 🐞 BACKEND REPORTED:  ❌ Error processing (scaling and converting) the image. Please report this error on GitHub. Error: Input file is missing: image_upscayl_2x_realesrgan-x4fast.jpg
14:22:41.921 › 🔄 Resetting image paths

***MEMORY-ERROR***: upscayl[39380]: GSlice: assertion failed: sinfo->n_allocated > 0
Abandon (core dumped)
```

**Comment by aaronliu0130** [comment]
Sounds like you ran out of memory.

**Comment by aaronliu0130** [comment]
> ### GPU Name
>
> no

Huh?
