### ISSUE TITLE
Error when scaling and converting the image

### ISSUE THREAD

**Issue by KenSakuraba** [upscayl/upscayl#749]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

A few weeks ago I tried to scale some images, however, Upscayl has been crashing. Because, when I try to convert an image, the process completes instantly, but nothing happens. Only a failed image icon appears, no image is saved.

### To Reproduce

start any convert image

### Upscayl Version (or commit hash)

v2.10

### Platform

Windows

### OS Version

Windows 11 23H2

### GPU Name

AMD Radeon™ Graphics

### Expected Behavior

It should process correctly

### Screenshots

https://github.com/upscayl/upscayl/assets/163465005/3f8433fa-5d8d-4d48-b1f2-8480f65ce9bf

### Logs

```sh
⚙️ Setting saveImageAs to png
🔀 Setting model to realesrgan-x4plus
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\Sebas\Downloads\Compare\Sheera 1.remini.png
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\Sebas\Downloads\Compare\Sheera 1.remini.png
🖼 Selected Image Path:  C:\Users\Sebas\Downloads\Compare\Sheera 1.remini.png
📁 Selected Image Directory:  C:\Users\Sebas\Downloads\Compare
🖼 imagePath:  C:\Users\Sebas\Downloads\Compare\Sheera 1.remini.png
🔤 Extension:  png
🐞 BACKEND REPORTED:  📁 Updating Folder Path:  C:\Users\Sebas\Downloads\Compare\WIN
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\Sebas\Downloads\Compare\WIN
🗂 Setting Output Path:  C:\Users\Sebas\Downloads\Compare\WIN
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  Is Default Model? :  true
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"C:\\Users\\Sebas\\Downloads\\Compare","outputDir":"C:\\Users\\Sebas\\Downloads\\Compare\\WIN","fullfileName":"Sheera 1.remini.png","fileName":"Sheera 1.remini","initialScale":"4","desiredScale":"4","outFile":"C:\\Users\\Sebas\\Downloads\\Compare\\WIN\\Sheera 1.remini_upscayl_4x_realesrgan-x4plus.png","compression":0}
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Sebas\Downloads\Compare\Sheera 1.remini.png,-o,C:\Users\Sebas\Downloads\Compare\WIN\Sheera 1.remini_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-f,png
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\Sebas\\Downloads\\Compare\\Sheera 1.remini.png","-o","C:\\Users\\Sebas\\Downloads\\Compare\\WIN\\Sheera 1.remini_upscayl_4x_realesrgan-x4plus.png","-s","4","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png"]}
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
🐞 BACKEND REPORTED:  Skipping compression for 4x scale and 0% compression
upscaledImagePath:  C:\Users\Sebas\Downloads\Compare\WIN\Sheera%201.remini_upscayl_4x_realesrgan-x4plus.png
💯 UPSCAYL_DONE:  C:\Users\Sebas\Downloads\Compare\WIN\Sheera%201.remini_upscayl_4x_realesrgan-x4plus.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Setting rememberOutputFolder to false
```

**Comment by aaronliu0130** [comment]
What is the name of your GPU?

**Comment by KenSakuraba** [comment]
> What is the name of your GPU? Is there a file in the output folder?

1. I think my GPU is AMD Radeon™ Graphics (AMD Ryzen™ 7 4800H). This is what appears in dxdiag.
2. No, there is not a single new file in the output folder.

**Comment by aaronliu0130** [comment]
That's integrated.

> Yes, unfortunately. NCNN Vulkan requires a Vulkan-compatible GPU. Upscayl won't work with most iGPUs or CPUs.

A workaround exists for Windows and Linux in #580.

> I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

![compulsory rickrolls are issued for duplicates of issues and the FAQ and normies who use intelgrated GPUs](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Comment by KenSakuraba** [comment]
> workaround

I also have a NVIDIA RTX 3050. Upscayl worked just fine a few weeks ago, so I don't think my GPU is not compatible.

**Comment by aaronliu0130** [comment]
If you mean you have both GPUs, you should try setting the GPU ID.

**Comment by KenSakuraba** [comment]
> If you mean you have both GPUs, you should try setting the GPU ID. I see that you have no outputs, but you can try 0, 1, or 2.

Yeah, I tried that. Right now, I put 1 and it works again, thanks. But it stops working after a while, I will try to stick with this, thanks :).
