### ISSUE TITLE
Mouse movement and activity of other Windows programs gets stuck and released, during image processing

### ISSUE THREAD

**Issue by cgcore** [upscayl/upscayl#751]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [X] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

freezes 
Mouse movement freezes 
stuck and released everything
cant use gpu id section said use vulkan

### To Reproduce

i downloaded and start to use, thats all

### Upscayl Version (or commit hash)

2.9.9

### Platform

Windows

### OS Version

Windows 11 Enterprise 22H2 OS build: 22621.3296

### GPU Name

NVIDIA GeForce GTX650

### Expected Behavior

The entire Windows and mouse freezes every 3 to 4 seconds while zooming in and clarifying the image until the 100% processing is finished. Mouse movement and activity of other Windows programs gets stuck and released, gets stuck and released, and so on until the end of the processing. I have tested all versions and it is still the same. It prevents me from doing other tasks.

### Screenshots

here is a video that i capture during process. 

https://github.com/upscayl/upscayl/assets/106352513/ca392369-0f97-4b3b-9aaf-a451a4cf0900

### Logs

```sh
🎯 GET_MODELS_LIST:  
🧠 Recalling Output Folder:  D:\work\sea
🐞 BACKEND REPORTED:  📁 Updating Output Folder Path:  D:\work\sea
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  true
🐞 BACKEND REPORTED:  📐 Updating Compression:  NaN
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  true
🐞 BACKEND REPORTED:  🔕 Updating Turn Off Notifications:  false
🐞 BACKEND REPORTED:  📏 Updating Use Custom Width:  false
🔀 Setting model to ultrasharp
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  true
```

**Comment by aaronliu0130** [comment]
Unfortunately, that seems like a problem with your driver/hardware.
