### ISSUE TITLE
Add postprocessing sliders to main tab

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#754]
### Discussed in https://github.com/orgs/upscayl/discussions/753
<sup>Originally posted by **1001celeritas** March 19, 2024</sup>

Adding it as a step 5 may also make clearer that this is post-processing.

**Comment by NayamAmarshe** [comment]
Ah good idea!

**Comment by NayamAmarshe** [comment]
Added in v2.11
