### ISSUE TITLE
Image extended 

### ISSUE THREAD

**Issue by Vortex1x1x1x** [upscayl/upscayl#755]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

I think it would be cool if instead of just upscaling images upscayl could expand images like in the image below. i think it would also be super cool if you added some generation stuff like in adobe photoshop.
![image](https://github.com/upscayl/upscayl/assets/146856669/19de2519-d655-45fd-b3d1-cc7617e2305e)

**Comment by aaronliu0130** [comment]
Unfortunately, this is out-of-scope for our project, a GUI for a fork of something that just upscales. Hopefully you can find the tool you love!

**Comment by Vortex1x1x1x** [comment]
Oh I understand it would definitely take a lot to make that
