### ISSUE TITLE
Add this model?

### ISSUE THREAD

**Issue by happysurf** [upscayl/upscayl#756]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

This model is great for all images, and in my opinion is slightly better than Real-ESRGAN, especially on small details.

The model is here:
https://github.com/chenxwh/rudalle-sr

Try here:
https://replicate.com/cjwbw/rudalle-sr

**Comment by aaronliu0130** [comment]
We don't plan on changing our upscayling framework in the near future, and nor do we plan on introducing pip dependency hell in the next update.
