### ISSUE TITLE
Make slider view the default

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#760]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Slider view creates much more of an impression of the difference in image quality, and the iconic slider is in our logo.

### Related Problem(s)

Lens view can be very confusing on first sight, as seen in reports such as #759.

**Comment by NayamAmarshe** [comment]
I'll make this a priority. I'll work on the new build from tomorrow
