### ISSUE TITLE
AppImage contains wrong version in desktop file

### ISSUE THREAD

**Issue by vitlav** [upscayl/upscayl#761]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

release upscayl-2.10.0-linux.AppImage contains X-AppImage-Version=23.11.4

### To Reproduce

```
download https://github.com/upscayl/upscayl/releases/download/v2.10.0/upscayl-2.10.0-linux.AppImage
chmod u+x upscayl-2.10.0-linux.AppImage
./upscayl-2.10.0-linux.AppImage --appimage-extract
grep X-AppImage-Version squashfs-root/upscayl.desktop
X-AppImage-Version=23.11.4

```

### Upscayl Version (or commit hash)

2.10.0

### Platform

Linux

### OS Version

Linux

### GPU Name

does not matter

### Expected Behavior

X-AppImage-Version filled with release version.

### Logs

```sh
grep X-AppImage-Version squashfs-root/upscayl.desktop
X-AppImage-Version=23.11.4
```

**Comment by NayamAmarshe** [comment]
Ok, I'll fix this. Thanks for letting me know!
