### ISSUE TITLE
Option to disable app animations while upscaling

### ISSUE THREAD

**Issue by TIRTAGT** [upscayl/upscayl#767]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [x] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

I noticed during upscaling on a dedicated Nvidia GPU, my GPU 0 (Integrated Intel Iris Xe GPU, this is a laptop) is also heavily loaded:
![image](https://github.com/upscayl/upscayl/assets/55649705/65bc8b6d-4f09-44f4-8c72-0950a423719b)

The high utilization on GPU 0 or the iGPU is solved temporarily when upscayl window is minimized:
![image](https://github.com/upscayl/upscayl/assets/55649705/f6ba0cfb-02b7-40af-99c3-49ca8c1467a9)

I believe the high utilization is because of the upscayl animation:
![image](https://github.com/upscayl/upscayl/assets/55649705/6db7868e-5059-4039-b9db-8259cd9b4d2a)

although it's a pretty general/basic animation, but it looks like that's still *that* heavy for the integrated GPU.

And for laptop or even desktops with limited cooling capacity, having an option to disable app animation is nice.

### Related Problem(s)

> 💥 Are there any problems that coerced you into filing this feature request?

Yes, my GPU are overheating as the heatsink is shared with the CPU (and therefore iGPU) 🤣
![image](https://github.com/upscayl/upscayl/assets/55649705/a889cdc4-34a7-4882-b349-fddf727a5588)

Blue = CPU (Intel), Green = the dedicated Nvidia GPU

### Alternatives

Minimize the upscayl window, this seems to stop the issue temporarily as the iGPU doesn't need to render the animation if the window isn't active.

**Comment by aaronliu0130** [comment]
Wow, Intel Iris, le premium integrated graphics, can't handle a spinning wheel?

**Comment by TIRTAGT** [comment]
> Wow, Intel Iris, le premium integrated graphics, can't handle a spinning wheel?

Yup, It's my first time using upscayl on this laptop, mostly used upscayl on my PC with just  Ryzen 5 5600G (and it's iGPU), that handled upscayl a lot better than this laptop if ignoring the RTX 3050.

----

Lenovo paired this entry gaming laptop with RTX 3050 with a 11th gen Intel i5-11320H, a pretty _trash_ combination in my opinion.

**Comment by aaronliu0130** [comment]
Jesus Christ. And you set the GPU ID, right?

**Comment by TIRTAGT** [comment]
> Jesus Christ. And you set the GPU ID, right?

Yes, because I want to make sure the dedicated nvidia is used and not the integrated one.

**Comment by NayamAmarshe** [comment]
That's so weird haha. Maybe I can turn the animation into a webm file?

**Comment by TIRTAGT** [comment]
Probably that would help (I have no specific idea if it solves the issue though, but I can test if you set me up with a patch for that).

I believe having an option to turn the animation off is harder than trying to work around for the poor iGPU performance?

**Comment by NayamAmarshe** [comment]
> Probably that would help (I have no specific idea if it solves the issue though, but I can test if you set me up with a patch for that).
> 
> I believe having an option to turn the animation off is harder than trying to work around for the poor iGPU performance?

Oh I can certainly add that as an option, no worries :)

**Comment by NayamAmarshe** [comment]
I have replaced the huge 1024px logo image with a small svg, this should hopefully not cause issues anymore.

**Comment by NayamAmarshe** [comment]
I did not add an option to disable all animations because DaisyUI and ShadCN mess with the no-animation class and it's also something very specific. I hope this svg replacement works.
