### ISSUE TITLE
Example Output

### ISSUE THREAD

**Issue by WolfeJAM** [upscayl/upscayl#775]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Not really a suggestion, more of a question: 

Is there a set of example images showing the different models' output to compare?

### Alternatives

The work round is going through and trying every one listed on a test image

**Comment by aaronliu0130** [comment]
Check out https://github.com/upscayl/upscayl#%EF%B8%8F-results.
