### ISSUE TITLE
Windows app does not launch

### ISSUE THREAD

**Issue by Feoryc** [upscayl/upscayl#777]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

When running the exe, both on normal and admin, the app windows does not launch.

### To Reproduce

Install either zip or exe

run the exe file

### Upscayl Version (or commit hash)

2.10.0

### Platform

Windows

### OS Version

Windows 11

### GPU Name

RTX 3080

### Screenshots

![Screenshot 2024-04-17 115557](https://github.com/upscayl/upscayl/assets/161250243/00aff2e7-7205-4c06-bdd3-50358b433f29)

### Logs

```sh
I was not able to open the app
```

**Comment by NayamAmarshe** [comment]
Probably a corrupt installation/corrupt files.

**Comment by Feoryc** [comment]
Solved: It had to be installed at the OS drive
