### ISSUE TITLE
Option to set the upscale size

### ISSUE THREAD

**Issue by PierrunoYT** [upscayl/upscayl#785]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Option to set the upscale image size so I cant save it as a Desktop Background

### Related Problem(s)

I can't save the upscaled images as desktop background.

**Comment by aaronliu0130** [comment]
![image](https://github.com/upscayl/upscayl/assets/11874211/ef8a4c3a-be28-4ac5-ba2b-e1cfbe6e189a)

**Comment by PierrunoYT** [comment]
Did not see that. Thx
