### ISSUE TITLE
Run cli get segmentation fault on macOS

### ISSUE THREAD

**Issue by xtremforce** [upscayl/upscayl#788]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

try:
`/Applications/Upscayl.app/Contents/Resources/bin/upscayl-bin -i /path/to/img -o "/path/to/output`
get error:
`[1]    12738 segmentation fault  /Applications/Upscayl.app/Contents/Resources/bin/upscayl-bin -i  -o`

### To Reproduce

just run on cli:
`/Applications/Upscayl.app/Contents/Resources/bin/upscayl-bin -i /path/to/img -o "/path/to/output`

### Upscayl Version (or commit hash)

v2.10.0

### Platform

Mac DMG / Homebrew

### OS Version

macOS Sonoma 14.4.1 

### GPU Name

M1

### Logs

```sh
[1]    12738 segmentation fault  /Applications/Upscayl.app/Contents/Resources/bin/upscayl-bin -i  -o
```

**Comment by aaronliu0130** [comment]
Which image paths did you give it?

**Comment by xtremforce** [comment]
> Which image paths did you give it?

I tried various different images, but none of them worked.
I guess the error occurred during the process of reading parameters, and it should have nothing to do with the image itself.

**Comment by xtremforce** [comment]
I also tried something like these:
```
upscayl-bin -i/path1 -o/path2
upscayl-bin -i "/path1" -o "/path2"
upscayl-bin -i=/path1 -o=/path2
```
no luck.

**Comment by NayamAmarshe** [comment]
Try the upscayl-bin from upscayl-ncnn repository. You shouldn't be running the binary directly from the Upscayl Desktop package.

**Comment by xtremforce** [comment]
Use upscayl-bin from upscayl-ncnn worked!! Thank you!
