### ISSUE TITLE
Error processing (scaling and converting) the image.

### ISSUE THREAD

**Issue by mschoenb76** [upscayl/upscayl#789]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [X] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

Image upscaling doesn't produce and new/larger file.

### To Reproduce

I open the Upscayl app and drag the image file onto it. Then it begins to process the image, but at some point in the process, it gives me this error message: Error processing (scaling and converting) the image. Please report this error on Upscayl GitHub Issues page. Error: Could not grab the original image! All processing stops.

### Upscayl Version (or commit hash)

2.9.5 (23.11.4)

### Platform

Mac DMG / Homebrew

### OS Version

Ventura 13.6.2

### GPU Name

32-core GPU

### Expected Behavior

I've been using the app for a couple of months and it's worked great! It's the best I've been able to find. It should export out a larger resolution file.

### Screenshots

![Screenshot 2024-04-24 at 11 19 02 AM](https://github.com/upscayl/upscayl/assets/70965348/9a63ea49-e546-4b5b-9812-085361feba43)

### Logs

```sh
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"realesrgan-x4fast"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4fast
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"realesrgan-x4fast"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
```

**Comment by NayamAmarshe** [comment]
Hi, this error won't appear in v2.11. For now you can try to v2.11 Pre-release :)
