### ISSUE TITLE
Allow Video Upscaling, detect ext and set model accordingly

### ISSUE THREAD

**Issue by NayamAmarshe** [upscayl/upscayl#79]

**Comment by aaronliu0130** [comment]
@NayamAmarshe Do we have an update on this?

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe Do we have an update on this?

This will be in a future update.

**Comment by NayamAmarshe** [comment]
@aaronliu0130 I kinda meant far future 😅 
Right now, my priority is to improve the wiki and prompts in the UI and fix any small bugs. I'll be spending time daily on the project starting next week :)

**Comment by Kaiddd** [comment]
Honestly not allowing videos is the only thing stopping this project from being a daily tool for me

**Comment by Lolagatorade** [comment]
There’s some projects out for video upscaling. Hopefully itlle be integrated soon it would be very useful as no projects as of now to run on Linux with GUI


https://github.com/k4yt3x/video2x

**Comment by Kaiddd** [comment]
> There’s some projects out for video upscaling. Hopefully itlle be integrated soon it would be very useful as no projects as of now to run on Linux with GUI
> 
> 
> https://github.com/k4yt3x/video2x
> 

video2x has weird issues on my machine unsure why, but yeah I would love to use this nice little gui on my Linux machine!

**Comment by aaronliu0130** [comment]
um, what

**Comment by NayamAmarshe** [comment]
> um, is this never planned anymore?

Yes, kinda. I will be adding this feature on Upscayl Cloud but doing the same on Desktop is kinda hard with just node modules.

**Comment by Kaiddd** [comment]
@NayamAmarshe what's the difficulties with node modules, any specific problem I could perhaps look into solving myself?

**Comment by NayamAmarshe** [comment]
Well, for one, the Real-ESRGAN NCNN doesn't really process a large number of images. So, having video upscaling would be extremely difficult since the base itself might refuse to process the images.

The other issue is metadata like framerate and everything else. You can convert a video into frames but converting those frames into video is difficult. That's why I gave up the idea of video upscaling in the first place.

Hopefully though, this won't be a problem on cloud.

**Comment by Kaiddd** [comment]
Don't know much about the upscaling process, but I have some ideas for the above issues

It'd be hacky, but you could do it in groups of the maximum it'd process, and framerates aren't an issue either if you're willing to ignore speed, you could use ffmpeg to extract each specific frame from the video, and then replace that frame afterwards
https://superuser.com/a/1010108

I'll write an example of frame extraction and replacing, without needing to account for framerate in py and reply it here

**Comment by Kaiddd** [comment]
@NayamAmarshe Ping because I edited above message, incase you've already seen above message before edits (sorry)
