### ISSUE TITLE
Images Being Upscaled Too Much

### ISSUE THREAD

**Issue by Gryph2021** [upscayl/upscayl#790]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

Basically I'm using upscayl to upscale textures for an old game, but for some reason when I batch upscale the folder the textures get upscaled to 8k (8196x8196) which is way too much. I've tried adjusting the image scale to 1x, 2x, 3x, and 4x and they all produce the same result. Its as if its defaulting to 4x which is quite frustrating. 

Also thought it might be worth noting that these images were originally .dds files which were converted to .png for the upscale (maybe it changes the compatibility or something, I'm not sure)

### To Reproduce

Batch upscale a folder of .png files of varying texture sizes. 

### Upscayl Version (or commit hash)

2.10

### Platform

Windows

### OS Version

Windows 11

### GPU Name

RTX 3070 Ti

### Screenshots

![Screenshot (265)](https://github.com/upscayl/upscayl/assets/92765108/51b9f854-3e7f-4242-8f64-bc4cbdc14b83)

### Logs

```sh
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
```

**Comment by NayamAmarshe** [comment]
Try v2.11

**Comment by Gryph2021** [comment]
The new version works perfectly, thanks!
