### ISSUE TITLE
Batch processing not applying advanced user settings.

### ISSUE THREAD

**Issue by wr104gamma** [upscayl/upscayl#791]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

The software works excellent spare one feature. It is not preserving advanced features and post-processing selections in batch processing. I am attempting to upscale a batch of High Quality Jpg's with RealEsrganV3.0 and give a 20% compression on the filesize. It seems to only create massive lossless Jpg images on batch processing for any of my post processing choices. It is the same for selecting "no post processing" massive, lossless jpg images of higher quality than the input.

### To Reproduce

Attempt to batch process some high quality 1080 images around 4-500k in size and upscale them to 4k with maintaining a filesize under 1mb. It should be easy. With single images you can upscale the image to 4k in this manner and compress the jpg 20% which will give you a 1080 -> 4k upscale without losing any quality. The images individually, in this manner are approximately 800k. In batch processing and choosing jpg images with 20% compression am seeing massive file sizes.

Thanks

### Upscayl Version (or commit hash)

2.10

### Platform

Linux

### OS Version

Ubuntu 22.04

### GPU Name

Nvidia 1060GT Amped 6gb

### Expected Behavior

It should be creating much smaller images on batch processing and applying post-processing affects.

### Screenshots

![Screenshot_20240424_233859](https://github.com/upscayl/upscayl/assets/126746891/78d4bdfd-17fd-4931-85e5-79f01820bf64)
![image](https://github.com/upscayl/upscayl/assets/126746891/80bcf3b7-b30e-4beb-a91d-4baee05dcb17)

![image](https://github.com/upscayl/upscayl/assets/126746891/1a53a25e-b8b2-4a62-bfe4-16ebf914ad6e)

### Logs

```sh
It's log it's log, it's big it's heavy it's wood.
```

**Comment by NayamAmarshe** [comment]
Please update to the latest version

**Comment by wr104gamma** [comment]
Version 2.11 seems to be working very well. Good Job! I gave you a star on
github.
