### ISSUE TITLE
After upgrade to upscayl 2.11.0 some models hangs on processing

### ISSUE THREAD

**Issue by osts** [upscayl/upscayl#792]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

After upgrade to upscayl 2.11.0 some models hangs on processing. It seems that processing problems is with models which don't have scale like 4x or x4 in name. For example - not working bundled model GENERAL PHOTO (ULTRASHARP) . I added to case error from log. Suggestion - maybe in code is way to assigng 4x scale when scale is not mentioned in model name?

### To Reproduce

Process image with GENERAL PHOTO (ULTRASHARP) model

### Upscayl Version (or commit hash)

2.11.0 

### Platform

Linux

### OS Version

Ubuntu 22.04.3

### GPU Name

NVIDIA

### Screenshots

![Screenshot_2024-04-25_12-04-25](https://github.com/upscayl/upscayl/assets/5476238/b2a41c15-b180-40e3-b373-851b52f140df)

### Logs

```sh
12:00:47.511 › 🚧 UPSCAYL_PROGRESS:  🚀 Starting Upscayl - Copyright © 2024
🚨 Error: The model name doesn't contain scale. Please make sure that the model name contains x2, x3, x4, etc. or 2x, x3, x4, etc.
```

**Comment by NayamAmarshe** [comment]
Uh oh, I'll push a hotfix ASAP!

**Comment by NayamAmarshe** [comment]
The issue was here in upscayl-ncnn. It was just returning if the model name didn't have the scale value, it was even ignoring the `-z` switch 😅 

<img width="974" alt="image" src="https://github.com/upscayl/upscayl/assets/25067102/7e8e1ff6-770f-4ed7-b39c-926a5bf9ba83">

I'll be updating the binaries of v2.11

**Comment by NayamAmarshe** [comment]
I've updated the binary and the issue has been fixed. Please re-download the exe from the latest release section. Thank you for reporting the bug and sorry for the trouble
