### ISSUE TITLE
Upscayl DECODING ERROR: vkCreatenlnstance failed -9

### ISSUE THREAD

**Issue by habibiiAKHAN** [upscayl/upscayl#793]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [X] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

DECODING ERROR: vkCreatenlnstance failed -9

### To Reproduce

How I can fix this bug?

### Upscayl Version (or commit hash)

2.10.0

### Platform

Windows

### OS Version

windows 10 22H2

### GPU Name

Intel (R) Core (TM) i5-5200U CPU @ 2.20 GHz 2.20 GHz

### Screenshots

![IMG_20240425_151159_072](https://github.com/upscayl/upscayl/assets/153109519/625cbd14-150c-49d0-8100-2f20acd0fcaa)

### Logs

```sh
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
```

**Comment by habibiiAKHAN** [comment]
Anyone can fix this bug?

**Comment by aaronliu0130** [comment]
> Yes, unfortunately. NCNN Vulkan requires a Vulkan-compatible GPU. Upscayl won't work with most iGPUs or CPUs.

A workaround exists for Windows and Linux in #580.

> Make sure to read [the FAQ](https://github.com/upscayl/upscayl#-faq) first to avoid getting rickrolled.

> If the name is something like "Intel Graphics" or "AMD Vega" and you can't Upscayl images, [STOP and read the 3rd point in the FAQ](https://github.com/upscayl/upscayl?tab=readme-ov-file#-faq).

![compulsory rickrolls are issued for duplicates of issues and the FAQ and normies who use intelgrated GPUs](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Comment by habibiiAKHAN** [comment]
thanks
