### ISSUE TITLE
[BUG][CUSTOM WIDTH] Custom width calculates wrong height, causing images to be stretched to the right

### ISSUE THREAD

**Issue by StScAllen** [upscayl/upscayl#794]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

Using the Custom Width scale setting on version 2.11 I get an Unable to Write to output directory error.  This ONLY occurs when using custom width, using a preset scaling works fine. 
1.  This process worked with no issues in 2.10.  I have uninstalled 2.11 and reinstalled 2.10 - it works again. I reinstalled 2.11 and the error returned.
2. Not sure if its related, but I am working with files on my D: drive and not my C: drive. 

### To Reproduce

1.  Change settings to Custom Width and restart Upscayl. 
2.  Select an image to Upscayl.
3.  Click the Upscayl button.  
4. The upscayl process will occur but when the application proceeds to try and write the image to disk it will fail with an "Unable to write to this location" toast.

### Upscayl Version (or commit hash)

2.11

### Platform

Windows

### OS Version

Windows 11

### GPU Name

Nvidia Geforce RTX 4070 TI SUPER

### Expected Behavior

Image will be upscaled to custom width setting and write the output to disk without error.

### Logs

```sh
🎯 GET_MODELS_LIST:  
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\junk\slashers3.png
🎒 BACKEND REPORTED:  📄 Selected File Path:  D:\junk\slashers3.png
🖼 Selected Image Path:  D:\junk\slashers3.png
📁 Selected Image Directory:  D:\junk
🖼 imagePath:  D:\junk\slashers3.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"ultramix_balanced","gpuId":null,"saveImageAs":"jpg","inputDir":"D:\\junk","fileNameWithExt":"slashers3.png","outputDir":"D:\\Backup\\CookieJar\\restored\\temp","outFile":"D:\\Backup\\CookieJar\\restored\\temp\\slashers3_upscayl_2x_ultramix_balanced.jpg","fileName":"slashers3","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\junk\slashers3.png,-o,D:\Backup\CookieJar\restored\temp\slashers3_upscayl_2x_ultramix_balanced.jpg,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,ultramix_balanced,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","D:\\junk\\slashers3.png","-o","D:\\Backup\\CookieJar\\restored\\temp\\slashers3_upscayl_2x_ultramix_balanced.jpg","-s","2","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","ultramix_balanced","-f","jpg","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  [0 NVIDIA GeForce RTX 4070 Ti SUPER]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[1 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 4070 Ti SUPER]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[1 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  ℹ️ Info: Image D:\junk\slashers3.png has alpha channel!

🚧 UPSCAYL_PROGRESS:  ℹ️ Info: Image D:\junk\slashers3.png has alpha channel!

🎒 BACKEND REPORTED:  0.00%
100.00%

🚧 UPSCAYL_PROGRESS:  0.00%
100.00%

🎒 BACKEND REPORTED:  🏞️ Resizing image according to output scale

🚧 UPSCAYL_PROGRESS:  🏞️ Resizing image according to output scale

🎒 BACKEND REPORTED:  🏞️ Resized image from 192x192 to 384x384

🚧 UPSCAYL_PROGRESS:  🏞️ Resized image from 192x192 to 384x384

🎒 BACKEND REPORTED:  🙌 Upscayled Successfully!

🚧 UPSCAYL_PROGRESS:  🙌 Upscayled Successfully!

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  D:\Backup\CookieJar\restored\temp\slashers3_upscayl_2x_ultramix_balanced.jpg
💯 UPSCAYL_DONE:  D:\Backup\CookieJar\restored\temp\slashers3_upscayl_2x_ultramix_balanced.jpg
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🔀 Model changed:  remacri
🔀 Setting model to remacri
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"remacri","gpuId":null,"saveImageAs":"jpg","inputDir":"D:\\junk","fileNameWithExt":"slashers3.png","outputDir":"D:\\Backup\\CookieJar\\restored\\temp","outFile":"D:\\Backup\\CookieJar\\restored\\temp\\slashers3_upscayl_2x_remacri.jpg","fileName":"slashers3","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\junk\slashers3.png,-o,D:\Backup\CookieJar\restored\temp\slashers3_upscayl_2x_remacri.jpg,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,remacri,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","D:\\junk\\slashers3.png","-o","D:\\Backup\\CookieJar\\restored\\temp\\slashers3_upscayl_2x_ultramix_balanced.jpg","-s","2","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","ultramix_balanced","-f","jpg","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  [0 NVIDIA GeForce RTX 4070 Ti SUPER]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[1 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 4070 Ti SUPER]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[1 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  ℹ️ Info: Image D:\junk\slashers3.png has alpha channel!

🚧 UPSCAYL_PROGRESS:  ℹ️ Info: Image D:\junk\slashers3.png has alpha channel!

🎒 BACKEND REPORTED:  0.00%
100.00%

🚧 UPSCAYL_PROGRESS:  0.00%
100.00%

🎒 BACKEND REPORTED:  🏞️ Resizing image according to output scale

🚧 UPSCAYL_PROGRESS:  🏞️ Resizing image according to output scale

🎒 BACKEND REPORTED:  🏞️ Resized image from 192x192 to 384x384

🚧 UPSCAYL_PROGRESS:  🏞️ Resized image from 192x192 to 384x384

🎒 BACKEND REPORTED:  🙌 Upscayled Successfully!

🚧 UPSCAYL_PROGRESS:  🙌 Upscayled Successfully!

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  D:\Backup\CookieJar\restored\temp\slashers3_upscayl_2x_remacri.jpg
💯 UPSCAYL_DONE:  D:\Backup\CookieJar\restored\temp\slashers3_upscayl_2x_remacri.jpg
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Remacri)","value":"remacri"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Remacri)","value":"remacri"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to remacri
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"remacri","gpuId":null,"saveImageAs":"jpg","inputDir":"D:\\junk","fileNameWithExt":"slashers3.png","outputDir":"D:\\Backup\\CookieJar\\restored\\temp","outFile":"D:\\Backup\\CookieJar\\restored\\temp\\slashers3_upscayl_1020px_remacri.jpg","fileName":"slashers3","scale":"2","compression":"0","customWidth":"1020","useCustomWidth":true,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\junk\slashers3.png,-o,D:\Backup\CookieJar\restored\temp\slashers3_upscayl_1020px_remacri.jpg,-m,C:\Program Files\Upscayl\resources\models,-n,remacri,-f,jpg,-w,1020,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","D:\\junk\\slashers3.png","-o","D:\\Backup\\CookieJar\\restored\\temp\\slashers3_upscayl_2x_ultramix_balanced.jpg","-s","2","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","ultramix_balanced","-f","jpg","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  [0 NVIDIA GeForce RTX 4070 Ti SUPER]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[1 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 4070 Ti SUPER]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4070 Ti SUPER]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[1 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  ℹ️ Info: Image D:\junk\slashers3.png has alpha channel!

🚧 UPSCAYL_PROGRESS:  ℹ️ Info: Image D:\junk\slashers3.png has alpha channel!

🎒 BACKEND REPORTED:  0.00%
100.00%

🚧 UPSCAYL_PROGRESS:  0.00%
100.00%

🎒 BACKEND REPORTED:  🏞️ Resizing image according to desired resolution

🚧 UPSCAYL_PROGRESS:  🏞️ Resizing image according to desired resolution

🎒 BACKEND REPORTED:  🏞️ Resized image from 192x192 to 1020x1465275732

🚧 UPSCAYL_PROGRESS:  🏞️ Resized image from 192x192 to 1020x1465275732

🎒 BACKEND REPORTED:  🚨 Error: Couldn't write the image D:\Backup\CookieJar\restored\temp\slashers3_upscayl_1020px_remacri.jpg

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  🚨 Error: Couldn't write the image D:\Backup\CookieJar\restored\temp\slashers3_upscayl_1020px_remacri.jpg

⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Remacri)","value":"remacri"}
⚙️ Setting gpuId to empty string
```

**Comment by StScAllen** [comment]
Followup:  Now when I try to rescale *without* custom settings I get a corrupted output:
![slashers_upscayl_2x_ultramix_balanced](https://github.com/upscayl/upscayl/assets/5774645/7a8c9d5c-e21a-477e-8419-3b0ecd4adb65)

Reinstalling 2.10 once again cleared the issue.

**Comment by NayamAmarshe** [comment]
Seems like there's an issue with height calculation.

It's calculating the height as 1020x1465275732, which is why it's unable to write.

**Comment by NayamAmarshe** [comment]
I'd suggest using just the scale for now. I'll push a new update for custom width later.

**Comment by NayamAmarshe** [comment]
Also strange that it never actually calculates the height, otherwise it would have given an output.

https://github.com/upscayl/upscayl-ncnn/blob/41d6415db66e4b495fa96c65462eb48aa74377c1/src/main.cpp#L480

**Comment by NayamAmarshe** [comment]
@StScAllen Could you please share the image if possible? I am unable to reproduce the error

**Comment by StScAllen** [comment]
Absolutely.  Image attached.
![slashers](https://github.com/upscayl/upscayl/assets/5774645/7fc6a19f-d983-44c6-820a-7ce66fc56d71)

**Comment by vmackey** [comment]
I started using upscayl today, and I am having the exact same issue. I am trying to increase the image from 870x870 to 4500x4500. (I would share the image but my company won't allow it.) I'm glad there is an update planned to fix it, thanks.

**Comment by StScAllen** [comment]
> I started using upscayl today, and I am having the exact same issue. I am trying to increase the image from 870x870 to 4500x4500. (I would share the image but my company won't allow it.) I'm glad there is an update planned to fix it, thanks.

FYI - If you uninstall 2.11 and download and install 2.10 it will work fine. Nice changes in 2.11 but rolling back to 2.10 is not critical.

**Comment by vmackey** [comment]
> > I started using upscayl today, and I am having the exact same issue. I am trying to increase the image from 870x870 to 4500x4500. (I would share the image but my company won't allow it.) I'm glad there is an update planned to fix it, thanks.
> 
> FYI - If you uninstall 2.11 and download and install 2.10 it will work fine. Nice changes in 2.11 but rolling back to 2.10 is not critical.

Understood. Thank you for the tips.

**Comment by NayamAmarshe** [comment]
@StScAllen I'm unable to reproduce this issue on Mac:
<img width="1297" alt="image" src="https://github.com/upscayl/upscayl/assets/25067102/bbccd3e2-cff1-45cd-a275-2b1e69f6bf1d">

**Comment by NayamAmarshe** [comment]
Huh, on Linux it throws an error. It's calculating the wrong height.
So the issue is on Linux and Windows.

![Uploading image.png…]()

**Comment by NayamAmarshe** [comment]
@aaronliu0130 the images don't stretch, they get corrupted

**Comment by aaronliu0130** [comment]
That may be the cause, but the visual effect in https://github.com/upscayl/upscayl/issues/794#issuecomment-2077957060 (and in my testing) is that the image gets striated and stretched to the right.

**Comment by xvim64** [comment]
Windows 11 23H2
Upscayl 2.11.0

# source
![width512-source](https://github.com/upscayl/upscayl/assets/83569599/f7e9e2e8-aecc-46ab-a539-6e3a6a415c02)

# width:1200, fast real-esrgan  -->  no output
<img width="960" alt="width1200-output-fast-real-esrgan" src="https://github.com/upscayl/upscayl/assets/83569599/b9782840-5747-45ee-9df8-58a4927e1ac3">

# width:1200, demarci  -->  distorted
<img width="960" alt="width1200-output-demarci" src="https://github.com/upscayl/upscayl/assets/83569599/581f4397-cd9b-499d-88ec-ec0c28c6611f">

**Comment by vnihouarn** [comment]
Hi,

I just wanted to confirm what [xvim64](https://github.com/xvim64) commented. Either no output or distorded. The height is wrong. A 768x768 image that I try to upscale to 4k is becoming a 4096x628. ;-(

Just wanted to say that your program is still really nice though. Having the custom width working would be so sweeeeeet!

**Comment by NayamAmarshe** [comment]
Upscayl NCNN has received the hotfix. If you want to fix it in Upscayl right now, here's what you can do:

1. Download the latest upscayl-bin: https://github.com/upscayl/upscayl-ncnn/releases/tag/20240426-231028 and extract it somewhere. It should have a file called 'upscayl-bin'.
2. Find where Upscayl is installed on your system. Find the folder called 'resources' which should have a 'bin' folder.

![image](https://github.com/upscayl/upscayl/assets/25067102/c1ff051f-8e38-4837-9a03-46849f8b08b7)

3. Replace the 'upscayl-bin' file with the one you just downloaded in Step 1.

This should hopefully fix all issues with the custom width :smile:

**Comment by xvim64** [comment]
> Upscayl NCNN has received the hotfix. If you want to fix it in Upscayl right now, here's what you can do:
> 
>     1. Download the latest upscayl-bin: https://github.com/upscayl/upscayl-ncnn/releases/tag/20240426-231028 and extract it somewhere. It should have a file called 'upscayl-bin'.
> 
> This should hopefully fix all issues with the custom width 😄

@NayamAmarshe 

The hotfix works well on Windows 11 23H2.
Thank you for your hard work.

**Comment by aaronliu0130** [comment]
Since the hotfix works, we should probably release a 2.11.1.

**Comment by NayamAmarshe** [comment]
> Since the hotfix works, we should probably release a 2.11.1.

Ok, will do!

**Comment by xcloudx01** [comment]
> This should hopefully fix all issues with the custom width 😄

Legendary. Just confirming it's also working for me to fix the bug. Thank you for your hard work guys <3

**Comment by owen555999** [comment]
> Upscayl NCNN has received the hotfix. If you want to fix it in Upscayl right now, here's what you can do:
> 
> 1. Download the latest upscayl-bin: https://github.com/upscayl/upscayl-ncnn/releases/tag/20240426-231028 and extract it somewhere. It should have a file called 'upscayl-bin'.
> 2. Find where Upscayl is installed on your system. Find the folder called 'resources' which should have a 'bin' folder. For Mac, it would be in /Applications/Upscayl.app/Contents/Resources/bin´
> 
> ![image](https://private-user-images.githubusercontent.com/25067102/326254921-c1ff051f-8e38-4837-9a03-46849f8b08b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4Mjk3NTIsIm5iZiI6MTcxNTgyOTQ1MiwicGF0aCI6Ii8yNTA2NzEwMi8zMjYyNTQ5MjEtYzFmZjA1MWYtOGUzOC00ODM3LTlhMDMtNDY4NDlmOGIwOGI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAzMTczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YWRmMWE3MDdiNjRhZmU3ZTI0OGJmNmNhYmI4MDZmYzg3MjhiMzhkMTRlMzAzOTg5NmVkOThkMzc2NWRhZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0ZiUy5DoOH-pw4jEbFshyOCQ-fBKksg_SwI0aJTBJyw)
> 
> 3. Replace the 'upscayl-bin' file with the one you just downloaded in Step 1.
> 
> This should hopefully fix all issues with the custom width 😄

Thanks for hotfix
