### ISSUE TITLE
[FLATPAK] Scale not being applied

### ISSUE THREAD

**Issue by taintedcypher** [upscayl/upscayl#795]
Hello,

I updated to 2.11.0 and noticed some models didn't work anymore on my setup:

- Remacri
- Ultramix Balanced
- Ultrasharp

When I try to upscayl, it just hangs at the _"Hold On - Doing the upscayl magic"_ dialog.

I uninstalled and reinstalled the flatpak but it didn't help.
Then I downgraded the flatpak to 2.9.5 and everything works again.
(For good measure I then tried updating to 2.11.0 again - no luck)

Real-ESRGAN, Fast Real-ESRGan and Digital Art behave as expected.

Ubuntu 23.10, Nvdia drivers 545.29.06

**Comment by NayamAmarshe** [comment]
I've updated the flatpak. Should be up in a few hours :)

**Comment by taintedcypher** [comment]
Thank you!
