### ISSUE TITLE
How to fix "DiscardVirtualMemory could not be located"

### ISSUE THREAD

**Issue by TobiasScheuerer** [upscayl/upscayl#800]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

I am trying to install Upscayl on my Windows 8 PC, but it's saying "the procedure entry point DiscardVirtualMemory could not be located". How can I fix this?

### To Reproduce

...

### Upscayl Version (or commit hash)

...

### Platform

Windows

### OS Version

8

### GPU Name

...

### Logs

```sh
...
```

**Comment by xvim64** [comment]
It seems to be an Electron compatibility issue.
https://www.electronjs.org/blog/electron-23-0#dropping-windows-7881-support

**Comment by NayamAmarshe** [comment]
https://github.com/upscayl/upscayl?tab=readme-ov-file#-windows

![image](https://github.com/upscayl/upscayl/assets/25067102/b59caaf9-c469-4274-a7ea-0237bd14e61c)
