### ISSUE TITLE
vkEnumeratePhysicalDevices failed 5 🚨 Error: Invalid GPU Device

### ISSUE THREAD

**Issue by Garou312** [upscayl/upscayl#803]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [X] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

I Just shifted to windows 11 canary build but upscayl now doesn't seem to recognize the dGPU, before this I was in windows 10 and Upscayl was working fine, I also tried older version but it also didn't work, I shared the screenshot

### To Reproduce

‎ 

### Upscayl Version (or commit hash)

2.11.0

### Platform

Windows

### OS Version

Windows 11 24H2 Canary Build

### GPU Name

RTX 3060 laptop GPU

### Expected Behavior

I think it is not recognizing Dedicated GPU

### Screenshots

 The first one is 2.11.0 and second one is 2.9.1

### Logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\Suryansh\Downloads\Minish cap 3d build\download (25).png
🖼 Selected Image Path:  C:\Users\Suryansh\Downloads\Minish cap 3d build\download (25).png
📁 Selected Image Directory:  C:\Users\Suryansh\Downloads\Minish cap 3d build
🖼 imagePath:  C:\Users\Suryansh\Downloads\Minish cap 3d build\download (25).png
🔤 Extension:  png
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\Suryansh\Downloads\Minish cap 3d build\download (25).png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"C:\\Users\\Suryansh\\Downloads\\Minish cap 3d build","fileNameWithExt":"download (25).png","outputDir":"C:\\Users\\Suryansh\\Downloads\\Minish cap 3d build","outFile":"C:\\Users\\Suryansh\\Downloads\\Minish cap 3d build\\download (25)_upscayl_16x_realesrgan-x4plus.png","fileName":"download (25)","scale":"16","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Suryansh\Downloads\Minish cap 3d build\download (25).png,-o,C:\Users\Suryansh\Downloads\Minish cap 3d build\download (25)_upscayl_16x_realesrgan-x4plus.png,-s,16,-m,D:\upscayl-2.11.0-win\resources\models,-n,realesrgan-x4plus,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"D:\\upscayl-2.11.0-win\\resources\\bin\\upscayl-bin","args":["D:\\upscayl-2.11.0-win\\resources\\bin\\upscayl-bin","-i","C:\\Users\\Suryansh\\Downloads\\Minish cap 3d build\\download (25).png","-o","C:\\Users\\Suryansh\\Downloads\\Minish cap 3d build\\download (25)_upscayl_16x_realesrgan-x4plus.png","-s","16","-m","D:\\upscayl-2.11.0-win\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkEnumeratePhysicalDevices failed 5
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed 5
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
```

**Comment by NayamAmarshe** [comment]
Please follow the troubleshooting steps. Also, this is a duplicate of #735 so I'm closing this but we can continue the discussion there.

**Comment by Garou312** [comment]
> Please follow the troubleshooting steps. Also, this is a duplicate of #735 so I'm closing this but we can continue the discussion there.

I have done troubleshooting but can't see any GPU numbers in logs and I also one by one entered 0,1,2 in GPU ID but still not working

**Comment by aaronliu0130** [comment]
@NayamAmarshe This error is usually different for each system and shouldn't be closed as a duplicate.

Does VulkanCapsViewer report capabilities?

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe This error is usually different for each system and shouldn't be closed as a duplicate.
> 
> Does VulkanCapsViewer report capabilities?

The error is the same in the issue I linked. I see no reason to create another thread for it. OP can simply find support the other issue.

**Comment by aaronliu0130** [comment]
The error code basically means that something is wrong with the drivers or hardware. The error code being the same doesn't mean much.

**Comment by NayamAmarshe** [comment]
> The error code basically means that something is wrong with the drivers or hardware. The error code being the same doesn't mean much.

I still don't see why one can't find support in the other thread by mentioning the same details in a comment, because that's what issues are for. We want to avoid duplicate vulkan issues, it's better to have everyone with the same problem in a single thread so that we may find a solution.

**Comment by aaronliu0130** [comment]
Another reason was that using CPUs also often causes this, and referring people to the checklist, which prevents most unneeded posts. But there's now a troubleshoot button in the dialog box, so maybe you're right.

**Comment by Garou312** [comment]
> The error is the same in the issue I linked. I see no reason to create another thread for it. OP can simply find support on th
> Even if the system is different, the error code is exactly the same. It shouldn't require another thread imho, otherwise, we'll keep having to create a new issue for each configuration for the exact same error and error code.

This is a different issue and you clearly didn't read my reply and if you read, then it blew over your head, I did everything written in troubleshoot, changed GPU ID and also sent logs but you didn't read it.
If you don't have to help, then don't suck time of anyone, end support for this thing.

**Comment by NayamAmarshe** [comment]
> > The error is the same in the issue I linked. I see no reason to create another thread for it. OP can simply find support on th
> > Even if the system is different, the error code is exactly the same. It shouldn't require another thread imho, otherwise, we'll keep having to create a new issue for each configuration for the exact same error and error code.
> 
> This is a different issue and you clearly didn't read my reply and if you read, then it blew over your head, I did everything written in troubleshoot, changed GPU ID and also sent logs but you didn't read it. If you don't have to help, then don't suck time of anyone, end support for this thing.

It's not a different issue, afaics. Pretty much the same error:

```
🐞 BACKEND REPORTED:  image upscayl:  vkEnumeratePhysicalDevices failed 5
invalid gpu device
```

This happens due to misconfigured device drivers. If you've really tried everything mentioned in the troubleshooting, I'm sorry I can't really suggest anything else. I cannot reproduce your machine configuration and then the bug, the troubleshooting in these cases depends on the one reporting the issue.

I apologize for the other irrelevant 'issue management' comments in this thread though.

**Comment by aaronliu0130** [comment]
We can track in #735, the logs don't differ much either. It's not like you can assume #735's reporter didn't try the troubleshooting steps either.

**Comment by Ryosama2** [comment]
I used these code to upscale image (in Anaconda Prompt)

1. C:\Users\minhh\Downloads\Compressed\Real-ESRGAN-ncnn-vulkan-20220424-windows
2. realesrgan-ncnn-vulkan -i inputs -o outputs -n realesrgan-x4plus -f jpg

But now it is no longer work, it failed with the error notification:
**vkEnumeratePhysicalDevices failed 5
invalid gpu device**
![image](https://github.com/upscayl/upscayl/assets/115549537/a45e16c2-f08f-4b81-98e8-4b652c5a08d5)

And this one also failed when I tried on cmd
![image](https://github.com/upscayl/upscayl/assets/115549537/989e7b55-f1e8-48c2-94d1-ce00a3b13da7)

My laptop configuration:
![image](https://github.com/upscayl/upscayl/assets/115549537/e94d40b8-d1c8-40af-9e99-8401f88933fa)


Yesterday and many days (many years before), REAL-ESRGAN run normally and smoothly, but suddenly today, it happened with this issue. Please help

**Comment by aaronliu0130** [comment]
Please go through the checklist and use Upscayl.

**Comment by Ryosama2** [comment]
> Please go through the checklist and use Upscayl.

I read all the checklist and I found that there was nothing I can do.

But there was the mots suspicious was that the Windows update. Since my laptop is using **AMD GPU**, the **Windows update often conflicts** with my **AMD GPU**. **When I go back the previous version of Windows system, the problem fixed**. Then I had to temporary delayed the Windows update.
![image](https://github.com/upscayl/upscayl/assets/115549537/418b623b-4f50-47bb-bdec-85184d375b0d)

**Comment by aaronliu0130** [comment]
Again, go through the checklist. You'll see instructions about the GPU ID.
