### ISSUE TITLE
Moving the Upscayl window to a different monitor causes a segmentation fault

### ISSUE THREAD

**Issue by conradolandia** [upscayl/upscayl#804]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

Moving the Upscayl window to a different monitor causes a segmentation fault after a few seconds (not immediately) and the application closes. 

### To Reproduce

Move the Upscayl window to a different monitor

### Upscayl Version (or commit hash)

2.10.9

### Platform

Linux

### OS Version

Arch Linux (using both AUR and AppImage)

### GPU Name

AMD Lexa PRO (Radeon RX 550X rev. c7)

### Expected Behavior

The application should work fine even if moved to a different monitor.

### Logs

```sh
📂 DIRNAME /opt/upscayl/app.asar/export/electron
APPIMAGE env is not defined, current application is not an AppImage
18:05:27.649 › 🚀 UPSCAYL EXEC PATH:  /opt/upscayl/bin/upscayl-bin
18:05:27.652 › 🚀 MODELS PATH:  /opt/upscayl/models
18:05:28.317 › 📁 Updating Output Folder Path:  "/home/andi/Dev/Spyder/design/posts/20240429"
18:05:28.393 › ⚙️ Getting saveImageAs from localStorage:  png
18:05:28.394 › ⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
18:05:28.394 › ⚙️ Setting gpuId to empty string
18:05:28.394 › 🔀 Setting model to null
18:05:28.397 › 𝌖 BACKEND REPORTED:  📁 Updating Output Folder Path:  "/home/andi/Dev/Spyder/design/posts/20240429"
18:05:28.401 › 🔀 Setting model to realesrgan-x4plus
/usr/bin/upscayl: line 5: 45338 Segmentation fault      (core dumped) electron /opt/upscayl/app.asar "$@"
```

**Comment by aaronliu0130** [comment]
Could you try the newest release?

**Comment by conradolandia** [comment]
I'm using Xorg (XFCE4). Using 2.11.0 produces the same result.

**Comment by conradolandia** [comment]
I'm using Xorg (XFCE4). Using 2.11.0 produces the same result, I have not tried in Wayland.

**Comment by lokesh-krishna** [comment]
Unsure if my issue is the same but launching Upscayl on Arch (2.11.0-1) directly results in a segmentation fault. I'm presently on Sway.

```
📂 DIRNAME /usr/lib/upscayl/app.asar/export/electron
APPIMAGE env is not defined, current application is not an AppImage
09:54:37.321 › 🚀 UPSCAYL EXEC PATH:  /usr/lib/upscayl/bin/upscayl-bin
09:54:37.322 › 🚀 MODELS PATH:  /usr/lib/upscayl/models
[1]    10524 segmentation fault (core dumped)  upscayl
```

**Comment by NayamAmarshe** [comment]
Could you try the zip versions?

**Comment by conradolandia** [comment]
I can confirm the zip version of 2.11.0 **does not** produce the segmentation fault.

**Comment by aaronliu0130** [comment]
Okay, that is weird. The upscayl-bin package installs the zip. Which package did you install Upscayl from?

**Comment by conradolandia** [comment]
I confirm that uninstalling and reinstalling from the AUR solved the issue. I don't know what caused it, nor what solved it. Apologies for the noise.
