### ISSUE TITLE
NOT UPSCALE IMAGE

### ISSUE THREAD

**Issue by deepu6200** [upscayl/upscayl#805]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  E:\Chunav\ok done.png
🖼 Selected Image Path:  E:\Chunav\ok done.png
📁 Selected Image Directory:  E:\Chunav
🖼 imagePath:  E:\Chunav\ok done.png
🔤 Extension:  png
🎒 BACKEND REPORTED:  📄 Selected File Path:  E:\Chunav\ok done.png
🎒 BACKEND REPORTED:  🚫 File Operation Cancelled
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  ⚙️ Getting saveImageAs from localStorage:  jpg ⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"} ⚙️ Setting gpuId to empty string 🔀 Setting model to  🔀 Setting model to realesrgan-x4plus 🔄 Resetting image paths 🔄 Resetting image paths 🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  E:\Chunav\ok done.png 🖼 Selected Image Path:  E:\Chunav\ok done.png 📁 Selected Image Directory:  E:\Chunav 🖼 imagePath:  E:\Chunav\ok done.png 🔤 Extension:  png 🎒 BACKEND REPORTED:  📄 Selected File Path:  E:\Chunav\ok done.png 🎒 BACKEND REPORTED:  🚫 File Operation Cancelled ⚙️ Getting saveImageAs from localStorage:  jpg ⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"} ⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":"⚙️ Getting saveImageAs from localStorage:  jpg ⚙️ Getting model from localStorage:  {\"label\":\"General Photo (Real-ESRGAN)\",\"value\":\"realesrgan-x4plus\"} ⚙️ Setting gpuId to empty string 🔀 Setting model to  🔀 Setting model to realesrgan-x4plus 🔄 Resetting image paths 🔄 Resetting image paths 🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  E:\\Chunav\\ok done.png 🖼 Selected Image Path:  E:\\Chunav\\ok done.png 📁 Selected Image Directory:  E:\\Chunav 🖼 imagePath:  E:\\Chunav\\ok done.png 🔤 Extension:  png 🎒 BACKEND REPORTED:  📄 Selected File Path:  E:\\Chunav\\ok done.png 🎒 BACKEND REPORTED:  🚫 File Operation Cancelled ⚙️ Getting saveImageAs from localStorage:  jpg ⚙️ Getting model from localStorage:  {\"label\":\"General Photo (Real-ESRGAN)\",\"value\":\"realesrgan-x4plus\"} ⚙️ Setting gpuId to empty string","saveImageAs":"jpg","inputDir":"E:\\Chunav","fileNameWithExt":"ok done.png","outputDir":"E:\\Chunav","outFile":"E:\\Chunav\\ok done_upscayl_2x_realesrgan-x4plus.jpg","fileName":"ok done","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,E:\Chunav\ok done.png,-o,E:\Chunav\ok done_upscayl_2x_realesrgan-x4plus.jpg,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-g,⚙️ Getting saveImageAs from localStorage:  jpg ⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"} ⚙️ Setting gpuId to empty string 🔀 Setting model to  🔀 Setting model to realesrgan-x4plus 🔄 Resetting image paths 🔄 Resetting image paths 🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  E:\Chunav\ok done.png 🖼 Selected Image Path:  E:\Chunav\ok done.png 📁 Selected Image Directory:  E:\Chunav 🖼 imagePath:  E:\Chunav\ok done.png 🔤 Extension:  png 🎒 BACKEND REPORTED:  📄 Selected File Path:  E:\Chunav\ok done.png 🎒 BACKEND REPORTED:  🚫 File Operation Cancelled ⚙️ Getting saveImageAs from localStorage:  jpg ⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"} ⚙️ Setting gpuId to empty string,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","E:\\Chunav\\ok done.png","-o","E:\\Chunav\\ok done_upscayl_2x_realesrgan-x4plus.jpg","-s","2","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-g","⚙️ Getting saveImageAs from localStorage:  jpg ⚙️ Getting model from localStorage:  {\"label\":\"General Photo (Real-ESRGAN)\",\"value\":\"realesrgan-x4plus\"} ⚙️ Setting gpuId to empty string 🔀 Setting model to  🔀 Setting model to realesrgan-x4plus 🔄 Resetting image paths 🔄 Resetting image paths 🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  E:\\Chunav\\ok done.png 🖼 Selected Image Path:  E:\\Chunav\\ok done.png 📁 Selected Image Directory:  E:\\Chunav 🖼 imagePath:  E:\\Chunav\\ok done.png 🔤 Extension:  png 🎒 BACKEND REPORTED:  📄 Selected File Path:  E:\\Chunav\\ok done.png 🎒 BACKEND REPORTED:  🚫 File Operation Cancelled ⚙️ Getting saveImageAs from localStorage:  jpg ⚙️ Getting model from localStorage:  {\"label\":\"General Photo (Real-ESRGAN)\",\"value\":\"realesrgan-x4plus\"} ⚙️ Setting gpuId to empty string","-f","jpg","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  ⚙️ Getting saveImageAs from localStorage:  jpg ⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"} ⚙️ Setting gpuId to empty string 🔀 Setting model to  🔀 Setting model to realesrgan-x4plus 🔄 Resetting image paths 🔄 Resetting image paths 🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  E:\Chunav\ok done.png 🖼 Selected Image Path:  E:\Chunav\ok done.png 📁 Selected Image Directory:  E:\Chunav 🖼 imagePath:  E:\Chunav\ok done.png 🔤 Extension:  png 🎒 BACKEND REPORTED:  📄 Selected File Path:  E:\Chunav\ok done.png 🎒 BACKEND REPORTED:  🚫 File Operation Cancelled ⚙️ Getting saveImageAs from localStorage:  jpg ⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"} ⚙️ Setting gpuId to empty string

**Comment by aaronliu0130** [comment]
Please file this again with the bug report template, which will prompt you for information vital to troubleshooting.
