### ISSUE TITLE
Decoding Error when using Sharpen Image

### ISSUE THREAD

**Issue by OLoKo64** [upscayl/upscayl#81]
## System info

OS: Endeavour OS
Kernel: 5.19.9-arch-1-1

## Steps to reproduce:

1. Select General Photo type
2. Select Double Upscayl
3. Change the type to Sharpen Image
4. Upscayl a image

## Error
![image](https://user-images.githubusercontent.com/49915167/191318519-6f91f616-b24a-4e48-b367-273718c5c7f2.png)

## Observations

- It outputs a file with "8x" in the name, seems that the Double Upscayl option is active when using this mode too when it should not.
- If I deselect the Double Upscayl before the error does not happen.
- I need to close the application and open it again to bypass the issue.

**Comment by NayamAmarshe** [comment]
Ok, gonna fix this ASAP. Seems like a high priority bug.

**Comment by NayamAmarshe** [comment]
https://github.com/upscayl/upscayl/releases/tag/v1.5.5
