### ISSUE TITLE
The software are freezing

### ISSUE THREAD

**Issue by goshtdev** [upscayl/upscayl#812]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

When I try to upscale the Image form Any size, Any format and any model
The PC is freezing ,I try use different image and change lot of models and he is still freeze 

### To Reproduce

Step 1 :Put your image want to upscale in the box<is working>
Step 2 :Select the settings in the right <Is working>
Step 3 :Click on Upcayl <Is working>
Step 4 :Wait for seconds and the Upcayl stop first and in few second the PC freeze <here the problem>

### Upscayl Version (or commit hash)

2.11.0

### Platform

Windows

### OS Version

Windows 10 22H2 (19045.4291)

### GPU Name

AMD Radeon R5

### Expected Behavior

Complete the Upscale without freeze

### Screenshots

![Screenshot (63)](https://github.com/upscayl/upscayl/assets/169049573/2d95ef89-058f-42f6-b5f1-bf1ee289870a)

### Logs

⚙️ Setting saveImageAs to png
🔀 Setting model to realesrgan-x4plus
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\Youtube\PHOTO\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg
🖼 Selected Image Path:  D:\Youtube\PHOTO\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg
📁 Selected Image Directory:  D:\Youtube\PHOTO
🖼 imagePath:  D:\Youtube\PHOTO\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg
🔤 Extension:  jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  D:\Youtube\PHOTO\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"D:\\Youtube\\PHOTO","fileNameWithExt":"d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg","outputDir":"D:\\Youtube\\PHOTO","outFile":"D:\\Youtube\\PHOTO\\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3_upscayl_2x_realesrgan-x4plus.png","fileName":"d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\Youtube\PHOTO\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg,-o,D:\Youtube\PHOTO\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3_upscayl_2x_realesrgan-x4plus.png,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","D:\\Youtube\\PHOTO\\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg","-o","D:\\Youtube\\PHOTO\\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3_upscayl_2x_realesrgan-x4plus.png","-s","2","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🎒 BACKEND REPORTED:  [0 AMD Radeon(TM) R5 Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 AMD Radeon(TM) R5 Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon(TM) R5 Graphics]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 AMD Radeon(TM) R5 Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 AMD Radeon(TM) R5 Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 AMD Radeon(TM) R5 Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon(TM) R5 Graphics]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 AMD Radeon(TM) R5 Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🛑 Stopping Upscayl
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  true
🎒 BACKEND REPORTED:  🛑 Stopping Upscaling Process 2828

**Comment by aaronliu0130** [comment]
Can't reproduce. Does Vulkan caps viewer report capabilities? What precise model is your graphics card?

**Comment by NayamAmarshe** [comment]
R5 probably doesn't support Vulkan.

**Comment by goshtdev** [comment]
R5 is support Vulkan
![Screenshot (64)](https://github.com/upscayl/upscayl/assets/169049573/e32980c4-d934-43b2-8d33-210f81cf43e8)

**Comment by goshtdev** [comment]
I try also Topaz Gigapixel and is work 
Maybe is work with OpenGL or DirectX I don't now

**Comment by goshtdev** [comment]
![Screenshot (66)](https://github.com/upscayl/upscayl/assets/169049573/ca305b82-a703-4039-a518-c193440cc26e)

**Comment by goshtdev** [comment]
Im lucky to Copy logs
⚙️ Setting saveImageAs to png
🔀 Setting model to realesrgan-x4plus
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\Youtube\PHOTO\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg
🖼 Selected Image Path:  D:\Youtube\PHOTO\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg
📁 Selected Image Directory:  D:\Youtube\PHOTO
🖼 imagePath:  D:\Youtube\PHOTO\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg
🔤 Extension:  jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  D:\Youtube\PHOTO\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"D:\\Youtube\\PHOTO","fileNameWithExt":"d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg","outputDir":"D:\\Youtube\\PHOTO","outFile":"D:\\Youtube\\PHOTO\\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3_upscayl_2x_realesrgan-x4plus.png","fileName":"d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\Youtube\PHOTO\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg,-o,D:\Youtube\PHOTO\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3_upscayl_2x_realesrgan-x4plus.png,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","D:\\Youtube\\PHOTO\\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3.jpg","-o","D:\\Youtube\\PHOTO\\d1c2bn4-6956ae25-2dd0-4549-b5ae-81d0891445c3_upscayl_2x_realesrgan-x4plus.png","-s","2","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🎒 BACKEND REPORTED:  [0 AMD Radeon(TM) R5 Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 AMD Radeon(TM) R5 Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon(TM) R5 Graphics]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 AMD Radeon(TM) R5 Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 AMD Radeon(TM) R5 Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[2]
[0 AMD Radeon(TM) R5 Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon(TM) R5 Graphics]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 AMD Radeon(TM) R5 Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🛑 Stopping Upscayl
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  true
🎒 BACKEND REPORTED:  🛑 Stopping Upscaling Process 2828

**Comment by goshtdev** [comment]
> R5 probably doesn't support Vulkan.

I edit the logs maybe can help you

**Comment by goshtdev** [comment]
> Can't reproduce. Does Vulkan caps viewer report capabilities? What precise model is your graphics card?

![Uploading Screenshot (66).png…]()

**Comment by goshtdev** [comment]
> Can't reproduce. Does Vulkan caps viewer report capabilities? What precise model is your graphics card?

![Screenshot (66)](https://github.com/upscayl/upscayl/assets/169049573/8a90c123-a92e-4fe0-b21e-4657b1fc4fad)

**Comment by aaronliu0130** [comment]
Vulkan came out in 2016, so I really doubt that your hardware supports it. Sorry. Best you can do is look at the #580 workaround.
