### ISSUE TITLE
Hold on doing the Upscayl magic vers. 2.11.0... 

### ISSUE THREAD

**Issue by Mykion** [upscayl/upscayl#815]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

My problem is similar to the recent bug #798, at step 4 the image calculation process does not start. 

### To Reproduce

Step 1
I select image size 1300px X 366px 
Step 2
Select mode Photo (Real-Ersgan)
Step 3
Image scale (4x)
Step 4
Click Upcayl

### Upscayl Version (or commit hash)

2.11.0

### Platform

Windows

### OS Version

Windows 10

### GPU Name

Intel(R) UHD Graphics 620

### Expected Behavior

The image calculation process at step 4 does not start, it holds on....

### Screenshots

![Upscayl hold on](https://github.com/upscayl/upscayl/assets/169353574/73419952-c4c4-4060-964d-d075c118fdae)

### Logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Remacri)","value":"remacri"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to remacri
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\$ £ % % DOC EN COURS\$ A FAIRE\PHOTO WORK\Cascade Huay Mae Khamin - Parc national de Khuean Srinagarindra - Thaïlande4.jpg
🖼 Selected Image Path:  D:\$ £ % % DOC EN COURS\$ A FAIRE\PHOTO WORK\Cascade Huay Mae Khamin - Parc national de Khuean Srinagarindra - Thaïlande4.jpg
📁 Selected Image Directory:  D:\$ £ % % DOC EN COURS\$ A FAIRE\PHOTO WORK
🖼 imagePath:  D:\$ £ % % DOC EN COURS\$ A FAIRE\PHOTO WORK\Cascade Huay Mae Khamin - Parc national de Khuean Srinagarindra - Thaïlande4.jpg
🔤 Extension:  jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  D:\$ £ % % DOC EN COURS\$ A FAIRE\PHOTO WORK\Cascade Huay Mae Khamin - Parc national de Khuean Srinagarindra - Thaïlande4.jpg
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\$ £ % % DOC EN COURS\$ A FAIRE\PHOTO WORK\Cascade Huay Mae Khamin - Parc national de Khuean Srinagarindra - Thaïlande2.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  D:\$ £ % % DOC EN COURS\$ A FAIRE\PHOTO WORK\Cascade Huay Mae Khamin - Parc national de Khuean Srinagarindra - Thaïlande2.jpg
🖼 Selected Image Path:  D:\$ £ % % DOC EN COURS\$ A FAIRE\PHOTO WORK\Cascade Huay Mae Khamin - Parc national de Khuean Srinagarindra - Thaïlande2.jpg
📁 Selected Image Directory:  D:\$ £ % % DOC EN COURS\$ A FAIRE\PHOTO WORK
🖼 imagePath:  D:\$ £ % % DOC EN COURS\$ A FAIRE\PHOTO WORK\Cascade Huay Mae Khamin - Parc national de Khuean Srinagarindra - Thaïlande2.jpg
🔤 Extension:  jpg
🔀 Model changed:  realesrgan-x4plus
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🛑 Stopping Upscayl
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  true
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
```

**Comment by Mykion** [comment]
Thanks, but I am a bit puzzled as the suggested workaround seems to relate to an installed upscayl program wheras mine is a portable one... Note that before, it worked well with a previous upscayl version 2.9.9 (or the like).
Anything I could do in my case?

**Comment by NayamAmarshe** [comment]
> Thanks, but I am a bit puzzled as the suggested workaround seems to relate to an installed upscayl program wheras mine is a portable one... Note that before, it worked well with a previous upscayl version 2.9.9 (or the like). Anything I could do in my case?

It's most likely a driver issue. You'll need to try vulkan cube and other stuff mentioned in the troubleshooting guide.
