### ISSUE TITLE
[BUG] Upscayl process stops instantly

### ISSUE THREAD

**Issue by nekkitl** [upscayl/upscayl#825]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

Just drop any image and try upscale

### To Reproduce

idk watta hell

### Upscayl Version (or commit hash)

2.11.0 

### Platform

Windows

### OS Version

11 Pro Dev 22631.3447 (clean install week ago + all vc libs)

### GPU Name

AMD RX470 8GB (ASUS ROG StriX RX470 o8G ) latest vbios + vdriver

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/107915590/3759dcc7-6535-4580-a675-49bb69e57c4d)

### Logs

```sh
🎯 GET_MODELS_LIST:  C:\Users\Nick\Downloads\custom-models-main\models
🎒 BACKEND REPORTED:  📁 Updating Custom Models Folder Path:  C:\Users\Nick\Downloads\custom-models-main\models
🎒 BACKEND REPORTED:  📁 Custom Models Folder Path:  C:\Users\Nick\Downloads\custom-models-main\models
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  0
🔀 Setting model to 
🎒 BACKEND REPORTED:  🔎 Detected Custom Models:  4xHFA2k,4xLSDIR,4xLSDIRCompactC3,4xLSDIRplusC,4xNomos8kSC,4x_NMKD-Siax_200k,4x_NMKD-Superscale-SP_178000_G,realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,uniscale_restore,unknown-2.0.1
📜 CUSTOM_MODEL_FILES_LIST:  4xHFA2k,4xLSDIR,4xLSDIRCompactC3,4xLSDIRplusC,4xNomos8kSC,4x_NMKD-Siax_200k,4x_NMKD-Superscale-SP_178000_G,realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,uniscale_restore,unknown-2.0.1
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/png","filePath":"D:\\fsdaf.png","extension":"png"}
🖼 Setting image path:  D:\fsdaf.png
🗂 Setting output path:  D:
🖼 imagePath:  D:\fsdaf.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":"0","saveImageAs":"jpg","inputDir":"D:","fileNameWithExt":"fsdaf.png","outputDir":"C:\\Users\\Nick\\Downloads\\custom-models-main\\models","outFile":"C:\\Users\\Nick\\Downloads\\custom-models-main\\models\\fsdaf_upscayl_4x_realesrgan-x4plus.jpg","fileName":"fsdaf","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\fsdaf.png,-o,C:\Users\Nick\Downloads\custom-models-main\models\fsdaf_upscayl_4x_realesrgan-x4plus.jpg,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-g,0,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","D:\\fsdaf.png","-o","C:\\Users\\Nick\\Downloads\\custom-models-main\\models\\fsdaf_upscayl_4x_realesrgan-x4plus.jpg","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-g","0","-f","jpg","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  C:\Users\Nick\Downloads\custom-models-main\models\fsdaf_upscayl_4x_realesrgan-x4plus.jpg
💯 UPSCAYL_DONE:  C:\Users\Nick\Downloads\custom-models-main\models\fsdaf_upscayl_4x_realesrgan-x4plus.jpg
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  0
```

**Comment by nekkitl** [comment]
btw, on this PC also installed macOS Sonoma and app works great, lol.

**Comment by NayamAmarshe** [comment]
I suspect some sort of permission issue.

**Comment by nekkitl** [comment]
> I suspect some sort of permission issue.

Firstly I think so, but when I connected for experiment new empty disk, formatted and grant rights to all - I got same result.

Earlier I tried to restart app with highest rights in Windows by local admin. Said it - did it.
No sense.

Next step was recheck system and runtime libs:
Vulcan, DirectX and VisualC lib, but all are up-today. Moreover, works without any problems in other apps.

(btw, thx for DX Repair tool, useful)

**Comment by NayamAmarshe** [comment]
> > I suspect some sort of permission issue.
> 
> Firstly I think so, but when I connected for experiment new empty disk, formatted and grant rights to all - I got same result.
> 
> Earlier I tried to restart app with highest rights in Windows by local admin. Said it - did it. No sense.
> 
> Next step was recheck system and runtime libs: Vulcan, DirectX and VisualC lib, but all are up-today. Moreover, works without any problems in other apps.
> 
> (btw, thx for DX Repair tool, useful)

Could you try using the ZIP version?

**Comment by nekkitl** [comment]
At first try I downloaded an installer, then tried zipped version.
Same results.

**Comment by nekkitl** [comment]
If you need any additional info or logs - mo problem, just text me.

**Comment by NayamAmarshe** [comment]
It's hard for me to suggest anything outside of the troubleshooting guide. Does the upscayl work with default models?

**Comment by nekkitl** [comment]
No, I have tried default and some other models - result is negative.

**Comment by NayamAmarshe** [comment]
@dosu-bot

**Comment by nekkitl** [comment]
> It seems that the upscaling process in Upscayl version 2.11.0 on your Windows 11 Pro system stops instantly despite following all troubleshooting steps. Here are some potential reasons and solutions for this issue:
> 
> ### Potential Reasons and Solutions:
> 1. **Error Handling in the Code**:
>    The code provided includes mechanisms to handle errors and log them. If the process encounters any data that includes the word "Error" or "failed", it logs the error, sets `failed` to true, and kills the process, which could cause the process to stop instantly.
> 2. **GPU Compatibility**:
>    Ensure that your GPU drivers are up-to-date and that Vulkan is properly installed and configured. The AMD RX470 is Vulkan-compatible, but there might be specific issues with the drivers or Vulkan support on your system.
> 3. **File Read/Write Permissions**:
>    Double-check the permissions for the specific directories and files used by Upscayl to ensure they have the necessary read/write permissions.
> 4. **Custom Models**:
>    Ensure that the custom models you are using are compatible with Upscayl and that there are no issues with the model files themselves.
> 5. **System Libraries**:
>    Verify that all required system libraries (Vulkan, DirectX, VisualC) are up-to-date. It might be worth double-checking or reinstalling them to ensure there are no issues.
> 
> ### Additional Steps to Try:
> 1. **Run VulkanCapsViewer**:
>    Run [VulkanCapsViewer](https://github.com/SaschaWillems/VulkanCapsViewer) to verify that your system supports Vulkan and that there are no issues with Vulkan on your system.
> 2. **Set GPU ID**:
>    Try setting your GPU ID to your discrete GPU. You can find more information on how to do this in the [Upscayl Guide](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
> 3. **Check for Specific Error Messages**:
>    Look for specific error messages in the logs that might indicate the cause of the issue. The logs you provided do not show any explicit errors, but there might be additional logs or error messages that can provide more information.
> 4. **Reinstall Graphics Drivers**:
>    Reinstall your graphics drivers to ensure there are no issues with the drivers themselves. Before doing this, run VulkanCapsViewer to check for Vulkan support.
> 5. **Try Different Models**:
>    Try using different models (both default and custom) to see if the issue persists with all models or only specific ones.
> 
> If the issue persists after trying these steps, please provide any additional logs or error messages that might help in diagnosing the problem further.
> 
> #### Details
> _To continue the conversation, mention @dosu._

So, that's a default FAQ/troubleshoot, that I tried to do at first. Now problem gone, coz of Windows removed :D
