### ISSUE TITLE
[Feature Request] when will upsayl be added to the winget repository?

### ISSUE THREAD

**Issue by fislysandi** [upscayl/upscayl#83]
i just dont want to go to the github page download it and install it

i wanted to be like this : open cmd winget install upscayl.upscayl and get installed in not time same with updating upscayl.

**Comment by NayamAmarshe** [comment]
Never, sorry.

**Comment by TejasMate** [comment]
Can I try to add upscayl into the Winget repository?

**Comment by aaronliu0130** [comment]
Of course you can
