### ISSUE TITLE
Add the function of "Update app version" within app

### ISSUE THREAD

**Issue by jarvis1801** [upscayl/upscayl#833]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Check the version in app and update may be good, and no need watch the repo and update anymore

**Comment by NayamAmarshe** [comment]
It's already there though. The app tells you when an update is available.

**Comment by aaronliu0130** [comment]
In fact, it can download and run the installer for you or view the release notes at the click of a button.
