### ISSUE TITLE
Wipes out color profiles

### ISSUE THREAD

**Issue by kkthompson** [upscayl/upscayl#84]
Looks like it replaces currently color profiles with sRGB (even when they aren’t).

**Comment by NayamAmarshe** [comment]
Yeah this is a limitation on Real-ESRGAN's side. The algorithm changes the color palette. You can create an issue in their repository but I'm not sure if they'd fix it.

**Comment by m-kuutti** [comment]
This happens (at least) with ultrasharp and ultra mix models as well.

**Comment by NayamAmarshe** [comment]
Unfortunately, a bit difficult to do on Upscayl Desktop. This is a feature on Upscayl Cloud though.
