### ISSUE TITLE
i can not upscale image 4x with my asus a455l Laptop

### ISSUE THREAD

**Issue by djdhemitz** [upscayl/upscayl#846]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

i can not upscale image 4x with my asus a455l Laptop, can you help me?

### Screenshots

⚙️ Setting saveImageAs to png
🔀 Setting model to realesrgan-x4plus
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
🖼 Selected Image Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
📁 Selected Image Directory:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version
🖼 imagePath:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
🔤 Extension:  png
🎒 BACKEND REPORTED:  📄 Selected File Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version","fileNameWithExt":"tengrai_image_1716775989_3431115.png","outputDir":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version","outFile":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115_upscayl_4x_realesrgan-x4plus.png","fileName":"tengrai_image_1716775989_3431115","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png,-o,D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115_upscayl_4x_realesrgan-x4plus.png,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115.png","-o","D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115_upscayl_4x_realesrgan-x4plus.png","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

🔄 Resetting Upscaled Image Path
🚫 No valid image selected
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
🎒 BACKEND REPORTED:  📄 Selected File Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
🖼 Selected Image Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
📁 Selected Image Directory:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version
🖼 imagePath:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version","fileNameWithExt":"tengrai_image_1716775989_3431115.png","outputDir":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version","outFile":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115_upscayl_4x_realesrgan-x4plus.png","fileName":"tengrai_image_1716775989_3431115","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png,-o,D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115_upscayl_4x_realesrgan-x4plus.png,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115.png","-o","D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115_upscayl_4x_realesrgan-x4plus.png","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115-upscale.png
🎒 BACKEND REPORTED:  📄 Selected File Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115-upscale.png
🖼 Selected Image Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115-upscale.png
📁 Selected Image Directory:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version
🖼 imagePath:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115-upscale.png
🔤 Extension:  png
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
🎒 BACKEND REPORTED:  📄 Selected File Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
🖼 Selected Image Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
📁 Selected Image Directory:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version
🖼 imagePath:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version","fileNameWithExt":"tengrai_image_1716775989_3431115.png","outputDir":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version","outFile":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115_upscayl_2x_realesrgan-x4plus.png","fileName":"tengrai_image_1716775989_3431115","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png,-o,D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115_upscayl_2x_realesrgan-x4plus.png,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115.png","-o","D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115_upscayl_4x_realesrgan-x4plus.png","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  nvidia
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
🖼 Selected Image Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
📁 Selected Image Directory:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version
🖼 imagePath:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
🔤 Extension:  png
🎒 BACKEND REPORTED:  📄 Selected File Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  nvidia
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  nvidia
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":"nvidia","saveImageAs":"png","inputDir":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version","fileNameWithExt":"tengrai_image_1716775989_3431115.png","outputDir":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version","outFile":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115_upscayl_4x_realesrgan-x4plus.png","fileName":"tengrai_image_1716775989_3431115","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115.png,-o,D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775989_3431115_upscayl_4x_realesrgan-x4plus.png,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-g,nvidia,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115.png","-o","D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115_upscayl_4x_realesrgan-x4plus.png","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  nvidia
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  nvidia
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775991_1348548.png
🎒 BACKEND REPORTED:  📄 Selected File Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775991_1348548.png
🖼 Selected Image Path:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775991_1348548.png
📁 Selected Image Directory:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version
🖼 imagePath:  D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775991_1348548.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":"nvidia","saveImageAs":"png","inputDir":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version","fileNameWithExt":"tengrai_image_1716775991_1348548.png","outputDir":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version","outFile":"D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775991_1348548_upscayl_4x_realesrgan-x4plus.png","fileName":"tengrai_image_1716775991_1348548","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775991_1348548.png,-o,D:\[AI WORK] - [TENGR.AI] (NSFW)\Carmen Electra Cosplay as Princess Jasmine New Version\tengrai_image_1716775991_1348548_upscayl_4x_realesrgan-x4plus.png,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-g,nvidia,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115.png","-o","D:\\[AI WORK] - [TENGR.AI] (NSFW)\\Carmen Electra Cosplay as Princess Jasmine New Version\\tengrai_image_1716775989_3431115_upscayl_4x_realesrgan-x4plus.png","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  nvidia

**Comment by aaronliu0130** [comment]
Please file a bug report and follow that template's instructions.
