### ISSUE TITLE
[FEATURE REQUEST] keep image noise. no suppress noise

### ISSUE THREAD

**Issue by badddev** [upscayl/upscayl#849]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

I'm using Google Translate so I ask for understanding for the strange sentences. Anyway, I'm new to using the application so I don't even know if there is already an option to keep the noise in the image, but if it isn't, I humbly ask you to add it because it would help me a lot, and if you already have this option, I ask you to tell me where it is, because I looked a lot and so far I haven't found anything.

**Comment by NayamAmarshe** [comment]
That depends on the model. You could try other models to keep the noise.

**Comment by DJboutit** [comment]
Sound like your using a model or 2 that does like 35% to 40% more sharpening that you like these 2 models you should stay away from BSGRAN and 4X RealisticRescaler.  Try these two models Ultrasharp and Ultramix Balanced these leave more details.
