### ISSUE TITLE
Companion AI APP suggestion 

### ISSUE THREAD

**Issue by alcomposer** [upscayl/upscayl#85]
Hello,

First - great app, simple, and does one job very well!

I would like to suggest that your team takes a look at rembg: https://github.com/danielgatis/rembg

rembg is another python AI tool, which removes backgrounds from images (or video image sequences).

This may be a great companion app (another app, not upscayl) to your upscaling app, as it also uses AI, and very similar toolchains.

rembg is python cli, which is very complex to get working (as in correct python env, packages, cuda etc)

If not, no problem, thanks for this great app!

Cheers,
Alex

**Comment by NayamAmarshe** [comment]
We were thinking of adding this, the only problem is finding out how to create binaries for all 3 operating systems, it's a huge task.

**Comment by NayamAmarshe** [comment]
I'll close this issue for now. When I get time to explore more binaries, will reopen.

**Comment by BinaryQuantumSoul** [comment]
> We were thinking of adding this, the only problem is finding out how to create binaries for all 3 operating systems, it's a huge task.

Hey, are you still considering this? @NayamAmarshe
