### ISSUE TITLE
作者您好，能出个中文汉化吗？

### ISSUE THREAD

**Issue by liteyais** [upscayl/upscayl#850]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

请求作者增加一个语言切换的功能，是否可以增加中文切换。

**Comment by aaronliu0130** [comment]
Duplicate of #91
> I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Comment by jiehwa** [comment]
中文汉化版本在这里：https://upscale.huazhiai.tech/zh
@liteyais

**Comment by liteyais** [comment]
> 中文汉化版本在这里：https://upscale.huazhiai.tech/zh @liteyais

不是一个东西啊

**Comment by aaronliu0130** [comment]
是的
> Version:2.11.5, fork from [Upscayl](https://github.com/upscayl)
他们好似没看到我们的 license，不过因为大概只是把一大堆字符串改了一下应该没关系

**Comment by liteyais** [comment]
> 是一个东西
> 
> > Version:2.11.5, fork from [Upscayl](https://github.com/upscayl)
> 
> 他们好似没看到我们的 license，不过因为大概只是把一大堆字符串改了一下应该没关系

没看懂啊大佬

**Comment by aaronliu0130** [comment]
打开 @jiehwa 发的链接然后往下滑

**Comment by liteyais** [comment]
只看到一个win客户端的，没看到mac的

**Comment by aaronliu0130** [comment]
百度“upscayl mac汉化”即可找到 https://www.maczh.com/app/upscayl.html

**Comment by NayamAmarshe** [comment]
在下次更新中，我将添加更多语言

**Comment by NayamAmarshe** [comment]
https://github.com/orgs/upscayl/discussions/899

**Comment by jiehwa** [comment]
> 是一个东西
> 
> > Version:2.11.5, fork from [Upscayl](https://github.com/upscayl)
> 
> 他们好似没看到我们的 license，不过因为大概只是把一大堆字符串改了一下应该没关系

你们支持四方连续图的高清放大吗？我主要的目的是想要扩展四方连续图的高清放大功能

> 是一个东西
> 
> > Version:2.11.5, fork from [Upscayl](https://github.com/upscayl)
> 
> 他们好似没看到我们的 license，不过因为大概只是把一大堆字符串改了一下应该没关系

核心功能是增加了四方连续图的高清放大，汉化和多语言是其次的。因为不管是 upscayl 还是其他的高清放大工具，目前都无法支持四方连续图的高清放大

**Comment by jiehwa** [comment]
> 只看到一个win客户端的，没看到mac的

目前目前苹果开发者账号还在申请中，先支持了 win 版本。后续有需要再加 mac 版本
