### ISSUE TITLE
Upscayl how to use with video-files using custom-models

### ISSUE THREAD

**Issue by typoworx-de** [upscayl/upscayl#853]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

Website mentions upscayl is able to process videos and I've checked out [upscayl custom-models](https://github.com/upscayl/custom-models) and selected that model folder. But still the file-dialog only allows to select image-formats.

Is this a bug or does upscayl not (yet) support processing video-upscaling?

### To Reproduce

1. Do git checkout out [upscayl custom-models](https://github.com/upscayl/custom-models) to local folder.
2. In Upscayl > settings select custom modal-path
3. try to open a video for processing

### Upscayl Version (or commit hash)

2.11 (recent snap)

### Platform

Linux

### OS Version

Ubuntu 23.04 (Lunar)

### GPU Name

NVIDIA GeForce RTX 4060

### Expected Behavior

As there are models for video-processing and upscayl website mentions video-processing I would expect it's working

### Logs

```sh
Nothing to log for this problem
```

**Comment by aaronliu0130** [comment]
See #542!
