### ISSUE TITLE
Add Real-CUGAN for anime upscaling?

### ISSUE THREAD

**Issue by AshtakaOOf** [upscayl/upscayl#86]
This is a suggestion.
https://github.com/bilibili/ailab/blob/main/Real-CUGAN/README_EN.md
https://github.com/nihui/realcugan-ncnn-vulkan
https://github.com/nullArrayList/Real-CUGAN/blob/master/README_EN.md
This an upscale AI made for Anime pictures, so maybe you could try adding it for v2?
Feel free to close this issue if you don't want to deal with it.
ps: It's MIT Licensed, and made by bilibili.

**Comment by NayamAmarshe** [comment]
Yeah, we can consider adding this, no problem.

**Comment by AshtakaOOf** [comment]
Any ETA?

**Comment by AshtakaOOf** [comment]
Uh @NayamAmarshe why was this closed?

**Comment by NayamAmarshe** [comment]
> Uh @NayamAmarshe why was this closed?

Check #200

I'll be adding an option to choose custom models

**Comment by AshtakaOOf** [comment]
Okay thanks, just want to let you know this model work differently from Real-ESRGAN and others.

**Comment by NayamAmarshe** [comment]
> Okay thanks, just want to let you know this model work differently from Real-ESRGAN and others.

If this requires a different binary, I unfortunately cannot include it as our application size is already quite big. I wouldn't mind 10-20 MB extra though.

**Comment by aaronliu0130** [comment]
Note that Real-ERSGAN is not a model, it's basically a program to apply models.
