### ISSUE TITLE
Log image input and output pixel dimensions

### ISSUE THREAD

**Issue by KyodaiKen** [upscayl/upscayl#868]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

The input and output image dimensions in pixels should be logged. This could come in handy when troubleshooting issue #493 and related issues.

### Related Problem(s)

#493

**Comment by aaronliu0130** [comment]
Implemented some time ago:
```sh
🎒 BACKEND REPORTED:  🏞️ Resized image from 1920x1325 to 3840x2650
```
