### ISSUE TITLE
Build for Apple Silicon chip

### ISSUE THREAD

**Issue by fnankivell** [upscayl/upscayl#87]
Are you planning on having a build for Apple silicon chip? Thank you!

**Comment by NayamAmarshe** [comment]
The build that we provide works on >= M1. So for now, we're not planning to release an ARM version.

**Comment by Brog33** [comment]
It works on M1, but it needs Rosetta to work. It would be highly appreciated if you could build for Apple Silicon. Hope you will consider this for the next major update.

**Comment by aaronliu0130** [comment]
I think we could also build on macos-11.

**Comment by aaronliu0130** [comment]
I can't remove the 2.5 label because "The token seems to be incorrect or expired. Update it in the options."?
