### ISSUE TITLE
Output file name unchanged? 

### ISSUE THREAD

**Issue by Softboi1** [upscayl/upscayl#875]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

i have a large batch of files that need to be upscaled without their name changing and to replace their old un-upscaled selfs

if this is possible how do i go about it? this would really really help me out

**Comment by aaronliu0130** [comment]
Another alternative that doesn't require JavaScript knowledge and completely averts all risk of AI channeling Their raw power through your precious computer and taking over the solar system is to post-process the file names.
I'd recommend [PowerRename](https://github.com/microsoft/PowerToys/wiki/PowerRename), which is part of Microsoft® (😱)'s [PowerToys](https://github.com/microsoft/PowerToys), must-had software for Windows. After installing PowerToys and finishing the batch upscayl, you select all the output inside the output folder with Ctrl+A after going inside the folder, right click, go under "More options" if you're using Windows 11, and click "Rename with PowerRename". Then, simply put the part of the filename you want to remove plus the file extension (e.g. _upscayl_4x_realesrgan-x4fast.jpg) into the "Search for" field, and only put the file extension (e.g. .jpg) into the "Replace with" field. Then, click "Apply".
If you're using Linux or macOS, you can ask dosu (or any AI (or Bing if you're lucky)) to find a command that renames stuff for you.
