### ISSUE TITLE
What are the different models capable of?

### ISSUE THREAD

**Issue by max1mvs** [upscayl/upscayl#879]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

As a layman regarding models, it would be beneficial to have a short description of what the different models are good at—perhaps 1-2 paragraphs underneath the selector at step 2 in the UI.

**Comment by NayamAmarshe** [comment]
I have gotten this request quite a few times. I'll look into adding screenshots in the UI :)

**Comment by max1mvs** [comment]
Sounds great! ⭐️
