### ISSUE TITLE
[Suggestion] Multi GPU support

### ISSUE THREAD

**Issue by NXTler** [upscayl/upscayl#88]
Just what the title says to be honest.

**Comment by NayamAmarshe** [comment]
Providing an interface to multi-GPU options is hard to achieve with consistency and guaranteed compatibility, sorry. So I'd recommend that you use the REAL-ESRGAN CLI instead of Upscayl.

**Comment by NXTler** [comment]
Other Idea would be to give you the ability to select the gpu to use. In that way I could just start anothet instance with a different gpu selected.

**Comment by NayamAmarshe** [comment]
> Other Idea would be to give you the ability to select the gpu to use. In that way I could just start anothet instance with a different gpu selected.

Yeah, I can add that but the only thing that worries me is detecting whether there are multiple GPUs available or not. I'm not entirely sure if that's possible but I'll see what I can do.
