### ISSUE TITLE
Failing to upscale any image on AMD based laptop  vkAllocateMemory failed -2

### ISSUE THREAD

**Issue by cas8180** [upscayl/upscayl#880]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

Unable to upscale any image. When I drag the image onto the canvas, with default settings and just click upscale. The app is reporting that the upscaling was successful. However, it is not. My laptop is using a AMD 780m GPU. I would like to note that I have used this app on both my m1 pro and mother other intel based laptop without any issues.

### To Reproduce

This could be a bit hard to reproduce as this is specific to my latop and gpu I believe. But I am running an AMD Ryzen 7 pro 7840u with Radeon 780M graphics.

Repro steps:
drag any image onto the default canvas and simply click upscale. 
The app executes quickly with a success message indicating that the image has been successfully upscaled. However, the upscaled version of the image is never created

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

Windows 11 Build 22631

### GPU Name

780M

### Expected Behavior

Image to be properly upscaled

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/1483688/6cbdc217-da85-4d59-b2d8-26be50749641)

### Logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Remacri)","value":"remacri"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to remacri
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Remacri)","value":"remacri"}
⚙️ Setting gpuId to empty string
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/jpeg","filePath":"C:\\Users\\cas81\\Downloads\\_4ad23c6a-6491-47b0-99df-965ea916e7df.jpg","extension":"jpg"}
🖼 Setting image path:  C:\Users\cas81\Downloads\_4ad23c6a-6491-47b0-99df-965ea916e7df.jpg
🗂 Setting output path:  C:\Users\cas81\Downloads
🖼 imagePath:  C:\Users\cas81\Downloads\_4ad23c6a-6491-47b0-99df-965ea916e7df.jpg
🔤 Extension:  jpg
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Remacri)","value":"remacri"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to remacri
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"remacri","gpuId":null,"saveImageAs":"png","inputDir":"C:\\Users\\cas81\\Downloads","fileNameWithExt":"_4ad23c6a-6491-47b0-99df-965ea916e7df.jpg","outputDir":"C:\\Users\\cas81\\Downloads","outFile":"C:\\Users\\cas81\\Downloads\\_4ad23c6a-6491-47b0-99df-965ea916e7df_upscayl_4x_remacri.png","fileName":"_4ad23c6a-6491-47b0-99df-965ea916e7df","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\cas81\Downloads\_4ad23c6a-6491-47b0-99df-965ea916e7df.jpg,-o,C:\Users\cas81\Downloads\_4ad23c6a-6491-47b0-99df-965ea916e7df_upscayl_4x_remacri.png,-m,C:\Program Files\Upscayl\resources\models,-n,remacri,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\cas81\\Downloads\\_4ad23c6a-6491-47b0-99df-965ea916e7df.jpg","-o","C:\\Users\\cas81\\Downloads\\_4ad23c6a-6491-47b0-99df-965ea916e7df_upscayl_4x_remacri.png","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","remacri","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  [0 AMD Radeon(TM) 780M]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[0 AMD Radeon(TM) 780M]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon(TM) 780M]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon(TM) 780M]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 AMD Radeon(TM) 780M]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[0 AMD Radeon(TM) 780M]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon(TM) 780M]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon(TM) 780M]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  vkAllocateMemory failed -2

🚧 UPSCAYL_PROGRESS:  vkAllocateMemory failed -2

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  C:\Users\cas81\Downloads\_4ad23c6a-6491-47b0-99df-965ea916e7df_upscayl_4x_remacri.png
💯 UPSCAYL_DONE:  C:\Users\cas81\Downloads\_4ad23c6a-6491-47b0-99df-965ea916e7df_upscayl_4x_remacri.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Remacri)","value":"remacri"}
⚙️ Setting gpuId to empty string
```

**Comment by aaronliu0130** [comment]
It sounds like running out of emmory.

**Comment by cas8180** [comment]
> It sounds like running out of emmory.

I am pretty sure thats not the issue, I have 32gb of ram on this PC. My intel PC and Mac m1 both have 16gb of ram and can run this app just fine. Its some kind of incompatibility with the AMD Ryzen.

**Comment by aaronliu0130** [comment]
What about video memory?

**Comment by cas8180** [comment]
> What about video memory?

I dont if this will help, but  I recorded a loom showing the repro steps and the behavior I am seeing.

https://www.loom.com/share/5d2efd2e8a0a4ecabd7e7e7baffca796

**Comment by aaronliu0130** [comment]
Yeah, I don't think it helps much. What about video memory?

**Comment by cas8180** [comment]
I don’t know how to determine that but I don’t feel like that’s the issue considering I have ran this on several laptops that are much lower spec’s than this one.

Sent from my iPhone

On Jun 23, 2024, at 10:11 AM, Aaron Liu ***@***.***> wrote:

﻿

Yeah, I don't think it helps much. What about video memory?

**Comment by Megane1c** [comment]
I encountered this too. Currently using 5600g APU since I placed my GPU on another machine. I have set my APU to use 4gb of vram.

**Comment by aaronliu0130** [comment]
Have y'all tried disabling switchable graphics?

**Comment by Megane1c** [comment]
> Have y'all tried disabling switchable graphics?

In my case, I do not have a switchable graphics since I only have the APU of 5600G.

**Comment by aaronliu0130** [comment]
As said in the README, probably because that's integrated graphics. Try the workaround?
