### ISSUE TITLE
Add JFIF support

### ISSUE THREAD

**Issue by SuperNerd-James** [upscayl/upscayl#888]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

The file open dialog does not support JFIF, there is no option for it in the file selector, nor an "All Files" option, so they don't show in the picker. Renaming the JFIF to JPG works, but this is tedious and needless. JFIF is technically JPG anyway. Bing Creator has all of a sudden started saving in JFIF in Edge, when it used to do JPG, and I use Upscayl to upscale them.

![JFIF-issue-Upscayl](https://github.com/upscayl/upscayl/assets/2358163/0813d140-b372-49fe-9092-db74fce20409)

### Alternatives

A workaround is to edit the extension to JPG, this makes them show up but is tedious with large amounts of files.

**Comment by NayamAmarshe** [comment]
Here's a discussion: https://github.com/orgs/upscayl/discussions/886
