### ISSUE TITLE
a error happen to open a local build exe file 

### ISSUE THREAD

**Issue by jiehwa** [upscayl/upscayl#889]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

![image](https://github.com/upscayl/upscayl/assets/3799526/cc13122e-6dd8-4e41-b80c-a47355dcd326)
I run the exe file which i build local (run  pnpm  dist:win) , i get a error 

### To Reproduce

1.run pnpm dist:win 
2.find the exe file in dist
3. click exe file to install it ,and then open it 

### Upscayl Version (or commit hash)

main branch

### Platform

Windows

### OS Version

window 11

### GPU Name

4090

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/3799526/cc13122e-6dd8-4e41-b80c-a47355dcd326)

### Logs

```sh
![image](https://github.com/upscayl/upscayl/assets/3799526/cc13122e-6dd8-4e41-b80c-a47355dcd326)
```

**Comment by aaronliu0130** [comment]
Upscayl requires a binary executable of https://github.com/upscayl/upscayl-ncnn at resources/[platform]/bin/upscayl-bin to run.

**Comment by jiehwa** [comment]
Don't use pnpm or yarn,Just  use npm !!!

**Comment by aaronliu0130** [comment]
pnpm is faster.

**Comment by NayamAmarshe** [comment]
pnpm has issues, which is why I don't use it and don't recommend it for Upscayl. The type definitions break too often for me + there might be packages that do not support pnpm.
