### ISSUE TITLE
Possibility of adding the colorizing AI?

### ISSUE THREAD

**Issue by MrQuerter** [upscayl/upscayl#89]
Hello again. I am in awe how well this upscayler of yours works on images that I didn't think would work well with it. One question since it is the easiest program that I encountered so far when it comes to AI. Would it be possible to add colorizing AI such as DeOldify? I don't know how all this works, but could it be included? (doesn't exactly match the upscayl name, but who knows) Would be fantastic to watch old movies in color (that's of course after upscayl has video support, but I suppose it will be made)

**Comment by NayamAmarshe** [comment]
Yes, it's possible if the model can be converted to ncnn vulkan. Will explore this when I get more time :)

**Comment by DJboutit** [comment]
I have noticed that a lot of images with Upscayl after image has been process brightness and contrast has been dropped like 35%.  Also colors look 35% less vibrant to.  This needs be fixed

**Comment by aaronliu0130** [comment]
Hi @DJboutit, that would belong in a separate issue complete with images.
