### ISSUE TITLE
denoising option

### ISSUE THREAD

**Issue by kalle07** [upscayl/upscayl#893]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

is it possible to add an denoising slider strength and steps

**Comment by aaronliu0130** [comment]
See #849. The noise change is dependent on the models and not just something we can just slider through.

**Comment by MinePro120** [comment]
Are there any future plans to add denoise models though? Maybe in the `custom-models` repo.

**Comment by aaronliu0130** [comment]
You could make a PR in that repo for that.
