### ISSUE TITLE
Issue with the Upscayl Program

### ISSUE THREAD

**Issue by SAMEHAli19717** [upscayl/upscayl#897]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

GPU Error
Ran into an issue with the GPU. Please read the docs for troubleshooting! (vkCreateInstance failed -9 Error: Invalid GPU Device
X
![بيبب](https://github.com/upscayl/upscayl/assets/174484171/58504cea-0742-4d24-bd80-f44bd461b837)

### To Reproduce

.....

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

Windows 10

### GPU Name

Intel® HD Graphics Family

### Expected Behavior

.....

### Screenshots

.....

### Logs

```sh
.....
```

**Comment by aaronliu0130** [comment]
> Yes, unfortunately. NCNN Vulkan requires a Vulkan-compatible GPU. Upscayl won't work with most iGPUs or CPUs.

A workaround exists for Windows and Linux in #580.

> Make sure to read [the FAQ](https://github.com/upscayl/upscayl#-faq) first to avoid getting rickrolled.

> If the name is something like "Intel Core", "Intel Graphics" or "AMD Vega" and you can't Upscayl images, [STOP and read the 3rd point in the FAQ](https://github.com/upscayl/upscayl?tab=readme-ov-file#-faq).

![compulsory rickrolls are issued for duplicates of issues and the FAQ and normies who use intelgrated GPUs](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
