### ISSUE TITLE
为什么我导出的图片是纯黑色

### ISSUE THREAD

**Issue by llywjngit** [upscayl/upscayl#900]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

我导出一张图片，导出来是黑色，，

### To Reproduce

麻烦解答

### Upscayl Version (or commit hash)

无

### Platform

Linux

### OS Version

win10

### GPU Name

无

### Expected Behavior

无

### Screenshots

无

### Logs

```sh
无
```

**Comment by aaronliu0130** [comment]
无信息，无帮助
