### ISSUE TITLE
Mangajanai Support

### ISSUE THREAD

**Issue by zeoint** [upscayl/upscayl#901]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Please support [mangajanai](https://github.com/the-database/mangajanai) in models.

**Comment by aaronliu0130** [comment]
Upscayl is a GUI for upscayl-ncnn, our CLI for REAL-ESRGAN upscayling. Custom models for REAL-ESRGAN can be converted according to instructions in the README; models based on any other algorithms are not supported.
