### ISSUE TITLE
Upscayl does not run in Ubuntu 24.04 due to apparmor issue

### ISSUE THREAD

**Issue by archisman-panigrahi** [upscayl/upscayl#902]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

Due to recent changes in apparmor, upscayl does not run in Ubuntu 24.04. Ubuntu based distributions like Linux Mint 22 is also affected.

```
$ upscayl 
[14893:0706/103815.419970:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_upscayYkv01E/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

This is not really an upscayl bug, but a regression in Ubuntu. Many other apps are [not working as well](https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844). I am reporting the bug here to explain why the issue is occurring, because there may be duplicates in the future.

The solution is described [here](https://askubuntu.com/questions/1511654/how-to-make-balena-etcher-work-in-ubuntu-24-04/1511655#1511655) (temporary solution) and [here](https://askubuntu.com/questions/1511654/how-to-make-balena-etcher-work-in-ubuntu-24-04/1511655#1511655) (permanent solution).

### To Reproduce

Install .deb file of upscayl in Ubuntu 24.04 and try to run it. It will not run graphically, and if run from terminal, it will crash with the error message I posted above.

### Upscayl Version (or commit hash)

2.5.5

### Platform

Linux

### OS Version

Ubuntu 24.04

### GPU Name

WhiskeyLake-U GT2 (UHD Graphics 620)

### Expected Behavior

Upscayl should run without any error.

### Logs

```sh
[14893:0706/103815.419970:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_upscayYkv01E/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

**Comment by aaronliu0130** [comment]
I'm assuming newer versions don't work either?[[2]](https://tally.miraheze.org/wiki/n/a)[[3]](https://tally.miraheze.org/wiki/n/a)[[1]](https://zombo.com)

**Comment by NayamAmarshe** [comment]
> I'm assuming newer versions don't work either?[[2]](https://tally.miraheze.org/wiki/n/a)[[3]](https://tally.miraheze.org/wiki/n/a)[[1]](https://zombo.com)

What are the links that you added?

**Comment by archisman-panigrahi** [comment]
@NayamAmarshe That comment seems to be spam

**Comment by aaronliu0130** [comment]
I linked random stuff to parody the reference order at the end of dosubot's message. Sorry for the confusion.
Anyway, I think that's confirmation that this doesn't work with 2.11.5 either. Maybe we could look into electron-builder's docs.

**Comment by archisman-panigrahi** [comment]
> Maybe we could look into electron-builder's docs.

It will not work. All electron apps are affected. https://github.com/electron/electron/issues/41066#issuecomment-1913509942

A few electron app like VS Code work because the Ubuntu and apparmor developers manually hand-picked and allowed them.

**Comment by NayamAmarshe** [comment]
You should wait for the apparmor update

**Comment by archisman-panigrahi** [comment]
This is a Ubuntu bug rather than an upscale bug.

The permanent solution has been described here https://askubuntu.com/q/1511854/124466

**Comment by lproven** [comment]
> This is a Ubuntu bug rather than an upscale bug.

I agree this is an Ubuntu bug. It also affects me, on both 24.04 and 24.10.

I can't find a bug on Launchpad. Does anyone know of one?

**Comment by archisman-panigrahi** [comment]
This is the main bug where hundreds of affected apps are listed https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844.

You can create a separate bug for upscayl and link this bug against it.
