### ISSUE TITLE
Update FAQ: In Arch Linux, vulkan needs to be installed separately from graphics drivers

### ISSUE THREAD

**Issue by archisman-panigrahi** [upscayl/upscayl#906]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

I am using upscayl on Arch Linux and encountered [this](https://github.com/upscayl/upscayl/issues/878) error. 

I had already installed intel graphics driver during system installation, but turns out that I also had to install the `vulkan-intel` package manually for upscayl to run (everything else worked fine without the vulkan drivers). 
For other graphics card, the name of the appropriate package may be found at https://wiki.archlinux.org/title/Vulkan#Installation

I suggest we add this information (that vulkan driver may need to be installed manually in some distros like Arch) to the Linux section in Wiki/DosuBot/docs.

**Comment by NayamAmarshe** [comment]
Thanks, I'll add the info!

**Comment by aaronliu0130** [comment]
Added to https://github.com/upscayl/upscayl/wiki/Troubleshooting.
