### ISSUE TITLE
[FEATURE REQUEST] i18n Localization

### ISSUE THREAD

**Issue by kirill0ermakov** [upscayl/upscayl#91]
Hello! Maybe You can add Ukraine localization? I can and want to help for this

**Comment by NayamAmarshe** [comment]
Hey, thanks for willing to contribute. For localization, I think I'd have to setup multi-lang support first. Will see what's possible :)

**Comment by kirill0ermakov** [comment]
Then I'll just say that if the opportunity arises, I'd be happy to contribute :)

**Comment by lyonelf** [comment]
same for french language ;)

**Comment by MarcosKlender** [comment]
I want to help localize the entire app to English (:

**Comment by MarcosKlender** [comment]
I want to help localize the entire app to Spanish (:

**Comment by aaronliu0130** [comment]
You can start out with porting the entire app to a translation framework!

**Comment by kailous** [comment]
You can use json language packs
This way you can make your own language pack replacements to achieve localization. You can also localize by modifying the source code and injecting text replacement scripts, but maintenance is too difficult and each update is troublesome.

**Comment by aaronliu0130** [comment]
As with any other translation framework, we'd have to replace all strings first. Slightly tedious.

**Comment by abhishek-gaonkar** [comment]
@NayamAmarshe assign it to me

**Comment by abhishek-gaonkar** [comment]
Hi @aaronliu0130 , 
Yes.. I had a talk with @NayamAmarshe
Do you have a implementation system in mind? Or should I think of one myself?

**Comment by NayamAmarshe** [comment]
@abhishek-gaonkar Could you see what options do we have? Let's do a review of the most popular ways and then pick one :)

**Comment by abhishek-gaonkar** [comment]
Yeah, sounds good

**Comment by NayamAmarshe** [comment]
I found this: https://youtu.be/BTTwpt8IbFw

**Comment by NayamAmarshe** [comment]
I found this: https://next-intl-docs.vercel.app/

**Comment by NayamAmarshe** [comment]
For languages, I've decided on the following:
Mandarin, French, Japanese, Spanish, Russian

**Comment by abhishek-gaonkar** [comment]
looks good.. i'll get started

**Comment by abhishek-gaonkar** [comment]
Looks like in Next config, you cannot use i18n and output: "export" in the same configuration.
`
[9178:0828/112020.871676:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
(node:9132) UnhandledPromiseRejectionWarning: Error: Specified "i18n" cannot be used with "output: export". See more info here: https://nextjs.org/docs/messages/export-no-i18n
    at assignDefaults (/home/gaonkar/Projects/Open-Source/upscayl/node_modules/next/dist/server/config.js:269:19)
    at loadConfig (/home/gaonkar/Projects/Open-Source/upscayl/node_modules/next/dist/server/config.js:765:32)
    at async initialize (/home/gaonkar/Projects/Open-Source/upscayl/node_modules/next/dist/server/lib/router-server.js:51:20)
    at async NextCustomServer.prepare (/home/gaonkar/Projects/Open-Source/upscayl/node_modules/next/dist/server/next.js:240:28)
    at async devServer (/home/gaonkar/Projects/Open-Source/upscayl/node_modules/electron-next/index.js:18:3)
    at async module.exports (/home/gaonkar/Projects/Open-Source/upscayl/node_modules/electron-next/index.js:96:3)
    `

This has been mentioned here: [Issue](https://nextjs.org/docs/messages/export-no-i18n)

**Comment by abhishek-gaonkar** [comment]
Can I remove output: "export" from next.config.js?
const nextConfig = {
  **output: "export",**
  images: {
    unoptimized: true,
  },
  experimental: {
    externalDir: true,
  },
  i18n: {
    locales: ["en-US", "ru", "jp"],
    defaultLocale: "en-US",
  },
};

**Comment by NayamAmarshe** [comment]
No, it'll break the app.

Maybe we can use export: standalone?

**Comment by abhishek-gaonkar** [comment]
@NayamAmarshe Yeah, output: "standalone" works..

**Comment by NayamAmarshe** [comment]
Okay, I'll take a look at this

**Comment by abhishek-gaonkar** [comment]
I found that most i18n packages work with similar implementation.. 
If you find a workaround ping me..

**Comment by NayamAmarshe** [comment]
@abhishek-gaonkar #950 is the PR that adds language switcher support. Here are the action items:

1. Port all strings in `/renderer` to the new translations system.
2. Strings will be stored in `locales/en.json`.
3. The renderer, where it uses strings, they'll now use the new `{t(category.stringName)}`

That's pretty much it :)

**Comment by abhishek-gaonkar** [comment]
@NayamAmarshe PR: https://github.com/upscayl/upscayl/pull/953

**Comment by aaronliu0130** [comment]
Just gotta create the template JSON (and maybe set up a translations website, I recommend translatewiki) now!

**Comment by abhishek-gaonkar** [comment]
I have kept a template.json file in there for this reason..

**Comment by NayamAmarshe** [comment]
> Just gotta create the template JSON (and maybe set up a translations website, I recommend translatewiki) now!

We can use ChatGPT for the most part thankfully. It's quite good when it comes to languages.

**Comment by aaronliu0130** [comment]
> I have kept a template.json file in there for this reason..

Yeah, that’s in PR #953, which isn’t merged yet.
