### ISSUE TITLE
Add denoise setting

### ISSUE THREAD

**Issue by kalle07** [upscayl/upscayl#915]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Add denoise setting

and may add an option that on image processed with all upscalers same conitions too check whcih uscaler best result

### Related Problem(s)

at the moment i think 
10 steps denoise 0.1

**Comment by aaronliu0130** [comment]
Duplicate of #893, dude. Uncool.
> I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
