### ISSUE TITLE
Install in Google Colab

### ISSUE THREAD

**Issue by didisya** [upscayl/upscayl#916]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

I don't have a GPU on my PC, can I run Upscayl in Google Colab or Sagemaker Studio Lab?

**Comment by aaronliu0130** [comment]
Instructions are in the FAQ.

> Make sure to read [the FAQ](https://github.com/upscayl/upscayl#-faq) first to avoid getting rickrolled.

![compulsory rickrolls are issued for duplicates of issues and the FAQ and normies who use intelgrated GPUs](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
