### ISSUE TITLE
Denoise again ...

### ISSUE THREAD

**Issue by kalle07** [upscayl/upscayl#919]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

dude ... 
maybe denoise is bit depend on model but if you just look outside your box, see below it give it in real
and also you can support the image with a prompt

you can copy and paste from 
A1111 or
WebUI_Forge or
CompfUi or
...

### Related Problem(s)

...

### Alternatives

![grafik](https://github.com/user-attachments/assets/95c4f888-67e5-4fad-9fa3-7522280495ef)

**Comment by aaronliu0130** [comment]
Again, that is simply not how our software works. Your screenshot is from a Stable Diffusion client while we are nearly purely Real-ESRGAN-ncnn, a specific implementation of Real-ESRGAN. We cannot simply "copy" over a frontend connected to a nonexistent backend.

Please listen to our comments and *stop opening new issues*. If you think we are wrong, just reply in the original issue. If you open another issue, you will be blocked from this repo.
