### ISSUE TITLE
Sharpening Smoothing Is Way To High For like 50% to 60% Images I Have Processed

### ISSUE THREAD

**Issue by DJboutit** [upscayl/upscayl#92]
I have noticed for like 50% to 60% of images I have process sharpening smoothing is like 35% to 60% to high it makes the images look they are 3d computer generated images.  Sharpening smoothing needs to be turned down a good amount many you have 3 or 4 different levels to select from like Low 2 Mid and high or 1 Mid 2 high settings for sharpening smoothing.  

A lot of images just need a good amount more of upscaling then a good amount of sharpening smoothing.  

One more thing is some images are only processed to 1.5x to 2x bigger while others are 3x to 4.5x would be nice to have selectable sizes we could chose from to have the images processed to like 2x to 4.5x bigger.

**Comment by NayamAmarshe** [comment]
It's just how the Real-ESRGAN algorithm works. The color profile changes and also the original image. I can't really fix the algorithm all on my own sadly.

> One more thing is some images are only processed to 1.5x to 2x bigger while others are 3x to 4.5x would be nice to have selectable sizes we could chose from to have the images processed to like 2x to 4.5x bigger.

This comes down to Real-ESRGAN again. All the images are scaled to 4x. Other modes are not possible because the algorithm gives unexpected results, so 4x is our only option for now.

**Comment by aaronliu0130** [comment]
Hey, this project is very good but I'd just like you to know that you can close issues as not planned.

**Comment by DJboutit** [comment]
Would it be possible to get a updated copy of Real-ESRGAN algorithm then add the new version of it to the software??

**Comment by NayamAmarshe** [comment]
> Would it be possible to get a updated copy of Real-ESRGAN algorithm then add the new version of it to the software??

It's possible but only if Real-ESRGAN is updated. Afaik, the original developers haven't updated it in months.
