### ISSUE TITLE
GPU is high on pc but Invalid GPU Device

### ISSUE THREAD

**Issue by Samanthaisthebest** [upscayl/upscayl#922]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

 like i mentioned, my GPU is high enough to work with the program, but it keeps giving errors

### To Reproduce

Help

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

Windows 10 Version 22H2

### GPU Name

Intel(R) Pentium(R) CPU G645 @ 2.90GHz   2.90 GHz

### Expected Behavior

It should've upscaled my image

### Screenshots

![Schermafbeelding 2024-07-25 114836](https://github.com/user-attachments/assets/61a97f9d-33be-4f7b-bf10-e42d3ba74bc5)

### Logs

```sh
vkCreateInstance failed -9
🚨 Error: Invalid GPU Device
```

**Comment by aaronliu0130** [comment]
> Yes, unfortunately. NCNN Vulkan requires a Vulkan-compatible GPU. Upscayl won't work with most iGPUs or CPUs.

Especially not a Pentium. A workaround exists for Windows and Linux in #580.

> Make sure to read [the FAQ](https://github.com/upscayl/upscayl#-faq) first to avoid getting rickrolled.

> If the name is something like "Intel Core", "Intel Graphics" or "AMD Vega" and you can't Upscayl images, [STOP and read the 3rd point in the FAQ](https://github.com/upscayl/upscayl?tab=readme-ov-file#-faq).

![compulsory rickrolls are issued for duplicates of issues and the FAQ and normies who use intelgrated GPUs](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
