### ISSUE TITLE
The GPU NVIDIA Geforce GT730 seams not to work 

### ISSUE THREAD

**Issue by jean-loup84** [upscayl/upscayl#924]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

The GPU NVIDIA Geforce GT730 seams not to work 

### Screenshots

![image](https://github.com/user-attachments/assets/e13f16da-12ec-4437-9c41-914afb949d61)

**Comment by aaronliu0130** [comment]
See Dosu's advice. If you want to make further inquiries, follow the bug report template.
