### ISSUE TITLE
[BUG] UTF-8 / Umlaut problem

### ISSUE THREAD

**Issue by tomybyte** [upscayl/upscayl#925]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

Upscayl can't save files with UTF-8 / Umlaut in filename

### To Reproduce

rename your File in name below and press Upscayl button
1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

Windows 11 Pro 21H2

### GPU Name

Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz 

### Logs

```sh
🎒 BACKEND REPORTED:  🚨 Error: Couldn't write the image C:\_Privat\Familie\Fotos Berlin\Gro�er J�denhof\Rundblick 10 1912 Berlin, Gro�er J�denhof N� 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdek�pfe am Haus Nr. 5 Gesch�ft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org_upscayl_2x_realesrgan-x4plus.jpg
```

**Comment by NayamAmarshe** [comment]
I'll take a look at this. Thank you for reporting.

**Comment by abhishek-gaonkar** [comment]
@tomybyte @NayamAmarshe 
I just tested this on my machine. It is working fine.
App Version: 2.11.5
---------------OS Details--------------
Edition             Windows 11 Pro
Version	        23H2
Installed on	‎5/‎14/‎2023
OS build	        22631.4037
Experience	Windows Feature Experience Pack 1000.22700.1027.0
----------------------------------------
GPU: Nvidia GeForce 1660Ti

Steps followed:
- To a random image renamed it to: 1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg
- Ran Upscayl by choosing this file.
- Received output with same filename as well (Attached here)
![1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr  5 Geschäft Roll   Arbeitsfuhrwerke von A  Walther, stadtbild-deutschland org jpg](https://github.com/user-attachments/assets/b9fa2c01-60e9-4c83-aa02-73470f0e9fba)
![1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr  5 Geschäft Roll   Arbeitsfuhrwerke von A  Walther, stadtbild-deutschland org jpg_upscayl_5x_realesrgan-x4plus](https://github.com/user-attachments/assets/050527f0-3fe4-4727-abd0-90af53cbe746)

Screenshot from App:

![issue_not_found](https://github.com/user-attachments/assets/58dfd61e-668d-42d8-8027-2bcef57e48a8)

-------------------------LOGS BELOW----------------------------
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\Admin\Downloads\1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\Admin\Downloads\1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg.jpg
🖼 Selected Image Path:  C:\Users\Admin\Downloads\1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg.jpg
📁 Selected Image Directory:  C:\Users\Admin\Downloads
🖼 imagePath:  C:\Users\Admin\Downloads\1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"C:\\Users\\Admin\\Downloads","fileNameWithExt":"1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg.jpg","outputDir":"C:\\Users\\Admin\\Downloads","outFile":"C:\\Users\\Admin\\Downloads\\1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg_upscayl_5x_realesrgan-x4plus.png","fileName":"1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg","scale":"5","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Admin\Downloads\1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg.jpg,-o,C:\Users\Admin\Downloads\1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg_upscayl_5x_realesrgan-x4plus.png,-s,5,-m,D:\upscayl-2.11.5-win\resources\models,-n,realesrgan-x4plus,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"D:\\upscayl-2.11.5-win\\resources\\bin\\upscayl-bin","args":["D:\\upscayl-2.11.5-win\\resources\\bin\\upscayl-bin","-i","C:\\Users\\Admin\\Downloads\\1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg.jpg","-o","C:\\Users\\Admin\\Downloads\\1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg_upscayl_5x_realesrgan-x4plus.png","-s","5","-m","D:\\upscayl-2.11.5-win\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  [0 Intel(R) UHD Graphics 630]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) UHD Graphics 630]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) UHD Graphics 630]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) UHD Graphics 630]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 NVIDIA GeForce GTX 1660 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[1 NVIDIA GeForce GTX 1660 Ti]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 NVIDIA GeForce GTX 1660 Ti]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 NVIDIA GeForce GTX 1660 Ti]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 Intel(R) UHD Graphics 630]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) UHD Graphics 630]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) UHD Graphics 630]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) UHD Graphics 630]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 NVIDIA GeForce GTX 1660 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[1 NVIDIA GeForce GTX 1660 Ti]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 NVIDIA GeForce GTX 1660 Ti]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 NVIDIA GeForce GTX 1660 Ti]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🎒 BACKEND REPORTED:  50.00%

🚧 UPSCAYL_PROGRESS:  50.00%

🎒 BACKEND REPORTED:  🏞️ Resizing image according to output scale

🚧 UPSCAYL_PROGRESS:  🏞️ Resizing image according to output scale

🎒 BACKEND REPORTED:  🏞️ Resized image from 194x259 to 970x1295

🚧 UPSCAYL_PROGRESS:  🏞️ Resized image from 194x259 to 970x1295

🎒 BACKEND REPORTED:  100.00

🙌 Upscayled Successfully!

🚧 UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  C:\Users\Admin\Downloads\1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg_upscayl_5x_realesrgan-x4plus.png
💯 UPSCAYL_DONE:  C:\Users\Admin\Downloads\1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg_upscayl_5x_realesrgan-x4plus.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
----------------------=============================---------------------------

**Comment by NayamAmarshe** [comment]
Thanks for testing! It seems that it's not an issue then.

**Comment by abhishek-gaonkar** [comment]
Yeah.. I also used a few other systems and there were no issues amongst them either. Something else might be creating issues for tomybyte.

**Comment by tomybyte** [comment]
It seems as if the error cannot be copied and pasted. Apparently he is interested in the umlaut names of the files. The problem does not occur with every Umlaut file. Unfortunately, the error cannot be reproduced by packing the affected file into a ZIP. So please close.
Here my Log from Today. What's interesting is that the umlaut error isn't shown at every point in the log!
`🚧 UPSCAYL_PROGRESS:  🏞️ Resized image from 1512x1972 to 1512x1972

🎒 BACKEND REPORTED:  🚨 Error: Couldn't write the image C:\_Privat\Familie\Fotos Berlin\Gro�er J�denhof\Rundblick 10 1912 Berlin, Gro�er J�denhof N� 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdek�pfe am Haus Nr. 5 Gesch�ft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org_upscayl_1x_realesrgan-x4plus.jpg

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  🚨 Error: Couldn't write the image C:\_Privat\Familie\Fotos Berlin\Gro�er J�denhof\Rundblick 10 1912 Berlin, Gro�er J�denhof N� 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdek�pfe am Haus Nr. 5 Gesch�ft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org_upscayl_1x_realesrgan-x4plus.jpg

🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/jpeg","filePath":"D:\\x dvd\\Rundblick 10 1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg","extension":"jpg"}
🖼 Setting image path:  D:\x dvd\Rundblick 10 1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg
🗂 Setting output path:  D:\x dvd
🖼 imagePath:  D:\x dvd\Rundblick 10 1912 Berlin, Großer Jüdenhof N° 2-4, im Hintergrund Turm des Alten Stadthauses, die Pferdeköpfe am Haus Nr. 5 Geschäft Roll & Arbeitsfuhrwerke von A. Walther, stadtbild-deutschland.org.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL`

**Comment by abhishek-gaonkar** [comment]
I don't think so.. I've tried on three windows devices.. worked flawlessly, no issues

**Comment by tomybyte** [comment]
so then please close
