### ISSUE TITLE
[REQUEST] Option for default output folder

### ISSUE THREAD

**Issue by ItzExvirnity** [upscayl/upscayl#926]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

I request an option, that allows you to set the default output folder for image upscayling (yes I know I spelled it wrong, but it's for consistency purposes with the repo name)

### Related Problem(s)

none (yet)

### Alternatives

I couldn't find any other workaround for this. Well, there is always the option to painstakingly set the output folder whenever an image gets imported.

**Comment by aaronliu0130** [comment]
Use this:
![image](https://github.com/user-attachments/assets/4b408d80-beea-4a21-9904-0ba28830e340)
Also, you spelt it correctly.
