### ISSUE TITLE
flatpak warning

### ISSUE THREAD

**Issue by ludberg** [upscayl/upscayl#93]
Using the latest version 1.5.0 I get the following warning regarding upscayl:

`Info: org.freedesktop.Platform//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Applications using this runtime:
   org.upscayl.app
`

Is it something you can address in the next version?

**Comment by NayamAmarshe** [comment]
> Is it something you can address in the next version?

I believe this is an issue with electron-builder, unless I missed something. I updated the packages to the latest version and it would still use 20.08, so I suppose it's something only electron builder can fix.

**Comment by Etaash-mathamsetty** [comment]
> > Is it something you can address in the next version?
> 
> I believe this is an issue with electron-builder, unless I missed something. I updated the packages to the latest version and it would still use 20.08, so I suppose it's something only electron builder can fix.

check the heroic games launcher flatpak, they did it...

**Comment by NayamAmarshe** [comment]
> > > Is it something you can address in the next version?
> > 
> > 
> > I believe this is an issue with electron-builder, unless I missed something. I updated the packages to the latest version and it would still use 20.08, so I suppose it's something only electron builder can fix.
> 
> @NayamAmarshe check the heroic games launcher flatpak, they did it... maybe I can contribute something actually

Thanks for the idea, I'll check it out when I get time :)

**Comment by ludberg** [comment]
I still have the same issue even with 1.5.5, but maybe the closing of this issue doesn't mean it's fixed?

**Comment by Etaash-mathamsetty** [comment]
> I still have the same issue even with 1.5.5, but maybe the closing of this issue doesn't mean it's fixed?

I made another issue that's currently open, they are working on updating the flatpak runtime
