### ISSUE TITLE
Support for AuraSR upscaling model.

### ISSUE THREAD

**Issue by Leroy-X** [upscayl/upscayl#931]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

This looks great, and I'm looking forward to using it in upscayl. Thank you very much!

https://huggingface.co/fal/AuraSR
https://github.com/fal-ai/aura-sr

**Comment by jurassicjordan** [comment]
this would be perfect for upscayl. if implemented please also implement into upscayl-ncnn cli version

**Comment by NayamAmarshe** [comment]
Not possible. This is a totally different algorithm with higher hardware requirements.

Besides, Real-ESRGAN offers better quality as you can see in the results below:

**ORIGINAL:**
![image-4](https://github.com/user-attachments/assets/8b7dc02a-bcdb-4995-ac51-77bb7059e123)

**UPSCAYL:**
![image-4-upscayl_x4 (1)](https://github.com/user-attachments/assets/f93d4910-9b9b-4201-a2f0-433e2dbcf251)

**AURA SR:**
![image (1) (1)](https://github.com/user-attachments/assets/4914284a-a694-4a3d-a2e7-02aff1e8aa11)
