### ISSUE TITLE
Since I upscaled one of my own photos from my HD all of my1,000,000 photos and also on the sites that I used  to download the appear like AI to my eyes. Is it from Upskayl or is universal law for legal rights of Photographers? Because I also saw the same thing in manty PCs of other people

### ISSUE THREAD

**Issue by NickPelo** [upscayl/upscayl#934]
Since I upscaled one of my own photos from my HD all of my1,000,000 photos and also on the sites that I used  to download the appear like AI to my eyes. Is it from Upskayl or is universal law for legal rights of Photographers? Because I also saw the same thing in manty PCs of other people

_Originally posted by @NickPelo in https://github.com/upscayl/custom-models/issues/15#issuecomment-2275577216_

**Comment by NayamAmarshe** [comment]
You might have a virus or something, that's causing the issue, and it definitely isn't from Upscayl.
