### ISSUE TITLE
GPU error or copy error

### ISSUE THREAD

**Issue by hasan91zh** [upscayl/upscayl#936]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

I can't upscayl the file

### Screenshots

![Screenshot (7)](https://github.com/user-attachments/assets/b6fcc8f2-2704-467f-abe4-b02fac6349e8)

**Comment by aaronliu0130** [comment]
Please follow the bug reporting template.
