### ISSUE TITLE
batch upscale

### ISSUE THREAD

**Issue by kalpeshjadav** [upscayl/upscayl#937]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

i select batch upscale and later select my folder but file dont show.

**Comment by kalpeshjadav** [comment]
> Hey @kalpeshjadav! 👋 I'm here to help you with any bugs, questions, or contributions you have while waiting for a human maintainer. Let's tackle this together!
> 
> The files might not show up when you select batch upscale and choose your folder because the application only recognizes certain file types. Specifically, the allowed file types are "png", "jpg", "jpeg", and "webp" in both lowercase and uppercase formats. Ensure that the files in the selected folder are of these types.
> 
> ```tsx
> const allowedFileTypes = ["png", "jpg", "jpeg", "webp", "PNG", "JPG", "JPEG", "WEBP"];
> ```
> 
> Additionally, make sure that the folder path is correctly decoded and accessible, as the application uses `decodeURIComponent` to handle the folder path.
> 
> ```ts
> let inputDir = decodeURIComponent(payload.batchFolderPath);
> ```
> 
> If the folder path contains any special characters, ensure they are properly encoded to avoid issues with path recognition [[1]](https://github.com/upscayl/upscayl/blob/main/renderer/pages/index.tsx)[[2]](https://github.com/upscayl/upscayl/blob/main/electron/commands/batch-upscayl.ts)[[3]](https://github.com/upscayl/upscayl/blob/main/electron/commands/select-file.ts).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

i can do this things but all are correct but problem still there

**Comment by kalpeshjadav** [comment]
I can't understand this because my background is not coding

**Comment by NayamAmarshe** [comment]
Please attach logs. Without logs, there's no possibility of helping.

**Comment by aaronliu0130** [comment]
The bug reporting template has a troubleshooting checklist. Please use that instead.
