### ISSUE TITLE
Downscayl AI?

### ISSUE THREAD

**Issue by KommuSoft** [upscayl/upscayl#940]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Since we have model(s) for upscayling, I expect we can also do the reverse: downscayling in the most data-preserving manner. In other words if you have a picture of say 1920x1080, convert it to a picture of 480x270. Now one can do that with a classical resize algorithm, but I expect that just like upscayling through a statistical model is better than with traditional resize techniques, we can make it so that the most details are preserved. The picture does not per se have to be of the best quality in the resized form, given it can be generated back to almost the original.

It looks like a promising idea to reduce the size images and videos take.

**Comment by tocotronaut** [comment]
i Think Downscaling is quite normal.
is often used in Gaming Context as SSAA (Super Sampling Anti Aliasing) (google that)
e.g.: Hardcore gamers render their games in 4k and downscale it to 1080p to preserve more details.

and even in picture context downscaling ist used often.
Every Time your image has an Higher Resolution as your monitor and you click on "Full Screen" it downscles automatically.

deleting details from pictures before that seems to be the wrong way - at least for me...

**Comment by tocotronaut** [comment]
Maybe... 
it could be nice to set an resolution e.g. 4k and Upscayle processes all Pictures in an Folder to this Resolution. Downscaling larger ones and upscayling the tiny pictures.

**Comment by aaronliu0130** [comment]
What would downscayling even mean? It's impossible to preserve the data lost when downsizing.

**Comment by aaronliu0130** [comment]
@tocotronaut There's a custom resolution setting in the settings tab.

**Comment by KommuSoft** [comment]
@aaronliu0130 : sure, there is always data loss, but you try to minimize the data loss. A bit like an encoder-decoder model, where you (deliberately) downscale data to the form that contains still the most data to try to generate the data than back like the original. One can resize, but then some details might get removed in the downscaling process that could have been retained in an image with a slightly different downscaling technique.

**Comment by aaronliu0130** [comment]
The only way to do that would be copying the removed pixels to an invisible part of the image. That requires a different image format that other programs will not know how to use, which isn't really within our purview. Why not just keep the larger image?

**Comment by KommuSoft** [comment]
Well the main use case is to reduce disk space. That would mean that for example a movie or image is taken, reduced (which can indeed be done in the classical way), and then when needed upscayled again. The question is if we can do it better than thus classical downscaling.

**Comment by NayamAmarshe** [comment]
> Well the main use case is to reduce disk space. That would mean that for example a movie or image is taken, reduced (which can indeed be done in the classical way), and then when needed upscayled again. The question is if we can do it better than thus classical downscaling.

You can use the 1x scale and then downscale further as required, or just downscale the 4x image.

What you're essentially asking for is compression. I have another app called Comepress that does this. You can give it a try.

**Comment by tocotronaut** [comment]
Ai Compression is Possible.

You can identify items in Your Photo and mask them for replacement. So Ai Photos can be much smaller as normal Photos.

eg. The Moon - you can identify the moon in a photo and reduce it to an "white circle with description moon" - if you open the photo the moon will be "on the fly" replaced with an high definition photo of the moon.

i used Moon as example, because Samsung already uses this for moon Pictures!
https://www.theverge.com/2023/3/13/23637401/samsung-fake-moon-photos-ai-galaxy-s21-s23-ultra

The Question is - will it be "your" photo if you replace objects like houses, trees or pets this way.

**Comment by aaronliu0130** [comment]
@tocotronaut That's not compression. That's replacing the ship of Theseus with another contemporary ship altogether.

**Comment by Drael64** [comment]
> The only way to do that would be copying the removed pixels to an invisible part of the image. That requires a different image format that other programs will not know how to use, which isn't really within our purview. Why not just keep the larger image?

One use case is to render in a higher resolution than your screen can display, and then use AI to downscale in order to get a better level of detail. IMO, better than the opposite approach which tends to produce artefacts.

**Comment by Drael64** [comment]
> It's simply not how AI works. Even if possible, we will have to figure out a ton of math equations.

There are papers on AI downscaling. At least when I searched. I haven't looked into it deeply, but it looks like it is a thing.

**Comment by aaronliu0130** [comment]
I'm fairly sure you're looking at papers to refine meteorological data, not images.
For anyone interested, https://stackoverflow.com/questions/384991/what-is-the-best-image-downscaling-algorithm-quality-wise lists several image downsampling algorithms.

**Comment by Drael64** [comment]
Well I'm not sure if this is actually improving the quality of the downscaled image, or merely focused on reconstruction (it could be both), but there is stuff like this:

https://arxiv.org/abs/2211.10643

**Comment by KommuSoft** [comment]
Well that ten settles the matter I guess, using HCFlow or another AI model to retain as much detail as possible when downscaling, and upscayl to upscale it back.
