### ISSUE TITLE
[VULKAN] vkQueueSubmit failed -4

### ISSUE THREAD

**Issue by spencerpickett** [upscayl/upscayl#943]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

Hi,

I am hoping someone can help me out, because I have spent several hours trouble shooting this issue with no success.

I have gone through the setup guide, FAQ and read similar articles that report this topic (e.g. https://github.com/upscayl/upscayl/issues/362) - but no success.

My Windows 10 PC has an Nvidia 660 GTX (and it is supported based on the documentation from what I can see).  When I start Upscayl I can see that the GPU ID is blank, I have tried manually setting this to 0, 1, 2 but each time it generates a black screen output.

I downloaded the latest NVIDIA graphics drivers.  Also, I set up "performance mode" for Upscayl.  Rebooted, etc. However, I still see the same problem.

If anyone can help that would be appreciated.  

Thanks,

Spencer

### To Reproduce

Just try and upscale any image, results in black screen (regardless of model selected).

### Upscayl Version (or commit hash)

2.11.5

### Platform

Linux

### OS Version

Windows 10

### GPU Name

Nvidia GTX 660

### Expected Behavior

It upscales :)

### Logs

```sh
🎯 GET_MODELS_LIST:  
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  0
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  0
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  0
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  O:\My Drive\personal\Holiday\photo album\13 - katey kobe beach 4.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  O:\My Drive\personal\Holiday\photo album\13 - katey kobe beach 4.jpg
🖼 Selected Image Path:  O:\My Drive\personal\Holiday\photo album\13 - katey kobe beach 4.jpg
📁 Selected Image Directory:  O:\My Drive\personal\Holiday\photo album
🖼 imagePath:  O:\My Drive\personal\Holiday\photo album\13 - katey kobe beach 4.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":"0","saveImageAs":"png","inputDir":"O:\\My Drive\\personal\\Holiday\\photo album","fileNameWithExt":"13 - katey kobe beach 4.jpg","outputDir":"O:\\My Drive\\personal\\Holiday\\photo album","outFile":"O:\\My Drive\\personal\\Holiday\\photo album\\13 - katey kobe beach 4_upscayl_2x_realesrgan-x4plus.png","fileName":"13 - katey kobe beach 4","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,O:\My Drive\personal\Holiday\photo album\13 - katey kobe beach 4.jpg,-o,O:\My Drive\personal\Holiday\photo album\13 - katey kobe beach 4_upscayl_2x_realesrgan-x4plus.png,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-g,0,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","O:\\My Drive\\personal\\Holiday\\photo album\\13 - katey kobe beach 4.jpg","-o","O:\\My Drive\\personal\\Holiday\\photo album\\13 - katey kobe beach 4_upscayl_2x_realesrgan-x4plus.png","-s","2","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-g","0","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  [0 GeForce GTX 660]  queueC=0[16]  queueG=0[16]  queueT=1[1]
[0 GeForce GTX 660]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 GeForce GTX 660]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 GeForce GTX 660]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 GeForce GTX 660]  queueC=0[16]  queueG=0[16]  queueT=1[1]
[0 GeForce GTX 660]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 GeForce GTX 660]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 GeForce GTX 660]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  0
🎒 BACKEND REPORTED:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🎒 BACKEND REPORTED:  vkWaitForFences failed -4

🚧 UPSCAYL_PROGRESS:  vkWaitForFences failed -4

🎒 BACKEND REPORTED:  0.08%

🚧 UPSCAYL_PROGRESS:  0.08%

🎒 BACKEND REPORTED:  vkQueueSubmit failed -4
0.17%

🚧 UPSCAYL_PROGRESS:  vkQueueSubmit failed -4
0.17%

🎒 BACKEND REPORTED:  0.25%

🚧 UPSCAYL_PROGRESS:  0.25%

🎒 BACKEND REPORTED:  0.33%

🚧 UPSCAYL_PROGRESS:  0.33%

🎒 BACKEND REPORTED:  0.42%

🚧 UPSCAYL_PROGRESS:  0.42%

🎒 BACKEND REPORTED:  0.50%

... 

🚧 UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  O:\My Drive\personal\Holiday\photo album\13 - katey kobe beach 4_upscayl_2x_realesrgan-x4plus.png
💯 UPSCAYL_DONE:  O:\My Drive\personal\Holiday\photo album\13 - katey kobe beach 4_upscayl_2x_realesrgan-x4plus.png
```

**Comment by spencerpickett** [comment]
> Hello, @spencerpickett! I'm here to help you with any issues you encounter. If you need assistance with bug resolution, have questions, or want to become a contributor, feel free to reach out.
> 
> The issue of Upscayl generating a black image as output on your Windows 10 PC with an Nvidia GTX 660 GPU is likely due to the requirement for a Vulkan-compatible GPU. The GTX 660 is an older GPU and may not fully support the required Vulkan features needed by Upscayl.
> 
> To verify this, you can use the VulkanCapsViewer tool to check for Vulkan support on your GPU. If VulkanCapsViewer reports that your GPU does not support the necessary Vulkan features, this would explain why Upscayl is generating a black image as output.
> 
> Additionally, you can manually specify a Vulkan-enabled GPU to be used for upscaling images by setting the GPU ID in Upscayl. Follow these steps to find and set the GPU ID:
> 
>     1. Open Upscayl and attempt to upscale an image.
> 
>     2. Go to the Settings tab and scroll down to the logs area.
> 
>     3. Identify the GPU IDs available to you from the logs. For example, 1 might be Nvidia, 2 might be llvmpipe, and 0 might be AMD Radeon.
> 
>     4. Enter the appropriate GPU ID in the 'GPU ID' input box in the Settings tab.
> 
> 
> If setting the GPU ID does not resolve the issue, consider upgrading to a more recent GPU that is known to be compatible with Vulkan and Upscayl [[1]](https://github.com/upscayl/upscayl/blob/main/docs/Troubleshooting.md)[[2]](https://github.com/upscayl/upscayl/blob/main/docs/Guide.md)[[3]](https://github.com/upscayl/upscayl/blob/main/docs/Compatibility-List.md).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

As per my original message, I have already tried this and it did not work.  The log shows my GPU is "0", I tried this and same result black screen.  I also tried options 1, 2 and that did not work either.

**Comment by ghyujkilop** [comment]
Gosh thought it was me lol

**Comment by akrisha20** [comment]
Then it seems a general issue for a subset of the images.

**Comment by spencerpickett** [comment]
Ok after resetting everything (i.e uninstall, install, etc) I have been able to get the system working.  Technically I havenot changed anything on my system, just uninstall and install again.  NOTE: only one model works, which is "FAST REAL-ESGRAN" - all the other models do not work.  I also tried downloading additioanl AI models from the Upscayl website, and the vast majority of them do not work. 

My conclusion (which may be completely wrong) is that old NVIDIA GFX cards (although supported) do not fully work as expected.

Hope that helps...

**Comment by akrisha20** [comment]
I tried to uninstall and install everything, but it still shows a black image for certain pictures, and works for others.

**Comment by ghyujkilop** [comment]
Another sidenote to my comment, is it only happened when using Remacri. If that's helpful.

**Comment by spencerpickett** [comment]
> I also have this issue with multiple pictures with original resolution 6120x8160. Upscayl says it is done, but shows a black screen. When upscaling pictures with resolution 4000x3000, I don't have this issue. So it might be due to the high resolution?
> 
> I am running an NVIDIA RTX A1000.
> 
> @spencerpickett can you confirm that your original pictures are high resolution as well?

I just ran a couple of tests upscaling a low resolution image 1500x1500:

1) using 4x upscaling using FAST REAL-ESGRAN = works (as it did before)
2) using 1x REMACRI (did not work before) = partially works (half the screen is blank)

So it appears that a lower resolution image seems to produce better results (i.e. REMACRI did not work previously).

If I then proceed to select a larger image e.g. 3000x4000 then this model (and other models) do not work.  So 100% on my system Upscayl will "not" process high resolution images.  So that is my problem.

**Comment by akrisha20** [comment]
I think my issue is different, as I don't see the "vkQueueSubmit failed -4" in my log files.
But the end result is the same: a black screen.

Logs:
`⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"realesrgan-x4fast"}
⚙️ Getting gpuId from localStorage:  0
🔀 Setting model to 
🔀 Setting model to realesrgan-x4fast
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/jpeg","filePath":"C:\\Users\\robin\\Downloads\\upscayl\\20240729_154844.jpg","extension":"jpg"}
🖼 Setting image path:  C:\Users\robin\Downloads\upscayl\20240729_154844.jpg
🗂 Setting output path:  C:\Users\robin\Downloads\upscayl
🖼 imagePath:  C:\Users\robin\Downloads\upscayl\20240729_154844.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4fast","gpuId":"0","saveImageAs":"png","inputDir":"C:\\Users\\robin\\Downloads\\upscayl","fileNameWithExt":"20240729_154844.jpg","outputDir":"C:\\Users\\robin\\Downloads\\upscayl","outFile":"C:\\Users\\robin\\Downloads\\upscayl\\20240729_154844_upscayl_2x_realesrgan-x4fast.png","fileName":"20240729_154844","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\robin\Downloads\upscayl\20240729_154844.jpg,-o,C:\Users\robin\Downloads\upscayl\20240729_154844_upscayl_2x_realesrgan-x4fast.png,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4fast,-g,0,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\robin\\Downloads\\upscayl\\20240729_154844.jpg","-o","C:\\Users\\robin\\Downloads\\upscayl\\20240729_154844_upscayl_2x_realesrgan-x4fast.png","-s","2","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4fast","-g","0","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  [0 NVIDIA RTX A1000 Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA RTX A1000 Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA RTX A1000 Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA RTX A1000 Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA RTX A1000 Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA RTX A1000 Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA RTX A1000 Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA RTX A1000 Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  0,00%

🚧 UPSCAYL_PROGRESS:  0,00%

🎒 BACKEND REPORTED:  0,08%

🚧 UPSCAYL_PROGRESS:  0,08%

🎒 BACKEND REPORTED:  0,16%

🚧 UPSCAYL_PROGRESS:  0,16%

🎒 BACKEND REPORTED:  0,24%

🚧 UPSCAYL_PROGRESS:  0,24%

🎒 BACKEND REPORTED:  0,31%

🚧 UPSCAYL_PROGRESS:  0,31%

🎒 BACKEND REPORTED:  0,39%

🚧 UPSCAYL_PROGRESS:  0,39%

🎒 BACKEND REPORTED:  0,47%

🚧 UPSCAYL_PROGRESS:  0,47%

🎒 BACKEND REPORTED:  0,55%

🚧 UPSCAYL_PROGRESS:  0,55%

🎒 BACKEND REPORTED:  0,63%

🚧 UPSCAYL_PROGRESS:  0,63%

🎒 BACKEND REPORTED:  0,71%

🚧 UPSCAYL_PROGRESS:  0,71%

🎒 BACKEND REPORTED:  0,79%

🚧 UPSCAYL_PROGRESS:  0,79%

🎒 BACKEND REPORTED:  0,87%

🚧 UPSCAYL_PROGRESS:  0,87%

🎒 BACKEND REPORTED:  0,94%

🚧 UPSCAYL_PROGRESS:  0,94%

🎒 BACKEND REPORTED:  1,02%

🚧 UPSCAYL_PROGRESS:  1,02%

🎒 BACKEND REPORTED:  1,10%

🚧 UPSCAYL_PROGRESS:  1,10%

🎒 BACKEND REPORTED:  1,18%

🚧 UPSCAYL_PROGRESS:  1,18%

🎒 BACKEND REPORTED:  1,26%

🚧 UPSCAYL_PROGRESS:  1,26%

(...)

🚧 UPSCAYL_PROGRESS:  93,39%

🎒 BACKEND REPORTED:  93,47%

🚧 UPSCAYL_PROGRESS:  93,47%

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  C:\Users\robin\Downloads\upscayl\20240729_154844_upscayl_2x_realesrgan-x4fast.png
💯 UPSCAYL_DONE:  C:\Users\robin\Downloads\upscayl\20240729_154844_upscayl_2x_realesrgan-x4fast.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"realesrgan-x4fast"}
⚙️ Getting gpuId from localStorage:  0`
