### ISSUE TITLE
How to use upscale on cloud

### ISSUE THREAD

**Issue by onawia** [upscayl/upscayl#954]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Hi
On the website I saw that  we can use this image upscaling on cloud but there is no option to upload images. On the computer I dont think it will work as I have not strong graphic card.

**Comment by aaronliu0130** [comment]
Sadly, it's not here yet.
