### ISSUE TITLE
Black output of my own converted model

### ISSUE THREAD

**Issue by Kongsea** [upscayl/upscayl#960]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

When using my own model converted by chaiNNer as [Model Conversion Guide](https://github.com/upscayl/upscayl/blob/356bb5cf95c255914c66ea6d822473f576b0c844/docs/Model-Conversion-Guide.md) described, the upscayled image was black and the original image can be displayed correctly...

The software worked very well using the official models, such as Real-ESRGAN.

### To Reproduce

Convert my own model and used in Upscayl like mentioned in [README](https://github.com/upscayl/upscayl/blob/356bb5cf95c255914c66ea6d822473f576b0c844/docs/Model-Conversion-Guide.md).

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

Windows 10

### GPU Name

NVIDIA 4090D

### Expected Behavior

It seems the model did not work at all.
The output using our converted model will be like that using the official models.

### Screenshots

![image](https://github.com/user-attachments/assets/db0f8685-424c-49e9-b717-05f875b5f52a)

![image](https://github.com/user-attachments/assets/c6ab0b2e-b3c9-4a8c-ba66-78d56e9db7c4)

![image](https://github.com/user-attachments/assets/f9695f78-f91c-4192-b3d0-3941adafd4f6)
 

### Logs

```sh
?? GET_MODELS_LIST:  C:\models
?? BACKEND REPORTED:  ?? Updating Custom Models Folder Path:  C:\models
?? BACKEND REPORTED:  ?? Custom Models Folder Path:  C:\models
?? Getting saveImageAs from localStorage:  png
?? Getting model from localStorage:  {"label":"test","value":"test"}
?? Setting gpuId to empty string
?? Setting model to 
?? Setting model to test
?? BACKEND REPORTED:  ?? Detected Custom Models:  test
?? CUSTOM_MODEL_FILES_LIST:  test
?? Getting saveImageAs from localStorage:  png
?? Getting model from localStorage:  {"label":"test","value":"test"}
?? Setting gpuId to empty string
?? BACKEND REPORTED:  ?? Updating Custom Models Folder Path:  C:\models
?? BACKEND REPORTED:  ?? Detected Custom Models:  test
?? CUSTOM_MODEL_FILES_LIST:  test
?? BACKEND REPORTED:  ?? Custom Folder Path:  C:\models
?? BACKEND REPORTED:  ?? Updating Custom Models Folder Path:  C:\models
?? BACKEND REPORTED:  ?? Custom Models Folder Path:  C:\models
?? BACKEND REPORTED:  ?? Detected Custom Models:  test
?? CUSTOM_MODEL_FILES_LIST:  test
?? Getting saveImageAs from localStorage:  png
?? Getting model from localStorage:  {"label":"test","value":"test"}
?? Setting gpuId to empty string
?? Setting model to 
?? Setting model to test
?? Resetting image paths
?? BACKEND REPORTED:  ??? Updating Image Path:  E:\IECT\imgtest_upscayl_2x_realesrgan-x4plus-anime.png
?? BACKEND REPORTED:  ?? Selected File Path:  E:\IECT\imgtest_upscayl_2x_realesrgan-x4plus-anime.png
?? Selected Image Path:  E:\IECT\imgtest_upscayl_2x_realesrgan-x4plus-anime.png
?? Selected Image Directory:  E:\IECT
?? imagePath:  E:\IECT\imgtest_upscayl_2x_realesrgan-x4plus-anime.png
?? Extension:  png
?? BACKEND REPORTED:  ?? Updating Folder Path:  C:\Users\A\Desktop
?? BACKEND REPORTED:  ?? Selected Folder Path:  C:\Users\A\Desktop
?? Setting Output Path:  C:\Users\A\Desktop
?? Resetting Upscaled Image Path
?? UPSCAYL
?? BACKEND REPORTED:  ? Upscayl Variables:  {"model":"test","gpuId":null,"saveImageAs":"png","inputDir":"E:\\IECT","fileNameWithExt":"imgtest_upscayl_2x_realesrgan-x4plus-anime.png","outputDir":"C:\\Users\\A\\Desktop","outFile":"C:\\Users\\A\\Desktop\\imgtest_upscayl_2x_realesrgan-x4plus-anime_upscayl_2x_test.png","fileName":"imgtest_upscayl_2x_realesrgan-x4plus-anime","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
?? BACKEND REPORTED:  ?? Upscayl Command:  -i,E:\IECT\imgtest_upscayl_2x_realesrgan-x4plus-anime.png,-o,C:\Users\A\Desktop\imgtest_upscayl_2x_realesrgan-x4plus-anime_upscayl_2x_test.png,-s,2,-m,C:\models,-n,test,-f,png,-c,0
?? BACKEND REPORTED:  ?? Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","E:\\IECT\\imgtest_upscayl_2x_realesrgan-x4plus-anime.png","-o","C:\\Users\\A\\Desktop\\imgtest_upscayl_2x_realesrgan-x4plus-anime_upscayl_2x_test.png","-s","2","-m","C:\\models","-n","test","-f","png","-c","0"]}
?? BACKEND REPORTED:  ?? Updating Stopped:  false
?? BACKEND REPORTED:  [0 NVIDIA GeForce RTX 4090 D]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4090 D]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4090 D]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4090 D]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 Intel(R) UHD Graphics 770]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) UHD Graphics 770]  bugsbn1=0  bugbilz=25  bugcopc=0  bugihfa=0
[1 Intel(R) UHD Graphics 770]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) UHD Graphics 770]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

?? UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 4090 D]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4090 D]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4090 D]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4090 D]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 Intel(R) UHD Graphics 770]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) UHD Graphics 770]  bugsbn1=0  bugbilz=25  bugcopc=0  bugihfa=0
[1 Intel(R) UHD Graphics 770]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) UHD Graphics 770]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

?? BACKEND REPORTED:  ?? Done upscaling
upscaledImagePath:  C:\Users\A\Desktop\imgtest_upscayl_2x_realesrgan-x4plus-anime_upscayl_2x_test.png
?? UPSCAYL_DONE:  C:\Users\A\Desktop\imgtest_upscayl_2x_realesrgan-x4plus-anime_upscayl_2x_test.png
?? Getting saveImageAs from localStorage:  png
?? Getting model from localStorage:  {"label":"test","value":"test"}
?? Setting gpuId to empty string
```

**Comment by aaronliu0130** [comment]
DId you use the specified older version of chaiNNer?

**Comment by Kongsea** [comment]
> DId you use the specified older version of chaiNNer?

I used chaiNNer version 0.24.0.

**Comment by aaronliu0130** [comment]
Okay, I forgot about the docs site. https://github.com/upscayl/upscayl/wiki/Model-Conversion-Guide is a bit more updated, and I'll see if the docs can use the wiki.

**Comment by Kongsea** [comment]
Look forward to your response.

**Comment by Kongsea** [comment]
I found there are many slashes in the .param file of my own model, as:

![image](https://github.com/user-attachments/assets/38515f5c-7ccc-4bc9-a3c8-e28a7e03272c)

However, there are no slashes at all in all official models:

![image](https://github.com/user-attachments/assets/c96972e6-9d68-402f-86ee-596302590f26)

Is this normal or abnormal?

**Comment by Kongsea** [comment]
Besides, the second column name **data** of the model **ultrasharp** has not been changed at all:

![image](https://github.com/user-attachments/assets/348b25c3-a6d7-47bf-bbff-2f3ebeb2049c)

But this model works well too.

**Comment by NayamAmarshe** [comment]
Are you using old chainner version?

**Comment by Kongsea** [comment]
> Are you not using the old chainner version? 0.21?

I do have tried to use the old version. However, the network in China is special and I cannot config it successfully since the old version cannot access the internet through a VPN.
I can send my model to you, if you could do me a favor to convert it.

**Comment by Kongsea** [comment]
I want to mention that the model I used is [BSRGAN](https://github.com/cszn/BSRGAN) since it has better results for my cases, which is slightly different from real-esrgan. I don't know if the error was caused by this.

**Comment by NayamAmarshe** [comment]
> I want to mention that the model I used is [BSRGAN](https://github.com/cszn/BSRGAN) since it has better results for my cases, which is slightly different from real-esrgan. I don't know if the error was caused by this.

BSRGAN is not supported. Only ESRGAN and Real-ESRGAN.

**Comment by Kongsea** [comment]
> > I want to mention that the model I used is [BSRGAN](https://github.com/cszn/BSRGAN) since it has better results for my cases, which is slightly different from real-esrgan. I don't know if the error was caused by this.
> 
> BSRGAN is not supported. Only ESRGAN and Real-ESRGAN.

Real-ESRGAN model cannot be converted and used in Upscayl successfully too, even the official model weight, like in [issue](https://github.com/upscayl/upscayl/issues/969).

**Comment by NayamAmarshe** [comment]
I was having the same issue today and what helped was using v0.21.0.

**Comment by John-ckck** [comment]
I am so sorry how can i fix it, my laptop was not. Only used by me i didn't
know what's going on, i love your site I don't want to unsubscribe.

**Comment by John-ckck** [comment]
I am so sorry how can i fix it, my laptop was not. Only used by me i didn't
know what's going on, i love your site I don't want to unsubscribe.

**Comment by John-ckck** [comment]
I am using windows 7 when i try to open it says, The procedure entry point could not be located in the dynamic link Library Kernel32.dll. I can't fix this problem.

**Comment by Kongsea** [comment]
> I am using windows 7 when i try to open it says, The procedure entry point could not be located in the dynamic link Library Kernel32.dll. I can't fix this problem.

Please open a new issue to describe your situations.

**Comment by Kongsea** [comment]
> I was having the same issue today and what helped was using v0.21.0.

I finally try to installed the same traiNNer version with you.
I found that BSRGAN model can be used, however the output is not correct. The output looks like:
![imgtest_upscayl_2x_BG](https://github.com/user-attachments/assets/d0cdfbbf-742b-4d7f-8e11-b16fcf68118b)
Besides, the scale must be x4 when using Real-ESRGAN. When use the other scales, chaiNNer will raise error like:
![image](https://github.com/user-attachments/assets/c2a6715a-a227-4758-ab52-274469d8950e)
When using different number of features and blocks, errors would be raised too.
![image](https://github.com/user-attachments/assets/9e29d3ed-dbbb-4fc5-a162-3a7749dc544a)
It's very conffusing...
I look forward to more and more architectures and scales been supported.

**Comment by Kongsea** [comment]
BSRGANx4 can generated the correct results.
But the BSRGANx2 model will generate the disordered results as shown in the above image.

**Comment by aaronliu0130** [comment]
x2 models are meant to be used with x2 scale, but Upscayl should be able to handle that...

**Comment by NayamAmarshe** [comment]
> BSRGANx4 can generated the correct results. But the BSRGANx2 model will generate the disordered results as shown in the above image.

Make sure you put x2 in the model name.

**Comment by Kongsea** [comment]
> > BSRGANx4 can generated the correct results. But the BSRGANx2 model will generate the disordered results as shown in the above image.
> 
> Make sure you put x2 in the model name.

I have used a x2 scale model, however, the outputs are the same both for names w/wo x2. (add x2 to the model name after converting to .bin and .param files)
![image](https://github.com/user-attachments/assets/309768af-dea1-48ec-9bce-fa16b1980347)

**Comment by NayamAmarshe** [comment]
Then it's probably something else. Maybe the change in architecture causing it.

**Comment by Kongsea** [comment]
> Then it's probably something else. Maybe the change in architecture causing it.

I don't think so.
As you can see from the output, the output is the same as that used pytorch inference program from the same model and only the  subpart order has been adjusted. So I think it should be caused by the upscayl instead of the model and its archistructure.

**Comment by Kongsea** [comment]
Please dont. The issue has net been fixed.
