### ISSUE TITLE
gpu issue intel hd graphics 4600 testing in old systems

### ISSUE THREAD

**Issue by GeorgiosLos** [upscayl/upscayl#961]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\PC\Desktop\clear\nurse1.png
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\PC\Desktop\clear\nurse1.png
🖼 Selected Image Path:  C:\Users\PC\Desktop\clear\nurse1.png
📁 Selected Image Directory:  C:\Users\PC\Desktop\clear
🖼 imagePath:  C:\Users\PC\Desktop\clear\nurse1.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus-anime","gpuId":null,"saveImageAs":"png","inputDir":"C:\\Users\\PC\\Desktop\\clear","fileNameWithExt":"nurse1.png","outputDir":"C:\\Users\\PC\\Desktop\\clear","outFile":"C:\\Users\\PC\\Desktop\\clear\\nurse1_upscayl_2x_realesrgan-x4plus-anime.png","fileName":"nurse1","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\PC\Desktop\clear\nurse1.png,-o,C:\Users\PC\Desktop\clear\nurse1_upscayl_2x_realesrgan-x4plus-anime.png,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\PC\\Desktop\\clear\\nurse1.png","-o","C:\\Users\\PC\\Desktop\\clear\\nurse1_upscayl_2x_realesrgan-x4plus-anime.png","-s","2","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus-anime","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkCreateInstance failed -9

🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🎒 BACKEND REPORTED:  vkCreateInstance failed -9
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9
🎒 BACKEND REPORTED:  

🚧 UPSCAYL_PROGRESS:  

🎒 BACKEND REPORTED:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\PC\Desktop\clear\nurse1.png
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\PC\Desktop\clear\nurse1.png
🖼 Selected Image Path:  C:\Users\PC\Desktop\clear\nurse1.png
📁 Selected Image Directory:  C:\Users\PC\Desktop\clear
🖼 imagePath:  C:\Users\PC\Desktop\clear\nurse1.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus-anime","gpuId":null,"saveImageAs":"png","inputDir":"C:\\Users\\PC\\Desktop\\clear","fileNameWithExt":"nurse1.png","outputDir":"C:\\Users\\PC\\Desktop\\clear","outFile":"C:\\Users\\PC\\Desktop\\clear\\nurse1_upscayl_2x_realesrgan-x4plus-anime.png","fileName":"nurse1","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\PC\Desktop\clear\nurse1.png,-o,C:\Users\PC\Desktop\clear\nurse1_upscayl_2x_realesrgan-x4plus-anime.png,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\PC\\Desktop\\clear\\nurse1.png","-o","C:\\Users\\PC\\Desktop\\clear\\nurse1_upscayl_2x_realesrgan-x4plus-anime.png","-s","2","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus-anime","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkCreateInstance failed -9

🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🎒 BACKEND REPORTED:  vkCreateInstance failed -9

🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🎒 BACKEND REPORTED:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string

**Comment by aaronliu0130** [comment]
> Yes, unfortunately. NCNN Vulkan requires a Vulkan-compatible GPU. Upscayl won't work with most iGPUs or CPUs.

A workaround exists for Windows and Linux in #580.

> Make sure to read [the FAQ](https://github.com/upscayl/upscayl#-faq) first to avoid getting rickrolled.

> If the name is something like "Intel Core", "Intel Graphics" or "AMD Vega" and you can't Upscayl images, [STOP and read the 3rd point in the FAQ](https://github.com/upscayl/upscayl?tab=readme-ov-file#-faq).

![compulsory rickrolls are issued for duplicates of issues and the FAQ and normies who use intelgrated GPUs](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
