### ISSUE TITLE
nvida report

### ISSUE THREAD

**Issue by GeorgiosLos** [upscayl/upscayl#962]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  E:\clear
🖼 Selected Folder Path:  E:\clear
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  E:\clear
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,E:\clear,-o,E:\clear\upscayl_png_realesrgan-x4plus-anime_4x,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-f,png,-c,0
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🚧 FOLDER_UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 3060]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3060]  bugsbn1=0  bugbilz=92  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3060]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3060]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[1 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=92  bugcopc=0  bugihfa=0
[1 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%
66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%
77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%
88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%
66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%
88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%
66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%
88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%
66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%
66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%
77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.11%
22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  22.22%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  44.44%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.56%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  77.78%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.89%

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🎒 BACKEND REPORTED:  💯 Done upscaling
💯 FOLDER_UPSCAYL_DONE:  E:\clear\upscayl_png_realesrgan-x4plus-anime_4x
📂 OPEN_FOLDER:  E:\clear\upscayl_png_realesrgan-x4plus-anime_4x
🎒 BACKEND REPORTED:  📂 Opening Folder:  E:\clear\upscayl_png_realesrgan-x4plus-anime_4x
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/png","filePath":"C:\\Users\\user\\Desktop\\girl on the beach 2.png","extension":"png"}
🖼 Setting image path:  C:\Users\user\Desktop\girl on the beach 2.png
🗂 Setting output path:  C:\Users\user\Desktop
🖼 imagePath:  C:\Users\user\Desktop\girl on the beach 2.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus-anime","gpuId":null,"saveImageAs":"png","inputDir":"C:\\Users\\user\\Desktop","fileNameWithExt":"girl on the beach 2.png","outputDir":"C:\\Users\\user\\Desktop","outFile":"C:\\Users\\user\\Desktop\\girl on the beach 2_upscayl_4x_realesrgan-x4plus-anime.png","fileName":"girl on the beach 2","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\user\Desktop\girl on the beach 2.png,-o,C:\Users\user\Desktop\girl on the beach 2_upscayl_4x_realesrgan-x4plus-anime.png,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","E:\\clear","-o","E:\\clear\\upscayl_png_realesrgan-x4plus-anime_4x","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus-anime","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  [0 NVIDIA GeForce RTX 3060]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3060]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3060]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3060]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[1 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 3060]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3060]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3060]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3060]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 AMD Radeon(TM) Graphics]  queueC=1[2]  queueG=0[1]  queueT=2[1]
[1 AMD Radeon(TM) Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 AMD Radeon(TM) Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 AMD Radeon(TM) Graphics]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🎒 BACKEND REPORTED:  2.78%

🚧 UPSCAYL_PROGRESS:  2.78%

🎒 BACKEND REPORTED:  5.56%

🚧 UPSCAYL_PROGRESS:  5.56%

🎒 BACKEND REPORTED:  8.33%

🚧 UPSCAYL_PROGRESS:  8.33%

🎒 BACKEND REPORTED:  11.11%

🚧 UPSCAYL_PROGRESS:  11.11%

🎒 BACKEND REPORTED:  13.89%

🚧 UPSCAYL_PROGRESS:  13.89%

🎒 BACKEND REPORTED:  16.67%

🚧 UPSCAYL_PROGRESS:  16.67%

🎒 BACKEND REPORTED:  19.44%

🚧 UPSCAYL_PROGRESS:  19.44%

🎒 BACKEND REPORTED:  22.22%

🚧 UPSCAYL_PROGRESS:  22.22%

🎒 BACKEND REPORTED:  25.00%

🚧 UPSCAYL_PROGRESS:  25.00%

🎒 BACKEND REPORTED:  27.78%

🚧 UPSCAYL_PROGRESS:  27.78%

🎒 BACKEND REPORTED:  30.56%

🚧 UPSCAYL_PROGRESS:  30.56%

🎒 BACKEND REPORTED:  33.33%

🚧 UPSCAYL_PROGRESS:  33.33%

🎒 BACKEND REPORTED:  36.11%

🚧 UPSCAYL_PROGRESS:  36.11%

🎒 BACKEND REPORTED:  38.89%

🚧 UPSCAYL_PROGRESS:  38.89%

🎒 BACKEND REPORTED:  41.67%

🚧 UPSCAYL_PROGRESS:  41.67%

🎒 BACKEND REPORTED:  44.44%

🚧 UPSCAYL_PROGRESS:  44.44%

🎒 BACKEND REPORTED:  47.22%

🚧 UPSCAYL_PROGRESS:  47.22%

🎒 BACKEND REPORTED:  50.00%

🚧 UPSCAYL_PROGRESS:  50.00%

🎒 BACKEND REPORTED:  52.78%

🚧 UPSCAYL_PROGRESS:  52.78%

🎒 BACKEND REPORTED:  55.56%

🚧 UPSCAYL_PROGRESS:  55.56%

🎒 BACKEND REPORTED:  58.33%

🚧 UPSCAYL_PROGRESS:  58.33%

🎒 BACKEND REPORTED:  61.11%

🚧 UPSCAYL_PROGRESS:  61.11%

🎒 BACKEND REPORTED:  63.89%

🚧 UPSCAYL_PROGRESS:  63.89%

🎒 BACKEND REPORTED:  66.67%

🚧 UPSCAYL_PROGRESS:  66.67%

🎒 BACKEND REPORTED:  69.44%

🚧 UPSCAYL_PROGRESS:  69.44%

🎒 BACKEND REPORTED:  72.22%

🚧 UPSCAYL_PROGRESS:  72.22%

🎒 BACKEND REPORTED:  75.00%

🚧 UPSCAYL_PROGRESS:  75.00%

🎒 BACKEND REPORTED:  77.78%

🚧 UPSCAYL_PROGRESS:  77.78%

🎒 BACKEND REPORTED:  80.56%

🚧 UPSCAYL_PROGRESS:  80.56%

🎒 BACKEND REPORTED:  83.33%

🚧 UPSCAYL_PROGRESS:  83.33%

🎒 BACKEND REPORTED:  86.11%

🚧 UPSCAYL_PROGRESS:  86.11%

🎒 BACKEND REPORTED:  88.89%

🚧 UPSCAYL_PROGRESS:  88.89%

🎒 BACKEND REPORTED:  91.67%

🚧 UPSCAYL_PROGRESS:  91.67%

🎒 BACKEND REPORTED:  94.44%

🚧 UPSCAYL_PROGRESS:  94.44%

🎒 BACKEND REPORTED:  97.22%

🚧 UPSCAYL_PROGRESS:  97.22%

🎒 BACKEND REPORTED:  100.00

🙌 Upscayled Successfully!

🚧 UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  C:\Users\user\Desktop\girl on the beach 2_upscayl_4x_realesrgan-x4plus-anime.png
💯 UPSCAYL_DONE:  C:\Users\user\Desktop\girl on the beach 2_upscayl_4x_realesrgan-x4plus-anime.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string

**Comment by aaronliu0130** [comment]
What? Please file with the bug report template and explain.
