### ISSUE TITLE
Removing the auto-update feature.

### ISSUE THREAD

**Issue by Sue1133** [upscayl/upscayl#963]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Could you remove the auto-update feature?

### Related Problem(s)

It's really annoying. I can't use the old version with the internet. Why did you even do that? It just downloads the new version automatically. Do you think that's okay? Is it possible to remove all network features? This program doesn't need them.

p.s. no negativity, just this feature is terrible

**Comment by NayamAmarshe** [comment]
> The best way to use older versions would be to disable internet connection for Upscayl using your system Firewall. You can read more here: https://www.makeuseof.com/prevent-apps-accessing-internet/
