### ISSUE TITLE
Replace Original File

### ISSUE THREAD

**Issue by k3ltfalcon** [upscayl/upscayl#967]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

I’ve been upscaling a manga with many volumes, each containing several chapters. When I use Upscayl’s desktop app, I rely on batch mode, but I have to run it for each individual chapter. 
I’d like to request a feature update that allows users to drag an entire manga folder (containing all volumes and their respective chapters) into the software. The upscaled files would then automatically replace the original ones, similar to how XnConvert handles batch processing.

**Comment by aaronliu0130** [comment]
For subfolders, see #283.

Replacing already output files is already available via a toggle in settings.

![⅓ compulsory rickrolls are issued for ⅓ duplicates of other issues and the FAQ](https://github.com/upscayl/upscayl/assets/11874211/1b6870c9-bc20-419b-8f08-e4f77db239e5)

**Comment by k3ltfalcon** [comment]
> For subfolders, see #283.
As I understand, this feature isn't available yet, right?

> Replacing output files is already available via a toggle in settings.
I can't find an option to replace output files in the settings. Could you be more specific? (I'm using version 2.11.5).
![image](https://github.com/user-attachments/assets/647cb120-ac71-4289-b61c-61acfa2f728e)

**Comment by aaronliu0130** [comment]
@k3ltfalcon Sorry for the late reply. Right below the part of the settings you put into the screenshot is "overwrite previous upscayl".

**Comment by k3ltfalcon** [comment]
No, this feature will overwrite the previous Upscayl version's files, not the original files. That's not the feature I want.

**Comment by aaronliu0130** [comment]
Okay, I think I get what you mean now. Let's track this in #966.

**Comment by k3ltfalcon** [comment]
> Okay, I think I get what you mean now. Let's track this in #966.

Thank you. I will track it
