### ISSUE TITLE
程序根本无法打开

### ISSUE THREAD

**Issue by StevenGuo1145** [upscayl/upscayl#968]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

大部分运行库都装了，不知道是不是显卡的问题，双击打开之后转圈然后没反应，没报错

### To Reproduce

I Don't Know

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

Windows 11 23H2

### GPU Name

RTX4070laptop

### Logs

```sh
There's no logs.I can't even launch
```

**Comment by aaronliu0130** [comment]
能不能发个录屏（亲？），用的是从我们这个网站下载的程序吗

**Comment by StevenGuo1145** [comment]
我视频太大上传不了
程序就是GitHub下的

**Comment by StevenGuo1145** [comment]
Uploading 无标题视频——使用Clipchamp制作.mp4…

**Comment by StevenGuo1145** [comment]
https://github.com/user-attachments/assets/ec34f687-6a34-4ef9-bc91-d5e2be32e781

**Comment by aaronliu0130** [comment]
命令行上启动会怎么样

**Comment by StevenGuo1145** [comment]
start命令吗
也没反应

**Comment by StevenGuo1145** [comment]
https://github.com/user-attachments/assets/4a56b50b-aa21-4ff0-8c4d-efb22a517e5d

**Comment by StevenGuo1145** [comment]
乱码

**Comment by aaronliu0130** [comment]
D是个网络盘吗？如果不是的话，试试拖拽之后加`  --in-process-gpu`

**Comment by StevenGuo1145** [comment]
这样可以打开了，但是怎么操作可以让他以后都可以正常打开呢
是独显直连的问题吗

**Comment by aaronliu0130** [comment]
编辑下阿普的快捷方式，把第三行这么改
![](https://github.com/user-attachments/assets/2fccaca4-978b-4dc9-983c-00bac807de00)
从搜索运行的快捷方式可以这样找到其路径
![](https://github.com/user-attachments/assets/0fd0b1ae-ecaa-4df9-8a23-acea62e108a3)
吾个人的解决方法是用endeavourOS版的Arch Linux哦亲
