### ISSUE TITLE
Add OS to your release files

### ISSUE THREAD

**Issue by oxou** [upscayl/upscayl#97]
`upscayl-1.5.5.zip` may be mistaken for a Windows build whereas it's actually a Linux build.

Something like `upscayl-1.5.5-linux.zip`, `upscayl-1.5.5-windows.zip`, etc. would make more sense and save a lot of time for people with slow connections.

**Comment by NayamAmarshe** [comment]
The zip is automatically added by electron builder after CI/CD, I'm not even sure if there's a way to rename the builds.
