### ISSUE TITLE
Uspcaling Image with a number bigger than 29999 

### ISSUE THREAD

**Issue by DJboutit** [upscayl/upscayl#972]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

When you try to upscale a image to like 10X+ size is 37800x23000 or 23000x37800 or 50000x28000 it will try to run the image when it get to post processing it will fail every single time you get this error message Error: Couldn't write the image C:\Users\

### To Reproduce

Try to uspcale any image with a size of bigger than 29999 the image will fail every time 

### Upscayl Version (or commit hash)

2.11.5 

### Platform

Windows

### OS Version

Windows 11 

### GPU Name

4060 TI 16gb version

### Expected Behavior

Image upscale should be able to get to post processing and complete the whole process 

### Logs

```sh
🎒 BACKEND REPORTED:  🚨 Error: Couldn't write the image C:\Users\Desktop\3840x2566 254f3aa34a0d4dcba76f50275c88894b VFNNrtcT_upscayl_16x_BSRGAN.jpg

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  🚨 Error: Couldn't write the image C:\Users\Desktop\3840x2566 254f3aa34a0d4dcba76f50275c88894b VFNNrtcT_upscayl_16x_BSRGAN.jpg

⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"BSRGAN","value":"BSRGAN"}
⚙️ Setting gpuId to empty string
```

**Comment by Darkidea-ai** [comment]
Exactly the same problem here, height or width greater than 29999 = crash 🎒 BACKEND REPORTED:  🚨 Error: Couldn't write the image C:.....

**Comment by DJboutit** [comment]
Why have bigger than 8x upscale if 35% of the time you can not get use it because your image will be to big??

**Comment by NayamAmarshe** [comment]
We've already discussed this before. Crazy sizes like these aren't supported by Upscayl and as mentioned already, anything above 4X is just a stretched image, it's not upscaling.

**Comment by DJboutit** [comment]
Might be a good idea to remove anything bigger than 8x upscaling and this problem will go away.

**Comment by NayamAmarshe** [comment]
> Might be a good idea to remove anything bigger than 8x upscaling and this problem will go away.

Why? If I have smaller images, I can still use those options.

**Comment by aaronliu0130** [comment]
Perhaps related to #493?

**Comment by NayamAmarshe** [comment]
Yes, this is #493
