### ISSUE TITLE
Time completion

### ISSUE THREAD

**Issue by Iliya5digital** [upscayl/upscayl#977]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

It calculates the time it takes to perform image scaling, i.e. it will show the time spent on image scaling and the time spent on batch scaling too.

**Comment by aaronliu0130** [comment]
tracked in/duplicate of #1002
