### ISSUE TITLE
Commercial use of the Fast Real-ESRGAN model

### ISSUE THREAD

**Issue by trionalnovanza** [upscayl/upscayl#982]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

I am Trional, a free Upscayl Desktop user. I want to ask, is the FAST-Real-ESRGAN model available for commercial use for free like Real-ESRGAN?

because the FAQ doesn't explain FAST-Real-ESRGAN, I often use that model

Thank You.

@dosu.
### Screenshots
<img width="451" alt="ASFSAF" src="https://github.com/user-attachments/assets/4f036922-08df-41ed-b0ea-0ce2230857d5">

_No response_

**Comment by NayamAmarshe** [comment]
Yes, it is :) Since it's REAL-ESRGAN. I'll make things more clear in the FAQ :)

**Comment by trionalnovanza** [comment]
> Yes, it is :) Since it's REAL-ESRGAN. I'll make things more clear in the FAQ :)

Thank you, now it's clear, I understand
