### ISSUE TITLE
vkCreateInstance failed -9 🚨 Error: Invalid GPU Device

### ISSUE THREAD

**Issue by 11jouske11** [upscayl/upscayl#988]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

i just downloaded upscayl and i got this what is this?
These are my logs btw

⚙️ Setting saveImageAs to png
🔀 Setting model to realesrgan-x4plus
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🖼 Selected Image Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
📁 Selected Image Directory:  C:\Users\elvis\OneDrive\Documents\PPSSPP
🖼 imagePath:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","fileNameWithExt":"4-o.jpg","outputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","outFile":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o_upscayl_4x_realesrgan-x4plus.png","fileName":"4-o","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg,-o,C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o_upscayl_4x_realesrgan-x4plus.png,-m,D:\scale\Upscayl\resources\models,-n,realesrgan-x4plus,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","args":["D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o.jpg","-o","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o_upscayl_4x_realesrgan-x4plus.png","-m","D:\\scale\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkCreateInstance failed -9

🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🎒 BACKEND REPORTED:  vkCreateInstance failed -9
vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9
vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\5-o.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\5-o.jpg
🖼 Selected Image Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\5-o.jpg
📁 Selected Image Directory:  C:\Users\elvis\OneDrive\Documents\PPSSPP
🖼 imagePath:  C:\Users\elvis\OneDrive\Documents\PPSSPP\5-o.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","fileNameWithExt":"5-o.jpg","outputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","outFile":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\5-o_upscayl_2x_realesrgan-x4plus.png","fileName":"5-o","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\elvis\OneDrive\Documents\PPSSPP\5-o.jpg,-o,C:\Users\elvis\OneDrive\Documents\PPSSPP\5-o_upscayl_2x_realesrgan-x4plus.png,-s,2,-m,D:\scale\Upscayl\resources\models,-n,realesrgan-x4plus,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","args":["D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o.jpg","-o","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o_upscayl_4x_realesrgan-x4plus.png","-m","D:\\scale\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkCreateInstance failed -9

🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🎒 BACKEND REPORTED:  vkCreateInstance failed -9
vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9
vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔀 Model changed:  realesrgan-x4plus-anime
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting Upscaled Image Path
🚫 No valid image selected
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🖼 Selected Image Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
📁 Selected Image Directory:  C:\Users\elvis\OneDrive\Documents\PPSSPP
🖼 imagePath:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus-anime","gpuId":null,"saveImageAs":"png","inputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","fileNameWithExt":"4-o.jpg","outputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","outFile":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o_upscayl_2x_realesrgan-x4plus-anime.png","fileName":"4-o","scale":"2","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg,-o,C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o_upscayl_2x_realesrgan-x4plus-anime.png,-s,2,-m,D:\scale\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","args":["D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o.jpg","-o","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o_upscayl_4x_realesrgan-x4plus.png","-m","D:\\scale\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkCreateInstance failed -9

🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🎒 BACKEND REPORTED:  vkCreateInstance failed -9

🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🎒 BACKEND REPORTED:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/jpeg","filePath":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o.jpg","extension":"jpg"}
🖼 Setting image path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🗂 Setting output path:  C:\Users\elvis\OneDrive\Documents\PPSSPP
🖼 imagePath:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🔤 Extension:  jpg
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus-anime","gpuId":null,"saveImageAs":"jpg","inputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","fileNameWithExt":"4-o.jpg","outputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","outFile":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o_upscayl_1x_realesrgan-x4plus-anime.jpg","fileName":"4-o","scale":"1","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg,-o,C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o_upscayl_1x_realesrgan-x4plus-anime.jpg,-s,1,-m,D:\scale\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","args":["D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o.jpg","-o","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o_upscayl_4x_realesrgan-x4plus.png","-m","D:\\scale\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkCreateInstance failed -9

🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🎒 BACKEND REPORTED:  vkCreateInstance failed -9
vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9
vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP
🖼 Selected Folder Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\elvis\OneDrive\Documents\PPSSPP,-o,C:\Users\elvis\OneDrive\Documents\PPSSPP\upscayl_jpg_realesrgan-x4plus-anime_1x,-s,1,-m,D:\scale\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-f,jpg,-c,0
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🚧 FOLDER_UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🔄 Resetting image paths
🚧 FOLDER_UPSCAYL_PROGRESS:  vkCreateInstance failed -9
vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🎒 BACKEND REPORTED:  ❌  vkCreateInstance failed -9
vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🎒 BACKEND REPORTED:  💯 Done upscaling
💯 FOLDER_UPSCAYL_DONE:  C:\Users\elvis\OneDrive\Documents\PPSSPP\upscayl_jpg_realesrgan-x4plus-anime_1x
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage:  Intel(R) HD Graphics 4400
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🖼 Selected Image Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
📁 Selected Image Directory:  C:\Users\elvis\OneDrive\Documents\PPSSPP
🖼 imagePath:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus-anime","gpuId":"Intel(R) HD Graphics 4400","saveImageAs":"jpg","inputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","fileNameWithExt":"4-o.jpg","outputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","outFile":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o_upscayl_1x_realesrgan-x4plus-anime.jpg","fileName":"4-o","scale":"1","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg,-o,C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o_upscayl_1x_realesrgan-x4plus-anime.jpg,-s,1,-m,D:\scale\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-g,Intel(R) HD Graphics 4400,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","args":["D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o.jpg","-o","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o_upscayl_4x_realesrgan-x4plus.png","-m","D:\\scale\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkCreateInstance failed -9

🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🎒 BACKEND REPORTED:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\10-o.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\10-o.jpg
🖼 Selected Image Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\10-o.jpg
📁 Selected Image Directory:  C:\Users\elvis\OneDrive\Documents\PPSSPP
🖼 imagePath:  C:\Users\elvis\OneDrive\Documents\PPSSPP\10-o.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus-anime","gpuId":"Intel(R) HD Graphics 4400","saveImageAs":"jpg","inputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","fileNameWithExt":"10-o.jpg","outputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","outFile":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\10-o_upscayl_1x_realesrgan-x4plus-anime.jpg","fileName":"10-o","scale":"1","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\elvis\OneDrive\Documents\PPSSPP\10-o.jpg,-o,C:\Users\elvis\OneDrive\Documents\PPSSPP\10-o_upscayl_1x_realesrgan-x4plus-anime.jpg,-s,1,-m,D:\scale\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-g,Intel(R) HD Graphics 4400,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","args":["D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o.jpg","-o","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o_upscayl_4x_realesrgan-x4plus.png","-m","D:\\scale\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkCreateInstance failed -9

🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🎒 BACKEND REPORTED:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🖼 Selected Image Path:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
📁 Selected Image Directory:  C:\Users\elvis\OneDrive\Documents\PPSSPP
🖼 imagePath:  C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus-anime","gpuId":"Intel(R) HD Graphics 4400","saveImageAs":"jpg","inputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","fileNameWithExt":"4-o.jpg","outputDir":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP","outFile":"C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o_upscayl_1x_realesrgan-x4plus-anime.jpg","fileName":"4-o","scale":"1","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o.jpg,-o,C:\Users\elvis\OneDrive\Documents\PPSSPP\4-o_upscayl_1x_realesrgan-x4plus-anime.jpg,-s,1,-m,D:\scale\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-g,Intel(R) HD Graphics 4400,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","args":["D:\\scale\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o.jpg","-o","C:\\Users\\elvis\\OneDrive\\Documents\\PPSSPP\\4-o_upscayl_4x_realesrgan-x4plus.png","-m","D:\\scale\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkCreateInstance failed -9

🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🎒 BACKEND REPORTED:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🎒 BACKEND REPORTED:  🚫 File Operation Cancelled
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Getting gpuId from localStorage:  Intel(R) HD Graphics 4400

**Comment by aaronliu0130** [comment]
Please use the bug report template, which includes troubleshooting.
