### ISSUE TITLE
My Upsacyl Suddenly Stopped working

### ISSUE THREAD

**Issue by Hashintha7** [upscayl/upscayl#989]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

My Pc specifications are

Device name	DESKTOP-PDE0AJ2
Processor	AMD Ryzen 5 5600G with Radeon Graphics            3.90 GHz
Installed RAM	24.0 GB (19.9 GB usable)

![Screenshot (251)](https://github.com/user-attachments/assets/06d82d6c-0007-4fba-8c80-5d64b4437c7f)

Upscayl software was working untill today..then suddenly stopped working..I do everything..

### To Reproduce

I can't understand this.I don't know about coding or anything sorry.;-(
I just need to upsacyl my images..

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

Windows 10,Version 22H2

### GPU Name

AMD Radeon(TM) Graphics

### Screenshots

![Screenshot (250)](https://github.com/user-attachments/assets/f93c9f3c-ee85-4d25-8a60-5afd6b7c2ec5)
![Screenshot (251)](https://github.com/user-attachments/assets/c8469dbf-7eff-4aea-bae8-83d4c709778c)

### Logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
```

**Comment by Hashintha7** [comment]
Thank you git hub..I Solve the probles

I just have to change Select Model to - General photo (Fast real Esragan)
![Uploading Screenshot (252).png…]()

**Comment by aaronliu0130** [comment]
let's track in/duplicate of #984
