### ISSUE TITLE
Dedicated GPU not working/not recognized as GPU. Using integrated GPU instead.

### ISSUE THREAD

**Issue by qqmarcus** [upscayl/upscayl#991]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

I have a laptop with a dedicated GPU (NVIDIA RTX A3000 12GB Laptop GPU) and an integrated GPU (Intel(R) Iris(R) Xe Graphics). The program works fine using the integrated GPU, but I want it to use the dedicated GPU for better performance. Upscayl is set to high performance in windows graphics settings/set to use the dedicated GPU, but will still use the integrated GPU. Setting it to use GPU 1 in settings causes an error. Disabling integrated GPU in device manager also causes an error. Logs below are for when integrated GPU is disabled.

### To Reproduce

1. Have a laptop with the GPUs that I mentioned above.
2. Try to upscale an image using the dedicated GPU.
3. Get an error

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

Windows 11 23H2

### GPU Name

RTX A3000

### Expected Behavior

It should have used my dedicated GPU.

### Screenshots

![trouble](https://github.com/user-attachments/assets/649757cb-bd58-48f2-9dad-db2fd3fe1889)

### Logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  1
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  1
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\masll\Downloads\Wallpapers\away-1k.jpg
🖼 Selected Image Path:  C:\Users\masll\Downloads\Wallpapers\away-1k.jpg
📁 Selected Image Directory:  C:\Users\masll\Downloads\Wallpapers
🖼 imagePath:  C:\Users\masll\Downloads\Wallpapers\away-1k.jpg
🔤 Extension:  jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\masll\Downloads\Wallpapers\away-1k.jpg
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":null,"saveImageAs":"png","inputDir":"C:\\Users\\masll\\Downloads\\Wallpapers","fileNameWithExt":"away-1k.jpg","outputDir":"C:\\Users\\masll\\Downloads\\Wallpapers","outFile":"C:\\Users\\masll\\Downloads\\Wallpapers\\away-1k_upscayl_2560px_realesrgan-x4plus.png","fileName":"away-1k","scale":"2","compression":"0","customWidth":"2560","useCustomWidth":true,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\masll\Downloads\Wallpapers\away-1k.jpg,-o,C:\Users\masll\Downloads\Wallpapers\away-1k_upscayl_2560px_realesrgan-x4plus.png,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus,-f,png,-w,2560,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\masll\\Downloads\\Wallpapers\\away-1k.jpg","-o","C:\\Users\\masll\\Downloads\\Wallpapers\\away-1k_upscayl_2560px_realesrgan-x4plus.png","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus","-f","png","-w","2560","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkCreateInstance failed -9

🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🎒 BACKEND REPORTED:  vkCreateInstance failed -9

🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9

🎒 BACKEND REPORTED:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
```

**Comment by qqmarcus** [comment]
1. Settings tab only shows my integrated GPU as available so this is not helpful.
2. Switchable graphics isn't a thing on my laptop.
3. RTX A3000 is vulkan compatible.
4. Upscayl is set to performance mode.

**Comment by aaronliu0130** [comment]
We know that it should be compatible. However, only drivers can facilitate connections between vulkan capabilities and the software.

**Comment by DheerajParmar22** [comment]
Do we have any solutions for make it run on CPU only, as I am upscaling the single image at a time. What can be the best way to move it to CPU? If I can use any other model, do let me know the model names. Thanks!

**Comment by aaronliu0130** [comment]
As mentioned in the FAQ, you can check out #580.

**Comment by cbnsingram** [comment]
So, I was also getting the invalid GPU Device error with my RTX-3080 Ti.  The following is what I did. Steps 5-7 seem nonsensical to me, but Upscayl is now working with my GPU and very quickly. 

01. Uninstall/reinstall - **still errors**
02. Specified GPU ID, closed and opened Upscayl - **still errors**
03. Tried FAQ #580 CPU usage pegged at 100% and image upscaling was **CRAWLING slow**.
04. Shut down Upscayl again.
05. Deleted the C:\Program Files\Upscayl\resources\bin\vulcan-1.dll file that was added to the directory in the #580 solution
06. Then renamed C:\Program Files\Upscayl\vulcan-1.dll file to vulcan-1-old.dll 
07. Made a copy of C:\Program Files\Upscayl\vk_swiftshader.dll file and renamed the copy to vulcan-1.dll
08. **Still getting GPU error**
09. Closed Upscayl
10. Deleted C:\Program Files\Upscayl\vulcan-1.dll file and renamed vulcan-1-old.dll to vulcan-1.dll
11. Opened Upscayl and it now works great.

Maybe someone who is more atuned to the project can use the above steps to figure out a more elegant fix.  I suspect at least one step could have been skipped, but my install is working now so I'll stop playing with this issue.  

I hope this helps someon. Peace out.
