### ISSUE TITLE
Working on Intel UHD 730

### ISSUE THREAD

**Issue by md-rifatkhan** [upscayl/upscayl#994]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Issue

**Compatibility List**
Working on Intel UHD 730, 

Created the issue for improve Compatibility List document,

**Comment by John-ckck** [comment]
I can't install on my windows 7 it says library kernel32.dll
