### ISSUE TITLE
it worked before and nothing works anymore "error: vkCreateInstance failed -9 🚨 Error: Invalid GPU Device"

### ISSUE THREAD

**Issue by tdsiena** [upscayl/upscayl#996]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

i have an error: vkCreateInstance failed -9 🚨 Error: Invalid GPU Device

and I don't understand why, 2.11.5 worked because I tried it, the only difference is the NVIDIA GPU update, I tried everything in the "troubleshoot" and it still doesn't work, even uninstal install, deleting all the old folders to avoid bugs as much as possible

I give the image I launch upscale and the image disappears and I have the empty screen with written "select an image to upscale" and the notification: vkCreateInstance failed -9 🚨 Error: Invalid GPU Device

### To Reproduce

give the image I launch upscale and the image disappears and I have the empty screen with written "select an image to upscale" and the notification: vkCreateInstance failed -9 🚨 Error: Invalid GPU Device

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

windows11 21H2

### GPU Name

Nvidia msi geforce RTX 3070 ventus 2x 8GB GDDR6

### Logs

```sh
vkCreateInstance failed -9🚨 Error: Invalid GPU Device
```

**Comment by abhishek-gaonkar** [comment]
Hi @tdsiena
Can you post screenshots, your NVIDIA driver version and complete logs please, not just the error?
