### ISSUE TITLE
after upscaled it removes images details as you can see in screenshot 

### ISSUE THREAD

**Issue by Samthapa76** [upscayl/upscayl#998]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

no effect normal https://imgur.com/259npKj
with upscaled but no details https://imgur.com/DcEKwoP 
this is original image you can try https://imgur.com/XXWVAV2

### Related Problem(s)

this is awesome app it should be perfect

**Comment by aaronliu0130** [comment]
That's unfortunately just a fact of `l`-AI-fe. See #366, all AI models do is make a best guess. You could try applying different models.

**Comment by aaronliu0130** [comment]
see also #849
