### ISSUE TITLE
I cannot use upscaller 2.11.5

### ISSUE THREAD

**Issue by akhreen** [upscayl/upscayl#999]
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

vkCreateInstance failed -9
🚨 Error: Invalid GPU Device

### To Reproduce

![image](https://github.com/user-attachments/assets/62f55143-1e69-487f-8bb4-4c4686cad228)

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

windows 10, cori 5 6 gen

### GPU Name

🚨 Error: Invalid GPU Device

### Expected Behavior

![image](https://github.com/user-attachments/assets/b8067721-949a-493d-bb48-ae11f24b49c0)

### Screenshots

![image](https://github.com/user-attachments/assets/3c145c00-bf13-4024-b30c-0d927cbad47f)

### Logs

```sh
vkCreateInstance failed -9
🚨 Error: Invalid GPU Device
```

**Comment by akhreen** [comment]
Please help me to use this app

**Comment by aaronliu0130** [comment]
Please fill out your GPU name.

**Comment by aaronliu0130** [comment]
That's not the name of your GPU. I suspect that you're using a CPU, all of which are unsupported unless you use the slow #580 workaround

**Comment by NayamAmarshe** [comment]
v2.15 should show your GPU in the settings tab.
